# stardustdescends_ep01.gd - 星尘降临篇第1话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep01_script()

func play_script():
	pass

func stardustdescends_ep01_script():
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Prisoner.png")
	await novel_interface.show_text_only("有这样一个广为人知的经典故事……")
	await novel_interface.show_text_only("某位富翁的财物被盗，警察在一所两人人合租的房间内搜到赃物，却没有足够证据指控二人有罪。")
	await novel_interface.show_text_only("于是警方将两名嫌犯分开囚禁，并向他们提供了这样的选择——")
	await novel_interface.show_text_only("如果一人招供而另一方沉默，招供的人获释，而沉默的人将被判监10年；")
	await novel_interface.show_text_only("如果双方都保持沉默，则二人都被判监半年；但如果二人都招供，则二人都被判监5年")
	await novel_interface.show_text_only("对故事中的两人而言，他们永远无法达成总体利益最大的结果——")
	await novel_interface.show_text_only("因为无论对方沉默还是认罪，自己认罪的结果总比沉默要好，招供成为了支配性策略。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("有些经济学家提出，在现实中双方可以通过反复博弈让对方认识到，合作才是最优策略。")
	novel_interface.show_background("res://assets/images/bg/Shot/storyBGWar.png")
	await novel_interface.show_text_only("但有些博弈并没有重来的余地——")
	await novel_interface.show_text_only("陷入猜疑的双方永远无法突破这『囚徒困境』…")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("新丰洲城郊。")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Manorgate.png")
	await novel_interface.show_text_only("一辆加长轿车缓缓停在庄园门口，打扮精致的少女有些不自在的从车后座钻了出来。")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("这、这种地方——！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这是一座奢华的欧式庄园——黄铜装饰的大门、精致传神的雕塑，连草坪和灌木都修剪得一丝不苟。")
	await novel_interface.show_text_only("我惊叹着新丰洲居然有这种地方，耳机中传来了莉琉的声音。")
	await novel_interface.show_dialog("别一直东张西望，你的口水都快要流出来了~", "莉琉")
	novel_interface.show_character("ren_full","shy")
	await novel_interface.show_dialog("知、知道啦——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我整理一下仪容，结果刚踏上大门的阶梯就差点摔倒。")
	novel_interface.show_character("ren_full","shy")
	await novel_interface.show_dialog("这鞋跟好高啊……而且礼服的裙子怎么这么短！！", "小怜")
	novel_interface.change_expression("shy_right")
	await novel_interface.show_dialog("（腰还稍稍有点紧，是不是最近吃多了……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("挺起胸，保持仪态，别走得像只龙虾一样。", "莉琉")
	await novel_interface.show_dialog("你又不是第一天做女孩子了~", "莉琉")
	await novel_interface.show_text_only("你好烦——！！")
	await novel_interface.show_text_only("在我快要走到别墅门口时，侍应生打开了大门并彬彬有礼得向我鞠躬。")
	await novel_interface.show_text_only("我勉强挤出一个微笑，同时祈祷自己上台阶的时候别再摔倒……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我小心翼翼的走进别墅，通过一套繁复的安检设备后，昂贵的气息扑面而来——")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_VillaHall.png")
	await novel_interface.show_text_only("这里的前厅并不算大，却处处都透出精致考究的质感，即使是角落的台灯都散发着古董特有的珠光。")
	await novel_interface.show_text_only("我脑内反复默念着昨天仪态课上的要点——挺胸收腹、脖子不要前倾、保持微笑、别东张西望……")
	novel_interface.show_character("ren_full","uneasy")
	await novel_interface.show_dialog("（还有千万别打碎任何东西！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一走进大厅，那些穿着考究三三两两聚在一起窃窃私语的来宾，全都将目光投到我的身上。")
	await novel_interface.show_dialog("哇——小怜好漂亮！", "安妮")
	await novel_interface.show_text_only("在监控中看到我进门，安妮虽刻意压着音量，但是声音中却依然难掩激动之情。")
	novel_interface.show_character("ren_full","blush")
	await novel_interface.show_dialog("（这身确实……还挺好看的……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("但是绝不能承认！我可是男生啊！！")
	await novel_interface.show_dialog("到场的主宾都是各个学园都市的明星权贵，主要经营会员制赌场，由元老院特批牌照。", "莉琉")
	await novel_interface.show_dialog("不过，这座庄园的主业是违禁品和情报交易，还充当着新丰洲最大的地下担保中介。", "莉琉")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("所以，你是想收集证据查抄这里吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一边假装向远处的空气微笑致意，一边小声的说道。")
	await novel_interface.show_dialog("我有那么不解风情吗？\n而且我想要查抄的话需要证据吗？", "莉琉")
	await novel_interface.show_text_only("莉琉不屑的回道。")
	await novel_interface.show_dialog("一会你要先吸引目标的注意力，安妮会配合你。", "莉琉")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("这里的人基本都有四五十岁吧，我一个高中生出现在这里不会引起怀疑吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("从你进入庄园大门的那一刻，庄园安保系统就给你拍照扫描过。", "莉琉")
	await novel_interface.show_dialog("不过系统只会显示你是一个平时在女仆咖啡打工的女高中生而已。", "莉琉")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("诶——？\n（那不是完全露馅了吗？！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我吓得僵在原地，不安观察着周围人的目光。")
	await novel_interface.show_dialog("偶尔也会有你这种情况啦，有些客人还很喜欢呢。", "莉琉")
	await novel_interface.show_text_only("哪种情况啊！！")
	await novel_interface.show_dialog("目标坐在楼梯拐角的椅子上，看起来有些紧张。", "安妮")
	await novel_interface.show_text_only("我若无其事的走向可以观察到目标的视角，用余光扫过去——")
	novel_interface.show_character("shi","angry")
	await novel_interface.show_dialog("该死……该死该死！", "？？？")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那个头发蓬乱、满脸胡茬、着装与这里格格不入的中年男人正抱着一只皮包自言自语的碎碎念。")
	await novel_interface.show_text_only("老旧的外套、白衬衫外面套着件土黄色的毛衣、还围着一条绿色的围巾……")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("那个就是施教授？\n（简直土爆了！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("额……好像是的……", "安妮")
	novel_interface.show_character("ren_full","smile")
	await novel_interface.show_dialog("好的~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不知为何，我今天对自己的样子莫名有自信。")
	await novel_interface.show_text_only("我走到他面前，假装在欣赏二楼的彩绘玻璃，扭着腰来回踱步，然而那家伙都没正眼看我。")
	await novel_interface.show_text_only("我有些不甘，偷偷拉了拉胸垫，又凑近一些装作想看墙上的鹿头装饰品。")
	await novel_interface.show_text_only("那土包子居然嫌弃的把头扭开了！！")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("（喂！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("啊请问……这位小姐——", "男性宾客")
	await novel_interface.show_text_only("一个身着考究礼服，戴着领结的大叔凑了过来。")
	await novel_interface.show_dialog("我在纽摩利达斯经营一家传媒公司……请问有没有兴趣聊聊？", "男性宾客")
	await novel_interface.show_text_only("那个大叔一边搓着手一边笑盈盈的和我搭话。")
	novel_interface.show_character("ren_full","perspire1")
	await novel_interface.show_dialog("不、不好意思——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我赶忙摆摆手，假装肚子痛捂着腹部快步溜到拐角处，对着监控露出一副哭丧的表情。")
	await novel_interface.show_text_only("目标无动于衷，却吸引到了奇怪的家伙。")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("好像完全吸引不到那家伙的注意力啊……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("小怜的动作太僵硬啦……", "安妮")
	await novel_interface.show_dialog("看起来目标在等什么人，而且包里的东西也很可\n疑。", "莉琉")
	await novel_interface.show_dialog("小怜的手包里有透视设备，刚才扫描包内没有任何电子产品，只有大概二三十页的纸质文件。", "莉琉")
	await novel_interface.show_dialog("还真是个老古董……", "安妮")
	novel_interface.show_character("ren_full","normal2")
	await novel_interface.show_dialog("爱衣不是说过这东西能透过障碍给多页纸质文件拍照吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我拿着那个颇有分量的手包，精致的漆皮缝线背后塞满了战研部的小道具。")
	await novel_interface.show_text_only("最神奇的是内衬经过特殊处理后，居然能通过门口的安检。")
	await novel_interface.show_dialog("能同时拍多页文件的前提是在空间内均匀散布了金属粉末，让穿过每页纸的射线拉开强度层级。", "莉琉")
	await novel_interface.show_dialog("你包里有个能遥控爆破的金属粉末胶囊，但那页数太多了，要大力晃动才能均匀扩散开。", "莉琉")
	await novel_interface.show_dialog("胶囊爆开时是有声音的吧？而且那家伙一直像宝贝一样抱着那个包……", "安妮")
	await novel_interface.show_dialog("小怜不是有一个能炸开门锁的粘胶炸弹吗？", "莉琉")
	await novel_interface.show_dialog("那东西声音更大了！\n而且小怜要是穿成这样被抓住的话……", "安妮")
	await novel_interface.show_text_only("我想到刚才那个大叔色眯眯的目光，不禁抱住胸部打了个冷战。")
	novel_interface.show_character("ren_full","normal2")
	await novel_interface.show_dialog("说来……", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("那个大厅似乎是完全封闭的？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可能是为了保证私密性，连彩色玻璃都没有光透过来的样子。")
	novel_interface.show_character("ren_full","gratified")
	await novel_interface.show_dialog("对了，这里的电力系统可以控制吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哦？你好像想到了很大胆的方案嘛……", "莉琉")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("我回到大厅，尽量自然的溜达到施教授身边。")
	await novel_interface.show_text_only("这时楼梯另一侧的灯泡忽然发出强光，之后“啪”的一下爆掉了。")
	await novel_interface.show_text_only("趁他和众人扭头的功夫，我将一粒银色的胶囊从皮包缝隙中塞了进去。")
	await novel_interface.show_text_only("接着我假装检查高跟鞋半蹲下来，把那枚比硬币稍大的粘胶炸弹的爆破面贴在了他的椅子腿上。")
	novel_interface.show_character("ren_full","uneasy")
	await novel_interface.show_dialog("（准备好了！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我对着摄像头做了个OK的手势，并站到几步之外。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("随着天花板传来一声闷响，只听“砰”的一声，房间内所有光源同时熄灭。施教授发出一声惨叫。")
	await novel_interface.show_text_only("大家还没反应过来，就听到椅子的木腿被炸断和他摔在地上的声音。")
	await novel_interface.show_text_only("我赶忙摸黑凑过去，将包的扫描面对着地上他的大致方向，并暗自祈祷扫描装置能顺利工作。")
	await novel_interface.show_text_only("客人们开始骚动，侍应生立刻维持秩序，叫大家冷静一下，并说很快就会恢复供电。")
	await novel_interface.show_dialog("OK了~", "莉琉")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_VillaHall.png")
	await novel_interface.show_text_only("我长舒一口气，刚放下包包大厅就亮了起来。")
	novel_interface.show_character("ren_full","uneasy")
	await novel_interface.show_dialog("Yes！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一切顺利~")
	await novel_interface.show_dialog("咳咳，我说……", "？？？")
	await novel_interface.show_text_only("我身后传来一个女声。")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("我在二楼看你半天了，在这搔首弄姿的做什么呢？", "倪克斯")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("……倪克斯学姐？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她看着一旁坐在地上揉屁股的施教授。")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("这把椅子有一百三十多年的历史了，上次估价在两百万以上。", "倪克斯")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("诶——？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯扭过头来，暖昧得把手放在我的脸上。")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("打扮的还挺漂亮嘛——小学妹。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她有些冰凉的手指在我脸颊上滑动，微笑着轻轻取出我的骨传导耳机。")
	novel_interface.show_character("nyx_full","mock")
	await novel_interface.show_dialog("……那你打算，怎么赔偿呢？", "倪克斯")

	print("=== 星尘降临篇第1话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
