# stardustdescends_ep14.gd - 星尘降临篇第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep14_script()

func play_script():
	pass

func stardustdescends_ep14_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_ClusterBombs.png")
	await novel_interface.show_text_only("『蜂巢』——可对大范围区域内的人员与装备进行无差别毁伤的武器系统。")
	await novel_interface.show_text_only("手掌大小的无人机精简掉了繁冗的控制单元，每架只携带一枚自爆破片榴弹。")
	await novel_interface.show_text_only("通过AI识别系统分辨人员和装备，几十架无人机互相协同，能实现比集束炸弹更有效的范围打击。")
	await novel_interface.show_text_only("几年前马萨达曾向贝卡谷地投放了大量蜂巢，造成数千平民伤亡，遭到国际社会强烈谴责。")
	await novel_interface.show_text_only("而时至今日，马萨达依然没有签署任何废除此类武器的国际公约……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("轰——！！")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_StagingPost.png")
	await novel_interface.show_text_only("随着一声巨响，南侧山丘上的机枪突然爆炸，盖在上面的帆布被撕成了无数焦黑的碎片飘散开来……")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("怎么会有那种东西……\n车上不是医疗物资吗！？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","angry")
	await novel_interface.show_dialog("国防军瞒着他们私自加料了吧？", "艾米莉欧")
	await novel_interface.show_dialog("补给站里有辆吉普，薇拉你带她去。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","angry")
	await novel_interface.show_dialog("明白！", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("怎么回事……啊哎哎哎！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("怪力女不由分说的揽住了我的腰，把我夹在胳膊下面向补给站狂奔。")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("啊啊啊啊啊————！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她大跨步的冲下山坡，只要此时她手一滑，我就会像冰面上的小海豹一样甩飞出去。")
	await novel_interface.show_text_only("薇拉迅速冲进补给站，把我丢在了一堆沙袋上。")
	novel_interface.show_character("valkyrja","speak")
	await novel_interface.show_dialog("你在这躲好，我去帮艾米吸引火力！", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("留下这么一句，她便钻进吉普车疾驰而去……")
	await novel_interface.show_text_only("无人机群会按照既定程序摧毁周围一切未携带友军识别装置的车辆、武器和设备。")
	await novel_interface.show_text_only("而一辆高速行驶的汽车显然是最高优先级的打击目标。")
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_StagingPostF.png")
	await novel_interface.show_text_only("我瑟瑟发抖的缩在补给站角落的围垛后面，听着远处机枪扫射的声音和接二连三传来的爆炸声。")
	await novel_interface.show_text_only("每次爆炸都伴随着一阵噼噼啪啪的金属撞击砂石地面的碎响。")
	await novel_interface.show_text_only("那是随着榴弹的爆炸而飞溅四射的钢钉，对人有十分致命的杀伤力。")
	await novel_interface.show_text_only("然而机枪声音越来越稀疏，巨大的不祥感开始笼罩在我的心头——")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我把一块木板架在围垛顶上，像蘑菇一样捂着脑袋蹲在阴影里。")
	await novel_interface.show_text_only("据说二战期间，两军交战冲锋时，一旦己方的机枪声停止，就会对士气产生毁灭性的打击。")
	await novel_interface.show_text_only("今天我切身实地的体会了这句话的含义……")
	await novel_interface.show_text_only("随着最后一架机枪完全沉默，战场上的其他声音开始变得鲜明起来——")
	await novel_interface.show_text_only("那些盘旋的无人机发出的嗡嗡声，就像漫天飞舞的致命蜂群，根本无从分辨方位。")
	await novel_interface.show_text_only("它们似乎无处不在，就像在空中盘旋的死神，不知何时就会降临在我身边……")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("（她们两个，还好吗……）", "小怜")
	await novel_interface.show_dialog("（……等等，引擎的声音！？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_StagingPostF.png")
	await novel_interface.show_text_only("我探出半个脑袋，看到四周已经一片狼藉，远处堆放弹药的屋子也被大火包围。")
	await novel_interface.show_text_only("薇拉驾驶的吉普正从东侧的山坡朝补给站的方向冲来，身后卷起滚滚烟尘。")
	await novel_interface.show_text_only("十几架无人机紧随其后，它们速度并不算快，但也不至于被拉开多大距离。")
	await novel_interface.show_text_only("艾米莉欧从车顶钻出来架起一把M16，朝着机群断断续续的射击，但很难命中。")
	await novel_interface.show_text_only("很快她的子弹耗尽，索性将那把步枪朝车尾的方向丢了出去……")
	await novel_interface.show_text_only("只见一架无人机立刻冲向被丢出的枪械并自爆，其他的无人机则迅速拉升，避开了爆炸范围。")
	novel_interface.show_character("emilio","angry")
	await novel_interface.show_dialog("该死！", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那辆吉普开到补给站外的墙边减速，艾米莉欧避开无人机的视野，从车上翻下来并迅速抵在墙角。")
	await novel_interface.show_text_only("接着那辆车猛的打轮，扬起一阵尘土，径直向不远处另一个山丘开去。")
	await novel_interface.show_text_only("艾米莉欧则伏在墙角，等无人机群掠过头顶后利落的翻过围墙来到站内。")
	novel_interface.show_character("emilio","angry")
	await novel_interface.show_dialog("小怜！？", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("在、在这……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我压低声音回应，她一路顺着墙根摸进了我搭的木板下面。")
	novel_interface.show_character("ren_medical","sob")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("emilio","perspire",0.25)
	await novel_interface.show_dialog("你倒是会找地方……不过不用那么小声，那些东西听不到声音。", "艾米莉欧")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊，你受伤了？！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我看到艾米莉欧的上臂有几道划伤，鲜血顺着胳膊洇湿了军服，她却全然不在意的样子。")
	novel_interface.show_character("ren_medical","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("emilio","smile",0.25)
	await novel_interface.show_dialog("小意思，咱们得尽快回运兵车，那辆车的装甲应付这些东西应该绰绰有余。", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("此时运兵车在光学迷彩的掩护下正停在公路旁，距离补给站有两三百米的距离。")
	novel_interface.show_character("ren_medical","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("emilio","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你们没带友军识别装置吗！？\n那些无人机总不至于攻击自己人吧……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("不过这两位就是来劫持自家物资的，难道是马萨达的传统艺能？")
	novel_interface.show_character("emilio","speechless")
	await novel_interface.show_dialog("那些识别装置自带定位记录，我们出来干活当然留在城里了。", "艾米莉欧")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("咱们得快点！\n薇拉不知道还能拖多久……", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧拍了拍我的胳膊，向掩体外走去。")
	await novel_interface.show_text_only("我刚想跟上，却发现她定在了原地，声音略带颤抖的说道——")
	novel_interface.show_character("emilio","perspire")
	await novel_interface.show_dialog("小怜，快跑……", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我欠身抬头看，三架无人机正盘旋在补给站上空进行着360度的回转扫描。")
	await novel_interface.show_text_only("突然，其中一架无人机在朝向我们所在掩体的时候停了下来，同时机身上的红色光点开始闪烁……")
	novel_interface.show_character("emilio","angry")
	await novel_interface.show_dialog("快跑！！！", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧立刻拔出手枪对着天空射击，12发子弹瞬间倾泻而尽。")
	await novel_interface.show_text_only("一架无人机被击中悬臂，翻滚着坠向了补给站外。")
	await novel_interface.show_text_only("一架无人机直接在空中爆炸，大量金属碎屑插在了我们头顶的木板上。")
	await novel_interface.show_text_only("还有一架无人机，在漫天烟尘中拉着一道红线，径直朝我们冲了过来——")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("（完了！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("轰——！！")
	await novel_interface.show_text_only("榴弹爆裂的声浪伴随着炙热的气流，瞬间灌满掩体的狭小空间，掀飞了我们头顶的木板。")
	await novel_interface.show_text_only("空气中弥漫着刺鼻的糊味和浓浓的血液被蒸干后类似铁锈的味道。")
	await novel_interface.show_text_only("同时，大量金属破片被喷溅到补给站内……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_StagingPostF.png")
	await novel_interface.show_text_only("我在巨大的冲击下，身体失去平衡坐在了地上，同时感到小臂外侧传来一阵剧痛。")
	await novel_interface.show_text_only("不，比这更重要的是……")
	novel_interface.show_character("ren_medical","perspire1")
	await novel_interface.show_dialog("（我……还活着？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我摸了摸身体，除了小臂被划出一道口子，基本没受什么伤。")
	await novel_interface.show_text_only("而挡在我前方的艾米莉欧，手上似乎展开了一面用血液铸成的盾牌——")
	await novel_interface.show_text_only("盾牌挡住了爆炸的大部分冲击，之后便像烈日下的干冰般化为了暗红色的烟雾，消散在空气中。")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("你手上的是……？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("emilio","stare",0.25)
	await novel_interface.show_dialog("本来不想让你看见的……", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她甩了甩手腕，刚才被血液染红的军服袖子此时已经完全没有了血迹。")
	novel_interface.show_character("ren_medical","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("emilio","stare",0.25)
	await novel_interface.show_dialog("我和薇拉曾经意外接触过某种异质物，之后就有了这种奇怪的能力。", "艾米莉欧")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("我可以把自己的血液转化成强度超过钢铁的固体形态，不过血很快就会蒸发，实用度不大……", "艾米莉欧")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……可是很帅啊！！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speechless")
	await novel_interface.show_dialog("啊？", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她似乎对我的反应有些意外，回身看到我试图舔自己手肘的样子，不禁笑着摇了摇头。")
	await novel_interface.show_text_only("真的很疼啊！！\n刚才被金属片划到了……")
	novel_interface.show_character("emilio","speechless")
	await novel_interface.show_dialog("马萨达超过九成的人信教，无论在哪种宗教眼中这种操作血液的能力都是亵渎和诅咒吧？", "艾米莉欧")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("还是薇拉的能力实用些，虽然她力气本来就大……", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("薇拉的吉普车就在我们的视野右侧——")
	await novel_interface.show_text_only("此时怪力女已经把车停到了东侧的山丘上，后面十几架无人机大概还有十秒左右就要追上了……")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("熄火了？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("只见薇拉从驾驶舱出来走到车头，对着前保险杠深深的吸了一口气——")
	await novel_interface.show_text_only("随着“当”的一声震彻山谷的巨响，她把吉普车踹得横着飞了出去。")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("…………………………？？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("车像保龄球一样划着微妙的弧线冲向了刚刚爬升到山腰的无人机群，瞬间引发了一系列连锁爆炸……")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("……清理干净了！？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("emilio","stare",0.25)
	await novel_interface.show_dialog("别高兴的太早，你听。", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("是啊，那恼人的嗡嗡声并未消失……")
	await novel_interface.show_text_only("我转过头，看到了让人绝望的一幕——")
	await novel_interface.show_text_only("从我们补给站外的山脚下，又缓缓升起了三十多个小黑点……")
	await novel_interface.show_text_only("那群漆黑的幽灵在浓烟中盘旋，闪着红光，似乎要扼杀一切生存的意志。")
	await novel_interface.show_text_only("这就是『蜂巢』的可怕之处，像死神般如影随形无法摆脱，直到将全部目标彻底摧毁……")
	await novel_interface.show_text_only("艾米莉欧下意识的把我拉到身后——")
	novel_interface.show_character("ren_medical","wail")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("emilio","stare",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("怎么办……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("抱歉啊，把你卷进来。", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("喂喂，不要发表这种遗言似的感想啊！")
	novel_interface.show_character("ren_medical","wail")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("emilio","upset",0.25)
	await novel_interface.show_dialog("已经没有弹匣了，一会我引开它们，你用最快的速度跑向装甲车，或许……", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("那种距离，根本跑不到吧？")
	await novel_interface.show_text_only("第一批六七架无人机已经向我们俯冲了过来，我下意识的抓住了艾米莉欧的手。")
	await novel_interface.show_text_only("从我小臂伤口渗出的血流了她手上，我和艾米莉欧似乎同时感觉到了什么——")
	await novel_interface.show_text_only("只见她右手虚握，就像握住了什么东西，鲜血开始向她的手心汇聚。")
	await novel_interface.stop_music()
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("这是……？？", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_StagingPostL.png")
	await novel_interface.show_text_only("我们同时感到彼此的心脏都像被注入了液氮的赛车引擎，正以逼近极限的负荷搏动着。")
	await novel_interface.show_text_only("随着心率急速飙升，时间感被无限的拉长——")
	await novel_interface.show_text_only("周围的一切声音都变得冗长而模糊，高速俯冲的无人机看起来仿佛缓缓飞舞的蝴蝶。")
	await novel_interface.show_text_only("艾米莉欧掌心的血液在空中化为无数细丝，像履行着既定程序的3D打印机，自动编织成网状结构。")
	await novel_interface.show_text_only("她难以置信的看着手中逐渐成型物体——那似乎是一把长度与我身高相当的巨剑。")
	await novel_interface.show_text_only("剑身在成型的一瞬，立刻爆发出炙热耀眼的粉红色光芒，艾米莉欧迅速转身向空中挥砍出去……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("在她挥剑的瞬间，我的视野突然变暗，周围的空间似乎一下子被抽成了真空。")
	await novel_interface.show_text_only("一阵尖锐的耳鸣过后，整个世界就像被按下了静音键，万物归于寂静——")
	await novel_interface.show_text_only("——————")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_StagingPostC.png")
	await novel_interface.show_text_only("——！！！！！！！！！！")
	await novel_interface.show_text_only("再次回过神来的时候，耳边翻涌呼啸的气浪已经掩盖了一切声音。")
	await novel_interface.show_text_only("三十几架无人机像被飓风裹挟的枯叶般，随风飘零翻滚，吹散到了很远的地方。")
	await novel_interface.show_text_only("在强烈的冲击下榴弹纷纷自爆，但炸出的火团和破片也被炙热的气团一并带走，消失在了视野尽头。")
	await novel_interface.show_text_only("待到狂风渐渐平息，艾米莉欧手中的巨剑已然化为暗红的烟尘完全消散。")
	await novel_interface.show_text_only("我们俩都被面前的景象惊呆了——")
	await novel_interface.show_text_only("补给站仿佛被清洗了一番，累积的浮土、砂砾和细小的碎石被一扫而空。")
	await novel_interface.show_text_only("抬头望去，我们面前天空的沙尘也被完全吹散，清澈的视野一直延伸到遥远的山谷……")
	novel_interface.show_character("emilio","perspire")
	await novel_interface.show_dialog("你到底……是什么人？", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("你是魔女？？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧大概第一次听到这个词，困惑的盯着我。")
	await novel_interface.show_text_only("突然，她肩头挂着的军用步话机传来薇拉急切的呼叫声——")
	await novel_interface.show_dialog("有两枚地狱火导弹正从东边向咱们飞过来！！", "薇拉")
	await novel_interface.show_dialog("应该是刚才『蜂巢』给附近空域巡航的无人侦察机发出了攻击请求……", "薇拉")
	await novel_interface.show_dialog("非得赶尽杀绝吗？该死该死该死！！", "薇拉")
	await novel_interface.show_text_only("我们不约而同的望向天空，然而只看到东侧天边隐约出现了两朵爆炸的火团。")
	await novel_interface.show_dialog("消、消失了……", "薇拉")
	await novel_interface.show_dialog("是你打的？？", "薇拉")
	novel_interface.show_character("emilio","perspire")
	await novel_interface.show_dialog("这次不是我……", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧盯着一脸无辜的我，按住步话机回应道。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("不过我大概知道是因为谁了。", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("SID重型运载机机舱内。")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Dispatched_Ship_Aisle.png")
	await novel_interface.show_dialog("拦截成功了？", "莉琉")
	novel_interface.show_character("nyx_normal","smile")
	await novel_interface.show_dialog("是啊，马萨达的防御系统真难缠……", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯靠在椅背上长舒一口气，终于放下已在手中端了许久的红茶。")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("那两个女兵好像正在拆除NGO卡车的追踪设备，你不打算干预吗？", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("暂时保护性观察吧，她们应该不会伤害小怜。", "莉琉")
	novel_interface.show_character("nyx_normal","smile")
	await novel_interface.show_dialog("哦？看来你不想放过那个意外收获呢~\n查清那两个人的底细了吗？", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是啊，那个小笨蛋好像总能吸引到奇怪的人呢……", "莉琉")
	novel_interface.show_character("nyx_normal","mock")
	await novel_interface.show_dialog("比如说你？", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("彼此彼此。", "莉琉")
	await novel_interface.show_dialog("欧洲那边有什么消息吗？", "莉琉")
	novel_interface.show_character("nyx_normal","normal2")
	await novel_interface.show_dialog("刚收到线报，当年NASA大部分卫星都被纽摩利达斯接收了。", "倪克斯")
	await novel_interface.show_dialog("但据说有批未注册的卫星，在董事会接管之前，被从数据库里完全删除了。", "倪克斯")
	await novel_interface.show_dialog("完全无法确定是联邦政府解体前的授意还是工作人员的个人行为，甚至有传言是黑客组织所为。", "倪克斯")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("而两年前，欧洲和亚洲的黑市确实流入了一批卫星控制秘钥。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("看来地下世界的的情报网也很有用呢~", "莉琉")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("当年苏联解体时也从国防会议流出过一些卫星，等联邦政府想起追查的时候，早就毁尸灭迹了。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("没注册的应该大多是低轨间谍卫星吧，可能还有少量军方的短波通讯卫星。", "莉琉")
	await novel_interface.show_dialog("如果疏于维护，大部分的低轨卫星到现在应该都已经坠毁了——", "莉琉")
	novel_interface.show_character("nyx_normal","smile")
	await novel_interface.show_dialog("那么依然在工作的高轨道卫星……", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("唉，在地表两万公里之外的空间找一颗没有轨道数据的卫星吗……", "莉琉")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("简直是大海捞针。", "莉琉")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("马萨达郊外公路。")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadSways.png")
	await novel_interface.show_text_only("我和艾米莉欧坐在卡车粗壮的前保险杠上，一起欣赏沙漠的晚霞。")
	await novel_interface.show_text_only("薇拉此时正拿着探测设备，在货箱里排查剩余的武器和追踪装置。")
	novel_interface.show_character("emilio","normal")
	await novel_interface.show_dialog("所以……你还认识好几个像我和薇拉这样的人？\n就是你说的“魔女”。", "艾米莉欧")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_medical","smile",0.25)
	await novel_interface.show_dialog("是啊，她们有的人还——", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("艾米莉欧赶忙挡住我的嘴，轻轻摆了摆手。")
	novel_interface.show_character("emilio","speechless")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_medical","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嘘，你是SID的人，这种事我知道的少一点才好。", "艾米莉欧")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("那按照你的说法，这几个月有些破坏可能并不是由抵抗组织造成的？", "艾米莉欧")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("嗯，这种由魔导书赋予的能力对大脑负担很大，并不是每个人都能承受。", "小怜")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("一旦受体丧失理智就会暴走，对周边的区域大肆破坏……", "小怜")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("魔导书……类似随机散布的异质物吗？", "艾米莉欧")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("怪不得军事委员会这阵子总像没头苍蝇似的四处安排巡逻任务，有些还在根本没价值的地区。", "艾米莉欧")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("你的能力是可以放大别人的能力？", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我点了点头，这应该不算说谎吧……")
	novel_interface.show_character("emilio","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_medical","gratified",0.25)
	await novel_interface.show_dialog("不过我也是第一次见到像你这么夸张的……", "小怜")
	novel_interface.change_2nd_expression("bored")
	await novel_interface.show_dialog("刚才那一下，我的内脏都在颤抖，身体好像快要散架了。", "小怜")
	novel_interface.character_light(0.35,"speechless")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("可现在就算我接触你，也没什么特别的感觉。", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她左手拉着我的手腕，右手在半空挥了两下。")
	novel_interface.show_character("emilio","speechless")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_medical","bored",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("唉算了，不如聊聊你吧~", "艾米莉欧")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("你还有什么特别的地方？\n保密的事情不用讲~", "艾米莉欧")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("我、我没什么啊……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我几个月前还是男生这种事一定要保密！！")
	novel_interface.show_character("emilio","mock")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_medical","wry_smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哦——？", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她凑近我仔细打量一番，不禁叹了口气。")
	novel_interface.show_character("emilio","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_medical","bored",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你身上的漏洞实在太多，反而没法判断了……", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("漏洞至于这么多吗？！")
	novel_interface.show_character("ren_medical","shy")
	await novel_interface.show_dialog("你、你看出什么了……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("你性格缺乏自信，但又很独立，估计是在社会抚养系统里长大的吧~", "艾米莉欧")
	await novel_interface.show_dialog("新丰洲的福利真不错……", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这方面我确实没什么好抱怨的，尤其是和马萨达比起来。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("从说话方式和行为举止看来，你从小到大的玩伴应该主要是男生，而且对方显然没把你当女孩子。", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("因为老子本来就是男生！")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("这也太奇怪了吧？\n你的脸蛋明明这么可爱，又毫无防备心——", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她瞄了一眼我大咧咧岔开的坐姿，我立马满脸通红的并拢了双腿。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("那帮傻小子是瞎了吗？", "艾米莉欧")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("还是说……你男朋友很厉害？", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("永远都不会有的谢谢！！")
	novel_interface.show_character("emilio","mock")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_medical","shy_right",0.25)
	await novel_interface.show_dialog("你别乱猜了啦！！", "小怜")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("也不对，或者你喜欢的……不是男生？", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她表情玩味的用胳膊肘捅了捅我，我浑身一激灵。")
	novel_interface.show_character("emilio","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_medical","wail",0.25)
	await novel_interface.show_dialog("（这要我怎么回答啊！！）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我故作生气的望向远方的沙漠，回避着她的目光。")
	novel_interface.show_character("emilio","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_medical","wail",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("好啦好啦，其实我和你差不多……", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("艾米莉欧抬头看着天上缓缓移动的橘色云彩。")
	await novel_interface.show_text_only("差不多？等等，你指哪方面……")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("其实我的祖父……曾经是这个国家的大人物，不过都是过去的事了~", "艾米莉欧")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("后来很多人把圣城的毁灭归咎于他的政党对周边国家采取的绥靖政策，连他本人一起赶下了台。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧做出了完全超出我预料的发言。")
	novel_interface.show_character("emilio","worry")
	await novel_interface.show_dialog("我父亲虽然是家里的长子，但从小就和祖父的关系不好。", "艾米莉欧")
	await novel_interface.show_dialog("后来他娶了异族的女人——就是我母亲，祖父大动肝火的把他们一起赶出了家。", "艾米莉欧")
	await novel_interface.show_dialog("所以我六岁前一直在妈妈和外婆的聚落生活，就在埃尔比勒附近……", "艾米莉欧")
	await novel_interface.show_dialog("后来抵抗军四处流窜，马萨达要求聚落必须整体迁移到“保护区”，否则一概视为恐怖分子。", "艾米莉欧")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("但那次迁移路途遥远，国防军发放的物资和载具根本不够，半路又被土匪抢走了一大半的粮食——", "艾米莉欧")
	await novel_interface.show_dialog("结果一万多人有三分之一死在了路上，其中也包括我的父母。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","perspire1")
	await novel_interface.show_dialog("啊……\n（原来她说“和我一样”是这个意思……）", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("那、那你后来——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧笑着摇了摇头，继续说道。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("后来到了新的定居点，聚落里的老人联系到了马萨达的官员。", "艾米莉欧")
	await novel_interface.show_dialog("我还记得第一次被领到祖父面前的时候，他的表情迅速从期待变成了失望。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("……失望？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("他一直希望自己的后人能够重回政界，大概是对家族名誉之类的执念吧……", "艾米莉欧")
	await novel_interface.show_dialog("甚至还动用关系改了我的出生证明，把我的生母换成了别人。", "艾米莉欧")
	await novel_interface.show_dialog("父亲就是不想背负这些东西才和他闹僵的。", "艾米莉欧")
	await novel_interface.show_dialog("不过倒是帮了我，不然我连军校的审核都过不了。", "艾米莉欧")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_medical","panic",0.25)
	await novel_interface.show_dialog("那他有什么好失望的，那时你才六岁吧。", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她指了指自己的眼睛，向我示意左金右蓝的瞳孔。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("这个标志太过显眼了，不可能从政的。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","sprite")
	await novel_interface.show_dialog("这有什么关系吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("异色瞳不是很好的萌属性吗！？\n我代表新丰洲的电器街给你投票！")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("我小时候也不懂，但后来逐渐明白了。", "艾米莉欧")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("比如有些位高权重的政治家，为了表明自己不搞权力世袭，会特意给子女起一些奇怪的名字。", "艾米莉欧")
	await novel_interface.show_dialog("用水果或动物的名字和叫声，配合不常见的谐音或叠字……", "艾米莉欧")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("你能想象名字叫呱呱或桃子的人当选议长吗？", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("噗——\n好像被你这么一说……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("施恩内曼总理很早之前就承诺，自己卸任之后会恢复选举。", "艾米莉欧")
	await novel_interface.show_dialog("选举是极致的标签化运动，一个太过显眼的标志足以盖掉所有标签~", "艾米莉欧")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("不过无所谓，我才没兴趣讨好一群白痴。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","happy")
	await novel_interface.show_dialog("呼~~你俩聊什么呢？", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("薇拉拎着一堆电子元器件的线头从后面走了过来。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("都清理干净了？", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","wink")
	await novel_interface.show_dialog("没问题，每个货箱的追踪装置都拆下来了，这些物资全都“洗”干净了。", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("薇拉边说边把那些追踪装置包好，挂在一架提前磨掉了编号的无人机上。")
	await novel_interface.show_text_only("我们看着那架无人机按设定好的巡航路线，顺着公路一直飞向了远方的夕阳……")
	await novel_interface.show_text_only("艾米莉欧从保险杠跳下来，掸了掸手。")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("好，咱们回家。", "艾米莉欧")

	print("=== 星尘降临篇第14话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
