# stardustdescends_ep13.gd - 星尘降临篇第13话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep13_script()

func play_script():
	pass

func stardustdescends_ep13_script():
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadSentry.png")
	await novel_interface.show_text_only("从车体监控传来的影像看，我们的正前方是一段还在建造中的隔离墙。")
	await novel_interface.show_text_only("由于地处内城区边缘，这里完全没有中心区那种繁华安逸的感觉——")
	await novel_interface.show_text_only("钢铁、水泥和烟尘还原出了这片荒凉沙漠战区最原始的粗粝质感。")
	await novel_interface.show_text_only("前方的岗哨被建得犹如堡垒一般，周围还停靠着好几辆同型号的装甲运兵车。")
	await novel_interface.show_text_only("远处有很多塔吊和重型机械在工作，墙壁上空还隐约能看到成片的无人机群。")
	await novel_interface.show_text_only("从金属围栏的放置方式看来，前方的出口俨然一副禁止通行的样子。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadAPCO2.png")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("你们是要……闯过去？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧拍了拍装甲车的内壁。")
	novel_interface.show_character("emilio","speechless")
	await novel_interface.show_dialog("就凭它？", "艾米莉欧")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("这种装甲虽然坚固，但导热性和普通金属没什么区别，在咱们被烤熟前大概能坚持个20秒吧~", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("忽然，我们的车停了下来，前方驾驶舱传来一个似曾相识的声音——")
	await novel_interface.show_dialog("卡拉卡尔营一级准尉薇拉·瓦尔基里，去营区接队员出城侦查。", "薇拉")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("（是赌船上负责安检的那个怪力女吧？！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她一只手将那身材肥硕的总主教拎起来的画面我现在都记忆犹新。")
	await novel_interface.show_dialog("是薇拉啊，现在耶胡达集市那边有抗议活动，不想被围住的话最好从其他出口……", "男性的声音")
	await novel_interface.show_dialog("别废话快放行，绕路时间来不及了！", "薇拉")
	await novel_interface.show_dialog("哈哈好吧好吧，不过你别再捅什么娄子了，上次你老爹从总参谋部直接打电话来骂人……", "男性的声音")
	await novel_interface.show_dialog("你要再提他，我就直接轧过去。", "薇拉")
	await novel_interface.show_dialog("挪一下路挡，放行了放行了！", "男性的声音")
	await novel_interface.show_text_only("艾米莉欧凑过来小声问我。")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("呐，你刚才是不是有一瞬间想过大声呼救，然后又怂下去了呀？", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","shy_left")
	await novel_interface.show_dialog("才没！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我赶忙扭过头去，啊啊这人好讨厌！")
	await novel_interface.show_text_only("车子向前缓缓移动，很快穿过隔离墙来到了马萨达的外城区。")
	await novel_interface.show_text_only("我原以为外城区会更加荒芜，但穿过隔离墙后，路上的人突然多了起来——")
	await novel_interface.show_text_only("虽然这边路面有些不平整，也没那么多高层建筑和绿化带，但街道却异常热闹。")
	await novel_interface.show_text_only("熙熙攘攘的人群、穿梭往来的公交车和在路边招揽生意的小贩，让我感觉仿佛穿越了时空。")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("这里人好多……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("emilio","smile",0.25)
	await novel_interface.show_dialog("那当然了，这座城市90%的人住在隔离墙外面。", "艾米莉欧")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这么多！？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("内城区总共只有32平方公里，不到马萨达面积的四分之一，而且地价高得离谱~", "艾米莉欧")
	await novel_interface.show_dialog("尤其是中心区，一个厕所的面积就够在死海旁边买套单身公寓了。", "艾米莉欧")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我还以为隔离墙是为了那个……嗯……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("种族隔离？", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("对对对，好像有某种规定，某些对特定族群不友好的词汇，只有这个族群自己人能说……")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("联合议会早就明确禁止这么干了~", "艾米莉欧")
	await novel_interface.show_dialog("但马萨达《反恐袭法》规定，如果想在政府和议会所在的内城区长住，就必须通过安全局的审核。", "艾米莉欧")
	await novel_interface.show_dialog("而那些直系亲属是特定民族的申请者，都“恰好”无法过审……明白了吗？", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我似懂非懂的点了点头。")
	await novel_interface.show_text_only("这不就是隔离吗！\n虽然好像隔离的是自己……")
	await novel_interface.show_text_only("而且这么说的话，即使是马萨达本族的居民，也大部分都生活在外城区吧？")
	await novel_interface.show_text_only("我看到屏幕上，一个挎着M16的女兵蹲在卖头饰的地摊前，在跟用头巾包住脸的女摊主讨价还价。")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("（原来哪儿的人都买不起房啊……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然车子一个急刹，我的头差点没磕在屏幕上，同时驾驶舱传来了薇拉的叫骂。")
	await novel_interface.show_dialog("靠！！", "薇拉")
	novel_interface.show_character("emilio","shout")
	await novel_interface.show_dialog("怎么了！？", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("我放了侦查无人机，你们自己看屏幕吧。", "薇拉")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我和艾米莉欧赶忙凑到屏幕前，看到了让人不寒而栗的景象——")
	#novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_AncientHumanEH.png") #原游戏有素材，但已丢失
	await novel_interface.show_text_only("上千名身穿黑外套，头戴黑色帽子的男性聚在前方路口，犹如一场超大型的葬礼。")
	await novel_interface.show_text_only("他们举着自制只有黑白两色的标语牌，似乎在抗议这世界存在的其他任何颜色。")
	await novel_interface.show_text_only("这些人大多留着大胡子，两鬓梳着奇怪的小辫，这似曾相识的造型……")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadAPCR1.png")
	await novel_interface.show_dialog("这帮XX玩意儿！吃着国家的补贴还XX天天抗议！", "薇拉")
	await novel_interface.show_text_only("就当“XX”是某种方言吧……反正我听不懂。")
	await novel_interface.show_dialog("要求将符合教义的小学数量提升一倍？\n他们的XX鬓角是不是XX长进脑子里了！？", "薇拉")
	await novel_interface.show_text_only("驾驶舱传来踹门的声音，我们的驾驶员似乎跳下车去干架了。")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("她、她干嘛去了？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("emilio","mock",0.25)
	await novel_interface.show_dialog("去遮挡车牌吧~", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("艾米莉欧在厚实的军用平板上查看着路线图，漫不经心的回答道。")
	novel_interface.show_character("ren_medical","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("emilio","mock",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("要、要干什么……那些都是马萨达人吧？\n好像我刚在博物馆也见过……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("这帮人是马萨达的“历史遗产”，不工作不缴税还不用服兵役，每个月还要政府发补助金——", "艾米莉欧")
	await novel_interface.show_dialog("就算是破坏公共秩序阻断交通，警察和军队也管不了，因为他们有自己的宗教法庭。", "艾米莉欧")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……这么好？", "小怜")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("（那岂不可以天天宅家里玩游戏……）", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("不过他们的教义要求家里不能有电视和电脑，并且严格禁止上网——", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("那是酷刑吧！！")
	novel_interface.show_character("ren_medical","uneasy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("emilio","speechless",0.25)
	await novel_interface.show_dialog("但他们的老婆就不一样了，可以使用电子设备，毕竟这帮人还要靠女人赚钱来补贴家用。", "艾米莉欧")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("倒不是因为补助金给的少，而是这种家庭的女性平均要生六七个孩子，多的能生十几个。", "艾米莉欧")
	novel_interface.change_2nd_expression("speechless")
	await novel_interface.show_dialog("这么多小孩，宗教学校当然不够用了……", "艾米莉欧")
	novel_interface.character_light(0.35,"bored")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（难道刚才在博物馆看到围着那两个黑衣大胡子的十几个小孩——）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("还有跟在那帮孩子身后面容憔悴的两个女人……")
	await novel_interface.show_text_only("想到其中一个女人推着的那辆婴儿车，我不禁打了个冷颤。")
	novel_interface.show_character("emilio","speechless")
	await novel_interface.show_dialog("宗教原教旨主义者，无论在哪都是癌症……", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧继续低着头在摆弄平板，语气中带着莫名的悲伤和些许无奈。")
	await novel_interface.show_text_only("不一会，薇拉就回到了车上，艾米莉欧拍了拍驾驶舱的金属挡板提醒她注意。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("绕到东边第三个路口，有一座刚建好的高架桥，是最快的出城路线。", "艾米莉欧")
	await novel_interface.show_dialog("还有，你要做“那个”的话，记得先掉头哦。", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("明白~", "薇拉")
	await novel_interface.show_text_only("薇拉把方向盘打满猛踩油门，一把轮就将车头调了过来，完全不考虑乘客体验。")
	await novel_interface.show_text_only("随即车顶传来“咚—”“咚—”“咚—”\n“咚—”四声闷响。")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("（等等，怎么像是榴弹发射器的声音……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("很快聚集的黑衣人便开始骚动，人群中不同的位置同时冒出四股催泪弹的白烟……")
	await novel_interface.show_text_only("而我们的车开足马力，迅速消失在转角。")
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("随着隔离墙的影子在我身后越变越小，道路两边的环境逐渐开始变得荒芜。")
	await novel_interface.show_text_only("在城区里待久了，很容易忽略马萨达堡本身是一座突兀建在沙漠中的城市。")
	await novel_interface.show_text_only("运兵车沿着空无一人的道路疾驰，孤独的公路旁已经没有任何人类的踪迹。")
	await novel_interface.show_text_only("仅有少许干枯的灌木，还死硬的伫立在沙地中……")
	novel_interface.change_music("res://assets/audio/music/unkown/Battle_08.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_StagingPost.png")
	await novel_interface.show_text_only("出城后大约又行驶了一个多小时，随着车厢门被缓缓打开，一座军用补给站出现在了我面前。")
	novel_interface.show_character("valkyrja","normal")
	await novel_interface.show_dialog("就是这了，要让她帮忙干活吗？", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","perspire1")
	await novel_interface.show_dialog("诶？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("没问题，她会配合的。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("你们就不怕我逃跑——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一边抗议一边很老实的下车，话说到一半就咽了回去。")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("（四周都是荒无人烟的沙漠，我能跑哪去啊……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这座下沉式补给站藏在沙丘中，从远处看不过是光秃秃的山上众多土坡中的一个。")
	await novel_interface.show_text_only("不过似乎已经废弃蛮久了……")
	await novel_interface.show_text_only("大概因为这种地方的维护成本太高，而且抵抗军已经放弃了周边区域的缘故吧。")
	await novel_interface.show_text_only("停在站内的吉普车已经积了厚厚的一层土，大量用来制作掩体的麻袋也被随意堆得四处都是。")
	await novel_interface.show_text_only("靠在墙边的叉车和发电机布满了锈迹和被风沙侵蚀的瘢痕，角落还有几箱被打翻的子弹……")
	await novel_interface.show_text_only("刚才在车上，艾米莉欧解答了我第二个问题：她们要做的“私事”到底是什么。")
	await novel_interface.show_text_only("其实我多少已经猜到，与自己的伪装身份有关——")
	await novel_interface.show_text_only("根据艾米莉欧的说法，NGO在交战区替军方运送任何物资都是违反国际公约的。")
	await novel_interface.show_text_only("以救助无辜平民的名义获得交战双方的豁免权，又去帮助其中某一方的行为，严重违背道德准则。")
	await novel_interface.show_text_only("但马萨达军方这些年将很多军用哨站都伪装成了平民救助设施，并收买NGO替他们运送物资。")
	await novel_interface.show_text_only("这样不仅能更灵活的牵制打游击的抵抗军，而且每当哨站被毁，都可以大肆宣传恐怖袭击残害无辜。")
	await novel_interface.show_text_only("她们要做的，就是劫持这种灰色物资。")
	await novel_interface.show_text_only("通过我胸卡的紧急救援码，艾米莉欧查到了最适合作为目标的车辆信息。")
	await novel_interface.show_text_only("那本是用于在遭遇紧急情况时，查询并调用NGO名下离自己最近的救援物资的功能。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("那辆卡车运的主要是军用医疗物资，40分钟后会沿着公路经过这里。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","happy")
	await novel_interface.show_dialog("我去布置路障和地雷，你俩准备机枪和扬声器吧。", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","shy")
	await novel_interface.show_dialog("……扬声器？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我下意识的摸了一下胸部。")
	await novel_interface.show_text_only("薇拉依次揭开了车上那些装备的三防罩，虽然早有心理准备，但还是吓了我一跳——")
	await novel_interface.show_text_only("一台大狗四足运载机器人，两排遥控路障，六架自瞄机枪，四台扬声器和小型遥控炸弹若干……")
	await novel_interface.show_text_only("……她们究竟要做什么啊！？")
	await novel_interface.show_text_only("艾米莉欧和我靠大狗机器人的运载力，很快将机枪以及音箱部署在了附近的山坡上。")
	await novel_interface.show_text_only("埋设好路障和炸弹的薇拉遵照艾米莉欧的指示把一辆吉普车加满油，开到了公路旁的一座巨石背面。")
	await novel_interface.show_text_only("接着她们把装甲车顶部的侦查无人机放出，用光学迷彩罩将车完美的隐藏了起来。")
	await novel_interface.show_text_only("最后我们三人猫在最高的山坡背面，静静等待着目标出现。")
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("真的保证不会伤到人吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我不安的问道，刚才部署的那些武器消灭一个排都绰绰有余吧？")
	novel_interface.show_character("valkyrja","wink")
	await novel_interface.show_dialog("安心啦，这可是艾米计划的——", "薇拉")
	await novel_interface.show_dialog("我们营的人都知道，信她准没问题！", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("那几架机枪由AI控制红外瞄准，绝对不会打到人。", "艾米莉欧")
	await novel_interface.show_dialog("遥控炸弹也做过改装，基本没什么杀伤力，有些主要提供声响，而另一些会大量冒烟……", "艾米莉欧")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("啊，车来了！", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("从侦查无人机的画面可以看到，一辆印着医疗救援组织红色LOGO的卡车正沿着公路驶来。")
	await novel_interface.show_text_only("行驶到补给站附近的路段时，一枚炸弹爆炸，同时第一排路障支起一个角度令卡车颠簸。")
	await novel_interface.show_text_only("只见那辆卡车慢慢减速，司机以为是爆胎，赶忙下车查看。")
	novel_interface.show_character("emilio","angry")
	await novel_interface.show_dialog("就是现在！", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("随着少尉一声令下，精心布置的烟火秀开始了——")
	await novel_interface.show_text_only("第二排路障迅速支起并抱死卡车的前轮，山坡上的机枪陆续启动射击程序。")
	await novel_interface.show_text_only("大量子弹巧妙的避开人体和卡车的动力系统，在地上留下了无数弹痕。")
	await novel_interface.show_text_only("刚下车的司机狼狈的逃回车上，却发现无论怎么点火，车都纹丝不动。")
	await novel_interface.show_text_only("音箱开始播放提前录制好的几个男性用阿拉伯语的喊话，意思大概是抓活的要赎金之类。")
	await novel_interface.show_text_only("同时接二连三的发生爆炸，卡车周围顿时被烟雾笼罩了起来。")
	await novel_interface.show_text_only("司机和副驾驶两人趁着烟雾逃了出来，被机枪火力驱赶着，屁滚尿流的钻到了路边的巨石掩体后面。")
	await novel_interface.show_text_only("大概一分钟后，机枪火力渐稀，那两个被吓得魂飞魄散的可怜虫立刻开着停在那里的吉普仓皇逃走。")
	await novel_interface.show_text_only("只见他们把油门踩到底，也不管公路在哪，一路画着蛇形开向了沙漠深处……")
	await novel_interface.show_text_only("我张大着嘴目睹了这几分钟内发生的一切，震惊得说不出一句话来。")
	await novel_interface.show_text_only("艾米莉欧从地上爬起来，掸了掸身上的土，看着脑袋上挂满了问号的我解释道。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("抵抗军里有一些独立派系的游击队，还曾经流散出不少逃兵钻进山区当了土匪。", "艾米莉欧")
	await novel_interface.show_dialog("只要伪装成是那帮人做的并留下目击证人，那自身也违反了国际公约的国防军也只能吃个哑巴亏。", "艾米莉欧")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("大概就是根据这个思路设计的~", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然不明白你们为什么要抢劫自家的物资，但请先受我一拜！")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.show_character("valkyrja","angry")
	await novel_interface.show_dialog("等等，你看那边！", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("薇拉指着卡车车厢顶部缓缓展开的金属甲板喊道。")
	await novel_interface.show_text_only("从那漆黑的洞口迅速窜出六台小型无人机，间隔两三秒后，又窜出六台，然后又有六台……")
	await novel_interface.show_text_only("艾米莉欧立刻卧倒，开始在军用平板上更改机枪瞄准系统的设定，依然还有更多的无人机冒出来。")
	novel_interface.show_character("emilio","shout")
	await novel_interface.show_dialog("糟了，是『蜂巢』！", "艾米莉欧")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("这下麻烦了……", "艾米莉欧")

	print("=== 星尘降临篇第13话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
