# stardustdescends_ep21.gd - 星尘降临篇第21话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep21_script()

func play_script():
	pass

func stardustdescends_ep21_script():
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("事件两周后，第五学园都市郊外。")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_VillaHall.png")
	await novel_interface.show_text_only("倪克斯一边用耳机打电话，一边优雅的走下楼梯。")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("那次事件被定性为战后最严重、最恶劣的一次恐怖袭击。", "倪克斯")
	await novel_interface.show_dialog("联合议会正在展开全面调查，并表示对所有涉嫌参与的人都绝不姑息。", "倪克斯")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("所以——", "倪克斯")
	await novel_interface.show_dialog("“慕沙尔是从您的渠道购买的那颗卫星”这个情报应该值多少钱呢……洪先生？", "倪克斯")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("可能是因为……我最近交了一些很擅长做电子货币反向追踪的朋友吧~", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯的嘴角露出一抹微笑。")
	novel_interface.show_character("nyx_normal","smile")
	await novel_interface.show_dialog("那么这座庄园我就代父亲收回了——", "倪克斯")
	await novel_interface.show_dialog("当然，它一直运营的生意仍会继续，我只要一成的收益作为房租。", "倪克斯")
	await novel_interface.show_dialog("毕竟，我也不希望您和哈蒙一个下场。", "倪克斯")
	await novel_interface.show_dialog("只是需要您负责好我的安全保障……", "倪克斯")
	await novel_interface.show_dialog("受慕沙尔的启发，我也植入了一种生命检测设备。", "倪克斯")
	novel_interface.change_expression("sad")
	await novel_interface.show_dialog("如果我的生命活动停止，那些秘密就会被自动发布到网上……", "倪克斯")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("对了，米勒总主教和莱博娜的关系我会保密的~", "倪克斯")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("毕竟您很慷慨的把NASA失窃资料也交给我了嘛。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯拿起桌上的平板电脑，打开那份加密文件。")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("…『0812』项目卫星的名字叫“STARDUST”？", "倪克斯")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("真是……\n一点也不令人意外呢~", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("第二天，SID指挥室。")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","shock")
	await novel_interface.show_dialog("这么说……你真的什么都不记得了？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("一点印象都没……", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("我好像因为卫星撞击的那次冲击波，在装甲车里磕到脑袋晕过去了。", "小怜")
	await novel_interface.show_dialog("然后我醒来的时候，就发现自己躺在医院的床上打吊瓶……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("国防军传来的录像中，你从装甲车出来时面无表情且一言不发，周身还包裹一层诡异的钻蓝色光晕。", "莉琉")
	await novel_interface.show_dialog("好像你已经知晓了一切计划，在众人的目送下径直走上了会展中心的天台。", "莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("根据安妮的报告，几乎在同一时间，大使馆里昏迷不醒的小星尘身上也发出了类似的光……", "莉琉")
	await novel_interface.show_dialog("艾米莉欧说你在天台上拉住她的手时，似乎有种无以名状的巨大力量涌入进她的体内。", "莉琉")
	await novel_interface.show_dialog("比之前你们遭遇蜂巢那次还要强上百倍，好像随时会把她的身体溶解掉。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("但那一击打出后，你身上的光晕就随之消失，瞬间瘫软到人家怀中，还拼命试图把脸往她的胸口扎。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("……哈？\n有、有吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可恶，我怎么完全不记得了！")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("可我看了事件简报之后，还有些想不通的地方……", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("慕沙尔在两年前就买下了那颗卫星的控制秘钥吧？", "小怜")
	await novel_interface.show_dialog("当时马萨达还没宣布自动反击系统，他怎么可能提前就准备好反制策略呢。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("就算让那卫星直接撞在陆地上威力也十分可观，甚至可以在正面战场上扭转战局。", "小怜")
	await novel_interface.show_dialog("高明的战略家永远不会放过任何一枚棋子，谁知道什么时候就能派上用场……", "莉琉")
	await novel_interface.hide_character()
	
	
	await novel_interface.show_text_only("莉琉意味深长的看着假装听懂并连连点头的我。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("倪克斯昨天在黑市上找到一份NASA失窃的文件。", "莉琉")
	await novel_interface.show_dialog("那颗撞向死海的卫星是为了接收并存储从四百光年外昴宿星团的某个区域向地球方向传输的信号。", "莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("信号数据量极大，每秒存储的数据达TB级，而且只有在特定的轨道位置才能接收——", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("所以只能将数据存储在卫星内部的硬盘上，有朝一日存满后，再让卫星降回地球进行物理回收。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("可以说，那就是一座太空数据中心。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("爱衣推测，收到的数据很可能与小星尘丢失的记忆有关。", "莉琉")
	await novel_interface.show_dialog("但那颗卫星现在已经被撞成碎片，散落在深400多米的死海海底了……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("那小星尘的记忆取不回来了？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("谁知道呢……反正那个来自遥远宇宙空间的信号已经消失了。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("可能某种意义上，它已经达到自己的目的了？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("那小星尘现在怎么样了……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("她刚回来的时候跟你一样陷入昏睡，爱衣把她带到播磨脑研了……", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("不过你们就像有心灵感应似的，昨天几乎在同一时间醒了过来。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("不过她也是一问三不知，爱衣特别失望，说那孩子的脑袋和你一样空空如也", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我哪里空空如也了！？")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("哦对了！她还给小星尘做了亲缘检测……", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("？", "小怜")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("放心吧，你们确实没有血缘关系~", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("本来就不应该有吧！！", "小怜")
	novel_interface.character_light(0.35,"speak")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那小家伙醒来后就一直吵着要见你，安妮正带她回总部。", "莉琉")
	await novel_interface.show_dialog("呵呵呵……小孩子真是活泼啊~", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("怎么一副老祖母的样子……",)
	novel_interface.show_character("liliu_research","happy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","wail",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("既然那孩子非要赖着你，我想顺便纠正一下你那种喜欢逃避责任的性格也不错。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("什、什么意思……？\n（不是我想的那个意思吧！！）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉拿起保温杯，喝了一小口泡着奇怪植物的花草茶，脸上也舒展出慈祥的笑容。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("对了，那个……艾米和薇拉还好吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("你不知道吗？她们现在好得很~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("当时有个记者在附近的居民楼顶层拍到了会展中心天台的画面。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("于是全世界都看到了艾米莉欧像天神下凡一样把沙尘暴劈成了两半——", "莉琉")
	await novel_interface.show_dialog("虽然国防军后来解释说，那是某种只能发射一次的消耗型异质物武器。", "莉琉")
	await novel_interface.show_dialog("但在所有亚伯拉罕宗教中，只有像摩西那样的天选之人才能做出“分开大海拯救世人”的行为。", "莉琉")
	await novel_interface.show_dialog("眼看底层信众的反响激烈，再加上她本人是混血而且没有任何宗教信仰——", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("马萨达的大拉比和伊玛目破天荒的达成了一致，都争着说她是神的使者。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("真是……状况复杂的国家呢。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("施恩内曼总理顺水推舟，让她做了宗教与教育部的首席顾问。", "莉琉")
	await novel_interface.show_dialog("虽然只是个名誉性职位，但艾米莉欧还是找了薇拉做自己的助理。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("前几天马萨达议会决定，继续推动落实原停火协议中的部分条款，并由艾米莉欧协调民族事务。", "莉琉")
	await novel_interface.show_dialog("这样无论国防军内斗或者未来大选的结果如何，她们应该都不会受到牵连了。", "莉琉")
	await novel_interface.hide_character()
	
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("总之她俩没事就好……", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("那关于『幻想军势』……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没等我说完，莉琉就打断了我的发言。")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("这件事要严格保密，连安妮也不能说。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉像看正在犯蠢的小动物一样微笑的看着我。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("你不会以为是因为自己蒙对了幻想军势的秘密，哈蒙才放过艾米莉欧的吧？", "莉琉")
	await novel_interface.show_dialog("从你按下通话键开始，国防军和摩诺拉就在追踪你的位置，当时你那辆装甲车早已经被包围了。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("要不是我及时介入对话并自报身份，你和艾米莉欧一个都活不成。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("啊嘞？？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("你是不是忘了，幻想军势作为反击系统的核心早就被他们封存起来了。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("就算你的推论全部正确，也拿不出半点证据。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("这套理论20多年前马萨达就有一位叫施罗默·桑德的历史学教授提出过。", "莉琉")
	await novel_interface.show_dialog("他当时也是因为拿不出确实的证据，甚至被批驳为叛徒、大屠杀主义者和纳粹的同路人。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("那你不是也……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("我的介入传达了两个信息——", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("第一，主管亲自出面说明SID很重视你的安全。", "莉琉")
	await novel_interface.show_dialog("第二，如果你出了什么意外，SID会毫不犹豫的用这个情报对马萨达施加报复。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("摩诺拉知道SID掌握着许多能对大型国际媒体实控人施压的情报。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("就像传媒行业的那句名言：只要你的声量够大，就不需要什么见鬼的证据。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("只要这个新闻四处疯传，挑动起大量的民族主义情绪，西亚至少还得再打三十年的反恐战争。", "莉琉")
	await novel_interface.show_dialog("当时艾米莉欧也听到了，但她同样不会把这件事告诉薇拉，你也一样——", "莉琉")
	await novel_interface.show_dialog("而且秘密一旦被公开，就没有利用价值了。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("听·明·白·了·吗？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉微笑的看着我，同时指关节掰得咔咔作响。")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("明白了！\n我死也不会说的！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("想死也没那么容易——", "莉琉")
	await novel_interface.show_dialog("我听说马萨达贫民区的一家孤儿院，前不久收到了一笔巨额捐款……", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("那枚莱博娜金色筹码……你不会以为我忘了吧？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("诶？\n那那那那那个……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我倒把这事忘了个干净！")
	await novel_interface.show_text_only("当时我想下楼找艾米她们，又怕遇到什么意外……")
	await novel_interface.show_text_only("就趁海法阿姨关灯时把那枚筹码夹在纸条里，放在她办公桌的相框前面了。")
	await novel_interface.show_text_only("我留言上说如果自己一周内没回来，就让阿姨把它作为给孩子们的捐款。")
	await novel_interface.show_text_only("当时我觉得自己超帅气，没想到直接在床上睡了两个礼拜……")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("那件事的原委我已经了解了，所以接下来……", "莉琉")
	await novel_interface.hide_character()
	
	
	await novel_interface.show_text_only("莉琉不知为何显得有点兴奋。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("你只要考虑赚钱还债就可以了~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("这么多钱把我卖多少次都不够啊……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("别这么妄自菲薄~\n我都帮你签下好几个广告了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("啥？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("那个记者发布的视频连你也一起拍到了，不过大家普遍认为你是被艾米莉欧顺手救下的医务人员。", "莉琉")
	await novel_interface.show_dialog("既然你已经暴露了形象，与其让其他情报机构胡乱猜测，不如顺水推舟……", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("我已经帮你谈下了马萨达新推出的高能量电池的形象代言——", "莉琉")
	await novel_interface.show_dialog("厂家那边也觉得把传统电池广告里的玩具兔子换成“被拯救的少女”这个点子简直绝妙~", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("兔子这个词听起来一点都不妙！！")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("……原来做经纪人这么有趣啊~", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("莉琉见我已经面红耳赤头顶冒烟，便心满意足的打发我出去迎接安妮她们了。")
	await novel_interface.show_text_only("……")
	novel_interface.change_music("res://assets/audio/music/unkown/UI_Main_Funk.mp3")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	await novel_interface.show_text_only("我从电梯出来时，安妮已经和小星尘在街上等候多时了。")
	novel_interface.show_character("stardust_small","tear")
	await novel_interface.show_dialog("小怜啊啊嗷呜呜呜~~~~~", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小家伙见到我后大叫一声并拖着奇怪的尾音扑了过来，接着就像树袋熊一样糊在了我的大腿上。")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("喂喂喂——\n（脑袋别往我裙子下面钻啊！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看到她涕泪横流又想拼命撒娇的样子，马上心软的我轻轻得摸着她的头安抚起来。")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("好啦好啦……", "小怜")
	await novel_interface.show_dialog("你不是也睡了很久昨天才起床嘛……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","tear",0.25)
	await novel_interface.show_dialog("啊呜嗷呜饿……", "小星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她大概没跟我赖够，一边用脸磨蹭大腿一边嘟囔奇怪的音节，像抱着木天蓼的小猫一样似乎很享受。")
	novel_interface.show_character("ren_battle","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("stardust_small","konata_eye",0.25)
	await novel_interface.show_dialog("饿……", "小星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她的肚子发出“咕——”的声音，哼唧的音节也变得单调起来，似乎希望我赶快领会她的旨意。")
	novel_interface.show_character("ren_battle","happy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("stardust_small","konata_eye",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你是不是想吃东西啦？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("嗯！", "小星尘")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("想吃什么呢？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("只见她头上猫耳一样的耳机闪了两下，立刻答道。")
	novel_interface.show_character("stardust_small","smile")
	await novel_interface.show_dialog("Le Soufflé的杨桃舒芙蕾。", "小星尘")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_normal","smile",0.25)
	await novel_interface.show_dialog("哎呀，品位不错啊~", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮惊讶的看着得意洋洋的小星尘。")
	novel_interface.show_character("anne_normal","happy")
	await novel_interface.show_dialog("如果是小怜请客的话——", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("哈哈哈哈……\n（你绝对不会相信我现在欠了多少钱。）", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("你知道什么是舒芙蕾吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","smile")
	await novel_interface.show_dialog("不知道呀~", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("能不能别笑得这么理直气壮……")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("（原来这个智能音箱还可以搜索餐厅吗……）", "小怜")
	await novel_interface.hide_character()
	
	
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("那咱们走吧！正好我也饿了，中午什么东西都没吃就跑去播磨脑研接这个小鬼……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮拉起小星尘的手，我才发现她手腕上戴着一个很眼熟的东西——")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("等一下，那个是……？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_normal","normal1",0.25)
	await novel_interface.show_dialog("欸？这个怎么还绑着呀，快点摘下来~", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮利落的摘下了小星尘手腕上那条皱巴巴的粉色纸质手环，我赶忙要了过来。")
	await novel_interface.show_text_only("那手环上歪歪扭扭的写着星尘的名字——")
	novel_interface.show_character("ren_battle","solemn")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_normal","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这、这个手环……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我记得在赌船上，小星尘还没实体化的时候就已经被我摘下来了。")
	novel_interface.show_character("ren_battle","solemn")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_normal","worry",0.25)
	await novel_interface.show_dialog("你忘了？这不是艾米莉欧发现她没戴入境处的条形码，用纸带给她做的临时ID嘛~", "安妮")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……诶？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("那不是白色纸带吗？！\n而且条形码去哪了……")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("因为早就过了36小时，上面的油墨自动褪色了吧~", "安妮")
	await novel_interface.show_dialog("那天晚上，这家伙在床上用酒店的圆珠笔乱画的时候在手环上写了自己的名字——", "安妮")
	await novel_interface.show_dialog("然后她不小心打翻了石榴汁，就把纸带染成了这个颜色。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的脑子瞬间嗡的一下。")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("你还好吗？\n怎么眼神呆呆的……", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","konata_eye",0.25)
	await novel_interface.show_dialog("嗯嗯？\n你怎么啦呀~", "小星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("小星尘一边摇晃我的手臂，一边用水润的眼睛无辜的看着我。")
	novel_interface.stop_music()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_VaultStardust.png")
	await novel_interface.show_text_only("这个东西……")
	await novel_interface.show_text_only("不是和我最初见到她时，她手腕上戴的那个手环一模一样嘛……")
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("与此同时，新丰洲大隅纪念医院。")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Baizhu_Sickroom_Evening.png")
	await novel_interface.show_text_only("爱衣站在窗边，看着晚霞中的第五学园都市。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("施教授刚刚被放进了冬眠仓，你确定要将他作为实验体吗？", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("海因里希不是一直希望研究一下那种物质对大脑的作用吗……反正要不是咱们他也早就挂了~", "莉琉")
	await novel_interface.show_dialog("而且他的女儿或许很有价值……", "莉琉")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("话说我最近也在思考他女儿说的那个思想实验……", "爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("我们掌握了这么多情报资源，可直到最后一刻才勉强能理解慕沙尔计划的全貌。", "爱衣")
	await novel_interface.show_dialog("而小怜仅仅通过在马萨达两天的见闻，就猜出了幻想军势的秘密，并阻止了一次几乎完美的袭击。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("……你不觉得很不可思议吗？", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("或许吧。", "莉琉")
	await novel_interface.show_dialog("我记得大学时看过一本人类学的书，里面有一个与那种理论类似的新月沃地理论——", "莉琉")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_FertileCrescent.png")
	await novel_interface.show_dialog("书中认为，人类能有今天的文明，很大程度上是因为与非洲地理上相连的是西亚的两河流域。", "莉琉")
	await novel_interface.show_dialog("那片被称为新月沃地的区域，连马萨达人说的『应许之地』也一并包含在内。", "莉琉")
	await novel_interface.show_dialog("对人类影响最大的五种可驯化的大型动物是绵羊、山羊、牛、猪、马，而新月沃地能找到其中四种。", "莉琉")
	await novel_interface.show_dialog("对早期农业活动最重要的三种植物是大麦、小麦和豆类，新月沃地居然都能找到。", "莉琉")
	await novel_interface.show_dialog("人类的祖先走出非洲来到新月沃地，就像遇到了游戏中设定好的新手资源池。", "莉琉")
	await novel_interface.show_dialog("不觉得同样很不可思议吗？", "莉琉")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("就是说呀……", "爱衣")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Memory.png")
	await novel_interface.show_text_only("就像在危险任务中，一开始就穿着全套能保证自己生存下来的装备一样……")
	await novel_interface.show_text_only("那是不知要死掉重来多少次才能获得的经验。")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("听起来完全……不可能呢~", "爱衣")

	print("=== 星尘降临篇第21话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
