# stardustdescends_ep08.gd - 星尘降临篇第8话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep08_script()

func play_script():
	pass

func stardustdescends_ep08_script():
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Masada0.png")
	await novel_interface.show_text_only("第三学园都市——马萨达堡。")
	await novel_interface.show_text_only("一座建在沙漠中的军事要塞，特产是死海泥、沙尘暴和恐怖袭击。")
	await novel_interface.show_text_only("在大多数人的记忆中，伴随马萨达堡的新闻不是军事冲突就是人道主义灾难。")
	await novel_interface.show_text_only("血与沙、原油与白烟勾勒出的死亡曲线常年交织在这片古老的土地上……")
	await novel_interface.show_text_only("那里人的生活是什么样子的？\n我完全无从想象……")
	await novel_interface.show_text_only("但又有种莫名的熟悉感，就像我曾亲历过一般……")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("唉——", "小怜")
	novel_interface.change_music("res://assets/audio/music/unkown/UI_Main_Funk.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/Vessel.png")
	await novel_interface.show_text_only("我背靠在甲板的栏杆上，小星尘像树袋熊一样紧紧抱着我，泪水还隐隐的在她眼眶里打转。")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("好啦好啦，我刚才只是开个玩笑——", "小怜")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("喂喂你轻点，指甲都快抠我肉里啦……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","tear",0.25)
	await novel_interface.show_dialog("呜呜…………", "小星尘")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("别、别用我衣服擦鼻子啊！！！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我无奈的叹口气，安抚的摸了摸她的头。")
	await novel_interface.show_text_only("刚才爱衣推测小星尘所指的方向是马萨达堡，但询问一番后发现她对这个地名完全没印象。")
	await novel_interface.show_text_only("或者说，她连『学园都市』这个概念都不知道……")
	await novel_interface.show_text_only("莉琉说要先整理一下情报，让我在甲板待命，等一会再联系。")
	await novel_interface.show_text_only("我心里还是无法接受这家伙居然是只有我能看到的幻像，想趁机再做几个测试——")
	await novel_interface.show_text_only("我先把手机放在地上，要她帮我捡起来。")
	await novel_interface.show_text_only("然而她对我的要求只是报以礼貌性的微笑，歪着脑袋摆出一脸“你是弱智吗？”的表情。")
	await novel_interface.show_text_only("对峙了大约三十秒之后，我只能尴尬的自己捡起手机，随后又冒出个更蠢的点子——")
	await novel_interface.show_text_only("“既然她没有实体，那是不是可以穿墙呀？”")
	await novel_interface.show_text_only("于是我在她的注视下走回船舱，锁上船舱通往甲板的门，并藏进她的视线盲区。")
	await novel_interface.show_text_only("两分钟后，门的另一侧隐隐传来抽泣的声音，我觉得不妙赶忙开门，她一把抱住我的大腿就不放了。")
	await novel_interface.show_text_only("为了避开船舱内偶尔经过的侍者，我艰难的拖着她挪到了栏杆边上。")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("（拖着这么个腿部挂件，我走都走不动啊……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("带孩子原来这么辛苦的吗！？")
	await novel_interface.show_text_only("更糟的是别人还看不到她，现在的我看起来一定像个自言自语还肢体不协调的神经病。")
	await novel_interface.show_text_only("被她赖得实在没辙，我只能轻声细语的哄。")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("乖啦，我不会丢下你的~", "小怜")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("刚才是我不好，我道歉好吧？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("说着对她做了个傻乎乎的鬼脸。")
	await novel_interface.show_text_only("如果被人看到我对着空气挤眉弄眼，我绝对立刻从甲板缝里钻进去。")
	await novel_interface.show_text_only("小星尘稍稍平复一些，抱着我抬起头，眼睛眨巴眨巴，头上的耳朵闪了闪。")
	novel_interface.show_character("stardust_small","tear")
	await novel_interface.show_dialog("那你答应我，跟我去那个方向好不好……", "小星尘")
	await novel_interface.show_dialog("真的，真的很重要……", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("你刚才不会是装哭吧？")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("（小孩子果然很难搞啊……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("也不知道莉琉会不会同意，我带着这个小家伙去那么危险的地方。")
	await novel_interface.show_text_only("突然，耳机传来一阵电流音，莉琉恢复了连线。")
	await novel_interface.show_dialog("小怜，安妮，你们对马萨达堡有多少了解？", "莉琉")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("嗯……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("大概……", "安妮")
	await novel_interface.show_text_only("我努力回忆着，即使在SID特工培训的课程中，关于马萨达的信息也十分零散。")
	await novel_interface.show_dialog("第三学园都市，位于西亚腹地的堡垒都市，内外城区之间被几十米高的隔离墙分开。", "安妮")
	novel_interface.show_character("ren_full","bored")
	await novel_interface.show_dialog("好像是因为种族还是宗教矛盾什么的原因？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("总之马萨达外城区似乎很危险，每个月都有一两起爆炸恐袭的样子！")
	await novel_interface.show_dialog("他们的情报机构——马萨达复兴使命局是由军方直接控制的，作风大胆激进。", "安妮")
	novel_interface.show_character("ren_full","happy")
	await novel_interface.show_dialog("啊我知道，那个机构又叫『摩诺拉』吧？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那是经常出现在电影和游戏中的名字，但很少作为主要阵营。")
	novel_interface.show_character("ren_full","smile")
	await novel_interface.show_dialog("对了，他们的武器很先进，游戏里马萨达都是负责给玩家提供遥控战车和无人机什么的……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("好了，到此为止——", "莉琉")
	await novel_interface.show_dialog("那片区域的地缘政治环境一向很复杂，加上抵抗军和分裂组织就更混乱了。", "莉琉")
	await novel_interface.show_dialog("不过单论马萨达『内城区』的话，其安全性并不亚于新丰洲，所以——", "莉琉")
	novel_interface.show_character("ren_full","perspire1")
	await novel_interface.show_dialog("诶？难道说……\n你同意了？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一直抱着我大腿的小星尘似乎有些开心的扭了扭。")
	await novel_interface.show_dialog("就我们两个……没问题吗？", "安妮")
	await novel_interface.show_text_only("三个！是三个！！\n这儿还有个拖油瓶！！")
	await novel_interface.show_dialog("这又不是间谍行动，现在连具体要前往的目的地都不明确，你们别做出格的事就行了。", "莉琉")
	await novel_interface.show_dialog("而且你们也不需要换船，这艘赌船明天一早就会停靠在马萨达港啦~", "爱衣")
	await novel_interface.show_dialog("……怎么回事？不是要去萨蒙顿吗？", "安妮")
	await novel_interface.show_dialog("马萨达三天后要和抵抗组织签署停火协议，在签署仪式完成前苏伊士运河会全面封锁。", "莉琉")
	await novel_interface.show_dialog("赌场为了乘客安全考虑，刚刚决定遵从马萨达军方的“强烈建议”，退回到埃拉特。", "莉琉")
	await novel_interface.show_dialog("这艘船会顺着红海-死海大运河一路北上，在马萨达港停靠，直到苏伊士运河的封锁解除。", "莉琉")
	await novel_interface.show_dialog("安妮的伪装身份是新丰洲艺术交流项目的学生，手续已经办好了。", "莉琉")
	await novel_interface.show_dialog("至于小怜——你的伪装身份很可能已经被马萨达海防登记了，就继续当你的小护士吧~", "莉琉")
	await novel_interface.show_text_only("莉琉的话语中带着让我略感不妙的笑意。")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("诶？？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("总之你们要等协议签署完再行动，这两天就在城内旅游观光吧~", "爱衣")
	await novel_interface.show_dialog("如果那孩子想去的地点在城区外的话，我三天后再安排那边情报站的人接应。", "莉琉")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("连苏伊士运河都封锁了啊……", "小怜")
	await novel_interface.show_dialog("签署一份协议而已……需要搞得这么严重吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_dialog("因为……", "爱衣")
	await novel_interface.show_dialog("因为事态已经很严重了呀——", "爱衣")
	await novel_interface.show_dialog("你们这两天一直在船上，还不知道吧？", "莉琉")
	await novel_interface.show_dialog("怎、怎么回事……？", "安妮")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("十几个小时前，马萨达境内希伯仑市的易卜拉清真寺附近发生了一起工业化学品爆炸事故。", "莉琉")
	await novel_interface.show_dialog("爆炸的冲击波造成了附近建筑一定程度的垮塌，同时破坏了电力、供水和燃气系统。", "莉琉")
	await novel_interface.show_dialog("根据官方的说法，目前那一带的居民已经全部被疏散到安全区了。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("又是恐怖袭击？", "小怜")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("易卜拉清真寺下面的麦比拉洞，是传说中马萨达人先祖的墓穴。", "爱衣")
	await novel_interface.show_dialog("虽然自打他们在上个世纪接管那座城市以后，就从没进行过考古发掘……", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("而且奇怪的是，官方虽然给出了合乎情理的人员伤亡报告，但消息的封锁过于严密了……", "爱衣")
	await novel_interface.show_dialog("网上连附近居民拍摄的录像都找不到，关于这条新闻的页面全都是马萨达官方提供的照片和视频。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("同时希伯仑市内几家大型医院的电子系统全都出现了故障，急诊记录大面积丢失。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("事故发生后，马萨达方面几乎立刻回绝了世界遗产组织对麦比拉洞窟遗迹进行协助抢救的提议。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("这么明目张胆的情报控制，确实像『摩诺拉』的风格……可他们为什么要封锁信息？", "安妮")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("可能是不想事态变得更复杂吧——", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("从卫星图像分析，那大概率是由小型火箭弹引起的爆炸。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是抵抗军？\n可他们不是快签停火协议了嘛……", "小怜")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("抵抗军领袖立刻在社交账号上表示这次事件与他们无关，还表示了遗憾和谴责。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("目前情报组猜测这次袭击可能是抵抗军内部某个分支派系发动的，那群家伙从来都不是铁板一块呐~", "爱衣")
	await novel_interface.show_dialog("虽然领导人希望停火，但内部的极端分子并不希望达成这个协议吧？", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("或许是的，但这些都只是推测，而这三天毫无疑问是第三学园都市最敏感的时期——", "莉琉")
	await novel_interface.show_dialog("相应的，马萨达的安防等级也达到了最高，你们在内城区比在公海上更安全。", "莉琉")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("今晚好好休息吧，明天等你们到港口再联络。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("好的！", "小怜")
	await novel_interface.show_dialog("明白~", "安妮")
	await novel_interface.show_text_only("说罢，莉琉切断了与船上二人的连线，目光移向大屏幕上一位红衣女性的视频图像。")
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("……你也觉得不大对劲吧？", "秋子")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("是啊，这份协议宣布得太过突然了——", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("上周，马萨达政府发言人突然宣布，将在十天内与抵抗军签署停火协议。", "莉琉")
	await novel_interface.show_dialog("虽然各国政府和媒体一致赞扬，而且裁军停火确实也是大势所趋。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("——但这份协议还是显得太急躁了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("确实，不像施恩内曼总理谋定而后动的风格。", "秋子")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("是因为他的病情恶化超过预期吗……？", "爱衣")
	await novel_interface.show_dialog("上次和平论坛之后到现在，施恩内曼总理还一次都没在公开场合露过面呢~", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("或许不止这一个原因——", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("马萨达国防军内部的矛盾应该快要无法弥合了。", "莉琉")
	await novel_interface.show_dialog("在人员和预算都面临大幅缩减的时候，军功派的军官们和那帮搞技术的撕破脸只是时间问题。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("国防军内部学院系统出身的技术派和在前线拼杀获得功勋的军功派的争夺吗……", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉微微点了点头。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("而马萨达至今也没确定，会由谁作为代表来签署这份历史性的协议——", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("能在全世界的关注下领取这份不世之功的人，有极大概率在之后的选举中胜出吧？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("必然……", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("秋子好像忽然明白了什么，轻轻发出一声“啊”。")
	novel_interface.show_character("akiko","shock")
	await novel_interface.show_dialog("马萨达不希望签署仪式被这次袭击影响，所以才声称这是化学品爆炸事故吗……", "秋子")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("啧啧，你内心动摇的样子还是这么可爱呢~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","shy")
	await novel_interface.show_dialog("（小声）……变态。", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("秋子脸颊微红，轻轻咳嗽了两声。")
	novel_interface.show_character("akiko","shy")
	await novel_interface.show_dialog("那你找到了吗？", "秋子")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("——上次说的合适的『人选』。", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉摇了摇头。")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("要是这么简单就能找到的话，施恩内曼老爷子也不会坚持到现在还不退休了吧……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("第二天上午，8点40分。")
	await novel_interface.show_text_only("『自由之星』号赌船，VIP餐厅。")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat4.png")
	await novel_interface.show_text_only("贵宾餐厅位于船舱的顶层，这里虽然面积不大，但视野绝佳。")
	await novel_interface.show_text_only("窗外阴云密布，深沉的海面似乎酝酿着某种不祥的灾厄。")
	await novel_interface.show_text_only("或许因为大多数客人都被昨晚赌场不限量的免费酒水灌晕，此时餐厅内只有我们一桌客人。")
	await novel_interface.show_text_only("我望着窗外发呆，那片深蓝色的海面就是联通着红海和死海的马萨达运河。")
	await novel_interface.show_text_only("这条运用异质物技术，由第一和第三学园都市联合修建的运河长180公里，两端海拔落差达430米。")
	await novel_interface.show_text_only("从亚喀巴湾北端的埃拉特港，一路通往到死海西南岸的马萨达堡。")
	await novel_interface.show_text_only("作为马萨达的生命线，这条运河从规划之初就伴随着与周边众多小国的冲突和纷争。")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("前面就是最后一道船闸了吧？\n好厉害的工程呐……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮在手机上找到了关于这条运河的纪录片，拉着我一起看。")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("是啊，经理说昨天夜里咱们已经通过了三道落差超过一百米的巨型船闸……中午前就能到了。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我拉了拉国际医疗救援组织派发的这件有些过分宽大的外套。")
	novel_interface.show_character("ren_medical","shy")
	await novel_interface.show_dialog("（居然是均码……它们没有女款吗！？）", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","smile",0.25)
	await novel_interface.show_dialog("你怎么里面只穿了件吊带裙和打底裤啊？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮有些玩味的打量着我。")
	novel_interface.show_character("ren_medical","shy_left")
	await novel_interface.show_dialog("我没带那么多衣服啦！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("谁知道突然改变行程，还好便利店有卖内裤和那个\n……")
	await novel_interface.show_text_only("我有些不好意思的拉了拉吊带裙，这件衣服本来是带来当备用睡衣的。")
	novel_interface.show_character("ren_medical","shy_right")
	await novel_interface.show_dialog("（裙子下沿还有一小圈浅色的蕾丝，丢死人了！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","happy")
	await novel_interface.show_dialog("呐呐……", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小星尘扑过来摇着我的胳膊说道。")
	novel_interface.show_character("stardust_small","smile")
	await novel_interface.show_dialog("这集看完了，帮我换下一集~", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我从那个用餐巾布叠成的临时支架上拿过手机点了几下，然后放回她座椅面前的桌面上。")
	await novel_interface.show_text_only("她就乖乖的趴在那饶有兴致的看动画片。")
	novel_interface.show_character("anne_uniform","relieve")
	await novel_interface.show_dialog("这孩子不闹腾的时候还挺可爱的嘛……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮端详着手中那粒金平糖一样的小颗粒，将目光移向小星尘。")
	await novel_interface.show_text_only("昨晚，我们发现只要接触一次这颗从赌船保险库里找到的金黄色颗粒状物体，就能看到小星尘。")
	await novel_interface.show_text_only("但安妮无法像我一样摸到她，整体感觉就像在看立体投影一般。")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("亏你能想到把这东西藏在那里从保险库里带出来。", "安妮")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("我就不一定做得到呢……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮悄悄摸了摸胸口。")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("只、只是因为那件礼服夹的比较紧啦……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮露出一个勉强的笑容，假装有被我安慰到。")
	await novel_interface.show_text_only("昨晚汇报这个情况的时候，爱衣猜想星尘是以某种特殊形式存在的信息结合体。")
	await novel_interface.show_text_only("而那颗金平糖模样的东西应该存储着小星尘的人格信息——")
	await novel_interface.show_text_only("若要类比的话，就像是人类的“灵魂”。")
	await novel_interface.show_text_only("但这个灵魂却丢失了记忆，或许是由于年代久远或其他什么因素，具体原因爱衣也无法确定。")
	await novel_interface.show_text_only("我看着这个趴在桌面上津津有味的看着几十年前的搞笑动画的小家伙。")
	await novel_interface.show_text_only("那部动画片我小时候也看过，印象还挺深的——")
	await novel_interface.show_text_only("剧情是主角和自己不太负责任的妈妈住在热带雨林里，有天一个奇怪的小女孩突然出现……")
	novel_interface.show_character("ren_medical","bored")
	await novel_interface.show_dialog("（诶？这剧情怎么有点像……）", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	await novel_interface.show_dialog("小怜，保险库的那枚陨石是四千年前坠落在地球上的吧？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮的话打断了我的思绪。")
	novel_interface.show_character("ren_medical","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊是的，四千年前啊……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("是绳文还是什么时代来着……吓，历史课本的内容考完试就忘光不是理所当然的吗。")
	novel_interface.show_character("ren_medical","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这家伙不会是外星人吧……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("小星尘忽然被动画某个情节逗笑，没心没肺的笑了起来，耳朵上的灯也亮得此起彼伏。")
	novel_interface.show_character("ren_medical","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","relieve",0.25)
	await novel_interface.show_dialog("应该不是，你看她看动画片时候傻笑的样子，和你简直一个模子刻出来的——", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("有、有吗？")
	novel_interface.show_character("ren_medical","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","unhappy",0.25)
	await novel_interface.show_dialog("我说……小怜以前是男孩子吧？", "安妮")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("你之前有没有……就是……", "安妮")
	novel_interface.change_2nd_expression("shy")
	await novel_interface.show_dialog("对女生做过一些不负责任的事情啊？", "安妮")
	await novel_interface.show_dialog("这孩子跟你这么亲，会不会是你之前在外面……", "安妮")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("别、别乱讲啊！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我是男生的时候连初吻都没有过！！")
	novel_interface.show_character("ren_medical","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","relieve",0.25)
	await novel_interface.show_dialog("哦~？真的嘛？", "安妮")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("小怜原来这么纯情吗~", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮把脸凑近，一脸狐疑的看着我，我赶忙胡乱的转移话题。")
	novel_interface.show_character("ren_medical","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你、你看外面，那边的地平线……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我们从落地窗远望，东边的地平线上飘着一团诡异的暗红色云雾。")
	novel_interface.show_character("ren_medical","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","panic",0.25)
	await novel_interface.show_dialog("那是……", "小怜")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("什么东西……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我和安妮看着远处那片异象面面相觑，小星尘则头也不抬的说道——")
	await novel_interface.show_dialog("沙尘暴。", "小星尘")

	print("=== 星尘降临篇第8话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
