# stardustdescends_ep4.gd - 星尘降临篇第4话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep4_script()

func play_script():
	pass

func stardustdescends_ep4_script():
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	await novel_interface.show_text_only("几小时后，播磨脑研科学综合研究中心。")
	await novel_interface.show_text_only("身穿白大褂的瘦小女性一边用耳机通话，一边懒洋洋在平板电脑上滑动着手指。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("放心好啦，那两个乖宝宝都在好好的做梦呢。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("嘿嘿，可不要小瞧人类大脑将自身处境合理化的强大意愿和能力哦——", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣瞥了一眼病房，两个穿着黑色西服的男人分别躺在两台潜脑装置上。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("毕竟只有自己编造的故事才最能骗过自己嘛~", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然，爱衣被平板上显示的内容所吸引，她快速向下翻了几屏，接着又返回再次确认。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("喂喂喂，这个数据……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("怎么了？", "莉琉")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("小怜和倪克斯额头触碰的时候，别墅监视器上的玻尔兹曼探针读数有一瞬间爆表了！？", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("会不会是设备故障……你调整后的测量范围不是已经达到理论极值了吗？", "莉琉")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("只是接近而已，如果信息量逼近贝肯斯坦上限的话我也没办法……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你的意思是说，那一瞬间爆发的信息量逼近了物质所能携带的信息上限？", "莉琉")
	await novel_interface.show_text_only("爱衣快速在平板上进行着计算。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("如果先不考虑那个异常的话，倪克斯的特征数据倒是与魔女完全吻合，可她自己似乎没察觉到？", "爱衣")
	await novel_interface.show_dialog("是和拉斐尔类似的状况吗？\n要是索娅没被派遣出去就方便了……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣一边抱怨，一边打开了读数异常期间别墅内的监控录像。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("而且肯定不是机械故障，读数很快就恢复到了正常水平，探针送回来时的状态也很完好。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("更重要的是，当时只有小怜突然失去意识，在场的其他人似乎完全没被影响……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣快速排除着各种不合逻辑的假设，似乎最后只剩下一个解释——")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("就是说小怜一个人，将瞬间爆发出超过2.5YB的信息在不到一秒之内完全吸收了？", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在说出推理结果之后，爱衣自己都有些不敢相信。")
	await novel_interface.show_dialog("……YB是多大的单位来着？", "莉琉")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("1YB是10的24次方比特，这个信息量超过了战前整个互联网的容量总和……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣尽量压抑着她因兴奋而颤抖的语调。")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("我还以为那个小可爱的脑袋瓜除了游戏攻略以外装不下什么东西了呢~", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("等等，10的24次方的计量单位还叫做『尧』吧？似乎在施教授的那份情报里也出现过！", "莉琉")
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("你是说华云宫的那块古代陨石……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣快速将刚才的纸质情报照片调出来，沉吟了好一阵。")
	novel_interface.show_character("ai","blush_wink")
	await novel_interface.show_dialog("哦呀呀，搞不好这件事只能靠小怜了。", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("5天后，莱博娜『自由之星』号赌船。")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat.png")
	await novel_interface.show_dialog("咳咳，这位小姐……", "荷官")
	await novel_interface.show_dialog("这位小姐？", "荷官")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("唔……啊？", "小怜")
	await novel_interface.show_dialog("弃，弃牌……", "小怜")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("不好意思，下局我退出~~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女离开牌桌，走到过道拐角找了个没人的角落。")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("刚才那把是同花诶！为什么非要我弃牌啊~！", "小怜")
	await novel_interface.show_dialog("（小声）而且前两轮都跟注那么多了……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然压低着声音，但小怜的话语中透露着明显的不甘心。")
	await novel_interface.show_dialog("喂喂小怜，别自言自语的，拿出手机假装打电话好一点吧。", "安妮")
	await novel_interface.show_dialog("船上有三个监控室，我只扫荡了其中一个……", "安妮")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("（扫、扫荡？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("这艘赌船虽然不大但遍布着摄像头，被人发现你戴着微型耳机的话，多半会被丢进海里喂鲨鱼哦。", "倪克斯")
	await novel_interface.show_text_only("我打了个激灵，立马从手包里掏出手机。")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("都输掉两成多的本金了，不是说要赢到翻倍才能进入贵宾室吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着赌场派发手环上显示的筹码数量，我不停安慰自己这是莉琉的钱这是莉琉的钱……")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("（可说到底这也是新丰洲市民的税金啊！！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Dispatched_Ship_Aisle.png")
	await novel_interface.show_text_only("海拔三万米的高空，SID所属高速重型运载机上，倪克斯端着一杯红茶盯着投影屏幕。")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("刚才你只有方片2和6，从对方的行为看来他有大概率也中了同花，而且牌面几乎肯定比你大。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("诶！？\n我刚才都想ALL-IN了……", "小怜")
	novel_interface.show_character("nyx_normal","speak")
	await novel_interface.show_dialog("唉……", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她无奈的叹了口气，思考着怎么解释才能让这个昨晚抱着五千万筹码流了一夜口水的笨蛋听明白。")
	novel_interface.show_character("nyx_normal","normal2")
	await novel_interface.show_dialog("菜鸟最常犯的错误就是，遇到好牌就想快点下重注甚至ALL-IN，反之就恨不得马上弃牌。", "倪克斯")
	await novel_interface.show_dialog("尤其是拿到好牌的时候，很容易热血上涌从而丧失收集场上信息的能力，陷入盲目无知的状态。", "倪克斯")
	await novel_interface.show_dialog("无知导致恐惧，恐惧导致鲁莽，所以菜鸟只能通过ALL-IN来释放内心的恐惧。", "倪克斯")
	novel_interface.change_expression("sad")
	await novel_interface.show_dialog("在把筹码全部推入底池的那一刻，他才终于获得了自己灵魂的自由。", "倪克斯")
	await novel_interface.show_dialog("结果就是对手很容易根据他的行为预测选择。", "倪克斯")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("所以很多人拿到好牌却赢不到钱，直到某局被对手更好的牌一把吃光——", "倪克斯")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("在赌场里一夜输个倾家荡产的基本都是这种笨蛋。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("噫！", "小怜")
	await novel_interface.show_text_only("小怜的身体好像被一支箭射中，微微颤抖了一下。")
	await novel_interface.show_text_only("倪克斯满意的端起茶杯抿了一口，接着说道。")
	novel_interface.show_character("nyx_normal","mock")
	await novel_interface.show_dialog("听好了，德州扑克是轮流行动的游戏——", "倪克斯")
	await novel_interface.show_dialog("你最应该关注的是与你一起在底池下注的对手，而不是自己手里的牌。", "倪克斯")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Choice.png")
	await novel_interface.show_dialog("当你做出行动之后，对手只有三个选择，『弃\n牌』、『跟注』或者『加注』。", "倪克斯")
	await novel_interface.show_dialog("所以你行动的首要原则是：让对手找不到支撑自己选择任何一种行动的理由。", "倪克斯")
	await novel_interface.show_dialog("最好的状态是，在对方看来，似乎每个选择都是对的，或者说每个选择都不对。", "倪克斯")
	await novel_interface.show_dialog("好像……有点道理……", "小怜")
	await novel_interface.show_dialog("当人面对信息黑洞，找不到最优选择，每次出手就都会处于万分纠结和痛苦的状态——", "倪克斯")
	await novel_interface.show_dialog("就像是在经历一场心灵和意志的折磨，需要尽快找到一个解脱。", "倪克斯")
	await novel_interface.show_dialog("那时就是你在支配局势，将他吃干抹净的最好时机\n~", "倪克斯")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("吃干…抹净……？", "小怜")
	await novel_interface.show_text_only("我回味着学姐的教导，小心翼翼的点了点头。")
	await novel_interface.show_dialog("（学姐到底是怎么学会这些的……）", "小怜")
	await novel_interface.show_dialog("（总之千万不能让我和她一起打牌啊！！）", "小怜")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat.png")
	await novel_interface.show_text_only("我乖巧的回到牌桌，在学姐指挥下，用了不到一个小时就使自己手中的筹码翻了一倍。")
	await novel_interface.show_text_only("其中赢的最大的一把，我刚押上全部筹码，就听到耳机里学姐和爱衣讨论起我的睡相。")
	await novel_interface.show_text_only("而且两个人居然还开始交换照片！听得我的脸红一阵紫一阵。")
	await novel_interface.show_text_only("对手看我慌张的神态以为我在诈唬，也跟着一起全推了。")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("虽然赢了，但总觉得她们……", "小怜")
	await novel_interface.show_dialog("啊啊啊啊实在想不下去啦！", "小怜")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat3.png")
	await novel_interface.show_text_only("在侍者引导下，我终于进入了赌船VIP区域。")
	await novel_interface.show_text_only("这个房间与大厅的感觉完全不同，装修、摆设甚至座椅的质地都更加高级。")
	await novel_interface.show_text_only("三个穿着考究的男人在牌桌上喝得微醺，远处沙发上几个身材火辣的姐姐正在叽叽喳喳的聊天。")
	await novel_interface.show_text_only("自由之星号本就是针对高端赌客的小型赌船，周身覆盖着灰色的装甲，外观极其低调。")
	await novel_interface.show_text_only("想要上船最低要买入两千万的筹码，船上总共也只有不到几十名客人。")
	await novel_interface.show_text_only("而想要进入VIP区域，更是要在任意莱博娜的赌场累计盈利五千万以上。")
	await novel_interface.show_text_only("按照莉琉的指示，我将一亿现金兑换成了一枚金色筹码，上面雕刻着精美的莱博娜徽记。")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("这就是那枚传说中的……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("使用异质物材料作为外壳，能抵抗强冲击、强磁场和高温，可以在全球数百家赌场兑现。")
	await novel_interface.show_text_only("可以说是全世界最大额的不记名债券。")
	await novel_interface.show_dialog("监控劫持已经完成了，随时可以动手哦。", "安妮")
	await novel_interface.show_text_only("终于，耳机中传来了让人安心的声音。")

	print("=== 星尘降临篇第4话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
