# stardustdescends_ep07.gd - 星尘降临篇第7话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep07_script()

func play_script():
	pass

func stardustdescends_ep07_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Vault.png")
	await novel_interface.show_text_only("我本能的想要尽快离开这里，偷偷对小星尘使了个眼色，然后一言不发的朝着电梯大门走去。")
	await novel_interface.show_text_only("她马上心领神会的小跑几步跟上来，留下在那里继续审问侍者的艾米莉欧。")
	await novel_interface.show_text_only("小家伙似乎从我略显僵硬的动作中察觉到了不安的情绪，轻轻蹭了蹭我的手腕。")
	novel_interface.show_character("stardust_small","normal2")
	await novel_interface.show_dialog("（小声）呐呐~", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("感到那从柔软肢体传来的温度，我的心境渐渐平静下来，默默拉住了她的小手。")
	novel_interface.show_character("stardust_small","normal2")
	await novel_interface.show_text_only("就像达成了某种默契般，她露出一个灿烂的笑容。")
	await novel_interface.show_text_only("说来奇怪，虽然是第一次见面，我却对她有种莫名的熟悉和亲切感。")
	await novel_interface.show_text_only("而且刚才那些人，无论侍者还是士兵，为什么全都对她视若无睹呢？")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("在电梯里，我一边思考一边捏了捏小星尘软乎乎的脸，引起了她一阵抗议。")
	novel_interface.show_character("ren_full","gratified")
	await novel_interface.show_dialog("（不过还好，这让人安心的触感和体温……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("或许这孩子和贝阿特丽切的情况类似，有着某种自己无法控制的特殊能力吧？")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat3.png")
	await novel_interface.show_text_only("正当我胡乱猜测着种种可能性，电梯已经带我们回到了赌船的VIP区。")
	await novel_interface.show_text_only("随着厚重的电梯大门缓缓打开，我才意识到事态的严重性。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Gambling_Boat.png")
	await novel_interface.show_text_only("几十名乘客和工作人员被装备自动武器的马萨达士兵控制在大厅，分成四人一组正接受安检。")
	await novel_interface.show_text_only("记录员拿着军用的平板设备，无视客人们的抗议挨个给他们拍照建档。")
	await novel_interface.show_text_only("大厅的墙壁上挂着定向信号干扰装置，那些想打电话联系高层关系的客人们纷纷拿着手机一筹莫展。")
	await novel_interface.show_text_only("我的手机和耳机此时也收不到任何信号，小星尘看到这幅阵仗，本能的缩到了我身后。")
	await novel_interface.show_text_only("大厅出口处，一个军官样子的人用扩音器宣读着接受安检时的注意事项。")
	novel_interface.show_character("valkyrja","normal")
	await novel_interface.show_dialog("全部手表、首饰和金属物品都要摘下来接受检查。", "军官")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("个人包裹和行李箱要在建档后贴上识别码，集中在这边进行扫描。", "军官")
	await novel_interface.show_dialog("全部检查通过后会得到一个蓝色手环，戴着手环的人才可以离开大厅！", "军官")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("这么严格的吗？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看了看手腕上的蓝色手环。")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("（这说明我……已经通过检查了？）", "小怜")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("（还、还是先看看情况吧……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("环视四周，我发现这一层的军人中只有那个军官是女生，而且她和刚才的艾米莉欧一样都很年轻。")
	await novel_interface.show_text_only("让我有些不解的是，那些穿着蓝色迷彩作战服的海军士兵们似乎都很服从这个人。")
	novel_interface.show_character("ren_full","bored")
	await novel_interface.show_dialog("（看起来也就是高中生或者刚上大学的年纪吧…\n…）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然，一个硕大的身影不顾阻拦冲到大厅门口并朝军官大喊起来。")
	novel_interface.show_character("miller")
	await novel_interface.show_dialog("我是南印度圣公会的米勒总主教，你们无权盘查神职人员！", "米勒")
	await novel_interface.show_dialog("而且你这身根本不是马萨达国防军的军服吧？", "米勒")
	await novel_interface.show_dialog("你到底是什么人？这次行动是谁授权的？", "米勒")
	await novel_interface.show_dialog("我要求和你的长官谈话！", "米勒")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("总主教大人像座小山一样站在那个女生面前，气势咄咄逼人。")
	novel_interface.show_character("valkyrja","normal2")
	await novel_interface.show_dialog("啊？这身当然不是国防军的军服了……我是临时指挥准尉薇拉·瓦尔基里。", "军官")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("你刚说你是南……南印度的什么玩意儿？\n啊！是税务官之类的吧~", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("薇拉好似恍然大悟的打量着面前的男人，自言自语的说道。")
	novel_interface.show_character("valkyrja","speechless")
	await novel_interface.show_dialog("怪不得吃成这样……", "薇拉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("不过那破地方不是一直在打仗吗？能收上税来？", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她全然不顾主教大人已涨红的脸，心不在焉地接过记录员递来的平板设备。")
	novel_interface.show_character("valkyrja","happy")
	await novel_interface.show_dialog("哦~神职人员签证啊……", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("薇拉不屑的笑了笑，接着看向不远处的轮盘赌桌。")
	novel_interface.show_character("valkyrja","happy")
	await novel_interface.show_dialog("呵呵，原来是教廷的人，怪不得白白胖胖的，您老人家刚才玩的尽兴吗？", "薇拉")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("我还以为上帝不会掷骰子呢~", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("miller")
	await novel_interface.show_dialog("你说什么！！？", "米勒")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("总主教大人终于绷不住了，大叫着上前两步一副要打人的样子，却被薇拉一手抓住了领子。")
	await novel_interface.show_text_only("我不由倒抽一口凉气——")
	await novel_interface.show_text_only("那个身材肥硕的总主教被薇拉用一只手卡住脖子时双脚稍稍的离开了地面。")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("（那是什么怪力啊！！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","speechless")
	await novel_interface.show_dialog("啊……你要是没听清楚我就再说一遍——", "薇拉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("我可不是什么士兵，而是被临时分配来处理这种破事的『塔楼计划』学员。", "薇拉")
	await novel_interface.show_dialog("军事委员会的那群混蛋，觉得随便安一个临时军衔就能对我们呼来喝去。", "薇拉")
	await novel_interface.show_dialog("我已经忍耐好几天了，你若是想惹事，我马上就把你丢海里喂鲨鱼！", "薇拉")
	await novel_interface.show_dialog("听清楚了吗！？", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("此时男人的脸颊已经涨得发紫，无法发出声音的他忙不迭的点了点头。")
	novel_interface.show_character("valkyrja","angry")
	await novel_interface.show_dialog("滚那边排队去！", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("终于被松开的总主教大人踉跄后退几步，捏着脖子喘了几口粗气，然后悻悻的走向安检队伍。")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("那个，请问……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我小心翼翼的凑过去，晃了晃腕上的手环。")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("拿到这个就可以出去了是吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("薇拉似乎有些意外，用平板对着我手环上的条形码扫了一下，随后露出一个微笑。")
	novel_interface.show_character("valkyrja","wink")
	await novel_interface.show_dialog("嗯，没问题，你可以离开了。", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我稍稍松一口气，同时暗自庆幸这层的人也看不到小星尘。")
	await novel_interface.show_text_only("刚走出门，大厅外的一位赌船工作人员就走过来对我再三表示抱歉。")
	await novel_interface.show_text_only("他说关于今天的事莱博娜会与马萨达进行交涉，绝对确保客人资料的保密性。")
	await novel_interface.show_text_only("现在船舱内全部处于信号屏蔽状态，他说我想要打电话的话可以用有线线路或者去船尾甲板。")
	novel_interface.change_music("res://assets/audio/music/unkown/UI_Main_Funk.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/Vessel.png")
	await novel_interface.show_text_only("我拉着小星尘一路来到甲板上。")
	await novel_interface.show_text_only("船舷的一侧停靠着最新型的超级德沃拉巡逻艇，旗杆上挂着马萨达标志性的蓝白两色国旗。")
	novel_interface.show_character("ren_full","smile")
	await novel_interface.show_dialog("啊——总算能出来透透气~", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("（赌场里所有窗户都是封闭的，快闷死我了。）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看着横跨运河的大桥舒展了一下双臂，这条人工河道的两岸一直延展到视野的尽头。")
	novel_interface.show_character("ren_full","gratified")
	await novel_interface.show_dialog("这就是苏伊士运河吧？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","happy",0.25)
	await novel_interface.show_dialog("哇——！", "小星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("小星尘比我还兴奋，蹦蹦跳跳的跑到了栏杆前。")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("（不过怎么是船尾对着这边……？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然手机响起，我赶忙接通，听筒中传来了久违的声音。")
	await novel_interface.show_dialog("小怜！你没事吧？", "安妮")
	await novel_interface.show_dialog("她没事，正对着大海做扩胸运动呢。", "莉琉")
	await novel_interface.show_dialog("哦呀呀，真是充满青春的气息~是想让身体吸满养料再发育一下吗？~", "爱衣")
	await novel_interface.show_text_only("这是多方通话，莉琉她们也在线上……")
	novel_interface.show_character("ren_full","awkward")
	await novel_interface.show_dialog("诶？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我立刻四下环视，并没发现监控之类的设备，才想起她们大概是从高空观察到的。")
	novel_interface.show_character("ren_full","shy")
	await novel_interface.show_dialog("（天上有双眼睛盯着自己总觉得怪怪的……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你就别捂了，先做个简报。", "莉琉")
	novel_interface.show_character("ren_full","shy_left")
	await novel_interface.show_dialog("呜呜……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我清清嗓子，汇报了在保险库发现小星尘的全过程\n，特别强调别人都看不到她这件事。")
	await novel_interface.show_dialog("那孩子现在就在你身边？我在监控里确实只看到你一个人穿过大厅……", "安妮")
	await novel_interface.show_dialog("当时我还在想你怎么这么快就做完安检了，你可是第一个出来的！", "安妮")
	novel_interface.show_character("ren_full","gratified")
	await novel_interface.show_dialog("是去保险库检查的一个海军少尉，她只读取我身份卡上面的内容就把通过的手环给我了。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("马萨达的海防部队不应该这么松懈……", "莉琉")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("还有，好像赌场大厅的军官和保险库的少尉都是不到二十岁的女孩子……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("怎么会？虽然马萨达的女性也要服强制兵役，但这个年纪也……", "安妮")
	novel_interface.show_character("ren_full","normal1")
	await novel_interface.show_dialog("对了，我听到大厅的那个军官说自己是什么“塔楼计划”学员，这是被临时分配的任务。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那就难怪了——", "莉琉")
	await novel_interface.show_dialog("塔楼（Talpiot）是直属于马萨达国防总参谋部的精英军校，有几十年的历史了。", "莉琉")
	await novel_interface.show_dialog("马萨达军方后来将其升级为塔楼计划，只从中学生和一般军校招收前1%的顶尖学员参与选拔。", "莉琉")
	await novel_interface.show_dialog("然后在心理、体能和智力测试中严格筛选，每年只有几十人能被正式录取。", "莉琉")
	await novel_interface.show_dialog("是个专门培养高级军官和军事科技人才的地方，课程中确实会参与指挥小规模的军事行动。", "莉琉")
	await novel_interface.show_dialog("『摩诺拉』里也有不少塔楼计划的学员，从那里出来的家伙虽然都是精英，但很难被策反。", "莉琉")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("就是某种精英学校吧……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("总觉得……我和小怜都不可能考上呢。", "安妮")
	await novel_interface.show_dialog("呐，小怜。", "爱衣")
	await novel_interface.show_text_only("爱衣的语气带着些许迟疑。")
	await novel_interface.show_dialog("你说的那个小孩子，此刻正跟你一起在甲板上吗？", "爱衣")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("对啊，怎么？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("可是热成像显示，现在甲板上的确只有你一个人…\n…", "爱衣")
	await novel_interface.show_text_only("我心中一惊，扭头看看蹲在栏杆前的小家伙，一直在出神的盯着某个方向。")
	await novel_interface.show_text_only("她忽然站起来，耳机上的金光快速闪烁，指向自己刚才盯着的方向。")
	novel_interface.show_character("stardust_small","happy")
	await novel_interface.show_dialog("我们……要去那边！", "小星尘")
	novel_interface.change_expression("pleased")
	await novel_interface.show_dialog("虽然忘记了为什么，但感觉必须去那个方向的什么地方不可。", "小星尘")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("不然就……不然就糟糕了……！", "小星尘")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("呐呐呐！我们一起去……好不好嘛？", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小星尘拉住我的手来回摇晃，眨巴着大眼睛，就像耍赖想要妈妈给自己买玩具的小孩子一样。")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("你们……听到她说的了吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("我一直只听到你的声音啊…", "安妮")
	await novel_interface.show_dialog("如果没有实体的话，是无法震动空气发出声音的。", "爱衣")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("可、可我明明能感觉到！她的触感和温度……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("从你的描述看来，很可能是你的大脑被某种东西影响，产生了只有你能体验到的神经反馈。", "爱衣")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("不是吧……我连她的影子都能看到！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我试着辩解，实在无法接受这个与自己的感知完全矛盾的解释。")
	await novel_interface.show_dialog("……你用手机的摄像模式试试看。", "莉琉")
	await novel_interface.show_text_only("我立刻照做，可当我用镜头对准她的时候，顿时感觉头皮一阵发麻——")
	await novel_interface.show_text_only("屏幕上的取景框内空空如也，全然没有她的身影。")
	await novel_interface.show_text_only("可当我将手机挪开，又能看到她鼓着小脸央求的样子。")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","happy",0.25)
	await novel_interface.show_dialog("好~~不~~好~~嘛~~", "小星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我不死心的在手包里寻找，翻出那个从她手腕取下写着她名字的粉色小纸条。")
	await novel_interface.show_text_only("但当我将手机对准那个纸条时，却发现自己手上什么都没有。")
	await novel_interface.show_text_only("手机挪开后，那个小纸条也消失不见了。")
	await novel_interface.show_text_only("我伸出有些颤抖的手，把手机放在小星尘的头顶。")
	await novel_interface.show_text_only("“啪嗒”一声，手机直接掉落在她脚下的甲板上。")
	novel_interface.show_character("stardust_small","konata_eye")
	await novel_interface.show_dialog("？", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我只觉耳边嗡嗡直响，四肢忽然变得沉重起来。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("过了一小会儿，我的耳机中传来了爱衣的声音。")
	novel_interface.show_background("res://assets/images/bg/Stardust/Vessel.png")
	await novel_interface.show_dialog("我有一个理论，或者说是猜测……", "爱衣")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("什、什么猜测？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你之前唤回的魔女，不仅能为她们制造出实体，而且都保留着完整的记忆。", "爱衣")
	await novel_interface.show_dialog("但根据你描述她的失忆情况，再加上没有实体，或许是缺失了某些条件？", "爱衣")
	await novel_interface.show_dialog("她有表达什么诉求吗？或许是某种提示？", "爱衣")
	novel_interface.show_character("ren_full","happy")
	await novel_interface.show_dialog("诉求……有的！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我像是抓住什么救命稻草般，指向了她刚才说的方向。")
	novel_interface.show_character("ren_full","happy")
	await novel_interface.show_dialog("她说她要去那边，但不知道具体是哪，就是我手指的方向！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听筒中立刻传来一阵敲打键盘的声音。")
	await novel_interface.show_dialog("那个方向前方318公里……", "莉琉")
	await novel_interface.show_dialog("就是马萨达堡。", "安妮")

	print("=== 星尘降临篇第7话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
