# stardustdescends_ep09.gd - 星尘降临篇第9话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep09_script()

func play_script():
	pass

func stardustdescends_ep09_script():
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Ordovician.png")
	await novel_interface.show_text_only("人们总乐于猜测，如果存在强大的外星文明，它们是善意的还是恶意的。")
	await novel_interface.show_text_only("更加可能答案的是——它们是无意的。")
	await novel_interface.show_text_only("4.49亿年前的一天，一束来自6000光年外的高能伽马射线穿透大气层，击中了地球。")
	await novel_interface.show_text_only("射线瞬间击毁了三分之一的臭氧层，阳光中的紫外线直接穿透大气层。")
	await novel_interface.show_text_only("大量浮游生物死亡，破坏了海洋食物链的基础，饥荒开始蔓延。")
	await novel_interface.show_text_only("灾难过后数十年，被击碎的大气分子重新组合，形成了大量有毒的二氧化氮气体。")
	await novel_interface.show_text_only("二氧化氮遮天蔽日，遮住了50%的阳光。地球失去阳光的照射，气温开始迅速下降。")
	await novel_interface.show_text_only("海洋温度由25度下降到10度，更多浮游生物的死亡加速了食物链的崩溃。")
	await novel_interface.show_text_only("灾难发生500年后，地球上三分之一的生物消失，剩下的生物在饥饿与严寒中挣扎。")
	await novel_interface.show_text_only("由于缺少阳光照射，全球大量海水结冰，冰川的蔓延速度快得难以想象，海平面下降了100米。")
	await novel_interface.show_text_only("灾难发生后15万年，全球平均气温降至5度，地表大部被冰壳覆盖，超过一半的生物在严寒中灭绝。")
	await novel_interface.show_text_only("银河系中某颗遥远恒星坍缩时的无心之失，让地球上的远古生物群落陷入了无尽的绝望。")
	await novel_interface.show_text_only("——这次意外史称奥陶纪大灭绝。")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("第五学园都市。")
	await novel_interface.show_text_only("随着悠扬的背景音乐，瘫在沙发上的男人渐渐醒了过来……")
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	novel_interface.show_background("res://assets/images/bg/Fabiola/BAR.png")
	await novel_interface.show_text_only("他满脸胡茬，头发凌乱，艰难的撑着沙发靠背坐起身来。")
	await novel_interface.show_text_only("面前的桌上摆着一杯清水，男人顿觉喉咙干渴得好像刚从沙漠走出来，拿起水杯一饮而尽。")
	await novel_interface.show_text_only("接着他感到头痛欲裂，捂着脑袋沉吟了好一阵，之后突然站起身来，似乎在找什么东西。")
	await novel_interface.show_text_only("发现自己的皮包就放在沙发边上，里面的文件也都完好之后，他才稍感安心又坐下来。")
	novel_interface.show_character("shi","normal")
	await novel_interface.show_dialog("这是……\n哪啊……", "施教授")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("施教授观察着周围，这里像是一间高级酒吧，在舒缓的乐声中，窗外的楼宇霓虹闪烁。")
	await novel_interface.show_dialog("你醒了？", "女性的声音")
	await novel_interface.show_text_only("施教授循声望去，一个穿着白大褂的红发女性正拿着杯淡黄色的饮料缓步走来。")
	await novel_interface.show_text_only("她将饮料放在施教授面前，自己坐在了对面的沙发椅中。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("这是电解质水，能缓解头疼。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("shi","normal")
	await novel_interface.show_dialog("你是……", "施教授")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("施教授狐疑的盯着对方的脸，似乎有点印象。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("您应该认识我——", "莉琉")
	await novel_interface.show_dialog("我是莉琉·冯·布劳恩，您去年作为访问学者来新丰洲科学院交流，听过我关于晶体异质物的讲座。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉顿了顿，笑着继续说道。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("另外，我还是SID的主管。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("施教授一惊，本能的想起身逃走，但很快放弃了这个幼稚的念头——")
	await novel_interface.show_text_only("莉琉递过去一个平板电脑，安抚的说道。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("别害怕，这里很安全——", "莉琉")
	await novel_interface.show_dialog("而且要不是我们，你早就没命了。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("施教授狐疑得接过电脑，上面是街道的监控录像。")
	await novel_interface.show_text_only("他忽然想起，自己之前在那栋别墅等了很久都没见到约好的买家，在离开时叫了一辆出租车。")
	await novel_interface.show_text_only("在街边等车的时候，忽然觉得脖子一阵刺痛，然后就眼前一黑……")
	novel_interface.show_character("shi","normal")
	await novel_interface.show_dialog("这是……", "施教授")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("监控录像中，施教授站在路边等车，一个不起眼的中年妇女从他身后经过时忽然掏出了注射器——")
	await novel_interface.show_text_only("那人干脆利落的将针头扎进施教授的脖子，然后迅速从后面搀住了他瘫倒的身体。")
	await novel_interface.show_text_only("大约三秒之后，一辆着侧门的黑色面包车开到路边，车上的两个人将他拖上车。")
	await novel_interface.show_text_only("接着面包车迅速开走，前后不到十秒，他就像人间蒸发般消失了。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("这群人是匿名雇主在网上高价雇用的杀手，还好这辆车在第一个路口就被我们拦下……", "莉琉")
	await novel_interface.show_dialog("当时他们正准备给你注射神经毒剂，如果晚一步你现在就已经是脑死亡状态了。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("施教授不由倒抽了一口凉气，身体僵硬起来。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("所以说……", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("你究竟招惹到什么人了？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("shi","angry")
	await novel_interface.show_dialog("招惹……？\n怎、怎么会！", "施教授")
	await novel_interface.show_dialog("我只是一个学者，能惹到什么人……", "施教授")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("那个别墅作为“地下中介”的信誉一向很好，不管是交易军火、机密文件还是异质物——", "莉琉")
	await novel_interface.show_dialog("在『七诫』组织的担保下，无论买卖双方是什么样的恶徒都不敢越界。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("但这次，你联系的买家却要冒这么大风险对你这种没什么价值的菜鸟下手，为什么？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("施教授防御性的收了收大衣领子，瞄了一眼自己的旧皮包。")
	novel_interface.show_character("shi","normal")
	await novel_interface.show_dialog("你们都看过了吧，这可是第一学园都市的『绝密』级文件，会不会是无形门……", "施教授")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉笑着靠在沙发背上，不屑的说道——")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("你这种人都能带出境，就说明不怎么绝密。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("目前同样的文件市面上已经出现了三份，马萨达的情报部门也拿到手了。", "莉琉")
	await novel_interface.show_dialog("甚至可以推断，华云宫方面是故意放任这份文件流出的——", "莉琉")
	await novel_interface.show_dialog("而且据我所知，其他几个出卖这份情报的卖家都顺利完成了交易。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("你和他们相比，有什么特殊之处，必须要冒险灭口不可呢？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("施教授眼神空洞的愣了好久，一个字也没说出来。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("我猜你和之前联络的买家提出的开价，应该不只是要钱吧……", "莉琉")
	await novel_interface.show_dialog("或许是你索取的东西，差点要了你的命？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉面前的男人长叹一口气，身体松弛下来，向后靠在了沙发背上。")
	novel_interface.show_character("shi","eyeclose")
	await novel_interface.show_dialog("你们这种人……真可怕。", "施教授")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("过奖~", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉的嘴角微微扬起。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("既然你已经明白自己的处境了——", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("那么，来谈谈咱们的交易吧。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("第三学园都市，马萨达港海关。")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadaCustoms.png")
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("这个像纹身一样的东西真能自动降解吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我摸了摸手背上的条形码，据说用的是某种异质物加工的油墨，能在设定的时间点自动消失。")
	await novel_interface.show_text_only("这个条形码是马萨达海关的入境许可，也是外国游人驻留本国期间的唯一合法ID。")
	await novel_interface.show_text_only("在驻留时限到期的那一刻，这种油墨会自动挥发。")
	await novel_interface.show_text_only("如果没这个条形码，马萨达境内任何士兵和临检人员都有权将我立刻逮捕。")
	novel_interface.show_character("ren_medical","uneasy")
	await novel_interface.show_dialog("（嗯……洗澡的时候不会蹭掉吧？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","disgust")
	await novel_interface.show_dialog("好慢啊呜……", "小星尘")
	novel_interface.change_expression("wordless")
	await novel_interface.show_dialog("啊呜啊呜嗷呜~~", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小星尘等得不耐烦，嘴里嘟囔着莫名其妙的音节一扭一扭的跑到走廊窗边，扒着立柱往外看。")
	await novel_interface.show_text_only("我拉她一路跟我从国际医疗援助组织的特殊通道混过来，而安妮要排队走常规游客的安检通道。")
	await novel_interface.show_text_only("马萨达的安防在全世界都是出了名的严格，港口大厅也随处可见荷枪实弹巡逻的士兵。")
	await novel_interface.show_text_only("我走到小星尘身后，从这扇窗向东望去，能看到碧蓝无波的死海和伫立在大运河终点的以利亚大坝。")
	await novel_interface.show_text_only("死海南侧大坝出水口附近的海面混合着不均匀的青色和浅蓝色，越往北海面的颜色越深。")
	await novel_interface.show_text_only("据说《创世纪》中被毁灭的两座罪恶之城——所多玛城和蛾摩拉就沉没于死海南部的水底。")
	await novel_interface.show_text_only("不知那片海中是不是还游荡着对“那位大人”心怀怨愤的冤魂。")
	await novel_interface.show_text_only("此时东北天边的地平线上，由沙尘暴形成的暗红色云雾正蠢蠢欲动。")
	await novel_interface.show_text_only("但最让我感到不可思议的是，沙尘暴的信息居然是这个小家伙告诉我的——")
	novel_interface.show_character("stardust_small","konata_eye")
	await novel_interface.show_dialog("咩？", "小星尘")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("呐~你知道马萨达的历史吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她一副“你说啥呢”的表情眨巴着眼睛，同时头上猫耳一样的耳机则快速闪动了两下。")
	novel_interface.show_character("ren_medical","smile")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","normal1",0.25)
	await novel_interface.show_dialog("马萨达是亚拉姆语中“堡垒”的意思，原是一座建在山丘上的宫殿，也是坚固的防御工事——", "小星尘")
	await novel_interface.show_dialog("公元72年，仅有一千人的马萨达堡在罗马军团围攻下坚守了两年，在城破之际守城将士集体自杀。", "小星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("和刚才在餐厅里的状况一样，她像念书般机械的说出了百科页面上的标准答案。")
	novel_interface.show_character("ren_medical","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("stardust_small","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……那你知道你刚才说的话是什么意思吗？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"konata_eye")
	await novel_interface.show_dialog("不知道呀~！", "小星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她露出一个没心没肺的笑容。")
	await novel_interface.show_text_only("你是智能音箱吗！？")
	await novel_interface.show_text_only("还是特别不智能的那种……")
	await novel_interface.show_text_only("我对历史了解不多，只知道马萨达从几千年前就很惨，七年战争期间连原来的圣城首都被端掉了。")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("唉，这个民族还真是坎坷……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("想到这里，我多少能理解入境大厅横梁上那句“马萨达永不陷落”的标语表达的心境了。")
	novel_interface.show_character("ren_medical","upset")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","happy",0.25)
	await novel_interface.show_dialog("啊！安妮——", "小星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("小星尘指着安检口叫道，安妮正拉着手提箱从那边向我们走来。")
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("播磨脑科学研究中心，实验医疗部。")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Dementium.png")
	await novel_interface.show_text_only("莉琉坐在大脑潜入装置的床上，有些疲惫的揉着太阳穴——")
	await novel_interface.show_text_only("爱衣走进房内，递给她一瓶电解质水。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("怎么样？审讯有收获吗？", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("啊……得到了有趣的情报。", "莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("施教授那边现在状况如何？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("嘛……依然是深度昏迷状态，脑干反射微弱，要靠器械维持生命——", "爱衣")
	await novel_interface.show_dialog("虽然螯合剂清除了他体内大部分神经毒素，但无法确定已经造成了多大损伤，也不知道能不能醒来。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("这套装置是目前从他身上获取信息唯一的办法了~", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉拧开了瓶盖，喝了一大口之后说道。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("那家伙说他窃取文件倒卖，是为了找女儿。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","wink",0.25)
	await novel_interface.show_dialog("啊嘞？我还以为那个老土是光棍呢~", "爱衣")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("他女儿六年前从伯克利的天文系毕业，在联邦政府解体前被召入了NASA的一个保密项目组。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("NASA？真是让人怀念的名字呐……", "爱衣")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("是军方的太空武器项目吗？", "爱衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是个天文观测类项目——", "莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("据说NASA在观测昂宿星团的某个坐标时，偶然收到了特定波段的高频闪烁信号。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("那个信号明显是指向性的，只能在特定轨道位置接收到——", "莉琉")
	await novel_interface.show_dialog("就像在四百光年外对着太阳系发射了一道激光，只有处在那条狭窄的光路中才能观测到。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣的面颊顿时红润起来，兴奋的问道。")
	novel_interface.show_character("liliu_research","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	await novel_interface.show_dialog("就像是……用光纤定向发送讯息？", "爱衣")
	novel_interface.change_2nd_expression("blush_dizzy")
	await novel_interface.show_dialog("难难难难道说——？！", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉微微点了点头。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_CrabNebula.png")
	await novel_interface.show_text_only("1967年，天文学家第一次观测到一组有规律的脉冲信号。")
	await novel_interface.show_text_only("最初他们认为信号来自外星文明生物，并将这个信号命名为“小绿人”。")
	await novel_interface.show_text_only("后来这种信号被确定为脉冲星，并非智慧生命的造物，但人类对系外信号的监听从未停止。")
	await novel_interface.show_text_only("不少天文学家和业余爱好者，终其一生希望接收到来自外层空间的电波。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Dementium.png")
	novel_interface.show_character("liliu_research","angry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ai","blush_dizzy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这个项目从十几年前就开始了，但在黑色圣诞节事件之后，NASA也陷入了瘫痪。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("黑色圣诞节啊……", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("2033年12月24日，一个巨大的球形『黑域』毫无征兆的在纽摩利达斯附近的海面上展开。")
	await novel_interface.show_text_only("黑域瞬间吞噬了联邦政府大部分海面作战力量，为七年战争画上了一个纯黑色的句号。")
	novel_interface.show_character("liliu_research","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ai","normal",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("当时施教授收到了一封他女儿的电邮，内容就是那个项目的香农熵特征值。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("我记得类似于电磁信号的指纹吧？", "爱衣")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("没错，之后他女儿就音讯全无，这些情报也是施教授在这几年里陆续调查到的。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare") 
	await novel_interface.show_dialog("那个大叔比他看起来要靠谱嘛……", "爱衣")
	novel_interface.character_light(0.35,"speak")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("有意思的是，那个黑色石棺状的EX级异质物在被激发时能发出具有同样特征值的电磁波——", "莉琉")
	await novel_interface.show_dialog("只不过强度猛烈得多，最严重的那次激发毁掉了华云宫的一个收容站点。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("他得知这个信息后立刻申请回国，并主动加入了那个石棺的研究团队。", "莉琉")
	await novel_interface.show_dialog("然而，在上次国际和平论坛之后，他们的项目组毫无征兆的被解散了。", "莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("华云宫高层似乎打算将石棺交给教廷永久封存。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think") 
	await novel_interface.show_dialog("那样他女儿的最后线索也会被切断，所以……", "爱衣")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所以他偷出了这份机密文件，想在暗网上找中介进行情报交易。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("啊，他是想要NASA的——？", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉露出一副得到了自己想要玩具般的笑容。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("没错。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("为他招来杀身之祸的，就是他向暗网中介索要NASA『0812项目』的内部资料这件事。", "莉琉")

	print("=== 星尘降临篇第9话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
