# stardustdescends_ep11.gd - 星尘降临篇第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep11_script()

func play_script():
	pass

func stardustdescends_ep11_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadMuseum.png")
	novel_interface.show_character("ren_medical","normal1")
	await novel_interface.show_dialog("马萨达国家博物馆……就是在这儿？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我拿着手机，确认自己已经到达了目标位置。")
	await novel_interface.show_text_only("让我意外的是，这座国家博物馆的大部分展厅都设在半地下的空间内。")
	await novel_interface.show_text_only("正门入口处矗立的黑色石壁，据称内部石材取自旧都圣殿山西侧老城墙的废墟。")
	await novel_interface.show_text_only("石壁外严密包裹的黑色防辐射材料，似乎在默默诉说着那场浩劫带来的创伤和苦难。")
	await novel_interface.show_text_only("整面墙就像一座巨大的墓碑，几位老人正站在墙下低头轻抚墙壁，不知是在悼念还是在祈祷……")
	novel_interface.show_character("ren_medical","uneasy")
	await novel_interface.show_dialog("是在这里登记吧……？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我用胸卡在场馆门口的无人柜台登录并完成了面部生物扫描。")
	await novel_interface.show_text_only("这张胸卡是国际医疗救援组织的加密通证，专为经常出入交战区的医务人员设计。")
	await novel_interface.show_text_only("除了存储个人信息和医疗记录，凭这个通证还能在全球范围内调用组织的通讯设备和救援物资。")
	await novel_interface.show_text_only("甚至还预存了一笔离线电子货币，据说是用于被绑架时支付赎金……")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("（一个实习护士根本用不着这些权限吧！）\n（莉琉真是的……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("总之别让我去执行什么危险的任务就好……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_FirstExhibition.png")
	await novel_interface.show_text_only("我顺着扶梯进入第一展厅，并不宽敞的空间内陈列着很多石刻浮雕。")
	await novel_interface.show_text_only("那些清晰可见的风蚀痕迹，每一道都像是在讲述着遥远而沧桑的历史。")
	await novel_interface.show_text_only("然而我对历史并不感兴趣，只是一边刷手机一边盘算着要如何度过这难熬的三小时。")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("那个是……讲解员！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在AI合成语音设备如此普及的今天，我已经很久没见过真人讲解员了。")
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("（马萨达人口不是很稀缺吗……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那是一位胡子花白的老者，大概六十多岁，头戴黑色小圆帽，西服领口别着工作证。")
	await novel_interface.show_text_only("他耐心的引导大家领取折页传单，同时笑容慈祥的回应着每一个向他询问的人。")
	await novel_interface.show_text_only("我有些好奇的凑了过去，他正在给几位游客介绍博物馆的历史——")
	await novel_interface.show_dialog("虽然很多珍贵的文物，都和原本的国家博物馆一起在战争中损毁了。", "讲解员")
	await novel_interface.show_dialog("但这座新博物馆近些年收藏了很多西亚和非洲的珍贵文物，使它们能够免遭战火的蹂躏……", "讲解员")
	await novel_interface.show_text_only("我看了看宣传页背面印的埃及木乃伊和青铜面具。")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("（就是从人家那儿抢过来的吧！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不过目前世界上大多数珍贵历史文物都由六大学园都市保管，这种事也见怪不怪了。")
	await novel_interface.show_text_only("我注意到他在声情并茂的讲解时，左手一直插在西服口袋里。")
	novel_interface.show_character("ren_medical","bored")
	await novel_interface.show_dialog("（可能是某种特殊的宗教习惯吧……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我环视四周，好在今天不是安息日，参观者并不算多，而且场馆内也没有医疗组织的其他成员。")
	await novel_interface.show_text_only("NGO成员进行“参观学习”的必要流程是首先在历史和文献馆停留三十分钟以上。")
	await novel_interface.show_text_only("我百无聊赖的闲逛，视线不禁被同场参观的几个当地人和十几个小孩吸引住了。")
	await novel_interface.show_text_only("那群人里两个四十多岁的男人最是抢眼——他们都蓄着大胡子，两鬓的头发梳成了奇怪的小辫。")
	await novel_interface.show_text_only("二人统一身穿白衬衫和黑色及膝外套，头上戴着黑色平顶卷檐帽，像是来自某种奇怪的组织。")
	await novel_interface.show_text_only("那十几个小孩跟在男人周围，无论男生女生都穿着同样款式且只有黑白两色布料的衣服。")
	novel_interface.show_character("ren_medical","bored")
	await novel_interface.show_dialog("（是附近学校组织参观吗？）\n（不过这学校的年级跨度有点大啊……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那群小孩从三四岁到十来岁均匀分布，最小的路都走不稳，而年龄稍大的几个孩子则在叫喊打闹。")
	await novel_interface.show_text_only("人群后面，默默的跟着两位身材松垮面容憔悴的中年妇女。")
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("（那两个不会是老师吧……）", "小怜")
	await novel_interface.show_dialog("（怎么其中一个还推着婴儿车？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("真是奇怪的组合……")
	await novel_interface.show_text_only("历史馆的参观很快就结束了，讲解员开始带着大家前往文献馆。")
	await novel_interface.show_text_only("他调整了下夹在衣领上的麦克风，清了清嗓子——")
	await novel_interface.show_dialog("接下来，我将带各位参观本馆最重要的展品。", "讲解员")
	await novel_interface.show_dialog("下一个展厅禁止拍照，请大家收起手机，跟随我进入圣书之龛。", "讲解员")
	await novel_interface.show_text_only("听到这话，那群打闹的小朋友立刻安静了下来，同行的两个黑衣男人也变得表情肃穆。")
	await novel_interface.show_text_only("我收起手机，满心好奇的跟了上去。")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("讲解员扫描掌纹信息后，历史展厅的一扇玄武石大门缓缓打开，露出后面幽长的石质走廊。")
	await novel_interface.show_text_only("我和二十多位参观者鱼贯进入，好像被某种庄重的氛围所感染，所有人小心翼翼一言不发。")
	await novel_interface.show_text_only("……")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_SOTB.png")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("这是……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("走廊末端连接着一个造型奇异的空间。")
	await novel_interface.show_text_only("圣书之龛的展厅呈正圆形，规则等距的环状条纹从墙壁一直蔓延到顶部的天窗。")
	await novel_interface.show_text_only("从天窗射入的光线落在正中的展台上，让这里的环境显得静谧而神圣。")
	await novel_interface.show_text_only("整个空间被设计得像是一个陶罐，周围的墙壁也采用了类似陶土质地的材料。")
	await novel_interface.show_text_only("石阶上经筒样式的圆形展台内，陈列着一卷发黄斑驳的古老羊皮卷。")
	await novel_interface.show_text_only("我拾级而上凑近观察，展台外层的防护玻璃目测至少五厘米厚，经卷上的希伯来字符大多清晰可见。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_DSS.png")
	await novel_interface.show_dialog("难道这就是——", "小怜")
	await novel_interface.show_text_only("就是那部动画里出现过的那个那个……")
	await novel_interface.show_dialog("这是在死海西北侧山洞中发现的古代文献，被称为上个世纪最伟大的考古发现的『死海古卷』。", "讲解员")
	await novel_interface.show_dialog("死海古卷规模非常浩大，包含从12个洞穴中发掘出的五百多份文书——", "讲解员")
	await novel_interface.show_dialog("而现在展柜中的这份，正是死海古卷中『摩西五经\n』《创世纪》的部分稿页。", "讲解员")
	await novel_interface.show_dialog("它记载了神创世的过程以及如何选择马萨达人成为的自己选民，是这个国家最重要的历史文物。", "讲解员")
	await novel_interface.show_text_only("说来，马萨达人好像一直自诩为神的选民吧……")
	await novel_interface.show_text_only("不过我向来对这种宗教故事不感兴趣——")
	await novel_interface.show_text_only("全世界的民族有一个算一个，谁家没几个当神仙的祖先啊……")
	await novel_interface.show_text_only("但几个本地游客显然不这么认为，那两个戴着奇怪帽子的大叔更是立刻面向展柜祷告了起来。")
	await novel_interface.show_text_only("讲解员用他低沉而慈祥声音接着说道。")
	await novel_interface.show_dialog("这段书稿记录了先祖亚伯拉罕、以撒、雅各和他十二个儿子的故事。", "讲解员")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_TheThree.png")
	await novel_interface.show_dialog("亚伯拉罕是诸多宗教的先知，还是希伯来人和和阿拉伯人的共同祖先。", "讲解员")
	await novel_interface.show_dialog("亚伯拉罕是上主从众生中捡选并给予祝福的人。", "讲解员")
	await novel_interface.show_dialog("神曾与亚伯拉罕立约，应许将一片丰沃的土地赐予他的嫡子、嫡孙以及嫡孙所延续的后代。", "讲解员")
	await novel_interface.show_dialog("这片土地从尼罗河延续至幼发拉底河，就是今天我们所说的『应许之地』。", "讲解员")
	await novel_interface.show_dialog("后来亚伯拉罕生嫡子以撒，以撒生嫡子以扫，他的次子叫做雅各……", "讲解员")
	await novel_interface.show_dialog("（等等……雅各？）", "小怜")
	await novel_interface.show_text_only("伊露卡原来那个管理员不就叫这个名字吗！")
	await novel_interface.show_text_only("不过西方人确实喜欢用宗教经典中的角色为自己的子女命名……")
	await novel_interface.show_text_only("讲解员顿了顿，扶起老花镜继续讲解古卷上内容。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MessOfPottage.png")
	await novel_interface.show_dialog("根据经文中的记载，以撒的次子雅各曾用一碗红豆汤买下了哥哥以扫的长子权。", "讲解员")
	await novel_interface.show_dialog("根据亚伯拉罕与神的契约，获得长子权的雅各就拥有了『应许之地』的合法继承权。", "讲解员")
	await novel_interface.show_dialog("雅各后来成为了马萨达的圣祖，他的十二个儿子就是马萨达各支派的十二先祖……", "讲解员")
	await novel_interface.show_text_only("听到这里，我感到脑袋有些发胀。")
	await novel_interface.show_text_only("等一下……红豆汤是什么鬼！？\n古人这么随便的吗？")
	await novel_interface.show_text_only("而且这么说的话，所有马萨达人都是那个雅各的后裔啊……")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_DSS.png")
	await novel_interface.show_text_only("讲解员沿环形的展台向前走了两步，端详着书卷末尾的文字继续说道。")
	await novel_interface.show_dialog("这里是《创世纪》结尾的部分——", "讲解员")
	await novel_interface.show_dialog("圣祖雅各的一生充满传奇，他曾梦见天堂之门，听见神重申对他祖父的誓约。", "讲解员")
	await novel_interface.show_dialog("他曾与神摔跤而病腿，而被赐予了圣名。", "讲解员")
	await novel_interface.show_dialog("雅各晚年住在埃及地十七年，在他死前，找来了自己的儿子约瑟……", "讲解员")
	await novel_interface.show_dialog("雅各要儿子起誓，必要将他带出埃及，葬在迦南地希伯仑的麦比拉洞。", "讲解员")
	await novel_interface.show_dialog("那是当年由亚伯拉罕买下，安葬着雅各的父母和祖父母的家族墓地。", "讲解员")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("文稿就在这里截止。")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_SOTB.png")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("（麦比拉洞……这个名字怎么有点熟悉）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("昨晚爱衣的简报里好像有提到过……是不是前两天发生过什么爆炸？")
	await novel_interface.show_text_only("哎呀记不清了，反正这些外国的人名地名听起来都差不多……")
	await novel_interface.show_text_only("讲解员轻抚着展柜的玻璃，低声感叹。")
	await novel_interface.show_dialog("马萨达是个历史悠久的民族，也很重视考古发掘。", "讲解员")
	await novel_interface.show_dialog("从第一份古卷被发现的那天，『死海古卷』的发掘和复原工作已经持续了八十多年。", "讲解员")
	await novel_interface.show_dialog("那是我们祖先宝贵的遗产，也是我们的根源。", "讲解员")
	await novel_interface.show_dialog("然而……", "讲解员")
	await novel_interface.show_text_only("讲解员走下楼梯，来到展厅一侧的巨幅油画处。")
	novel_interface.change_music("res://assets/audio/music/Hero.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_TheJewishWar.png")
	await novel_interface.show_text_only("他在油画前意味深长的驻足凝望了许久。")
	await novel_interface.show_text_only("这幅油画篇幅宏大，几乎占据了一整面墙。")
	await novel_interface.show_dialog("然而我们的历史，也充满了苦难。", "讲解员")
	await novel_interface.show_text_only("他转过身来，嘴角微微抽动了一下，好像在极力压抑着某些痛苦的回忆。")
	await novel_interface.show_dialog("这幅画是根据公元一世纪的历史学家弗拉维奥·约瑟夫斯的著作创作而成。", "讲解员")
	await novel_interface.show_dialog("当时强大的罗马帝国征服了圣城，一百多万马萨达先民被军团士兵屠戮。", "讲解员")
	await novel_interface.show_dialog("而这幅画，讲述的就是第二圣殿被点燃的那一天。", "讲解员")
	await novel_interface.show_dialog("那是马萨达历史上最悲伤的日子……然而这只是上千年苦难的开端。", "讲解员")
	await novel_interface.show_dialog("公元七十年，我们的先祖被罗马人大批的从犹地亚流放出去。", "讲解员")
	await novel_interface.show_dialog("不甘心被逐出故土的人打算奋起反抗，其中一千多名起义军，将当年的马萨达作为了最后的堡垒。", "讲解员")
	await novel_interface.show_dialog("他们坚守在这座城池，在罗马人的围困下固守了足足两年，直到水源被断再无余力。", "讲解员")
	await novel_interface.show_dialog("当第十军团终于破城而入时，他们的总督看到的仅仅是九百多具尸体和被烧毁的建筑——", "讲解员")
	await novel_interface.show_dialog("守城将士因不想屈从成为罗马的奴隶而全部选择自杀，最后仅有两个大人和五个小孩活了下来……", "讲解员")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我想象着当时的画面，感到有些揪心。")
	await novel_interface.show_text_only("讲解员沉默许久，转过身来面对我们继续说道。")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_SOTB.png")
	await novel_interface.show_dialog("我们曾一次又一次的被逐出故土，被赶出自己的家园。", "讲解员")
	await novel_interface.show_dialog("我们不断的被征服、被统治、被排挤、被屠杀，被作为奴隶、囚徒、甚至牲畜对待……", "讲解员")
	await novel_interface.show_dialog("一个世纪前，在那场人类史上罕见的惨绝人寰的种族清洗中，我们六百万同胞惨遭屠戮。", "讲解员")
	await novel_interface.show_dialog("而在十年前，我们的首都再次化为焦土，圣殿山被紫色的烈焰焚烧了七天七夜……", "讲解员")
	await novel_interface.show_dialog("很多人——我的家人和朋友，都在那场浩劫中失去了生命。", "讲解员")
	await novel_interface.show_dialog("而侥幸活下来的人，可能失去的更多……", "讲解员")
	await novel_interface.show_text_only("他声音有些颤抖，将插在口袋中的左手举了起来。")
	await novel_interface.show_text_only("我们这才看见，那只手已被金属义肢代替，从袖口露出的手腕和小臂上遍布着烧伤的瘢痕……")
	await novel_interface.show_text_only("全场都陷入了沉默，我也不由屏住呼吸。")
	await novel_interface.show_text_only("人群中一位来旅游的小女生双手捂着嘴，泪水在她的眼眶中打转。")
	await novel_interface.show_text_only("讲解员却将那只手攥成拳头高高举起，注视着我们用坚定的声音说道——")
	await novel_interface.show_dialog("然而就像那一千名死守城池的战士一样，苦难从来不会让我们屈服——", "讲解员")
	await novel_interface.show_text_only("他的声音并不洪亮，却满怀豪情气魄，让人感到心中充满了力量。")
	await novel_interface.show_text_only("他眼神发着光，就像看到了神灵在指引着方向。")
	await novel_interface.show_dialog("我们曾经历过两次大流散，但最终，我们都会再回到这片土地，因为苦难绝不会让我们屈服。", "讲解员")
	await novel_interface.show_dialog("九十年前，我们的先辈便冒着枪林弹雨，只为再次回到这里，建立属于我们自己的国家。", "讲解员")
	await novel_interface.show_dialog("尽管这只是一片贫瘠的沙漠，尽管当时连淡水都难以供应，但这里是我们的家！", "讲解员")
	await novel_interface.show_dialog("这片土地上流淌的不是奶与蜜，而是我们的鲜血、眼泪和汗水。", "讲解员")
	await novel_interface.show_dialog("这是我们在这个世界上唯一的故乡，更是马萨达人几千年来的心灵家园。", "讲解员")
	await novel_interface.show_dialog("『应许之地』是我们先祖和神明的契约，也是我们对后世子孙的承诺——", "讲解员")
	await novel_interface.show_dialog("圣殿可以被烧毁，但精神的堡垒永远不会陷落！", "讲解员")
	await novel_interface.show_dialog("最后，再次感谢大家来到马萨达国家博物馆，谢谢大家！", "讲解员")
	await novel_interface.show_text_only("说罢，讲解员向大家鞠躬致意。")
	await novel_interface.show_text_only("周围响起了经久不息的掌声，我也不禁对这个坚忍的民族感到敬佩，自发的鼓起掌来。")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_IndiaEH.png")
	await novel_interface.show_text_only("离开文献展区，我开始在馆内漫无目的闲逛。")
	await novel_interface.show_text_only("尽管刚刚很充实，但最低时间限制让我不得不在这里继续逗留两个半小时。")
	await novel_interface.show_text_only("方才讲解员的那段演说像海底翻涌的暗流，一直萦绕在我脑中。")
	await novel_interface.show_text_only("直到我走进一间光线明亮的半地下展厅时，才渐渐平复下来。")
	novel_interface.show_character("ren_medical","normal2")
	await novel_interface.show_dialog("（那个讲解员好像去迎接下一批游客了……）", "小怜")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("（这么说来……他每天都要讲很多场？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("忽然一个念头闪过我的脑海——")
	await novel_interface.show_text_only("是啊，那位老人家的工作，就是每天不厌其烦的向一批批参观者重复同一套说辞吧……")
	await novel_interface.show_text_only("那么他的每次停顿、每个重音，他在展台间移动的路线，应该都经过了成百上千次的排练……")
	await novel_interface.show_text_only("甚至他插在口袋里的那只手——")
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("……是一开始就设计好的吗！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我不禁感到头皮发麻，似乎有些明白昨晚莉琉连线时说的那些话了……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Masadhotel.png")
	await novel_interface.show_dialog("想要维系全民兵役制，就必须把思想宣教渗透进社会的每个毛孔。", "莉琉")
	await novel_interface.show_dialog("而最有效的洗脑手段，就是让人们为自己民族的历史感到屈辱和委屈——", "莉琉")
	await novel_interface.show_dialog("受伤的动物会自发的聚在一起，感到委屈的人会本能的想要报复……", "莉琉")
	await novel_interface.show_dialog("你到时候自己感受一下就明白了~", "莉琉")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_IndiaEH.png")
	await novel_interface.show_text_only("我双手捂住太阳穴使劲摇了摇头，像个试图把脑子里的水倒出来的笨蛋。")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("（还好我机灵，不然就被洗脑了~）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("要不是经常被莉琉敲打，早就被洗脑了。")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("（好像……还是被小洗了一下……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("就当没事发生，快给我忘掉啊！")
	await novel_interface.show_text_only("其实仔细想想，“这块地是创世神划给我们家的”这种话怎么想都不太靠谱……")
	await novel_interface.show_text_only("上位者离开自己统治的土地前，在地图上胡乱划上几条分界线，然后拂袖而去——")
	await novel_interface.show_text_only("留下当地的民众，陷入无尽的纷争与苦难之中。")
	await novel_interface.show_text_only("我看了看展厅角落陈列的那尊印度佛像——")
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("（这种事，人类才更擅长吧……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我在博物馆里继续溜达，走进了一间昏暗的展厅。")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_TechnologyEH.png")
	await novel_interface.show_text_only("这里似乎是个工程类展区，墙上的投影讲解着红海死海大运河各节点的技术细节。")
	await novel_interface.show_text_only("几个视频都是讲述果敢智慧的马萨达人如何克服重重困难，终于完成了这样的超级工程。")
	await novel_interface.show_text_only("或许因为才刚清空大脑，这种歌功颂德的宣教口吻让我有些排斥。")
	await novel_interface.show_text_only("我想起昨天早上在赌船餐厅，安妮给我分享的大运河纪录片链接，页面底部有一个关联视频——")
	await novel_interface.show_text_only("内容是本古里安大学的一位微生物学教授对大运河工程发表的反对意见。")
	novel_interface.show_character("ren_medical","normal2")
	await novel_interface.show_dialog("（某种意义上，那位教授还是网络名人呢……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Itsuki.png")
	await novel_interface.show_text_only("这位教授出名，是因为不久前他在课堂上当着学生们吃某种爱斯基摩人传统食物的视频。")
	await novel_interface.show_text_only("从死海豹身体中掏出发酵完成的侏儒海燕，然后用嘴对着海燕的……………………")
	await novel_interface.show_text_only("总之，那魔幻的画面和炸裂的音效，迅速在社交网络上疯传，还成为了各种鬼畜视频的常客。")
	await novel_interface.show_text_only("我点开的视频应该是这位硬核教授在十多年前发表的，内容意外的严肃。")
	await novel_interface.show_text_only("马萨达官方称在大运河建成前的几十年里，死海一直以每年水位下降1.2米的速度迅速枯竭。")
	await novel_interface.show_text_only("如果不修运河，死海会在2050年之前完全见底。")
	await novel_interface.show_text_only("但教授表示，这件事的根本原因是从上世纪六十年代开始，马萨达一直对本应汇入死海的河道截流。")
	await novel_interface.show_text_only("人们都觉得西亚沙漠地下埋藏的石油是上天赐予的宝藏——")
	await novel_interface.show_text_only("但其实在这片土地上，最宝贵的资源是水。")
	await novel_interface.show_text_only("他说如果将红海海水灌入死海，死海盐度会被大幅稀释，可能严重破坏原有菌群的生态平衡。")
	await novel_interface.show_text_only("但显然没人会去关心什么细菌，大运河作为国家重点工程，当年随着新都选址的确定火速上马。")
	await novel_interface.show_text_only("那段视频让我印象最深刻的是，那种鱼虾都无法存活的超高盐度水域，居然成了嗜盐细菌的天堂。")
	await novel_interface.show_text_only("生态系统真是神奇……")
	await novel_interface.hide_background()
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("（但那个视频居然讲了38分钟，难怪没人看…\n…）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不知道现在15秒的视频是大多数人的脑力极限吗~")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_AncientHumanEH.png")
	await novel_interface.show_text_only("我继续在巨大的博物馆里游荡了好久，鬼使神差下走进一个冷清的展厅。")
	await novel_interface.show_text_only("这里只有我一个人，大厅中央的展柜里陈列着两幅类似人形生物的骨骼标本。")
	await novel_interface.show_text_only("每套骨骼缺失的部分都很多，一半以上的骨架要靠石膏补足才得以还原成大概的形态。")
	await novel_interface.show_text_only("展柜上镶嵌的金属铭牌上写着『Lucy&Ardi』。")
	await novel_interface.show_text_only("走了半天我感到有些疲累，坐到一张长凳上。")
	novel_interface.show_character("ren_medical","normal2")
	await novel_interface.show_dialog("不知道那个不让人省心的小家伙现在在干嘛……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一会参观结束后，我还要带小星尘去入境处补办手续。")
	await novel_interface.show_text_only("昨晚在酒店，她把房间搞得一塌糊涂，还打翻了艾米莉欧送的石榴汁。")
	await novel_interface.show_text_only("之后她居然还赖着让我帮她洗澡！")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("（还好有安妮帮我解围……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不、不然……")
	await novel_interface.show_text_only("啊啊啊啊不想了不想了！！")
	await novel_interface.show_text_only("我抬头看着展柜旁的年代还原示意图，画中描绘的似乎是个原始人群落。")
	await novel_interface.show_text_only("构图与一部经典老科幻电影的开头有几分相似——")
	await novel_interface.show_text_only("那部电影中，地球上居住的古猿受某个巨大的黑色立方体影响而产生进化，终于懂得了使用工具。")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("我已经忘记自己是什么时候看过的那部电影，甚至有些恍惚是不是真的存在那么一部电影了。")
	await novel_interface.show_text_only("黑色的立方体……")
	novel_interface.change_music("res://assets/audio/music/unkown/UI_Draw.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_AncientHumanEH.png")
	await novel_interface.show_text_only("忽然，我听到一个清丽的女声。")
	await novel_interface.show_dialog("很神奇吧——", "少女的声音")
	await novel_interface.show_text_only("我吓得猛转过头，看见一位少女正站在我身后。")
	await novel_interface.show_text_only("她理了理仿佛丝锦般柔软的头发，对我露出一个温柔的微笑。")
	novel_interface.show_character("stardust_big","normal")
	await novel_interface.show_dialog("你好呀。", "少女")

	print("=== 星尘降临篇第11话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
