# stardustdescends_ep17.gd - 星尘降临篇第17话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep17_script()

func play_script():
	pass

func stardustdescends_ep17_script():
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SlumArea.png")
	await novel_interface.show_text_only("我顺着昏暗的楼梯，一路摸黑走出了楼门。")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("（好暗啊……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("刚才和艾米莉欧的通讯忽然中断，无论怎么呼叫都没有回应。")
	await novel_interface.show_text_only("我暗暗感到有些不妙——这片贫民区夜间犯罪率本来就爆表，据说时不时还有极端分子出没……")
	await novel_interface.show_text_only("海法阿姨迅速关掉了走廊和各个房间的灯，好在孩子们此时都已经睡着了。")
	await novel_interface.show_text_only("在她缓缓合上孤儿院厚重的金属大门时，一股不祥的预感忽然涌上我的心头——")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("如果留在这里的话，或许就再也见不到艾米她们了\n……")
	await novel_interface.show_text_only("不知哪来的动力，我在大门关闭前冲了出去，留下句“我出去看看”，就一溜烟的跑下楼。")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_SlumArea.png")
	await novel_interface.show_text_only("……")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("（我怎么这么冒失的跑出来了……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("马萨达虽然是温和的地中海气候，但夜风吹在我还没干透的头发上也会有些凉意。")
	await novel_interface.show_text_only("停在院里的装甲车内外照明都已熄灭，但我发现车子的后仓门只是虚掩着。")
	await novel_interface.show_text_only("我屏住呼吸，蹑手蹑脚的潜到车尾，轻轻将后仓门拉开到自己刚好能探进头去的程度。")
	await novel_interface.show_text_only("望着漆黑一片的车舱，打开了手机的闪光灯——")
	await novel_interface.show_text_only("一张翻转过来的男人的脸猛然呈现在面前！那人嘴角泛着泡沫，正用无神的瞳孔凝视着我！")
	await novel_interface.show_text_only("我像只受惊的小鹿般条件反射的后跳，手机也从手里飞了出去。")
	await novel_interface.show_text_only("脚还没落地，我的身体就被一只手从身后搂起，同时嘴巴被另一只手紧紧的按住。")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("（嗷呜呜——！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我眼看着手机在空中划出一道弧线，在落地前被艾米莉欧单手接住并一气呵成的关掉了闪光灯。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("（小声）嘘！是我们。", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她无奈的拍了拍我惊魂未定的脸，顺手拭去了我眼角刚冒出来的泪花。")
	novel_interface.show_character("valkyrja","happy")
	await novel_interface.show_dialog("你刚洗完澡？\n（嗅嗅）还挺好闻的~", "薇拉")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("别出声，明白吗？", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("身后传来薇拉戏谑的声音，看到我乖巧的微微点头她才把手松开。")
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("（小声）你看外面。", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我顺着她指的方向，从院子铁门的缝隙向外面的街道看去——")
	await novel_interface.show_text_only("瞳孔逐渐适应了黑暗之后，我很快发现街上有一些窸窸窣窣的人影在攒动。")
	novel_interface.show_character("emilio","stare")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_medical","stare",0.25)
	await novel_interface.show_dialog("（是小偷吗……不对，人也太多了。）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("单在我视野中的人就有四五个黑衣人，围绕着两辆行驶异常缓慢的老式厢型车。")
	await novel_interface.show_text_only("那两辆车没开大灯，车尾的刹车灯也被卸掉了，司机将引擎声音压到了最低。")
	await novel_interface.show_text_only("那只可疑的车队刚开过去没多久，又有一只相同配置的小队从后面开了过来。")
	await novel_interface.show_text_only("远处一个流浪汉拎着酒瓶从街角的窝棚里晃晃悠悠的走了出来，茫然的盯着漆黑的街道打了个嗝。")
	await novel_interface.show_text_only("小队中的一个黑衣人向醉汉走去，不由分说的扭断了他的脖子，并迅速将尸体拖到路边阴影处。")
	novel_interface.show_character("emilio","stare")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_medical","panic",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("——？！！", "小怜")
	await novel_interface.show_dialog("那些是什么人……", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这已经是我们看到的第六只小队了，刚才我偷偷抓到一个，没来得及审问那人就服毒自杀了。", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("艾米莉欧指了指装甲车，大概就是我刚才看到的那个口吐白沫的家伙。")
	novel_interface.show_character("emilio","stare")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_medical","panic",0.25)
	await novel_interface.show_dialog("那人怀里揣着一面印有宗教标语的黑旗，通常只有发动自杀式袭击的极端分子才会这么做……", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("艾米莉欧眉头紧锁，显然事态的发展已经超乎了她的预期。")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("自……自杀式袭击？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这个词我只在电影和海外新闻上见过，但从没听说这么多人一起来的啊！")
	novel_interface.show_character("ren_medical","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("emilio","stare",0.25)
	await novel_interface.show_dialog("那些车没有车牌和刹车灯，只能在属于监控盲区的贫民区活动，否则很快就会被无人机拦截。", "艾米莉欧")
	await novel_interface.show_dialog("白天这一带也有国防军的随机巡逻，所以我猜那些车并没有全身而退的打算……", "艾米莉欧")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("你、你是说——", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","angry")
	await novel_interface.show_dialog("一次规模史无前例的自杀性袭击，并且很大可能在几小时内就会发生。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","speak")
	await novel_interface.show_dialog("能开到这么靠近内城区的地方，说明那些车上没有放射性物质……", "薇拉")
	await novel_interface.show_dialog("马萨达周围几公里的路面下面都埋设了放射性物质探测器。", "薇拉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("可如果只是汽车炸弹袭击的话，需要这么多人吗？", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("咱、咱们要不要先把情况汇报上去？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("现在附近的电磁信号都被干扰了，我刚才用公共电话亭发送了紧急代码。", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这附近还有那么古老的东西吗？")
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("抵抗军在正面战场上都很少用到干扰设备，实在不知道这帮人是什么来路……", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","angry")
	await novel_interface.show_dialog("等军队和摩诺拉的人赶到最快也得十几分钟，到时这些人早就没影了。", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("那咱们悄悄跟着他们？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","speechless")
	await novel_interface.show_dialog("跟上去也没用，既然他们是分组行动，肯定该会分头隐匿。", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("是啊，这片贫民区本就是少数民族聚居区，说着不同语言的地头帮派更是鱼龙混杂。")
	await novel_interface.show_text_only("不仅大量基础设施年久失修，还有很多由违章建筑围出来的完全不在规划图上的暗区。")
	await novel_interface.show_text_only("马萨达官方对这种局面一直态度暖昧，反正这几年国家财政处处吃紧，也无力清剿这种垃圾场。")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("会不会和明天的停火协议有关？", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("莉……我的上级之前说过明天有个什么签约仪式。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","shout")
	await novel_interface.show_dialog("啊！明天的签约仪式是几点？", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","panic")
	await novel_interface.show_dialog("我记得内部通报上说提前到清晨六点了，因为到场媒体很多，为了画面效果希望尽可能避开沙尘暴。", "薇拉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("咱们的签约代表是陆军少将哈蒙，他在接受采访时还说自己签约时会穿着西服而不是军装。", "薇拉")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("那个大蛤蟆还不如直接宣布自己打算参加明年的竞选呢，这姿态真是昭然若揭……", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("（……蛤、蛤蟆？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("等等，如果是哈蒙的话……", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧似乎很熟悉那位陆军少将，眉头紧锁着思考着什么。")
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("如果说哈蒙真打算参选总理，以他那性格，多半会觉得单纯的签字握手力度过小了。", "艾米莉欧")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("要让媒体更直观的看到停火协议带来的转变，我猜他会同时更新AI防卫武器的电子协议。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","bored")
	await novel_interface.show_dialog("什么意思……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","shout")
	await novel_interface.show_dialog("如果看到常年盘旋在马萨达上空的无人机群刀枪入库的场面，到场的左派媒体估计会当场泪崩吧。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","wink")
	await novel_interface.show_dialog("噗——\n好像是。", "薇拉")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("等一下……你是说那些人打算马萨达的城防系统\n统一更新协议的时候发起攻击！？", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("马萨达的防御力量80%靠AI防卫武器，系统不会那么愚蠢的让所有设备一起停机的。", "艾米莉欧")
	await novel_interface.show_dialog("这种重大协议更新，会按照不同防区分批进行……", "艾米莉欧")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("对了，明天签约仪式的地址在哪？", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("啊，似乎是在死海边上的一个什么会展中心。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我记得刚才莉琉在电话里提到过——")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_ShelterOffice.png")
	await novel_interface.show_dialog("明天代表马萨达签署停火协议的人定下来了，是国防军北方司令部的陆军少将哈蒙。", "莉琉")
	await novel_interface.show_dialog("而且出于政治目的考虑，协议签署地选在死海边的马萨达国际会展中心。", "莉琉")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SlumArea.png")
	novel_interface.show_character("valkyrja","speak")
	await novel_interface.show_dialog("马萨达国际会展中心？\n离这倒是不远……", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","solemn")
	await novel_interface.show_dialog("他们是想直接袭击会场？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","speechless")
	await novel_interface.show_dialog("别逗了，会场附近肯定会被摩诺拉严密监控，国防军也安排了大量重武器。", "薇拉")
	await novel_interface.show_dialog("那些家伙要是敢去会展中心，在五公里外就会被发现然后迅速歼灭。", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("我记得地图上会展中心的位置，如果我站在那个大厅的话……", "艾米莉欧")
	await novel_interface.show_dialog("能看到最近的隔离墙，就是咱们前面那段吧？", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我顺着艾米莉欧所指的方向望去，远处延伸的街道仿佛被那面高大的隔离墙直接截断一般——")
	await novel_interface.show_text_only("墙后隐隐泄出繁华内城区闪烁的微光……")
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("那是内城区东北侧的隔离墙，如果他们的目标不是签约会场的话……", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧和薇拉同时陷入了沉默，我从她们的表情大概猜到了那是多么糟糕的情况。")
	await novel_interface.show_text_only("我仰望着暗沉的天空，没有一丁点星光。")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("（天上……本来就这么暗吗？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("当时，我心中涌出一股不可言喻诡异且不祥的预\n感。")
	await novel_interface.show_text_only("但我当时无论如何也想不到，事情会发展成那个样子……")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("与此同时，第五学园都市。")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_bar.png")
	await novel_interface.show_text_only("依然是悠扬的背景音乐，施教授坐在沙发上神情痛苦的捂着脑袋。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("你醒了？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉将一杯饮料放在施教授面前，缓缓得坐在他对面的沙发椅中。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("这是电解质水，能缓解头疼。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("shi","eyeclose",0.25)
	await novel_interface.show_dialog("我……", "施教授")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("我好像……认识你？", "施教授")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉心里一惊，但表情没有表现出任何波动。")
	await novel_interface.show_text_only("她本想用刚刚获得的关于NASA机密项目的信息和施教授做一下交叉验证，却得到了意外的反馈。")
	novel_interface.show_character("liliu_uniform1","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("shi","normal",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（之前的几次审讯都没有留下记忆，难道上次的记忆清除不完整？）", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("你……还记得什么？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"eyeclose")
	await novel_interface.show_dialog("不、好像是梦里见到的……我、我也记不清了。", "施教授")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这是电解质水，能缓解头疼。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉将那杯淡黄色的饮料推向施教授，这是爱衣设计的“保险措施”。")
	await novel_interface.show_text_only("只要杯中的液体被消耗，审问者和对象的链接就会自动断开。")
	await novel_interface.show_text_only("在正常情况下，当对象看到这杯电解质水时会本能的感到抗拒，认为喝它就是在承认自己有问题。")
	await novel_interface.show_text_only("但当对象的精神状态变得不稳定，就会倾向于喝掉这杯水来平复自己的情绪。")
	await novel_interface.show_text_only("施教授盯着杯子思量了很久，终于开口说话——")
	novel_interface.stop_music()
	novel_interface.show_character("shi","eyeclose")
	await novel_interface.show_dialog("我女儿曾有段时间反复失眠，她在电话里给我讲了一个思想实验……", "施教授")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("她的问题是：为什么世界末日还没降临？", "施教授")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("哦？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("shi","normal")
	await novel_interface.show_dialog("地球之前的五次物种大灭绝分别在4.4亿年、3.65亿年、2.5亿年、2亿年和6500万年前。", "施教授")
	await novel_interface.show_dialog("按照这个频率，自然环境中大约每一亿年就会发生一次末日级事件。", "施教授")
	await novel_interface.show_dialog("但自从人类发明了核武器，末日降临的概率就被大幅缩短了。", "施教授")
	await novel_interface.show_dialog("古巴导弹危机，人类文明曾命悬一线，但终究还是熬过了冷战……", "施教授")
	await novel_interface.show_dialog("然而异质物武器出现了，它不仅能屠戮生命、摧毁家园，还能扭曲观念和信仰。", "施教授")
	novel_interface.change_expression("eyeclose")
	await novel_interface.show_dialog("其实我们都知道，能制造末日级事件的异质物远不止联合议会公开的那六个……", "施教授")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("施教授盯着杯中不断上浮的气泡，幽幽的说道。")
	novel_interface.show_character("shi","eyeclose")
	await novel_interface.show_dialog("那些只是一定程度上可控制的异质物而已。", "施教授")
	await novel_interface.show_dialog("而那些强大到无法控制的东西，人们只能竭尽全力将它掩埋。", "施教授")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("但问题是，无论怎么计算，都至少应该有一种能造成末日级事件的异质物被触发了才对。", "施教授")
	await novel_interface.show_dialog("就像100个人同时掷硬币，只要一个人掷出一次反面，所有人就会同时死亡。", "施教授")
	await novel_interface.show_dialog("在所有人掷了几轮以后，最值得思考问题就是——", "施教授")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("为什么我们现在还活着？", "施教授")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉身体紧贴在靠背上深吸了一口气，她何尝没问过自己这样的问题呢。")
	await novel_interface.show_text_only("这几年她作为SID主管，处理过数次非常严重的危机，常常自己都会觉得不可思议。")
	await novel_interface.show_text_only("在处理那些事件时，只要一步行差踏错，甚至仅仅错过关键时机，都会造成不堪设想的后果。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("这个问题……您女儿是如何作答的？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("shi","normal")
	await novel_interface.show_dialog("她觉得……或许存在一种类似游戏中“存档”功能的异质物。", "施教授")
	await novel_interface.show_dialog("如果末日降临，相当于游戏失败，就自动退回到关键的存档点重来。", "施教授")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("丢出反面就重来一次吗……\n这答案倒确实符合复杂问题求最简单解的原则。", "莉琉")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("可如果一切都退回到当初的状态，有什么理由重来一次就能得出不同的结果呢？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("shi","eyeclose")
	await novel_interface.show_dialog("这就是困扰她的问题：要想维持这个世界，总要有人作为游戏的玩家，去做出不同的尝试。", "施教授")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("每次重来，那人都应该保留着某些上一轮的记忆或信息。", "施教授")
	await novel_interface.show_dialog("而每次末日危机，或许需要不同的人去破解。", "施教授")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("……被选中的那个人是救世主？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("shi","eyeclose")
	await novel_interface.show_dialog("不。", "施教授")
	await novel_interface.show_dialog("无论选择哪个存档点，都意味着那个时间之前的所有的苦难与牺牲都是与“拯救世界”无关的。", "施教授")
	await novel_interface.show_dialog("每一次侥幸通关后的存档，都意味着此前一批新的牺牲者被永远确认了下来。", "施教授")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("7年战争，30亿生灵涂炭……\n他们再也没有重来的机会了。", "施教授")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("背负着这些的人，怎么能被称作救世主？", "施教授")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("施教授可能是想起了逝去的亲人，情绪有些激动。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("不过这到底只是个假说，平行宇宙理论也可以解释得通……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没等莉琉说完，施教授就拿起那杯电解质水一饮而尽。")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("六小时后，马萨达国际会展中心，停车场。")
	await novel_interface.show_text_only("装甲运兵车内。")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_MasadAPCO2.png")
	await novel_interface.show_text_only("我和薇拉气喘吁吁的靠在扶手上，感觉心脏快要跳出来了。")
	novel_interface.show_character("valkyrja","angry")
	await novel_interface.show_dialog("他们应该已经验出你的指纹了……\n你入关时登记过的。", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("薇拉用车上的急救包处理着自己胳膊上的伤口。")
	novel_interface.show_character("valkyrja","angry")
	await novel_interface.show_dialog("如果有可靠的加密通信频道，就快点通知你的同伴让她们千万别被抓到。", "薇拉")
	await novel_interface.show_dialog("摩诺拉很快就会推测出你是SID的人。", "薇拉")
	await novel_interface.show_dialog("你待在车里别出来，停车场上有好几辆这种军用装甲车，半小时内大概都不会穿帮。", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("艾米莉欧呢？？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","angry")
	await novel_interface.show_dialog("她刚被国防军押走了……应该暂时关在会展中心的某间临时安全屋。", "薇拉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("我得去把她救出来！", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("薇拉把几枚手雷和闪光弹跨在腰带上，不由分说的跳出了车舱。")
	await novel_interface.show_text_only("我无力的瘫在座椅上，自己的身份暴露、艾米莉欧被抓……")
	await novel_interface.show_text_only("——这简直，是最糟的状况了啊啊啊！！！")

	print("=== 星尘降临篇第17话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
