# stardustdescends_ep18.gd - 星尘降临篇第18话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep18_script()

func play_script():
	pass

func stardustdescends_ep18_script():
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Psychology.png")
	await novel_interface.show_text_only("每个人都体验过内心的痛苦——那感觉是如此的真切、沉重、让人心焦、难以承受。")
	await novel_interface.show_text_only("然而很少有人知道，人类心理上的痛苦大多是后天习得的。")
	await novel_interface.show_text_only("吃个鸡腿就能幸福一整天的小孩，无法理解在社交网络上被同学排斥和孤立的痛苦。")
	await novel_interface.show_text_only("无论你苦于无法融入团体、苦于不被周遭认同、还是苦于不能成为想象中的角色……")
	await novel_interface.show_text_only("这些痛苦全都构建在复杂的概念之上，是大量后天所习得的意义堆砌而出的副产品。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Camus.png")
	await novel_interface.show_text_only("加缪说，人类的荒诞之处在于，永远要在无意义的宇宙中不停寻找意义。")
	await novel_interface.show_text_only("在意义的枷锁中，没人能够获得真正的自由。")
	await novel_interface.show_text_only("人类文明无法脱离意义，它是各个时代社会体系的基石。")
	await novel_interface.show_text_only("宗族的意义、国家的意义、主君的意义、宗教的意义、乃至民族认同、意识形态和流行文化……")
	await novel_interface.show_text_only("当你被灌输了一套意义系统，就会自然而然的形成各种观念，在脑内构造出价值阶梯——")
	await novel_interface.show_text_only("什么值得嘉奖和晋升，什么需要唾弃和贬斥，怎样是幸福和光荣，怎样该痛苦和羞愧……")
	await novel_interface.show_text_only("改朝换代时有人痛苦到自杀，偶像结婚时也有人痛苦到自杀，二者的痛苦并无真伪之分。")
	await novel_interface.show_text_only("但如果你头脑够灵光，或许能偶尔的挣脱枷锁，独自出去放放风。")
	await novel_interface.show_text_only("然后再次回到群体中，继续假装挂上镣铐，歌颂大家共同歌颂的，鄙视大家共同鄙视的。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Prisoner.png")
	await novel_interface.show_text_only("因为聪明的你一定已经意识到：人类不仅是意义的囚徒，还会自愿成为它的狱卒。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_ConventionCentre.png")
	await novel_interface.show_text_only("马萨达国际会展中心，签字仪式开场前。")
	await novel_interface.show_text_only("大厅中，上百家媒体的记者已经就位，各种闪光灯和摄影摄像器材随时准备记录这历史性的一刻。")
	await novel_interface.show_text_only("而主席台背面，厚重的蓝色幕布将外面人声鼎沸的大厅和后台全隔绝开来。")
	await novel_interface.show_text_only("顶棚桁架上一排排崭新的专业照明设备，此时全都处于低亮度待机模式。")
	await novel_interface.show_text_only("墙壁包裹的隔音板和幕布上的隔音涂层，让这里安静得有些诡异。")
	await novel_interface.show_text_only("身着沙漠迷彩作训服的军官看到穿着灰色西服的男人从幕帘后的通道走来，立刻挺直腰板敬礼。")
	await novel_interface.show_text_only("军官迷彩服领章上的军衔和金色六芒星标志着这是一位国防军少校。")
	await novel_interface.show_text_only("而他将要汇报的对象，正是今天马萨达方面的签约代表——国防军北方司令部陆军少将哈蒙。")
	await novel_interface.show_dialog("报告少将，我来做关于刚才袭击的简报。", "少校")
	await novel_interface.show_text_only("少将的身材有些发福，但头发梳得一丝不苟，目光依然保持着军人特有的犀利。")
	await novel_interface.show_text_only("他边走边不耐烦的解下领带，和手中黑色皮革底面的平板电脑夹在一起。")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("这东西真戴不惯……", "哈蒙")
	await novel_interface.show_dialog("你说吧。", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是关于30分钟前，会展中心西南方爆炸事件的调查报告。", "少校")
	await novel_interface.show_dialog("爆炸物处理小队根据现场痕迹判断，那是以砂糖为主要原料的IED（简易爆炸装置）。", "少校")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("……砂糖做的土制炸弹？", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("对，但爆炸烈度不大，没有造成人员伤亡，炸药似乎加入了能强化烟雾的添加物。", "少校")
	await novel_interface.show_dialog("烟雾在第一时间被我们扑灭了，警卫团现已将周围区域戒严，目前没有媒体报导此事。", "少校")
	await novel_interface.show_dialog("附近街道的监控录像暂未发现疑犯踪迹，现正扩大搜查范围，报告完毕。", "少校")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("……就这些？", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("哈蒙盯着少校的眼睛，半晌没有说话，少校不敢言语，只得笔直的站在原地。")
	await novel_interface.show_text_only("哈蒙哼了一声，不满的将手中的平板电脑拍向了少校的胸口——")
	novel_interface.show_character("hamon","speak")
	await novel_interface.show_dialog("你自己看吧！", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少校被拍得向后一个趔趄，赶紧扶稳平板，屏幕上赫然显示着『摩诺拉』标志性的七灯烛台LOGO。")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("这是他们几分钟前发来的。", "哈蒙")
	await novel_interface.show_dialog("摩诺拉发现三个形迹可疑的人混进了地下停车场。", "哈蒙")
	await novel_interface.show_dialog("其中两个潜入了电梯井，意图破坏大厦消防系统。", "哈蒙")
	await novel_interface.show_dialog("还好他们的特工及时出手，抓了一个，还有两个跑了，其中一人在逃走时被子弹擦伤。", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……电梯井！？\n有、有人潜入会场了？", "少校")
	await novel_interface.show_text_only("少校快速翻阅着报告，脑袋顿时嗡的一下——")
	await novel_interface.show_text_only("难道刚才那次爆炸，是转移注意力……")
	await novel_interface.show_text_only("由于地表的停车场被守备部队和军用车辆占用，媒体运载设备的厢型车全都停在会展中心地下。")
	await novel_interface.show_text_only("那么地下停车场确实是最容易被渗透的区域。")
	await novel_interface.show_text_only("虽然军情局对大厦的各个角落都有严密布控，但电梯轿厢底部却是监控死角。")
	await novel_interface.show_text_only("看到自己布置的防线被轻易攻破，少校的额头上立刻渗出了汗珠。")
	novel_interface.show_character("hamon","speak")
	await novel_interface.show_dialog("会场守备方面，军情局不是给我打过包票吗？", "哈蒙")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("我特意把摩诺拉的人支开让他们去外围警戒，你就这么给我露脸？！", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("想到幕帘后的大厅坐满了记者，哈蒙刻意压低了斥责的声音。")
	await novel_interface.show_dialog("这个……\n是、是我失职！", "少校")
	await novel_interface.show_dialog("可摩诺拉的特工不都在会展中心外围吗？\n怎么会出现在大厦里……", "少校")
	await novel_interface.show_text_only("哈蒙微微摇头，拍了拍少校的肩膀。")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("外面那些记者，谁知道有多少他们的人呢……", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("他当然明白，自己这几年从军队系统内部培养出的军情局，是无法和摩诺拉这种怪物相比的。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Speech.png")
	await novel_interface.show_text_only("“他们是这个国家的神经系统，要能对任何危险做出最快速的反应。”")
	await novel_interface.show_text_only("“当有人向你射来一支箭，若需要大脑思考一下再去躲避，那只会中箭而亡。”")
	await novel_interface.show_text_only("哈蒙的叔父，施恩内曼总理曾对议会如此解释摩诺拉为何有毫无制约的最高行动权。")
	await novel_interface.show_text_only("但哈蒙无法容忍全部情报都掌握在这样一个自己无法控制的机构手中。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("信息即权力，是他这几十年来积累的战斗经验——不论是对内还是对外的战争。")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_ConventionCentre.png")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("还有——", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("他意味深长的看着面前这位自己一手提拔的军官。")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("被抓的那个女人，是卡拉卡尔营的少尉。", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("——是我们自己人？！", "少校")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("而且还是塔楼的学员……", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("哈蒙一字一句的说道。")
	await novel_interface.show_text_only("少校意识到这件事可能造成的政治影响，不禁屏住了呼吸——")
	await novel_interface.show_text_only("国防军内部对这次协议一直有不少反对的声音，尤其是那些满腔热血想要建功立业的少壮派。")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("更奇怪的是，根据现场采集的指纹，和她一起行动的还有一个几天前在入境处登记过的外国人。", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("难道是境外的……间谍？", "少校")
	await novel_interface.show_text_only("哈蒙双眉紧锁，沉吟了片刻。")
	novel_interface.show_character("hamon","speak")
	await novel_interface.show_dialog("不排除这个可能，总之我先让摩诺拉把资料都共\n享，可你不能指望他们有多配合……", "哈蒙")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("被抓的那个少尉我让警卫团扣下了，现在关在楼上的安全屋，一并交由你负责。", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是！", "少校")
	await novel_interface.show_text_only("哈蒙转过身去整了整衣领，把领带套了回去。")
	novel_interface.show_character("hamon","speak")
	await novel_interface.show_dialog("仪式马上开始……\n别再给我出乱子了！", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是！请少将放心！", "少校")
	await novel_interface.show_text_only("哈蒙顿了一下，背对着少校幽幽的说道。")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("我今天穿的不是军装，别称呼我的军衔。", "哈蒙")
	await novel_interface.show_dialog("国民不希望继续由军人领导政府了……明白了么？", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("啊……明白！", "少校")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……\n马萨达国际会展中心，室外停车场。")
	await novel_interface.show_text_only("装甲运兵车内。")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_MasadAPCRS.png")
	await novel_interface.show_dialog("你个笨蛋——！！！\n自己钻到人家口袋里了？？！", "莉琉")
	await novel_interface.show_text_only("要不是这耳机能动态调整音量，我的鼓膜大概已经先行去世了吧。")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("啊呜……", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("那、那个……", "小怜")
	await novel_interface.show_dialog("因、因为一直联系不上……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我在控制台捣鼓了半天，好不容易才把这辆车的屏蔽模式关掉，终于接通了莉琉。")
	await novel_interface.show_text_only("耳机中传来“咚”的一声巨响，我脑海中浮现出她把桌面锤烂的画面。")
	await novel_interface.show_dialog("所以……你就擅自行动了对吧？", "莉琉")
	await novel_interface.show_dialog("是不是我太久没操练你，你特别浑身不自在啊……", "莉琉")
	await novel_interface.show_text_only("莉琉不再叫嚷，而是换成了一种低沉但充满威胁的语气。")
	await novel_interface.show_text_only("好像随时会爆发的火山，比刚才更吓人了！！")
	await novel_interface.show_dialog("呐呐……\n你也别这么上火嘛~", "爱衣")
	await novel_interface.show_text_only("爱衣用大般的语气帮我打着圆场。")
	await novel_interface.show_dialog("小怜虽然各项体能考核全是D，却能自告奋勇的参加这种外勤渗透工作，勇气还是很可嘉的~", "爱衣")
	await novel_interface.show_text_only("她这是在劝人还是拱火啊！？")
	await novel_interface.show_text_only("实在没办法，只能硬着头皮自己解释了……")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("因、因为星星——", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SlumArea.png")
	await novel_interface.show_dialog("我记得昨晚是晴天，贫民区的光源又少，所以天上的星星看得很清楚……", "小怜")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SlumArea1.png")
	await novel_interface.show_dialog("可后来那些人经过贫民区的时候，却一颗星星也看不到了。", "小怜")
	await novel_interface.show_dialog("再加上当时，各种通讯设备都没了信号……", "小怜")
	await novel_interface.show_dialog("我觉得那可能不是一般的干扰设备——", "小怜")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("……什么意思？", "莉琉")
	await novel_interface.show_dialog("我感觉和抓捕艾尔加纳那晚，教堂周围的状况一模一样……", "小怜")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Church.png")
	await novel_interface.show_text_only("那天晚上，随着我和莉琉的通话信号突然中断，周围的气氛也变得诡异起来——")
	await novel_interface.show_text_only("远处的楼群变得扭曲模糊，原本清朗的夜空也瞬间暗沉了下来。")
	await novel_interface.show_dialog("我记得当时就是，天上的星星一下子都不见了。", "小怜")
	await novel_interface.show_dialog("然后那些穿着黑色特种作战服的士兵紧随其后……", "小怜")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadAPCRS.png")
	await novel_interface.show_text_only("莉琉沉默了好一阵，我像个打碎了花瓶的小孩，大气都不敢喘的等着家长的回应。")
	await novel_interface.show_dialog("……所以，你就傻乎乎的跟她们去了？", "莉琉")
	await novel_interface.show_text_only("听到莉琉无奈中带着责备语气，我一直紧绷的身体稍稍放松了下来。")
	await novel_interface.show_dialog("她们也只是军校还没毕业的学员吧，不明白这种事应该找专业机构吗？", "莉琉")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("其实开出贫民区后，艾米莉欧跟军队、警察和情报部门都报告了，还打了反恐举报热线……", "小怜")
	await novel_interface.show_dialog("但他们都拿出冠冕堂皇的回应，说会尽快前往贫民区确认，并且感谢提供线索什么的……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧说他们这反应也不奇怪，因为贫民区经常发生帮派械斗，晚上有人拿着武器上街很常见。")
	await novel_interface.show_text_only("而在一般马萨达市民眼中，这里入夜后街上的每个人看起来都像恐怖分子……")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("而且艾米判断，以马萨达的城防系统，那些人根本打不出贫民区。", "小怜")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("如果车上装的真是炸弹，而他们选择在签约仪式时引爆的话——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("孤儿院的那些孩子们……")
	await novel_interface.show_dialog("因为联系的机构都反应迟缓，她们才决定自己搞点事情，迫使签约仪式延期？", "莉琉")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("嗯……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那你不是·有大把时间·能给我·打电话吗——？", "莉琉")
	await novel_interface.show_text_only("莉琉的语气忽然凶狠起来，随着她断句的节奏，耳机中不断传来掰指关节的响声。")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("啊啊啊啊说漏嘴了！！！")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("对、对不起！！！！\n我错了！", "小怜")
	await novel_interface.show_dialog("我错了……", "小怜")
	await novel_interface.show_dialog("可、可是艾米她……", "小怜")
	await novel_interface.show_dialog("被抓走了啊~~~！！！！", "小怜")
	await novel_interface.show_dialog("呜呜呜呜呜呜呜呜……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("紧张、焦虑、后悔、委屈一大堆情绪忽然一股脑涌了上来，我的眼泪止不住的往下掉。")
	await novel_interface.show_dialog("真是笨蛋……", "莉琉")
	await novel_interface.show_text_only("莉琉叹了口气，切换成了坚定而沉稳的声音。")
	await novel_interface.show_dialog("艾米莉欧是国防军的人，还是塔楼的尖子生，况且她也没造成什么实质性破坏。", "莉琉")
	await novel_interface.show_dialog("各个机构有她昨晚报警的录音能证明动机，还有她爷爷就算为了家族颜面也不会袖手旁观。", "莉琉")
	await novel_interface.show_dialog("现在最重要的就是你不能被抓，否则她们行为的性质就不一样了。", "莉琉")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("嗯……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉用这种冷冷的语气说话时，总能一下就抓住重点，让人无法反驳。")
	await novel_interface.show_dialog("还有什么问题吗？", "莉琉")
	novel_interface.show_character("ren_medical","shy")
	await novel_interface.show_dialog("你安慰人的时候，不能温柔点吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("不能，刚才的话听明白了吗？", "莉琉")
	await novel_interface.show_text_only("我点点头，想快点抹掉脸上的眼泪，可鼻子还在不争气的抽泣。")
	await novel_interface.show_dialog("沙尘暴很快就来了，在那期间我帮你找机会撤离，你现在就乖乖呆在车里别乱跑。", "莉琉")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("这辆车是分配给她们的吧，会不会被查到……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("要是能关联到她俩，就不会开着它去劫持物资了。", "莉琉")
	await novel_interface.show_dialog("袭击的事我找人调查，但就算真有人要趁着签约仪式制造袭击，会展中心附近也是安全的。", "莉琉")
	await novel_interface.show_dialog("我现在要先切到其他频道做部署，这条线路一直开着，你说话我能听到。", "莉琉")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("好……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("等她关了语音，我做了几个深呼吸，想尽快让自己冷静下来。")
	novel_interface.show_character("ren_medical","upset")
	await novel_interface.show_dialog("（沙尘暴啊……）\n（似乎只在游戏和电影里见到过……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一只手搭在控制台上，切换着屏幕的信号源。")
	await novel_interface.show_text_only("从四周的车体监控来看，会展中心周围还笼罩在清晨特有的淡粉色微光之中。")
	await novel_interface.show_text_only("然而切到本地早间新闻时，死海东岸的直播画面居然已是黄沙漫天，甚至看不清一米之外了。")
	await novel_interface.show_text_only("再过一会，西岸这边也会变成那幅情景吧……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("新丰洲市，SID总部。")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("莉琉关闭语音后，大屏幕上只剩下秋子的实时通讯影像。")
	await novel_interface.show_dialog("你居然在逼供的时候停下来了……", "秋子")
	await novel_interface.show_text_only("秋子感到有些不可思议。")
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("她不是已经招了么~", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("招了？", "秋子")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("是小怜主动提出要和她俩一起去的，那个笨蛋觉得要是遇到危险，或许能靠自己的体质帮她们脱困。", "莉琉")
	await novel_interface.show_dialog("但她知道我肯定不会批准，所以故意不报告。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("并不是她自己承认的吧哎呀——", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉一记手刀敲在爱衣脑袋上，顺手拿起她桌上小瓶装的功能饮料，仰头一口气喝掉了半瓶。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("那个蠢货怎么可能将自己的心理描述得如此准确。", "莉琉")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("你才睡几个小时就起来了？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("伦伯特上次押给你那个异质物有压缩睡眠时长的效果，我一直放在办公室里。", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那个不是没通过安全性评估吗？\n你小心精神错乱——", "秋子")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("反正对她没什么区别……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉将瓶内剩下的液体一饮而尽。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("如果小怜描述的没错，联合议会背后的组织也参与进来了？", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("不好说……", "莉琉")
	await novel_interface.show_dialog("那种能干扰一定区域内全频率电磁波的异质物武器最早是在西亚战场上出现的。", "莉琉")
	await novel_interface.show_dialog("马萨达从没未公开承认过这种武器的存在，但他们不予承认的武器实在太多了。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("根据伦伯特的描述，那种武器的作用机制与一般的电子干扰设备完全不同——", "莉琉")
	await novel_interface.show_dialog("在其作用范围内，发射源越远的电磁波被扭曲的越厉害，所以能完全阻碍卫星的成像。", "莉琉")
	await novel_interface.show_dialog("天上的星星也并不是消失，而是被扭曲成了长长的细线，由于亮度被分摊而变得无法观测。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("上次国际和平论坛期间，想要劫走天堂之门复制品的那只黑衣行动队，也配有这种装备。", "莉琉")
	await novel_interface.show_dialog("我一直以为那是马萨达军方研发的武器，通过某种协议将技术共享给了联合议会。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("但其实还存在另一种可能——", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("啊嘞？", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉把手里的空瓶立在爱衣的头顶，像驯兽师一样示意她顶好。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("那种武器来自西亚战场上的另一方。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你是说——？", "秋子")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("如果那东西是抵抗军研发的，并且他们将其作为某种筹码交给了联合议会呢？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("指挥室内陷入了沉静，一向喧闹的爱衣居然老实的顶着空瓶一言不发。")
	await novel_interface.show_dialog("这个猜测也太……", "秋子")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("你不觉得奇怪吗？", "莉琉")
	await novel_interface.show_dialog("联合议会能轻易摆平南美各个派系的军阀，却一直对抵抗军这个自己认定的恐怖组织毫无作为——", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("如果这是那个人的设计的话……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Mouchard.png")
	await novel_interface.show_text_only("莉琉在控制台前调出了瓦利德·慕沙尔的卷宗。")
	await novel_interface.show_dialog("外界对抵抗军在装备绝对劣势的情况下一直能够生存最普遍的猜测，是马萨达在养寇自重。", "莉琉")
	await novel_interface.show_dialog("甚至不少人认为，如果国防军不在乎平民伤亡的舆论压力，一周就能把抵抗组织彻底荡平。", "莉琉")
	await novel_interface.show_dialog("SID关于这位抵抗军领袖的情报一直少得可怜，大多是他在妻女被杀前作为学者留下的公开信息。", "莉琉")
	await novel_interface.show_dialog("曾与他在大学共事过的同事和教授都说，这个人极为聪明并且深爱自己的家人。", "莉琉")
	await novel_interface.show_dialog("很难想象一个对马萨达有着深仇大恨的天才，会去做国防军的傀儡。", "莉琉")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("但如果换个角度想的话……", "莉琉")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Kidnap.png")
	await novel_interface.show_dialog("两年前纽摩利达斯的绑架事件——", "莉琉")
	await novel_interface.show_dialog("抵抗军在第二届国际和平论坛期间策划绑架一位董事会成员的女儿。", "莉琉")
	await novel_interface.show_dialog("由于绑匪在市区投放了从马萨达流出的无人武装直升机，董事会迫于压力终止了战争债券的发行。", "莉琉")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("第二学园都市的资金被切断后，马萨达的裁军就只是时间问题了——", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("从经济上，确实如此……", "秋子")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("也是从那个时间开始，抵抗军不断传出派系分裂的消息，让外界觉得这个组织好像随时都会散架。", "莉琉")
	await novel_interface.show_dialog("这两年马萨达国防军一路高歌，歼灭了一个个小头目，但这些派系旁支似乎越打越多。", "莉琉")
	await novel_interface.show_dialog("把军事哨都站伪装成平民救助设施，说明这场战争他们越来越打不起了……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("秋子看着莉琉在几分钟内仅靠一个大胆的假设就串接起一系列线索，并得出了的惊人的结论。")
	await novel_interface.show_text_only("不禁想起她在学校时为自己出头，把导师辩驳得哑口无言时神采奕奕的样子，脸上泛起一阵红晕。")
	await novel_interface.show_text_only("而某个正躲在装甲车里瑟瑟发抖的笨蛋，似乎已经不需要被营救了似的。")
	await novel_interface.show_text_only("莉琉出神的凝视着屏幕上的照片自言自语。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("不在乎一时的输赢，也不在乎自己人的死活……", "莉琉")
	await novel_interface.show_dialog("用精确的计算和纯粹的理性进行的复仇。", "莉琉")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("意识到自己正在被这样的对手逼进死角，施恩内曼总理可不会坐以待毙……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("——所以才设计了『自动反击系统』！？", "秋子")
	await novel_interface.show_text_only("秋子恍然大悟，莉琉微微点了点头。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("即使你满盘皆胜，也永远无法将军。", "莉琉")
	await novel_interface.show_dialog("现在抵抗军只要显露出攻击马萨达堡的意图，就等于与全世界为敌——", "莉琉")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("到时候联合议会可不会在乎自己做过什么承诺~", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("而马萨达只要保住首都，保住这个国家的菁英，就有足够的空间进行改革与转型。", "莉琉")
	await novel_interface.show_dialog("面对施恩内曼这反客为主的一手，慕沙尔选择的对策是……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("那个那个——", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣头上依然顶着瓶子，乖巧的举手发言。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("小怜的营救计划……要不要先讨论一下？", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("不需要~", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("让爱衣没想到是，秋子也几乎同时做出了同样的回应。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("……诶？", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("任何营救都有风险，何况是在摩诺拉的眼皮底下。", "秋子")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("想靠沙尘暴救人不现实，他们对这种早有预报的天气肯定准备了预案。", "莉琉")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("所以让小怜乖乖被抓，然后我们赎回来就好~", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("无论情报还是权限，SID有的是摩诺拉想要交换的资源。", "莉琉")
	await novel_interface.show_dialog("即使他们对小怜的能力有所了解也没关系——马萨达现在急于推销自己的产品，浑身都是软肋。", "莉琉")
	await novel_interface.show_dialog("面对SID和伦伯特的直接威慑，他们不会做出不理性的选择。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("原来如此……", "爱衣")
	await novel_interface.show_dialog("那个叫薇拉的怪力女去救人了，她怎么办？", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("薇拉应该是去找安全屋了吧？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在大型集会场所设置安全屋是国防军的通用安保协议，是马萨达经历多次恐袭后换来的应对经验。")
	await novel_interface.show_text_only("如果发生突发状况，在无法确认出口安全的时候，安全屋可以临时保护VIP或关押重要犯人。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("把这个情报通知薇拉的父亲。", "莉琉")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("好歹是总参谋部的高层，不会眼看自己的女儿羊入虎口的~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("你真是坏心眼呐……", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("所以，现在最关键的就是——", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉一只手捂着下腹，在大屏幕上调出了签约仪式现场的新闻直播。")
	await novel_interface.show_text_only("身材略微发福的哈蒙和留着白色络腮胡的慕沙尔正在长时间握手，前者的笑容几乎快要凝固在脸上。")
	novel_interface.show_character("liliu_uniform1","angry")
	await novel_interface.show_dialog("这次慕沙尔把自己都交了出去，必然是策划了一场能毕其功于一役的袭击……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("莉琉……好像有点不对劲？", "秋子")
	await novel_interface.show_text_only("莉琉的肚子发出“咕——”的一声，接着她一言不发的冲出了指挥室。")
	await novel_interface.show_dialog("…………………………", "秋子")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("哦呀呀……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣轻轻把瓶子从头顶拿了下来，放入一个印着生物危险品标志的密封袋，然后小心的封好。")
	await novel_interface.show_dialog("那个不是一般的功能饮料吧……", "秋子")
	novel_interface.show_character("ai","blush_think")
	await novel_interface.show_dialog("稍微……加了点东西。", "爱衣")
	await novel_interface.show_dialog("本来想用自己测试一下，24小时分批次喝完的…\n…", "爱衣")
	novel_interface.change_expression("blush_stare")
	await novel_interface.show_dialog("谁知道她两口就喝掉了~", "爱衣")

	print("=== 星尘降临篇第18话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
