# stardustdescends_ep16.gd - 星尘降临篇第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep16_script()

func play_script():
	pass

func stardustdescends_ep16_script():
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_ShelterOffice.png")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("您这有多少孩子啊？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我望着陷入沉思的海法阿姨问道。")
	await novel_interface.show_dialog("32个，都是聚落里不到十岁的孤儿。", "海法")
	await novel_interface.show_dialog("我只有能力照顾这么多，而且白天还得靠社工来帮忙，唉……", "海法")
	await novel_interface.show_dialog("附近的贫民区有几百个这样的孩子，马萨达的保育机构经费太少，快要运营不下去了。", "海法")
	await novel_interface.show_text_only("果然如莉琉所说，当周边资源被掠夺殆尽，拥有如此庞大军队的马萨达就会无以为继吗……")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("就没有什么人能帮帮这些孤儿吗？马萨达不是一直对NGO开放……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("曾经来过一些戴着白头盔的，但他们找了几个身体有残疾的孩子拍了几张照片就走了……", "海法")
	await novel_interface.show_dialog("我平时也照顾不过来，做卫生之类的杂活都要靠大一些的孩子帮忙，我能做的太有限了……", "海法")
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("别这么说！孩子们一定都非常感激您……\n其实我也——", "小怜")
	await novel_interface.show_dialog("总、总之拥有家人对这些孩子而言很重要啦！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她有些惊讶的看着我，随后和蔼的笑了笑。")
	await novel_interface.show_dialog("真是好孩子，小怜不是本地人吧？", "海法")
	await novel_interface.show_dialog("艾米说你们今晚住在这，明天早上再走？", "海法")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("嗯，好像因为明天要和抵抗军签停火协议，今晚内城区戒严了……打扰您了！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("没事没事，我先去准备一下浴室。", "海法")
	await novel_interface.show_text_only("海法阿姨起身向门外走，同时自言自语道。")
	await novel_interface.show_dialog("唉，这么多仇怨，真能靠一纸协议就抹平吗……", "海法")
	await novel_interface.stop_music()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("SID指挥室。")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("莉琉边打哈欠边拿着两杯咖啡走进指挥室，看到爱衣还在主机上操作。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("难得你自告奋勇的揽下这种枯燥的情报工作。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("因为目标很有趣嘛~", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉把手中的焦糖玛奇朵放在爱衣旁边的桌上，她拿起杯子抿了一口。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("大半夜喝这么甜的东西没问题吗……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("反正大脑会把糖分烧掉的，而且找到突破口了。", "爱衣")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform1","normal1",0.25)
	await novel_interface.show_dialog("找到线人了？", "莉琉")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("没，根据『0812项目』的加密等级，能了解项目全貌的人应该不超过十个而且根本找不到。", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sigh")
	await novel_interface.show_dialog("确实，以帕兰蒂尔的风格，这种高价值目标是不可能放过的……", "莉琉")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所以我索性换了个思路——", "爱衣")
	await novel_interface.show_dialog("涉及到异质物的航天器，应该是国家工业和科技水平的最高结晶。", "爱衣")
	await novel_interface.show_dialog("在设计、研发、制造、运输过程中涉及到的人员至少应该有几千人。", "爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("而联邦政府解体后，相关保密法失效，所以……", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("你打算用网上的公开信息做分析？\n绝大多数是垃圾信息吧……", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣耸了耸肩。")
	novel_interface.show_character("ai","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform1","sigh",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("最开始是一些前内部员工靠着爆料来赚钱……毕竟人们对这种事都充满了好奇。", "爱衣")
	await novel_interface.show_dialog("接着网络营销公司蜂拥而至，把那些原始信息换上能博人眼球的标题，再添油加醋的报导出来。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("在大众被标题党和假新闻弄到失去兴趣前，总共有六百多万条涉及到NASA机密的公开信息。", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("我想也是……", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉无奈的揉了揉太阳穴，爱衣对她做了个鬼脸。")
	novel_interface.show_character("ai","stare")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform1","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不过如果用AI进行语意拆解和溯源分析，筛选出正交置信度超过90%的信息的话……", "爱衣")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("得到的资料意外的多~", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣敲了下键盘，立刻冒出一屏幕的资料，莉琉瞬间打起了精神。")
	novel_interface.show_character("ai","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform1","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("『0812项目』总质量在30-50吨之间，光学设备就占了5吨，且没有装备任何维生系统。", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("这么重绝对不是卫星了吧……无人空间站？", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("有可能，那个航天器装有两套动力系统，能支持在地球660千米到3.6万千米的轨道上变轨。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("其中离子推动引擎能在太空中长期提供稳定的加速度，设计寿命30年。", "爱衣")
	novel_interface.change_expression("normal") 
	await novel_interface.show_dialog("而另一套传统工质引擎能支持它降落回地球，占据了系统近一半质量。", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"serious")
	await novel_interface.show_dialog("长期滞留太空，并需要不停调整轨道位置……是为了对准400光年外的信号源？", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("而可回收性说明信息量大到难以通过无线传输——", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("到底是什么规模的信息……", "莉琉")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("能找到那颗卫星的位置吗？", "莉琉")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("按说那么大的东西应该逃不过『哨兵系统』，但在各个轨道都没有找到……", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("『哨兵系统』是监测小行星的那个吧？", "莉琉")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯，根据记录，符合这种特征的航天器最后一次变轨时间大概在一年前。", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("那个时间点就是说……控制秘钥在黑市上卖掉了？", "莉琉")
	novel_interface.character_light(0.35,"wink")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那就不知道了，那么大的东西想要藏起来，可能是放到了月球背面？", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sigh")
	await novel_interface.show_dialog("话说……你什么时候写了这种AI？", "莉琉")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我可写不出来，是前天一个ID叫『Elder Seven』的账号上传的这套模型和参数。", "爱衣")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("这几天开源社区的讨论版因为这个事都炸锅了~", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("有什么特别吗？", "莉琉")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那人同时公开了算法，大家粗略估计要想把AI训练到这种程度，大概要消耗价值十几亿的算力。", "爱衣")
	await novel_interface.show_dialog("而且这种规模的代码绝不是一个人能完成的。", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("哪个机构会把这么有价值的东西开源……做好隔离了吗？", "莉琉")
	novel_interface.character_light(0.35,"wink")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("当然，我都是在『Themis』的虚拟机上运行的。", "爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("这套模型能快速归档海量同类信息，并判断信息之间的相关性——", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("同时根据不同信源的正交程度为信息置信度打分。", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"jest")
	await novel_interface.show_dialog("听起来不错啊，那些无良的营销公司要遭殃了？", "莉琉")
	novel_interface.character_light(0.35,"blush_think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("一开始我也这么觉得，但你想想，如果把它接到足够大的数据库上的话……", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉的表情忽然严肃了起来——")
	novel_interface.show_character("ai","blush_think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("liliu_uniform1","serious",0.25)
	await novel_interface.show_dialog("比如政府安保监控系统……？", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("是啊，配合图像识别系统，能对所有人建档分类并判断相关性。")
	await novel_interface.show_text_only("亦能根据这些信息，判断对象的目的并预测人们的行为，甚至有意加以引导……")
	await novel_interface.show_text_only("莉琉摇了摇头，现在还不是分散精力的时候。")
	novel_interface.show_character("ai","blush_think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("liliu_uniform1","sigh",0.25)
	await novel_interface.show_dialog("这个AI的事以后再说。", "莉琉")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("明天代表马萨达签署停火协议的人定下来了，是国防军北方司令部的陆军少将哈蒙。", "莉琉")
	await novel_interface.show_dialog("而且出于政治目的考虑，协议签署地选在死海边的马萨达国际会展中心。", "莉琉")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("也是，在隔离墙里签署的停火协议，怎么想都无法让人信服吧。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("抵抗组织都是些什么人啊，我之前没关心过。", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("你当然不会关心了~", "莉琉")
	await novel_interface.show_dialog("最初是由地方民族武装、极端宗教团体，政府解散后的军队残部和流寇土匪组成的联军。", "莉琉")
	await novel_interface.show_dialog("都是一些痛恨马萨达的武装组织，内部讲着七八种地方语言，本来是应该被各自歼灭的——", "莉琉")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("能把这样一群人组织起来的是什么家伙啊？", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("就是明天代表抵抗军签署协议的瓦利德·慕沙尔。", "莉琉")
	await novel_interface.show_dialog("被装备领先两个代际的国防军围剿了这么多年，还能把抵抗组织越做越大。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣在屏幕上调出了瓦利德·慕沙尔的档案。")
	novel_interface.show_character("ai","dizzy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform1","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……居然是个博士！？", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("嗯，这个曾经全世界悬赏金额最高的男人，是本古里安大学的物理学博士。", "莉琉")
	novel_interface.change_2nd_expression("serious")
	await novel_interface.show_dialog("据说圣城被摧毁后，他在贝尔谢巴市的妻女被暴怒到失去理智的马萨达人从家里拖到了街上……", "莉琉")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("无差别的民族仇恨？\n人类真是愚蠢到无可救药的动物呐……", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉一个手刀敲在爱衣头上，爱衣条件反射的缩起脖子，却发现对方这次并没有太用力。")
	novel_interface.show_character("ai","think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("liliu_uniform1","sigh",0.25)
	await novel_interface.show_dialog("是啊，人类真是愚蠢。", "莉琉")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("那件事后慕沙尔就离开了大学，再次出现时已经成为了马萨达最头疼的敌人。", "莉琉")
	await novel_interface.show_dialog("如果不是因为马萨达的自动反击系统，这个人大概会一直战斗到死吧……", "莉琉")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("你去睡会吧，都在这坐好几个小时了。", "莉琉")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("不知道明天还会出什么事儿……", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("外城区孤儿院。")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_ShelterCorridor.png")
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("呼……头发里全是沙子，洗完澡舒服多了。", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("（还好军用物资里有一次性内裤……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这里浴室比我想象的大，而且收拾得很干净，台子上整齐摆着很多小朋友的塑料玩具。")
	await novel_interface.show_text_only("我边擦头发边拿起浴室外面正在充电的手机，断开了无线音箱的连接。")
	await novel_interface.show_dialog("小怜洗完了？", "海法")
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("嗯嗯，很舒服~\n谢谢海法阿姨！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("刚才我好像听到浴室里在放音乐？\n你的手机不是放在外面吗……", "海法")
	novel_interface.show_character("ren_medical","shy_left")
	await novel_interface.show_dialog("没、不是！没有啦……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我满脸通红的捂住了胸部。")
	await novel_interface.show_text_only("忽然，放在手机旁边的步话机传出一阵噪音——")
	await novel_interface.show_dialog("小怜在吗？！", "艾米莉欧")
	novel_interface.show_character("ren_medical","serious")
	await novel_interface.show_dialog("怎么？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.show_dialog("你快让海法小姨把灯都关掉！大门也锁起来！\n我这边发现——", "艾米莉欧")
	await novel_interface.show_text_only("还没说完，步话机就陷入了一片噪音。")

	print("=== 星尘降临篇第16话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
