# stardustdescends_ep19.gd - 星尘陨落篇第19话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep19_script()

func play_script():
	pass

func stardustdescends_ep19_script():
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Recording.png")
	await novel_interface.show_dialog("我的女儿娜莎今年7岁，最近她很喜欢拉着我和她一起玩拼图。", "录音")
	await novel_interface.show_dialog("有时我会故意摆出不情愿或很忙的样子，看着她央求自己一会之后才“勉为其难”的答应。", "录音")
	await novel_interface.show_dialog("其实我很喜欢陪她玩……但娜莎撒娇的样子实在太可爱了。", "录音")
	await novel_interface.show_text_only("录音中传来观众的一阵笑声。")
	await novel_interface.show_dialog("我们玩的是一种新式的拼图，和我小时候的拼图很不一样——", "录音")
	await novel_interface.show_dialog("每块拼图都有一面是彩色电子墨水屏，显示着固定的图案，和传统的拼图没什么区别。", "录音")
	await novel_interface.show_dialog("但当你逐渐拼好并填上最后一块拼图时，所有零片都会被点亮，拼图上的画面也会流动起来……", "录音")
	await novel_interface.show_dialog("我还记得第一次玩的时候，最初我以为我们在拼的是那张名为“蓝色弹珠”的地球照片——", "录音")
	await novel_interface.show_dialog("但当我女儿拼上最后一块的时候，整个画面动了起来：镜头渐渐拉远，穿过月球、火星、木星……", "录音")
	await novel_interface.show_dialog("然后一路飞出太阳系，越过无数恒星，最终呈现出整个银河。", "录音")
	await novel_interface.show_dialog("娜莎兴奋的跳了起来，她尖叫着摇着我的胳膊，就像我第一次完成异质物光线偏转实验时的样子……", "录音")
	await novel_interface.show_dialog("我相信在场的各位都和我一样经历过那样的时刻。", "录音")
	await novel_interface.show_dialog("那天我穿着拖鞋和睡裤大叫着跑出实验室，一路冲进了我们大学里一位微生物学教授的办公室。", "录音")
	await novel_interface.show_dialog("那老家伙曾跟我说，要是我能把实验做成，就把他学生送他的那瓶名贵的日本酒开封……", "录音")
	await novel_interface.show_dialog("那酒险些呛死我，真不敢相信竟能卖那么贵。", "录音")
	await novel_interface.show_text_only("观众哄堂大笑，还有人在鼓掌。")
	await novel_interface.show_dialog("后来我逐渐明白，其实我们研究异质物的过程和拼图真的很像。", "录音")
	await novel_interface.show_dialog("在谜题最终解开前，你只能凭直觉和很少的线索去尝试。", "录音")
	await novel_interface.show_dialog("就像拼图时，要先找到四个角这样的公理作为逻辑支点。", "录音")
	await novel_interface.show_dialog("然后从四角出发，想方设法合拢边框。", "录音")
	await novel_interface.show_dialog("正如从最基本的公理开始，逐步推导出合乎逻辑的推论。", "录音")
	await novel_interface.show_dialog("接着在搭好的边框下，不断试错，一步步向未知的核心推进……", "录音")
	await novel_interface.show_dialog("这个过程漫长而艰苦，而只有当最后一块拼图被拼好的时候，我们才能一窥世界的真相。", "录音")
	await novel_interface.show_dialog("在此期间，你尽可充满期待的畅想，最终你将看到一副怎样雄伟壮丽的图景。", "录音")
	await novel_interface.show_dialog("我相信这是科学研究最迷人的地方，也是我们大多数人坚持不懈的动力！", "录音")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("咔哒——")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("在观众的掌声刚要响起时，录音文件戛然而止。")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("这是莉琉从一位去世研究员的电脑里找到的录音。", "爱衣")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("据说是十几年前，慕沙尔在第30届索尔维会议上做的一段非公开演讲~", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","shock")
	await novel_interface.show_dialog("说话的人就是……瓦利德·慕沙尔？","秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("秋子有些意外，一时无法将那个儒雅随和的声音和杀伐决断的恐怖分子头子联系起来。")
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("第30届索尔维会议……是2026年吧？","秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这个由比利时企业家欧内斯特·索尔维创办的学术会议，每次都会邀请当时世界上最顶尖的科学家。")
	await novel_interface.show_text_only("会议每三年举办一次，虽然因战争和政治局势等原因几度停办，但依然延续至今。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("是啊，就是在开战前一年……","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("慕沙尔当时不会想到，那次演讲几个月后，他的妻女就会因盲目的民族仇杀而暴尸街头。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("那时国际条约禁止异质物的研究，这种学术会议也只能以非公开形式进行讨论。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("不过第二年各国就撕破了脸，参加过那场会议的人现在大多都也已经不在了呢……","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣脸上闪过一丝惆怅的神情，但很快就恢复成一如往常的样子。")
	await novel_interface.show_text_only("她在大屏幕上调出了数十家不同媒体平台的直播画面，毫无例外都是马萨达的签约仪式——")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SigningCeremony.png")
	await novel_interface.show_text_only("一切似乎都顺利的进行着，没有任何关于先前艾米莉欧在会场附近制造那场爆炸的报导。")
	await novel_interface.show_text_only("在冗长的文件签署流程完毕后，马萨达和抵抗军的签约代表走到一起，共同将手掌按在一块屏幕上。")
	await novel_interface.show_text_only("二人的掌纹连同协议文本被同步传到网上，马萨达的城市防卫系统立刻开始更新防御协议。")
	await novel_interface.show_text_only("与此同时，抵抗军方面主动提交了二十多万名赞同停火协议成员的电子档案。")
	await novel_interface.show_text_only("今后只要这些人放弃武装，就可以像普通市民一样自由进出马萨达的大部分区域。")
	await novel_interface.show_text_only("代价是要在两年内佩戴追踪手环，并被纳入摩诺拉的监控系统。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SigningCeremony1.png")
	await novel_interface.show_text_only("在仪式的最后，双方代表要在媒体面前交换文件并握手。")
	await novel_interface.show_text_only("国防军陆军少将和抵抗军领袖在镜头前握手时间长达三分钟。")
	await novel_interface.show_text_only("哈蒙夸张的笑容几乎快要凝固在脸上，穆莎尔则只是保持着淡然的微笑。")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("爱衣看着屏幕上那张咧开的大嘴，又扫了一眼昨天从社交网络上收集来关于此人的资料。")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("哈蒙啊……\n怪不得军队里给他起的外号是蛤蟆~","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看莉琉还没回来，秋子摘下了眼镜，很自然的对着镜片哈了口气。")
	await novel_interface.show_text_only("她擦拭镜片时，之前被镜腿卡住的一缕头发从鬓边垂下，神情和气质瞬间就像变了个人——")
	novel_interface.show_character("akikounglass")
	await novel_interface.show_dialog("这家伙是马萨达国防军里鹰派的代表人物。","秋子")
	await novel_interface.show_dialog("拥护者称赞他是护国功臣，反对者说他是血债累累的屠夫……","秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣察觉到秋子的语气变化，满脸好奇盯着她的视频影像。")
	await novel_interface.show_text_only("秋子似乎并不在意，继续回忆道。")
	novel_interface.show_character("akikounglass")
	await novel_interface.show_dialog("当年哈蒙跟随他的叔父——时任复国军中将的施恩内曼总理，一起参加过马萨达保卫战。","秋子")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("就是弹尽粮绝时靠『幻想军势』翻盘的那次？","爱衣")
	await novel_interface.show_dialog("那确实够资格竞选了……","爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("似乎参加过那场战斗的高级军官，只要还活着的全都在军队和政府系统里身居要职~","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("平日里对政治并不感兴趣的爱衣，凭她昨晚用AI搜集整理的情报做出了自己的判断。")
	novel_interface.show_character("akikounglass")
	await novel_interface.show_dialog("当时的那些军官现在还活着的不到十个，个个都是战争英雄，而且还知晓国家的核心机密……","秋子")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("『幻想军势』的真实情报嘛……他们确实把这个秘密保护的很好。","爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("不过哈蒙能得到这么多支持也有其他原因吧，据说要不是他的高效运营，国防军早就破产了……","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("akikounglass")
	await novel_interface.show_dialog("“运营”？\n应该说是掠夺吧……","秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("秋子丝毫不掩饰对此人的不屑。")
	novel_interface.show_character("akikounglass")
	await novel_interface.show_dialog("除了绕过国际法打各种擦边球，还对军管区实行种族隔离，大幅提升无人武器的开火权限……","秋子")
	await novel_interface.show_dialog("帕兰蒂尔的情报官判断，如果这家伙上台，肯定会在第一时间通过国家民族法案。","秋子")
	await novel_interface.show_dialog("毕竟大拉比已经表示了对哈蒙的明确支持……","秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣对这种超纲的政治话题不知怎么接，悄悄的搜索了一下“国家民族法案”。")
	await novel_interface.show_text_only("关键词下面冒出一大堆“种族隔离”之类的字眼。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("（人类还真是无聊啊……）", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("akikounglass")
	await novel_interface.show_dialog("对了，莉琉怎么还没回来……\n那饮料真的没问题吗？","秋子")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("放心，那女人很强悍的——","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣打开一瓶新的功能饮料，抿了一小口，瞬间精神了不少。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("现在大概正蹲在洗手间里思考问题吧……","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("akikounglass")
	await novel_interface.show_dialog("……思考怎么处决你？","秋子")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("思考法穆尔的计划啦~！！","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然收集了大量信息，但爱衣对抵抗军即将发动攻击的形式依然毫无头绪。")
	await novel_interface.show_text_only("她又调出死海附近的一系列卫星图像。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SatelliteDustStorm.png")
	await novel_interface.show_text_only("从气象卫星的实时图像看，沙尘暴就像一滩在地球表面肆意流淌的污水。")
	await novel_interface.show_text_only("此时这摊污水已经完全淹没了死海东岸的穆吉布大峡谷，正朝西南方向的马萨达堡滚滚而来……")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("爱衣又用SID所属卫星对马萨达的贫民区扫描了两次，没有发现任何时空相位波动的踪迹。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("就算真有那种能屏蔽电磁波的异质物武器，现在应该也处于关闭状态吧——","爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("否则现在贫民区的卫星图像就因为光线偏转效应会变成一片扭曲模糊的样子……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("在没有异质物武器的情况下攻打重兵把守的马萨达堡？","秋子")
	await novel_interface.show_dialog("就算AI防御武器100%瘫痪也不可能做到吧……","秋子")
	await novel_interface.show_dialog("按照小怜描述的那种作战小队规模，那些恐怖分子撑不到20分钟，根本不可能踏进内城区半步。", "秋子")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("确实不对劲……","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("就像莉琉所说，慕沙尔这次是把自己和几十万抵抗军同袍都交了出去。")
	await novel_interface.show_text_only("如果真是为了发动袭击的话，那就像在牌桌上选择了全押的赌徒，势必要在这一轮就把对方带走。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_doomsday.png")
	await novel_interface.show_text_only("更困难的是，他们还面临一个隐含的限定条件：不能触发马萨达的自动反击系统。")
	await novel_interface.show_text_only("如果不在乎自动反击系统的话，抵抗军大可以继续原来的战略，不断挤压马萨达的生存空间。")
	await novel_interface.show_text_only("总有一天马萨达的社会和经济系统会全面崩溃，到时抵抗军就能从正面进攻轻松占领这座城市。")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("爱衣一言不发的盯着大屏幕陷入了沉思，时间也一分一秒的过去……")
	await novel_interface.show_dialog("啊啊啊啊啊啊，完全想不到啊！！！","爱衣")
	await novel_interface.show_text_only("爱衣突然像考场上解不开高分题的考生，额头重重砸在操作台的键盘上，把秋子吓了一跳。")
	await novel_interface.show_dialog("如何在不触发自动反击系统的情况下歼灭或占领马萨达内城区……","爱衣")
	await novel_interface.show_text_only("爱衣保持把脑袋埋在键盘里的状态，小声的自言自语。")
	await novel_interface.show_dialog("这个问题我想好几周了，完全不可能做到嘛！！","爱衣")
	await novel_interface.show_dialog("……好几周？","秋子")
	await novel_interface.show_dialog("……你平时想这种问题做什么？","秋子")
	await novel_interface.show_dialog("呃——\n嘛……","爱衣")
	await novel_interface.show_text_only("爱衣抬起头，脑门被键盘印出几个红印，有气无力的回答道。")
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("就是大脑闲着的时候打发时间……我从马萨达发布自动反击系统的那一天就开始想这个问题了。","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……你是恶魔吗？！","秋子")
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("与此同时，签约仪式会场外。")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadAPCRS.png")
	await novel_interface.show_text_only("时间一分一秒过去，我不安的用双手抱膝缩在座位里，等待莉琉说的“撤离指令”。")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("（好像女孩子做抱膝的动作确实比较轻松啊……）", "小怜")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("（就是屁股有点凉飕飕的……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("控制台屏幕上是签约仪式的电视直播，似乎导播都觉得那两人握手时间太久，把画面切回了演播室。")
	await novel_interface.show_text_only("演播室里主播开始和嘉宾东拉西扯，我盯着艾米莉欧昨晚塞给我的军用步话机看得出神。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_UAVs.png")
	await novel_interface.show_text_only("忽然，屏幕上的直播画面切到会场外，摄像师将长焦镜头对准了内城区隔离墙的上空。")
	await novel_interface.show_text_only("嘉宾和场外记者的音调同时提高，只见隔离墙上空\n，几组正在巡航的无人机群不约而同得下降。")
	await novel_interface.show_text_only("根据流程，沿隔离墙巡逻的无人机会分成十二批次轮流回到停机埠更新防御协议。")
	await novel_interface.show_text_only("看到常年盘旋在隔离墙上空的防御武器逐渐下降并消失在墙后，现场解说的女记者情绪十分激动。")
	await novel_interface.show_text_only("她用颤抖到要哭出来的声音，赞颂并拼命拔高这一幕的历史意义，不停说着和平终于降临之类的话。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_APC_Wall.png")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("（拜托……）\n（那些无人机更新完协议还要飞回来的吧？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("而且那明明是萨蒙顿电视台的，标准的金发碧眼白种人，却比大多数当地记者都激动。")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("果然有媒体当场泪崩啊~","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我恍然大悟，怪不得一个室内的签约仪式却非要赶在沙尘暴到来前的清晨时分举行。")
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("再晚些的话，他们恐怕只能拍到漫天黄沙了……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧说的没错，哈蒙这一手确实效果拔群。")
	novel_interface.show_character("ren_medical","normal2")
	await novel_interface.show_dialog("艾米和薇拉……\n应该会没事吧？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("刚才我反复切换电视频道，没看到任何有人闯入会场的报导，或许薇拉已经被她父亲截住了？")
	await novel_interface.show_text_only("还有被抓走的艾米……虽然莉琉对局势的判断很少出错，但我心中依然感到莫名的不安。")
	await novel_interface.show_text_only("如果抵抗军真在筹划某种攻击的话……")
	await novel_interface.show_text_only("我抬头看着车顶，若隐若现的蜂窝状反光纹路是这种异质物装甲的典型特征。")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("（不知这辆车能不能扛得住……）\n（我记得它能在辐射区行驶，密封性应该不错。）", "小怜")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("（不过艾米似乎说过这车的隔热性很差……？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我还正胡思乱想，突然地面带动车体震了一下。")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("诶！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("停车场外隐约传来人群骚动的声音，几秒后电视转播信号交代出了缘由——")
	await novel_interface.show_text_only("先是一股黑烟从高大的隔离墙底部升起，片刻之后就传来了爆炸的闷响。")
	await novel_interface.show_text_only("很快大团的灰色烟雾覆盖了全部画面，人群开始尖角，摄影师也在慌乱中终止了拍摄。")
	await novel_interface.show_text_only("装甲车外的骚动声音越来越大，还有国防军杂乱的脚步和大声的呼喝声。")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("出……出事了！？","小怜")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("几分钟前，马萨达内城区。")
	await novel_interface.show_text_only("第五学园都市大使馆地下室。")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Basement.png")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("为什么要跑到使馆地下室联络啊，SID的保密线路不是很安全吗？","安妮")
	novel_interface.change_expression("frustrate")
	await novel_interface.show_dialog("总感觉这里阴森森的……","安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是怕隔墙有耳啦，就算使馆里也很可能有摩诺拉的渗透人员。","爱衣")
	await novel_interface.show_dialog("而且那地下室是按照能抵御近距离核爆的标准建设的，是不是多点安全感了~？","爱衣")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("啊？哈哈……\n（马萨达人听到这话估计会直接气炸吧……）","安妮")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("……说起来莉琉不在吗？","安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("她有点……不方便~\n而且现在还没到约定的联络时间嘛，怎么啦？","爱衣")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("刚才我起床，发现小星尘蜷缩在旁边的床上嘴里一直支吾着什么。","安妮")
	await novel_interface.show_dialog("我以为她做噩梦了，却怎么摇都摇不醒她……","安妮")
	await novel_interface.show_dialog("使馆军医说她的生命体征都正常，但似乎陷入了某种意识模糊的状态。","安妮")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("如果要做进一步检查的话就只能去医院了，可她现在的身份……","安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("昨天本来应该给小星尘去补办入境手续，但因小怜被绑架，这个安排被临时取消了。")
	await novel_interface.show_dialog("有趣……她进入那种状态前有什么异常举动吗？","爱衣")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("也没什么吧……\n就是她头顶那个猫耳形状的耳机一直在闪。","安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是类似警报器的闪烁？","爱衣")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("不是，比那个要快，而且频率很不均匀……","安妮")
	novel_interface.change_expression("unhappy")
	await novel_interface.show_dialog("啊！有点类似光纤网线插口的那种闪烁。","安妮")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("线路另一头，爱衣刚想追问其他细节，突然指挥室的大门被打开了。")
	await novel_interface.show_text_only("莉琉此刻正扶着门框，额头上还有些微汗滴。")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("爱衣见莉琉回来被吓了个激灵，双手下意识的护住脑袋。")
	await novel_interface.show_text_only("秋子也连忙戴上眼镜咳了两下，瞬间恢复到了那种冷冰冰的姿态。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("安妮，那孩子的事我知道了，暂时应该没有大碍。","莉琉")
	await novel_interface.show_dialog("你先下线吧，如果她有新情报你随时汇报，这边现在有更重要的事要处理。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("好的，我先闪啦。","安妮")
	await novel_interface.show_text_only("莉琉似乎并不急于找爱衣算账，不知是不是药劲还没过，她言语中依然带着那种兴奋感。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("我想了很久……慕沙尔的计划，关键线索是时间！","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("什么意思？","秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉单刀直入的发言，秋子脑子一时没转过来。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("你们想想，签约仪式为什么要选在今天？","莉琉")
	await novel_interface.show_dialog("马萨达对这次仪式极为重视，还大费周章的管制负面消息吸引媒体宣传造势。","莉琉")
	await novel_interface.show_dialog("甚至临时封锁了苏伊士运河，生怕哪里出了差池。","莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("但为什么把这么重要的仪式定在了早就预报会有沙尘暴来袭的今天？","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("确实……按照马萨达的惯例，重大活动会尽量避开恶劣天气，应该把日期延后才对。","秋子")
	await novel_interface.show_dialog("而且为了避开沙尘暴覆盖全城的时间，仪式还被迫定在了清晨，这个时间很多国民还在睡觉吧？","秋子")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("所以可以推测这个日期是抵抗军方面的意思，甚至很可能是慕沙尔本人的坚持……","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("你是说……慕沙尔的袭击计划必须在今天的某个特定时间才能执行？","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","shock")
	await novel_interface.show_dialog("啊！快看电视！","秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉和爱衣循声望向大屏幕，直播画面中一股黑烟正从高大的隔离墙底部升起。")
	await novel_interface.show_text_only("随后传来了爆炸和人群骚乱的声音……")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("已经开始了吗……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("他们是想趁沙尘暴的时候发动总攻？","秋子")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("应该不是，沙尘暴前锋还有二十多分钟才能到那\n边。","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("电视台的镜头很快被大量灰色的烟雾遮挡，爱衣立刻切换到间谍卫星的红外成像画面。")
	await novel_interface.show_text_only("从近地轨道俯瞰的红外视图上，分析软件快速标注出了所有可见的作战单位。")
	await novel_interface.show_text_only("本应在贫民区隔离墙上空巡逻的无人机群，此时应该还在更新协议无法行动。")
	await novel_interface.show_text_only("但只要稍稍拉远视角，就能看到周边巡逻的其他机群和城防部队都在赶向那个区域援防。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("等一下，看那几个地方……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉指着贫民区内几块糊成一片的小块区域，显然是受到了某种异质物的影响。")
	await novel_interface.show_text_only("然而或许是受功率所限，每块模糊区域的半径都不大，虽看不到内部但足以判断袭击者的大致方位。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("果然是小怜说的那种异质物武器吗……","莉琉")
	await novel_interface.show_dialog("倪克斯所在的那架运载机上有激光探声阵列吧？","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("啊……明白~","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣立刻心领神会的发出一串坐标指令，盘旋在马萨达上空的运载机底部随即展开了两排激光设备。")
	await novel_interface.show_text_only("协同程序很快将运载机采集到的的声音与红外视图同步，每片模糊的区域都传出了密集的爆炸声。")
	await novel_interface.show_dialog("他们已经和国防军的地面部队开始交火了？","秋子")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("不，不可能这么快……","莉琉")
	await novel_interface.show_dialog("目前只能猜测，很可能每块模糊区域中心都有一组小怜昨晚见到的小分队。","莉琉")
	await novel_interface.show_dialog("而烟雾弹和异质物武器，屏蔽了一切可能的光学探测手段。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("这些人到底要做什么事，这么极力遮挡视线……","秋子")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("话说……\n他们的战线拉得也太长了吧？","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣把视角拉远，地图上总共八块模糊区域，每块互相间隔一两百米，顺序排成了一条曲线。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("这个阵型……是嫌自己死不够快吗？","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("果然，最靠两端的小分队不到五分钟就被最先抵达的援防无人机群歼灭了。")
	await novel_interface.show_text_only("随着厢型车中的异质物武器被摧毁，红外画面中顿时只剩下六块依然模糊的区域。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("不，是因为……\n他们根本就没打算活着出去。","莉琉")
	await novel_interface.show_dialog("这种自杀式袭击，是为了掩护某个需要抓住特定时间窗口才能达成的战略意图。","莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("他们真正的目标或许是——","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉调出了这片区域原本的地图，将坐标与红外图像重合起来。")
	await novel_interface.show_dialog("隔离墙？！","秋子")
	await novel_interface.show_text_only("秋子和爱衣几乎同时发现了端倪。")
	await novel_interface.show_text_only("八个作战小队基本上是沿着着靠近贫民区那段长达1.5公里的隔离墙分布排列的。")
	await novel_interface.show_text_only("随着导致卫星视野模糊的异质物武器被摧毁，能在红外画面中清晰的看到隔离墙的废墟。")
	await novel_interface.show_text_only("他们趁无人机群更新协议的短暂窗口期，要以自己的生命为代价，摧毁那段不到两公里的隔离墙。")
	await novel_interface.show_dialog("隔离墙有几十米高吧，怎么会这么轻易就……","秋子")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("那种墙并不厚，只要让携带炸药的简易无人机分布在关键受力点上同时引爆就能破坏掉。","莉琉")
	await novel_interface.show_dialog("但在有无人机群巡航的时候，这是不可能完成的操作……","莉琉")
	await novel_interface.show_dialog("其实隔离墙并不是按防御工事设计的，想靠一堵墙防御现代兵器也不现实。","莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("它的初衷是区分不同民族的活动区域，顺便改善内城区的自然环境。","莉琉")
	await novel_interface.show_dialog("马萨达的城防力量主要还是靠那些沿隔离墙设置的驻军、哨点和自动防御武器。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("国防军方面似乎也察觉到了对方的意图，迅速抽调了大量防卫部队，纷纷涌向隔离墙的缺口。")
	await novel_interface.show_text_only("已经到位的部队和无人机群如临大敌般的驻守在缺口处，准备抵御可能的下一波攻击……")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("这么快就都打光了……？","爱衣")
	novel_interface.change_expression("blush_dizzy")
	await novel_interface.show_dialog("果然还是同时挂载射击加自爆模组的无人机群最有效率呐~！！","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣眼中发出了奇异的光芒，突然整个人都激动了起来。")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("莉琉莉琉，咱们要不要也……\n啊呜！！！","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉这次并没有敲打爱衣，而是直接从身后按着后脑勺把爱衣的脸埋进键盘里磨蹭着。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("马萨达的无人机那么有效率，是因为它们的敌我识别模块会优先从肤色和面部特点判断种族。","莉琉")
	await novel_interface.show_dialog("同时根据体态判断目标是否营养不良，以及身上是否佩戴了非国防军制式的武器。","莉琉")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("就像在功能饮料里偷加了其他药物给人喝，是不是很缺德呢~~~~？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣嘴里不停发出“嗷呜呜”的声音，还伴随着奇怪的笑声，不知她是痛苦还是兴奋。")
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	novel_interface.change_music("res://assets/audio/music/Wind.mp3")
	await novel_interface.show_text_only("不久之前。")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_SigningCeremony.png")
	await novel_interface.show_text_only("袭击发生后，从切回会场仅有几秒的直播片段中可以看到主席台上二人短暂的互动——")
	await novel_interface.show_text_only("哈蒙怒视着慕沙尔，似乎在压低声音质问对方，而慕沙尔的视线只是平静的延伸向远方……")
	await novel_interface.show_text_only("安保人员冲上主席台要将两位代表带回安全屋，慕沙尔起身后却僵直的向后倒了下去——")
	await novel_interface.show_text_only("周围的人赶紧扶住了他，迅速将这位抵抗军领袖连搀带架的带下了主席台……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("会展中心三层。")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_SafeHouse.png")
	await novel_interface.show_text_only("哈蒙被五个安保人员簇拥着出了电梯，怒气冲冲的走进关押囚犯的安全屋。")
	await novel_interface.show_text_only("安全屋是套间结构，他走进大门紧闭的内间，叫正在审讯犯人的那位军情局少校停手。")
	await novel_interface.show_text_only("只见近乎虚脱的艾米莉欧手臂上插着静脉注射的针头和导管，正斜坐在椅子上，呼吸轻微而急促。")
	await novel_interface.show_text_only("她的手脚紧拷在与地板一体的金属椅上，旁边还有两个荷枪实弹的宪兵看押……")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("招供什么了吗？","哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少校心虚的摇摇头。")
	await novel_interface.show_dialog("一直在死撑，刑讯药物已经用到最大剂量了，今天再继续的话很可能会猝死……","少校")
	await novel_interface.show_text_only("少校还想继续解释，一个军官急匆匆走进屋内交给哈蒙一份报告。")
	novel_interface.show_character("hamon","shout")
	await novel_interface.show_dialog("慕沙尔死了？？！","哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("医生估计他在参加仪式前，就服下了延时发作的毒药……","军官")
	novel_interface.show_character("hamon","shout")
	await novel_interface.show_dialog("混账！！","哈蒙")
	await novel_interface.show_dialog("刚才的骚动摆平了吗？\n到底怎么回事！","哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("有抵抗军分散成了几组并提前埋伏在贫民区，趁着无人机群更新协议时发起了袭击。","军官")
	await novel_interface.show_dialog("目前袭击者已被全歼，正在做身份识别，似乎是慕沙尔第一卫戍旅的人……","军官")
	await novel_interface.show_dialog("他们把内城区东北侧，面向贫民区的大概1.3公里的隔离墙炸掉了。","军官")
	novel_interface.show_character("hamon","unhappy")
	await novel_interface.show_dialog("第一卫戍旅都是抵抗军中的精英，这么送死就为了炸段隔离墙……？","哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("现在城防部队正在准备应对可能的第二波袭击，但尚未发现后续打击的踪迹……","军官")
	await novel_interface.show_text_only("哈蒙咬牙切齿的在房间里来回渡步。")
	await novel_interface.show_text_only("虽然明显感到哪里不对，但现在他还面临着更严重的问题——")
	await novel_interface.show_text_only("这本是为竞选准备的一次重要政治宣传，结果自己却在全世界媒体前弄得颜面尽失。")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("必须转移焦点……\n还要显示出强硬的姿态……", "哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("哈蒙自言自语的念叨了一会，把军官打发走，接着走到少校身边准备交代工作。")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("要全面封锁穆沙尔死亡的消息。","哈蒙")
	await novel_interface.show_dialog("让技术部门的人做一段认罪视频，不是能用什么拟合技术模拟人脸和声音吗？就说……","哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("长官……","少校")
	await novel_interface.show_text_only("一直盯着平板上简报的少校打断了他。")
	await novel_interface.show_dialog("刚才网上公开了一份有慕沙尔电子签名的录音，似乎是他的遗言。","少校")
	novel_interface.show_character("hamon","speak")
	await novel_interface.show_dialog("什么？！","哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("他气急败坏的抢过少校手中的平板设备。")
	await novel_interface.stop_music()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Recording.png")
	await novel_interface.show_text_only("十几秒的空白之后，出现一个沧桑而浑厚的声音。")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_dialog("我是瓦利德·慕沙尔，这段录音会在我佩戴的生命检测设备判定我死亡后自动发布到网络。","慕沙尔")
	await novel_interface.show_dialog("以下是我的遗言和自白——","慕沙尔")
	await novel_interface.show_dialog("多年来，国防军和摩诺拉一直视我为最大的敌人并一直在调查我的踪迹。","慕沙尔")
	await novel_interface.show_dialog("官方记录中，我最后现身是在贝尔谢巴市，我的妻子和女儿被发现在距家70米的路边因外伤致死。","慕沙尔")
	await novel_interface.show_dialog("我明白，那是圣城被核爆摧毁后，一些被愤怒冲昏头脑的人在做出的愚蠢的暴行。","慕沙尔")
	await novel_interface.show_dialog("人们大概不知道的是，其实我的女儿活了下来，但精神受到了很大的打击。","慕沙尔")
	await novel_interface.show_dialog("我带她回到贝卡谷地我父母家里疗养，那是我长大的地方，也是我的故乡……","慕沙尔")
	await novel_interface.show_dialog("但没过多久，国防军就驱赶着大批难民来到这里并封锁整个山谷。","慕沙尔")
	await novel_interface.show_dialog("他们将几个语言不通民族的难民圈在一起，但提供的食物仅够不到一半的人活命。","慕沙尔")
	await novel_interface.show_dialog("而“不小心”流入难民营的武器，却足够让他们自相残杀……直到血流成河。","慕沙尔")
	await novel_interface.show_dialog("这一次，我失去了一切……","慕沙尔")
	await novel_interface.show_dialog("马萨达媒体却颠倒黑白，捏造宣传恐怖分子屠杀平民的新闻，使国防军以维护区域稳定的名义介入。","慕沙尔")
	await novel_interface.show_dialog("他们兵不血刃的接管了我的故乡，大肆洗劫后只留下了一片废墟。","慕沙尔")
	await novel_interface.show_dialog("那片废墟，就是我建立抵抗军的地方。","慕沙尔")
	await novel_interface.show_dialog("虽然不停有人出面揭露真相，但马萨达的行为获得了自己国民的空前支持。","慕沙尔")
	await novel_interface.show_dialog("就像每个在历史中反复上演的故事一样，但我决定写下一个不同的结局。","慕沙尔")
	await novel_interface.show_dialog("在抵抗军里，年轻人习惯称我为“老师”，就像以前在大学里一样。","慕沙尔")
	await novel_interface.show_dialog("学生们总是问我，要如何摧毁，一个不可战胜的敌人？","慕沙尔")
	await novel_interface.show_dialog("利用上层的腐败和虚伪？\n借助民众的偏见和仇恨？","慕沙尔")
	await novel_interface.show_dialog("我说都不是……","慕沙尔")
	await novel_interface.show_dialog("能毁灭他们的，只有那些让他们骄傲到近乎疯狂的东西。","慕沙尔")
	await novel_interface.show_dialog("当人们热泪盈眶的沉浸在自己和身边之人的口号中时，毁灭的力量就会在暗流里酝酿。","慕沙尔")
	await novel_interface.show_dialog("民众会在心中筑起一堵围墙，包裹住那些他们认为不容置疑的信仰。","慕沙尔")
	await novel_interface.show_dialog("任何触碰它的人都会被无视、攻击和嘲笑，即使是他们中最智慧和富有远见的人所发出的警告。","慕沙尔")
	await novel_interface.show_dialog("就像马萨达修造的……所谓无法攻破的第三圣殿，终有一天会成为他们无法逃脱的坟墓……","慕沙尔")
	await novel_interface.show_text_only("沉默了很久，慕沙尔发出一声长叹，声音也变得微弱。")
	await novel_interface.show_dialog("唉……就到这里吧。","慕沙尔")
	await novel_interface.show_dialog("娜莎，爸爸很快就会和你团聚……","慕沙尔")
	await novel_interface.show_text_only("播放结束。")
	await novel_interface.stop_music()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("SID指挥室内，莉琉也刚刚听完这份录音。")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("不可能就这么结束，一定还差最关键的一步。","莉琉")
	await novel_interface.show_dialog("最后那块拼图，只有他自己才知道吗……","莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("可恶，他隐藏的…究竟是什么……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("忽然，大屏幕的左上角弹出红色的警报模块，同时发出急促的“滴滴滴滴”的报警音。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("那是什么警报？","莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_dizzy",0.25)
	await novel_interface.show_dialog("……诶？\n是『哨兵系统』？！","爱衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是小行星？","莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣迅速调出系统界面，看到了让她惊讶的数据。")
	novel_interface.show_character("liliu_uniform1","serious")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","blush_dizzy",0.25)
	await novel_interface.show_dialog("不……是0812项目的卫星！","爱衣")
	novel_interface.character_light(0.35,"angry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("什么？！","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"blush")
	await novel_interface.show_dialog("而且这个速度，也太快了……","爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("会展中心，安全屋内。")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_SafeHouse.png")
	novel_interface.show_character("hamon","speak")
	await novel_interface.show_dialog("可恶！！","哈蒙")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("——可恶可恶可恶！！！","哈蒙")
	await novel_interface.show_dialog("这个混蛋！！！","哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("哈蒙气急败坏的踹翻墙角一把椅子。")
	await novel_interface.show_text_only("他忽然明白为什么慕沙尔提出停火协议时，联络对象是他的军情局而不是摩诺拉。")
	await novel_interface.show_text_only("因为自己就是当年处理贝卡谷地难民问题的总指挥官。")
	await novel_interface.show_text_only("但慕沙尔整篇遗言里，并没有提及具体的攻击计划或为某次袭击负责。")
	await novel_interface.show_text_only("难道只是想用意识形态的宣讲激起其他西亚民族对马萨达的敌意吗……？")
	novel_interface.show_character("hamon","speak")
	await novel_interface.show_dialog("去，马上叫人准备我的军装！","哈蒙")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("然后你立刻准备发布会，让发言人说这是外国间谍机构联合恐怖分子对马萨达发起的袭击。","哈蒙")
	await novel_interface.show_dialog("国防军粉碎了对方的阴谋，并且成功收缴了数十万份恐怖分子的情报。","哈蒙")
	await novel_interface.show_dialog("我们必能凭此一举歼灭抵抗军，为西亚带来真正的和平……","哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("军情局少校一边记录一边频频点头。")
	await novel_interface.show_text_only("一旁的艾米莉欧后脑勺枕在椅背上，闭着眼睛，嘴角却微微上扬，不屑的发出“嘁”的一声。")
	await novel_interface.show_text_only("哈蒙白了她一眼，并没有发作，继续和少校交代发布会的要点。")
	await novel_interface.show_dialog("明白，那您说的“外国间谍机构”是指……","少校")
	await novel_interface.show_text_only("哈蒙并未作答，而是打量了一下艾米莉欧，然后走到她面前，从她肩膀上取下了步话机。")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.show_character("hamon","serious")
	await novel_interface.show_dialog("你们这些年轻人就是太自以为是了。","哈蒙")
	await novel_interface.show_dialog("以前在军队里像你这年纪就能晋升少尉的，多半是因为上级全在战场上死光了。","哈蒙")
	await novel_interface.show_dialog("……并且下一个要去送死的就是你。","哈蒙")
	await novel_interface.show_dialog("你的外国朋友不可能跑出会展中心外围的摩诺拉控制区，也就是说她一直躲在附近什么地方。","哈蒙")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("那就看看她是不是也像你一样意气用事吧……","哈蒙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("哈蒙左手按下步话机的通话键，右手掏出旁边宪兵腰间的手枪。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("装甲运兵车内。")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_APC_Wall.png")
	await novel_interface.show_text_only("我从刚才开始就在胡乱的切换着频道，想找到关于刚才那场袭击任何更多一点的信息。")
	await novel_interface.show_text_only("忽然，我手边的步话机发出了声音。")
	await novel_interface.show_dialog("“我是马萨达国防军陆军少将哈蒙，限你在五分钟内向国防军自首。”","步话机")
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("（……哈？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("随后步话机传出某种猛烈击打的声音，一个熟悉女声发出的惨叫声让我瞬间紧张起来。")
	novel_interface.show_character("ren_medical","solemn")
	await novel_interface.show_dialog("（艾米——！？？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("“否则，我会对叛国的艾米莉欧·史维特莱德少尉亲手执行死刑，现在开始计时——”","步话机")
	await novel_interface.show_text_only("步话机内传出手枪上膛的声音，这家伙要干什么？\n！")
	await novel_interface.show_text_only("我刚想按下步话机的通话键，耳机里就传来莉琉斩钉截铁的命令。")
	await novel_interface.show_dialog("不要回复！！","莉琉")

	print("=== 星尘陨落篇第19话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
