# stardustdescends_ep03.gd - 星尘降临篇第3话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep03_script()

func play_script():
	pass

func stardustdescends_ep03_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_NoxRoom.png")
	await novel_interface.show_text_only("我坐在学姐豪华大床的一角，听着她的讲述。")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("监视我的人每半年会更换一批，这次的两个人刚刚调来不到三个月。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("一会你就跟门口的人说，要亲自送小怜回家，车我已经安排好了。", "莉琉")
	await novel_interface.show_dialog("只要那两个保镖一上车，就会立刻被麻醉。", "莉琉")
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("可监视人员要定期汇报，想不引起怀疑的话，还需要他俩的配合吧？", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("学姐显然对这个临时制定的逃脱计划有些担心。")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("虽然派来监视我的只是外围成员，但“对外安全委员会”的人都受过严格的抗审讯训练。", "倪克斯")
	novel_interface.change_expression("sad")
	await novel_interface.show_dialog("恐怕他们不会轻易合作吧……", "倪克斯")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("是那个“对外安全委员会”？", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Commandments.png")
	await novel_interface.show_text_only("那个组织又称『七诫』，是莱博娜的情报机构，最早由欧洲黑手党内部的整肃部门发展而来。")
	await novel_interface.show_text_only("他们以匪夷所思的暗杀能力和对黑色西装的执着闻名于世，任何被盯上的人都很难逃脱。")
	await novel_interface.show_text_only("最具传奇色彩的是，那是一个以维护《莱博娜诫\n条》为宗旨的独立组织。")
	await novel_interface.show_text_only("通过遍布全球的数百家赌场的固定股份获取运作资金，不听命于任何政府……")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_NoxRoom.png")
	novel_interface.show_character("ren_full","happy")
	await novel_interface.show_dialog("（简直……太硬核了！！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("而且相关的几款游戏我都打到了白金。")
	novel_interface.show_character("ren_full","gratified")
	await novel_interface.show_dialog("所以想安全脱离的话，问题不在于如何出逃，而是如何保密不引起七诫的警觉吧？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("呵呵呵，放心好了。", "莉琉")
	await novel_interface.show_text_only("莉琉得意的笑道——")
	await novel_interface.show_dialog("战研部对付他们的方法多得是~", "莉琉")
	await novel_interface.show_text_only("我脑海中浮现出爱衣一脸兴奋地拿着审讯道具的样子，不禁打了个冷颤。")
	await novel_interface.show_dialog("你们俩先准备一下，随时可以行动。", "莉琉")
	await novel_interface.show_text_only("说罢，莉琉便断开了通信。")
	await novel_interface.show_text_only("忽然安静下来的氛围让我有些尴尬，而学姐却还不依不饶的盯着我的胸部。")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("音质……不错呢。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我有点不好意思的低下了头。")
	novel_interface.show_character("ren_full","shy")
	await novel_interface.show_dialog("还、还行吧……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我们在聊什么啊？？")
	await novel_interface.show_text_only("上次爱衣说做了个升级，似乎音质确实变好了…？")
	novel_interface.show_character("ren_full","shy_right")
	await novel_interface.show_dialog("（不对，干嘛要升级那种没用的东西啊？！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯忽然凑近我身边，右手也顺势伸到了我背\n后。")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("学、学姐……？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她的手在我后背上隔着衣服轻轻拉了一下，我顿时感到一阵松脱。")
	novel_interface.show_character("ren_full","awkward")
	await novel_interface.show_dialog("——！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不会是把那个扣子给……")
	await novel_interface.show_text_only("接着，学姐左手伸进我礼服的前襟，缓缓的抽出了黑色胸垫……")
	novel_interface.show_character("ren_full","awkward")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.show_dialog("…………", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……………………")
	await novel_interface.show_text_only("啊啊啊啊啊啊啊啊啊啊啊啊啊啊——！！！！")
	await novel_interface.show_text_only("她把玩着胸垫捏来捏去，发现没有扬声器后，又狐疑的望向一旁早已凌乱的我。")
	await novel_interface.show_text_only("我的脸已经红到了脖子根，一把夺过胸垫后冲进洗手间。")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("嗯？小怜肚子不舒服吗？", "倪克斯")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("如果需要“那个”的话，壁橱里就有哦~", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("学姐在洗手间外用关切的声音说道。")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("不、不是啦——！！", "小怜")
	await novel_interface.show_dialog("（呜呜呜呜呜~~）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("与此同时，SID作战指挥室。")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("爱衣坐在指挥台上翻阅着一摞纸质文件，她面前的大屏幕里跳动着四五个分析窗口。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("呐……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣仰过头来看向身后穿着笔挺军装的女性。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("要从那个土包子身上窃取文件的话，应该有无数种方法吧……", "爱衣")
	await novel_interface.show_dialog("但你却偏偏派小怜去冒这种不必要的风险，她和安妮不会起疑心吗？", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉看着手持设备上的数据笑了笑。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("那家伙应该还处在进入学姐闺房的兴奋中吧~", "莉琉")
	await novel_interface.show_dialog("而且……这本来是安妮的主意。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("咦？", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("你还记得吧——", "莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Earthperspective.png")
	await novel_interface.show_dialog("十几天前，小怜从异空间带回索娅的时候，在全球范围内引起了5秒左右的巨幅时空相位波动。", "莉琉")
	await novel_interface.show_dialog("虽然信号剧烈，但因为很快就消失了，各国都没能探测出信号源。", "莉琉")
	await novel_interface.show_dialog("似乎目前最被接受的解释是，当时太阳系正好扫过银河中一束伽玛射线暴的边缘。", "莉琉")
	await novel_interface.show_dialog("虽然是胡扯，但在某种意义上，人类确实又一次与世界末日擦肩而过了呢~", "莉琉")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("但只要世界还没毁灭，我们就要避免有人怀疑到新丰洲头上。", "莉琉")
	await novel_interface.show_dialog("从那次事件之后，SID一直在执行最高级别的舆论与情报监控。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("虽然信息部那边一无所获，但安妮在爬取社交网络内容的时候却发现了有趣的东西。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("安妮都会做这种分析了？教官说她在体能训练的时候也特别努力呢~", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("那孩子也有自己的理由吧……", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("倒是小怜，一直都悠闲过头了。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉调出一长串小怜最近通关的游戏列表，像发现了自己的小孩是笨蛋的家长般无奈的摇了摇头。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("总之，安妮发现小怜把索娅带回来的那天，有几十个人在网上描述了自己下午睡觉时的奇怪的梦境。", "莉琉")
	await novel_interface.show_dialog("“在梦中坠入一个黑暗空间，之后在模糊环境中见到了去世的亲人。”", "莉琉")
	await novel_interface.show_dialog("发布信息的都是没什么关注者的普通人，所以很快就被信息流淹没了", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("下午睡觉时的梦……", "爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("等等，那次剧烈的波动是在新丰洲时间下午四点左右出现的！", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("下午那个时间在睡觉的人本来就不多，会把自己的梦发到网上的家伙更是少之又少。", "莉琉")
	await novel_interface.show_dialog("进一步分析发现，那些账号的物理地址全都位于新丰洲，且分布在一个半径不到五公里的区域内。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到这里，爱衣的两眼放光。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("——而那个区域的中心就是倪克斯的庄园。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("难道是这座庄园里的某种存在，在天堂之门打开的瞬间被激发，从而引发了大规模的梦境？", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣的声音中传递出难以压抑的兴奋。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("本来我也不确定，所以让安妮在庄园的监控上安装了玻尔兹曼探测器……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣满脸写着“给我看”的表情向莉琉扑过去，被莉琉一把糊在脸上。")
	await novel_interface.show_text_only("身形娇小的银发少女两只手完全够不到莉琉，却不依不饶的在空中胡乱挥舞着。")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("咕（给）~呜（我）~罐（看）~rua（啦）~~~", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("等设备回收之后会给你的啦，现在快点给我做完施教授那份情报的分析！", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("把爱衣按回去之后，莉琉走出指挥室，一言不发的盯着手持设备上卫星传来的数据。")
	await novel_interface.show_dialog("（刚才小怜和倪克斯额头接触的一瞬间，爆发出了强度极高的低频电波。）", "莉琉")
	await novel_interface.show_dialog("（电波类型与人类快速眼动睡眠时的脑电波在模式上高度匹配）", "莉琉")
	novel_interface.show_background("res://assets/images/bg/Baizhu/snowfield.png")
	await novel_interface.show_text_only("简直，就像是南极那次……")

	print("=== 星尘降临篇第3话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
