# stardustdescends_ep02.gd - 星尘降临篇第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep02_script()

func play_script():
	pass

func stardustdescends_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_VillaHall.png")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("两、两百万！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我脑内顿时闪过一大堆“庶民少女在贵族学校打破古董花瓶”之类不妙的桥段。")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("（不、不会要我一辈子打工还债吧！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我偷偷计算着要赔那把椅子需要在女仆咖啡厅打工多久时，倪克斯学姐突然挑起了我的下巴。")
	novel_interface.show_character("ren_full","sob")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","normal1",0.25)
	await novel_interface.show_dialog("平日看你在学校里呆头呆脑的……", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她侧过脸，发现我的耳环是夹在耳朵上的种类后，露出了一个玩味的笑容。")
	novel_interface.show_character("ren_full","sob")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("好好化一下妆，居然这么可爱~", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("你、你要做什么！？")
	await novel_interface.show_text_only("这时，两个身着黑色西服、身材魁梧的保镖从学姐身后的角落向我走来。")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("（完了完了……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我万念俱灰，还以为刚才自己那套行云流水的操作很帅气呢，这不是完全暴露了吗！")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("刚才没吓到你吧——", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("学姐突然话锋一转，不动声色将那只从我耳中扯出的耳机藏进手心。")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("欸？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她故作关切的摸着我的脑门，头也不回对身后的保镖冷冷得说道。")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","sad",0.25)
	await novel_interface.show_dialog("这是我在御樱川的学妹，只是碰巧遇到了。", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("其中一人拿出手机对着我的脸扫了一下，看到屏幕上的结果后点点头。")
	await novel_interface.show_text_only("另一人似乎还有所疑虑，走到摔倒在地的施教授身旁，似乎打算检查那把椅子。")
	await novel_interface.show_text_only("倪克斯见状忽然勾住我的后颈，将我们的额头贴在一起作出要检查体温的样子——")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","mock",0.25)
	await novel_interface.show_dialog("机灵点。", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("学姐命令的口吻中透出一丝紧迫，随之呼出的气息直吹在我的脸上。")
	novel_interface.show_character("ren_full","awkward")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","mock",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（脸……贴的太近啦！）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我僵在原地，不知该如何回应，脑子里冒出一连串的疑问")
	await novel_interface.show_text_only("学姐为什么会在这里？是作为赌场的宾客还是来交易情报？目标和她有关系吗？")
	await novel_interface.show_text_only("她知道这把椅子的历史和价格，似乎很熟悉这里，难道她是这座庄园的主人？")
	await novel_interface.show_text_only("但这两个保镖模样的人是怎么回事？\n还有这诡异的气氛……")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_text_only("我盯着学姐的眼睛，心跳越来越快，感觉好像要被那双淡红色的眼睛吸进去一样。")
	novel_interface.change_expression("sad")
	await novel_interface.show_text_only("她先是用余光观察着保镖的动向，忽然看向我，四目相对，我下意识的将目光下移——")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("等等，从这个角度往下看的话……")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("原来学姐晚礼服的胸部是这样设计的啊……")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_text_only("盯着那若隐若现的蕾丝封边，我心脏一阵狂跳，只觉得似乎有一股热流被猛然泵入我的大脑。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("先是涨的耳根发烫，然后便是一阵眩晕……")
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("小怜……？", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("你怎么了？", "倪克斯")
	await novel_interface.show_dialog("还愣着干嘛？快帮忙！", "倪克斯")
	await novel_interface.show_dialog("先把她扶到我房里吧……", "倪克斯")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………")
	novel_interface.change_music("res://assets/audio/music/Noise.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Spot.png")
	await novel_interface.show_text_only("——")
	await novel_interface.show_text_only("呐~")
	await novel_interface.show_text_only("你还记得吗？")
	await novel_interface.show_text_only("谁？")
	await novel_interface.show_text_only("无尽的黑暗中突然出现一个金色光点，周围散发着七彩光辉。")
	await novel_interface.show_text_only("你问我记得……什么？")
	await novel_interface.show_text_only("我在等你……")
	await novel_interface.show_text_only("在约定的地方。")
	await novel_interface.show_text_only("约定的……")
	await novel_interface.show_text_only("地方？")
	await novel_interface.show_text_only("等等，你是——")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("——！！")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("喂！")
	await novel_interface.show_text_only("喂——！！")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_NoxRoom.png")
	await novel_interface.show_dialog("喂，你还真睡啊……口水都流出来了。", "倪克斯")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("哈……？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我迷迷糊糊的睁开眼，发现自己正躺在一张宽大柔软的床上。")
	await novel_interface.show_text_only("紫色的床架，全套黑色真丝质地的床具泛着昂贵的光泽。")
	await novel_interface.show_text_only("学姐坐在床边，正用看小动物的眼神居高临下得盯着我。")
	await novel_interface.show_text_only("我才发现枕头被口水浸湿了一块，更要命的是，我两条腿正大咧咧的岔开，裙子都快翻到腰上了。")
	await novel_interface.show_text_only("啊，原来我在学姐的床上睡着了啊……")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("（等等，学姐……床！？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我刚才不是在那个别墅里吗？！还有那两个身材魁梧的保镖")
	await novel_interface.show_text_only("我赶忙并拢双腿扯下裙子，抱着自己的膝盖躲到床头另一侧，警觉地盯着倪克斯。")
	await novel_interface.show_text_only("房间内没有其他人，一侧的整面墙壁都挂着厚重的紫色窗帘，一丝光线也无法透入。")
	await novel_interface.show_text_only("灯饰、墙纸和家具与刚才庄园里那种有些复古的风格完全不同，地上还铺着厚实的灰色地毯。")
	novel_interface.show_character("ren_full","shy")
	await novel_interface.show_dialog("（我刚才晕倒了？到底过了多久啊！）", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("这是哪？你你你把我怎么了！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("学姐看到我颤抖的样子笑了笑，站起身来。")
	novel_interface.show_character("nyx_full","mock")
	await novel_interface.show_dialog("哦？", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她将一只膝盖压到床上，作势要向我爬来。")
	novel_interface.show_character("nyx_full","mock")
	await novel_interface.show_dialog("你觉得……我刚才把你怎样了呢？", "倪克斯")
	await novel_interface.show_dialog("小怜同学——", "倪克斯")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","perspire1")
	await novel_interface.show_dialog("刚、刚刚才？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我脸涨得通红，抓起被子缩在床头，她、她她刚才对我做什么了啊！")
	await novel_interface.show_dialog("唉，你就别逗她了~", "莉琉")
	await novel_interface.show_text_only("胸部忽然传出的声音，把学姐和我都吓了一跳。")
	await novel_interface.show_dialog("那么，就像刚才咱们谈好的——", "莉琉")
	await novel_interface.show_dialog("你们准备好之后随时可以行动。", "莉琉")
	await novel_interface.show_text_only("倪克斯没有再继续逼近，只是坐在床上好奇的盯着我的胸部微微点了点头。")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("（行动？）", "小怜")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("等一下，你们谈好什么了？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("为什么我感觉自己又被卖了！")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("还以为你刚才是装作晕倒，没想到真睡着了……", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("学姐的姿态稍稍放松了下来，我也有些迟疑的放下了被角。")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("没想到小怜这样的孩子，居然也能加入SID啊~", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("不小心加入了奇怪的组织，真是抱歉。")
	novel_interface.show_character("ren_full","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("等等，我刚才晕倒了？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我猛然回想起记忆中最后的场景，难道是因为看到了——")
	novel_interface.show_character("ren_full","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（不、不至于这么丢人吧？）", "小怜")
	await novel_interface.show_dialog("（平时我自己洗澡的时候也没少看啊……）", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("放心吧，这是我的房间，咱们还在庄园里。", "倪克斯")
	await novel_interface.show_dialog("你睡了差不多一个小时了。", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我刚想叫出来，却被学姐捂住了嘴。")
	novel_interface.show_character("ren_full","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","sad",0.25)
	await novel_interface.show_dialog("嘘——说话别太大声，虽然这房间隔音不错，但那两个人还守在门口呢。", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我赶紧把后面的话吞了回去，乖巧的点点头。")
	novel_interface.show_character("ren_full","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("刚才怎么摇都摇不醒，要不是莉琉说你的身体指数正常，我差点要叫救护车了。", "倪克斯")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你……和莉琉认识？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("刚刚认识——", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("倪克斯微笑着从耳中掏出了那只骨传导耳机。")
	await novel_interface.show_dialog("你都告诉她吧，也省得我再做说明。", "莉琉")
	await novel_interface.show_text_only("学姐似乎有些犹豫，然后好像下定决心一般，抬起头看着我的眼睛。")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("我很小的时候母亲就去世了，我对她几乎没有什么印象，是父亲一直照顾我。", "倪克斯")
	await novel_interface.show_dialog("我的父亲，克里斯托弗·斯特罗齐曾是第六学园都市的……不，那时还只是叫做莱博娜群岛——", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("学姐稍稍停顿，思索了一下措辞。")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("就是类似元老院首席执政那样的角色。", "倪克斯")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","happy")
	await novel_interface.show_dialog("欸——？", "小怜")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("那、那不是很厉害嘛！", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_LiberNa.png")
	await novel_interface.show_text_only("第六学园都市——莱博娜群岛。")
	await novel_interface.show_text_only("十五年前的一次异质物爆发，导致安达曼海东侧的陆地在几十天内分裂成上千个大小不一的小岛。")
	await novel_interface.show_text_only("异变还未停止，周围的国家就已经为那些岛的所属权吵得不可开交。")
	await novel_interface.show_text_only("虽然各国海军时有摩擦，但在那个敏感时期，无论哪只政府军强行占岛都无异于同时向多国宣战。")
	await novel_interface.show_text_only("结果谁也无法控制这片区域——这片位于国际贸易航线必经之路上的群岛，一时竟成为无主之地。")
	await novel_interface.show_text_only("由于未被划分的陆地不适用引渡法，最先被吸引来的是各国被通缉的罪犯和逃兵。")
	await novel_interface.show_text_only("将这里命名为莱博娜（LiberNa），也是因其自由之国（LiberNation）的理念深入人心。")
	await novel_interface.show_text_only("后来，那些没有政府背景的黑帮和暴力团体也纷纷来到这里，想从繁荣的海上贸易中分一杯羹。")
	await novel_interface.show_text_only("时至今日，莱博娜的坐馆都是由几大黑帮轮流选举产生的。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_NoxRoom.png")
	await novel_interface.show_text_only("也就是说……")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("（学姐的父亲是教父之类的角色吗？！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("父亲为混乱的莱博娜群岛建立了规则与秩序，让一个连淡水都找不到的小岛发展成繁华的都市。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("学姐的语气坚定，声音却有些颤抖，她盯着墙纸上的金色花纹，像是在回忆着什么。")
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("然而在战争期间，他却被卷入一场事故失踪了。", "倪克斯")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("学姐说这出句话时语气异常平静，但我对这种状况再熟悉不过了。")
	await novel_interface.show_text_only("虽然战争期间的所谓“失踪”，几乎百分之百的情况都是死亡——")
	await novel_interface.show_text_only("但那些坚信自己亲人还活着的人，会一遍遍的用坚定而平静的语气告诉自己。")
	await novel_interface.show_text_only("他们没死，他们只是失踪了……")
	await novel_interface.show_text_only("即使所有档案上都会标明冷冰冰的“推测死亡”。")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("后来的故事就很老套了——", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("学姐并没有过多停顿，接着说道。")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("其他几个黑帮趁着权力真空，迅速夺取属于我家族的财产和权力。", "倪克斯")
	await novel_interface.show_dialog("即使父亲不在，依然有很多人愿意对斯特罗齐家族效忠。", "倪克斯")
	novel_interface.change_expression("sad")
	await novel_interface.show_dialog("可在当时，那些人的忠诚只会让我处境更危险。", "倪克斯")
	await novel_interface.show_dialog("为了表明自己无意继续参与家族事业，我离开了莱博娜群岛，到新丰洲上学。", "倪克斯")
	await novel_interface.show_dialog("但很显然，他们依然不放心——", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯说着看向大门，原来那两个保镖模样的人是负责监视学姐的。")
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("我只被允许在学校附近很小的区域内自由行动，去其他地方都会被人监视。", "倪克斯")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("三年前，我靠父亲当年的人脉，逐渐恢复了斯特罗齐家在欧洲和西亚的地下交易网。", "倪克斯")
	await novel_interface.show_dialog("于是我联系了现任莱博娜坐馆洪先生，并和他提出一个交易——", "倪克斯")
	await novel_interface.show_dialog("我用地下交易网帮他拓展欧洲业务，他则允许我住在这座庄园——当然，是在洪先生的监控下", "倪克斯")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("即使这里本来就是父亲的……", "倪克斯")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("等等等等，我有点晕。", "小怜")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("就是说，这座庄园是当年你父亲买下来的，现在则是由第六学园都市官方所有？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("就当是莱博娜与元老院的某种“默契”吧……", "莉琉")
	await novel_interface.show_dialog("这个世界刚从战争中恢复，充斥着各种政府很想参与，却又不适合公开介入的交易。", "莉琉")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("就是所谓的地下黑市？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("有需求就有市场，有市场就有钱赚嘛。", "莉琉")
	await novel_interface.show_text_only("难怪你舍不得查抄这里！")
	await novel_interface.show_text_only("我环视四周，这间房里各种陈设虽都是顶级货，却严重缺乏烟火气，就好像从没入住过的客房。")
	await novel_interface.show_text_only("常年被人监视和窥探，可能就是这种感觉吧……")
	novel_interface.show_character("nyx_full","smile")
	await novel_interface.show_dialog("我查了一下，你们今天想窃取情报的那个人，是华云宫一所大学的历史学教授施玉折。", "倪克斯")
	await novel_interface.show_dialog("可能是察觉到什么，他联系的买家已经爽约，十几分钟前他也悻悻的离开。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那家伙离开庄园后在第一个路口就被我回收了，现在还在麻醉中。", "莉琉")
	novel_interface.show_character("ren_full","stare")
	await novel_interface.show_dialog("早知道这样就不用偷了……", "小怜")
	await novel_interface.show_dialog("（害得我去上好几个小时的仪态课，还被那些姐姐们各种嘲笑，昨晚做梦的时候都在挺胸……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("虽然还在分析中，但如果施教授的情报正确，我们正好用得上斯特罗齐家在欧洲和西亚的资源。", "莉琉")
	await novel_interface.show_text_only("所以你就趁我睡着的时候，跟学姐谈了个生意？")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("还有两点我不明白——", "小怜")
	await novel_interface.show_dialog("如果他们这么信不过你，那为什么……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("为什么不杀了我？", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("倪克斯表情轻松的补全了我的问题。")
	novel_interface.show_character("ren_full","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("根据父亲定制的《莱博娜诫条》，任何签署组织的成员都不得伤害其他组织的首领和家人。", "倪克斯")
	await novel_interface.show_dialog("所以他们最多将我软禁起来，还要共同出一大笔钱来保障我的生活。", "倪克斯")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这么守规矩的吗！？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("福利简直比公务员还好！")
	await novel_interface.show_dialog("这是相当高明的设计——既然暴力团体之间的争斗无法避免，那至少设置一个底线。", "莉琉")
	await novel_interface.show_dialog("底线一旦确立，就没人想破坏规矩，因为这也是他们自己的最终保险和免死金牌。", "莉琉")
	novel_interface.show_character("ren_full","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("可能因为小怜对莱博娜群岛有些误会吧~", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("大概就是由几个黑帮共同管理，四处都是黑市、赌场和那种场所的国家吧……")
	novel_interface.show_character("ren_full","uneasy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（感觉全国都18岁以下禁止入内的样子……）", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("其实莱博娜群岛的犯罪率在六个学园都市中是最低的哦~", "倪克斯")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("黑帮存在的前提是法制环境——", "倪克斯")
	await novel_interface.show_dialog("在没有法律和律师保护的地方，政府能在毫无证据的情况下轻松消灭任何自己不爽的个人和组织。", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("所以当这些黑帮成员成为国家的主人后，依然会强调严刑峻法。", "莉琉")
	await novel_interface.show_dialog("也多亏了这种理念，才造就了莱博娜今天的繁荣。", "莉琉")
	await novel_interface.show_dialog("立宪、法制、多党轮换、周期选举、保持底线……", "莉琉")
	await novel_interface.show_dialog("很多国家的政治体制改革都不成功，没想到一群法外之徒却自发的做到了，真是讽刺。", "莉琉")
	await novel_interface.show_text_only("听着莉琉的解说，我似懂非懂的点了点头。")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("还有最后一个问题……", "小怜")
	await novel_interface.show_dialog("与SID合作，学姐想要的是？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯认真的看着我，郑重的说道——")
	novel_interface.show_character("nyx_full","normal1")
	await novel_interface.show_dialog("自由。", "倪克斯")

	print("=== 星尘降临篇第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
