# stardustdescends_ep20.gd - 星尘降落篇第20话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep20_script()

func play_script():
	pass

func stardustdescends_ep20_script():
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Religion.png")
	await novel_interface.show_text_only("很多人都有信仰，并将其作为在动荡世界中建立自身秩序的锚点。")
	await novel_interface.show_text_only("信仰还能帮人获得内心所渴求的东西：比如目标、勇气、救赎、归属感……不一而足。")
	await novel_interface.show_text_only("信仰的形式也多种多样——可以是宗教、政治、主义，甚至个人。")
	await novel_interface.show_text_only("很多人都争论过，信仰的本质是什么？")
	await novel_interface.show_text_only("哲学家认为，信仰就是将某个不可证的命题强行设定为真理，并深信不疑的捍卫它。")
	await novel_interface.show_text_only("这样在面对那些“终极问题”时，你就可以跳过证明过程直接填上答案，甚至能逆推出应有的题设。")
	await novel_interface.show_text_only("逻辑自洽的系统性解释，确实是填补人类内心空洞的一剂良药。")
	await novel_interface.show_text_only("但神经生物学的研究逐渐表明，人的大脑在面对问题时，本来就会试图直接填上一个答案。")
	await novel_interface.show_text_only("而真正的理性思考，是在验算和否定那些答案的过程中发生。")
	await novel_interface.show_text_only("当理性的火炬逐渐暗淡，人就会本能的为自己制造信仰……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("正如那句名言：信仰始于思考停止的地方。")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_APC_Wall.png")
	await novel_interface.show_dialog("——不要回复！！","莉琉")
	await novel_interface.show_text_only("莉琉厉声重复着刚才的命令。")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("可、可是……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你听好，哈蒙这次栽大了——","莉琉")
	await novel_interface.show_dialog("所有人都会认为是他的残暴和愚蠢招致了这次自杀性报复。","莉琉")
	await novel_interface.show_dialog("而且慕沙尔的遗言，会让马萨达的政府、军队甚至宗教公会都成为被国际社会指责的目标。","莉琉")
	await novel_interface.show_dialog("如果哈蒙还想参选……不，那怕只是为了自己不死于非命，也必须把矛盾转移出去。","莉琉")
	await novel_interface.show_dialog("而将国内冲突变成国际争端正是他最好的选择。","莉琉")
	await novel_interface.show_dialog("现在只要他拿出证据，马萨达全国上下无论是否真的支持哈蒙的人，都只能选择支持他。","莉琉")
	await novel_interface.show_dialog("所以你现在自首不仅是送死，还会坐实艾米莉欧的叛国罪，她的亲人也会受到牵连。","莉琉")
	await novel_interface.show_dialog("哈蒙会组织一场声势浩大的全国公审，当庭宣判你们的死刑判决，并立刻执行。","莉琉")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉对局势的分析让我哑口无言。")
	await novel_interface.show_dialog("放弃吧……","莉琉")
	await novel_interface.show_dialog("这场谈判，我们没有任何筹码。","莉琉")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("步话机的通话灯再次亮起。")
	await novel_interface.show_dialog("还剩4分钟。","步话机")
	await novel_interface.show_text_only("哈蒙的声音中没有一丝的情绪波动。")
	await novel_interface.show_text_only("那平静到冷彻骨髓的语调，让我确信他会在倒计时结束后毫不犹豫的扣下扳机……")
	novel_interface.show_character("ren_medical","serious")
	await novel_interface.show_dialog("（怎么办……）\n（怎么办啊！！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("给我好好……想一想啊！！！")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("另一方面，SID指挥室。")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("爱衣在大屏幕上迅速调出卫星的一系列数据，全然不顾脸颊上还未消退的印痕。")
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("那颗卫星质量约30吨，现已越过地球同步轨道。","爱衣")
	novel_interface.change_expression("blush_dizzy")
	await novel_interface.show_dialog("预计于10分钟后进入大气层，届时速度将达到…\n…80马赫！！","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("能拦截吗？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣摊了摊手。")
	novel_interface.show_character("ai","blush_think")
	await novel_interface.show_dialog("卫星一直在做姿态微调，连轨道都无法确定，这个速度下已经没有任何能拦截它的东西了……","爱衣")
	await novel_interface.show_dialog("隔热罩应该会让它在坠落中损失很多速度，但撞击的能量依然十分可观……","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("现在的速度已经超过了旅行者1号了吧！\n怎么可能……","秋子")
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("是有可能的——","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣调出了太阳系空间模型，画面中一条红色的椭圆曲线贯穿了第三和第四行星的轨道。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("如果利用地球和火星之间的霍曼转移轨道的话……","爱衣")
	await novel_interface.show_dialog("两年前确实有一段时间窗口，地球和火星都处在各自轨道中合适的位置。","爱衣")
	await novel_interface.show_dialog("如果当时处于地球轨道的卫星发动工质引擎瞬间加速，就能进入转移轨道，并在1年后抵达火星。","爱衣")
	await novel_interface.show_dialog("然后利用引力弹弓效应加速返回地球，同时开启离子推动引擎，在归途一直持续加速……","爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("只要加速120天，卫星就能达到第三宇宙速度，而从火星返回地球至少需要260天","爱衣")
	novel_interface.change_expression("dizzy")
	await novel_interface.show_dialog("将本来设计用于降回地球的工质引擎燃料消耗掉飞往火星，然后利用离子引擎做长时间加速……","爱衣")
	novel_interface.change_expression("blush_dizzy")
	await novel_interface.show_dialog("要实现这种大胆的创想，需要相当的物理学知识和精密的计算……真是厉害。","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("物理学……慕沙尔？","秋子")
	await novel_interface.show_text_only("莉琉点了点头。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("这才是最后的那块拼图，也是签约仪式为什么一定要定在今天的原因——","莉琉")
	await novel_interface.show_dialog("但在这块拼图最终拼好之前，依然看不到慕沙尔计划的全貌……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("拼好是指……？","秋子")
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("是指撞击点吧~","爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("卫星不是炸弹，造成破坏的方式类似陨石撞击，而30吨的陨石确实说不上大……","爱衣")
	await novel_interface.show_dialog("撞击点不太可能在内城区，第二代『铁穹』系统的饱和式末期拦截能完全覆盖马萨达的核心区域。","爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("那种变态的拦截方式不需考虑命中率，到时内城区上空连只虫子也活不下来。","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("其他可能被攻击的敏感区域……\n以利亚大坝？","秋子")
	await novel_interface.show_dialog("如果红海-死海大运河的水坝被击溃……","秋子")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("不会的，马萨达当初规划那条运河的时候就预想了可能遭受的各种攻击。","莉琉")
	await novel_interface.show_dialog("如果大坝坍塌，洪水会被引向死海东岸的穆吉布和卡拉克地区。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("祸水东引……\n不愧是马萨达的设计呐~","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("既然慕沙尔已死，那么要撞击的绝对是一个能确保击中的目标。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那个让慕沙尔布局数年，付出如此的大代价，却不想亲眼目睹的终局……")
	await novel_interface.show_text_only("到底是什么……")
	await novel_interface.stop_music()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("运兵车内。")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_APC_Snowflakes.png")
	await novel_interface.show_text_only("哈蒙的倒计时还剩下不到两分钟。")
	await novel_interface.show_text_only("我把步话机顶在额头，手心在不停的冒汗。")
	await novel_interface.show_text_only("想一想，好好想一想！")
	await novel_interface.show_text_only("到底有什么能救下艾米的筹码……")
	await novel_interface.show_text_only("我做了个深呼吸，慢慢的闭上双眼——")
	novel_interface.change_music("res://assets/audio/music/unkown/bgm.mp3")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("仔细想来……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_MasadaCustoms.png")
	await novel_interface.show_text_only("从第一次进入这座城市，就有种奇怪的感觉。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadaCustomsB.png")
	await novel_interface.show_text_only("似乎这里的每个地方，都是为了某个宏大的目标而设计的——")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Masada0.png")
	await novel_interface.show_text_only("无处不在的标语、哨卡和AI自动防卫武器、几十米高的隔离墙还有严格划分的城区……")
	await novel_interface.show_text_only("整个第三学园都市，仿佛一座随时处于备战状态的军事要塞。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("但长期的高压状态，必然导致一系列问题——")
	await novel_interface.show_text_only("财政赤字高涨，社会矛盾激化，甚至一些城区陷入了完全崩坏的状态……")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_MasadSways.png")
	await novel_interface.show_text_only("而抵抗军只要放弃正面战场，采用远离城市的游击战术，就能轻易的避开锋芒。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("那为什么马萨达要一直背负着如此高昂的成本呢？")
	await novel_interface.show_text_only("这座在沙漠中拔地而起的堡垒，究竟是为了抵御外面的敌人——")
	await novel_interface.show_text_only("还是在镇守内部的什么东西……？")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_APC_Snowflakes.png")
	await novel_interface.show_dialog("还剩一分钟，倒计时结束我就开枪。\n这是最后一次警告。","步话机")
	await novel_interface.show_text_only("哈蒙的声音忽然将我的思绪带回现实。")
	novel_interface.show_character("ren_medical","solemn")
	await novel_interface.show_dialog("（可恶……要没时间了！！！）","小怜 ")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我用手胡乱的抓着头发，哪怕能再抠出一丁点灵感也好……")
	await novel_interface.show_text_only("冷静，冷静下来！")
	await novel_interface.show_text_only("就像莉琉教我的那样——")
	await novel_interface.show_text_only("我紧闭双眼，呼吸加快，如走马灯般回想着这几天的经历。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("要找到诸多信息中隐含的矛盾和关联……")
	await novel_interface.show_text_only("隐含的矛盾……")
	await novel_interface.show_text_only("我记得在马萨达国家博物馆，讲解员说过——")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_SOTB.png")
	await novel_interface.show_dialog("马萨达是个历史悠久的民族，也很重视考古发掘。","讲解员")
	await novel_interface.show_dialog("从第一份古卷被发现的那天，『死海古卷』的发掘和复原工作已经持续了八十多年。","讲解员")
	novel_interface.change_background("res://assets/images/bg/Stardust/Vessel.png")
	await novel_interface.show_text_only("重视考古发掘？\n可我明明记得两天前……")
	await novel_interface.show_dialog("十几个小时前，马萨达境内希伯仑市的易卜拉清真寺附近发生了一起工业化学品爆炸事故。","莉琉")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("又是恐怖袭击？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("易卜拉清真寺下面的麦比拉洞，是传说中马萨达人先祖的墓穴。","爱衣")
	await novel_interface.show_dialog("虽然自从他们在上个世纪接管那座城市以后，就从没进行过考古发掘。","爱衣")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("等一下，博物馆讲解员似乎也提到过麦比拉洞……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_DSS.png")
	await novel_interface.show_dialog("马萨达的圣祖雅各的一生充满传奇，他曾梦见天堂之门，听见神重申对他祖父的誓约。","讲解员")
	await novel_interface.show_dialog("他曾与神摔跤而瘸腿，而被神赐予了圣名。","讲解员")
	await novel_interface.show_dialog("雅各临终前要儿子起誓，必要将他带出埃及，葬在迦南地希伯仑的麦比拉洞。","讲解员")
	await novel_interface.show_dialog("那是其祖父亚伯拉罕买下的家族墓地……","讲解员")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("而且我还在哪里听过这个名字……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_ShelterOffice.png")
	await novel_interface.show_dialog("薇拉是军人世家，她的曾祖父摩西·达杨还是马萨达家喻户晓的人物。","莉琉")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("诶？这么厉害……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("有意思的是，那人还是个业余考古学家，据说是唯一对麦比拉洞进行过考古的马萨达人——","莉琉")
	await novel_interface.show_dialog("1967年六日战争之后，马萨达获得了希伯仑的控制权。","莉琉")
	await novel_interface.show_dialog("当时任国防部长的摩西·达杨派一个身材苗条的\n12岁小女孩，从洞穴外的缝隙钻进了麦比拉洞。","莉琉")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("（怎么听起来这么乱来……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("不过那个收集狂居然什么文物都没拿出来，后来出于宗教原因就不再允许人们进去了……","莉琉")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("不再允许进入，难道是因为……？")
	await novel_interface.show_text_only("对了，好像安妮对我说过——")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Masadainner.png")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("告诉你吧，马萨达的『幻想军势』就在内城区地下的某个地方哦！","安妮")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("各国都猜想，或许『幻想军势』还存在某种尚未公布的关键特性。","安妮")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("以至于马萨达的领导人不惜将全民族的命运都押在这片土地上……","安妮")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我感到头皮一阵发麻——")
	await novel_interface.show_text_only("然而倒计时还剩不到30秒，我只能强迫自己的思绪继续飞奔。")
	await novel_interface.show_text_only("如果真的如我所想\n那他们一直守护这个秘密的理由……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_MasadaF.png")
	await novel_interface.show_text_only("能理直气壮的将两千年来一直生活在这里的原住民赶走并迅速建立起国家。")
	await novel_interface.show_text_only("他们的国父们当年依仗的理论依据是——")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SOTB.png")
	await novel_interface.show_dialog("我们的先辈便冒着枪林弹雨，只为再次回到这里建立属于我们自己的国家。","讲解员")
	await novel_interface.show_dialog("尽管这只是一片贫瘠的沙漠，尽管当时连淡水都难以供应，但这里是我们的家！","讲解员")
	await novel_interface.show_dialog("这是我们在这个世界上唯一的故乡，更是马萨达人几千年来的心灵家园。","讲解员")
	await novel_interface.show_dialog("『应许之地』是对我们先祖和神明的契约，也是我们对后世子孙的承诺！","讲解员")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("这片『应许之地』是他们先祖和神明的契约……？")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_MessOfPottage.png")
	await novel_interface.show_dialog("根据经文中的记载，以撒的次子雅各曾用一碗红豆汤买下了哥哥以扫的长子权。","讲解员")
	await novel_interface.show_dialog("根据他们的祖父亚伯拉罕与神的契约，他和他的后代就成为了『应许之地』的合法继承人。","讲解员")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("雅各的后代是『应许之地』的合法继承人……")
	await novel_interface.show_text_only("等一下，后代……")
	await novel_interface.show_text_only("——后代？！")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_AncientHumanEH.png")
	novel_interface.show_character("stardust_big","normal")
	await novel_interface.show_dialog("但如果尸体一直被密封保存的话，用萨蒙顿最新的基因分析技术倒是能检测出亲缘关系哦。","少女")
	await novel_interface.show_dialog("前两年曾用一具六千年前的木乃伊提取DNA与现代基因数据库比对，真的发现了延续至今的后代。","少女")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Spot.png")
	await novel_interface.show_text_only("———！！！")
	await novel_interface.show_text_only("那种接近真相的兴奋和紧张感让我不禁颤抖起来。")
	await novel_interface.show_text_only("这些天由不同的人传达给我信息，似乎一直在等我将它们串联起来……")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Stardust.png")
	await novel_interface.show_dialog("这样就能传达到了吧……","少女")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("——就像我们约定的那样。","少女")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_APC_Snowflakes.png")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("“冷静分析，大胆下注”吗……")
	await novel_interface.show_text_only("这次的赌注，真的有点大呢。")
	await novel_interface.show_text_only("我把和莉琉通讯用的入耳式耳机拿了出来，按下了步话机的通话键。")
	novel_interface.show_character("ren_medical","shout")
	await novel_interface.show_dialog("死蛤蟆，我劝你把身边的人都调走——","小怜")
	await novel_interface.show_dialog("我接下来要说的，你大概不会希望他们听到。","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("等待回复的那几秒，周围的一切仿佛都静止了。")
	await novel_interface.show_text_only("即使把耳机拿在手里，依然能隐约听到从中传出的莉琉的怒吼。")
	await novel_interface.show_dialog("……我让其他人都出去了。\n怎么，想在自首前先做一番自白？","哈蒙")
	await novel_interface.show_text_only("我深吸一口气，拿起步话机直奔主题。")
	novel_interface.change_music("res://assets/audio/music/unkown/Sign of brave.mp3")
	novel_interface.show_character("ren_medical","solemn")
	await novel_interface.show_dialog("埋在内城区地下的XK级空间型异质物『幻想军势\n』的真实面目是——","小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_TheThree.png")
	await novel_interface.show_dialog("马萨达人的先祖，『雅各』的墓穴。","小怜")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_APC_Snowflakes.png")
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("步话机和耳机同时陷入了沉默。")
	await novel_interface.show_text_only("等了大概十秒，我按下通话键继续说道。")
	novel_interface.show_character("ren_medical","solemn")
	await novel_interface.show_dialog("多亏了你们强制进行的“历史课程”……","小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_TheJewishWar.png")
	await novel_interface.show_dialog("博物馆的讲解员说，约瑟夫斯的书中记载，罗马帝国征服了圣城，一百多万马萨达先民被杀害。","小怜")
	await novel_interface.show_dialog("但我记得学校的历史课上明明讲过，那个时代唯一可能达到上百万人口的城市，只有罗马城吧？","小怜")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_APC_Snowflakes.png")
	novel_interface.show_character("ren_medical","solemn")
	await novel_interface.show_dialog("你们的历史还说，在公元七十年，马萨达人的先祖被罗马人大批的从犹地亚流放出去。","小怜")
	await novel_interface.show_dialog("但即使是这个世纪，艾米莉欧母亲的聚落迁徙，一万多人也会有四分之一死在路上。","小怜")
	await novel_interface.show_dialog("两千年前的马萨达人，在没有现代交通工具的情况下，根本不可能做到大规模长途迁徙。","小怜")
	await novel_interface.show_dialog("如果罗马人流放的是异教徒，那么唯一合理的解释就是：只有少数最虔诚的教士离开了那里。","小怜")
	await novel_interface.show_dialog("而绝大部分人都留在了家乡，他们为了生存，改信了其他宗教。","小怜")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("这些人的后裔，就是那些在今天的马萨达不被许进入隔离墙内的“特定民族”。","小怜")
	await novel_interface.show_dialog("那些世代都生活在这里，被你们肆意屠戮和摆布的外族人，才是『雅各』真正的血脉。","小怜")
	await novel_interface.show_dialog("若真按照你们的经文，那些人才是这片土地的合法继承者不是吗？","小怜")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("但这些都是对历史的猜想，能被你们的宣传机构轻而易举的压制——","小怜")
	await novel_interface.show_dialog("然而如果能找到雅各本人的棺椁，凭今天的DNA技术可以直接验证这个观点。","小怜")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("这就是你们倾举国之力也要守护的秘密。","小怜")
	await novel_interface.stop_music()
	await novel_interface.hide_character()
	await novel_interface.show_text_only("步话机沉默了许久，却忽然传出了莉琉的声音。")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_dialog("马萨达军用频道的加密也不过如此……","莉琉")
	await novel_interface.show_dialog("下面的话，我来替你说吧。","莉琉")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("……诶？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("一百年前，复国主义的领袖们真是一群天才……","莉琉")
	await novel_interface.show_dialog("他们用虚构的历史故事建立起意识形态，编造出了\n“回归故土”的传说。","莉琉")
	await novel_interface.show_dialog("巧妙的利用了二战后的国际形势，并靠这些手段将异教的原住民一直压制至今。","莉琉")
	await novel_interface.show_dialog("那些先人用智慧和政治手腕为自己的族人争取到了土地并建立起国家，我深感佩服。","莉琉")
	await novel_interface.show_dialog("摩西·达杨在上个世纪就发现麦比拉洞里的状况和经文中的记载不符，所以立即加以封锁。","莉琉")
	await novel_interface.show_dialog("但估计他做梦也没想到，圣城毁灭后，你们在古马萨达城遗址的地下找到了圣祖雅各真正的墓穴。","莉琉")
	await novel_interface.show_dialog("如果这个秘密被公开，马萨达建立在坚定民族信仰上的合法性和统治根基会瞬间崩塌。","莉琉")
	await novel_interface.show_dialog("但你们最想销毁的秘密，却恰恰是你们唯一能赖以达成威慑的战略武器。","莉琉")
	await novel_interface.show_dialog("真是太讽刺了……","莉琉")
	await novel_interface.show_dialog("……你是什么人？","哈蒙")
	await novel_interface.show_dialog("啊，忘了自我介绍。","莉琉")
	await novel_interface.show_dialog("我是莉琉·冯·布劳恩——","莉琉")
	await novel_interface.show_dialog("就是你要找的“外国情报机构”SID的主管。","莉琉")
	await novel_interface.show_dialog("哈蒙，够了。","老者的声音")
	await novel_interface.show_text_only("步话机中又传出一个低沉而苍老的声音。")
	await novel_interface.show_dialog("叔叔？！\n可、可是……","哈蒙")
	await novel_interface.show_dialog("你都不知道外面发生了什么吧……","老者的声音")
	await novel_interface.show_dialog("呵呵，果然您也在监听这个频道。","莉琉")
	await novel_interface.show_dialog("别来无恙吗——","莉琉")
	await novel_interface.show_dialog("施恩内曼总理。","莉琉")
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_dialog("咳咳咳咳咳咳——","施恩内曼")
	await novel_interface.show_text_only("步话机中传出老人一阵沉闷嘶哑的干咳。")
	await novel_interface.show_dialog("医生说一时半会还死不了……","施恩内曼")
	await novel_interface.show_dialog("但也可能，很快就到大限了。","施恩内曼")
	await novel_interface.show_dialog("很快……？","哈蒙")
	await novel_interface.show_dialog("啊对了……","莉琉")
	await novel_interface.show_dialog("小怜，你座椅边上有安全带，最好马上系好，然后伏低身体双手抱头。","莉琉")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("诶？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("有颗卫星正以极快的速度向死海坠落，预计撞击点距你四公里左右，可能会产生很强的冲击波。","莉琉")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("撞击？！\n什、什么时候……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("五","莉琉")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("……？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("四","莉琉")
	await novel_interface.show_dialog("三","莉琉")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("——欸啊啊啊啊！！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("二","莉琉")
	await novel_interface.show_text_only("我手忙脚乱的扣上安全带，像蘑菇般双手抱头紧闭双眼身体蜷缩熟练得一气呵成。")
	await novel_interface.show_text_only("然而，莉琉数到“—”后过了好一阵，似乎什么动静都没有……")
	await novel_interface.show_text_only("我缓缓睁开眼睛抬起了头。")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("哈？","小怜")
	await novel_interface.show_dialog("你是不是骗——","小怜")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("轰————！！！！！")
	await novel_interface.show_text_only("啊，原来冲击波传到这里是需要时间的……\n我可真是个笨蛋。")
	await novel_interface.show_text_only("随着车体的剧烈震动，我的上半身被猛然甩飞，后脑勺重重的磕在了椅背上。")
	novel_interface.change_music("res://assets/audio/music/Sonar.mp3")
	await novel_interface.show_text_only("“嗡——”的一阵耳鸣过后，我眼前快速浮现出一幕幕画面。")
	await novel_interface.show_text_only("仿佛前世的记忆一般……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_ReStardust.png")
	await novel_interface.show_text_only("我似乎曾搂着一位少女从高空坠落，她冰凉的钻蓝色长发，如丝绸般顺滑……")
	await novel_interface.show_dialog("（是我在博物馆遇到的……？！）","小怜")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_ReMissile.png")
	await novel_interface.show_text_only("我刚想伸出手抓住那转瞬即逝的画面，却又看到了某个黄昏中，夕阳映照下绝望的景象……")
	await novel_interface.show_text_only("数百枚导弹同时升空——")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_ReDoomsday.png")
	await novel_interface.show_text_only("犹如最恐惧的噩梦终于成真……")
	await novel_interface.stop_music()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("SID指挥室。")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("闪烁着撞击警报的大屏幕上，一个马萨达地图东北侧的红圈正在迅速缩小。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("撞击点确定在……","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("最终红圈在死海南端，距以利亚大坝约一公里的地方收束成一个红点。")
	await novel_interface.show_text_only("根据卫星图像，撞击瞬间激起的水柱高几十米，形成的冲击波强度却远低于预期。")
	novel_interface.show_character("liliu_uniform1","angry")
	await novel_interface.show_dialog("——怎么会？！","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("由于水几乎不可被压缩，卫星撞向海面时应该像撞在水泥地面上一样，造成比现在大得多的冲击。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("撞击区域是红海-死海大运河的入水口……","爱衣")
	await novel_interface.show_dialog("每年有超过12亿吨海水从红海顺运河一路北上灌入死海。","爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("那个区域的水流很强，同时伴随着大量气泡，足以破坏水体的表面张力——","爱衣")
	await novel_interface.show_dialog("所以卫星没在海面解体，而是直接钻进海里，大部分能量消散在了海底的撞毁点……","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("难道……撞偏了？","秋子")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("躲过一劫吗……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉刚想松口气，却在卫星图像中发现了异常。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("怎么撞击时激起的水柱还没落下，是图像卡住了？","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("沙尘暴的前锋马上就要推到这里了，可能对信号传输造成了影响……","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣将信号切换成在高空盘旋的运载机传来的实时图像后，三人看到了不可思议的一幕——")
	await novel_interface.show_text_only("撞击点附近的水域正不停冒出大量气泡，海面像煮沸的开水般沸腾起来。")
	await novel_interface.show_text_only("镜头拉远，能看到周围的水面伴随气泡突然喷发出六七个高度超过50米的喷泉状水柱。")
	await novel_interface.show_text_only("被巨大水柱激起的波浪达十多米高，如海啸般呈放射状扫向四面八方。")
	await novel_interface.show_text_only("水体逐渐由清澈的浅蓝变为浑浊的锈红色，仿佛海底的污泥被瞬间翻涌到了水面，")
	await novel_interface.show_text_only("腾空而起的水柱在空中形成了大量雾气，好似被封印已久的恶灵，正迫不及待的想要破笼而出……")
	await novel_interface.show_text_only("然而不到半分钟后，撞击点所处的海面就被土黄色的沙尘暴完全覆盖，无法继续看到有效画面了……")
	await novel_interface.show_text_only("被那副诡异的景象所震慑，三人都沉默了许久。")
	await novel_interface.show_dialog("那是什么东西……","秋子")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("如果这就是卫星撞击那里的原因……","莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("爱衣，慕沙尔在遗言里提到过“无视他们中最有远见的人发出的警告”吧？","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("最有远见的人……","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣调出了瓦利德·慕沙尔在本古里安大学任教时的同事名单。")
	await novel_interface.show_text_only("大学包括工程物理科学部、健康科学部、自然科学部以及人文社科部，战前教员达三百多人。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("等一下，那个人——","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉指着名为『Itsuki』的微生物学教授说道。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("我记得慕沙尔在索尔维会议的演讲中提到过，他和大学里一位微生物学教授的关系很好……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那名字我在一份政府备忘录里见过！\n……我找一下！","秋子")
	await novel_interface.show_text_only("很快，秋子发来了备忘录的电子文档——")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Itsuki.png")
	await novel_interface.show_dialog("这位教授多年前反对大运河工程，声称死海内丰富的嗜盐菌会因水体盐度的剧变死亡而令水体酸化。","秋子")
	await novel_interface.show_dialog("当时将自然环境恶劣的马萨达定为新首都的决定本就饱受置疑。","秋子")
	await novel_interface.show_dialog("他身为外籍教授提出的意见就显得更加微妙……","秋子")
	await novel_interface.show_dialog("很多民族主义者为了维护这个国家核心项目，疯狂的攻击他怀有险恶的政治目的。","秋子")
	await novel_interface.show_dialog("再加上此人平日里作风就有些古怪，反对声很快就被压了下去。","秋子")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("他说的“水体酸化”具体是指什么？","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("照那位教授的理论，死亡的嗜盐菌会沉入水底并生成大量碳酸~","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("碳酸……？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("莉琉忽然打了个冷颤，她似乎隐约窥见了慕沙尔拼图的全景——")
	await novel_interface.show_text_only("若真的如她所想，那实在是一副令人毛骨悚然的画面……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_AqueousLayer.png")
	await novel_interface.show_text_only("死亡的嗜盐菌会沉入海底，并产生二氧化碳。")
	await novel_interface.show_text_only("而大运河涌入的盐度较低的海水形成了一面盖子，把这些气体封锁在了底层的高盐度水体中。")
	await novel_interface.show_text_only("经过多年的积累，会在运河入水口附近的水体底层积聚巨量的碳酸。")
	await novel_interface.show_text_only("而卫星的撞击，就像打破了一个装满高压碳酸饮料的罐子……")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform1","angry")
	await novel_interface.show_dialog("爱衣，死海上空有没有能检测温室气体的卫星！？","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("华云宫的TanSat卫星正扫过西亚，我可以通过环境安全协议调用……","爱衣")
	novel_interface.change_expression("dizzy")
	await novel_interface.show_dialog("OK，拿到画面了！","爱衣")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	await novel_interface.show_dialog("等一下……那一大片红色的是什么？！","秋子")
	novel_interface.show_character("liliu_uniform1","angry")
	await novel_interface.show_dialog("……果然。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉立刻切换到国防军的通讯频道——")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("总理先生，我想贵国正面临一场史无前例的危机。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那团雾气究竟是……","施恩内曼")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("是二氧化碳云团。","莉琉")
	await novel_interface.show_dialog("死海南岸的部分陆地已经被那片气团笼罩，有媒体的无人机刚刚拍下了那片区域的照片——","莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Pasture.png")
	await novel_interface.show_dialog("照片中草场上分布着大量不规则白色斑块，放大后你会发现那些斑块都是死去的山羊。","莉琉")
	await novel_interface.show_dialog("散落各处的尸体上看不出任何外伤的痕迹，牧场的围栏和农机设施也完好无损。","莉琉")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_dialog("是怎么回事？！","施恩内曼")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("刚才的撞击，释放出了存储于死海底层高盐度水体中的上百万吨二氧化碳——","莉琉")
	await novel_interface.show_dialog("形成了一个80米厚，半径超过一公里的气层……","莉琉")
	await novel_interface.show_dialog("正常空气中的二氧化碳浓度只有0.03%，而人体呼出的气体中二氧化碳占大概5%。","莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("根据扩散原理，当二氧化碳浓度达到10%，人类就很难呼吸了。","莉琉")
	await novel_interface.show_dialog("如果浓度达到15%，大部分需氧型生物会像照片中的羊群一样立即死亡。","莉琉")
	await novel_interface.show_dialog("而这个气层的平均浓度已经超过了60%，用导弹轰炸只会徒增它的杀伤范围。","莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("在东北风的带动下，它会随着沙尘暴一起被吹向四公里外的马萨达市区……","莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("大约五分钟后抵达会展中心，六分半后从贫民区隔离墙的缺口灌入内城区。","莉琉")
	await novel_interface.show_dialog("而由于隔离墙仅被打开了这一个缺口，很快被隔离墙环绕的内城区就会变成一个大闷罐。","莉琉")
	await novel_interface.show_dialog("二氧化碳密度比空气大，气团会一直贴近地表，即使躲在地下防空洞里也难逃一劫。","莉琉")
	await novel_interface.show_dialog("在这个时间点，大部分市民会在睡梦中无声无息的死去……","莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Jigsaw.png")
	await novel_interface.show_text_only("这才是慕沙尔设计的拼图全景——")
	await novel_interface.show_text_only("无需破坏城区建筑，不会触发反击系统，却能将内城区中这个国家的精英和政要屠戮殆尽。")
	await novel_interface.show_text_only("无论是否无辜，这团死亡之云所过之处，不会留下任何生命。")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_dialog("唉……","施恩内曼")
	await novel_interface.show_text_only("以坚强不屈意志闻名的施恩内曼总理发出了一声无力的叹息。")
	await novel_interface.show_dialog("这就是慕沙尔说的“无法逃脱的坟墓”吗……","施恩内曼")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("总理先生。\n或许……还有希望。","莉琉")
	await novel_interface.show_dialog("如果有某种足够强大的力量，能从正面吹散那片气团的话……","莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("只不过需要借用一下艾米莉欧·史维特莱德少尉。","莉琉")
	await novel_interface.show_dialog("以及麻烦国防军和摩诺拉，为我的手下让让路……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("几分钟后。")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_ConventionCentreDS.png")
	await novel_interface.show_text_only("被狂风裹挟的沙尘暴从死海海面向会展中心的方向滚滚袭来。")
	await novel_interface.show_text_only("数百米高的沙暴锋面遮蔽了日光，天空逐渐由土黄变为暗红色。")
	await novel_interface.show_text_only("城市由朝露未退的清晨，瞬间切换成一幅末日黄昏般的景象……")
	await novel_interface.show_text_only("巨型二氧化碳气团来袭的消息几分钟内就通过联合议会的末日预警系统扩散开来。")
	await novel_interface.show_text_only("城区中的每部手机都弹出了紧急警报，酣睡中被惊醒的市民惊觉大难即将临头。")
	await novel_interface.show_text_only("有人光着脚抱起孩子仓皇奔出，而有些人看到所剩无几的倒计时后反而陷入了绝望的平静。")
	await novel_interface.show_text_only("很多人开始打电话和亲人朋友告别，某些城区的通讯网络被拥塞到几乎瘫痪。")
	await novel_interface.show_text_only("社交媒体上疯传的畜群死亡画面，更是将一些人的恐惧情绪拉到顶点——")
	await novel_interface.show_text_only("街道上有人跪下祈祷，有人失声痛哭，尖叫和哭喊此起彼伏……")
	await novel_interface.show_text_only("刚才感动到涕泪横流的那位女记者，驾着直播车逃跑时高跟鞋卡住了油门，车子直接怼到了树上。")
	await novel_interface.show_text_only("而当地电视台的一名老记者，爬上了死海岸边的一栋居民楼顶层，决定完成生命中最后的播报……")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_ConventionCentreL.png")
	await novel_interface.show_text_only("忽然，从会展中心的天台上垂直向上射出一道巨型光柱，捅破了黑云压城般的暗红天空。")
	await novel_interface.show_text_only("光柱亮度迅速升高，外层泛出一层钴蓝色光晕，周围空气急剧膨胀，滚烫的热浪涌向四方——")
	await novel_interface.show_text_only("霎时间，只见那光柱如一把直入云霄的巨剑般向死海的方向劈了下去，天空也瞬间暗淡下来。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("一片寂静中，由于气压骤降，方圆两公里内的所有人都感到了强烈的耳压变化。")
	await novel_interface.show_text_only("真空造成的气流回抽如飓风般强劲，让街上的人难以站住脚。")
	await novel_interface.show_text_only("裹挟着沙尘和碎石的强风持续了一两分钟，几乎没有人能睁开眼睛……")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_DustStorm2.png")
	await novel_interface.show_text_only("待一切逐渐平息，会展中心附近的人回过神来，纷纷看到了让他们永世难忘的一幕——")
	await novel_interface.show_text_only("沙尘暴被生生撕成两半，中间露出了一片清朗的天空和海面。")
	await novel_interface.show_text_only("在温室气体卫星的监测图像中，巨型二氧化碳气团由于瞬间剧烈的搅动，均匀消散在了死海周围……")

	print("=== 星尘降落篇第20话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
