# stardustdescends_ep15.gd - 星尘降临篇第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep15_script()

func play_script():
	pass

func stardustdescends_ep15_script():
	novel_interface.change_music("res://assets/audio/music/Wind.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_StarrySky.png")
	await novel_interface.show_text_only("Take my love Take my land\n夺我所爱，抢我土地")
	await novel_interface.show_text_only("Take me where I cannot stand\n让我无处可栖居")
	await novel_interface.show_text_only("I don't care I'm still free\n我不在乎，我仍不羁")
	await novel_interface.show_text_only("You can't take the sky from me\n因为天空你夺不去")
	await novel_interface.show_text_only("Take me out to the black\n赶走我，向黑暗")
	await novel_interface.show_text_only("Tell them I ain't coming back\n告诉世人我不会回来")
	await novel_interface.show_text_only("Burn the land and boil the sea\n焚烧大地，煮沸海洋")
	await novel_interface.show_text_only("You can't take the sky from me\n可你没法夺去我的天际……")
	await novel_interface.show_text_only("——《Firefly》主题曲")
	await novel_interface.stop_music()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("马萨达城外，公路旁。")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Sways.png")
	await novel_interface.show_text_only("太阳下山后，沙漠中的天色很快暗淡下来，我们在城外一条偏僻的小路下车。")
	await novel_interface.show_text_only("薇拉换掉了卡车的车牌，我帮着艾米莉欧在货箱外罩上印着国防军标志的防暴网。")
	await novel_interface.show_text_only("据说城外经常有哑弹、地雷等危险品需要处理，人们对这种罩着防暴网的军用货车都会敬而远之。")
	await novel_interface.show_text_only("卡车的无人驾驶模式被设置成了跟随，一会就让它尾随我们的装甲车进城。")
	await novel_interface.show_text_only("或许因为下午死里逃生的共同经历，我和她们从绑架者和人质的关系渐渐变成了“共犯”。")
	await novel_interface.show_text_only("刚才我们一路闲聊，我讲了新丰洲的校园生活和各种美食，她们说了很多军事学院的趣事。")
	await novel_interface.show_text_only("原来薇拉和艾米莉欧年纪没比我大多少，可以算是同龄人，而我们却经历了完全不同的人生——")
	await novel_interface.show_text_only("七年战争期间，马萨达兵源紧缺，开始尝试从初中选拔学生直接进入资源更丰富的军校就读。")
	await novel_interface.show_text_only("艾米莉欧12岁时为了从压抑的家里逃出来，主动报名了全寄宿制的军校。")
	await novel_interface.show_text_only("而薇拉因父亲是空军系统的高级官员，被家人早早的安排进了坎伯利参谋学院。")
	await novel_interface.show_text_only("她们各自接受30个月的文化课和军事训练后，在同一年报名了马萨达最顶级的『塔楼』精英军校。")
	novel_interface.show_character("ren_medical","perspire1")
	await novel_interface.show_dialog("“塔楼”就是那个录取率不到1%的……？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("是啊，薇拉为了证明自己不用靠关系就能录取，报名时特意改掉了姓氏，给她老爸气得半死。", "艾米莉欧")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("其实『达杨』也不是什么罕见的姓氏啦，非要给自己改成『瓦尔基里』这么夸张……", "艾米莉欧")
	await novel_interface.show_dialog("入围考生名单公示的时候，学生和家长看榜单时都在议论那个“女武神”是何方神圣。", "艾米莉欧")
	await novel_interface.show_dialog("她当时就在人群里低着头，小脸涨得通红，真是让人心疼呢~", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("啊我懂的！就是那种中二病的公开处刑！")
	await novel_interface.show_text_only("等等为什么我会懂……")
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("别说啦！！！\n等毕业我就改掉……", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("别啊，我还挺喜欢的——", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","blush")
	await novel_interface.show_dialog("诶？", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("那次近身格斗考核，我只要在擂台上喊她“女武神大人”，薇拉就会立刻方寸大乱。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("闭嘴啊你！！\n不许那么叫我……", "薇拉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("小怜帮拉一下那边的防爆网！", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("好的女武神大人，没问题女武神大人。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("喂！！", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("噗——哈哈哈哈哈哈哈哈哈哈哈哈哈哈~", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("你怎么总教小孩这种东西啊！！", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("我们说笑着完成整备时，天色已经完全暗了下来。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_SlumArea.png")
	await novel_interface.show_text_only("装甲车从城东侧的老厂区进城，一路缓缓开到了内城区东北侧隔离墙外不远的地方。")
	await novel_interface.show_text_only("这一带似乎是贫民区，周围的建筑低矮破旧，整条街上没几支路灯还能正常工作。")
	await novel_interface.show_text_only("昏暗的街道上几乎没有行人，街边挂着用四种地方语言写的提示牌。")
	await novel_interface.show_text_only("年久失修的居民楼发出的幽光，还不如从远处的隔离墙后面泄出的光显得明亮。")
	await novel_interface.show_text_only("唯有满天的繁星，在这条街上看得特别清晰。")
	novel_interface.show_character("ren_medical","happy")
	await novel_interface.show_dialog("哇——\n星星好亮。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("就是这了~", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧拉开街边一扇锈迹斑斑的铁皮大门，露出后面被居民楼围出来的小院。")
	await novel_interface.show_text_only("薇拉小心翼翼的驾驶卡车倒车驶入小院，然后把装甲车也停了进去。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我们从院内的单元门走进昏暗的居民楼，刚上到二楼就看到一扇如防空洞大门般的厚重金属门。")
	await novel_interface.show_text_only("艾米莉欧按响门铃，轻轻说了句“是我”，一个四十岁左右的女人开门将我们迎了进去。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_ShelterCorridor.png")
	await novel_interface.show_text_only("走入室内先看到一条长长的走廊，屋内飘着淡淡的玫瑰熏香的味道。")
	await novel_interface.show_text_only("屋顶的灯泡很直白的挂在用电线垂下的灯座上，地毯虽然老旧但能看得出维护的很好。")
	await novel_interface.show_text_only("走廊的墙面和门都是淡雅的群青色，墙上还贴着很多色彩艳丽的儿童画。")
	await novel_interface.show_text_only("走廊远处的房间忽然探出半个脑袋，一个小姑娘扒着门框好奇的看了看我们，又迅速缩了回去。")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("（这里是幼儿园？）", "小怜")
	await novel_interface.show_dialog("（不，更像是孤儿院……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看着墙上那些稚嫩的画作，有些是以孩子的视角目睹的残酷画面……")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("海法小姨~", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("（小姨？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哎呀都这么晚了你们还跑一趟，薇拉也来了？\n这位是……", "海法")
	novel_interface.show_character("ren_medical","happy")
	await novel_interface.show_dialog("阿姨您好，我叫小怜。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("啊哟小姑娘真漂亮，对了你们还没吃饭吧？\n我去厨房给你们拿点吃的……", "海法")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("不用啦，上次不是说要给这边的社区送一些军队打算处理掉的物资嘛。", "艾米莉欧")
	await novel_interface.show_dialog("最近国防军在精简编制，薇拉缠着她爸把裁撤部队的一些物资要来了。", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("怎么总麻烦你父亲，都送好几次东西了……改天咱一定得当面感谢他。", "海法")
	novel_interface.show_character("ren_medical","speechless")
	await novel_interface.show_dialog("（你们干过几次了啊？怪不得这么熟练……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","panic")
	await novel_interface.show_dialog("不用不用，我爸他太忙！", "薇拉")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("反正军队撤退的时候，把物资带回去的成本可能比重新采购都高。", "薇拉")
	await novel_interface.show_dialog("不过这些东西的处理流程不太规范，我们才特意晚上送过来……您嘱咐大家别四处说就可以啦！", "薇拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哦哦好的好的，那我帮你们拿吧？", "海法")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("我给孩子们拿了一批军粮和平板电脑，您帮我在仓库里腾些地方就可以。", "艾米莉欧")
	await novel_interface.show_dialog("剩下大部分是哈迪医生的救助站用得上的东西，我一会再给他送过去……", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是艾米莉欧姐姐！", "小孩A")
	await novel_interface.show_dialog("艾米姐姐——", "小孩B")
	await novel_interface.show_dialog("还有女武神姐姐~~", "小孩C")
	await novel_interface.show_text_only("薇拉满脸黑线的用手捂住了脸。")
	await novel_interface.show_text_only("不一会，从两间大卧室接二连三的跑出来十几个小朋友把我们团团围住。")
	await novel_interface.show_text_only("艾米莉欧显然是这里的名人，孩子们都争着环绕在她身边，大家都很开心的样子。")
	await novel_interface.show_dialog("姐姐姐姐，我已经能读2年级的课文啦！", "小孩A")
	await novel_interface.show_text_only("一个小姑娘拿着电子墨水平板得意的说道，那古老的型号看起来和我年纪差不多。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("丽玛真厉害，这次给你们带了新的平板~", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("艾米姐姐，我现在能颠20个球！", "小孩B")
	await novel_interface.show_text_only("一个小男孩穿着宽大到能露出肩膀的10号球衣，拼命的举着手。")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("奥马尔加油！以后踢爆华云宫国家队就靠你啦。", "艾米莉欧")
	await novel_interface.hide_character() 
	await novel_interface.show_dialog("还有还有，看、看我画的——", "小孩C")
	await novel_interface.show_text_only("一个发音有些不清楚的孩子，指着墙上最大的那副画。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("哈桑画的真好……", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("其实刚才看物资清单的时候我就大概猜到了她们的目的，只是不知道还有这种地方——")
	await novel_interface.show_text_only("楼下用各种地方语言写成的告示牌，说明这一带是马萨达的外来民族聚居区。")
	await novel_interface.show_text_only("这片区域明显极度缺乏基础设施，而且从那厚重的大门看来，附近的犯罪率应该不低。")
	await novel_interface.show_text_only("看着孩子们的笑脸，我忽然有点担心那个小鬼——")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("艾米莉欧，那个……我的手机……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她从兜里掏出手机，想了想又拿下一台步话机，转身一起递给了我。")
	novel_interface.show_character("emilio","normal")
	await novel_interface.show_dialog("我和薇拉下去搬东西，步话机你拿着，这附近手机信号时有时无……", "艾米莉欧")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("明天清晨是停火协议签署仪式，现在内城区的通道已经封闭了。", "艾米莉欧")
	await novel_interface.show_dialog("明天早上我们赶在沙尘暴前送你回去~", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("孤儿院办公室。")
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_ShelterOffice.png")
	await novel_interface.show_text_only("我拿着手机缩在好不容易找到信号的墙角，不停的点头道歉。")
	await novel_interface.show_dialog("现在才想起跟她们要手机？\n这都几点了！", "莉琉")
	await novel_interface.show_dialog("你们几个都在外面玩疯了吧！", "莉琉")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("噫——！\n对、对不起……", "小怜")
	await novel_interface.show_dialog("所以……\n我今天得在外城区过夜，明天一早就回……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("还要过夜？！", "莉琉")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("艾米说现在内城区的通道都封锁了，好像因为那个停火协议。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("艾米……叫的还挺亲的哈？", "莉琉")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("没、没有！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你这种笨蛋被人埋沙漠里恐怕自己都不知道。", "莉琉")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("啊，今天那两枚导弹……是你拦截的吧？\n谢谢谢谢！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("嘁——\n算了，也不能说全无收获。", "莉琉")
	await novel_interface.show_dialog("那个薇拉的父亲是马萨达总参谋部的作战部长，国防军里的军功派。", "莉琉")
	await novel_interface.show_dialog("他们是军事世家，薇拉的曾祖父摩西·达杨还是马萨达家喻户晓的人物。", "莉琉")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("诶？这么厉害……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("有意思的是，那人还是个业余考古学家，据说是唯一对麦比拉洞进行过考古的马萨达人——", "莉琉")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("麦比拉洞……就是前两天发生事故的那个？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("1967年六日战争之后，马萨达获得了希伯伦的控制权。", "莉琉")
	await novel_interface.show_dialog("当时任国防部长的摩西·达杨派一个身材苗条的\n12岁小女孩，从洞穴外的缝隙钻进了麦比拉洞。", "莉琉")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("（怎么听起来这么乱来……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("不过那个收集狂居然什么文物都没弄出来，后来出于宗教原因就不再允许人们进去了……", "莉琉")
	await novel_interface.show_dialog("总之火爆脾气和说干就干的性格似乎是他们的家族遗传，她父亲当年也是不要命飞行员。", "莉琉")
	await novel_interface.show_dialog("薇拉非要考技术派的塔楼军校这事就够让他没面子了，要是再被人知道他女儿今天……", "莉琉")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("你、你要做什么啊？", "小怜")
	await novel_interface.show_dialog("她俩人还挺好的，你别……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("笨蛋，万一你们半路被抓了，我得提前找些谈判的筹码吧。", "莉琉")
	await novel_interface.show_dialog("叛逆期的小孩真不让人省心……", "莉琉")
	novel_interface.show_character("ren_medical","uneasy")
	await novel_interface.show_dialog("嘿嘿放心啦我没事的，安妮和小星尘怎么样了？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你被绑架之后，出于安全考虑她们俩都被我送到大使馆了。", "莉琉")
	await novel_interface.show_dialog("唉，这下又得跟元老院的那帮老头子解释……", "莉琉")
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("那就好~~我明天一定按时赶到大使馆！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("啊对了，你要是在外面过夜的话——", "莉琉")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("嗯？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("洗澡的时候注意别被男人看到，按照有些民族的习俗你可能就得嫁出去了~", "莉琉")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("哈！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉说完马上“啪”的挂掉了电话。")
	await novel_interface.show_text_only("我回味着她最后的话，不禁打了个哆嗦。")
	novel_interface.show_character("ren_medical","sob")
	await novel_interface.show_dialog("（真讨厌！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("打完电话了吗？\n小怜来喝点石榴汁吧，都是新榨好的。", "海法")
	await novel_interface.show_text_only("海法阿姨端着托盘走了进来，声音特别和蔼。")
	await novel_interface.show_text_only("她在桌上放了一碟开心果，还有一个装着红色液体没有标签的玻璃瓶——")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("啊，昨天艾米就给了我一瓶，是从您这里拿的？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哈哈那孩子从小就喜欢喝，跟她妈妈一样。", "海法")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("我听她叫您小姨，那她母亲是您的……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("唉——那是我大姐。", "海法")
	await novel_interface.show_text_only("海法阿姨叹了口气，面露忧伤的轻轻坐在椅子上。")
	await novel_interface.show_dialog("我们家三个女儿，大姐去世了，后来二姐也没了音信……", "海法")
	await novel_interface.show_dialog("小时候聚落里的老人为了能让艾米上学，把她送到了她父亲家，但她还是经常跑出来。", "海法")
	await novel_interface.show_dialog("这两年都照顾起我们来了，明明还是个孩子……", "海法")
	await novel_interface.show_text_only("我注意到办公桌上的相框里，是张三人在集市合影的老照片，照片上三个女孩都很漂亮。")
	await novel_interface.show_text_only("从眉宇间能看出最左面的短发女孩是小时候的海法阿姨，当时她穿着校服，年纪大概十二三岁。")
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("艾米跟我说过，她父母都在迁移的路上去世了。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……她是跟你这么说的？", "海法")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("对呀，怎么？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那时她一直发着高烧，估计也不记得了，后来的事都是长老告诉她的……", "海法")
	await novel_interface.show_dialog("迁移路上确实死了很多人，唉——", "海法")
	await novel_interface.show_dialog("这样也好，这样也好……", "海法")
	await novel_interface.show_text_only("海法阿姨没有再说下去，我轻轻拿起相框，照片右下角写着两行小字——")
	await novel_interface.show_text_only("“艾米尔&莉娜&海法”\n“阿勒颇2010”")

	print("=== 星尘降临篇第15话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
