# stardustdescends_ep10.gd - 星尘降临篇第10话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep10_script()

func play_script():
	pass

func stardustdescends_ep10_script():
	await novel_interface.show_text_only("走出入境大厅时，天空的阴霾已经散去，我们三人搭上了港口专列。")
	await novel_interface.show_text_only("磁悬浮列车的速度很快，不到十分钟就抵达了马萨达内城区的克奈塞特站。")
	await novel_interface.show_text_only("……")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Masadainner.png")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("这……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","happy")
	await novel_interface.show_dialog("好、好厉害！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","happy")
	await novel_interface.show_dialog("哇嗷——", "小星尘")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","happy")
	await novel_interface.show_dialog("这里就是……马萨达堡？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","panic",0.25)
	await novel_interface.show_dialog("我也……没想到……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("面前的这幅景象完全颠覆了我对马萨达“战火纷飞的沙漠要塞”的印象——")
	await novel_interface.show_text_only("花园般整洁优雅的街道上，随处可见AI环卫机器人和无人驾驶的货运小车。")
	await novel_interface.show_text_only("远处市中心高层建筑群的外立面，包裹着科技感十足的金属甲板，隐约反射出白云的倒影。")
	await novel_interface.show_text_only("碧蓝的天空下，大片植被一直绵延到视线尽头……")
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("真是让人神清气爽呢——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我扶着石质围栏眺望远方，不由做了个深呼吸，湿润的空气中夹杂着海风特有的咸味。")
	novel_interface.show_character("ren_medical","smile")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("这里是全球气压最高的地方，含氧量高人就会感觉呼吸自在~", "安妮")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("亏他们能把死海边的沙漠改造成现在的样子……", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("安妮，那边连成一片的是……？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我指向左手边，远处有一条横贯东西的围栏，围栏背后似乎就没有任何高层建筑了。")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("那个就是『隔离墙』啊。", "安妮")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("咱们现在离得远，那堵墙实际上有几十米高，遍布着安检岗哨和自动防御装置。", "安妮")
	await novel_interface.show_dialog("地下还埋设了很多传感器，连老鼠都钻不过去。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮叹了口气，小声自言自语道。")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("他们之前的首都也有这种东西，可还不是被夷为平地……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","worry")
	await novel_interface.show_dialog("那是很久之前的事吧……\n当时我才上小学——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我忽然想到，因为安妮在『因果之隙』中停留了七年，对她而言那或许是不久前的记忆。")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("话、话说——\n修那种墙有什么意义吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我赶忙生硬的切换了话题。")
	novel_interface.show_character("ren_medical","smile")
	await novel_interface.show_dialog("如果真的打起来，一堵墙什么也挡不住吧……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","normal2")
	await novel_interface.show_dialog("政府会为了各种目的修墙——阻止外敌入侵、民众出逃或者非法移民之类的……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮望着前方公园中六大学园都市的旗帜说道。")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("但马萨达的状况还要更复杂些……", "安妮")
	await novel_interface.show_dialog("在那堵墙的两侧，很多人都不希望看到对方。", "安妮")
	await novel_interface.show_dialog("只有看不到另一边，假装对方不存在，才能心安理得的过自己的生活。", "安妮")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("嘛……不过估计小怜也不明白。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","pleased")
	await novel_interface.show_dialog("哦~~这样啊……", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小星尘忽然冒出来，一副好像很明白的样子边点头边做思考状。")
	novel_interface.show_character("stardust_small","pleased")
	await novel_interface.show_dialog("嗯、嗯~", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("你懂个头啦！这不是跟我在物理课上断片时的反应一样吗？！")
	await novel_interface.show_text_only("安妮的话确实说得我云里雾里，可能和她过去的经历有关吧……")
	await novel_interface.show_text_only("看着我迷茫空洞的眼神，安妮搂住了我的脖子。")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("哎呀别这么认真啦，我其实乱讲的~", "安妮")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("告诉你吧，马萨达的『幻想军势』就在内城区地下的某个地方哦！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("诶……？\n就是那个XK级的异质物？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("『幻想军势』是马萨达的战略级异质物，其存在形式为一个不可移动的特定空间。")
	await novel_interface.show_text_only("从那个空间内部发射的武器可以获得威力倍化的异常效果，产生几倍到几百倍于原设计值的破坏力。")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_doomsday.png")
	await novel_interface.show_text_only("第三学园都市前段时间公布的『自动反击系统』正是利用了这一特性。")
	await novel_interface.show_text_only("当系统判断马萨达市区的毁伤程度超过50%时，就会自动启动『末日程序』——")
	await novel_interface.show_text_only("利用『幻想军势』向全世界所有大型城市无差别投放核武器，以确保共同毁灭。")
	await novel_interface.show_text_only("虽然在宣布之初遭到了激烈的抗议，但民众似乎很快就接受了木已成舟的事实。")
	await novel_interface.show_text_only("马萨达能迅速与抵抗军达成停火协议，恐怕也与这个系统有莫大的关系。")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Masadainner.png")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("你看到那些大楼外立面的金属装甲了吗？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("刚才就注意到了……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("你不会想告诉我这座城市是用来对抗使徒的吧……")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("据说这片内城区的地下，全都铺满了那种装甲。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("越听越像了喂！")
	novel_interface.show_character("ren_medical","perspire1")
	await novel_interface.show_dialog("什、什么意思……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("你觉得他们为什么要将新首都设在死海边这块贫瘠的沙漠盐碱地上呢——", "安妮")
	await novel_interface.show_dialog("而且为了支撑这座地理位置糟糕透顶的首都，还要斥巨资修建落差四百多米的大运河。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("是为了这下面的『幻想军势』……？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我指了指自己脚下，又觉得有什么不对。")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("可也太下本了吧……又不是『埃癸斯』那种能屏蔽一切外部攻击的防护罩。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("所以各国都猜想，或许『幻想军势』还存在某种尚未公布的关键特性。", "安妮")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("以至于马萨达的领导人不惜将全民族的命运都押在这片土地上。", "安妮")
	await novel_interface.show_dialog("可以说这整座城都是为保护『幻想军势』而设的防护设施——", "安妮")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("那么作为防护体系的一环，修建那种级别的隔离墙就不足为奇了吧~", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("“马萨达永不陷落”还有这一层意思吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可越是不计成本去守护的秘密，就会越让人觉得好奇吧……")
	await novel_interface.show_text_only("我转身看了看克奈塞特站外印着同样标语的巨幅广告，却意外看到一个熟悉的面孔——")
	await novel_interface.show_text_only("艾米莉欧拎着一个装满的白色购物袋，正好从出站口的扶梯走出来……")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("啊嘞？", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这位少尉军官和我对视了一眼，微笑着走了过来。")
	await novel_interface.show_text_only("安妮立刻训练有素的装作和我不认识的路人，拉着行李箱边看手机边快步走开。")
	await novel_interface.show_text_only("而小星尘这两天似乎明白了别人看不见也听不到自己这件事，胆子大了不少。")
	await novel_interface.show_text_only("她趾高气昂的站在我身前，就像有主人撑腰的小型犬一样嚣张。")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("啊！你就是赌船上的那个……实习护士？", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她看了看我挂在胸前的名牌。")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("叫小怜是吧~", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","perspire1")
	await novel_interface.show_dialog("你、你好……\n真巧又见面了。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("哈哈我正好告诉你，那天你走以后我好好教训了一下那个侍者。", "艾米莉欧")
	await novel_interface.show_dialog("后来发现赌场的好几个女荷官都被那家伙骚扰过。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("——诶！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那人居然还是个惯犯吗？")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("不过这次居然敢对客人下手，他是不是脑子抽了~", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("啊哈哈哈哈……！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("其实是中了催眠喷雾！")
	novel_interface.show_character("ren_medical","happy")
	await novel_interface.show_dialog("说来那天真得谢谢你，提前放我过了安检……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("小意思啦，最近上面总喜欢征调我们去执行一些无聊的任务。", "艾米莉欧")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("而且上次还搞乌龙，收容队带着一堆设备在船上扫描了半天，结果什么都没找到。", "艾米莉欧")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("不知道他们又从哪买的假情报……", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","stare")
	await novel_interface.show_dialog("哼！那还那么凶……", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小星尘对艾米莉欧做了个鬼脸。")
	novel_interface.show_character("stardust_small","stare")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("emilio","normal",0.25)
	await novel_interface.show_dialog("话说——", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("艾米莉欧蹲下身来。")
	novel_interface.show_character("stardust_small","stare")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("emilio","smile",0.25)
	await novel_interface.show_dialog("这孩子好可爱呀~不是本地人吧？", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我和小星尘瞬间石化了。")
	novel_interface.show_character("stardust_small","panic")
	await novel_interface.show_dialog("诶……？\n呜……咕……", "小星尘")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这家伙一下子没了底气，拼命往我身后缩，被吓得差点哭出来。")
	novel_interface.show_character("stardust_small","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_medical","wail",0.25)
	await novel_interface.show_dialog("啊？哈哈哈哈……\n她、她是我的……我的那个……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她到底是怎么看到的！？")
	await novel_interface.show_text_only("艾米莉欧从购物袋中拿出一个装着红色透明液体的玻璃瓶，瓶身上没有任何标签。")
	novel_interface.show_character("stardust_small","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("emilio","smile",0.25)
	await novel_interface.show_dialog("新榨的石榴汁，很好喝哦~\n是城里有名的特产。", "艾米莉欧")
	await novel_interface.show_dialog("来，送你一瓶——", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她说着就将瓶子递给了小星尘，我意识到要阻止时已经来不及了。")
	await novel_interface.show_text_only("我几乎已经能想到那个玻璃瓶穿过小星尘的身体摔碎在地上的画面……")
	novel_interface.show_character("stardust_small","uneasy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("emilio","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯……谢谢……", "小星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("小星尘接住瓶子，抱在了手里。\n艾米莉欧摸了摸她的头。")
	novel_interface.show_character("stardust_small","uneasy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("emilio","mock",0.25)
	await novel_interface.show_dialog("真乖~", "艾米莉欧")
	novel_interface.character_light(0.35,"konata_eye")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("欸嘿嘿~~", "小星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("怎么回事……\n这小家伙……已经不是幻影了？")
	await novel_interface.show_text_only("从什么时候开始的？因为我和安妮一直能看到她所以才没有察觉吗？")
	await novel_interface.show_text_only("不对，肯定是通过入境处之后的事，否则海关安检是不会轻易放行的。")
	await novel_interface.show_text_only("也就是说，是刚刚发生的？")
	await novel_interface.show_text_only("总之一会回酒店再做研究，现在先蒙混过关吧~")
	await novel_interface.show_text_only("等一下，说到入境处……")
	novel_interface.show_character("emilio","normal")
	await novel_interface.show_dialog("不过小怜啊——", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧似乎注意到了什么，顺势抓住了小星尘的手腕一把翻了过来。")
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("她的手上，怎么没有入境处的条形码？", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的头嗡的一下，汗珠从脑门渗了出来。")
	await novel_interface.show_text_only("完了完了，要被逮捕了！！")
	await novel_interface.show_text_only("听说马萨达连普通市民都对非法入境者很敏感，更别提我们被士兵当街抓个现行……")
	await novel_interface.show_text_only("艾米莉欧端详着我僵硬的表情，又看了看完全没搞清楚状况还抱着石榴汁傻笑的小星尘。")
	novel_interface.show_character("emilio","speechless")
	await novel_interface.show_dialog("唉，你带着她这么大摇大摆的在街上走，不到一个小时就会被逮捕的。", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧从腰带挂扣上拿出一台手持设备，样子像是加厚了两三倍的手机。")
	await novel_interface.show_text_only("点了几下之后，那台设备的打印口冒出一条约一厘米宽、印着条形码的白色纸带。")
	await novel_interface.show_text_only("她将纸带绕在小星尘手上，并把两端粘好。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("这是军用的临时ID，条形码的油墨会在36小时后自动消失。", "艾米莉欧")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("纸带的防水性一般，可以淋浴，但最好不要泡澡或游泳。", "艾米莉欧")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("这段时间内，你要么去入境处补办手续，要么赶紧带小孩出城，明白了吗？", "艾米莉欧")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_medical","wry_smile",0.25)
	await novel_interface.show_dialog("好、好的！\n谢谢……", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不用谢啦，我的营地就在外城区，挨着救援组织的配送中心。", "艾米莉欧")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("没准这两天咱们还能见到呢~", "艾米莉欧")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("说罢，艾米莉欧捏了捏小星尘的脸蛋，拎起购物袋大步流星的离开了。")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("拜~", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着她的背影，我拉紧了星尘的小手。")
	novel_interface.show_character("ren_medical","gratified")
	await novel_interface.show_dialog("还真是个好人呢……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("当天晚上。")
	await novel_interface.show_text_only("马萨达荫巴尔酒店客房内。")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Masadhotel.png")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("好嘞——", "安妮")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("房间里所有的盗摄和监听装置都拆掉啦。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮用爱衣发放的设备在套房各个角落仔细检查了半个小时，拆下好几个微型电子元件。")
	novel_interface.show_character("anne_uniform","happy")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_medical","wail",0.25)
	await novel_interface.show_dialog("……这么多？！", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("应该是摩诺拉对所有酒店高级套房的常规部署，并非是针对咱们的。", "安妮")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("一会就在客厅和莉琉连线吧~", "安妮")
	novel_interface.hide_all_characters()
	await novel_interface.show_text_only("小星尘正趴在卧室床上用酒店的圆珠笔和稿纸乱画\n，似乎还在那种终于可以触碰实物的兴奋中。")
	novel_interface.show_character("ren_medical","bored")
	await novel_interface.show_dialog("（她现在可以自己拿我的手机玩了……）\n（好像更难搞了啊！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我还在庆幸还好给收藏夹设了密码，却突然感到胸部一阵酥麻，同时传出了爱衣的声音。")
	await novel_interface.show_dialog("哦呀呀，我正在汇总安妮的简报——", "爱衣")
	await novel_interface.show_dialog("也就是说，那个叫星尘的小家伙在进入马萨达内城区后立即获得了身体，却依然处于失忆状态吗？", "爱衣")
	novel_interface.show_character("ren_medical","shy")
	await novel_interface.show_dialog("——你就不能用手机吗？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("用这个音质比较好嘛……", "爱衣")
	await novel_interface.show_dialog("不要在意不要在意~", "爱衣")
	await novel_interface.show_dialog("先确认一下情况，昨天安妮触摸到小怜在保险库找到的金色颗粒后，同样也能看到小星尘了对吧？", "爱衣")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("嗯，当时吓了我一跳，还以为见鬼了……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("对小怜之外的人都可以生效……\n难道是新型的异质物？", "爱衣")
	await novel_interface.show_dialog("你们刚才用酒店的体重秤帮她测量是20公斤，倒是处于那个年龄的平均水平……", "爱衣")
	await novel_interface.show_dialog("虽然失忆，但具备基本生活常识，甚至识字水平远超同龄人，能将网页上的文字念出来……", "爱衣")
	await novel_interface.show_dialog("这孩子听来……很有料啊！", "爱衣")
	novel_interface.show_character("ren_medical","stare")
	await novel_interface.show_dialog("有……料？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你们能不能快点把她带回来，让我好好研究一下她的构造哎呀！……", "爱衣")
	await novel_interface.show_text_only("一声暴击打断了爱衣渐入高潮的自言自语，莉琉好像完全不介意把战研部主任敲傻呢~")
	await novel_interface.show_dialog("咳咳，总之那个魔女有表达什么新的诉求吗？", "莉琉")
	await novel_interface.show_dialog("或许是能帮她取回记忆的线索……", "莉琉")
	novel_interface.show_character("ren_medical","wry_smile")
	await novel_interface.show_dialog("好像还没……\n她现在的诉求除了吃就是玩。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看了看远处餐桌上，那堆被小星尘从迷你吧翻出来吃了一两口就丢在那里的零食。")
	await novel_interface.show_dialog("也好，你们再等等吧，马萨达与抵抗军停火协议的签署仪式就在后天一大早。", "莉琉")
	await novel_interface.show_dialog("小怜的伪装身份是国际医疗救援组织成员，按规定明天要接受一次“历史课程”后才能自由行动。", "莉琉")
	novel_interface.show_character("anne_uniform","frustrate")
	await novel_interface.show_dialog("那是什么……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("就是马萨达立场的爱国主义教育，条件很宽松，只要在国家博物馆停留三小时以上就可以。", "莉琉")
	novel_interface.show_character("ren_medical","wail")
	await novel_interface.show_dialog("我可以翘课吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("不行，NGO成员未完成课程一律不许出隔离墙。", "莉琉")
	await novel_interface.show_dialog("你完成课程后，我会派大使馆的人接你和星尘去入境处补办正式ID。", "莉琉")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("后天协议签署完成后，我们就能自由行动了吧？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("理论上是这样，不过——", "爱衣")
	await novel_interface.show_text_only("终于从击打中苏醒过来的爱衣插话道。")
	await novel_interface.show_dialog("签署协议那天，从中午开始马萨达就会陷入漫天黄沙的状态。", "爱衣")
	novel_interface.show_character("ren_medical","panic")
	await novel_interface.show_dialog("沙尘暴？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("所以他们才把签约仪式定在早上吧……", "安妮")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Duststorm.png")
	await novel_interface.show_text_only("马萨达是地中海气候，处于盛行西风带，每年只有这几周会刮东风。")
	await novel_interface.show_text_only("每到这段时期，荒漠风化的浮沙很容易被卷起，沙尘能被扬起几百米高，顺着东风排山倒海而来。")
	await novel_interface.show_text_only("据说在这种极端环境下，高大的隔离墙能在一定程度上维护内城区脆弱的生态系统。")
	await novel_interface.show_text_only("但我依然无法想象，到时候窗外这片繁华的城区会是一副怎样的景象……")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Masadhotel.png")
	await novel_interface.show_dialog("啊呀——！！", "小星尘")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("隔壁突然传来一阵玻璃破裂的声音。")
	novel_interface.show_character("ren_medical","shout")
	await novel_interface.show_dialog("怎么回事？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮瞬间从沙发窜起来跑向卧室，却看到小星尘趴在地上，胳膊周围的地板上撒满了红色的汁液。")
	novel_interface.show_character("stardust_small","panic")
	await novel_interface.show_dialog("呜……\n石榴汁……", "小星尘")
	novel_interface.change_expression("tear")
	await novel_interface.show_dialog("打翻了啦……", "小星尘")

	print("=== 星尘降临篇第10话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
