# stardustdescends_ep06.gd - 星尘降临篇第6话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	stardustdescends_ep06_script()

func play_script():
	pass

func stardustdescends_ep06_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Stardust/BG_Stardust_Vault.png")
	await novel_interface.show_dialog("呐，你在找什么呢？", "小女孩的声音")
	novel_interface.show_character("ren_full","worry")
	await novel_interface.show_dialog("——！！！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("封闭的空间内，突然从身后冒出一个小女孩，我脑子嗡的一下身体也完全僵住，空气似乎都凝固了。")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("（啊啊啊啊啊啊啊啊啊啊啊啊！！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("按照恐怖电影里的桥段，我、我难道……")
	await novel_interface.show_text_only("…………")
	await novel_interface.show_dialog("嗯嗯~？", "小女孩")
	await novel_interface.show_text_only("在我屏气凝神到几乎灵魂出窍的时候，她轻巧的绕到了我的面前，将头探过来好奇的看来看去。")
	novel_interface.show_character("stardust_small","panic")
	await novel_interface.show_dialog("……坏，坏掉了？", "小女孩")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小女孩伸过手捏了捏我的脸，头上那对猫耳造型的头饰发出的金色光晕忽明忽暗。")
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("你、你是……？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","wordless")
	await novel_interface.show_dialog("咦，你不记得了吗？", "小女孩")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("记得什么啊？！")
	await novel_interface.show_text_only("她好像很失望的叹了口气。")
	novel_interface.show_character("stardust_small","wordless")
	await novel_interface.show_dialog("唉，还是这种喜欢逃避责任的性格啊——", "小女孩")
	novel_interface.change_expression("konata_eye")
	await novel_interface.show_dialog("啧啧啧……", "小女孩")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小女孩露出一幅“你行不行啊”的表情，无奈的摇了摇头。")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("哈？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然还没搞清楚状况，不过我好像被这个小丫头深深的鄙视了。")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("你到底是谁啊……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","pleased")
	await novel_interface.show_dialog("哼，那就再告诉你一遍，听好了哦——", "小女孩")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小女孩插着腰，得意的抬起下巴，似乎准备宣布她的名号。")
	novel_interface.show_character("ren_full","bored")
	await novel_interface.show_dialog("（这个表情怎么好像有点熟悉……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","pleased")
	await novel_interface.show_dialog("我就是——", "小女孩")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","uneasy")
	await novel_interface.show_dialog("（不会又是哪个贵族大小姐或者天才少女暴力大姐头或者抖M变态什么的吧……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","uneasy")
	await novel_interface.show_dialog("是——", "小女孩")
	await novel_interface.show_dialog("嗯……", "小女孩")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","stare")
	await novel_interface.show_dialog("……嗯？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她直勾勾的盯着我，表情从得意渐渐变为惊惶，好像我是拐卖小孩的人贩子。")
	novel_interface.show_character("stardust_small","panic")
	await novel_interface.show_dialog("我……叫什么来着！？", "小女孩")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","perspire1")
	await novel_interface.show_dialog("我哪知道啊！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","tear")
	await novel_interface.show_dialog("好……好凶！", "小女孩")
	await novel_interface.show_dialog("咕呜……", "小女孩")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("似乎被我的话吓到，她有些无助的左右看看，后退了几步。")
	await novel_interface.show_text_only("然后转过身，两只小手捂着脑袋蹲了下去。")
	novel_interface.show_character("ren_full","shy_left")
	await novel_interface.show_dialog("（……怎么搞得好像是我是坏人一样？！）", "小怜")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("欸？那个是……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看到她手腕上绑着一张皱巴巴的粉色小纸条，便走上前去轻轻的摘了下来。")
	await novel_interface.show_text_only("纸条上面歪歪扭扭的写着两个字——")
	novel_interface.show_character("ren_full","normal2")
	await novel_interface.show_dialog("『星尘』……？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","panic",0.25)
	await novel_interface.show_dialog("啊——！！！", "小女孩")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她恍然大悟的跳了起来，猫耳差点扎到我。")
	novel_interface.show_character("ren_full","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("stardust_small","panic",0.25)
	await novel_interface.show_dialog("那不是我的名字吗！！！", "小女孩")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("你是那种挂着写了名字的小纸条然后被不负责任的父母丢到孤儿院的婴儿吗？！")
	novel_interface.show_character("ren_full","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("stardust_small","tear",0.25)
	await novel_interface.show_dialog("我、我……\n呜……", "星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她的眼角挂着泪花，鼻子一抽一抽的，好像随时要哭出来的样子。")
	novel_interface.show_character("ren_full","perspire1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("stardust_small","tear",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊，我不是那个意思……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她低头不语，似乎在试图平复自己的情绪，我也终于冷静了下来——")
	await novel_interface.show_text_only("这个小女孩会突然出现在金库里，应该是我刚才触摸货柜中的陨石造成的。")
	novel_interface.show_character("ren_full","upset")
	await novel_interface.show_dialog("（这孩子……是魔女吗？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那块陨石不是4000多年前砸到地球上的吗，这家伙的装束怎么看都不像是来自那个年代。")
	novel_interface.show_character("ren_full","normal2")
	await novel_interface.show_dialog("（或者是类似海因里希那种状况……）\n（这身服装也是『那位大人』的杰作？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("stardust_small","normal1")
	await novel_interface.show_text_only("不对，她头上的那对猫耳耳机，我记得似乎在购物网站上看到过类似的。")
	novel_interface.change_expression("normal2")
	await novel_interface.show_text_only("居然和她这身还挺搭……")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("另外这孩子说话的方式，更像是那种常年沉迷各种社交软件的小鬼，完全不像古代人。")
	await novel_interface.show_text_only("是由于某种原因失忆了吗？总之一会让安妮在失踪儿童名录里查查看吧……")
	await novel_interface.show_text_only("我还在为后续工作感到头疼，她却不知什么时候走到我面前，轻轻抱住了我。")
	novel_interface.show_character("ren_full","timid")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("见我没有抗拒，她渐渐抱紧，把小脸蛋贴在我的肚子上，像小动物的幼崽一般，生怕我走掉不管她。")
	novel_interface.show_character("ren_full","timid")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("stardust_small","tear",0.25)
	await novel_interface.show_dialog("我不管嘛，你不许走……", "星尘")
	await novel_interface.show_dialog("明明约好了……", "星尘")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她一边抽泣一边小声嘟着，好像很伤心的样子。")
	await novel_interface.show_text_only("我轻轻拍了拍她的小脑袋，淡蓝色的头发又滑又软像丝绸一样。")
	await novel_interface.show_text_only("在灯光下还泛着一层若隐若现的紫色光晕……")
	novel_interface.show_character("ren_full","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("stardust_small","tear",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（她是把我当成其他人了吧？）\n（真让人没办法……）", "小怜")
	await novel_interface.show_dialog("好啦好啦，我知道啦……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("抱歉，其实我什么都不知道！\n谁来教教我怎么哄小孩啊！")
	novel_interface.show_character("ren_full","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("stardust_small","tear",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("乖~我不会走的，但一会你要配合一下，就说是和我一起来的，明白了吗？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她仍旧把头埋在我的衣服里，微微点了点头。")
	novel_interface.show_character("ren_full","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("stardust_small","tear",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（……不会是把我当成妈妈之类的了吧？）", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("（我是男孩子的时候，明明连初吻都没……）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("按照事前的约定，如果出现魔女，在确定对方没有敌意后，要尽快给侍者新的催眠暗示以免穿帮。")
	await novel_interface.show_text_only("我哄着这个小家伙慢慢松开手，将那个金平糖一样的颗粒状物体塞进了安全的地方。")
	await novel_interface.show_text_only("保险起见，我再度打开了0812号货柜，陨石依旧好端端的躺在里面。")
	novel_interface.show_character("ren_full","normal2")
	await novel_interface.show_dialog("（并没有像青金石柱那次一样碎掉吗……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("我抬起头，忽然发现监控摄像头的状态灯正在快速的一亮一灭，那是安妮和我约定的紧急信号。")
	novel_interface.show_character("ren_full","serious")
	await novel_interface.show_dialog("发生什么状况了！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不，更严重的问题是，因为刚才的走神，我不知道这个紧急信号已经持续多久了。")
	await novel_interface.show_text_only("这时，走廊尽头突然传来“叮”的一声。")
	novel_interface.show_character("ren_full","serious")
	await novel_interface.show_dialog("该不会……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金库电梯厚重的大门正在缓缓打开。")
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("糟了！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一手拉着星尘，一手拎起鞋和手包向电梯口飞奔过去。")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("（要来不及给侍者新的暗示了，忽然多了个小孩我可怎么解释啊啊啊！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然而一切发生的太快，我刚赶到侍者旁边，电梯大门就渐渐打开了。")
	await novel_interface.show_text_only("从电梯中走出四个人，最前面的是一名身着军官服装的女性。")
	await novel_interface.show_text_only("她的身后，两名穿着蓝色迷彩作战服的壮汉一左一右的架着表情复杂的赌场经理。")
	await novel_interface.show_text_only("领头的女生看着已经恢复神智的侍者和刚气喘吁吁跑过来的我，有些没精打采的说道——")
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("我是马萨达国防军卡拉卡尔营的艾米莉欧·史维特莱德少尉，正在执行海防任务。", "女性军官")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这位马萨达少尉皮肤白皙，右面的瞳孔是蓝色，而左面则是橙黄色。")
	novel_interface.show_character("ren_full","stare")
	await novel_interface.show_dialog("（这是……异色瞳？还是第一次见到……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","stare")
	await novel_interface.show_dialog("你们正处于马萨达军事管控的海域，有情报表示这艘船上有萨蒙顿条约规定的违禁品……", "艾米莉欧")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("关于“搜查权”之类的废话刚才在上面已经和船长说过一遍了。", "艾米莉欧")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("有什么不满的话，可以向马萨达军事委员会或者外面的武装巡逻艇进行申诉~", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("年轻的少尉一边不耐烦的说着国际法规定的“权力声明”，一边若无其事的给手枪上膛。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("所以呢，请你们配合一下——", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她使了个眼色，身后的两名士兵就架着瘦弱的经理径直向保管箱走去。")
	novel_interface.show_character("emilio","speechless")
	await novel_interface.show_dialog("喂，金库里就你们两个吗？\n刚才做什么呢~", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","normal1")
	await novel_interface.show_dialog("（我们……两个？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我瞄了一眼小星尘，她无辜的眨了眨眼睛。")
	await novel_interface.show_text_only("此时那名侍者已经从催眠中觉醒，正盯着手中的筹码看的出神，我的心一下子提到了嗓子眼。")
	novel_interface.show_character("ren_full","sob")
	await novel_interface.show_dialog("（不是说催眠会让大脑自动补充过程和细节吗？能不能行行好把这孩子也补进去……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("他忽然面颊一红，额头开始冒出汗来，好像刚想做什么坏事就被抓包了的样子。")
	await novel_interface.show_dialog("没、没没！", "侍者")
	await novel_interface.show_dialog("真、真的，没做什么……！", "侍者")
	novel_interface.show_character("emilio","speechless")
	await novel_interface.show_dialog("……", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("…………", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("他到底脑补出了什么情节啊？？！")
	await novel_interface.show_text_only("而且你没看见这里还有位小朋友吗！")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("哦——？", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧露出一副玩味的表情，不屑的看了看侍者的跨下，一步一步逼近到他身前。")
	await novel_interface.show_text_only("后者则很配合的两眼一直盯着她手里的枪，好像快要吓尿出来的样子。")
	await novel_interface.show_text_only("艾米莉欧对她冷冷的“呵”了一声，转过身来，微笑的看着我。")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("这位小姐，您的证件~", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("啊？\n……哦哦！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我连忙打开手包翻找，SID为这次行动力给我设计了好几个伪造身份。")
	await novel_interface.show_text_only("如果遇到马萨达方面的盘查应该用的身份是……\n我抽出了对应的那张橙色身份卡。")
	await novel_interface.show_text_only("她将身份卡在随身的设备上扫了一下，随即眉毛微微扬起。")
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("国际医疗救援组织……", "艾米莉欧")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("实习护士？\n哈哈哈，居然还有这种职位啊？", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不好意思啊，我只接受了三天的临时医护培训。")
	await novel_interface.show_text_only("而且考核项目居然是给自己肌肉注射中亚地区的疫苗！")
	await novel_interface.show_text_only("考核那天，我拿着注射器在大腿上犹豫了一个多小时，每次都在刚要扎到表皮的时候就下不去手了。")
	await novel_interface.show_text_only("终于在某次刚刺下去的时候，胸部的扬声器忽然传出一声尖锐的噪音——")
	await novel_interface.show_text_only("我被突如其来的声音吓了一跳，瞬间把针头插进去了三分之二，居然就这么通过了考核。")
	novel_interface.show_character("ren_full","wry_smile")
	await novel_interface.show_dialog("（后来那帮人对着那段录像嘲笑了好久……）\n（她们都是虐待狂吗！？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("看你这身打扮，是哪家的大小姐被NGO的宣传片洗脑了？", "艾米莉欧")
	await novel_interface.show_dialog("……还是说想增加点资历凑大学学分？", "艾米莉欧")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("嗯，你看起来不像那么有上进心的样子。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","wail")
	await novel_interface.show_dialog("（就这么明显吗！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧忽然凑到我耳边，用低沉的声音说道。")
	await novel_interface.show_dialog("交战区可不是给你这种小孩过家家的地方哦……", "艾米莉欧")
	await novel_interface.show_text_only("我有些吃惊，她却忽然转换回刚才的笑脸，拍了拍我的肩膀。")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("开玩笑，开玩笑啦~\n说不定到时候我们还得靠你呢！", "艾米莉欧")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾米莉欧顺手给我套上了一个蓝色的手环。")
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("这个别摘掉，楼上所有人都在接受检查，戴着它说明你已经通过了。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_full","panic")
	await novel_interface.show_dialog("（只扫了一下身份卡就算通过了吗？）\n（而且，更诡异的是……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我困惑的望着正朝艾米莉欧做鬼脸的小星尘。")
	await novel_interface.show_text_only("这些人都……看不见她？")

	print("=== 星尘降临篇第6话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
