# bathophobia_ep12.gd - 深海恐惧篇第12话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep12_script()

func play_script():
	pass

func bathophobia_ep12_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/CauseAndEffect.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("当然，我也不能完全确定『那位』的身份，就算他说谎我也无力分辨。", "海因里希")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("而且我总在想，就算一切属实……", "海因里希")
	await novel_interface.show_dialog("真正高阶的存在，应该是不会如此在意人类这么弱小的物种的。", "海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("从另一个尺度思考，『那位』很可能只是自己族群中一个喜欢用放大镜烧蚂蚁的小孩。", "海因里希")
	await novel_interface.show_dialog("而蚂蚁们则认为这是神的惩戒，从此便对那束强光背后的黑影顶礼膜拜。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("哈，哈哈……", "拉斐尔")
	novel_interface.character_dark()
	await novel_interface.show_text_only("拉斐尔意味深长的笑了笑。")
	novel_interface.character_light(0.35,"mock")
	await novel_interface.show_dialog("这么说的话，我倒是很认同。", "拉斐尔")
	await novel_interface.show_dialog("人们俯首跪拜祈求禱告的对象……所定制的第一条戒规就像小孩子一样任性呢。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("虽然并没有清晰的表明意志，但以『那位』的恶劣个性来看，故意将她们卷入也不是不可能——", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希对拉斐尔说这句话的时候，视线指向了我和安妮。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("……我们？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("安妮曾经来过这里，并且她消失的那段时间，很有可能就是在这个空间里吗……", "拉斐尔")
	await novel_interface.show_dialog("天空酒店事件之后，『十字玫瑰』的情报组很快就查出了安妮的身份，但当时还判断是复制体。", "拉斐尔")
	await novel_interface.show_dialog("后来与SID共享的情报交叉比对才知道……她消失了7年之久。", "拉斐尔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("heinrich_battle","speechless",0.25)
	await novel_interface.show_dialog("『十字玫瑰』……Rosenkreuzer？", "海因里希")
	await novel_interface.show_dialog("那不是我和几个女炼金术士讨论交流研究成果的秘密结社吗，现在成为情报组织了？", "海因里希")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("看来我还是留下了一些有趣的“遗产”嘛。", "海因里希")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("海因里希露出得意的笑容，一旁的拉斐尔则似乎突然想通了什么。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("怪不得……『十字玫瑰』那句传承至今的问候语，在当年的环境下显得对教会太过不敬了。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("——“愿玫瑰在你的十字上绽放”", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("“玫瑰”指的是女炼金术士……不，仅仅是代表女性吧？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("虽然不明白，但感觉好厉害……", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("总之你们说的『那位』，是个很糟糕的家伙吧？", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("看到被吓坏的安妮，我的内心升起一股愤怒。")
	novel_interface.character_light(0.35,"solemn")
	await novel_interface.show_dialog("随随便便强迫别人签订契约，还把我们带到这种奇怪的地方。", "小怜")
	await novel_interface.show_dialog("更过分的是，不知道那家伙做过什么过分的事，给安妮留下了这样的阴影……", "小怜")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("被我遇到的话，一定打扁他！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("……", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她们突然安静下来，像看笨蛋一样看着我。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("你、你们这么盯着我干嘛……？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("……还真像你这个笨蛋会说出的话呢。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("如果是主人的话，我倒是十分期待。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("唔…所以说，我们现在要怎么回去啊……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("现在恐怕不行了，虽然在这个空间内没有感觉，但我们正在被转移至契约的任务地点。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("任务……什么任务？我可以拒绝吗！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("简而言之，我的契约是要守护地球上十个特定的区域。", "海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("虽然不情愿，但不得不承认……如果没人去做的话往往会引发无法挽回的灾难。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("十个区域对应的是『生命之树』的十个圆环吗？", "拉斐尔")
	novel_interface.character_dark()
	await novel_interface.show_text_only("拉斐尔抬头看着天上的树状图腾，唯一发出红光的那个圆环。")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("那个位置是……Yesod，代表万物的基础、神的创造力，也可能是『生命的基础』。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("我也没去过那个位置，但一旦进入这个领域，我们的目的地就是不可改变的。", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这种根本不容拒绝的风格，突然令我想到了一个熟悉的家伙……")
	await novel_interface.show_text_only("我摸了摸胸口。")
	novel_interface.show_character("ren_battle","speechless")
	await novel_interface.show_dialog("（奇怪，莉琉居然到现在都没有联络我……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到我们的对话，安妮似乎更加慌张了。")
	novel_interface.show_character("anne_normal","upset")
	await novel_interface.show_dialog("不可以……不可以一直在这里……", "安妮")
	await novel_interface.show_dialog("『那家伙』会把每个人都吞噬掉……", "安妮")
	await novel_interface.show_dialog("永远都无法离开……", "安妮")
	await novel_interface.show_dialog("不要、不要——！", "安妮")
	novel_interface.character_dark()
	await novel_interface.show_text_only("安妮紧紧抱紧了我，我有些手足无措。")
	novel_interface.character_light()
	await novel_interface.show_dialog("我不要一个人……", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","upset",0.25)
	await novel_interface.show_dialog("（再这样下去不行……）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮现在，像极了我以前在医院里见过守卫埃癸斯边境的士兵创伤后应激障碍发病的样子。")
	await novel_interface.show_text_only("等等，医院……，\n我……住过医院……？")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("（不、现在不是想这些的时候……）", "小怜")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("我们有办法离开这里吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希摊开手摇了摇头。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("不可能，某种意义上人类只是『那位』的奴隶……", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("带我出去，小怜——！", "安妮")
	await novel_interface.show_text_only("安妮大叫着抓紧我胸前的衣服，面颊上满是泪水。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("不行，必须快点离开——！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("随着我爆发出的喊叫，四周的金色图腾开始崩裂。")
	await novel_interface.show_text_only("咔——咔——咔——")
	await novel_interface.show_text_only("仿佛玻璃一般在虚空中破碎。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("——？？", "海因里希")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/CauseAndEffect_collapse.png")
	await novel_interface.show_text_only("在海因里希眼中，如多米诺骨牌一般碎裂的图腾，不住地向虚空中的四人身上坠落。")
	await novel_interface.show_text_only("触碰到黑发少女的瞬间，化成了轻飘飘的雾气。")
	await novel_interface.show_text_only("周围的空间开始折叠扭曲成细碎的矩形，矩形再次分裂，形成一条条分形的立体空间。")
	await novel_interface.show_text_only("平静的空间瞬间充满了大量的几何图形，似是卷起狂风，众人脚下唯一“地面”也不再稳定。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("这是……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Fabiola/white_bg.png")
	await novel_interface.show_text_only("海因里希的话还未说完，最后一块金色图腾也出现了裂缝。")
	await novel_interface.show_text_only("众人在虚空中向下坠落。")
	await novel_interface.show_text_only("金发少女惊讶的瞳孔之中，映射出了另一种白色。")
	await novel_interface.show_text_only("——一片纯白的光。")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	await novel_interface.show_text_only("小怜等人消失瞬间，监控室前据称可以阻绝电磁狙击步枪冲击的防弹玻璃出现了裂痕。")
	await novel_interface.show_text_only("根据安保协议，特勤队立刻安排元老院成员从预备通道撤离了现场。")
	await novel_interface.show_text_only("电子屏幕前，依然深处方舟基地的莉琉正在接受元老院的问话。")
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("实验品和实验对象全部消失……", "华音泷")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("怎么，诸位似乎很吃惊？", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉的声音不疾不徐地从通讯器中传出。")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("空间异变形成性模拟实验报告第三部分里，已经提到过这种可能了。", "莉琉")
	await novel_interface.show_dialog("异质物坍缩本身就有概率将周围最多三十米内的任何物质卷入异变空间。", "莉琉")
	await novel_interface.show_dialog("再加上小怜特殊能力的影响，参与实验的拉斐尔和安妮被一道卷入异空间的概率也会上升。", "莉琉")
	await novel_interface.show_dialog("虽然实验场地内配置了遮断性防护层。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("但是从结果看来，即使现在最先进的材料，对这种级别引力的阻断性还是远远不够啊……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("观察室内众人陷入了短暂的沉默。")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("哈哈哈，现在造成了可能引发外交问题的后果，你却很镇定啊。", "布莱特")
	await novel_interface.show_dialog("以你所见，老戴克斯能容许自己的孙女失联多久？", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("不必担心。", "莉琉")
	await novel_interface.show_dialog("以过往小怜出入异变空间的记录来看……", "莉琉")
	await novel_interface.show_dialog("如无意外，二十四小时内，她们将会离开异变区域并随机出现在新丰州的某一处。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("哈，希望别出什么意外~", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("但这样一来，实验数据说不定会被污染……", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("她们三人都随身携带了记录设备，异变区域内发生的一切，都会被如实记录的。", "莉琉")
	await novel_interface.show_dialog("这也是一直以来我们获取异变区域情报的方式。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("激活异质物时的数据记录呢？", "基尔斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("通讯器中闪过一道极轻的杂音。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("已经梳理完毕。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("随着众人面前的荧幕上开始刷新内容，元老院成员情绪逐渐平静下来。")
	await novel_interface.show_text_only("只有#C博士依旧沉默不语。")
	await novel_interface.show_text_only("他并没有和其他元老一起撤离，而是正在布满巨大裂痕的观察窗后，看着下面实验台中央的莉琉。")
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("小猫咪要是走丢了，落入别人手中，那可就……", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("那样的话，正好可以用作『伊利安索斯号』的测试对象——", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("哎呀呀，看来莉琉阁下对自己的人，也并没有想象中那么温柔啊~", "#C")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("哔——")
	await novel_interface.show_text_only("注意到通讯联络，站在观察荧幕前的爱衣立即接通了电话。")
	await novel_interface.show_dialog("爱衣，能追踪到小怜的芯片位置吗？", "莉琉")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("很讨厌啊~几分钟前突然失去了信号。", "爱衣")
	novel_interface.character_dark()
	await novel_interface.show_text_only("爱衣咬着手里的记录笔，啧了一声。")
	novel_interface.character_light(0.35,"stare")
	await novel_interface.show_dialog("奇怪，芯片自带的玻尔兹曼发生器就算在异空间内也能确定小怜大致范围，从来没丢失过信号……", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("卫星集群是不可能突然丟失信号的，难道小可爱被高温瞬间蒸发了……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……喂！", "莉琉")
	await novel_interface.show_text_only("通讯另一侧的莉琉展现出一丝罕见的焦虑。")
	await novel_interface.show_dialog("好像有点麻烦……底层能拍摄到真实场景的摄像机最后拍到的画面是小怜打碎了青金石柱。", "莉琉")
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("真是个冒失的孩子啊~", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("然后所有成像设备——包括光学、热成像和微波成像的讯号同时出现了异常。", "莉琉")
	await novel_interface.show_dialog("再次恢复的时候，她们三人都不见了。", "莉琉")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("一定发生了不得了的事情……\n可恶，居然收集不到数据！！", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("按照计划，如果带回了生命体，小怜必须在光学迷彩解除前带对方进入安全通道。", "莉琉")
	await novel_interface.show_dialog("（这样才能配合伪造异常空间数据，向元老院隐瞒她和拉斐尔的真实情况。）", "莉琉")
	await novel_interface.show_dialog("实验过程中采集到了两组数据，一组看上去和贝阿特丽切出现时的相位波动十分接近。", "莉琉")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("所以，召唤实验成功？", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉的语气变得严肃。")
	await novel_interface.show_dialog("但是另一组时空波动的数值，却无法匹配到相似的特征……", "莉琉")
	await novel_interface.show_dialog("推测包括召唤出的那个人在内的所有人，应该全部被卷入了这个不明区域。", "莉琉")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("呀啊~", "爱衣")
	novel_interface.character_dark()
	await novel_interface.show_text_only("爱衣瞬间爆发出了兴奋的声音。")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……具体内容已经通过加密通道传回SID了。", "莉琉")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("小怜总是会给我带来惊喜呢~", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("总之，继续追踪她的位置。", "莉琉")
	await novel_interface.show_dialog("三十分钟内，我需要确定分析报告。", "莉琉")
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("明白。", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣面前巨大的屏幕上，原本显示着少女位置的标识旁，赫然是鲜红的——")
	await novel_interface.show_text_only("Offline—")
	
	print("=== 深海恐惧篇第12话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
