# bathophobia_ep11.gd - 深海恐惧篇第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep11_script()

func play_script():
	pass

func bathophobia_ep11_script():
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("『现实』是什么？")
	novel_interface.change_background("res://assets/images/bg/Baizhu/game.png")
	await novel_interface.show_text_only("我们所认为的现实，或许只是一个线上游戏。")
	await novel_interface.show_text_only("角色们在被登录时醒来，被下线时沉睡，被删除时死亡。")
	await novel_interface.show_text_only("却渐渐产生了拥有『灵魂』的错觉。")
	await novel_interface.show_text_only("理所当然地觉得自己被控制做出的种种行为，完全是出于『自由意志』。")
	await novel_interface.show_text_only("公式、定律、语法、守则……在获得自由之前，每个角色都要被灌输这些不知由谁制定的游戏规则。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/unknowm.png")
	await novel_interface.show_text_only("即使某天，天空中出现了因渲染故障而撕裂的巨大马赛克像素色块——")
	await novel_interface.show_text_only("角色们也不会承认那是『未知』，而是编造各种神话或信仰来解释。")
	await novel_interface.show_text_only("因为承认『未知』意味着无法否定那最让人无法心安的可能——")
	await novel_interface.show_text_only("可能所谓『现实』，只是一种幻觉。")
	await novel_interface.show_text_only("一场梦。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/CauseAndEffect.png")
	await novel_interface.show_text_only("我慢慢睁开双眼，发现自己身处一片朦胧的世界。")
	await novel_interface.show_text_only("雾气缭绕中，一串串水珠诡异的悬浮在半空。")
	await novel_interface.show_text_only("我伸手去触碰，那些“水珠”立刻消散于无形。")
	await novel_interface.show_dialog("这里是……", "小怜")
	await novel_interface.show_text_only("我正站在某个平面上，并且能感到重力，然而低头却看不到地面，视觉有产生一种奇妙的下坠感…")
	await novel_interface.show_text_only("周围的背景噪音掺杂着某种特殊的异响，但在没有参照系的空间无法判断方位。")
	await novel_interface.show_text_only("我抬头，看到上空漂浮着一个树状的镂空图腾。")
	await novel_interface.show_text_only("图腾在天空中像毯子一样展开，发着微微的亮光。")
	await novel_interface.show_text_only("图腾上的10个圆环缓慢的转动着，其中一个圆环散发出淡红色。")
	await novel_interface.show_text_only("随后，我的脚下也展开了由巨大的线条和铭文构成的图形，构成了概念上的『地面』。")
	await novel_interface.show_text_only("仔细观察，地面上是与天空一样的图腾，只是比从远处看起来大得多。")
	await novel_interface.show_text_only("被以某种规则连接起来的圆环，每一个直径都超过5米，图腾中穿插着不知年代的铭文。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("（我是在…做梦吗？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("之前的训练中有学习过识别幻觉或梦境的方法。")
	await novel_interface.show_text_only("那个重要的『问题』是什么来着……")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("——我，是怎么来到这里的？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("记忆慢慢开始浮现，刚才我们还在方舟基地，然后似乎突然开始坠落，然后……")
	await novel_interface.show_text_only("这里，不是梦境。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("（和刚才出现的那个女生有关吗？）", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（上来就叫我“主人”，而且还……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("啊——\n不对！才不是回味那种画面的时候！")
	await novel_interface.show_text_only("安妮呢？还有拉斐尔？！")
	await novel_interface.show_text_only("她们两个……应该和我一起被卷进来了！")
	await novel_interface.show_text_only("我在雾气中紧张的四处张望，忽然一个温暖的身体从身后抱住了我。")
	await novel_interface.show_dialog("不要紧张，主人——", "金发少女")
	await novel_interface.show_text_only("出现了！\n那个一丝不挂的家伙正从后面搂着我的腰！")
	await novel_interface.show_text_only("我很想质问她，又不知该不该回头……")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("（而且“主人”这个称呼……）\n（让我想起了动画片里很多奇怪的角色啊！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她似乎在摸索着什么，手掌划过我的腰，最后停留在我那不管如何训练都长不出肌肉的小腹。")
	await novel_interface.show_text_only("在寂静的环境中，她的呼吸轻拂着我的头发，我的心跳不断加快……")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("（她、她要干什么？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哦~？","金发少女")
	await novel_interface.show_text_only("她好像发现了什么有趣的事情，手掌轻轻一按，我的肚子立刻不争气的发出“咕—”的一声。")
	await novel_interface.show_text_only("在本安静的环境中，这个声音格外明显。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("（诶？？为什么……）", "小怜")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("（感觉……好丢人啊啊啊啊！！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我拨开她的手，少女步伐轻巧的绕到我面前，用好奇的眼神打量着我。")
	await novel_interface.show_dialog("原来主人的身体也被改造过？\n……真是完美的炼金产物啊！","金发少女")
	await novel_interface.show_text_only("我刚想捂住眼睛，发现她已经穿好了衣服。")
	await novel_interface.show_text_only("等等，她刚才说我的身体被改造过？！\n另外她这身装束……")
	await novel_interface.show_text_only("就算只用肉眼观察，也能看出海因里希的服装是以非常先进的材料制作的。")
	await novel_interface.show_text_only("无论质感还是设计，都不是16世纪的工艺可以达到的……不，就算是现在也不一定能做到。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("（难道莉琉的情报有误？）\n（还有，她是如何知道我身体的事情的？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在我思考要先问哪个问题的时候，衣服的帽子突然被人用力向后扯。")
	await novel_interface.show_text_only("拉斐尔把我拉到身后，挡在了我和金发少女之间。")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("你这家伙，到底是谁？！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("——哦？", "金发少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("金发少女看着拉斐尔，露出轻蔑的微笑。")
	novel_interface.character_light()
	await novel_interface.show_dialog("你是问名字吗？\n那种东西我用过上百个~", "金发少女")
	await novel_interface.show_dialog("不过告诉你也无妨，海因里希·昆哈特——这就是我的“契约”之名。", "金发少女")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("别开玩笑了！", "拉斐尔")
	await novel_interface.show_dialog("姑且不说所有历史记录中，海因里希都是男性——", "拉斐尔")
	await novel_interface.show_dialog("就你这身轻浮的打扮……\n你是错误的理解了内衣的定位吗？", "拉斐尔")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("海因里希是有名的炼金术士，绝不是你这种毫无廉耻、随意叫别人主人、并且……说什么精华……", "拉斐尔")
	novel_interface.character_dark()
	await novel_interface.show_text_only("拉斐尔的脸可疑地红了一下。")
	novel_interface.character_light()
	await novel_interface.show_dialog("……你到底是什么人！", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她们对峙时，我在拉斐尔身体的掩护下，情不自禁的从缝隙中观察海因里希。")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("（她上半身的衣服到底是什么材质……）\n（好惊人的包裹性！还能同时向不同的方向抖吗）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然间，海因里希与我目光相接，我低下头满脸通红的扯着裙角，不敢再看她。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("哦？我以为完美炼成了这幅躯体的主人，并不会对自己的作品产生动摇……", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不不不，我（以前）可是男孩子啊……")
	await novel_interface.show_text_only("海因里希说着拉了拉自己胸口的衣服。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("似乎比以前大了些……是主人的兴趣吗？", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔回头瞪了我一眼。")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("不！！我不是！我没有！！", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_text_only("我只是不小心打碎了萨蒙顿的国宝级文物……")
	await novel_interface.show_dialog("还有，别叫我主人啦……叫我小怜就行。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("小怜……？\n没想到如此伟大的您…居然有着这样可爱的名字。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("那么你呢？你真的是那个海因里希？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女犹豫了一下，看了看手腕上的数字，有点无奈的叹了口气。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("已经过去400多年了啊……", "海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("等等，她手腕上有电子表或者万年历之类的吗！？")
	novel_interface.character_light()
	await novel_interface.show_dialog("无论是研究、发表论文书籍还是行医，我确实一直都使用的是男性身份。", "海因里希")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("所以历史上能有如此记载也很正常。", "海因里希")
	await novel_interface.show_dialog("因为在我那个时代，大学不招收女生，教会也不准女人行医——", "海因里希")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("至于炼金术……哼哼，如果女性的身份去研究，很快就会被宗教法庭找上门吧？", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不知为何，最近听到这些种种对女性的压迫，我就有一种感同身受的愤愤不平。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("虽然想要处理掉那些“教廷的警犬”易如反掌，但凡夫俗子不值得我浪费宝贵的时间。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("好像……很厉害的样子……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔的表情也有些动摇。")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("等等，女生可以伪装成男孩子上大学吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我忽然很好奇她用了什么方法，说不定……")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("我只是剪短头发，伪造了几封推荐信，然后用假名混进了莱比锡大学。", "海因里希")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","smile",0.25)
	await novel_interface.show_dialog("只……剪短头发就可以吗？", "小怜")
	novel_interface.change_2nd_expression("wry_smile")
	await novel_interface.show_text_only("我又看了看她的胸部，400年前的人难道真的像电视剧里一样瞎到看不出女扮男装？")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("当时我刚10岁，大学入试题目太简单了。", "海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("海因里希不屑的笑了笑。")
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("打扰了！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("无论哪个时代，学霸都太可怕了！！")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("那你现在这身装束作何解释？", "拉斐尔")
	await novel_interface.show_dialog("海因里希是医生和炼金术士，但你的护具和武器明显是为了战斗配置的。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希微笑着退后一步。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("——哦，抱歉，这是我的疏忽。", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希右手按在胸前，随后她服装的表面开始浮现出碎片。")
	await novel_interface.show_text_only("蓝白色的缎带和各色晶石环绕在她的四周，围绕金发少女的身体发出光芒。")
	await novel_interface.show_text_only("青金色的光芒退却之际，海因里希的身上渐渐……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("渐渐……诶？")
	await novel_interface.show_text_only("拉斐尔冲到我面前紧紧的捂住了我的眼睛。")
	await novel_interface.show_dialog("够了！我明白了——", "拉斐尔")
	await novel_interface.show_dialog("你个暴露狂，快把衣服穿回去！！", "拉斐尔")
	await novel_interface.show_dialog("还有女裝癖，你看什么看！", "拉斐尔")
	await novel_interface.show_text_only("我明明什么都没看见！！")
	novel_interface.show_background("res://assets/images/bg/Baizhu/CauseAndEffect.png")
	await novel_interface.show_text_only("拉斐尔移开手掌的时候，海因里希已经恢复了刚才的装束。唉……")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("这是魔法战服，和主人身上的类似，只不过制造者是更上位的存在。", "海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("至于款式，可能是『那位』的恶趣味……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("『那位』？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("我曾经以炼金之法，制造了这个空间的『门』。", "海因里希")
	await novel_interface.show_dialog("但凡人窥视真理总要付出代价，『那位』将我的灵魂强行定下了契约……", "海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("海因里希的表情有些无奈。")
	novel_interface.character_light(0.35,"bored")
	await novel_interface.show_dialog("（嘟嚷）上次我明明已经把身体炸得完全粉碎，契约居然还能以新的肉体启动……", "海因里希")
	await novel_interface.show_dialog("真是阴魂不散……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("？", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("我正奇怪海因里希在说什么，安妮颤抖的声音突然从浓雾中传来。")
	await novel_interface.show_dialog("小怜——", "安妮")
	novel_interface.character_light(0.35,"solemn")
	await novel_interface.show_dialog("安妮？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我们循声跑过去，发现安妮正缩成一团蹲在地上全身不住的发抖。")
	await novel_interface.show_dialog("救、救我……", "安妮")
	await novel_interface.show_dialog("……我不要、不要……", "安妮")
	await novel_interface.show_text_only("我连忙上前安抚安妮，在我的手接触到她身体的一剎那——")
	await novel_interface.show_text_only("一股无形但柔软的东西迅速滑过了我的手背，并带着粘稠的热浪迅速远离。")
	await novel_interface.show_text_only("我打量了一下四周，并没有什么异常，只是海因里希有些吃惊的注视我。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("没事的，安妮！", "小怜")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("安妮？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("颤抖的安妮显然很不对劲。")
	await novel_interface.show_text_only("我能够理解对未知空间的担忧……但是四周空旷完全看不到敌人的样子。")
	await novel_interface.show_text_only("我只能抱紧安妮，尝试给她一些安慰。")
	await novel_interface.show_text_only("拉斐尔看到安妮的状态，转向海因里希。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("你刚才说的“这个空间”，是不是『因果之隙』？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("这是刻印在『生命之树』上的名字……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("『生命之树』？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("擅自把我们带到这种地方，你到底想做什么？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希耸了耸肩。")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("不是我。", "海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("事实上，你们本不可能出现在这里的……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("哎？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("除非是『那位』……或者更高位存在的意志。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("你说的『那位』究竟是……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("按照契约，我不能直呼其名，但『那位』的名字实在太多了。", "海因里希")
	await novel_interface.show_dialog("『真理』、『道路』、『门』。", "海因里希")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("从最初……到最终。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("……？！！", "拉斐尔")
	
	print("=== 深海恐惧篇第11话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
