# bathophobia_ep05.gd - 深海恐惧篇第5话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep05_script()

func play_script():
	pass

func bathophobia_ep05_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/baizhu_sleeping.png")
	await novel_interface.show_text_only("『灵魂』是什么？")
	await novel_interface.show_text_only("是记录着意识的某种能量，还是无法观测的量子态存在？")
	await novel_interface.show_text_only("或许『灵魂』仅仅是一种概念。")
	await novel_interface.show_text_only("就像物理学中『时间』的概念一样——")
	await novel_interface.show_text_only("只是一种幻觉……一场梦。")
	await novel_interface.hide_background() 
	await novel_interface.show_text_only("那么唯一的问题是——")
	await novel_interface.show_text_only("做梦的人是谁？")
	novel_interface.show_background("res://assets/images/bg/Baizhu/submarineDetector.png")
	novel_interface.change_music("res://assets/audio/music/Sonar.mp3")
	await novel_interface.show_text_only("南极辐合带区域，冰冷刺骨的寒意似乎拒绝着外界的一切的探究。")
	await novel_interface.show_text_only("海平面下6100米，深渊水层。")
	await novel_interface.show_text_only("在钛合金耐压外壳包裹下的深潜舱正在缓慢沉降。")
	await novel_interface.show_text_only("舱体的状态灯发出的微弱光线，射出不到10厘米就被周围的黑暗吞噬殆尽。")
	await novel_interface.show_text_only("毫无光线之处，空间也变得无法感知。")
	await novel_interface.show_text_only("一只色彩诡异的尖牙鱼试着撞击舱身，但没有收到任何回应。")
	await novel_interface.show_text_only("60兆帕的巨大水压时刻考验着深潜舱的极限强\n度。") #换行问题
	novel_interface.change_background("res://assets/images/bg/Baizhu/submarineDetector_Lighting.png")
	await novel_interface.show_text_only("突然，深潜舱的8组探照灯按照预设程序同时打\n开， 笔直的射出八条狭长光柱。") #换行问题
	await novel_interface.show_text_only("像刺入黑暗的长剑，突然爆发出灼目的光芒。")
	await novel_interface.show_text_only("一缕光线从几十厘米厚的观察窗射入，照亮了舱内沉睡着的少女。")
	await novel_interface.show_text_only("黑灰色的长发反射着淡蓝色的光泽，柔顺的披散在少女冰玉般透彻无暇的脸上。")
	await novel_interface.show_text_only("在她面前，操作台上的深度探测仪已经失效，深度显示还停留在1247M。")
	await novel_interface.show_text_only("外部探照灯的光芒逐渐暗淡，少女的身体周围却闪烁着一层不易察觉的银白微光。")
	await novel_interface.show_text_only("在足以承载人类任何恐惧想象的海洋深处，传来了一阵低沉悠远的声音。")
	await novel_interface.show_text_only("如同来自远古的召唤。")
	await novel_interface.show_text_only("沉睡的少女仿佛从母体中被唤醒。")
	await novel_interface.show_text_only("随之被唤醒的，是被压迫的眩晕感和无法克制的想要呕吐的欲望……")
	await novel_interface.show_text_only("这个深度已经远超4500米的设计安全线，潜水舱的金属外壳开始发出异响。")
	await novel_interface.show_text_only("少女的肺部迸发出压抑着的呛咳。")
	await novel_interface.show_text_only("起初有些呼吸困难，但在几次呼吸调整之后，她很快适应并稳定了下来。")
	await novel_interface.show_dialog("刚才的撞击……我好像晕过去了。", "少女")
	await novel_interface.show_dialog("还能正常呼吸，说明含氧量正常。", "少女")
	await novel_interface.show_dialog("从哈气看来……果然\n舱内已经接近0度了吗。", "少女")
	await novel_interface.show_dialog("主系统检查，准备冷启动\n识别信息：白烛。", "少女")
	await novel_interface.show_text_only("名为白烛的少女似乎并不担心低温可能对身体产生的影响，只是认真的检查着各个系统。")
	await novel_interface.show_text_only("这是她生来就具备的能力，最初还是婴儿的她被发现时，已经在冬日冰封的深山中过了一整夜。")
	await novel_interface.show_text_only("后来一系列的检查发现，这个奇迹般的小女孩能适应各种寒冷环境。")
	await novel_interface.show_text_only("成年人30秒内就会丧失意识的极端低温下，她可以始终保持正常体温，而且手掌还很温暖。")
	await novel_interface.show_text_only("直到养父将小白烛从孤儿院接走为止，那些医生也没能搞清楚原因。")
	await novel_interface.show_dialog("照明动力系统正常，传感器重启后也OK。", "白烛")
	await novel_interface.show_dialog("居然沉到6000米了……『那个东西』不可能在水压这么大的地方吧。", "白烛")
	await novel_interface.show_dialog("要节省电池返航……探照灯先关掉——", "白烛")
	await novel_interface.show_text_only("在探照灯熄灭前一刻，白烛用余光扫到观察窗外。")
	await novel_interface.show_dialog("什……", "白烛")
	await novel_interface.show_text_only("那令人惊异一幕，让少女瞬间寒毛倒竖僵在那里。")
	await novel_interface.show_dialog("那是……什么……", "白烛")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("探照灯熄灭前的瞬间，照亮了观察窗外一片巨型珊瑚状组织。")
	await novel_interface.show_text_only("一圈崎岖不平的血红色组织像瀑布般向中心点凹陷进去，形成巨大深邃的黑洞。")
	await novel_interface.show_text_only("可刚才扫描周围的区域，没有发现任何生物或地形构造。")
	await novel_interface.show_text_only("白烛立刻打开舱外的广角镜头，试图看清全景——")
	novel_interface.show_background("res://assets/images/bg/Baizhu/sea_eyeball.png")
	novel_interface.change_music("res://assets/audio/music/Wind.mp3")
	await novel_interface.show_text_only("屏幕上，白烛看到黑暗中一个横展开超过90米，长着触须的巨大而模糊的影子。")
	await novel_interface.show_dialog("怎么可能……", "白烛")
	await novel_interface.show_text_only("可以肯定那不是地形构造而是某种生物，在黑暗中可以观察到上面流动着的红色光斑。")
	await novel_interface.show_dialog("那是……眼球吗？", "白烛")
	await novel_interface.show_text_only("——如果，那种夸张的东西能被称作是“眼球”的话。")
	await novel_interface.show_text_only("观察窗正对着的凹陷黑洞正是眼球的瞳孔。")
	await novel_interface.show_text_only("因为太靠近巨大的物体而无法判断距离，好像随时会被吸进去一般。")
	await novel_interface.show_text_only("随着流动的光斑渐渐消失，在沉默的黑暗中，少女与不可名状之物对峙着。")
	await novel_interface.show_text_only("待渐渐适应黑暗环境，能看到屏幕上那个巨大的眼球本身发出的微弱红光，仿佛不透明的水母。")
	await novel_interface.show_text_only("眼球内充斥着似乎随时都会鼓动而出的组织物\n而每次鼓动都与少女的心跳重合。")
	await novel_interface.show_dialog("（冷静……要冷静！）\n（仔细想想……）", "白烛")
	await novel_interface.show_text_only("如果那真的是眼球的话，晶状体的位置应该对光线非常敏感。")
	await novel_interface.show_text_only("眼球之下，脉络膜结构的位置，在黑暗中闪烁着密密麻麻的白色光点。")
	await novel_interface.show_text_only("白烛注意到，屏幕中眼球的后方，连接着枝丫一般的触须。")
	await novel_interface.show_text_only("灰黑色的触须浸没在海洋深处，无法看到尽头。")
	await novel_interface.show_dialog("（……身体……动不了……）", "白烛")
	await novel_interface.show_text_only("——与其说是对峙，不如说是“那个东西”在单方面观察着少女。")
	await novel_interface.show_text_only("这种极具压迫感的审视而造成的恐慌，正在慢慢消磨少女的理智。")
	await novel_interface.show_dialog("哈……", "白烛")
	await novel_interface.show_text_only("——会被吞噬吗？")
	await novel_interface.show_text_only("深海带来的奇异感受，令她开始怀疑自己的存在。")
	await novel_interface.show_dialog("（是梦吗……）\n（是的话就快点醒来啊……）", "白烛")
	await novel_interface.show_text_only("然而身体依靠本能比意识先一步挣脱了枷锁。")
	await novel_interface.show_text_only("随着少女左手拉动操纵杆，潛水仓继续向眼球前进了一段距离。")
	await novel_interface.show_text_only("水流传来的波动显示“那个东西”似乎被惊动了。")
	await novel_interface.show_text_only("眼球紧缩了一下，观察着少女的下一步举动。")
	await novel_interface.show_dialog("喂？喂喂？", "白烛")
	await novel_interface.show_text_only("白烛摸到了自己佩戴的耳麦，尝试与信息台另一边的人沟通。")
	await novel_interface.show_text_only("然而这个深度的海水足以屏蔽任何电磁波，现在又不能去尝试水声通信。")
	await novel_interface.show_dialog("……", "白烛")
	await novel_interface.show_text_only("如果是她的话，一定会在耳机里拼命对我喊——\n“别再继续靠近了！”")
	await novel_interface.show_dialog("哈哈…为什么我会想这些……", "白烛")
	await novel_interface.show_dialog("“她”……又是谁？", "白烛")
	await novel_interface.show_dialog("这是……哪里……", "白烛")
	await novel_interface.show_text_only("在眼球注视的压力下，白烛的神志变得恍惚，真实和虚幻的边界逐渐模糊。")
	await novel_interface.show_text_only("少女的手紧张的在控制台上摸索着。")
	await novel_interface.show_text_only("很快，她找到了采样机械臂的操作器。")
	await novel_interface.show_dialog("（真的要……这么做吗……）", "白烛")
	await novel_interface.show_text_only("白烛逐渐稳住自己的心神，但依然有幻觉一般的光斑在她眼前出现。")
	await novel_interface.show_dialog("取样……然后，马上离开……", "白烛")
	await novel_interface.show_text_only("首先把探照灯都调往正前方")
	await novel_interface.show_text_only("动力系统设置到最大航速，方向是……后退。")
	await novel_interface.show_text_only("少女光是强撑着精神一步步的做完这些前置步骤，就已经快要晕倒过去。")
	await novel_interface.show_dialog("父亲，这就是……精神污染吗……\n就快要……", "白烛")
	await novel_interface.show_text_only("白烛慢慢的调整着操作器，机械臂逐渐展开，露出一个巨大的针头——")
	await novel_interface.show_dialog("抽吸模式……这种压强下只要一下……", "白烛")
	await novel_interface.show_text_only("机械臂一直向前伸出，直到针头刺入了眼球的玻璃体内。")
	await novel_interface.show_text_only("一瞬间，采样容器的饱和值就由0%升到了100%") #标点删除
	await novel_interface.show_text_only("眼球瞳孔的位置开始扭曲变形，如果声音能传递过来的话，应该会是刺骨的尖叫声……")
	await novel_interface.show_dialog("（是幻听吗……）", "白烛")
	await novel_interface.show_text_only("少女用尽最后一点力气，按下了序列执行按钮。")
	await novel_interface.show_text_only("根据刚才预设的程序，深潜舱的8个探照灯同时向眼球的瞳孔射出强光，螺旋桨也开始快速转动。")
	await novel_interface.show_text_only("随着刺激和强光，眼球向后退却，深潜舱逐渐远离并上浮……")
	await novel_interface.show_text_only("少女的心神终于耗尽，眼前一黑倒了下去。")
	
	print("=== 深海恐惧篇第5话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
