# bathophobia_ep19.gd - 深海恐惧症篇第19话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep19_script()

func play_script():
	pass

func bathophobia_ep19_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Snedronningen_Exhibition_Room.png")
	await novel_interface.show_text_only("我们顺着向下的阶梯，缓缓步入一间展览室。")
	await novel_interface.show_text_only("出乎意料的是，这里的电力设备和换气系统一直在运作，空气中并没有什么灰尘。")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("这么大的建筑里，居然连个人影都没有吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("但是系统还在运转……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("展厅内整齐排列的展台发出幽幽的灯光，远处来传来换气扇转动的声音。")
	await novel_interface.show_text_only("在这种昏暗的环境中，总觉得有未知的危险正潜伏在角落窥探着我们……")
	await novel_interface.show_text_only("我们小心的观察着周遭的环境，过了好久才将注意力落在那些展品上。")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("这是……标本吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看到玻璃展柜中，有机玻璃的支架正支撑着某种外形类似海洋生物的展品。")
	await novel_interface.show_text_only("这种生物的外壳光滑，呈半透明的白色，还有一根光滑的尾巴，看起来像是某种奇特的深海生物。")
	await novel_interface.show_text_only("有些好奇这种后背光滑透亮的生物，正面看起来是什么样子的……")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("——！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我绕到展台的另一侧，不禁倒抽了一口冷气。")
	await novel_interface.show_text_only("这个生物正面伸出八只粗大丑陋的爪子，每只爪子都像人类的手指一样有两个关节。")
	await novel_interface.show_text_only("在八只爪子中间，是纵向裂开的口器，里面密布着细小的倒钩，口器周围是类似肌肉的红色组织。")
	await novel_interface.show_text_only("这个造型让我不禁想起恐怖片里看过的会扑在人脸上抱住不放的外星生物。")
	novel_interface.show_character("ren_battle","wail")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","perspire",0.25)
	await novel_interface.show_dialog("真是变态的艺术品啊……", "拉斐尔")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("诶——这是像电影道具一样制作出来的吗？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("不，这确实是生物标本……", "拉斐尔")
	await novel_interface.show_dialog("这是战争时期基因改造的失败品，我小时候在萨蒙顿的研究所里见过很多。", "拉斐尔")
	await novel_interface.show_dialog("后来这些东西被证明没什么价值，某个时间点之后就被大规模废弃了。", "拉斐尔")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("不过这种东西一般都会作为生物废料处理。", "拉斐尔")
	await novel_interface.show_dialog("像这样如艺术品般，堂而皇之的展览……", "拉斐尔")
	novel_interface.change_2nd_expression("jeer")
	await novel_interface.show_dialog("这里的主人可是高出你好几个量级的变态啊~", "拉斐尔")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("——我才不是变态啦！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("只是这东西，长得确实有点……")
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("这里也是一个人都没有……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("是啊，整个基地就像一座空城，有些地方还有年久失修的痕迹。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","shout")
	await novel_interface.show_dialog("注意脚下！", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("哎？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一脚踩到了弹壳上，身体向展柜的方向滑倒，眼看头就要磕在柜台的尖角上——")
	await novel_interface.show_text_only("拉斐尔一个箭步上前及时的扶住了我。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("真是个麻烦的笨蛋……", "拉斐尔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","wail",0.25)
	await novel_interface.show_dialog("——好、好险！", "小怜")
	novel_interface.change_2nd_expression("wry_smile")
	await novel_interface.show_dialog("谢谢……拉斐尔。", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔用类似交谊舞的姿势抱住我，不得不承认这个动作真的好帅！")
	await novel_interface.show_text_only("拉斐尔松开揽在怀里的我，有点不好意思的咳嗽了一声。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Corridor.png")
	await novel_interface.show_text_only("离开展厅，我们来到一条金属甲板覆盖的走廊。")
	await novel_interface.show_text_only("这里的灯光明显更明亮，安静的气氛也更加诡异。")
	await novel_interface.show_text_only("但远处机械运转的白噪音说明了一点——")
	await novel_interface.show_text_only("这个基地并未陷入完全的沉睡。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("如果有人维持着系统的运作，那他为什么会对我们几个置之不理呢？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","smile",0.25)
	await novel_interface.show_dialog("如果对方抱有敌意的话，早就可以动手了……", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("突然我发现有个光点在黑暗中中移动，仔细一看才发现，是不远处的一只监控摄像头转向了我们。")
	await novel_interface.show_text_only("我朝着监控器挥了挥手。")
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("不好意思——那个，请问……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("你的姿势也太少女了吧。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔突然打断了我。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("喂，我说你们，别再这么鬼鬼祟祟的了！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("不对，并没有被窥视的感觉……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("（只是声音感应的监控装置吗？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这种根据声音锁定设备，已经被淘汰很多年了吧\n……只要一个小型的超声发生器就能使其瘫痪。")
	await novel_interface.show_text_only("监控装置还在运作，但它的背后却无法感受到任何“人类”的动作。")
	await novel_interface.show_text_only("我有些失望，发现拉斐尔还蒙在鼓里，于是用故作恐怖的语气幽幽说道——")
	novel_interface.show_character("ren_battle","uneasy")
	await novel_interface.show_dialog("说直觉……可能有些好笑……", "小怜")
	await novel_interface.show_dialog("但我觉得，这里可能……有人类之外的……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("——你、你想说有鬼吗！！", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔突然用异常升高的语调打断了我。")
	await novel_interface.show_text_only("发现我在故意吓人，拉斐尔有些气急败坏的想冲过来敲我的脑袋。")
	await novel_interface.show_text_only("躲避中我跌倒在地上，身上的温玉也掉了出来。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("不不不拉斐尔我不是这个意思——啊——阿嚏！ 我不知道你怕鬼……", "小怜")
	await novel_interface.show_dialog("好、好冷！！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("哼！", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看到失去温玉的保护被冻得缩成一团的我，拉斐尔才算有些消气。")
	await novel_interface.show_text_only("明明都到了基地内部，为什么还这么冷冷冷冷……")
	await novel_interface.show_text_only("我连忙拾起了温玉。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("奇怪，这个温度是不打算让基地里的人活动吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("仔细观察，发现墙角很多地方已经结冰了……")
	await novel_interface.show_text_only("让我恍惚间回想起某个在冰天雪地里求生的游戏……")
	await novel_interface.show_text_only("抓革命，促生产，搞好生产大自救……什么的，虽然游戏的结局很莫名其妙啦。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("（不对劲。）", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希把掌心贴在了墙壁上。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("别、别又在人家的地盘上搞破坏啊——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("真怕她顺手把承重立柱给拆出来……")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("不对。", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发的炼金术士表情严肃。")
	await novel_interface.show_text_only("从她手掌按着的区域，一道波纹般的气流顺着墙壁向四周扩散。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("怎么？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("……我们好像，被困住了。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("什么？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我连忙跑到走廊尽头，发现来时展览室的门并没有上锁。")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("不要随便吓人嘛……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一边捂着自己惊魂未定跳个不停的心脏，一边往刚才路过开着门的资料室走去。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room.png")
	await novel_interface.show_text_only("我来到了一间灯光明亮的资料室，这里的氛围比刚才的走廊好了很多。")
	await novel_interface.show_text_only("只顾着观察四周，完全没注意到地砖上裂缝的我又一下绊了个趔趄。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("你这家伙，注意点啊……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔站在资料室门口，一边看着我，一边盯着还在对走廊墙壁若有所思的海因里希。")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("等等，这间资料室里……有风？", "小怜")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("难道……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我试着把温玉放在桌子上，感受室内的温度。")
	await novel_interface.show_text_only("果然，这里和走廊完全不同……充足的暖气完全能让人忘记自己身处南极。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("哎……？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可是，刚才路过的时候，书架上的陈列好像…… 好像不是这样的？")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("（……是我记错了吗？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我挠了挠头，向门外走去。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("小心脚下——", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("知道知道，刚才我还在想呢，地上裂了那么大的一道缝居然也没人修……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一边说着，我一边留意着地面——")
	await novel_interface.show_text_only("地砖上没有任何破损和缝隙。")
	await novel_interface.show_text_only("光洁平整如镜面一般的大理石地砖，甚至连我的蓝白……")
	await novel_interface.show_text_only("发现了问题的我，立刻并拢了双腿。")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("果然不对劲。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("……怎么了小怜。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("呆在那里做什么？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("刚刚这里的裂缝……自己消失了？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我很确信，刚才是踢在一道裂缝边缘差点绊倒。")
	await novel_interface.show_text_only("原本应该有裂痕的地面。")
	await novel_interface.show_text_only("唯一开着暖风的资料室。")
	await novel_interface.show_text_only("书架上变换的物品摆放方式…….")
	await novel_interface.show_text_only("我的心扑通扑通扑通直跳。")
	await novel_interface.show_text_only("我小心翼翼的向前迈了一步。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("哎，你往裂缝里联是什么意思，是不是还想让我扶你……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔的态度让我差点产生错觉。")
	await novel_interface.show_text_only("但是身体却明确地告诉我，我脚下踩着的，是一片完整的地面。")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("……我想，我们所能观察到的恐怕不太一样。", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("为什么会这样……")
	await novel_interface.show_text_only("我不安地拿出对讲机，希望能联系上安妮和莉琉寻回一些安全感。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("——喂喂，安妮，安妮？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("对讲机中并没有回应，可能在地下没有信号了。")
	await novel_interface.show_text_only("注意到我奇怪的神情，拉斐尔和海因里希也进入了资料室。")
	await novel_interface.show_text_only("——这间，和刚刚路过时完全不同的资料室。")
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("不是我的错觉……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("这，不是刚才那个房间。", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("忽然，走廊外面传来了咯咯咯咯的怪声。")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("——什么人！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/xiaolianContact.png")
	await novel_interface.show_text_only("拉斐尔和海因里希立刻做出了迎战的准备。")
	await novel_interface.show_text_only("在我回头的瞬间，背后冲出一群手持冷兵器，神色诡异的人。")
	await novel_interface.show_text_only("而对方无神的双眼中露出的，是单纯的敌意——")
	await novel_interface.show_text_only("我握紧了手中的球棒……")
	print("=== 深海恐惧症篇第19话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
