# bathophobia_ep04.gd - 深海恐惧篇第04话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep04_script()

func play_script():
	pass

func bathophobia_ep04_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_lawn.png")
	await novel_interface.show_text_only("午后，我半躺在树荫下的草坪上，有些惆怅的看着天空。")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("唉——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一道阴影遮住了我的视线。")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("怎么啦小怜，唉声叹气的。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("是安妮啊……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮顺势坐在了我的旁边，将手里的纸袋放在膝盖上。")
	novel_interface.show_character("ren_uniform","timid")
	await novel_interface.show_dialog("——好甜的气味！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("锵锵~~新出炉的枫糖奶油饼干~\n要尝一块吗？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("虽然这么说，但是拆开包装的安妮并没容我拒绝的意思，直接将一块饼干塞进我的嘴里。")
	novel_interface.show_character("ren_uniform","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("唔……（嚼）\n还不错嘛！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("对吧！刚才路过家政课教室的时候，闻到了超——香的味道，我就偷偷找人要了一袋~", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("真好啊……安妮已经完全融入这里了。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("嗯？", "安妮")
	await novel_interface.show_dialog("小怜也很受欢迎啊~\n不少同学都和我打听你的情况呢……", "安妮")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("哎？是这样吗？")
	await novel_interface.show_text_only("相比起过去，现在的我还真是桃花运大丰收啊？")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("不过莉琉小姐禁止我们透露个人信息……所以我什么都没讲哦！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮一边咬着饼干，一边关心地看着我。")
	novel_interface.show_character("ren_uniform","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","smile",0.25)
	await novel_interface.show_dialog("……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("心情不好吗？", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("总觉得自己无法安心的面对这种平静的日常……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("不好吗？", "安妮")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("好像有什么重要的事，又不知从何做起\n这样无所事事又觉得忐忑不安……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("重要的事情……？", "安妮")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("比如说，未来会怎样……之类的。\n我现在这样的身体——", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("噗嗤——", "安妮")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("唔啊——！\n果然笑话我了吧！！！")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_text_only("讲出这种话，实在是有点太羞耻了！！！")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("那个，因、因为班上有那么多女生，会毫无顾忌的跟我聊各种话题……会很不好意思啊。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("哦~所以你才在这里一个人呆着？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮的表情似乎很轻松。")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("是吧，有时我会不自觉的玩起自己的头发或者调整一下内衣。", "小怜")
	await novel_interface.show_dialog("或者在执行任务的时候，很自然的穿短裙踩上高跟鞋……", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("可有时一旦意识到，就觉得我怎么能这样呢！！", "小怜")
	await novel_interface.show_dialog("我、我可是男孩子啊……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","relieve",0.25)
	await novel_interface.show_dialog("男孩子也没有问题啊？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮语气变得一本正经。")
	novel_interface.show_character("ren_uniform","perspire1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","relieve",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("诶？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("高跟鞋的话，最初就是路易十四发明的。", "安妮")
	await novel_interface.show_dialog("17世纪的时候，女性开始穿上高跟鞋，是为了让自己看起来更加阳刚呢。", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("高跟鞋是为了……阳刚？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("而且，苏格兰地区的男性可是会在正式场合穿短裙的！", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("好像是有听说过……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("嗯……据说还不用穿内裤！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我忍不住摸了摸自己的裙子。")
	await novel_interface.show_text_only("还好还好，我不是苏格兰人！")
	novel_interface.show_character("ren_uniform","perspire1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	await novel_interface.show_dialog("所以，小怜的打扮，明明就很有男子气概！", "安妮")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是、是这样的吗？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("唔……至于内衣嘛……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮的视线落在我胸口。")
	novel_interface.show_character("ren_uniform","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("是、是吧！这个东西不会有男子气概了吧！")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("……我觉得更像是运动时的负重训练用品。", "安妮")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("——啊？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("是啊~只要把增加的重量视作沙袋不就可以了吗？", "安妮")
	novel_interface.change_2nd_expression("shy")
	await novel_interface.show_dialog("虽然我是没有这种烦恼啦……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮有点失落的摸了摸自己。")
	novel_interface.show_character("ren_uniform","uneasy")
	await novel_interface.show_dialog("好像……也很有道理？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("——才没有啊！")
	await novel_interface.show_text_only("你以为我会被这种话说服吗？！")
	novel_interface.show_character("ren_uniform","uneasy")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("不管怎么说，在我心中，小怜是很棒的男孩子呢~", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"shy")
	await novel_interface.show_text_only("感觉脸颊一阵发烫。")
	await novel_interface.show_dialog("是、是吗？？", "小怜")
	await novel_interface.show_dialog("（感觉有点道理，又感觉自己被骗了……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着安妮天真友善的笑容，我……还是相信她吧。")
	await novel_interface.show_dialog("还真是无忧无虑的青春呢。", "莉琉")
	await novel_interface.show_text_only("莉琉的声音突然从我的胸部传出。")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("呀——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我被吓了一跳，赶紧捂住胸口，生怕被同学发现。")
	await novel_interface.show_text_only("虽然爱衣安慰我说时间长了就适应了，但这种麻麻痒痒的感觉绝对无法适应！！")
	await novel_interface.show_text_only("我从天空酒店回来后三番五次的要求把这块奇怪的芯片取出来。")
	await novel_interface.show_text_only("直到莉琉威胁我，再闹就在课上当着全班同学的面用我的胸部播放下课铃。")
	await novel_interface.show_text_only("这个恶魔！！呜呜呜呜……")
	await novel_interface.show_dialog("我可是为了你们，好一阵子没有休息过了。", "莉琉")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("难怪最近都没有什么任务呢~", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("哈、哈哈……\n安妮还真是积极……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("要不是因为元老院那边太难缠，早就应该搞定的…\n…", "莉琉")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("哎？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉的声音有些兴奋。")
	await novel_interface.show_dialog("很快你就会知道——", "莉琉")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("什么呀？神神秘秘的……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("先不说这个，训练时间马上就到了，你俩还悠闲的在校园里谈情说爱吗？", "莉琉")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("不是还有半小时吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("没收到邮件通知？\n最近你的体能训练课程增加了。", "莉琉")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("又要折磨人啊……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可以预想无数个精疲力竭瘫痪在床的夜晚了……")
	await novel_interface.show_dialog("折磨？哼哼——", "莉琉")
	await novel_interface.show_dialog("你的身体，早就属于我了哦。", "莉琉")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_text_only("不要说这种令人误会的话啊！！！")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	await novel_interface.show_text_only("莉琉面带笑意的切断了通讯。")
	await novel_interface.show_text_only("面对着冷冰冰的荧幕，她站姿挺拔。")
	await novel_interface.show_text_only("手持终端的数据被传送到荧幕背后的几人面前。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("关于项目预算……", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("已经向市政部门申请征用新东北地区的G-cans周围四十公里的无人区，统一划归SID管理。", "莉琉")
	await novel_interface.show_dialog("相应预算为14.9亿。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……", "众人")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("重设管道、配置交通及安保设施，均采用V级军事掩体标准。", "莉琉")
	await novel_interface.show_dialog("相应预算为6.2亿。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("…………", "众人")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("地下泄洪口并列改造，全区域电磁屏蔽，还有定制的自律武器系统。", "莉琉")
	await novel_interface.show_dialog("相应预算为5.32亿。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("………………", "众人")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("改造工期约为58天。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("元老院对这部分企划没有异议的话，SID会立刻开始执行。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("……有些……太贵了……吧……", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("这是三份开发报告中相对性价比最高的选择。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("……", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("我倒是不介意终止这项计划。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("不过，诸位的意见是……？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……", "众人")
	await novel_interface.show_text_only("众人的沉默并不意味着否定。")
	await novel_interface.show_text_only("电磁的噪音充斥着这间安静的房间。")
	await novel_interface.show_text_only("——荧幕上逐步闪现出“确认”的字样。")
	await novel_interface.show_text_only("直到所有人的影像下方，都出现了确认。")
	await novel_interface.show_text_only("莉琉满意地勾起嘴角。")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("那么——『方舟计划』启动！", "莉琉")

	print("=== 深海恐惧篇第04话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
