# bathophobia_ep07.gd - 深海恐惧篇第7话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep07_script()

func play_script():
	pass

func bathophobia_ep07_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_entrance.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("从莉琉的红色Coupe跑车上爬下来的时候，我只\n觉头晕目眩，双脚好像踩在棉花上")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("莉琉……呕……！\n你开车的方式！！也太夸张了吧！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("周末清晨，我像蘑菇一样缩在温暖的被窝里，安妮突然冲进我的房间强行将我挖了起来。")
	await novel_interface.show_text_only("半梦半醒状态下的我被塞进这辆跑车的时候，还在对刚才安妮的暴力采摘行径耿耿于怀。")
	await novel_interface.show_text_only("但体验了莉琉惊天动地的驾驶技术之后，我脑子里只剩下“活着真好”的念头了……")
	await novel_interface.show_text_only("虽然今天是进行『方舟实验』的日子，但真的超想申请病休。")
	await novel_interface.show_text_only("肚子疼了好几天了，可恶。")
	await novel_interface.show_text_only("还是想吐……呕！")
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("没事吧，小怜？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我朝安妮摆了摆手。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("还好，就是有点恶心，身体还在发抖……", "小怜")
	await novel_interface.show_dialog("一会回去的时候，我们别坐这辆车了可以吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的声音虚弱，用祈求的目光看向安妮。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("你这家伙，竟然还在发自内心的演绎着柔弱少女的设定吗？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我扶着墙缓慢回血的时候，身后传来了一个熟悉声音。喂喂，饶了我吧……")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("拉斐尔？你怎么……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("莉琉没告诉你吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("提前告诉她的话，就更不愿意来了~", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉一边像宠物商看着自己的商品一样看着我，一边轻描淡写的说道。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("一会儿小怜就要拜托给你咯~\n『萨蒙顿执行代表』——拉斐尔·戴克斯小姐。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("哎？！拜托她？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉笑了笑，带我们来到了『方舟基地』的入口。")
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("就是……这里？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("郊外的路边，混凝土结构的地下室入口，上面是仅允许单人通过的小门。")
	await novel_interface.show_text_only("周围一公里内没有任何建筑物，若不是刻着SID的标志，说里面住着奇怪的大叔都不奇怪。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("呵呵，进来就知道了——", "莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_elevator_overlook.png")
	await novel_interface.show_text_only("进门之后经过一条向下延伸的楼梯，我们进入了一台大型工业电梯。")
	await novel_interface.show_text_only("似乎是为了保证在极端环境下也能正常工作，电梯靠四个厚重的金属绞轮驱动，结构异常坚固。")
	await novel_interface.show_text_only("电梯稳定的下降，四壁和底部都能听到齿轮转动的声音。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_elevator.png")
	await novel_interface.show_text_only("昏暗的的灯光，排气孔、金属网和铆钉，处处透露着老式工业风格。")
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("这样极致追求稳定性的设计……之前在纽摩利达斯中央银行的地下金库里也见过。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("那种地方你也去过吗？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("这里是战前世界闻名的超级工程之一，修复起来可费了一番功夫。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉得意的介绍着。")
	await novel_interface.show_text_only("确实，虽然电梯在运行中，但就像踩在大铁块上一样稳定，感觉就算蹦起来也不会有任何抖动。")
	await novel_interface.show_text_only("从晕车中恢复过来的我正跃跃欲试的想蹦蹦看，发现拉斐尔瞪了我一眼。")
	await novel_interface.show_text_only("意识到自己的样子可能有点傻，我立刻收敛并露出抱歉的表情，她却不屑地转头看向观察窗。")
	await novel_interface.show_text_only("……也不知道她能在黑暗中看到什么。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("你干嘛一直看着我？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("居然恶人先告状！")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("呃……没想到萨蒙顿会派你来。", "小怜")
	await novel_interface.show_dialog("这次实验不是危险性还蛮高的吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("更重要的是，就我所知，这次试验有着两套剧本。")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("（不知道你拿到的是哪一个啊，大小姐！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我无助地望向莉琉。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("明面上说来，这是新丰洲和萨蒙顿两个学园都市的合作研究项目。", "莉琉")
	await novel_interface.show_dialog("目标是研究“空间异变”的成因并探索解决方案。", "莉琉")
	await novel_interface.show_dialog("双方都需要派出一个身份与能力合适、且值得信任的人作为实验样本。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("新丰洲的人选自然是因为在天空酒店的一系列愚蠢行为而暴露了身份的你——", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉用余光扫向我，一股巨大的威压让我直冒冷\n汗。")
	await novel_interface.show_text_only("我不是已经接受过惩罚了嘛……")
	novel_interface.character_light()
	await novel_interface.show_dialog("而贵族出身，现就读于御樱川的“普通人”拉斐尔则是志愿代表萨蒙顿参加实验的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("……志愿参加！？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("哼，『青金石柱』是萨蒙顿重要的历史文物，我可不想让你这个废柴把实验搞砸了。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("拉斐尔拥有加速细胞自愈的能力，这一点爱衣已经验证过了。", "莉琉")
	await novel_interface.show_dialog("不过按照贝阿特丽切的说法，想让这种能力最大化表达，最好的媒介就是小怜。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我回想起上次在天空酒店地下停车场，拉斐尔瞬间就治好了安妮的伤势。")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("所以说，拉斐尔应该是友军吧！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("哼，“啊~撑不住了快加血”之类没骨气的话确实跟你还很搭呢。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("怎么好像你很期待看到这一幕似的！！", "小怜")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("等等，这不是机密实验吗？\n拉斐尔是怎么知道……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("当然是我向戴克斯博士提出的了。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("由于见证了你复活贝阿特利切的情景，他老人家觉得此前与元老院的合作的方向是错误的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("是因为宗教方面的原因嘛……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("应该没这么简单——不过萨蒙顿暂时是倾向于SID 的，只要我们保证拉斐尔的安全。", "莉琉")
	await novel_interface.show_dialog("元老院并不清楚小怜和拉斐尔的真正能力，这是我们的优势。", "莉琉")
	await novel_interface.show_dialog("已经成为『魔女』的人，接触其他的魔导器不会有任何效果，这也是我们的方案可以成立的前提。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("还真是要感谢双方高层的配合了~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("……你确定我爷爷那个异想天开的家伙，不是被你刻意引导吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("你最好不要把你爷爷想得太简单了，他可不是随便挑选这件文物的。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("这样安排也是为了『真正的实验』能够顺利进行。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("嘁，要不是爷爷的命令……", "拉斐尔")
	novel_interface.character_dark()
	await novel_interface.show_text_only("拉斐尔含糊地嘟嚷了一句，眼神轻飘飘地掠过我。")
	novel_interface.character_light()
	await novel_interface.show_dialog("我才不会答应和这个女装癖演戏呢！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("可是戴克斯博士总说，家里最不听话的就是你呀~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("哼——", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("这么看来，萨蒙顿其实是对青金石柱的原主人——海因里希感兴趣？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("加油啊，小怜！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("元老院想瞒着SID继续和萨蒙顿进行人造魔女的研究，这次也想测试我作为“稳定器”的可能性。")
	await novel_interface.show_text_only("萨蒙顿则瞒着元老院与莉琉达成了交易。")
	await novel_interface.show_text_only("莉琉则是向元老院隐瞒了我和拉斐尔的状况。")
	await novel_interface.show_text_only("这关系想想就头疼……")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("（真的能好好配合吗……）", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("我偷偷看着这位面色不善的大小姐。")
	novel_interface.character_light()
	await novel_interface.show_dialog("（拉斐尔转入御樱川这件事……）\n（难道也早就被设计好了？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("（看她这副蠢相，又在想些有的没的了吧。）", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("随着咣当一声锁定的声音，电梯终于停稳\n我们面前出现了一道高十米左右的金属大门。")
	await novel_interface.show_text_only("一道红色的扫描光从上而下掠过我的身体。\n门内发出了确认的响声。")
	await novel_interface.show_text_only("莉琉接着上前，进行了二次虹膜识别。")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("虽然是老派的安保措施，但好严格啊……", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_corridor.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("随着扫描结束，大门缓缓降下，露出门后让人震撼的空间。")
	await novel_interface.show_text_only("色调冷峻的巨大地下空间中，两排高达数十米的立柱延伸到远处。")
	await novel_interface.show_text_only("每个混凝土立柱的底部都整齐的贴着大量双向反射式装甲片。")
	await novel_interface.show_text_only("对外可以让建筑抵御火箭筒级的火力，但朝内部启动的话，能瞬间摧毁它们所包裹的结构。")
	await novel_interface.show_text_only("这种装甲在七年战争期间被广泛使用在需要封锁或自毁的堡垒式建筑中。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("这里似乎挺潮湿的……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("地板上还有未干的水迹，头顶高空中交错排列着几十条崭新的管道，传来液体流动的声音。")
	await novel_interface.show_text_only("莉琉改造这里，看来下了不少功夫啊……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我们一路走到通道的尽头，看到一个完全由金属甲板包裹的空间……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_cistern.png")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("到了。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("——欢迎来到『方舟』基地。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("居然——改造的这么彻底吗！")
	await novel_interface.show_text_only("我们面前是一个几十米宽的蓄水池，池中水光闪烁感觉好像身处码头一般。")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("——好好看着吧，『登船梯』第一次正式对接。", "莉琉")
	
	print("=== 深海恐惧篇第7话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
