# bathophobia_ep25.gd - 深海恐惧症篇第25话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep25_script()

func play_script():
	pass

func bathophobia_ep25_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling.png")
	novel_interface.show_character("heinrich_battle","shout")
	await novel_interface.show_dialog("——小心！！","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("监控室大门打开的同时，海因里希猛的将我推到一旁。")
	await novel_interface.show_text_only("瞬间数十道电弧，伴随着刺耳炸裂的声音打在金发少女的胸前，强光闪得我睁不开眼。")
	await novel_interface.show_text_only("几秒后一切归于平静，我的头发上似乎突然累积了大量的静电，空气里有股氯气的味道。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("哈啊……\n海因里希！你没事吧？","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("heinrich_battle","serious",0.25)
	await novel_interface.show_dialog("是某种陷阱类的防御武器……\n还不赖嘛，积蓄了相当于一次小型雷击的能量。","海因里希")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("只见海因里希正拿着一块淡蓝色半透明的晶体，对着监控室顶灯若有所思的观察着。")
	novel_interface.show_character("ren_battle","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("heinrich_battle","serious",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("刚才怎么回事！？\n还有你手上的那是……","小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("一种电气石……主人要试试看吗~","海因里希")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("炼金术士露出一个神秘的笑容，伸出右手穿过我的头发，将那块晶体轻轻贴在我的耳后。")
	await novel_interface.show_text_only("突然一股酥麻温热的电流贯穿了我的全身，感觉每根汗毛都突然紧绷起来。")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("呀啊~","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我情不自禁发出一声娇弱的叫声。")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("啦？主人的身体很敏感呢~","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("哼……真是变态。","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔用看草履虫的眼神看着我。")
	novel_interface.show_character("ren_battle","shy_left")
	await novel_interface.show_dialog("我、我不是……故意的……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我说话声音越来越小，满脸通红的低下头。")
	await novel_interface.show_text_only("但头发上的静电确实一下子就没了，还柔顺了许\n多。")
	await novel_interface.show_text_only("回去跟海因里希偷偷要一块……\n应该可以吧？")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Control_Room.png")
	await novel_interface.show_text_only("我猫在炼金术士身后，小心翼翼的走进监控室。")
	await novel_interface.show_text_only("这里似乎经历过一场浩劫，屏幕和设备有大半严重破损，墙壁和天花板大部分被剥离。")
	await novel_interface.show_text_only("高压电留下的焦黑灼痕以主控台旁边的控制器为中心向外扩散，外露的线圈还时不时打出火花。")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("球形半径……超过五米……\n是高压放电武器吗……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("如果采用的是通用战略Genuine系统的话，那么这个痕迹——")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("应该是简单的改造了系统的攻击性防御设备，用基地内网的高压电……通入了化学蓄电池？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看着被炸得已难以分辨的外壳，忽然明白了氯气的味道是怎么来的。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("电爆炸——","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("强大的电流通过金属箔时，加热作用会使相当大的能量聚集，产生剧烈的爆炸和闪光。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("利用了这东西里面多层折叠的金属箔嘛……真是能高效增加杀伤力的改造。","海因里希")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("但把引导放电的金属线固定在了唯一出口的门缝下面，制作这个武器的人……","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("只要监控室的门被打开，就会与敌人玉石俱焚……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这个安保系统的关键硬件都有电磁屏障，我发现除了一些按键损坏，主控台居然还可以点亮。")
	await novel_interface.show_text_only("进入安保系统，已经是被破解状态，可能与连接在主控台上的军用制式手表有关。")
	await novel_interface.show_text_only("手表的闪存还可以访问，芯片里的内容，记录了主人的身份。")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("是个很厉害的家伙啊……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("监控区还有几个屏幕可以使用，正播放着基地内的探头实时采集到的画面。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("希望能找到点有用的情报——","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我做了个深呼吸，点开历史记录。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("呃……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不愧是保密机构，历史数据庞大到让人发指，早期的影像资料甚至还有用VCR转录的。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("——这要找到地球爆炸啊！","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("乌鸦嘴不要大呼小叫的，设计系统的人肯定要想办法解决这个问题才能验收通过吧？","拉斐尔")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("确实有个模式，能同步所有录像的时间点快速预览\n……","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("但基地里有上百个监控，而且时间是从建站起算的\n……我面前只有一个20寸的屏幕还能工作。")
	await novel_interface.show_text_only("我绝望的不停加大着时间比例尺，直到每个画面都缩小成几个像素点。")
	novel_interface.show_character("ren_battle","stare")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("喂，女装癖，那个——！","拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔敲了我的脑袋一下，指着屏幕上一条竖直的白线。")
	novel_interface.show_character("ren_battle","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","stare",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所有的画面都……一片纯白？","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("……\n……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/TheMan1.png")
	await novel_interface.show_text_only("我跳到拉斐尔所指的时点，找到那之后第一个拍到内容的画面——")
	await novel_interface.show_text_only("屏幕中逐渐出现了一名身材高大的男性。")
	await novel_interface.show_text_only("身穿灰蓝色的防护服，大约一百九十公分左右，身形健壮，步伐坚定而迅速。")
	await novel_interface.show_text_only("他并不在意被拍摄到，但在模糊的录像中无论如何都无法分辨他的脸。")
	await novel_interface.show_dialog("这个感觉……","小怜")
	await novel_interface.show_dialog("主人认识吗？","海因里希")
	await novel_interface.show_dialog("不，不认识……","小怜")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Control_Room.png")
	await novel_interface.show_text_only("男人像是在寻找什么，快速查探着基地。")
	await novel_interface.show_text_only("他快步的从资料室走向医务室。")
	await novel_interface.show_text_only("在经过两名穿着雪地服的士兵尸体时，男人突然停止脚步，俯身仔细研究。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("那个士兵的小腿……不见了？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("从模糊的屏幕上看着那个人腿部伤口周围黑色的血迹，拉斐尔和我都屏住了呼吸。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("果然，发生过战斗吗……","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("——我突然回想起资料室地面上巨大的裂痕。")
	await novel_interface.show_text_only("男人淡漠地走进医务室，从药柜中取出一张黑色的卡片，突然他将手中的枪上膛。")
	await novel_interface.show_text_only("医务室的角落突然窜出一个动作诡异的黑影，男人果断对着黑影连开数枪，将其打出摄像范围外。")
	await novel_interface.show_text_only("接着他拔出匕首跟了过去，几秒钟后回到画面，将一团模糊的东西随意的丢进了垃圾桶。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("那、那个不会是……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不不不，一定是我看错了。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("很明确的战斗准则。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("……先别管，继续。","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("男人步伐沉稳的关上医务室的门，他似乎很熟悉基地的构造，用那张卡片打开了一个金属闸门。")
	await novel_interface.show_text_only("看到没人之后，男人快步走到了监控室外的隧道。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("这……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然监控画面的颜色很浅，但在录像中隧道里绝对是一片血腥惨烈的战场。")
	await novel_interface.show_text_only("数十具横七竖八的尸体朝着同一个中心点呈放射状散布着，似乎是被某种强烈的冲击同时所击倒。")
	await novel_interface.show_text_only("而中心点的位置，一名被长柄武器贯穿的白衣少女上身笔直的跪在地上。")
	await novel_interface.show_text_only("在寒冷的极地环境中，她穿得实在有些单薄，白皙的皮肤上满是鲜血。")
	await novel_interface.show_text_only("少女垂下的双手各自握着一把武器，哪怕失去了意识，她也并未放手。")
	await novel_interface.show_text_only("——男人单膝蹲在少女面前，轻轻抚过她的脸。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("（……是认识的人？）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("片刻之后，他绕到少女背后，握住长柄缓缓将其拔出，露出金色包边的枪头。")
	await novel_interface.show_text_only("少女的身体没有丝毫的移动，伤口也没出更多鲜血，整个过程有一种难以言表的违和感。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("（轻声）啊……","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("男人脱下外套，小心的将枪头卸下，用布包好后将之收入西装上衣的内侧，并将长柄丟在一边。")
	await novel_interface.show_text_only("随后他走进了监控室，但切到里面的画面无法显\n示。")
	await novel_interface.show_text_only("我们抬头，发现这个房间里的摄像头已经完全被电击损坏。")
	await novel_interface.show_text_only("过了一会，男人提着一个五十公分左右的合金手提箱走出来。")
	await novel_interface.show_text_only("箱子的锁扣已经损坏，他将之打开，从里面取出了三支玻璃容器。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("（……总觉得越来越奇怪了。）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一支玻璃容器已经完全碎裂，男子迟疑片刻，拿出另外两支收在衣服口袋中。")
	await novel_interface.show_text_only("接着他松开少女紧握武器的双手，一本笔记从少女身上掉了出来。")
	await novel_interface.show_text_only("男人捡起翻查了一下，顿了顿，又将其放回了少女怀中。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/TheMan2.png")
	await novel_interface.show_text_only("他像抱着婴儿一样，小心翼翼地将身材瘦小的白衣少女抱起，动作非常温柔。")
	await novel_interface.show_text_only("男子抱着少女一路走到隧道尽头，将黑色的卡片贴在了墙面上。")
	await novel_interface.show_text_only("原本封闭的墙面缓缓向一侧移开，接着他们一起消失在黑暗中……")
	await novel_interface.show_text_only("——监控记录就此停止。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Control_Room.png")
	await novel_interface.show_text_only("之后所有的录像都出现了一段漫长的记录空白，再恢复的图像中，也没有捕捉到这名男子的身影。")
	await novel_interface.show_text_only("空白、空白、空白……直到，我们三人的身影出现在基地门口。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("奇怪……","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("等等，这里……","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔指向医务室的画面。")
	novel_interface.show_character("ren_battle","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","perspire",0.25)
	await novel_interface.show_dialog("那里之前有一具尸体……但现在消失了。","拉斐尔")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不如说，所有的尸体全都消失了……","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("也就是说，在录像的空白期间，原本血腥的战场仿佛被全面打扫过一般。")
	await novel_interface.show_text_only("我们又开始向前查询记录。")
	await novel_interface.show_text_only("往前倒退，监控画面忠实的记录了那个少女和一只小分队在基地中的遭遇。")
	await novel_interface.show_text_only("监控室摄像头留下最后的影像，是穿雪地服的女生用枪将黑发少女逼出了门外。")
	await novel_interface.show_text_only("然后记录就此中止。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("……之前这里，还发生过那种事啊。","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我关闭资料，将模式恢复为实时画面。")
	await novel_interface.show_text_only("大门口、展览室、走廊、资料室、隧道……还有一些我们没去过地方的实时影像全都分列开来。")
	await novel_interface.show_text_only("我扫过实时画面的屏幕，突然想到一个问题：我们在资料室外的战斗完全没有被记录下来。")
	await novel_interface.show_text_only("回溯的录像中，我们三人从走廊进入了资料室再没有出来，而从另一侧的出口来到了隧道。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("那场战斗是『梦境』吗，确实太奇怪了……","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("而且到底是谁清理的这里？","拉斐尔")
	await novel_interface.show_dialog("……这里的录像一定被人动过手脚。","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("连那个男人离开的部分也没有保留下来。","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一边与她俩猜测着刚才的少女和男子的身份，一边机械的切换着各处的实时画面。")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("等等……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("录像被人动过手脚，以及我们进入了『梦境』，这些都是合理的推测。")
	await novel_interface.show_text_only("而真正不合理的是——")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("为什么，我们能看到资料室的实时画面？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔和海因里希也愣在原地。")
	await novel_interface.show_text_only("诡异的沉默飘荡在房间内……")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("那个线缆……","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("不是被我们拆掉了吗……","海因里希")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("那个重要的『问题』是什么来着……")
	await novel_interface.show_text_only("——我，是怎么来到这里的？")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("忽然间，我又有点想上厕所。")
	
	print("=== 潜渊症篇第25话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
