# bathophobia_ep13.gd - 深海恐惧症篇第13话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep13_script()

func play_script():
	pass

func bathophobia_ep13_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Submarine_centralControlRoom.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("白烛坐在中控室内，对着屏幕上舱外实时监控画面中的皑皑冰山看得出神。")
	await novel_interface.show_text_only("随着舰艇上浮，南极极夜天空下的淡紫色光线笼罩了整个房间。")
	novel_interface.show_character("milk_normal","laugh")
	await novel_interface.show_dialog("小 ~ 白 ~ 烛 ~", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("房间门突然被推开，性格活泼的马尾少女朝她扑了过来。")
	await novel_interface.show_text_only("白烛的思绪被拉回现实，无奈的叹了口气。")
	novel_interface.show_character("milk_normal","pleased")
	await novel_interface.show_dialog("呐，一定想我了吧~？", "牛奶")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("之前的密码锁是那群无聊家伙的恶作剧而已，不用放在心上！", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶边说边拉下T恤的领口，展示自己胸部夹着的一打钞票——刚才赌局的“战利品”。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("还真是恶趣味。", "白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_normal","laugh")
	await novel_interface.show_dialog("每次都不会让我失望呢，小白烛真是太棒太~~可爱了！", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛试图推开黏在自己身上乱蹭的生物，但对方立刻又扑了回来。")
	novel_interface.show_character("milk_normal","mock")
	await novel_interface.show_dialog("嘿嘿，不提那个了。\n刚才做简报的时候，你有些奇怪哦……", "牛奶")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","think")
	await novel_interface.show_dialog("是吗？", "白烛")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("白烛坐在沙发上，而牛奶骑在她腿上，伸出双手捧住了少女的脸颊。")
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	await novel_interface.show_text_only("白烛不自在的回避了对方的视线。")
	novel_interface.show_character("baizhu_normal","think")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("milk_normal","gratified",0.25)
	await novel_interface.show_dialog("……", "牛奶")
	await novel_interface.show_dialog("不承认吗？", "牛奶")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("一阵沉默之后，牛奶温柔的笑了笑。")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("其实，这次任务，我一点都不想参与的……", "牛奶")
	await novel_interface.show_dialog("毕竟超自然现象和非人生物，完全不是我的菜。", "牛奶")
	await novel_interface.show_dialog("再加上只有“南极上空检测到异常的类生物电波”这种情报，一般人怎么可能找到『目标』嘛……", "牛奶")
	novel_interface.change_2nd_expression("laugh")
	await novel_interface.show_dialog("即使空手而归，我也不会意外……就当来南极度假咯~", "牛奶")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛听懂了对方的言下之意。")
	novel_interface.show_character("baizhu_normal","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("milk_normal","laugh",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("……你是不是都看出来了？", "白烛")
	novel_interface.character_dark()
	await novel_interface.show_text_only("马尾少女的表情认真起来。")
	novel_interface.character_2nd_light(0.35,"solemn")
	await novel_interface.show_dialog("嗯，我调取了你深潜舱的行为记录。", "牛奶")
	await novel_interface.show_dialog("你……亲眼见到了『那东西』？", "牛奶")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛看着桌面上的军事级南极地图。")
	await novel_interface.show_text_only("为特遣队提供的地图上，一道阴影清晰可见——")
	await novel_interface.show_text_only("在那片区域，标记着南极大陆东部海洋中发现的巨型不明物。")
	novel_interface.show_character("baizhu_normal","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","pleased",0.25)
	await novel_interface.show_dialog("——唉，安心吧。", "牛奶")
	novel_interface.change_2nd_expression("sprite")
	await novel_interface.show_dialog("你在行动中故意让深潜舱失控，然后设置下沉到6\n000米后自动唤醒的操作日志，我全部修改掉了~", "牛奶")
	await novel_interface.show_dialog("你这家伙，虽然对机械很擅长，但总会忽视那些隐藏代码……", "牛奶")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我知道你会帮我的。", "白烛")
	novel_interface.character_dark()
	await novel_interface.show_text_only("白烛露出有些狡猾的笑容。")
	novel_interface.character_2nd_light(0.35,"shock")
	await novel_interface.show_dialog("拜托，刚才做简报的时候，你想深入南极大陆的意图太明显了好不好！", "牛奶")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("牛奶轻轻的敲了下白烛的脑袋。")
	novel_interface.show_character("baizhu_normal","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","normal",0.25)
	await novel_interface.show_dialog("而且就算样本箱只能再维持几个小时的深海环境\n但样本并不一定会因此而失去活性吧~？", "牛奶")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("唔……", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sprite")
	await novel_interface.show_dialog("喂喂，『那东西』好看吗？", "牛奶")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("白烛露出畏惧的眼神，摇了摇头。")
	novel_interface.character_2nd_light(0.35,"gratified")
	await novel_interface.show_dialog("哎~我就知道！", "牛奶")
	await novel_interface.show_dialog("……但你为什么要隐瞒自己知道关于『那东西』额外情报的事情？", "牛奶")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛沉默不语。")
	await novel_interface.show_text_only("牛奶坐在白烛的床上，看着窗外。")
	novel_interface.show_character("baizhu_normal","think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","normal",0.25)
	await novel_interface.show_dialog("我一开始以为，你的目标是乌斯怀亚号。", "牛奶")
	await novel_interface.show_dialog("但“在破冰船上加载实验室”这种事，听上去就让人不安啊……", "牛奶")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所以，一定会被否决的。", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("那么能解析样本的，就只剩下极地区域内有实验室的常驻设施了。", "牛奶")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("两小时可达的范围里，拥有这种规格实验室的只有南极圈内的白皇后和纽伦堡两个基地。", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("剩下的不是设备老旧，就是权力关系复杂，有驻军的更不能考虑。", "牛奶")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("从地理位置来看，纽伦堡基地更靠近埃默里冰架。", "白烛")
	await novel_interface.show_dialog("但是——", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sprite")
	await novel_interface.show_dialog("很不幸，上个月纽伦堡基地刚刚入驻了一支私人武装，也就是说它已经被卖给了“独立机构”。", "牛奶")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("两人目光交汇，白烛眨了眨眼睛。")
	novel_interface.show_character("baizhu_normal","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("milk_normal","sprite",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("其实，如果你的Boss能表达一下和私人企业合作的意愿的话……", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("唉，政府高层的那群家伙，最重视的就是脸面了。", "牛奶")
	novel_interface.character_light(0.35,"shock")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哪怕要收买控制附近海域的海盗和独裁者？", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"pleased")
	await novel_interface.show_dialog("喂，你知道的太多了！", "牛奶")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("总之，排除掉破冰船，纽伦堡基地，你真正想要引导我们进入的目标是——", "牛奶")
	await novel_interface.show_dialog("东经76-55-22，南纬68-24-59…… 『Snedroningen』——白皇后基地。", "牛奶")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……嗯。", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"gratified")
	await novel_interface.show_dialog("就这么承认了？", "牛奶")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你啊，明明都知道我在想什么……", "白烛")
	novel_interface.character_dark()
	await novel_interface.show_text_only("牛奶并没有炫耀推理能力的意思，而是对好友露出了担忧的神情。")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("线索……指向了那里么？", "牛奶")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……", "白烛")
	novel_interface.character_dark()
	await novel_interface.show_text_only("白烛沉默着点了点头。")
	novel_interface.character_2nd_light(0.35,"laugh")
	await novel_interface.show_dialog("那……放心吧。我会安排好的！", "牛奶")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("每次你都能猜出我是不是隐瞒了什么秘密呢。", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sprite")
	await novel_interface.show_dialog("不要小瞧我……对你的了解哦~", "牛奶")
	await novel_interface.show_dialog("你也不该把什么都藏在心里。知道你的计划我才能帮你嘛！", "牛奶")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("但是……", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("还是说不信任我？", "牛奶")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不，怎么会……\n只是——", "白烛")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("少女在思考要如何否认，但是下一秒，她已经被对方温暖的双臂紧紧抱住。")
	novel_interface.show_character("baizhu_normal","think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","gratified",0.25)
	await novel_interface.show_dialog("哎，真是难为你……", "牛奶")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哎？", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("我知道你只是不想让我卷入到。\n那些事情……", "牛奶")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("少女低下了头。")
	novel_interface.character_light(0.35,"sad")
	await novel_interface.show_dialog("父亲的事，太过复杂了……", "白烛")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("牛奶更加用力地抱紧了白烛。")
	await novel_interface.show_text_only("黑发少女的面颊涨得通红，一开始本能的想试着推开对方，但还是慢慢放下了双手。")
	await novel_interface.show_text_only("在她心中，一种难以名状的宁静而温暖的感觉，静静升起。")
	novel_interface.show_character("baizhu_normal","sad")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","gratified",0.25)
	await novel_interface.show_dialog("你啊，看上去冷冰冰的，其实是很容易心软的人…", "牛奶")
	await novel_interface.show_dialog("连舰艇上这些相处没多久的笨蛋，你也不想把他们牵连进去。", "牛奶")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我并没有……", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"laugh")
	await novel_interface.show_dialog("嘿嘿，那为什么要说“想放弃还来的及”这种话？", "牛奶")
	await novel_interface.show_dialog("就是想让他们早点回到安全区嘛~", "牛奶")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……大概，是吧。", "白烛")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛在牛奶怀里露出了浅浅的笑容，仰头看着拥抱自己的女孩，眼中蕴着光芒。")
	novel_interface.show_character("baizhu_normal","think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","laugh",0.25)
	await novel_interface.show_dialog("不要对我隐瞒啦~\n小白烛这么单纯，根本学不会骗人。", "牛奶")
	novel_interface.change_2nd_expression("gratified")
	await novel_interface.show_dialog("相信我，把真相告诉我吧……", "牛奶")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛沉默了。")
	novel_interface.show_character("baizhu_normal","think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","sprite",0.25)
	await novel_interface.show_dialog("唔，就算你不说，我也能够猜到。我可是拥有能看穿你的超能力哒！", "牛奶")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是啊，你那么聪明。", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("但是越猜测你的意图，我就会越担心……", "牛奶")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("抱歉。", "白烛")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sprite")
	await novel_interface.show_dialog("与其道歉，不如用行动来补偿我吧！", "牛奶")
	novel_interface.character_light(0.35,"shock")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哎？", "白烛")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("牛奶戳了戳白烛的额头。")
	novel_interface.show_character("baizhu_normal","shock")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","laugh",0.25)
	await novel_interface.show_dialog("就不知道抱抱我吗？", "牛奶")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……嗯。", "白烛")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛如释重负地伸出手臂，环在牛奶腰间。")
	novel_interface.show_character("baizhu_normal","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("milk_normal","laugh",0.25)
	await novel_interface.show_dialog("多笑笑啦，明明是这么可爱的女孩子。", "牛奶")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("浮上海面的潜艇，安静的在冰冷的洋流中穿行。")
	await novel_interface.show_text_only("因为白夜效应的缘故，哪怕是午夜时分，天际依旧交织着着橙红与黛紫的色泽。")
	await novel_interface.show_text_only("然而，倒映在白烛的双眸中牛奶展露的笑容，却像朝阳般温暖明艳。")
	await novel_interface.show_text_only("那是比艇外的美景更加动人的一幕。")
	novel_interface.show_character("baizhu_normal","shy")
	await novel_interface.show_dialog("（嘟嚷）……还是你比较可爱。", "白烛")
	
	print("=== 深海恐惧症篇第13话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
