# bathophobia_ep28.gd - 深海恐惧症篇第28话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep28_script()

func play_script():
	pass

func bathophobia_ep28_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/3Girls.png")
	await novel_interface.show_text_only("在莉琉的许可下，我、拉斐尔、还有早已恢复元气的安妮一起去探望白烛。")
	await novel_interface.show_text_only("集合地点是新丰洲大隅纪念医院，白烛已经在那里进行了半个月的恢复性训练。")
	await novel_interface.show_dialog("据说莉琉小姐为了避开运营白皇后基地的组织，用离岸公司匿名买下了那所医院大半的股份哦。","安妮")
	await novel_interface.show_text_only("安妮大步走在前面，漫不经心的说道。")
	await novel_interface.show_dialog("哈哈哈，还真有她的风格……","小怜")
	await novel_interface.show_text_only("虽然同时也能脱离元老院的视野\n但这样的手笔未免还是太夸张了吧……")
	await novel_interface.show_dialog("笨蛋——","拉斐尔")
	await novel_interface.show_dialog("那所医院在细胞学方面的研究一直都是世界一流水准，而且坐落在寺上公园这种地段。","拉斐尔")
	await novel_interface.show_dialog("就算仅仅作为投资，也是明智的选择。","拉斐尔")
	await novel_interface.show_dialog("哦……\n（怎么好像你也想买似的！）","小怜")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("算了，还是不问了……")
	await novel_interface.show_text_only("她真的买了也很有可能……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Baizhu_Sickroom.png")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("请问……\n白烛是在这个房间吗？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("病房门虚掩着，我有些忐忑的推门进去。")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_text_only("皮肤白暂的少女正穿着一身纯白的连衣裙，半坐在病床上，安静的翻着一本书。")
	await novel_interface.show_text_only("微风拂过她的面颊，远处是新丰洲漂亮的城景，偶尔传来楼下公园的鸟鸣和小孩子玩耍的声音。")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","blush")
	await novel_interface.show_dialog("（果然很漂亮啊……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("——我很不争气的呆在了原地。")
	await novel_interface.show_text_only("这种感觉，能理解吧……")
	await novel_interface.show_text_only("就是之前在游戏里攻略过的那种——")
	await novel_interface.show_text_only("“美丽病弱的邻家少女在安静的午后读着诗集，等待着那个如诗中描述般与她邂逅的男……”")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("（嗯……女孩子？）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("咳咳——","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔轻咳着从后面拍了我一把，也提示白烛我们的到来。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("小怜，你们来啦。","白烛")
	await novel_interface.show_text_only("看到我们，白烛合上手中的书。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("偷瞄了一下书名…叫做《拓扑绝缘体和低维凝聚态物理》。")
	novel_interface.show_character("ren_battle","uneasy")
	await novel_interface.show_dialog("（哈哈哈哈……我刚才在想什么啊笨蛋！）","小怜")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("你还记得我的名字吗？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛露出理所当然的微笑。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("如果没认错的话……另外两位是拉斐尔和安妮？","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","shy")
	await novel_interface.show_dialog("嗯？你也认识我？","安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("前阵子莉琉有向我介绍过南极行动的相关成员。","白烛")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("似乎给你们添了不少麻烦……","白烛")
	novel_interface.character_dark()
	await novel_interface.show_text_only("白烛脸上略过一丝悲伤的表情，但立刻转到了下一个话题。")
	novel_interface.character_light(0.35,"smile")
	await novel_interface.show_dialog("对了，海因里希没来吗？","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("小怜现在是元老院关注的焦点人物，海因里希暂时不方便和她一起行动。","拉斐尔")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("不过她拜托我到了医院之后——","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔走到病床旁边的操作台，输入了一串地址。")
	await novel_interface.show_text_only("接着海因里希的半身图像就出现在了白烛病床小桌上的屏幕中。")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("嘿——你好呀~","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","mock")
	await novel_interface.show_dialog("你好，上次还没跟你好好道谢呢。","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("不用谢。某种意义上，应该是我谢你才对……","海因里希")
	await novel_interface.show_dialog("嘛，你恢复的很快嘛！现在的医疗设备真是厉害~","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("你的身体好些了吗？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("还不错。","白烛")
	await novel_interface.show_dialog("小时候父亲每天都会给我安排训练，所以我的身体可能恢复得比普通人快一些。","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("嗯嗯，那就好~","小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("诶……好多书啊！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看向堆满书本的床头柜，完全不知该把带来探病的礼物放在哪。")
	await novel_interface.show_text_only("而且——")
	await novel_interface.show_text_only("和那些书相比，我送的颜文字抱枕好像太蠢了……")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("我比较喜欢纸质书的触感，拜托莉琉给我送来了不少，刚好可以补一下这些年错过的知识。","白烛")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","worry",0.25)
	await novel_interface.show_dialog("……有什么有趣的书推荐吗？","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我一边随口搭着话，一遍四处寻觅着适合放抱枕的地方。")
	novel_interface.show_character("baizhu_normal","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_battle","gratified",0.25)
	await novel_interface.show_dialog("（嗯，先放在床对面的茶几上吧~）\n（趁那里还没被堆满……）","小怜")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("最近觉得比较有趣的——","白烛")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("将抱枕上表情调整到合适位置的我，转身发现白烛正在书堆里翻着什么。")
	await novel_interface.show_text_only("她脸上洋溢着喜悦，似乎早就想找人分享了。")
	novel_interface.show_character("baizhu_normal","mock")
	await novel_interface.show_dialog("比如这本《异质物量子相变研究》，和这个《时空非对称异场论》——","白烛")
	await novel_interface.show_dialog("看到人类正在用科学的方法，一点一点解析异质物的原理，真是令人振奋。","白烛")
	await novel_interface.show_dialog("嗯……还有这本《帕兰蒂尔收容日记》，是一部科幻恐怖小说，作者的物理学分析非常精彩。","白烛")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("……","小怜")
	novel_interface.change_2nd_expression("wry_smile")
	await novel_interface.show_dialog("啊、啊哈哈哈……","小怜")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_text_only("对不起！完全不能理解你的有趣点！\n左右手法则已经是我的极限了！！")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊，我似乎有点唐突了，小怜最近在看什么书呢？","白烛")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("《主角魔女的养成办法》、《魔女的工作》之类的\n……")
	novel_interface.show_character("baizhu_normal","think")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_battle","shy",0.25)
	await novel_interface.show_dialog("（不，不能说！）","小怜")
	novel_interface.change_2nd_expression("shy_left")
	await novel_interface.show_dialog("一些……嗯……关于“成长”方面的书。","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("呜呜呜……有种智商被碾压的感觉。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("哼，笨蛋就是笨蛋。","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","worry")
	await novel_interface.show_dialog("稍微有点能理解小怜……\n物理什么的太可怕了。","安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮似乎回想起了物理教导主任锋利的目光，下意识的躲在了我的身后。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("我最近也在研究，但相比『化学』这种去掉神秘成分只探讨可知部分的分类法——","海因里希")
	await novel_interface.show_dialog("我还是更喜欢『炼金』这种毫不回避人类的未知部分，只想一心追求真理的称呼~","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("确实“科学”就是分科的学问，将复杂的问题拆分简化，为的是让普通人也能研究——","白烛")
	await novel_interface.show_dialog("但绝大多数时候，我们都是在不明白原理的情况下就先利用起来呢。","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("（我还以为神秘学和科学完全搭不上界呢……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("（因为你自以为知道的太多了，笨蛋——）","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("等等，现在我已经能从拉斐尔嘴角挑起的弧度中读取出她想表达的内容了吗？")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("（并、并不想要这种能力！……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("注意到我的表情，白烛轻轻一笑，收回了自己的推荐。")
	novel_interface.show_character("ren_battle","sob")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	await novel_interface.show_dialog("小怜是不是觉得，身边大多数事物的运作原理早已经被研究透彻了？","白烛")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不、不是这样的吗……","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("看我傻乎乎的样子，白烛露出了一个狡猾的笑容。")
	novel_interface.show_character("ren_battle","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("baizhu_normal","mock",0.25)
	await novel_interface.show_dialog("提问：为什么自行车骑起来不会倒？","白烛")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯……因为车轴……力矩……平衡……\n什么的吧？","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我胡乱的扯着觉得可能有关的专业名词，但这么简单的问题，肯定一百年前就被研究明白了吧？")
	await novel_interface.show_text_only("白烛、拉斐尔和视频中的海因里希看着我，不约而同的笑了起来。")
	await novel_interface.show_text_only("有一种被大佬围观的感觉……")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("在我上大学的时候，这就是科学界一直悬而未决的问题，《Science》上还有一篇论文讨论过。","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("直到今天也没有被科学界完全认可的解释。","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","panic")
	await novel_interface.show_dialog("自行车这么简单的东西……都没研究明白吗？","安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我也有点懵，她们不会在联手骗我吧。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("所以呢……不用那么害怕的。","白烛")
	await novel_interface.show_dialog("在科学家看来，我们每天的日常，都是万亿分之一概率的奇迹。","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("确实，昨天我一口气补完了关于分子机器和热能驱动的知识。","海因里希")
	await novel_interface.show_dialog("世界上居然曾经存在着一群和我的思路如此一致的家伙……真是不可思议。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("生物学中也有这种状况呢，虽然不知道一段基因的具体原理，但只要它的表达能对抗『黑缕病』——","拉斐尔")
	novel_interface.character_dark()
	await novel_interface.show_text_only("拉斐尔望着窗外繁荣的新丰洲市区。")
	novel_interface.character_light(0.35,"normal1")
	await novel_interface.show_dialog("就能保证足够的粮食产量，让这个世界继续运转下去……","拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛似乎看出了拉斐尔的担心。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("就算不明白运作原理，也可以成为“机器”最重要组成部分，关键是设计机器的灵魂。","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","panic")
	await novel_interface.show_dialog("机器……灵魂？","安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("小到病毒、大到国家城市、其实都是按照某种规则设计运转的机器","白烛")
	await novel_interface.show_dialog("虽然机器本身是中立无感情的，但我始终认为，可以从机器的形态，看到设计者的灵魂。","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉菲尔微微点了点头，露出一个欣慰的笑容。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("我喜欢这个想法——","海因里希")
	await novel_interface.show_dialog("从这个意义上来说……无论是人类，还是更高位的存在，灵魂都是对等的。","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听着她们三人似懂非懂的对话，我和安妮安静的坐在沙发上。")
	await novel_interface.show_text_only("白烛看着我们，轻轻笑了起来。")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("怎么了吗？","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	await novel_interface.show_dialog("没什么……","白烛")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("少女顿了顿，似乎在回忆过去。")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("只是看着你们天真的样子，我会忍不住想起——","白烛")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("我也有过这样无忧无虑的日子呢……","白烛")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("诶？这……","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("糟糕，我最棘手的场景——安慰突然陷入回忆的少女。")
	novel_interface.show_character("ren_battle","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","mock",0.25)
	await novel_interface.show_dialog("倒不如直说，这家伙是缺乏思考能力只会耍小聪明的笨蛋。","拉斐尔")
	novel_interface.character_light(0.35,"speechless")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……是这个意思吗？","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛摇了摇头，非常诚恳的说道。")
	novel_interface.show_character("baizhu_normal","mock")
	await novel_interface.show_dialog("我是真心的羡慕你们啦。","白烛")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_normal","normal1",0.25)
	await novel_interface.show_dialog("嗯~","安妮")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("能相信一些简单的东西……感觉也不错呢。","安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮看了看我，又对着白烛露出一个灿烂的笑容。")
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("然后海因里希抓住机会和白烛聊了半天很具体的学术问题，拉斐尔也时不时的参与其中。")
	await novel_interface.show_text_only("三人的词汇完全超越了我和安妮的常用辞典范围。")
	await novel_interface.show_text_only("而更令我无法相信的是，她们可以轻松的将科学和神学放在一起探讨。")
	await novel_interface.show_text_only("某处的教宗大人听到这样的对话可能会喷血吧。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Baizhu_Sickroom_Evening.png")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("我现在……真心觉得自己像个笨蛋诶……","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_normal","frustrate",0.25)
	await novel_interface.show_dialog("……同感。","安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("为什么一个物理学家、一个神秘学的炼金术士和一个把生物学和神学掺和到一起的家伙","小怜")
	await novel_interface.show_dialog("能聊得那么火热啊……","小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"relieve")
	await novel_interface.show_dialog("……大概她们三个能聚在一起，从某种意义上来说就已经很不科学了吧？","安妮")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是哦……","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("可我们不也是——")
	await novel_interface.show_text_only("不科学的存在吗？")
	
	print("=== 潜渊症篇第28话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
