# bathophobia_ep02.gd - 深海恐惧篇第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep02_script()

func play_script():
	pass

func bathophobia_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("（历史上的贝阿特丽切于1290年死亡）\n（而她现在的身体应该是小怜的能力所制造的）", "莉琉")
	await novel_interface.show_dialog("（制造承载灵魂的容器，这已经是『神的领域』\n了）", "莉琉")
	await novel_interface.show_dialog("（这一点，绝不能暴露……）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("哈哈哈哈，有意思……\n真是太有意思了。", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("想必你们已经调查过，在天空酒店与小怜一同行动的那位名为安妮·巴斯的探员。", "莉琉")
	await novel_interface.show_dialog("她就是七年前，在『自由光巨蛋事件』中消失的五万人中的一员。", "莉琉")
	await novel_interface.show_dialog("是小怜将她从异空间中带出来的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("……", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("大家看上去都不怎么惊讶呢。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("确实，如果是这样就可以解释了……", "华音泷")
	await novel_interface.show_dialog("但就这么大大方方的让安妮用真名活动，看来你也没打算保密。", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("莉琉阁下也没必要保密，因为安妮当年在网络上的记录实在太多了。", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("不过将自己设为那个叫怜的女孩的监护人，完全是出于你的私心吧。", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("哼，那当然。", "莉琉")
	await novel_interface.show_dialog("我在几年前就发现了小怜的能力，但后来她的父母打算移民到第二学园都市……", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("我不得不采取一些行动。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("她的父母和哥哥遭遇的那场空难……", "#C")
	await novel_interface.show_dialog("难道是莉琉阁下您——？", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("呵呵呵呵，我可不会承认。", "莉琉")
	await novel_interface.show_dialog("我可还要继续做那个小可爱的监护人呢~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("……", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("不愧是能主管SID的手段，真是让我倍感安全。", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("为了新丰洲的和平与稳定，有些牺牲是必要的。", "基尔斯")
	await novel_interface.show_dialog("莉琉和SID的工作一直完成的十分漂亮。", "基尔斯")
	await novel_interface.show_dialog("那么这段时间在各国肆虐的时空相位波动，SID应该已经掌握了更多情报吧？", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("记录显示那个小姑娘只有15岁，派她去那种高风险区域会不会……", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("虽然风险确实很大，但这个代价是值得的。", "莉琉")
	await novel_interface.show_dialog("根据小怜帮助采集的情报，可以推断——\n时空异变本质上是概率乱流。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("将概率不足万亿分之一的事件，以100%确定的形式表达出来——", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("那不就像魔法一样！", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("那可真是……令人梦寐以求的能力啊……", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("不对不对，这种情况仅仅在理论上可能，因为需要一个超强的观测者……", "布莱特")
	await novel_interface.show_dialog("不可能，就算把全人类的注意力都集中到一点也无法达到这种观测强度。", "布莱特")
	await novel_interface.show_dialog("除非……", "布莱特")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("除非是，制造了各种异质物的存在。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("……", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("唉———", "基尔斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("基尔斯博士长长的叹了一口气，随后是一阵沉默。")
	await novel_interface.show_text_only("长期以来，关于“谁制造了异质物”一直是科学界刻意回避的话题。")
	await novel_interface.show_text_only("就像“谁制造了宇宙大爆炸”一样，因为答案无法被证伪，不属于科学的讨论范围。")
	await novel_interface.show_text_only("就像曾有科学家试图研究哈勃距离之外，那些由于宇宙空间膨胀而以超光速远离地球的星系一样。")
	await novel_interface.show_text_only("他们认为『可观测宇宙』只是真正宇宙中的沧海一粟，而我们在有意回避我们看不到的东西。")
	await novel_interface.show_text_only("理所应当的回避，可能这才是科学能让人感到安心的真正原因。")
	await novel_interface.show_text_only("如果真的存在神级的观测者，在它面前，地球上的人类和彗星尾部的尘埃没有多大区别。")
	await novel_interface.show_text_only("这样的神不会眷顾我们……人类只能自己拯救自\n己。")
	await novel_interface.show_text_only("或许在黑暗冰冷的宇宙中，这才是最可怕的事实。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("……综上所述，『相位波动空间』是无序的大规模概率坍缩事件。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("这种事件是由于在有限的时空，有限的尺度内召唤了超乎认知的观测者所致。", "莉琉")
	await novel_interface.show_dialog("当召唤者的理智被观测者反噬，就会造成概率乱流引发时空异变。", "莉琉")
	await novel_interface.show_dialog("但如果能进入异变区域控制住召唤者，就能从根本上消除其影响。", "莉琉")
	await novel_interface.show_dialog("我已经在新丰洲的异变区域进行了多次试验，证明这是一种行之有效的对策。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("如果不加以干预，当异变空间完全蒸发，除了会造成区域性熵值暴增——", "莉琉")
	await novel_interface.show_dialog("还极有可能在蒸发点出现一个或多个丧失理智的超能力者，造成进一步破坏。", "莉琉")
	await novel_interface.show_dialog("目前看来，理智丧失是不可逆的，这些袭击者的特征符合中世纪历史卷宗对『女巫』的描述。", "莉琉")
	await novel_interface.show_dialog("唯一值得欣慰的是，异变空间蒸发后，用常规手段也可以将女巫镇压。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("以上。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一片死寂——")
	await novel_interface.show_text_only("加密通讯的另一头传出阵阵倒抽凉气的声音，除此以外，鸦雀无声。")
	await novel_interface.show_text_only("即使是新丰洲权利顶端的人，一时也难以处理如此繁复的信息。")
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("确实……", "基尔斯")
	await novel_interface.show_dialog("在新丰洲由时空相位波动造成的破坏，要远少于其他学园都市。", "基尔斯")
	await novel_interface.show_dialog("我们之前一直认为，这是埃癸斯的效果所致。", "基尔斯")
	await novel_interface.show_dialog("……这样看来，这名少女的能力，确实有必要设为『机密』。", "基尔斯")
	await novel_interface.show_dialog("由莉琉直接监护，也是正确的选择。", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("但是你所说的这些，有证据吗？", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("SID保留了完整的监测数据。", "莉琉")
	await novel_interface.show_dialog("而且有很多其他学园都市的异变区域附近出现无法沟通且破坏力强大的人型生物的情报。", "莉琉")
	await novel_interface.show_dialog("前不久在江森变电所附近也出现过类似的情况。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("这些信息，想必#C博士应该已经知道了吧？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉紧盯着荧幕上的被加密的隐藏面孔。")
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("莉琉阁下在开启反扫描模式的直升机上从江森变电所凯旋的英姿，自然是让人过目不忘。", "#C")
	await novel_interface.show_dialog("如果是因为那个“怜”也在直升机上的话，在下就没有什么疑问了。", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("（看来南哲的部下并没有泄露情报）", "莉琉")
	await novel_interface.show_dialog("我派小怜到天空酒店，也是为了防止在中立区域出现异变的情况。", "莉琉")
	await novel_interface.show_dialog("没想到关键证物被另一伙人抢走了……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("这么说你一开始就是冲着黄金蝴——", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("——莉琉的判断是正确的。", "基尔斯")
	await novel_interface.show_dialog("那名叫做“怜”的姑娘，你们测试过她能力的启动方法或能力边界吗？", "基尔斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("基尔斯快速打断了布莱特的话并转移了话题。")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("……", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("（哼，露出马脚了。）", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("由于需要特殊的防护设施，暂时还没有安排实验。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("荧幕后方的人有些不满。")
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("如此特殊的资源，需要什么支持只要和元老院申请便好。", "基尔斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉低下头，露出狡猾的笑容。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("现在并不能确定，另一个维度的空间中，是否有我们无法应对的危险存在。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("就算成功回收了某些人或物品，如何保证对方不存在攻击性呢？", "莉琉")
	await novel_interface.show_dialog("毕竟历史上，可是有过“黑死病是由魔女的力量造成的”之类的传闻……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("但是也不能把这么有意思的研究全都交给莉琉吧。", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("不如，把那个小怜带到我的实验室？\n哈哈哈哈哈哈——", "布莱特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("布莱特爆发出一阵带着电流音的大笑声。")
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("不知道这只小猫咪自己想要谁做主呢……可以的话，我也想尝试饲养呢~", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("……", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("……", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("作为小怜的监护人，我拒绝二位的要求。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉笑了笑。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("不过——", "莉琉")
	await novel_interface.show_dialog("既然元老院对小怜如此看重\n我倒有一个提议……", "莉琉")

	print("=== 深海恐惧篇第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
