# bathophobia_ep08.gd - 深海恐惧症篇第8话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep08_script()

func play_script():
	pass

func bathophobia_ep08_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("随着莉琉在手持终端上的几次点按，蓄水池底部传来低沉的开闸声，水位随之迅速下降。")
	await novel_interface.show_text_only("我们才发现蓄水池有十几米深，原先的岸边沿立刻成为了悬崖。")
	await novel_interface.show_text_only("随着水位下降，悬崖另一侧的基台上升起一座蓝色的石碑。")
	await novel_interface.show_text_only("周围的照明设施依次开启——我才看清那个石碑的轮廓，正是『特斯海姆青金石柱』。")
	novel_interface.show_character("ren_battle","blush")
	await novel_interface.show_dialog("哇…", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("对岸是一片宽幅超过标准足球场的广阔空间，几排数十米高的巨型柱子一直延伸到黑暗中。")
	await novel_interface.show_text_only("近百米的屋顶上的照明设施虽然能照亮近处，但光线依然无法达到深邃的远端。")
	await novel_interface.show_text_only("夸张的建筑尺度给人一种恐怖的压迫感。")
	await novel_interface.show_text_only("前方基台四角的指示灯提醒着我们周围存在着电磁防壁。")
	await novel_interface.show_text_only("一条通道从我们这一侧的岸边缓缓伸出。")
	novel_interface.show_character("ren_battle","timid")
	await novel_interface.show_dialog("（……好帅！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我不禁想起某款射击游戏里的开场剧情。")
	await novel_interface.show_text_only("跟随着莉琉的脚步，我们踏上通往操作台的可变通道。")
	await novel_interface.show_text_only("只有当人踩在上面的时候，踏板才会伸出，平时通道踏板只会老老实实地收在墙体内——")
	await novel_interface.show_text_only("这种设计，就像要故意阻止人靠近或者离开一样。")
	await novel_interface.show_text_only("我四处张望，注意到了顶部几处封闭式小型重武器发射口。")
	await novel_interface.show_text_only("回想着一路走进来的情景，我试图在脑中还原这个庞大地下设施的结构。")
	novel_interface.show_character("ren_battle","uneasy")
	await novel_interface.show_dialog("……你花起钱来，真是毫不手软。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("虽然征用这里进行改造的难度不小，但是能在短期内达到方舟计划安全标准的，也只有这里了。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉所说的“安全标准”，就是万一召唤出强大且有敌意的魔女或者其它什么存在的时候——")
	await novel_interface.show_text_only("为了确保学园都市的安全，元老院需要能确保将其控制并消灭在设施内的标准。")
	await novel_interface.show_text_only("然而面对未知的威胁，这种所谓的标准也只是提供了最大的程度的心理安慰而已……")
	await novel_interface.show_text_only("莉琉在之前的行动会议上是这么说的。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("还呆着做什么？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我们一路走到操作台前，虽然知道踏板会自动追踪脚步，但十几米的高度还是让我有些紧张。")
	await novel_interface.show_text_only("前方的基台上，由四只机械爪托起的，就是那个比我还高一些的青金石柱。")
	await novel_interface.show_text_only("网上看照片与身临其境看到实物相比，所带来的震撼完全不可同日而语。")
	await novel_interface.show_text_only("半透明的碧蓝色石碑表面，刻画着由粗细均匀的线条构成的图形。")
	await novel_interface.show_text_only("这些图形像是以独特的逻辑排列的字符，但考古学家一直没能成功破译。")
	await novel_interface.show_text_only("同心圆、轴体、等高线——与其说是有实际意义的暗号语言，更像是想直接传达某种概念。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("这是国宝级的文物吧……第一次实验要不先换个别的什么东西来……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("哦？怯场了？", "拉斐尔")
	await novel_interface.show_dialog("要是搞砸了，你知道是什么下场吧——", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔用威胁的口气说道。")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("不不，只是觉得太奢侈了……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("那么，现在解除电磁防壁——", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉干脆地将操作台上的红色拉杆拉下来，防护装置的四角的红灯同时熄灭。")
	await novel_interface.show_text_only("我感到头皮一阵酥麻，好像一股微弱的电流突然扫过大脑皮层般。")
	novel_interface.character_light(0.35,"serious")
	await novel_interface.show_dialog("怎么样？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("应该是魔法刻印，但……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我目不转睛地盯青金石柱，总觉得有些异样。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("看来你身体的反应还是很敏感呢。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("莉琉，别当着……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我扫了一眼拉斐尔，她正用看变态的眼神看着我。")
	novel_interface.show_character("ren_battle","shy_left")
	await novel_interface.show_dialog("不要说这种会让人误会的话啊！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("安全起见，我再向你们说明一下电磁防壁的操作方方法。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉面朝拉斐尔和安妮，示意她俩到操作台前，眼神却落在了我身上。")
	novel_interface.show_character("ren_battle","solemn")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（表演要开始了吗……）", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("这座控制台和周围的柱子上布置了几十种传感器和全光谱摄像机，在隔离箱打开以后会自动运行。", "莉琉")
	await novel_interface.show_dialog("数据和影像资料都会直接发送到观察室，在实验结束后这些数据会与萨蒙顿的研究机构共享。", "莉琉")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("莉琉向我眨了一下眼睛。")
	novel_interface.character_light(0.35,"speechless")
	await novel_interface.show_dialog("（说得好像真的一样……）\n（明明早就准备好了伪造数据……）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我抬头看了看附近柱子顶部的观察室。")
	await novel_interface.show_text_only("单向防爆玻璃上并不会显示任何人影，只是冷淡地反射着环境光。")
	novel_interface.show_character("ren_battle","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（元老院的人，应该就在那里吧……）", "小怜")
	await novel_interface.show_dialog("（希望能瞒过他们……）", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("隔离箱和栈桥的控制方式也很简单，使用这边的机械开关和齿轮摇杆。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮在莉琉的引导下，逐一确认了操作台的控制方法。")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("好久没见到过机械开关了，居然还有摇杆……\n为什么要用这么古老的控制装置？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("有时机械构造的装置反而是最稳定的，稍微忍耐一下吧~", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("那么，我一会就会回到指挥室，还有什么问题吗？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("（要、要开始了吗……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我感到心跳加快，开始做深呼吸调整。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("……很紧张？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("仿佛看穿了我的不安，莉琉走近用一只手臂从身后揽住我，温柔的说道。")
	await novel_interface.show_text_only("我被她在众目睽睽之下突然做出的亲密动作弄的不知所措，脸颊顿时像灼烧一般。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("是、是有点……", "小怜")
	await novel_interface.show_text_only("我的心跳更快了啊！！")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（演戏什么的，我真的很不擅长啊！只在小学表演的《汤姆叔叔的小屋》中扮演过小屋……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉侧过头，眼神扫过上面的观察室。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("是吗……", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("她的呼吸弄得我的耳根发麻，好像有一根神经从耳后贯穿全身到脚后跟，能将这种感觉传遍全身。")
	novel_interface.character_light()
	await novel_interface.show_dialog("放心吧，一会元老院不会看到这里发生了什么的。", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉以近乎耳语的方式对我说。")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("我们头顶20米的地方，布置了一层光学迷彩。", "莉琉")
	await novel_interface.show_dialog("而且观察室的玻璃隔层也做了特殊处理，只会让他们看到“应该”看到的部分……", "莉琉")
	await novel_interface.show_dialog("在拉斐尔关闭防护装置之后，你们就会在他们的视野中消失，就像进入了异变空间一样。", "莉琉")
	await novel_interface.show_dialog("之后你只要尝试接触青金石柱就可以了，就算无法按照原计划召唤出魔女也没关系……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("耳边传来轻笑声，莉琉对着我的耳朵吹了一口气 我刚发现的那根神经再次表示强烈抗议。")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("呀~！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("不过，如果召出了什么不妙的家伙……\n最差的情况，你知道怎么做吧？", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我吞了吞口水。")
	novel_interface.show_character("ren_battle","solemn")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("只要传感器超过警戒阈值，就会自动触发封锁和销毁程序……", "小怜")
	await novel_interface.show_dialog("五秒之内，我们必须从右侧的地板上的安全门进入地下的隔离区。", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我的视线划过行动会议中提到的逃生路线。")
	novel_interface.show_character("ren_battle","solemn")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("liliu_uniform2","serious",0.25)
	await novel_interface.show_dialog("准确地说，你们的逃生时间只有四秒八。", "莉琉")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（稍有迟缓，海水瞬间就会灌满整个基地）\n（更别提头顶还有武器系统……）", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("不过根据对青金石柱的背景调查……", "莉琉")
	await novel_interface.show_dialog("它曾经的主人是一位比较稳定的和平主义者，只是比较神秘，换过很多假名。", "莉琉")
	await novel_interface.show_dialog("所以没准召唤出一个黄毛大叔也说不定。", "莉琉")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("召唤出大叔的话就交给拉斐尔带回萨蒙顿好了！！")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("总之，一切要以你们的安全为最优先。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉松开手，摸了摸我的头。")
	novel_interface.show_character("ren_battle","wail")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("注意保护好自己……我会看着你的。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("随着提醒实验启动的声音响起，我再次望着安静的立在基台上的青金石柱。")
	novel_interface.show_character("ren_battle","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("计划，能成功吗……", "小怜")
	# 在这里添加剧情脚本内容
	
	print("=== 深海恐惧症篇第8话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
