# bathophobia_ep14.gd - 深海恐惧篇第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep14_script()

func play_script():
	pass

func bathophobia_ep14_script():
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/falling.png")
	await novel_interface.show_text_only("一片纯白之中。")
	await novel_interface.show_text_only("眼前渐渐浮现出模糊的轮廓，似乎身边的一切都在被加速，就像正从万米高空极速坠落。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("双脚终于触到地面的瞬间，却丝毫没感到任何冲击力，只觉得两侧耳压突然升高带来的强烈不适。")
	await novel_interface.show_dialog("好痛……", "小怜")
	await novel_interface.show_text_only("从吸入的第一口空气，就明白自己已经脱离了那个空间回到了现世，因为周围的空气实在是……")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("好冷冷冷冷冷冷冷冷冷——！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("还没睁开双眼，身体就被刺骨的严寒包围，小腹传来阵阵坠痛。")
	await novel_interface.show_text_only("睫毛动一动也会传来阵阵刺痛，好像已经结了冰，连睁眼都十分费力……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/snowfield.png")
	await novel_interface.show_text_only("终于恢复了视线，只见四周都被银白覆盖，吸入的寒冷空气让气管如刀割般疼痛。")
	await novel_interface.show_text_only("一股冷空气被呼入喉咙，我忍不住咳嗽起来。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("呼——咳咳、咳咳咳！", "小怜")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("过去多久了，已经是夜里了吗？\n我们这是在哪……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("严寒令人丧失思考能力，我感到身体的热量正在迅速流失，身体开始无法控制的颤抖。")
	await novel_interface.show_text_only("而身旁的海因里希不知怎么却露出了兴奋的表情。安妮和拉斐尔则晕倒在我右侧的雪地上。")
	novel_interface.show_character("ren_battle","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("heinrich_battle","smile",0.25)
	await novel_interface.show_dialog("……主人这么怕冷吗？", "海因里希")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("海因里希轻轻握住了我的手。")
	novel_interface.character_light(0.35,"blush")
	await novel_interface.show_dialog("诶……？", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("一股暖流从她身上传递过来，我瞬间有了坐在炉火旁的错觉。")
	await novel_interface.show_text_only("我惊讶地看着这个穿的比我更少的金发少女，对方松开双手，留在我手心几枚橙黄色的石头。")
	novel_interface.character_light(0.35,"worry")
	await novel_interface.show_dialog("这是……？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("拿着这些暖玉，你会好受些。", "海因里希")
	novel_interface.hide_all_characters()
	await novel_interface.show_text_only("玉石质地的晶体虽然并不烫手，但却能散出一股包裏全身暖意。")
	await novel_interface.show_text_only("我捧着它们，在冰天雪地的荒原中，却仿佛置身于温暖的室内。")
	await novel_interface.show_text_only("这种体感上的违和让我不禁产生了或许周围都是室内布景的错觉。")
	novel_interface.show_character("ren_battle","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("heinrich_battle","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("好厉害……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("只是用炼金术和能量转换的刻印造出的小玩意。", "海因里希")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("海因里希虽然说得无所谓，但脸上的表情却透露着得意的神情。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("不不不，这已经不能叫做小玩意了……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("是呀……即使在今天，人工制造这种接近异质物效果的材料也是最尖端的保密技术。")
	await novel_interface.show_text_only("我拿着暖玉，往拉斐尔和安妮手里也塞了几块。")
	await novel_interface.show_text_only("伸手碰触，能感觉到她们两人的体温正在上升。")
	await novel_interface.show_dialog("咳、咳咳……", "拉斐尔")
	await novel_interface.show_dialog("唔……哈啊……", "安妮")
	await novel_interface.show_text_only("随着几声咳嗽，安妮和拉斐尔都醒了过来。")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("你们没事吧？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮和拉斐尔迷迷糊糊的点了点头，我长呼了一口气。")
	await novel_interface.show_text_only("我开始打量四周的环境，地面是被冻得硬邦邦的沙砾土层，上面覆着薄薄的积雪。")
	await novel_interface.show_text_only("这样的地形环境就像由计算机刻意生成的一般，空旷寂静的有些诡异。")
	await novel_interface.show_text_only("海因里希在一旁自言自语的思考着。")
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("刚才怎么脱离那个空间的…………", "海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("不，不能说是脱离，是『因果之隙』被强行的改变了形态。", "海因里希")
	await novel_interface.show_dialog("可即使是『那位』对我进行强制传送的时候，都要遵守因果法则——", "海因里希")
	novel_interface.change_expression("perspire")
	await novel_interface.show_dialog("难道说她……", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希的视线不由自主的转向对面的小怜。")
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("哇啊~~明明是真雪，却一点都不觉得凉。", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("我饶有兴致的攒了个雪球，但看了看她们几个，决定还是把雪球丟到地上吧……")
	novel_interface.character_light(0.35,"wail")
	await novel_interface.show_dialog("（傻透了……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("忽然一阵寒风吹来，呼啸中夹杂着大量的冰晶扑到我脸上。")
	await novel_interface.show_text_only("在温玉的加持下，我没有感到一丝寒冷。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("这里到底是……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我站起身，脚下是平坦的雪原。")
	await novel_interface.show_text_only("远方无尽的冰川山脉，顺着冻土雪原的边缘攀升。")
	await novel_interface.show_text_only("光线变幻的天空本应被夜色完全渲染。")
	await novel_interface.show_text_only("然而——")
	await novel_interface.show_text_only("在空中，一条漫无边际的炫彩光带一直蜿蜒延伸到无限远处。")
	await novel_interface.show_text_only("蔓延的光带淡入星空，流淌着绿色的荧彩，柔粉和浅紫点缀其中，将整个天空一并照亮。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("（这是……极光？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("曾在网上看到的照片，完全无法比拟身临其境所带来的强烈冲击感。")
	await novel_interface.show_text_only("纯净的星空，苍白的大陆，以及漂浮的绚丽光芒。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("我们这是……在北极圈？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不、不可能吧？！")
	await novel_interface.show_text_only("海因里希摇了摇头。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("（我就说嘛……应该是3D成像之类的……）", "小怜")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("这个模拟的效果还不错嘛，连温度和触感……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("这里是南极。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("………", "小怜")
	await novel_interface.show_dialog("（等待，她刚才说南极……）\n（就是有企鹅的那个……？）", "小怜")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("……哎哎哎？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("南极？！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("生命之树的第九原质所对应的区域。", "海因里希")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","upset",0.25)
	await novel_interface.show_dialog("你们刚才在那里就提到的『生命之树』和『原质』到底是……", "小怜")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("传说『生命之树』是神创造宇宙的蓝图，或者称之为神体的构造图。", "海因里希")
	await novel_interface.show_dialog("而所谓的原质……就是支撑生命之树的十个支柱。", "海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("至少『那位』是如此声称的——", "海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("但从海因里希的表情看来，她自己对这套解释并不买账。")
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("所以『第九原质』……南极，就是这次出现问题需要守护的区域？", "小怜")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_text_only("在这鸟不拉屎的地方要守护什么啊！海豹吗！？")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("根据以往的经验，即使人迹罕至的区域，也可能酿成末日级灾难。", "海因里希")
	await novel_interface.show_dialog("相比自然的力量，人类之间的纷争太渺小了。", "海因里希")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("不过……我们似乎并没有落到准确的地点。", "海因里希")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("哎？", "小怜")
	novel_interface.character_move_right(0)
	novel_interface.change_expression("smile")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_dialog("换句话说，现在我们是自由的。", "海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("海因里希对我微微一笑，目光明亮。")
	novel_interface.character_light()
	await novel_interface.show_dialog("虽然是在这种地方，而且或许只有片刻，但长久以来我第一次获得了自由。", "海因里希")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("现在『那位』应该非常懊恼吧……哈哈哈哈", "海因里希")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("而这些——都是你造成的，小怜。", "海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("海因里希双手向上，向我微微鞠躬。")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("诶？我……我做了什么吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("（对自己的能力一无所知吗……嘻嘻，有趣。）", "海因里希")
	await novel_interface.show_dialog("能凌驾于『那位』的规则——", "海因里希")
	await novel_interface.show_dialog("主人必是早已将真理刻印在灵魂之中了。", "海因里希")
	await novel_interface.show_dialog("这是我毕其一生所追求的境界。", "海因里希")
	await novel_interface.show_dialog("到底付出了怎样的牺牲，才能获得这样的成就呢？", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("成就什么的我不知道……", "小怜")
	novel_interface.change_expression("wail")
	await novel_interface.show_text_only("但是牺牲，非常大啊！！")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("总、总觉得风越来越大了，我们先找个地方躲一下吧~", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","upset")
	await novel_interface.show_dialog("前面……有一个补给站……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮虚弱的声音从旁边传来。")
	await novel_interface.show_text_only("她晃晃悠悠的踩在高地上，右手笔直的伸向前方。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Depot1.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("这是一栋并不算大的环形结构建筑，底部做了十米多高的防雪暴架空层。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("大面积金属框架结构镶嵌双层耐寒玻璃……", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("在极地还要坚持如此不实用的极简风格，只有那群北欧佬做得出来。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("补给站一层连接阶梯的钢索已经断裂，浮动的台阶散落了一地，只留下了两条光秃秃的扶手。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("请问……有人吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("笨蛋，好好看看出入口的情况，这种高热量逸散的站点在极夜期间怎么可能会有人。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔一说我才反应过来，南极圈内的黑夜要持续半年，从刚才可能并没经过太长时间。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("——安妮？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("从因果之隙出来后，安妮的脸色一直不对劲，进入补给站后似乎已经到了极限。")
	await novel_interface.show_text_only("一直紧绷的神经突然松开让她身体失去控制跌倒在了地上，我连忙扶起她。")
	await novel_interface.show_dialog("呼……", "安妮")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("一层没有通讯设施，得想办法搞定这个楼梯。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("想要去二层吗？", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我还没来得及反应，就看到海因里希走到了楼梯扶手旁。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("（嘟嚷）唔……是没见过的材料呢……", "海因里希")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("不过仅仅只是重塑的话还是很简单的~", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希拿起断裂的钢索和一颗宝石样子的东西。")
	await novel_interface.show_text_only("随着她变换的手势，斑驳的裂口被扭曲拉长，然后缓慢平稳地连接到了一起。")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("这就是炼金术吗……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一贯高傲的大小姐也不由赞叹起来。")
	await novel_interface.show_text_only("海因里希接着双手握紧钢索，身上的战服开始闪烁流溢的色彩。")
	await novel_interface.show_text_only("只见她用力一拉，钢索再次绷紧，十几级铜质阶梯被带动着拉回到了原来的位置。")
	await novel_interface.show_text_only("之后海因里希利落的将钢索在一层地板的栓扣上重新固定好，就好像在固定毛线团一样轻松。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("好大的力气！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("嘛……对于炼金术士而言，这套战服的强化能力有时还是蛮好用的~", "海因里希")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("毕竟有时要对付超乎想象的……麻烦。", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("将安妮安置在沙发上休息，我们三人拾级而上……")

	print("=== 深海恐惧篇第14话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
