# bathophobia_ep16.gd - 深海恐惧症篇第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep16_script()

func play_script():
	pass

func bathophobia_ep16_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Depot1.png")
	await novel_interface.show_text_only("拉斐尔在二楼找到几箱低凝点柴油，大概够支持补给站几天的运作。")
	await novel_interface.show_text_only("伴随着发电机的轰鸣，电力供应恢复了，我立刻冲进了洗手间。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("（实在不想在黑漆漆的环境中坐在马桶上……）", "小怜")
	await novel_interface.show_dialog("（还好那群人没有把这里也设计成玻璃的。）", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("真要命……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我捂着肚子从洗手间出来，看到安妮已经稍微恢复精神站了起来")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("安妮，你还好吗？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_normal","normal2",0.25)
	await novel_interface.show_dialog("没关系，我们去通讯室看看…", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我扶着只能勉强支起身体的安妮，来到二楼。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Depot2.png")
	await novel_interface.show_text_only("通讯室的内部依然是极简构造，T字型的过道贯穿了房间中部，一直连接到观察区的弧形墙壁。")
	await novel_interface.show_text_only("房间的储藏柜里找到很多饮用水、罐头和长保质期食品。")
	await novel_interface.show_text_only("这里的空气状况似乎也不错，透过贯穿墙壁的窗子能看到外面夜空中跳动着的极光。")
	novel_interface.show_character("anne_normal","upset")
	await novel_interface.show_dialog("不知道系统还能不能工作……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她试着启动操作台上有些陈旧的设备，还好以可靠性为前提配置的硬件依然能够运作。")
	await novel_interface.show_text_only("受过SID训练的安妮对这个系统并不陌生，补给站外部的通讯天线也没受到低温的太大影响。")
	await novel_interface.show_text_only("环绕墙壁的换气口，缓缓涌出一股湿润的暖风。")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("应该是制热系统在运作了吧？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我望了一眼墙上的温度提示，室内温度从零度起逐步上升。")
	await novel_interface.show_text_only("而室外温度……零下四十二摄氏度？？")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("还好有海因里希的温玉……", "小怜")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("（在零下四十二度的环境中，穿着短裙玩雪）", "小怜")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("（……我似乎解锁了不得了的成就。）", "小怜")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("啊…还是快点联络上莉琉救我们回去吧~", "小怜")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("（说起来，这芯片是坏掉了吗？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我忍不住摸了摸胸口，从来没如此期望这里能传出莉琉的声音。")
	novel_interface.show_character("anne_normal","normal1")
	await novel_interface.show_dialog("卫星连接中……搞定！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在安妮的指示下，我在操作台输入了早已铭记于心的字符串。")
	await novel_interface.show_text_only("还好莉琉强迫我背下了SID的加密特征码。")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("有意思，原来是这样——", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("从进入补给站开始，海因里希就饶有兴致的四处观察着各种材质和物品。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("早就想亲手摸摸看了——", "海因里希")
	await novel_interface.show_dialog("砂石、铝、钙、可燃金属及玄武岩的组合…", "海因里希")
	await novel_interface.show_dialog("再加以纤维化，性质就变得不一样了。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("嗯？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("这些玻璃的组成方式，与我熟悉的形态不一样。", "海因里希")
	await novel_interface.show_dialog("用这种方法就可以阻断热量流失……有趣。", "海因里希")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("不过还是炼金术能量转换的刻印解决方案更优秀~", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("刻印……那属于魔法了吧？", "小怜")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("（造个玻璃而已，搞不好会疯掉的！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("不过刚才在那边看到的橡胶制品确实高明，在小袋子里装着的，延展性十分惊人。", "海因里希")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("还有水果的香味……那是做什么用的呀？", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("……不、不知道！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("是口香糖罢了，变态。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔给了我一个白眼——")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("呜呜呜，海因里希那家伙，完全沉浸在自己的世界里了啊！")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("回到总部的莉琉，正和爱衣搜索着小怜的下落。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("卫星集群还没找到小怜的定位芯片，明明是覆盖全球的搜索范围……", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("难道是被传送到了地球外或者进行了时间跳跃？", "爱衣")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","serious",0.25)
	await novel_interface.show_dialog("如非必要，勿增实体——要先考虑最基础的情况。", "莉琉")
	await novel_interface.show_dialog("所谓的『全球卫星』，其实轨道只覆盖了北纬70度到南纬70度的范围。", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你是说——", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("突然，SID的加密通讯弹出了连接提示。")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("喂、喂——？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("莉琉！！\n总算联系上了——", "小怜")
	await novel_interface.show_text_only("听到熟悉的声音，莉琉的神色也放松下来，很快恢复到了平时的状态。")
	await novel_interface.show_text_only("她盯着依旧显示离线状态的定位信号，立刻开启了反向追踪程序。")
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("小怜？你在哪？\n其他人和你在一起吗？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("嗯嗯，我们在一个补给站。\n拉斐尔和安妮都在很安全，只是——", "小怜")
	await novel_interface.show_dialog("我们现在……在南极。", "小怜")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("……", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	await novel_interface.show_dialog("——南极？？！！", "爱衣")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("虽然惊讶，但莉琉的神色之中并没有任何动摇。")
	novel_interface.character_light()
	await novel_interface.show_dialog("（小怜的声音听起来没有失温的症状）\n（她们现在应该在安全的地方）", "莉琉")
	await novel_interface.show_dialog("（是方舟基地的实验中出现了空间跃变吗？）", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("荧幕上，通讯地址追踪的结果已经弹出，位于南极圈内伊丽莎白公主地的2号联合补给站。")
	novel_interface.show_character("liliu_uniform2","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("果然……除非刻意变轨，一般的近地卫星是不会扫过那个区域的。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("因为极地的太阳风会影响到数据传输嘛~", "爱衣")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("唔，果然是我疏忽了——", "爱衣")
	await novel_interface.show_dialog("要调用南极上空的卫星吗？", "爱衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯，注意别引起那几个老家伙的注意。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("总之，我也不知道怎么回事就被带到这里了。", "小怜")
	novel_interface.show_character("liliu_uniform2","speak")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("ai","normal",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("……除了你们三个，还有什么人吗？", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("海因里希吗？\n她就在我旁边——", "小怜")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Depot2.png")
	await novel_interface.show_text_only("靠这些老旧的设备能顺利联系到莉琉，让我安心了不少。")
	await novel_interface.show_text_only("我把目前的情况向莉琉做了简报。")
	await novel_interface.show_dialog("……情况大致了解了。", "莉琉")
	await novel_interface.show_dialog("听着，你们现在的位置很靠近南极点，要去接你们的话有点麻烦。", "莉琉")
	await novel_interface.show_dialog("根据战后《新南极公约》，想要向南极派遣五人以上的考察队——", "莉琉")
	await novel_interface.show_dialog("或者使用飞行工具进入南极圈，必须向联合议会申请并获得批准。", "莉琉")
	await novel_interface.show_dialog("再加上中途恐怕要在新澳大利亚停靠……", "莉琉")
	await novel_interface.show_dialog("就算安排物资在一小时内立刻起飞，所有手续都在路上办理，也需要大约四十个小时。", "莉琉")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("没问题，这边的发电机能维持几天，食物也还算充足。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("离你们最近的专用停机坪在东经76度55分，南纬6\n8度24分，距你们现在的位置大约一公里。", "莉琉")
	await novel_interface.show_dialog("我们会在那个位置降落，但南极天气情况复杂，如果中途通讯中断，就默认那里为一级汇合点。", "莉琉")
	await novel_interface.show_dialog("那是个规模很大的站点，大部分设施在地下…… 　叫做Snedronningen——白皇后基地。", "莉琉")
	await novel_interface.show_dialog("具体安排……会另行通知，小怜，现在……嘶嘶…\n…", "莉琉")
	await novel_interface.show_text_only("莉琉的声音突然被一串电流杂音覆盖。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("莉琉！喂喂——", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_dialog("——听……到吗？喂？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("通讯中心的杂音越来越强。")
	await novel_interface.show_dialog("可能有太阳风——标记……最好，能够确认一下信号？？", "莉琉")
	await novel_interface.show_text_only("哗——")
	await novel_interface.show_text_only("随着电流杂音的加剧，莉琉的声音从传输中消失。")
	await novel_interface.show_text_only("四周一片寂静。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("我们恐怕……又失联了……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("四十个小时？你最好祈祷这段时间内，不会再出现什么意外。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("但我总觉得有些不妙。")
	await novel_interface.show_text_only("与信号一起消失的，还有窗外的极光，甚至窗外隐约的风声都停止了。")
	await novel_interface.show_text_only("房间里只有电脑散热器和空调风扇的声音。")
	await novel_interface.show_text_only("这样的寂静给我一种风雨欲来的感觉……")
	await novel_interface.show_text_only("我眼前的操作台突然晃了一下。")
	await novel_interface.show_text_only("不，不对，是我没有站稳。")
	novel_interface.show_character("anne_normal","panic")
	await novel_interface.show_dialog("……你们有没有感觉……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("难道你也……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("原本轻微的摇动，逐渐变得强烈起来。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("……不、不是吧！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我扶住了操作台，心里有些紧张。")
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("这是……？", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一阵怒吼般的巨大异响从我们脚下传出。")
	await novel_interface.show_text_only("建筑开始剧烈的晃动，我们几乎站不稳脚跟。")
	await novel_interface.show_text_only("桌面上的所有物品，都像跳跳糖一样变换着位置。")
	await novel_interface.show_text_only("远处的冰山传来轰隆隆的崩裂的声音。")
	await novel_interface.show_text_only(" 我望向窗外，果然——")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("——是地震！！？", "小怜")
	print("=== 深海恐惧症篇第16话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
