# bathophobia_ep20.gd - 深海恐惧症篇第20话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep20_script()

func play_script():
	pass

func bathophobia_ep20_script():
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Snedronningen_Exhibition_Room.png")
	await novel_interface.show_text_only("特遣队一边躲避着未知敌人的疯狂攻击，一边试图呼叫支援。")
	await novel_interface.show_text_only("基地入口还在继续涌入更多的敌人，队员们暗自庆幸刚才没有回到冰原上。")
	await novel_interface.show_text_only("以这些敌人的行动力，恐怕小队已经在完全没有掩护地形的雪原中被围歼了。")
	await novel_interface.show_text_only("但现在他们只能继续深入基地，寻找可以进行战术防御的有利位置并呼叫支援。")
	await novel_interface.show_text_only("小队且战且退，从展览室的侧门来到了一条走廊。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Corridor.png")
	await novel_interface.show_dialog("糟糕，这里信号已经连不上了。","特遣队员C")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("你们先去控制室，那里可能有通讯设备！","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("好！","特遣队员C")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("我看过这里的立体结构图……\n朝八点钟方向下行！","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然队员的身上都出现了或深或浅的伤口，但大家依旧默契的以前后两个小组互相掩护着前进。")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("（这群家伙的恢复力……太奇怪了……）","白烛")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("milk_battle","shock",0.25)
	await novel_interface.show_dialog("——小心！！！","牛奶")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛稍走神的功夫，后面追击而来的敌人突然反向转动关节，巨大刀刃以刁钻诡异的角度劈了过来。")
	await novel_interface.show_text_only("情急之下的牛奶一把将白烛推进后面的资料室内。")
	await novel_interface.show_text_only("敌人的攻击落空，但巨刃仍在资料室门口的地砖上划出一道巨大的裂痕。")
	await novel_interface.show_text_only("这道印记仿佛天堑，隔断了小队前后的两组人。")
	await novel_interface.show_dialog("啊！！！","特遣队员D")
	await novel_interface.show_text_only("最靠近持巨刃敌人的代号“Mute”的特遣队员上前掩护时，用身体接下了紧接的又一次攻击。")
	novel_interface.show_character("milk_battle","shock")
	await novel_interface.show_dialog("——Mute！！！","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("“Mute”，那个平素里吊儿郎当，总喜欢穿着夏威夷衬衫，每次牛奶开赌局都会输钱的笨蛋。")
	await novel_interface.show_text_only("已经很长时间没叫那家伙的代号了，没想到再次脱口而出，却是在这种时候。")
	await novel_interface.show_text_only("一道鲜血喷洒在走廊的墙壁上……")
	await novel_interface.show_text_only("Mute手中的改装MP5K落在地上，打了几个转， 滑在牛奶脚下。")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("——混账！！！","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("被改装过的冲锋枪后座力变轻，足以让牛奶单手持握并倾泻出所有的子弹。")
	await novel_interface.show_text_only("随后牛奶掏出匕首，将那名身中数弹正在靠绿色液体恢复伤口敌人的脖子死死钉在了墙上。")
	await novel_interface.show_text_only("手持防暴盾的队员立刻挺身顶上，牛奶马上扶起队友按住他颈部的伤口。")
	await novel_interface.show_text_only("在冰冷的环境下，队友大动脉喷涌而出的鲜血像开水一样冒出大量的水汽。")
	novel_interface.show_character("baizhu_break","angry")
	await novel_interface.show_dialog("急救包呢？快给我止血喷雾！","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哈——啊——","特遣队员D")
	await novel_interface.show_text_only("其实大家都知道，这些或许都是徒劳……")
	await novel_interface.show_text_only("止血喷雾和血液混在一起，快速阴红了伤口处的止血棉，顺着牛奶的手不断滑落到地面上。")
	await novel_interface.show_text_only("与此同时，远处更多的敌人已经循音冲到了走廊。")
	await novel_interface.show_text_only("挡在众人前方的防暴盾在承受了多次冲击后，已经逐渐出现裂痕。")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("可恶……","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("回来支援的三名队员展开了一轮掩护射击，牛奶拖着受伤的队友，想要进入前面转角处的资料室。")
	await novel_interface.show_text_only("走廊冰冷光洁的甲板上，拉出了一道长长的血印。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Dark.png")
	await novel_interface.show_text_only("终于将Mute拖到房间内，牛奶伸手测他的颈动\n脉。") #换行问题
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("——肾上腺素！！","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛上前扯开被染红的雪地服，用手指在左胸找好位置，取出肾上腺素迅速插入了他的胸腔。")
	await novel_interface.show_text_only("心腔内穿刺注射给队友带来了一瞬的转机，Mute 脸上闪过一丝血色。")
	await novel_interface.show_dialog("咳、咳咳——\n嘶——","特遣队员D")
	await novel_interface.show_text_only("然而几秒钟后，血液流失的速度已远远超过身体能承受的极限。")
	await novel_interface.show_text_only("Mute的脸上再一次逐渐褪去血色，瞳孔开始涣\n散。")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("……","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶的眼中泛起了泪花。")
	await novel_interface.show_text_only("白烛轻轻按住牛奶依然压在队友伤口上的手，深吸一口气，什么也没有说。")
	await novel_interface.show_dialog("不行了，我们得马上撤！","特遣队员C")
	novel_interface.show_character("baizhu_break","speechless")
	await novel_interface.show_dialog("牛奶！","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶咬了咬牙，捡起Mute刚才在展览室拼命抢回来的样本箱。")
	await novel_interface.show_text_only("这样的绝境中队伍一旦开始减员，剩下的人恐怕也凶多吉少。")
	await novel_interface.show_text_only("尽管没人愿意承认，但这就是眼前的现实。")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("那边的安全通道，撤！","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("我断后！","特遣队员B")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BTB.png")
	await novel_interface.show_text_only("少女们背靠着背警戒。")
	await novel_interface.show_text_only("牛奶握紧手中的枪，努力将危险的一面留给自己。")
	await novel_interface.show_dialog("（为什么……会这样……）","白烛")
	await novel_interface.show_text_only("根据白烛的调查，“Ningen”派来南极的，应该只是一支普通的探测小队。")
	await novel_interface.show_text_only("而眼前这群敌人的战斗能力，已经完全超出了她的预计。")
	await novel_interface.show_dialog("（是我……没有想到吗？）","白烛")
	await novel_interface.show_dialog("（不，我想到了的。）","白烛")
	await novel_interface.show_dialog("（我明明知道……）\n（这样下去，利用他们……很危险……）","白烛")
	await novel_interface.show_dialog("（但却还是……）","白烛")
	await novel_interface.show_text_only("——注意到白烛的动摇，牛奶贴紧了她的后背。")
	await novel_interface.show_text_only("隔着雪地服，体温并不会传递过来，而白烛却感到了一丝温暖。")
	await novel_interface.show_dialog("不要怕。","牛奶")
	await novel_interface.show_dialog("……","白烛")
	await novel_interface.show_dialog("我在这里。","牛奶")
	await novel_interface.show_text_only("——“不要怕，我在这里。”")
	await novel_interface.show_text_only("白烛回过神来，视线落在了小队其余的成员身上。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Corridor.png")
	await novel_interface.show_text_only("在汹涌而来的敌人面前，手持防爆盾的队友只能勉强对两个女孩比了个“快撤”的手势。")
	await novel_interface.show_text_only("这些浴血奋战的人，了解自己的对手是什么吗？")
	await novel_interface.show_text_only("他们又了解自己的上级在做什么吗……")
	novel_interface.show_character("baizhu_break","sad")
	await novel_interface.show_dialog("抱歉，是我判断失误……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("都这时候了，还说这些？","特遣队员B")
	await novel_interface.show_text_only("对方用给白烛一个自行领会的媚眼。")
	await novel_interface.show_dialog("回去以后，至少要承包我十年份的龙舌兰吧？","特遣队员C")
	await novel_interface.show_text_only("其他队员居然也在只能勉力支撑的战场中努力安慰着自己。")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("——小心！","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶压低了白烛的左肩，用没有弹药的冲锋枪挡住袭来的镰刀。")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("这群家伙也太难缠了！！","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("敌人仿佛豹猫一般，轻松地跨越了防爆盾掩护下的缓冲区。")
	novel_interface.show_character("baizhu_break","puzzled")
	await novel_interface.show_dialog("因为，是Ningen（人类）啊……","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("witch_third")
	await novel_interface.show_dialog("Nin——gen……嘻嘻嘻嘻……\n给我……去死！！……","？？？")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到白烛口中的词，战斗力最强的敌人露出仿佛要裂至耳根的危险笑容。")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("可恶……这群家伙……\n完全挡不住了……","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("白，你们快撤，这边还能再撑一会！！！","特遣队长")
	await novel_interface.show_text_only("话音未落，巨镰携着刺骨的风刃挑飞了防爆盾，失去掩护的众人开始快速连射。")
	await novel_interface.show_text_only("特遣队员们勉强躲避着攻击。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BaizhuBattle.png")
	await novel_interface.show_text_only("突然，一把造型奇特的剑刃结结实实的挡住袭向牛奶的镰刀。")
	await novel_interface.show_text_only("白烛身上突然散出数十个银白色的光团，冲向袭来的敌人，在对方身上留下被冻伤一样的白点。")
	await novel_interface.show_text_only("绿色粘液无法修复冰冻的创面，枪刃射出的霰弹打上去，敌人顿时碎裂成为几块。")
	await novel_interface.show_text_only("随后白烛如魅影般出现在牛奶身侧，翻身凌空跳起向围上来的敌人瞬间打出数十枪。")
	await novel_interface.show_dialog("……小……白烛？","牛奶")
	await novel_interface.show_text_only("楞在原地的牛奶眼中映射出好友的武器上，正不断跳动着奇异的白色光团。")
	await novel_interface.show_text_only("冷兵器的刺击甚至比子弹还快，白烛左手的重剑上也浮起了旋转的纹路。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("与此同时，南极大陆再次出现了轻微的晃动。")
	await novel_interface.show_text_only("而陷入酣战中的人们，却并未察觉到……")
	
	print("=== 深海恐惧症篇第20话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
