# bathophobia_ep21.gd - 深海恐惧症篇第21话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep21_script()

func play_script():
	pass

func bathophobia_ep21_script():
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Corridor.png")
	await novel_interface.show_text_only("那群突然出现在走廊的人径直朝我们冲来。")
	await novel_interface.show_text_only("她们一言不发，除了衣物摩擦和脚步的声音，甚至连的呼吸都听不到。")
	await novel_interface.show_text_only("我握紧武器正准备应战，海因里希的战服突然发出强光并瞬间消失，只在原地留下一片光雾。")
	await novel_interface.show_text_only("在我还在错愕时，海因里希已经闪到一人身前，用青金石的剑背痛击其中一个女人的胸甲。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("——好快！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("钝击发出的巨大闷响回荡在走廊间，我不禁偷偷捂住了胸部……")
	await novel_interface.show_text_only("那人就像木偶般被轰然击倒，并顺着击打的力道在地上滚出了一大段距离。")
	await novel_interface.show_text_only("然而那家伙没有任何人类在落地时习惯性的保护动作。")
	await novel_interface.show_text_only("待身体停下后，胸部已经有些凹陷的那人再次拿起武器朝我们冲来。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("……！","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希察觉到不对，反身以极快的速度用剑锋分别刺穿了三人的脚跟。")
	await novel_interface.show_text_only("她们即使被斩断筋腱瘫倒在地，却依然抽搐着身体想爬向我们，并且始终保持着沉默。")
	await novel_interface.show_text_only("虽然这些并非强大的敌人，但这种以人类的躯体所表现出的非人性…")
	await novel_interface.show_text_only("却像是恐怖谷效应一样，令人更加不寒而栗……")
	await novel_interface.show_text_only("确认了这些敌人无法再构成威胁后，拉斐尔上前试图治疗对方。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("突然间，地面再次颤抖。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Second_Earthquake.png")
	await novel_interface.show_dialog("又是地震……","海因里希")
	await novel_interface.show_text_only("这次的晃动更加猛烈，时间也持续了更久。")
	await novel_interface.show_text_only("走廊的灯光随着震动忽亮忽暗，远处传来无法分辨是哀嚎还是金属被拉伸的刺耳声音。")
	await novel_interface.show_text_only("那几个瘫倒在地的人，在地震中像是被震碎的浪\n花，在我们面前渐渐变成透明的……液体？") #换行问题
	await novel_interface.show_text_only("随后液体开始沸腾，冒出大量的气泡，就像在炙热铁板上的水珠，只用了几秒就蒸发殆尽。")
	await novel_interface.show_text_only("冰冷的甲板上，一点痕迹都没有留下，仿佛那些诡异的家伙从未存在过。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	await novel_interface.show_text_only("地震后，我们发现周遭的环境也发生了改变。")
	await novel_interface.show_text_only("资料室的木制品变成了碎屑，飘散在空气中，墙壁也变得破旧斑驳。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("……哎？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这里看上去依旧是那间资料室。")
	await novel_interface.show_text_only("与之前不同的是，此时房间内的光源被熄灭，地砖不再光可鉴人，书架上物品的摆放也截然不同。")
	await novel_interface.show_text_only("厚重重工业感的钢铁横梁后面，另一只声音感应监控摄像头将黑洞洞的镜头对准了我们。")
	await novel_interface.show_text_only("墙壁上挂着一张精美的南极地形图，大气数据变化的记录本正摊开在桌面上。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("这是……怎么回事！","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("刚才的……难道是幻觉吗……","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("那群家伙也是假的？","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希看了看手中没有任何血迹的武器，又面色凝重的打量着刚才那些人蒸发的地方。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("不，恐怕刚才，我们并不在现实世界……","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希被莉统的声音所突然打断。")
	await novel_interface.show_dialog("总算联系上了！","莉琉")
	await novel_interface.show_text_only("我的胸部传出莉琉的声音。")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("莉琉！刚才信号出问题了吗？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉嗯了一声，声音听上去有些疲惫，而海因里希正一脸惊异的盯着我的胸部。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("（等等，不管你要说什么，你一定是误会了！！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希看着我的表情心领神会点了点头，然后用手轻轻的在自己胸前摸索。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("（小声）主人对我……也做了这样的改造吗？","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_text_only("并没有！！！而且怎么好像你很期待似的？！")
	await novel_interface.show_dialog("对、对了，你怎么没用无线电联系……\n安妮那边没事吧？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("通讯卫星已经就位了，安妮正在收集各个甲烷泄露点的信息，你们那边怎么样？","莉琉")
	await novel_interface.show_text_only("我一边整理思绪，一边用尽量简短精炼的语言报告了我们进入基地后的种种异状。")
	await novel_interface.show_dialog("……\n（“不在现实世界”吗……） ","莉琉")
	await novel_interface.show_dialog("等等，我确认一下时间。","莉琉")
	await novel_interface.show_dialog("从你们在基地门口最后一次与安妮联络，已经过去了8分钟。","莉琉")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("……有这么短吗？","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","perspire",0.25)
	await novel_interface.show_dialog("至少有40分钟了吧！","拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉似乎想到了什么，快速敲击着键盘。")
	await novel_interface.show_dialog("刚才一艘在南极海域巡航的莱博娜驱逐舰收到一段类似低频噪音的信号。","莉琉")
	await novel_interface.show_dialog("我本来以为是地震余波，但照现在的情况来看……","莉琉")
	await novel_interface.show_text_only("莉琉展开EEG模组，重新进行模式分析。")
	await novel_interface.show_dialog("果然……","莉琉")
	await novel_interface.show_dialog("这个信号和人类快速眼动睡眠时的脑电波模式上高度匹配，只不过……","莉琉")
	await novel_interface.show_dialog("强度被放大了62万倍。","莉琉")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("……开什么玩笑！！","拉斐尔")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("你是说刚才我们在做梦吗？","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("做梦时，时间确实会变慢……","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("heinrich_battle","normal",0.25)
	await novel_interface.show_dialog("梦境是『记忆』的映射，刚才出现的各种状况确实像是记忆碎片的重组……","海因里希")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那一定是个噩梦……","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我忽然想起曾经看过的一部电影，懊悔自己怎么没准备个陀螺。")
	await novel_interface.show_dialog("……可能并不是你们，而是有什么东西正在做梦。","莉琉")
	novel_interface.show_character("ren_battle","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("heinrich_battle","serious",0.25)
	await novel_interface.show_dialog("而我们，在那个东西的梦境里……吗？","海因里希")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("无端的推测只能加重不安，我发现莉琉那边非常很嘈杂，似乎还有不少人在旁边工作。")
	novel_interface.show_character("ren_battle","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("heinrich_battle","serious",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("对了，外面……怎么样了？","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉沉默了片刻，似乎在思考要透露多少信息。")
	await novel_interface.show_dialog("比预计的，要麻烦些。","莉琉")
	await novel_interface.show_dialog("『联合议会』正在讨论对甲烷泄露的应对措施，但不能指望那种官僚机构能应对这种『末日事件』。","莉琉")
	await novel_interface.show_dialog("萨蒙顿的戴克斯博士倒是提出了利用嗜甲烷古菌的方案……","莉琉")
	await novel_interface.show_dialog("但耐寒的菌种现有库存严重不足，那种古菌的培育代际周期又太长。","莉琉")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("而且厌氧菌对于大气内的甲烷也束手无策——","拉斐尔")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("爷爷也没办法了吗……","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("（听得懵懵懂懂……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("目前大多中小型考察站都在组织撤离，不过南极三大基地已经成立了临时应对小组。","莉琉")
	await novel_interface.show_dialog("到目前为止，南极圈内发现了42处甲烷泄露点，其中6处已经被引燃，还有人把画面传到了网上。","莉琉")
	await novel_interface.show_dialog("现在全世界的新闻上都循环播放着极地冰原裂缝中喷出几十米高火舌的画面。","莉琉")
	await novel_interface.show_dialog("新闻管制已经失效了，上次这种末日狂欢的氛围还是“黑色圣诞节”吧……","莉琉")
	await novel_interface.show_text_only("莉琉讽刺的话语中透露出一丝无奈。")
	await novel_interface.show_dialog("泄露地点集中在几处不冻湖区和罗斯岛的埃里伯斯火山带。","莉琉")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("……火山？","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("至于你们附近的伊丽莎白公主地，也有2起甲烷引发小型火灾的报告。","莉琉")
	await novel_interface.show_dialog("还有一起是格罗夫山旅行团火焰喷枪使用不当造成的……真是一群有钱的蠢货。","莉琉")
	await novel_interface.show_dialog("不过，白皇后基地目前应该不会受到火灾的影响。","莉琉")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("呼……","小怜")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("（还好还好，暂时不会变成烤肉。）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……不过，麦克默多站已经检测到，目前大陆的裂缝下方普遍出现了熔岩流活动。","莉琉")
	await novel_interface.show_dialog("白皇后基地旁边的裂缝最为明显，附近冰层强度也在快速下降。","莉琉")
	await novel_interface.show_text_only("我忍不住看了看自己脚下的金属甲板。")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("（但是...会变成铁板烧嘛……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然通讯中响起了尖锐的杂音，我的胸部随之一\n震，然后信号就断开了。") #换行问题
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("接连出现的地火、流动的岩浆、死亡的烟尘……","海因里希")
	await novel_interface.show_dialog("和四百多年前那次如出一辙……","海因里希")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("这些都是『原质』崩毀的前兆。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("是1600年那次？","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("那是在第七质点，『丰饶』之地——秘鲁总督区。","海因里希")
	await novel_interface.show_dialog("四处都是火海，空气中刺鼻的硫磺气味，无论如何也忘不了……","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希苦涩的回忆让我的心中一颤，想到自己似乎也经历过那样的情景……")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("难道……这些都和你所说的『那位』有关？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希点了点头。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Ampthitheatre.png")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_dialog("当年，我和玫瑰十字会的友人们集齐了三卷秘本: 《天车之书》、《创造之书》与《光之书》。","海因里希")
	await novel_interface.show_dialog("按照上面的记载，我们完成了炼金术中最伟大的成就——制造了可以进入因果之隙的『门』。","海因里希")
	await novel_interface.show_dialog("当时我们天真的认为，『门』的后面会有仁爱全能的主，为我们展示世界的真理。","海因里希")
	await novel_interface.show_dialog("…但之所以有“『门』不可穿越”和“『真理』不可窥视”这样的训诫，是有原因的……","海因里希")
	await novel_interface.show_dialog("『门』一旦进入便永远无法找到出口。\n『真理』一旦刻印在脑海中就永远无法忘却。","海因里希")
	await novel_interface.show_dialog("人类唯一能理解的就是语言本身——","海因里希")
	await novel_interface.show_dialog("任何语言无法描述的，都超出了我们的承受能力。","海因里希")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("这是20世纪才有人总结出的哲学观点……","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("哦？有人仅靠思考就得出了这样的结论吗？","海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("那个人，一定经历了相当的痛苦吧。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("何止，他的整个家族被人称为疯人院……","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("是啊，那些知识会不断消磨人的自我，你会在恐惧中无法自拔的希望与之融为一体。","海因里希")
	await novel_interface.show_dialog("在我经历被溶解的过程时，『那位』出现在我的面前……","海因里希")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("无需语言就能传达意图……","海因里希")
	await novel_interface.show_dialog("我要选择，是像融入大海的水滴一样就此消逝。","海因里希")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("还是被作为独立的个体装入瓶中，然后永远作为生命之树的守护者而存在。","海因里希")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("……","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("这不是乘人之危嘛！","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("那么生命之树，也不是他们宣称的那种东西吧？","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希露出了狡黠的笑容。")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("——是封印。","海因里希")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("生命之树的十个原质，封印着即使『那位』也会感到恐惧的不可言说的存在。","海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("虽说如此，但我也不知道那具体是什么……","海因里希")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("或许我该庆幸自己不知道吧~","海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("海因里希顿了顿。")
	novel_interface.character_light(0.35,"bored")
	await novel_interface.show_dialog("（在似乎将要燃尽万物的埃纳普蒂纳火山口）\n（我曾嘗到过一眼……）","海因里希")
	await novel_interface.show_dialog("『那位』虽然没有传达具体的意愿，但从这片大陆的变化看来——","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她苦笑了一声。")
	await novel_interface.show_text_only("海因里希的话让我们集体陷入沉默。")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("——等等！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我拿出气相色谱仪，紧盯着上面的读数。")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("就算存在于『梦境』，但是这里的『现实』也和其他地方不一样吧？","小怜")
	await novel_interface.show_dialog("基地外裂缝处的甲烷含量已经超过了25%，但这里的甲烷含量还是远低于燃烧要求……","小怜")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("这么明显的矛盾，一直都被我们忽略了！","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("你在说什么？","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("从我们进入基地开始，就能一直听到在工作的……","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("换气系统！？","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("所以基地里一定存在着什么东西，能阻止甲烷的扩散。","小怜")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("对了，出发前莉琉发来过一份基地的构造图吧？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔也明白过来，马上在桌面上展开了那份结构图。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Baizhu/Snowstorm.png")
	await novel_interface.show_text_only("呼啸的风声清晰可闻，一小时前还在安静飘落的雪花，忽然变得如利刃一般。")
	await novel_interface.show_text_only("漆黑的冰原瞬间变得苍白无情。")
	await novel_interface.show_text_only("——极地的暴风雪降临了。")
	
	print("=== 深海恐惧症篇第21话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
