# bathophobia_ep06.gd - 深海恐惧篇第6话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep06_script()

func play_script():
	pass

func bathophobia_ep06_script():
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	await novel_interface.show_text_only("一如往常的单方面视讯会议正在进行，莉琉站在会议台中央，冷静地报告着各项研究进展情况。")
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("关于“方舟计划”……", "基尔斯")
	await novel_interface.show_dialog("在萨蒙顿提供的历史文物清单中，你已经确定选用『特斯海姆青金石柱』了吗？", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("是的，关键是如何制造可控的『异变空间』。", "莉琉")
	await novel_interface.show_dialog("最近各学园都市频繁爆发的时空相位波动，都是由特征类似『异质物』的物品与人类接触造成的。", "莉琉")
	await novel_interface.show_dialog("这类『异质物』此前一直处于沉默状态，但几乎在同一时间被激活了。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("（其实应该叫做『魔导器』和『魔导书残页』，不过还是用他们熟悉的名词来解释吧。）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("就是『洛斯金杯』消失的那一天吧……", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("目前还不能确认两个事件的相关性。", "莉琉")
	await novel_interface.show_dialog("由于不可控因素过多，只能根据两个条件筛选。", "莉琉")
	await novel_interface.show_dialog("其一，色相扫描符合此类『异质物』特征，但活性不高的。", "莉琉")
	await novel_interface.show_dialog("其二，有历史文献可以追溯到文物的关联人，并确信其没有暴力及犯罪倾向。", "莉琉")
	await novel_interface.show_dialog("『特斯海姆青金石柱』的原主人为海因里希·昆哈特，是文艺复兴时期的医生和炼金术士。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("活性不高啊……还期待能收集到更临界的数据呢。", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("既然样本宝贵，还是不要用太激进的方案。", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("（只要能证明小怜可以出入异变空间，给元老院演一场戏就可以了。）","莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("（其实『特斯海姆青金石柱』并不是『魔导器』）\n（而是特征类似的拥有『魔法刻印』的物品）","莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（让普通人触碰『魔导器』这么危险的事情）\n（我可不是那个大猩猩……）","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("荧幕中传来低沉的笑声。")
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("炼金术士……科学的起源么？\n真是有趣的选择。", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("我听说那是萨蒙顿的重要历史艺术品，而且那个海因里希是『玫瑰十字会』的奠基人之一……", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","speak")
	await novel_interface.show_dialog("『玫瑰十字会』只是一个宗教和神秘学的团体，与现在萨蒙顿的情报机构『十字玫瑰』没有关系。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("而且炼金术士也可以看做那个时代的科学家，希望那个人能对未知事物保持基本的敬畏吧。", "莉琉")
	await novel_interface.show_dialog("不过以戴克斯博士的性格，不会白白把这种重要文物借给我们吧，除非……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("会议室中出现了一阵诡异的沉默。")
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("没错，萨蒙顿方面要求我们共享数据，并且要派遣一位代表全程参与。", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("……", "莉琉")
	await novel_interface.show_dialog("（看来他们还没放弃制造魔女的计划……）\n（想用小怜作为『稳定器』吗）","莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("明白了，那么我想最后再确认一下，萨蒙顿和各位都明白这次实验的危险性吧？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("是的，利用旧都的巨型地下排水设施改造的『方舟基地』就是为了应对最糟糕的情况。", "基尔斯")
	await novel_interface.show_dialog("极速海水倒灌系统可以在30秒内淹没整个基地。", "基尔斯")
	await novel_interface.show_dialog("如果实验之中出现什么意外的话……", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("希望那时候，莉琉阁下能够有启动紧急自毁装置的决心。", "#C")
	
	print("=== 深海恐惧篇第6话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
