# bathophobia_ep10.gd - 深海恐惧篇第10话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep10_script()

func play_script():
	pass

func bathophobia_ep10_script():
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("南极海域，特种动力潜艇——冥海号。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Submarine_door.png")
	await novel_interface.show_text_only("中控室门前，站着一名身着白色连衣裙的少女。")
	await novel_interface.show_dialog("访问者，名称——", "系统")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("Record，白烛。", "白烛")
	novel_interface.character_dark()
	await novel_interface.show_text_only("少女略显疲惫，微微潮湿的头发散落在背后，但并未影响到她的身姿")
	await novel_interface.show_text_only("自信，坚定，还透着一丝骄傲。")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("请确认口令——", "系统")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("Keshi0415-Z。", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("信息登陆中……扫描开启。", "系统")
	await novel_interface.show_text_only("通道四面出现的八条光带，开始对白烛进行扫描。")
	await novel_interface.show_text_only("此时，在两层防护门后的另一侧，一群人正聚在观察窗前兴奋的讨论着。")
	await novel_interface.show_text_only("中间那位褐色头发的少女，是白烛的好友思仪。")
	await novel_interface.show_text_only("不过她更喜欢别人称呼她的行动代号——牛奶。")
	await novel_interface.show_text_only("透过观察窗，两人的视线相遇，白烛的神情立刻多了一分柔软。")
	await novel_interface.show_dialog("识别完毕，请输入六位标准密码——", "系统")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("……", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女清楚的记得自己离开的时候，潜艇的安保系统中并没有这道验证程序。")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("（……这帮家伙，又在安全系统上动手脚了。）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("作为团队中的『特聘专家』，白烛已经习惯了这种针对自己的恶作剧式的“考核”。")
	await novel_interface.show_text_only("由军方精英组成的特遣队中，突然空降来一名没有作战经验的顾问。")
	await novel_interface.show_text_only("而且由于本次行动涉及极端环境，这名顾问还拥有临时战略决策权。")
	await novel_interface.show_text_only("哪怕她在自己的领域素有“天才”之名，也会让人心生不满吧……")
	await novel_interface.show_text_only("唯有证明自己，才能真正地融入这个团体。")
	await novel_interface.show_text_only("白烛十分清楚这一点。")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("数字密码……\n还真是很久没见过了。", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烟的视线扫过观察窗后的牛奶。")
	await novel_interface.show_text_only("此时她正伸出手贴在玻璃上，对自己做着鬼脸。")
	await novel_interface.show_text_only("从白烛的角度可以看到，牛奶用眼神偷偷瞄向了防护门外侧的铁牌。")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_text_only("舱门编码……？\nZ-100485。")
	novel_interface.change_expression("shock")
	await novel_interface.show_dialog("不会这么简单吧？", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛按照顺序输入了这六位数。")
	await novel_interface.show_text_only("一阵蜂鸣后，通道的大门依旧紧闭。")
	await novel_interface.show_dialog("密码错误，警告一次——", "系统")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("……果然。", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("除了那家伙、特遣队全员恐怕都期待着看到她被系统拒之门外束手无策的样子。")
	await novel_interface.show_text_only("牛奶露出得意的笑容，白烛叹了口气。")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("又是暗号游戏吗？", "白烛")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only(" 观察窗后的众人表情各异，但都带有一丝戏谑。")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Submarine_centralControlRoom.png")
	await novel_interface.show_dialog("喂喂，你们觉得这丫头这次需要多久？", "特遣队员A")
	await novel_interface.show_dialog("不是写了反暴力破解模块吗？就算她用破译程序也没办法吧！", "特遣队员C")
	await novel_interface.show_dialog("对了，牛奶你可不能提示她……", "特遣队员B")
	await novel_interface.show_text_only("牛奶乖巧地在嘴上做了一个拉链封口的动作。")
	await novel_interface.show_dialog("那我赌60秒。", "特遣队员D")
	await novel_interface.show_dialog("就算是天才也不可能这么快算出来吧……\n我赌十分钟！", "特遣队员C")
	await novel_interface.show_dialog("总觉得你们太小看白烛和这家伙了……", "特遣队员A")
	await novel_interface.show_text_only("身材高大的特遣队员A从后面揉了揉牛奶的脑袋。")
	novel_interface.show_character("milk_normal","sprite")
	await novel_interface.show_dialog("切~修改程序的代码可是大家都审查过的哎！", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不过如果是小白烛的话，肯定能看懂那个……")
	await novel_interface.show_text_only("这是她们二人之间心照不宣的小秘密。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Submarine_door.png")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("唔——", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛用余光看到牛奶举起右手，用拇指和食指的指肚交叉，对她做了个比心的手势。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("真是的……", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那是两人最初相遇的暗号。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("“100485” ……\n对应的是“124155”。", "白烛")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("只用了不到20秒，在众人讶异的目光中，白烛输入了正确的密码——")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Submarine_centralControlRoom.png")
	await novel_interface.show_text_only("中控室大门缓缓开启，少女整理了一下头发，嘴角掠过一丝微笑。")
	novel_interface.show_character("milk_normal","pleased")
	await novel_interface.show_dialog("嘿嘿嘿，我就知道……", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶一边贱兮兮的笑着，一边向刚才下注的人收着钞票。")
	await novel_interface.show_dialog("喂——你是不是给她什么提示了？\n……不是说好不能作弊嘛！", "特遣队员D")
	await novel_interface.show_text_only("牛奶摊开双手，做出无辜的表情。")
	novel_interface.show_character("milk_normal","pleased")
	await novel_interface.show_dialog("你们都看到了啊，我可什么都没说~", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("她到底怎么猜到的？", "特遣队员B")
	await novel_interface.show_dialog("不对，一定漏了什么细节……", "特遣队员C")
	await novel_interface.show_text_only("不给他们找寻找索的时间，白烛清了清嗓子，马上开始了调查简报。")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("和预估的情况一样，『那个东西』确实存在于深渊水层带。", "白烛")
	await novel_interface.show_dialog("我在几小时前与它进行了近距离接触，并且得到了液体采样。", "白烛")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	novel_interface.show_character("milk_normal","shock")
	await novel_interface.show_dialog("哎……？", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("众人立刻停止了喧闹。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/eyeball.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("白烛所说的『那个东西』，正是他们此次行动的目标：深海中某种古老的生物。")
	await novel_interface.show_text_only("在一些古老的宗教中认为那是地球上所有生命的基础。")
	await novel_interface.show_text_only("无法确定『那个东西』是否为单一生命体，甚至无法确定它是否以物质形态存在。")
	await novel_interface.show_text_only("在出发之前，特遣队中大多数人都认为那只是捕风捉影的谣言和传说，就像尼斯湖水怪一样。")
	await novel_interface.show_text_only("但白烛的报告打消了大家想要结束任务提前回家的幻想。")
	await novel_interface.show_text_only("在南冰洋，伊丽莎白公主冰层下4000-6000米的深海水层中……")#文字删除
	await novel_interface.show_text_only("存在着一个可能在人类诞生前，甚至从更早的时期就存在，并一直存活至今的神秘生物。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("光是这样的设想能够成立，就让人毛骨悚然。")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Submarine_centralControlRoom.png")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("虽然时间很短，但传感器成功采集到了它附近海水区域散布的电神经活动。", "白烛")
	await novel_interface.show_dialog("起初的波形平缓，后来频率突然飙升，从波形特征看来十分接近人类的β脑电波。", "白烛")
	await novel_interface.show_dialog("虽然强度是人类的数十万倍……", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("说到这里，白烛不禁回想起几小时前被那个巨大的眼球注视时，自己的理智逐渐溶解的感觉。")
	novel_interface.show_character("milk_normal","solemn")
	await novel_interface.show_dialog("有点像人从噩梦中惊醒的状态……", "牛奶")
	await novel_interface.show_dialog("那么任务说明里提到的南极空域“异常电波”，并不是因为设备故障吗。", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你确定？在那个深度，手掌大小的面积就要承受几十吨的压力……", "特遣队员A")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("我确定。", "白烛")
	await novel_interface.show_dialog("而且正如情报所说，它的体积十分巨大，横展超过这艘潜艇。", "白烛")
	await novel_interface.show_dialog("我也不知这种巨型生物是如何在那样的压强下维持形态的……", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哇哦，那是海底的巨型『异质物』吗？！", "特遣队员D")
	novel_interface.show_character("baizhu_normal","stare")
	await novel_interface.show_dialog("不。", "白烛")
	await novel_interface.show_dialog("那不是『异质物』。", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女的语气突然坚定起来，令大家有些讶异。")
	await novel_interface.show_text_only("白烛是出了名的没有确凿证据，就不会进行任何推论或假设的严谨性格。")
	await novel_interface.show_text_only("不知为何这次会做出如此确定的判断。")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("我的意思是，有主观意识的“异质物”，目前还没有发现……", "白烛")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("而『那个东西』，是有主观意识的……", "白烛")
	await novel_interface.show_dialog("而且，意识非常强大……", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛据了抿嘴唇，似乎想要解释，但又无法用语言表达，只是声音越来越小")
	await novel_interface.show_text_only("房间内也随之变得安静起来，大家一言不发，呼吸声都变得微弱。")
	await novel_interface.show_text_only("会对未知的事物感到恐惧，是人类的本能。")
	novel_interface.show_character("milk_normal","laugh")
	await novel_interface.show_dialog("不是就不是嘛~小白说了算！", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶笑嘻嘻地打了个圆场，特遣队员们相互哈了几声，总算是缓解了气氛。")
	await novel_interface.show_text_only("只有白烟还在皱着眉头，牛奶叹了口气，上前一把揽住了她的腰。")
	novel_interface.show_character("milk_normal","sprite")
	await novel_interface.show_dialog("好啦好啦，至少完成了第一步的任务目标。\n别总是这么严肃啦~", "牛奶")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("想要保持样本的活性，我们需要尽快赶到实验室。", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛对牛奶的行为不理睬也不反抗，继续认真的跟特遣队长讨论。")
	await novel_interface.show_dialog("我们去布宜诺斯艾利斯的实验室？", "特遣队员A")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("现在的样本箱大约只能再维持4个小时左右的深海环境，时间恐怕来不及。", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("最近有条件的实验室需要经过埃默里冰架，我得先向总部报告一下。", "特遣队员A")
	await novel_interface.show_dialog("不是吧，又要写破冰船申请了？", "特遣队员B")
	novel_interface.show_character("baizhu_normal","normal")
	await novel_interface.show_dialog("我记得乌斯怀亚号破冰船这个月没有启航任务。", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("乌斯怀亚号……", "特遣队员D")
	await novel_interface.show_text_only("几名特遣队员交换了一下目光。")
	novel_interface.show_character("baizhu_normal","normal") 
	await novel_interface.show_dialog("为了节省时间，也可以考虑在破冰船上架设临时实验室——", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶突然打断了白烛，抱紧了白烛的右臂。")
	novel_interface.show_character("milk_normal","sprite")
	await novel_interface.show_dialog("哎呀哎呀，我们还是先把现有的资料传回给Boss再说，文书工作让他们发愁就好啦！", "牛奶")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("——小白烛，不许你这么严肃了，笑一个~", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶亲昵地蹭了蹭白烛。")
	
	print("=== 深海恐惧篇第10话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
