# bathophobia_ep15.gd - 深海恐惧篇第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep15_script()

func play_script():
	pass

func bathophobia_ep15_script():
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Submarine_centralControlRoom.png")
	await novel_interface.show_dialog("阿嚏……", "白烛")
	await novel_interface.show_text_only("独自趴在桌前昏昏欲睡的少女打了个喷嚏，一下子清醒过来。")
	await novel_interface.show_text_only("潜艇所处的海域内正处于极夜后期，仅凭天色无法分辨出时间。")
	await novel_interface.show_text_only("看了看屏幕上的信息，白烛才意识到，距离她在深海见到那个怪物，仅仅过去几个小时。")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("……这样，真的好吗？", "白烛")
	await novel_interface.show_dialog("（为了寻找真相……而利用她）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女不自觉地望向手中摊开的笔记本。")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("（如果是父亲的话……）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("——如果是那个男人的话，根本不会为了这种情感而动摇吧。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/baizhu_father.png")
	await novel_interface.show_text_only("回想起父亲宽厚的手掌，少女渐渐握紧了拳头。")
	await novel_interface.show_text_only("这本记录了大量晦涩难懂文字的笔记，原本属于她的养父。")
	await novel_interface.show_text_only("那是一个身材高大、沉默而认真的生物学家，无论对自己还是对白烛都很严格。")
	await novel_interface.show_text_only("由于白烛特异的体质，父亲从小就要求她在学习之余还要进行严格的训练。")
	await novel_interface.show_text_only("少女还记得，小时候为了达到父亲所设定的目标，自己每天都要拼命努力。")
	await novel_interface.show_text_only("而她最期待的，就是父亲偶尔卸下严肃的表情，对自己露出认同的微笑。")
	await novel_interface.show_text_only("或许没有太多温情，但这个寡言少语的男人一直在默默的训练并保护着她……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("——就像是在为某种必定到来的命运做着准备。")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Submarine_centralControlRoom.png")
	await novel_interface.show_text_only("在白烛十二岁生日那天，她收到了装有这本笔记的匿名包裹——以及自己父亲的死讯。")
	await novel_interface.show_text_only("一次城区内的瓦斯爆炸，让少女唯一的亲人与另外三十多个生命瞬间消逝。")
	novel_interface.show_character("baizhu_normal","puzzled")
	await novel_interface.show_dialog("……", "白烛")
	novel_interface.character_dark()
	await novel_interface.show_text_only("少女嘴唇微张，无声的念出那个名字。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那名字背后的线索让她意识到，父亲的死绝非官方定性的意外事故。")
	await novel_interface.show_text_only("只身一人的小女孩必须擦干泪水快速成长起来，以躲避不知何时降临的危险。")
	await novel_interface.show_text_only("——父亲笔记中留下的信息表明，拥有特殊能力的白烛，一定会成为那群家伙的目标。")
	await novel_interface.show_text_only("而如果这个包裹被寄出，就说明自己无法继续保护她了……")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("（人们就这么在意……这种能力吗……）", "白烛")
	await novel_interface.show_dialog("（这，难道不是诅咒吗……）", "白烛")
	novel_interface.character_dark()
	await novel_interface.show_text_only("白烛看了看自己的手心，几个银色的小光团在她的指缝间跳动。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("自从有记忆起，白烛就知道自己是不同的——但并非由于她的异常体质。")
	await novel_interface.show_text_only("她从小就对数字有过目不忘的能力，心算速度远超常人，同时对机械也有浓厚的兴趣。")
	await novel_interface.show_text_only("但由于身体的原因，父亲要求她必须保持收敛，时刻伪装成一个“普通人”。")
	await novel_interface.show_text_only("父亲死后，白烛决定不再隐藏自己。")
	await novel_interface.show_text_only("一年后，她成为一所历史悠久大学多年来首次破例特招的新生。")
	await novel_interface.show_text_only("但就算沉入书海，却依旧没有一本书或一门课能够解答她心中的疑问。")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("（为什么，我是“不一样”的……）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女不断的思考和学习，好像要一口气把压抑多年的好奇心都释放出来。")
	await novel_interface.show_text_only("她没有意识到，这样的自己会被贴上“高傲”“冷淡”和“难相处”的标签。")
	await novel_interface.show_text_only("虽然渐渐被孤立，但她并不在意。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("（不然，我也不会遇见你……）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("思仪，她在一场意外中结识的好友。")
	await novel_interface.show_text_only("仅用了几分钟，白烛就推理出对方是伪装成学生来调查校园内非法异质物研究的调查员。")
	await novel_interface.show_text_only("明知对方可能从名字到经历全是伪造的，自己却被她那种大大咧咧的性格所吸引。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("（她是……“不一样”的。）", "白烛")
	novel_interface.character_dark()
	await novel_interface.show_text_only("比任何人更加理解自己……")
	novel_interface.character_light()
	await novel_interface.show_dialog("（明明就是习惯了伪装的家伙……）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("却毫无保留的对自己敞开了心扉。")
	await novel_interface.show_text_only("只是她们俩都未曾料到，私下里的交往，会引起牛奶身后组织的注意。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("得知白烛是那位生物学家的养女，牛奶的上级很快向她发出了南极深海考察项目的邀请。")
	await novel_interface.show_dialog("（本来是打算拒绝的……）", "白烛")
	novel_interface.show_background("res://assets/images/bg/Baizhu/milkBase.png")
	await novel_interface.show_text_only("在特遣队的某个地下站点。")
	await novel_interface.show_text_only("最终让我下定决心的，是在任务简述上看到的那个标志——")
	await novel_interface.show_text_only("那个在父亲的笔记中曾经出现的标志。")
	await novel_interface.show_text_only("一个代表着秘密宗教组织的，令人毛骨悚然的黑色眼球符号。")
	await novel_interface.show_text_only("在笔记的记录中，父亲与那个组织接触过，对方曾经流露出想要组建异质能力者武装的意向。")
	await novel_interface.show_text_only("相应的计划被命名为“Ningen”。")
	await novel_interface.show_text_only("由于白烛在孤儿院时留下的记录，她的名字当时就在“Ningen”计划I类目标的名单上。")
	await novel_interface.show_text_only("父亲也因此成为了这个危险组织的眼中钉。")
	novel_interface.show_character("baizhu_normal","stare")
	await novel_interface.show_dialog("（“Ningen”……南极）", "白烛")
	await novel_interface.show_dialog("（我记得南极的白皇后基地……）\n（命名取自《安徒生童话》中的冰雪女王。）", "白烛")
	await novel_interface.show_dialog("丹麦语： Snedronningen\n或者是： Snedron-Ningen", "白烛")
	await novel_interface.show_dialog("（不会是巧合。）", "白烛")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("你的Boss，和那群家伙看上了同样的东西吗？", "白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_normal","sprite")
	await novel_interface.show_dialog("看你的表情，这个组织似乎比『黑名单』上的其他家伙麻烦一些啊……", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛点了点头，但并不想深谈。")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("抱歉，就算我参与这个项目，也是出于私心。", "白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_normal","sprite")
	await novel_interface.show_dialog("我知道啊~", "牛奶")
	novel_interface.change_expression("pleased")
	await novel_interface.show_dialog("可对老大来说，只要你能继续你父亲对海洋生物的研究就可以了。", "牛奶")
	await novel_interface.show_dialog("互利互惠、互利互惠~", "牛奶")
	novel_interface.change_expression("sprite")
	await novel_interface.show_dialog("小白烛的私心……该不会是因为被我迷倒，才决定上了这艘贼船吧？", "牛奶")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("那我可会非常非常有压力的~", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶说着朝着白烟抛了个飞吻，白烛被逗得扑哧一笑。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("但白烛并没有注意到，当时她好友清澈的眼神中闪过的一丝阴霾。")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Submarine_centralControlRoom.png")
	await novel_interface.show_text_only("回想起签约时的情形，白烛还是一阵自责。")
	novel_interface.show_character("baizhu_normal","sad")
	await novel_interface.show_dialog("（我……在利用她。）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛坐到桌前抽出笔，盯着摊开的笔记本。")
	await novel_interface.show_text_only("“能够被利用的人，才有价值。”")
	await novel_interface.show_text_only("——少女这样写道。")
	await novel_interface.show_text_only("“您曾经这么说过，我也一直是如此认为的……”")
	await novel_interface.show_text_only("“毫无压力的利用别人，或者被利用”\n“在您看来，应该是一件理所当然的事情……”")
	await novel_interface.show_text_only("“区别只在于，谁的价值更高。”")
	await novel_interface.show_text_only("“无需解释，无需说明，只要关注目标。”")
	await novel_interface.show_text_only("“只有这样单纯的关系，才能和大多数人保持安全的距离。”")
	await novel_interface.show_text_only("白烛顿住了。")
	await novel_interface.show_text_only("可是，正如您所说，世界上还是存在有那种——")
	await novel_interface.show_text_only("“无论如何也希望被我利用的存在。”\n“无论如何也不愿意利用她的存在。”")
	await novel_interface.show_text_only("少女想到这里，嘴角微微扬起。")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("（愧疚吗？明明应该是被舍弃的情绪。）", "白烛")
	await novel_interface.show_dialog("（那是……喜欢吗？）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女合上了日记。")
	await novel_interface.show_text_only("她已经找到了自己的答案。")
	await novel_interface.show_text_only("白烛望向窗外，深蓝暗淡的天空变得更加深邃，几乎和漫无边际的海水融为一体。")
	await novel_interface.show_text_only("忽然，全舰响起了紧急通知。")
	await novel_interface.show_text_only("指令变更！中控呼叫全体成员，十分钟后会议室集合。")
	await novel_interface.show_text_only("重复，指令变更……")
	await novel_interface.show_text_only("白烛深深的呼了一口气，收好笔记本，大步朝外走去。")

	print("=== 深海恐惧篇第15话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
