# bathophobia_ep09.gd - 深海恐惧篇第9话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep09_script()

func play_script():
	pass

func bathophobia_ep09_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/liliu_observation.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("莉琉站在基台对岸高处的控制台上，可以同时看到一层的我们和元老院的观察室。")
	await novel_interface.show_text_only("空旷的大厅接连传来三声低沉的提示警报，是莉琉已经做好准备的讯号。")
	await novel_interface.show_text_only("拉斐尔朝莉琉挥挥手，我和安妮则严阵以待地站在她身旁。")
	await novel_interface.show_dialog("方舟计划，第一次实验开始。", "莉琉")
	await novel_interface.show_dialog("十秒后解除防壁！", "莉琉")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_awaitOrders.png")
	await novel_interface.show_text_only("操作台的底座上，出现了红色的倒计时。")
	await novel_interface.show_text_only("入口的闸门关闭，通道桥收回到墙体内。")
	await novel_interface.show_text_only("大厅顶部传出机械齿轮咬合的声音，隐蔽在天花板的自动武器阵列瞄向操作台，进入待命状态。")
	await novel_interface.show_text_only("我仿佛置身深海的游鱼，悬在黑暗的半空。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("感觉像重刑犯一样……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("被那么多武器指着，我感到浑身不自在。")
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("没关系，我会保护好小怜的！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮也很紧张吧……她紧握着球棒的双手指甲都没了血色，却还在安慰我。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("哼，胆小鬼。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倒计时归零的同时，拉斐尔毫不犹豫地拉下拉杆。")
	await novel_interface.show_text_only("基台周围的透明防壁迅速向底部收束并消失。")
	await novel_interface.show_text_only("青金石柱的本体被微微抬高，比刚才更加强烈的感觉向我袭来。")
	await novel_interface.show_text_only("体内的血液开始躁动，内心升起一种莫名的冲动。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("（厄……肚子更疼了……）", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("（如果现在申请去洗手间，会不会被打死啊……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/bedstand.png")
	await novel_interface.show_text_only("突然，上方的空间抖动了一下，一道闪光快速扫过我们头顶并一直延伸到大厅尽头。")
	await novel_interface.show_text_only("胸部随之传来两下短促的震动，这是伪装系统启动完毕的信号。")
	await novel_interface.show_text_only("大厅上空的光学迷彩和观察室的玻璃隔层作为两重保险，连同声音也一并隔绝。")
	await novel_interface.show_text_only("在他们的视野中，我们三人还有青金石柱应该在那一瞬间突然消失了。")
	await novel_interface.show_text_only("取而代之的是事先伪造的画面。")
	await novel_interface.show_text_only("大戏已经开幕，舞台中央的我已然没有退路。")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("没办法了……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我硬着头皮走上前，小心翼翼的伸出手。")
	await novel_interface.show_text_only("随着手一点点前移，我紧张地闭上眼睛屏住呼吸直到指尖触到柱石的表面。") #换行问题
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_awaitOrders.png")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………？")
	await novel_interface.show_text_only("我慢慢睁开眼。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("好像……并没有什么变化", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("我试着将手掌整个贴上去，触感有些像大理石。")
	novel_interface.character_light(0.35,"upset")
	await novel_interface.show_dialog("唔……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我又换了个角度，用力推了推\n七吨多重的石柱纹丝不动稳如泰山")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("嘁~", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("身后拉斐尔发出不屑的声音。")
	await novel_interface.show_text_only("虽然之前开会准备的各种预案中，什么事都没发生是我最期待的结果——")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("（但为什么……感觉有点丢人……）", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("我的手按在石柱上，气氛有些尴尬，正当我想再用点力的时候，心脏猛然抽动了一下。")
	await novel_interface.show_text_only("几乎同时，石柱似乎也震了一下。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然后我看着石柱缓缓的脱离了我的手，并且越离越远。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("——诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("升起的基台与石柱底部接触的部分发出低沉的摩擦声……")
	await novel_interface.show_text_only("萨蒙顿的国宝级文物，象征着文艺复兴时期人类启蒙与觉醒的伟大艺术品——『特斯海姆青金石柱』")
	await novel_interface.show_text_only("正顺着我推的方向慢慢倾倒……")
	await novel_interface.show_text_only("而且越来越快。")
	await novel_interface.show_text_only("昸——！！！")
	await novel_interface.show_text_only("随着一声巨响，青金石柱重重地砸在金属基台上直接碎成两块，前面的那一块还往前滑动了十几厘米") #缩减符号
	await novel_interface.show_text_only("裂口处散落出很多碎块，最远的一块直接滚进了前方的水池中。")
	await novel_interface.show_text_only("长久的沉默……")
	await novel_interface.show_text_only("即使是一向高傲的拉斐尔，惊愕的表情也凝固在脸上许久。")
	await novel_interface.show_text_only("然后她缓缓的转向我。")
	await novel_interface.show_text_only("眼中射出足以撕碎钢板的怒火。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("不、我不是，我没有……", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Ark_base_flare.png")
	await novel_interface.show_text_only("正当我思考如何才能保住性命的时候，虚空之中响起一阵风铃般的声音。")
	await novel_interface.show_text_only("地上的碎块随着声音分裂成更小的碎片，像被风吹起的纸片一样开始飘散。")
	await novel_interface.show_text_only("碎片折射出彩色的弧光，渐渐在空中形成了数个圆环，流动着向上爬升。")
	await novel_interface.show_text_only("直到地上碎开的石块完全风化消散在空中，大厅被散布着的无数流动光片照耀得五彩斑斓。")
	novel_interface.show_character("anne_battle","happy")
	await novel_interface.show_dialog("哇……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的指尖不由自主触摸向碎片构成的一个圆环——")
	await novel_interface.show_text_only("一触即碎的圆环，化作金色光沙。")
	await novel_interface.show_text_only("流动的光，如尘土一样散落。")
	await novel_interface.show_text_only("然后光斑逐渐向中心汇聚，越来越亮……")
	await novel_interface.show_text_only("在刺眼的强光中，一名金色长发的少女，出现在我面前。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("……！！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_text_only("少女张开双臂，坦然的站在我面前……但这样奇异绚烂的景象却让我无法移开视线。")
	await novel_interface.show_text_only("空气中飘散着一股淡淡的橙花和紫罗兰的香气。")
	await novel_interface.show_text_only("少女缓缓睁开了双眸。")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("奇妙而华丽的“炼成”……", "金发少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("她环顾了一下四周。")
	novel_interface.character_light()
	await novel_interface.show_dialog("这里……是现世！？", "金发少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("少女的眼神瞬间从迷茫变得兴奋。")
	novel_interface.character_light()
	await novel_interface.show_dialog("水与碳，盐与硫，硅与铁……", "金发少女")
	await novel_interface.show_dialog("居然成就了如此完美的……", "金发少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("她难以置信的打量着自己颤抖的双手。")
	novel_interface.character_light()
	await novel_interface.show_dialog("这种肉体的触感……", "金发少女")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女自上而下缓慢地拂过自己的身体。")
	await novel_interface.show_text_only("我忽然意识到有什么问题，连忙扭过头去。")
	await novel_interface.show_text_only("然后禁不住用余光继续打量着对方……")
	await novel_interface.show_text_only("那、那双手竟然还、还摸了……！！")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("这里……竟然也复原了吗？", "金发少女")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("……好刺眼的圣光，完全看不清楚！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然准备了各种预案，但面对这样的情形，我们三人竟一时不知所措。")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("那么……", "金发少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("金发少女扫过精神依旧紧绷的安妮和拉斐尔，目光落在了表情呆滯的我身上。")
	novel_interface.character_light()
	await novel_interface.show_dialog("您就是成就奇迹的人吗？", "金发少女")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("缓缓下落的金发少女足尖触及到地面，面向我恭敬地后退了一步。")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("……哎？\n（全不知道应该把眼睛放在哪里啊！！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("或者说，是您为我的灵魂制造了这个容器吗？", "金发少女")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("哈……应该……算是？", "小怜")
	await novel_interface.show_text_only("对不起，我只是轻轻的推了一下！")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女的单手放在胸前，向我微微鞠躬。")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("那么，如果您愿意的话……", "金发少女")
	novel_interface.character_dark()
	await novel_interface.show_text_only("金发少女抬起头，眼神直勾勾地盯着我湛蓝色的眸子之中仿佛有无尽的渴求。")
	novel_interface.character_light()
	await novel_interface.show_dialog("请将您的精华，尽数授予我吧……", "金发少女")
	await novel_interface.show_dialog("“主人”。", "金发少女")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("主人？", "拉斐尔&安妮")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("精精精精华？！？！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("打住——！")
	await novel_interface.show_text_only("不能进行奇怪的想象！！！")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("“炼金术，探索元素与生命之理的智慧。”", "金发少女")
	await novel_interface.show_dialog("能将躯体重新构造，唤回仿徨灵魂的人，必然掌握着我所不能企及的真理。", "金发少女")
	await novel_interface.show_dialog("而我…海因里希·昆哈特，愿为真理的奴……", "金发少女")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("名为海因里希的少女话没说完就突然顿住，站起身神色凝重的望着大厅一个空旷的方向。")
	await novel_interface.show_text_only("我也顺着她的目光看去，但除了柱子什么都没有。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("（等等，她刚才说奴……奴什么？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女叹了口气。")
	novel_interface.show_character("heinrich_naked")
	await novel_interface.show_dialog("这么快就被发现了。", "海因里希")
	await novel_interface.show_dialog("就算是新的身体，也不能免除那个“契约”吗……", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希的话音未落，大厅的空间突然开始剧烈扭曲。")
	await novel_interface.show_text_only("隔离箱内的传感器同时爆发了临界警报，检测状态灯瞬间切换为红色。")
	await novel_interface.show_text_only("上空传来一声巨响，是玻璃碎裂的声音。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("糟糕……这个时空波动……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希的身后，出现了波纹般的逆时针镜面。")
	await novel_interface.show_text_only("少女向后倒去，缓缓融入虚空。")
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("小怜，快离开！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然而已经迟了——")
	novel_interface.change_background("res://assets/images/bg/Baizhu/spaceTransfer.png")
	await novel_interface.show_text_only("周围的空间被无数的镜面带动着扭曲旋转。")
	await novel_interface.show_text_only("——紧接着，是一股昏天暗地的失重感。")
	await novel_interface.show_text_only("回过神来的时候，我们已经开始了下坠。")
	await novel_interface.show_dialog("啊啊啊啊啊————！！", "小怜")
	await novel_interface.show_text_only("在失去知觉之前，我最后记得的感觉是……")
	await novel_interface.show_text_only("屁股被风吹过凉飕飕的，肚子更痛了！")
	await novel_interface.show_text_only("今天真的是……")
	await novel_interface.show_text_only("糟透了！！！")
	
	print("=== 深海恐惧篇第9话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
