# bathophobia_ep18.gd - 深海恐惧症篇第18话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep18_script()

func play_script():
	pass

func bathophobia_ep18_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Depot2.png")
	await novel_interface.show_text_only("极地的震感并没有持续太久，补给站底部的防雪暴架空层起到了良好的缓冲作用。")
	await novel_interface.show_text_only("只过了几十秒，大陆就恢复了平静。")
	await novel_interface.show_text_only("对从小生活在埃癸斯边境区域的我来说，这种程度的震动完全是家常便饭。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("好像只是小型地震，大家没事吧！？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("没事……但你刚才遇到地震的第一反应，居然是捂住裙子吗？", "拉斐尔")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("还真是越来越进入角色了啊~", "拉斐尔")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我、我没有！\n只是这几天……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("求求你，放过我吧！！！")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("不过像南极这种被厚重冰层覆盖的大陆，应该很难受到地壳运动影响的……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔皱着眉头盯着窗外。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("难道是我记错了？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("『第九原质』，到底还是出现异常了吗……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","panic")
	await novel_interface.show_dialog("小怜你看！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮突然指着窗外叫道，我连忙凑上前去。")
	await novel_interface.show_text_only("平坦的冰层上，出现了一道巨大的裂缝，在夜幕的笼罩下，缝隙就像直通地狱的深渊。")
	await novel_interface.show_text_only("某种意义上，那道裂痕甚至可以称作峡谷了……")
	await novel_interface.show_text_only("缝隙的边缘还保有尖锐的凸起，网状结构的异变从冰层深处刺出。")
	await novel_interface.show_text_only("两边的冰崖并没有出现高度纵差，整片冰架给人一种像被某种巨大的力量硬生生撕开的感觉。")
	await novel_interface.show_text_only("巨大的裂口在高地区域横向蔓延，直至远处……")
	await novel_interface.show_text_only("还好，我们的所在位置是一处安全的谷地。")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("那边，很奇怪……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔和海因里希也凑了过来，看着眼前的异象倒抽了一口冷气。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("那个建筑……完全没受到影响？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我们前方的冰原上，一座巨大的人工建筑物正诡异的矗立在裂口前进的路径上。")
	await novel_interface.show_text_only("深色的建筑物在苍白的大地上显得格格不入。")
	await novel_interface.show_text_only("地震造成的裂痕分开成为两个弧形绕过建筑物，仿佛想故意避开里面的某种存在。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("那个地方……是不是莉琉刚才提到的汇合点？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","stare")
	await novel_interface.show_dialog("从位置上看，应该没错。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("操作台再度发出了电流杂音，补给站的通讯似乎正在恢复。")
	await novel_interface.show_dialog("喂，小怜！听得到吗！？", "莉琉")
	await novel_interface.show_text_only("莉琉的声音听上去有些紧张。")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("调用的侦查卫星群组完成变轨之前，南极大陆的影像情报只能以35分钟为周期进行静态刷新。")
	await novel_interface.show_text_only("荧幕上正不断弹出莉琉从各大极地站点中截取到的消息。")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("这次的地震，各方面都太不正常了。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("奇怪，还是联系不到白皇后基地的负责人……", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉盯着纽伦堡基地的气象传感器更新的报告。")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("等等，那是……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉开始快速的操作手持设备，调取了南极区域内所有的实时气象和水文监测数据。")
	await novel_interface.show_text_only("突如其来又高度一致的数据变化趋势，让这位SID主管回想起自己在大学时选修过的一门课程——")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("爱衣，你记不记得……", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("嗯？", "爱衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("即使不考虑核武器和异质物的影响，地球上依然潜伏着许多足以造成\"世界末日\"的自然因素。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("当然啦，人类是地球上第五次物种大灭绝之后崛起的物种，自然因素才是最关键的……", "爱衣")
	novel_interface.change_2nd_expression("normal")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_dialog("等等，要说南极最危险的自然因素——", "爱衣")
	novel_interface.character_light(0.35,"serious")
	await novel_interface.show_dialog("糟糕，是甲烷！！", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("小怜，你确定那个裂隙就在你们附近？", "莉琉")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Depot2.png")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("对，但奇怪的是……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我将裂隙显得有些刻意的绕过白皇后基地的情报汇报给了莉莉琉。")
	await novel_interface.show_text_only("莉琉思考了片刻，语气变得严肃起来。")
	await novel_interface.show_dialog("你们听好，那道裂缝中，恐怕正在源源不断的泄露出被冰封了上百万年的甲烷。", "莉琉")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("南极下方确实储存着数十亿吨甲烷，不过那些……不是大多以固体可燃冰的形式存在着吗？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("地震导致冰架开裂所释放的压力，加速了那些被迫裸露出来的可燃冰汽化。", "爱衣")
	await novel_interface.show_dialog("地震之后，纽伦堡基地的大气传感数据显示，南极上空的甲烷浓度对比一小时前上涨了2.1ppm。", "莉琉")
	await novel_interface.show_dialog("而其他几个气象站的数据虽然略微有所不同，但都显示出不同程度的甲烷含量上升。", "莉琉")
	await novel_interface.show_dialog("不仅如此，埃默里冰架前缘海域也出现了异常，可以推测是海底甲烷气泡上升引起的潮汐波动紊乱。", "莉琉")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("我记得甲烷的温室气体效应是二氧化碳的21倍…\n…", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("也就是说……天气会变热？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我努力回忆着环保小册子里的内容。")
	await novel_interface.show_dialog("目前已经出现了潮汐幅度加大，风速变缓，接下来的这段时间温度会以每12小时0.2度的速度上升。", "莉琉")
	await novel_interface.show_dialog("七天之内，从含氧量不足的海洋开始，全球的生物将会迎来新一轮的大清洗。", "莉琉")
	await novel_interface.show_text_only("拉斐尔似乎意识到了问题的严重性。")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("两周内，露天种植的庄稼会全部干枯……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("三周内，物种开始大面积灭绝，90%的人缺少饮用水，连近地卫星都会受到大气影响而停摆……", "爱衣")
	await novel_interface.show_dialog("45天之后，就只有少数几种昆虫可以在那样的大气环境中生存……", "莉琉")
	await novel_interface.show_dialog("如果不加以阻止的话，很快我们就会成为昆虫的食材了~", "爱衣")
	await novel_interface.show_text_only("我望着那道裂缝，忍不住打了个冷颤。")
	await novel_interface.show_text_only("莉琉清了清嗓子，在场的人都屏住呼吸，等待她接下来的命令。")
	await novel_interface.show_dialog("现在那道裂缝造成的影响正随着时间的推进呈几何级数扩大，每一分钟都是宝贵的。", "莉琉")
	await novel_interface.show_dialog("如果等联合议会的应急团队赶到再处理，状况就变得不可挽回了。", "莉琉")
	await novel_interface.show_dialog("而且他们也不一定有能力应对这种情况……", "莉琉")
	await novel_interface.show_dialog("所以我想问一下海因里希——", "莉琉")
	await novel_interface.show_text_only("顺着莉琉的话锋，我们把目光移到了那位炼金术士身上。")
	await novel_interface.show_dialog("如果这与你要守护的『第九原质』有关……那么你之前遇到过可能导致如此严重后果的情况吗？", "莉琉")
	novel_interface.show_character("heinrich_battle","speechless")
	await novel_interface.show_dialog("所以说，这才是这个差事最头疼的地方啊~", "海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("金发的炼金术士一边回忆一边无奈的笑起来。")
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.character_light(0.35,"bored")
	await novel_interface.show_dialog("『那位』每次都是将我传送到事发地点，将问题抛给我之后就扬长而去。", "海因里希")
	await novel_interface.show_dialog("但“那种东西”如果没人处理的话，整个世界都会就此完蛋吧……", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Baizhu/Heinrich_Memory.png")
	await novel_interface.show_dialog("1600年，西班牙殖民地附近的埃纳普蒂纳火山。", "海因里希")
	await novel_interface.show_dialog("因为我对『那位』的抗拒而拖延了几天，结果附近数公里的村庄都被夷为平地。", "海因里希")
	await novel_interface.show_text_only("少女露出了悲伤的表情。")
	await novel_interface.show_dialog("虽然最终处理掉了……但在那次事件中直接死亡人数超过六万人。", "海因里希")
	await novel_interface.show_dialog("后来火山灰飘荡在空中遮蔽阳光达一年之久，造成了数百年中最寒冷的几年。", "海因里希")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("海因里希不想再继续说下去。")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Depot2.png")
	await novel_interface.show_dialog("15世纪末秘鲁的那次火山爆发吗……", "爱衣")
	await novel_interface.show_dialog("——确实是同等量级的危机。", "莉琉")
	await novel_interface.show_dialog("那之后持续数年的寒冷气候引发了全球范围的饥荒和战争，甚至有的王朝就此终结。", "莉琉")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("居然这么严重吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("这样的责任确实不该由你一个人来背负。", "莉琉")
	await novel_interface.show_dialog("小怜，你刚才说过，你们现在有可以在寒冷气候下行动的对策吧？", "莉琉")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("你的意思……是要让我们一起去帮忙吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("对，虽然无法判断具体情况，但很可能唯一的解决办法就在那座基地中。", "莉琉")
	await novel_interface.show_dialog("至少要采集到现场数据……", "爱衣")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("如果那个地方甲烷浓度太高，我们没办法过去吧？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("你们口中的“甲烷”，是指目前充斥在空气里中的『燃素』物质么？", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然这种表达方式有些奇怪，但我还是点了点头。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("那就没问题了，那个地方上空的燃素浓度，呈现出漩涡状的下降。", "海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("那里莫非就是指……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希所指的，正是白皇后基地。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("白皇后基地外。")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Snedronningen2.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("喂——安妮，能听到我们的声音吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("冰雪中拔地而起的巨型建筑物前，我用手挡着风对着老旧的无线电对讲机喊道。")
	await novel_interface.show_dialog("OK……信号良好……\n暴风雪……要到了，你们小心……", "安妮")
	await novel_interface.show_text_only("对讲机中安妮的声音有些断断续续的。")
	await novel_interface.show_text_only("莉琉要求我们必须抓紧时间进行气象数据采集并传送回新丰州。")
	await novel_interface.show_text_only("与此同时，考虑到海因里希的说法——这间与周遭环境格格不入的基地似乎有什么蹊跷。")
	await novel_interface.show_text_only("尽管百般不愿意，我还是在狂风中一路捂着裙子和拉斐尔及海因里希来到了这座巨大的基地。")
	await novel_interface.show_text_only("安妮则负责通过古老的无线电设备，保持着我们和莉琉之间的通讯。")
	await novel_interface.show_text_only("一路走来，随身携带的气相色谱仪表明空气中的确存在着浓度爆表的甲烷气体。")
	await novel_interface.show_text_only("就在我难受得快要晕过去的时候，拉斐尔拉住了我的手。")
	await novel_interface.show_text_only("从这位大小姐身上传来的温暖治愈气息，是我能够勉强到达这里的主要原因。")
	novel_interface.show_character("ren_battle","gratified")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("哼，要不是答应了莉琉要保护好你的安全……", "拉斐尔")
	novel_interface.character_light(0.35,"sob")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……我也是被莉琉强迫的啦！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("才说两句话，我就被灌了一嘴雪。")
	await novel_interface.show_text_only("如果没有温玉的加持，我绝对会瞬间被冻成一座槽点满满的冰雕。")
	await novel_interface.show_text_only("不过总体来看，这座基地的确比我们之前所处的补给站规格高级许多。")
	await novel_interface.show_text_only("穿过固定翼飞机滑翔跑道，我们站在一处石碑前。")
	await novel_interface.show_text_only("石碑上方嵌入了一个采集箱，花体字在其周围展现着基地的名字——Snedronningen。")
	novel_interface.show_character("ren_battle","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","stare",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("S……什么来着……？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("是“Snedronningen”，芬兰语，笨蛋~", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("这个我无法念出名字的基地，光地表的建筑面积就已经十分惊人，而它的主要结构还是在地下。")
	await novel_interface.show_text_only("在南极这种严酷的环境下，这更是代表着一笔巨大的投资。")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("走吧！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希的动作，比我的反应快了太多。")
	await novel_interface.show_text_only("这位炼金术士将手贴合在门口的监控锁上，就像拆ATM机一样把巨大的框体从墙上直接卸了下来。")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("（太暴力了吧！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/xiaolianBase.png")
	await novel_interface.show_text_only("随着海因里希利落地解除了门闸的锁定，齿轮驱动的钢索开始滑动。")
	await novel_interface.show_text_only("在我们面前缓缓展开的，是略微下倾的楼梯通道。")
	await novel_interface.show_dialog("……本来是想用正常的方式先打个招呼的……", "小怜")
	await novel_interface.show_text_only("我忍不住看了一眼门柱上的大洞。")
	await novel_interface.show_text_only("造成了这种程度的动静，却没有人出现。")
	await novel_interface.show_dialog("我们……先进去吧。", "小怜")
	await novel_interface.show_text_only("我注意到通道旁边的地面上，有几枚子弹壳。")
	await novel_interface.show_text_only("一股不祥的强烈预感涌上我的心头……")
	print("=== 深海恐惧症篇第18话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
