# bathophobia_ep17.gd - 深海恐惧症篇第17话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep17_script()

func play_script():
	pass

func bathophobia_ep17_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Snedronningen.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("苍茫的大地被漫天的极光映照成异样的绿色。")
	await novel_interface.show_text_only("死寂的极寒大陆上，一串灯光划破了黑暗。")
	await novel_interface.show_text_only("几辆雪地摩托在夜色笼罩的冰原中划过，越过停机坪，停在庞大的基地入口处。")
	await novel_interface.show_text_only("他们的正前方矗立着一座茧型石碑，嵌刻了格罗夫山灶神星陨石的收集箱。")
	await novel_interface.show_text_only("石碑上用岩石涂料写下的『Snedronningen』字样环绕着收集箱，在射灯的照射下泛起银色光芒。")
	await novel_interface.show_text_only("此处正是骑手们的目标——白皇后基地。")
	await novel_interface.show_text_only("队伍前方一名全副武装的特遣队员掀开了防风镜。")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("——到了！", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在她身后的五名骑手接连熄火下车，各自收拾起自己的装备。")
	await novel_interface.show_text_only("这是一支拥有标准作战小队配置的“科考团”。")
	await novel_interface.show_text_only("两个月前，疑似异质物产生的电波在南极出现的消息吸引来了各种势力，擦枪走火也时有发生。")
	await novel_interface.show_text_only("为了保护样本安全，特遣队必须更加谨慎。")
	await novel_interface.show_text_only("不过他们的运气很好，畅行无阻的抵达了备用计划中提到的实验基地。")
	await novel_interface.show_dialog("OK~接下来只等交接了！", "特遣队员D")
	novel_interface.show_character("baizhu_battle","normal")
	await novel_interface.show_dialog("嗯。", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("与其他人厚实保暖的服装风格截然不同，对低温有特殊抗性的白烛只是穿着平时的衣物。")
	await novel_interface.show_text_only("她身上携带着的武器，也是自己改造的。")
	await novel_interface.show_text_only("这次小队的行程正如白烛所料——")
	await novel_interface.show_text_only("几小时前，白烛成功的从深海不明物的躯体上取得了活体样本。")
	await novel_interface.show_text_only("为了完成研究计划，牛奶的上司派了乌斯怀亚号破冰船来协助特遣队。")
	await novel_interface.show_text_only("当样品箱被移交至乌斯怀亚号时，破冰船上的生物实验室突然“意外”出现了电力故障。")
	await novel_interface.show_text_only("同时，一个多小时的路程外的白皇后基地积极发出回复，表示愿意提供相应规格的实验室。")
	await novel_interface.show_text_only("特遣队顺利的拿到了通行许可，并被要求在九十分钟内把样本送至白皇后基地。")
	novel_interface.show_character("baizhu_battle","normal")
	await novel_interface.show_dialog("（已经，到这里了……）", "白烛")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("那群家伙，会出现吗？", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛悄悄的握紧拳头。")
	await novel_interface.show_text_only("更令少女不安的，是样本箱内的东西似乎正在引发自己的某种感应。")
	novel_interface.show_character("baizhu_battle","sad")
	await novel_interface.show_dialog("……\n（这个感觉，莫名的熟悉）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然而容不得白烛多加思考，四周突然剧烈地摇晃起来。")
	novel_interface.show_character("baizhu_battle","speechless")
	await novel_interface.show_dialog("（是深海后遗症吗？）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不，显然不是。")
	await novel_interface.show_text_only("——整个大地都在晃动。")
	await novel_interface.show_text_only("远处的大地传来轰鸣。")
	await novel_interface.show_text_only("即使是久经战场的老兵也一阵惊慌。")
	await novel_interface.show_text_only("白色大陆的震动，只持续了不到30秒。")
	novel_interface.show_character("milk_battle","shock")
	await novel_interface.show_dialog("南极不是非地震带吗……居然会地震？！", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("但这次的震感并不强烈，只是让大家产生了一瞬的晕眩感。")
	await novel_interface.show_dialog("（嘟嚷）比起海啸可差远了……", "特遣队员B")
	await novel_interface.show_dialog("只是咱们脚下的冰架够结实，刚才那么一下释放的能量，在热带城市足以弄得房倒楼塌了。", "特遣队长")
	await novel_interface.show_text_only("但对小队成员来说，这种程度的地震实在无感，新奇感消失后，众人立刻恢复了正常。")
	novel_interface.show_character("baizhu_battle","normal")
	await novel_interface.show_dialog("好了，走吧。", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛小心的抱着样本箱，从牛奶雪地摩托的后座上跳下来。")
	await novel_interface.show_dialog("一会我要泡一杯热可可，这一趟真累的够呛~", "特遣队员B")
	await novel_interface.show_text_only("与大家轻松的心情不同，队长一直有意无意地盯着白烛。")
	await novel_interface.show_text_only("如果没有这个小姑娘，他们这次极地任务就不会有任何收获——就像其他同行组织一样。")
	await novel_interface.show_text_only("深海恐惧症、高压潜水仓、不明生物……")
	await novel_interface.show_text_only("哪怕换做他自己，也无法保证在这样的压力下能够完成取样吧……")
	await novel_interface.show_dialog("剩下的只要交给那边的科学家就行了吧？", "特遣队员D")
	await novel_interface.show_dialog("回到布宜诺斯艾利斯之后，我们得请你喝一杯啊？小白~", "特遣队员C")
	novel_interface.show_character("milk_battle","sprite")
	await novel_interface.show_dialog("我家小白烛不喝酒的啦！", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶一把将白烛扯到自己怀里，大声嚷道。")
	await novel_interface.show_text_only("白烛据了抿唇，刻意压制着自己的不安。")
	await novel_interface.show_text_only("牛奶在基地门口发出了几次通行申请之后，没有收到任何回应。")
	novel_interface.show_character("milk_battle","shock")
	await novel_interface.show_dialog("有点奇怪啊……", "牛奶")
	await novel_interface.show_dialog("是刚才的地震把线路搞坏了？\n上岸前明明和这边打过招呼的……", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不过，尽管基地正门限制车辆通行的地桩并没有放下，但小队已经提前获得了通行码。")
	await novel_interface.show_text_only("于是一行人向基地侧面亮着光的门闸处走去。")
	await novel_interface.show_text_only("白烛忽然停下，将样本箱塞给了其中一名队员。")
	await novel_interface.show_text_only("紧接着，少女双手紧握住了自己的枪刃。")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("……怎么了？", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("注意到白烛的异常，牛奶立刻警觉的卸下背后的武器握在手中。")
	await novel_interface.show_text_only("两人的变化提醒了其他成员，特遣队立刻进入全员备战状态，以一个能互相掩护的半圆阵型前进。")
	await novel_interface.show_dialog("……不是吧？", "特遣队员D")
	await novel_interface.show_dialog("嘘，小声点。", "特遣队长")
	await novel_interface.show_text_only("空气中只留下雪地靴踩在冰面上的声音，和几人细微的呼吸声。")
	await novel_interface.show_text_only("牛奶靠近门禁，在身份识别区输入了通行码。")
	await novel_interface.show_text_only("验证顺利通过，屏幕上出现了绿色的Enter字样。")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("呼——应该没什么问题吧？", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("但白烛的精神却无法松懈下来……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/baizhuBase.png")
	await novel_interface.show_text_only("随着齿轮咬合与钢索滑动的声音，白皇后基地的闸门缓缓打开……")
	await novel_interface.show_text_only("闸门后面是一条径直的楼梯，通往昏暗的下层。")
	await novel_interface.show_dialog("有人吗——", "牛奶")
	await novel_interface.show_text_only("狭窄的通道，空荡荡地拉长了她的问话。")
	await novel_interface.show_dialog("就算这个基地的大部分设施都在地下，但连个迎接我们的人都没有吗？", "牛奶")
	await novel_interface.show_dialog("至少也要来个研究员来看一下样本情况吧……", "特遣队员B")
	await novel_interface.show_dialog("——战斗准备！", "白烛")
	await novel_interface.show_text_only("白烛盯着深邃的楼梯尽头，发出了命令。")
	await novel_interface.show_dialog("恐怕，有人盯上我们了。", "白烛")
	await novel_interface.show_dialog("果然越是机密的行动，就越容易引人注目嘛……", "牛奶")
	await novel_interface.show_dialog("（会是你在意的那群家伙吗）", "牛奶")
	await novel_interface.show_text_only("枪械保险栓被打开的声音接连响起。")
	await novel_interface.show_text_only("特遣队员恢复了士兵的本性，望向这位拥有临时战术指挥权的少女，等待她的下一步命令。")
	await novel_interface.show_dialog("如果有埋伏，我们现在的位置太暴露了，可以撤回到冰原上……", "特遣队员D")
	await novel_interface.show_dialog("不行，刚才收到的警告一小时内会有暴风雪。", "白烛")
	await novel_interface.show_dialog("全员戒备，继续前进。", "白烛")
	await novel_interface.show_dialog("（众）是！", "特遣队员")
	await novel_interface.show_text_only("大家的脚步放轻，呼吸声也更加隐蔽。")
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("——小心！", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("利刃破空气的声音打破了这片刻沉默。")
	await novel_interface.show_text_only("一名手持重型镰刀状兵器的生物突然从从阴影中出现，攻向白烛的右侧。")
	await novel_interface.show_text_only("牛奶的提醒让白烛及时避开了这记攻击。")
	novel_interface.show_character("baizhu_battle","stare")
	await novel_interface.show_dialog("——！！！", "白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("witch_third")
	await novel_interface.show_dialog("呵呵呵~呵呵呵呵哈哈——", "???")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("袭击者是一个眼神涣散、肢体动作奇怪的少女，行动时关节发出着喀喀的响声。")
	await novel_interface.show_text_only("刚才还平静的通道入口，突然涌过来数名神情疯狂的少女。") 
	await novel_interface.show_text_only("特遣队员立刻进入战斗状态，小队成员分开保持着标准的三角阵型对袭击者开枪反击。")
	await novel_interface.show_text_only("负责持有样本箱的队员被保护起来，白烛率先为他挡住了另一侧的袭击。")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Snedronningen_Exhibition_Room.png")
	await novel_interface.show_text_only("众人一边保持着射击节奏一边寻找掩体，很快转到了一个展览室似的空间。")
	await novel_interface.show_text_only("这个房间灯光昏暗，四周的展柜里是一些生物标本样的东西。")
	await novel_interface.show_text_only("队长组织起防线守卫房间的入口，小队全员都发现了这些敌人的异常。")
	await novel_interface.show_text_only("那些被击中的敌人伤口不会流血，而且似乎完全感觉不到疼痛。")
	await novel_interface.show_text_only("折叠式防暴盾牌被展开，黑色的凯夫拉纤维抵挡住了一次冷兵器的冲击。")
	await novel_interface.show_text_only("另一侧冲来的敌人手持大剑，被手持防暴盾的队员挡在了入口通道的转角处。")
	await novel_interface.show_text_only("盾兵的身后，连续不断的9毫米子弹正挟着硝烟的味道迅速向敌人倾泻。")
	await novel_interface.show_dialog("换弹夹！", "特遣队员C")
	await novel_interface.show_text_only("连续射击并没有阻止敌人的攻势，脸部中弹的敌人裂开一个极为夸张的笑容。")
	await novel_interface.show_text_only("她的身体借助盾牌的力量翻腾而起，蝙蝠一般倒挂在通道的顶端。")
	novel_interface.show_character("milk_battle","shock")
	await novel_interface.show_dialog("那还是……人类吗？", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("对方身上的弹孔涌出大量墨绿色的液体，几乎被打断的颈部在瞬间被染成了紫绿混杂的颜色。")
	await novel_interface.show_dialog("小心！", "特遣队员B")
	await novel_interface.show_text_only("通道尽头，更多的敌人冲了过来。")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("后退——！", "牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小队成员不得不向两个不同的方向散开，很快又各自找到了合适的进攻点。")
	await novel_interface.show_text_only("片刻的交手令所有人都意识到，对方……不管那是什么，其单兵战斗力绝不在己方之下。")
	await novel_interface.show_text_only("但疯狂的战意要远超这批职业军人。")
	novel_interface.show_character("baizhu_battle","angry")
	await novel_interface.show_dialog("……这些人……", "白烛")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("milk_battle","solemn",0.25)
	await novel_interface.show_dialog("怎么回事？！\n这群家伙看上去也太奇怪了！", "牛奶")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛知道，面前这些手持冷兵器的少女们，显然和自己一样——")
	await novel_interface.show_text_only("不，还是有所不同。")
	novel_interface.show_character("baizhu_battle","stare")
	await novel_interface.show_dialog("（她们更像是父亲所描述的……）\n（\"Ningen\"的作风）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("极强的抗击打和回复能力，常人无法达到的关节活动度，使得她们呈现出一种瘆人的强悍。")
	await novel_interface.show_text_only("失去理智的人，仿佛被程序驱动的杀人机器一样。")
	novel_interface.show_character("witch_third")
	await novel_interface.show_dialog("咿呵呵呵呵——呷呷呷呷呷…………", "缝合女巫")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那不是人类的声带可以发出的声音，更像是恶魔的语言……")
	await novel_interface.show_text_only("突然，手持样本箱的队员被一支箭射中，在队员倒下的同时样本箱也滚落了出去。")
	await novel_interface.show_text_only("然而那群敌人，并没有在意地上的箱子。")
	await novel_interface.show_dialog("白！", "特遣队员D")
	await novel_interface.show_text_only("被敌人一路逼进展览室深处的特遣队员，需要白烛下达进一步指令。")
	await novel_interface.show_text_only("在这样的环境下，一般的作战原则已经失效，唯一能依靠的就是白烛的感觉和判断。")
	novel_interface.show_character("baizhu_battle","stare")
	await novel_interface.show_dialog("（它们的目的，并不是夺取采集的样本？）", "白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("可恶！", "牛奶")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_battle","stare")
	await novel_interface.show_dialog("（看来这些人的唯一目标——）", "白烛")
	novel_interface.change_expression("angry")
	await novel_interface.show_text_only("——即是剿灭这只特遣队。")
	await novel_interface.show_dialog("……\n（果然是你们！）", "白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛的视线，落在一名敌人眼罩上的标识上。")
	await novel_interface.show_text_only("和她在调查父亲死讯过程中，无数次看到的图案一模一样——")
	await novel_interface.show_text_only("那是一只令人毛骨悚然的、长着肢体的眼睛。")
	print("=== 深海恐惧症篇第17话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
