# bathophobia_ep26.gd - 深海恐惧症篇第26话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep26_script()

func play_script():
	pass

func bathophobia_ep26_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Subjective_Validation1.png")
	await novel_interface.show_text_only("『自我』是什么？")
	await novel_interface.show_text_only("在人的意识中，『自我』总会占据大部分空间。")
	await novel_interface.show_text_only("所有关于“我”的东西都很重要——")
	await novel_interface.show_text_only("我的房间、我的电脑、我的手机、我的书包，以至于我的感受和记忆……")
	await novel_interface.show_text_only("这些东西都会在其原本的形态上，被大脑小心翼翼的重新包装，并赋予特殊的意义。")
	await novel_interface.show_text_only("“我是特殊的。”——你的大脑让你如此相信着。")
	await novel_interface.show_text_only("然而，如果想要相信一件事，人们总能搜集到各种各样的证据。")
	await novel_interface.show_text_only("就算是毫不相干的事物：一本杂志，一场考试，一次偶遇，或者一个梦——")
	await novel_interface.show_text_only("只要你想相信，就一定能从中找到符合自己期待的逻辑。")
	await novel_interface.show_text_only("心理学中，这种效应叫做『主观验证』。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("你当然可以说，“只要我相信，我就是特殊的！”")
	await novel_interface.show_text_only("那么，唯一的问题是——")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Subjective_Validation2.png")
	await novel_interface.show_text_only("你的自我，是真实的吗？")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("我们从监控室出来走到隧道尽头，一路无言。")
	await novel_interface.show_text_only("海因里希根据录像中那个男人通过的位置，在墙上直接切出一个大洞。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Metal_Corridor.png")
	await novel_interface.show_text_only("墙后是一条被厚实黄色特殊金属所严密包裹的狭长通道。")
	await novel_interface.show_text_only("就算使用电气石，在毫无光源的通道中也只能照亮附近一小块区域。")
	await novel_interface.show_text_only("我们默默前进，脚步声似乎能反射到地心深处，一切都是如此的没有实感。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("我们……还在那个什么东西的『梦境』里吗？","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("应该是的，而且情况恐怕比预想中更加麻烦。","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女晃了晃手中作为光源的电气石，表情严肃的解释道。")
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("监控室的电爆陷阱对我们而言是“真实”的，那次电击的能量足以瞬间把人的内脏烤熟。","海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("虽然这套战服能够承受，但我依然会有痛感……","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("在做梦的时候，如果受到疼痛之类的强烈刺激…不是会马上醒过来吗？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("但在这个『梦境』里…我们恐怕就算死掉，也无法醒过来…","海因里希")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("不过只要我们中有一个人能以任何方法醒来，应该都能让咱们回到现实。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("否则，我们会在这个噩梦里一直沉睡下去吗……","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔的声音有些颤抖，进入通道以后她就一直揪着我的衣服不放。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("（她很怕黑吧……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("身体的晃动让我忽然意识到一个严重的问题。")
	await novel_interface.show_text_only("我紧握着那块从监控室带出来的手表。")
	await novel_interface.show_text_only("探查中，我意外的从这块手表中获取了一些资料。")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("（准确的说，应该是一段语音记录。）","小怜")
	await novel_interface.show_dialog("希望前面，能找到我们想要的答案吧……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("想到这里，我加快了步伐。")
	await novel_interface.show_text_only("一定要尽快。")
	await novel_interface.show_text_only("……是啊，这不是最基本的常识吗。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("（梦到上厕所……）\n（简直是，最糟糕的状况了啊！！）","小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Laboratory.png")
	await novel_interface.show_text_only("终于，在打开一扇厚重的金属门后，我们进入了这间实验室。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("应该就是这里了……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("与基地的其他区域不同，这间实验室安静的有些异常，墙壁和地板都是柔软的吸音材料。")
	await novel_interface.show_text_only("在昏暗的空间内，默默伫立着十几个培养槽，只有设备的状态灯隐约闪烁着淡蓝色的光点。")
	await novel_interface.show_text_only("房间的天花板上，大量的线路和管道被规划得整齐有序。")
	await novel_interface.show_text_only("即使以新丰洲科学院的标准，这都是一间高规格的实验室。")
	await novel_interface.show_text_only("我们很快就找到了这里唯一还在工作的设备……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Baizhu_eyesclosed.png")
	await novel_interface.show_text_only("室内的温度接近冰点，充盈着培养槽的淡蓝色液体正安静地守护着它所包裹的对象。")
	await novel_interface.show_text_only("乌黑的长发，白皙的皮肤——仿佛正在海洋的怀抱中沉睡的，正是我们在录像中看到的那个女生。")
	await novel_interface.show_text_only("肌肤尚有血色，肢体也在培养槽中自然摆动，加上她面罩周围冒出的气泡，都预示着——")
	await novel_interface.show_dialog("她……还活着？","拉斐尔")
	await novel_interface.show_dialog("她，也在梦境里？还是说……","小怜")
	await novel_interface.show_text_only("海因里希走到培养槽前，轻轻将手按在上面，摇了摇头。")
	await novel_interface.show_dialog("这个设备只是在维持她“未死亡”的状态……","海因里希")
	await novel_interface.show_dialog("（小声）奇怪……","海因里希")
	await novel_interface.show_text_only("金发少女好奇的打量着里面的器械，一路绕到了培养槽背后。")
	await novel_interface.show_dialog("果然——","海因里希")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Laboratory.png")
	await novel_interface.show_text_only("我和拉斐尔跟过去，发现少女后背连衣裙破损处的伤口依然清晰可见。")
	await novel_interface.show_text_only("不，与其说是伤口，更像是切面。")
	await novel_interface.show_text_only("就像美工刀在橡皮上雕出的一样，皮肤、肌肉、骨骼都被光滑整齐的切开。")
	await novel_interface.show_text_only("而她的身体似乎还没反应过来——没有出血，没有增生，伤口临近的皮肤甚至没有发炎或肿胀。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("那支枪……好像连“损伤”的概念都抹消了，身体自然没办法愈合。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("这个位置穿过的脏器和神经太多，离开这个设备的话，她应该活不了几分钟……","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("（虽然不知用了什么方法，但她身体的其他部分都已经被恢复到足以使意识苏醒的程度了。）","海因里希")
	await novel_interface.show_dialog("（如果是梦境的核心，必须想办法叫醒她。）","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然，一团白色的微光在少女身上跳跃了一下。")
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("……","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女露出狡黠的笑容。")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("（要叫醒睡美人的话……）","海因里希")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("主人，请你帮我去那边监测一下她的呼吸频率。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("哦~","小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/Baizhu_eyesclosed.png")
	await novel_interface.show_text_only("我再次回到少女正面，仰望着容器中的少女，此刻的她正以极慢的速度呼吸着。")
	await novel_interface.show_dialog("好漂亮……","小怜")
	await novel_interface.show_text_only("我伸手想触碰水槽，拉斐尔从背后敲了我一下。")
	await novel_interface.show_dialog("喂！你在幻想着做些什么下流的事情呢？","拉斐尔")
	await novel_interface.show_dialog("什、什么啊！\n我才不是那种乘人之危的家伙……","小怜")
	await novel_interface.show_text_only("透过水槽中的液体，我看到海因里希正在背面摸索着几根线管。")
	await novel_interface.show_dialog("（……？）","小怜")
	await novel_interface.show_dialog("她要醒过来咯~","海因里希")
	await novel_interface.show_dialog("哎？！","小怜")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Baizhu_eyesopen.png")
	await novel_interface.show_text_only("随着一阵电流声，培养槽中的少女猛地睁开了眼\n睛。")
	await novel_interface.show_text_only("我抬头望去，正好和她视线相对。")
	await novel_interface.show_text_only("那是一双殷红、冷淡的眸子。")
	await novel_interface.show_text_only("被那双眼睛所吸引，我有些恍惚……")
	await novel_interface.show_text_only("突然，黑发少女身上泛起泡沫般的银色光芒，水槽内的液体开始膨胀，在她的周身形成漩涡。")
	await novel_interface.show_text_only("——她正死死的盯着我手里拿着的手表！")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Laboratory.png")
	await novel_interface.show_text_only("“咔”地一声，培养槽崩裂。")
	await novel_interface.show_text_only("爆炸般的银色光芒四散溢开，蓝色培养液像海浪般向我和拉斐尔涌来。")
	await novel_interface.show_text_only("少女看我的眼神中泛起杀意。")
	await novel_interface.show_text_only("然而她的身体刚前倾半步，就像断了线的风筝般向我倒下来……")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("不好——！！","小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("砰——！")
	await novel_interface.show_text_only("……")
	await novel_interface.show_dialog("（唉？我跌倒了吗？）\n（头好疼……）","小怜")
	await novel_interface.show_dialog("（好冷……被接近0度的液体淋透了……）\n（温玉也没办法抵抗嘛……）","小怜")
	await novel_interface.show_dialog("（糟…她、她正倒在我身上？）","小怜")
	await novel_interface.show_dialog("（不对，那我的手在摸的是另一个人的……？）","小怜")
	await novel_interface.show_text_only("一股温热的呼吸吹过我的耳朵。")
	await novel_interface.show_dialog("你！这！个！！！","拉斐尔")
	await novel_interface.show_dialog("死！！变！！态！！！！","拉斐尔")
	await novel_interface.show_text_only("——咚！")
	await novel_interface.show_text_only("躺在地上的我腹部吃了一记肘击。")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Laboratory.png")
	await novel_interface.show_text_only("我浑身湿漉漉的，一脸木然坐在满地的水泊中。")
	await novel_interface.show_text_only("已经，没什么，好害怕的了……")
	await novel_interface.show_dialog("喂！能听到吗，小怜——","莉琉")
	await novel_interface.show_text_only("无线电中传来莉琉的声音。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("莉琉……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到我无精打采的回复，莉琉长吁一口气。")
	await novel_interface.show_dialog("情况如何？你知不知道过去多久了！\n我们已经和安妮会合了！","莉琉")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("我们没有危险，现在有点事……一会再联络你。","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我关闭了无线电，将注意力重新集中在黑发少女身上。")
	await novel_interface.show_text_only("海因里希正坐在一旁，让少女靠在自己的肩上。")
	novel_interface.show_character("baizhu_normal","stare")
	await novel_interface.show_dialog("——。","神秘少女")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她张口想说些什么，但却发不出声音。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("对了，她不要紧吧！？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("放心吧，伤口已经愈合了。","海因里希")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("或者说……重生了。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","angry")
	await novel_interface.show_dialog("…………","神秘少女")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她好像在努力呼唤着什么人的名字，却发不出一点声音，一副快急哭出来的表情。")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("不要着急……“小白烛”。","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我试着用那个名字呼唤她。")
	await novel_interface.show_text_only("少女有些困惑的看着我。")
	novel_interface.show_character("baizhu_normal","shock")
	await novel_interface.show_dialog("……你……怎……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("似乎是因为太久没说话，她的声带肌已经失去了力量。")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("你是叫白烛，没错吧……","小怜")
	await novel_interface.show_dialog("那段录音里，是这么称呼你的。","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","shock")
	await novel_interface.show_dialog("…………","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女的眼神转向我手中的军用手表。")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("这是你朋友的东西……还记得吗？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我把手表放进她的手中，轻轻合拢好她的手指。")
	novel_interface.show_character("baizhu_normal","cry")
	await novel_interface.show_dialog("……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着那块手表，白烛的瞳孔急剧收缩，眼泪止不住的流了出来。")
	novel_interface.show_character("baizhu_normal","tear")
	await novel_interface.show_dialog("……牛奶……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女终于说出那个名字，眼神中充满着痛苦、哀伤与不甘。")
	await novel_interface.show_text_only("我坐到白烛身旁想要安慰一下她，触到她肩膀的一剎那，少女的头已经无力的垂到了我的肩上。")
	await novel_interface.show_text_only("白烛紧握着那块手表，在我的怀里皱了皱眉。")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("（轻声）别怕……都结束了。","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我轻轻的抚了抚她的头发。")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("……应该是体力透支了吧？","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("嗯……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("毕竟，已经过去19年了。")
	
	print("=== 潜渊症篇第26话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
