# bathophobia_ep23.gd - 深海恐惧症篇第23话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep23_script()

func play_script():
	pass

func bathophobia_ep23_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Control_Room.png")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("通行权限……搞定。","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("哔——\n监控室的大门应声打开。")
	await novel_interface.show_text_only("室内的音感监控同时开启，白烛和牛奶互相換扶着走进了房间。")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("咳、咳咳——","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("呼，哈啊……","牛奶")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","smile")
	await novel_interface.show_dialog("这里暂时应该是安全的……","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_battle","serious")
	await novel_interface.show_dialog("嗯，我去看一下系统。","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶走到主控台前检查屏幕信息，对好友刚才展现出的异能和惊人的作战能力闭口不谈。")
	novel_interface.show_character("milk_battle","pleased")
	await novel_interface.show_dialog("哎嘿~居然是通用Genuine……","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶曾对白烛炫耀过，在军总三部的电子对抗考核中，她是最快攻破这套安保系统的。")
	novel_interface.show_character("milk_battle","pleased")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_break","think",0.25)
	await novel_interface.show_dialog("牛奶，我……","白烛")
	novel_interface.character_light(0.35,"laugh")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("安心安心~我明白的。","牛奶")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("牛奶看着面露不安的少女，有些心疼的摸了摸她的头。")
	await novel_interface.show_text_only("她不仅完全理解，甚至有些庆幸好友对自己隐瞒了那种能力")
	await novel_interface.show_text_only("不然以Boss的风格，大概不会轻易放过这样的\n“战略资源”吧……")
	await novel_interface.show_text_only("牛奶顺手从白烛头上取下了一根黑色金属发卡，白烛有些意外的看着她，不知要做什么。")
	await novel_interface.show_text_only("牛奶扮了个鬼脸，然后转身轻巧的钻到了主控台的桌子下面。")
	await novel_interface.show_dialog("用金属把这里短路的话，就会触发过载保护。","牛奶")
	await novel_interface.show_text_only("一阵微小的放电声后，主控台上两排指示灯同时熄灭，中央屏幕上的影像也变成一片雪花。")
	await novel_interface.show_text_only("接着牛奶从桌底钻出来，取出自己手表里内置的数据线缆，插在了桌面的接口上。")
	await novel_interface.show_text_only("几秒钟后，主控台的指示灯重新亮起，散热风扇再次开始转动。")
	novel_interface.show_character("milk_battle","serious")
	await novel_interface.show_dialog("只要赶在系统自动重启前将闪存加入自检队列，就可以注入代码了。","牛奶")
	novel_interface.change_expression("pleased")
	await novel_interface.show_dialog("所以说通用安保系统根本行不通嘛~","牛奶")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","mock")
	await novel_interface.show_dialog("即使软件设计的再天衣无缝，如果能从硬件层面破解的话就毫无意义吗……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛想起牛奶曾经在一家茶餐厅眉飞色舞的讲过半天这些理论，也不管自己能听懂多少。")
	await novel_interface.show_text_only("牛奶头也不回的盯着屏幕，左手快速敲击键盘的同时，伸出右手做了个“比心”的手势。")
	await novel_interface.show_text_only("看到这个傻乎乎的熟悉手势，白烛感到心里一暖，有种如释重负的感觉。")
	await novel_interface.show_text_only("——和心意相通的人，其实不必解释什么。")
	await novel_interface.show_text_only("牛奶用超驰控制运行了自己的软件，逐步接管了基地所有的监控设备。")
	await novel_interface.show_text_only("白烛观察着房间内的其它装置，主控台的一侧有一排用图不明的控制器，不过没时间研究了。")
	await novel_interface.show_text_only("牛奶面前的大屏幕上，逐渐显示刚刚获取的监控画面。")
	await novel_interface.show_text_only("屏幕中央，之前被特遣队射击倒地的敌人，现在大多七扭八歪地爬了起来。")
	await novel_interface.show_text_only("虽然行动上还有些迟缓，但身上的伤口，已经开始收敛。")
	await novel_interface.show_text_only("如果放大的话，能看到在这群家伙的伤口上附着着一种绿色的藤网状组织。")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("（那种痕迹，我在一份报告中见到过……）","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在人工干预下，一种藤网状生物会渐渐使它们寄生的人类丧失理智，成为行尸走肉般的杀人机器。")
	await novel_interface.show_text_only("牛奶十分清楚，这种技术在军事上的意义……")
	novel_interface.show_character("milk_battle","shock")
	await novel_interface.show_dialog("——糟了。","牛奶")
	await novel_interface.hide_character() 
	await novel_interface.show_text_only("顺着牛奶的视线，白烛看向左侧的监视屏。")
	await novel_interface.show_text_only("几组监控画面显示，目前基地内除了刚才与小队交战过的那几个，还有至少两组敌人。")
	await novel_interface.show_text_only("一组是她们三分钟前刚甩掉的家伙，另一组有七八个人，正极快的从基地东翼向这边前进。")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("（照这个速度，最近的一组敌人三分种内就能察觉到我们的位置。）","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛的视线移向另一组画面，找到了刚刚与她们二人分兵的另外几个特遣队员模糊的影像。")
	await novel_interface.show_text_only("刚才手持防爆盾的队友一条小腿已经没了大半，正被另外二人架着向医务室前进。")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("（他们的弹药应该不多了…如果继续像这样沿东翼前进的话，五分钟内就会与另一组敌人遭遇。）","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("那个家伙……！","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶发现了其中一个小屏幕上的人影。")
	await novel_interface.show_text_only("刚刚那个动作最快的敌人，正漫不经心的拎着一名特遣队沾满血液的靴子。")
	await novel_interface.show_text_only("她似乎感受到了来自另一侧的注视，特意将脸朝向镜头，露出了一个瘆人的笑容。")
	novel_interface.show_character("milk_battle","solemn")
	await novel_interface.show_dialog("混账……可恶！！！","牛奶")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_break","normal",0.25)
	await novel_interface.show_dialog("冷静，冷静。","白烛")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛轻轻拍了拍牛奶的肩膀，然后抬起头快速扫视着房间内数十个监控画面。")
	await novel_interface.show_text_only("此时她正在脑海中展开基地的立体结构图，并与这些监控画面进行对比，试图规划一个最优方案。")
	await novel_interface.show_text_only("牛奶看着好友的神情，知道她又进入了那种出神的演算状态。")
	await novel_interface.show_text_only("但这一次，想找到理想的方案几乎不可能。")
	novel_interface.show_character("milk_battle","gratified")
	await novel_interface.show_dialog("嗯嗯，小白烛最厉害了……","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶的声音逐渐变小。")
	await novel_interface.show_text_only("她忽然注意到东翼的那组敌人正在对基地进行地毯式扫荡，却略过了一处合金门闸。")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("……","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶闭上眼睛思索片刻，然后下定决心。")
	await novel_interface.show_text_only("她快速的在键盘上输入了一串指令信息，并发送出去。")
	await novel_interface.show_text_only("十秒之内，亚洲某山区的地下军事数据中心，就会收到这条——")
	await novel_interface.show_text_only("并非呼叫支援，而是阐述死亡的讯息。")
	novel_interface.show_character("milk_battle","gratified")
	await novel_interface.show_dialog("（……抱歉。）","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶看着焦急思考中的白烛。")
	await novel_interface.show_text_only("黑发少女的身上，闪烁着淡淡的银色辉光。")
	await novel_interface.show_dialog("……小白烛~","牛奶")
	await novel_interface.show_dialog("还记得咱们最初相遇的时候吗？","牛奶")
	novel_interface.show_character("baizhu_break","shock")
	await novel_interface.show_dialog("嗯？","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛聚精会神地盯着屏幕，丝毫没注意到牛奶的动作。")
	await novel_interface.show_dialog("那时候，我当着你的面偷了一份研究报告……","牛奶")
	novel_interface.show_character("baizhu_break","smile")
	await novel_interface.show_dialog("怎么突然提起这个？","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你从没主动问过我为什么要那么做，又是为了谁在做这件事呢……","牛奶")
	await novel_interface.show_text_only("白烛察觉到有些不对劲，转过头来。")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("milk_aim","normal")
	await novel_interface.show_text_only("她的面前，是单手持枪对准自己的牛奶。")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("一直以来，你都是这样……","牛奶")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","normal")
	await novel_interface.show_dialog("……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛并未在意牛奶的异常举动。")
	await novel_interface.show_text_only("她瞥了一眼监控视频，接着推开牛奶的枪口。")
	novel_interface.show_character("baizhu_break","speechless")
	await novel_interface.show_dialog("别闹了，还有六十秒那群家伙就要找到咱们了。","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶自嘲似的笑笑。")
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("你看，就连这种时候，你都不会怀疑我……","牛奶")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","smile")
	await novel_interface.show_dialog("你又不会伤害我。","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛的话，让牛奶感到一丝被拆穿的狼狈。")
	await novel_interface.show_text_only("牛奶给手枪上膛，打开保险，绷紧的手指压住扳机后再次对准了白烛。")
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("退后。","牛奶")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("隐约中，白烛猜到了对方想要做些什么。")
	novel_interface.show_character("milk_aim","solemn")
	await novel_interface.show_dialog("——退后！！","牛奶")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛的背触到了监控室的后门。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling.png")
	await novel_interface.show_text_only("大门应声开启，露出一条倾斜的通道。")
	await novel_interface.show_text_only("白烛随着牛奶的动作后退着。")
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("还记得那个问题吗？","牛奶")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("不要闹了，牛奶……","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("milk_aim","gratified")
	await novel_interface.show_dialog("一辆失控火车的前方岔道口，左侧轨道上是你的队员们，右侧轨道上只有你自己。","牛奶")
	await novel_interface.show_dialog("你会选择救谁呢……","牛奶")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_break","angry")
	await novel_interface.show_dialog("——牛奶！！","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛意识到好友在刻意掩饰着悲伤。")
	novel_interface.show_character("milk_aim","mock")
	await novel_interface.show_dialog("我选择……救我喜欢的人——","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶忽然露出一个狡猾的笑容，向前猛冲，将白烛撞入了隧道墙壁上的暗门内。")
	await novel_interface.show_dialog("——？！！","白烛")
	await novel_interface.show_text_only("白烛来不及防备，顺着几阶楼梯跌下去——这是基地中仅有的两处有合金门闸保密仓库之一。")
	await novel_interface.show_text_only("而仓库的开闭，只能由外部控制。")
	novel_interface.show_character("milk_aim","mock")
	await novel_interface.show_dialog("——小~白~烛~","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("系统语音响起——\n“安全系统锁定，闸门即将关闭”")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Locking.png")
	await novel_interface.show_text_only("白烛面前，牛奶绽放出一个灿烂的笑容。\n而白烛眼前的视野正在迅速缩小。")
	await novel_interface.show_text_only("门闸开始合拢。")
	await novel_interface.show_dialog("“3——”","系统")
	await novel_interface.show_dialog("下个圣诞节，提前预约给我好不好~","牛奶")
	await novel_interface.show_dialog("“2——”","系统")
	await novel_interface.show_text_only("白烛想要伸手抓住牛奶，却看到牛奶笑嘻嘻地做了一个飞吻的动作。")
	await novel_interface.show_dialog("“1——”","系统")
	await novel_interface.show_text_only("白烛露出无法相信的表情。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Locking2.png")
	await novel_interface.show_text_only("一秒钟，仿佛被累加折叠出了无数爆裂的情绪浮现在少女脸上。")
	await novel_interface.show_dialog("笑一个啦——","牛奶")
	await novel_interface.show_text_only("对方的话音未落，白烛眼前的那道壁门，残忍而决绝地重合了起来。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("随后隧道内传来一声巨响，是白烛用力捶在墙壁上的声音。")
	await novel_interface.show_text_only("相隔着Ti-451型多重复合型合金板，少女的敲击声显得格外沉重——")
	
	print("=== 深海恐惧症篇第23话结束 ===")
	
	await novel_interface.end_story_episode(0.5)
