# bathophobia_ep27.gd - 深海恐惧症篇第27话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep27_script()

func play_script():
	pass

func bathophobia_ep27_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Laboratory.png")
	await novel_interface.show_text_only("白烛靠在我的肩头陷入了沉睡。")
	await novel_interface.show_text_only("海因里希缓缓走到破碎的培养槽前，将手浸在底部还未漏出的淡蓝色液体中。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("这是——","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("怎么？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("其中99%以上的成分是水，但最关键的……","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她绕到培养槽后仔细观察，顺着管线在房间昏暗的角落找到了一个小型机柜。")
	await novel_interface.show_text_only("在电气石的照耀下，包裹着机柜的灰绿色金属泛出一层淡蓝色的光晕。")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("那个材料——！","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("（那种金属……是之前存放贝阿特丽切魔导器的手提箱外壳所用的材料！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那是一种可以减弱或屏蔽精神和模因类『异质物』影响的合金，那么机柜里的东西……")
	await novel_interface.show_text_only("没等我阻止，炼金术士就打开了机柜，从中取出一支玻璃容器。")
	await novel_interface.show_text_only("里面的蓝色液体已经消耗了五分之一。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("是录像里的男人带走的东西——","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","perspire")
	await novel_interface.show_dialog("我没法感知这种材料……但那个女孩应该就是靠它修复和保持生命活性的。","海因里希")
	await novel_interface.show_dialog("机柜上的计时器显示，上次被打开是在十六万七千六百六十五小时四十八分钟之前。","海因里希")
	await novel_interface.show_dialog("这段时间里她完全没有衰老的迹象，真是……了不起的力量。","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希的眼神发光，声音有些激动。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("“没有衰老”的生物学解释……","拉斐尔")
	await novel_interface.show_dialog("能停止新陈代谢强行延长细胞寿命，或者是能补充端粒并让受损的细胞快速进入凋亡程序。","拉斐尔")
	await novel_interface.show_dialog("但是她在培养槽里是有呼吸的。","拉斐尔")
	novel_interface.change_expression("perspire")
	await novel_interface.show_dialog("这么说……","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Dispatched_Ship_Aisle.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("我们三人带着白烛一路回到基地入口，即使离开了梦境，我们也没看到录像中的尸体……")
	await novel_interface.show_text_only("早已在此等候的莉琉，二话不说的把我丟到航船上任由爱衣疯狂蹂躏。")
	await novel_interface.show_text_only("看到我湿哒哒的衣物，爱衣露出了微妙的表情，然后丢给我一条粉色白条的运动裤。")
	await novel_interface.show_text_only("之后的经历充满了我不愿回忆的马赛克……")
	await novel_interface.show_text_only("拉斐尔怀疑白烛的苏醒并非我们脱离梦境的原因\n爱衣拿着我换下的衣服表示会进一步研究~")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("（求求你不要研究了！！！！）","小怜")
	await novel_interface.show_dialog("（呜呜呜呜呜呜……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("做梦梦到拼命找厕所，然后被人猛击了腹部……")
	await novel_interface.show_text_only("那种情况下，谁都会醒过来吧……")
	await novel_interface.show_text_only("还在昏睡的白烛被送进了隔离医疗仓，安妮也一上飞机就睡着了，应该是精神太过疲劳了吧……")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("不过还是没找到对付甲烷泄露的方法……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("望着窗外冰层上巨大的裂口，我担心的自言自语\n着。")
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("——那倒不一定。","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔从后面走来，跟我一起望着窗外，嘴上还挂着神秘的微笑。")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("（她、她不会知道了什么在嘲笑我吧……）","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("咳咳~","拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔严肃了一下表情，一本正经的说。")
	novel_interface.show_character("ren_battle","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","normal2",0.25)
	await novel_interface.show_dialog("爷爷提出的利用抗寒性嗜甲烷菌的方案，有两个最大的问题——","拉斐尔")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯嗯~","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我乖巧的点头，虽然并没有听懂……")
	novel_interface.show_character("ren_battle","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","normal2",0.25)
	await novel_interface.show_dialog("最大的问题是古菌的基因很不稳定，在大规模培养时，分裂几十代就有很大概率变异失能。","拉斐尔")
	await novel_interface.show_dialog("虽然每十几分钟就会分裂一次，但变异的细菌依然可以分裂，之后会以几何级数的速度污染样本。","拉斐尔")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("以现在的技术很难分辨和去除变异的菌株，这才是它难以培育的最主要原因。","拉斐尔")
	await novel_interface.show_dialog("不过“那种东西”既然可以让人类在那么长的时间里都没有出现衰老的迹象……","拉斐尔")
	await novel_interface.show_dialog("很可能是从细胞层面解决这个问题的关键突破口。","拉斐尔")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("好、好像很厉害……\n如果可行话，问题可以解决了？","小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("还有一个问题，就是那种厌氧菌只有在泄露点附近才能存活。","拉斐尔")
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("如果用生物气溶胶在大气中进行空中散播，恐怕还没落地就死光了……","拉斐尔")
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("需要一种可以快速封闭隔绝氧气，又能在寒冷环境下自动降解的物质来承载……","拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣捏了我一下，朝我使了个眼色。")
	novel_interface.show_character("ren_battle","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯……用气凝胶？","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("之前在天空酒店，安妮用那种东西封过这位大小姐的房门，不过被雅各那伙人用液氮破解了。")
	novel_interface.show_character("ren_battle","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("倒是个有趣的方案……你还挺机灵的嘛~","拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她刚才，好像难得的夸奖了我一下！")
	novel_interface.show_character("ren_battle","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","stare",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（我是不是听错了……）","小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("不过，你怎么穿着运动裤，尿床了？","拉斐尔")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("没、没、不是，绝对不是——！！","小怜")
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/Baizhu/snowfield.png")
	await novel_interface.show_text_only("麦克默多站的极地实验室中，存放着从深层冰川之下淤泥中取得的抗寒性嗜甲烷菌种。")
	await novel_interface.show_text_only("虽然原始样本数量很少，但爱衣配合那种蓝色液体成功的在几小时内培养出了足够的活性菌株。")
	await novel_interface.show_text_only("航船从南极上空飞过时，我注意到数量庞大的各国无人机正协力在裂缝的上空进行着作业。")
	await novel_interface.show_text_only("胶网结构的改良型气溶胶内部封存着高浓度活性嗜甲烷菌，像无数细小的冰晶一样散落在泄露点。")
	await novel_interface.show_text_only("地震的12小时后，南极各监测站的数据表明，空气中的甲烷含量已经得到控制。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("之后，莉琉向联合议会申请了一笔天文数字的维护费，由六大学园都市共同支付……")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("海因里希坐在指挥室内，而莉琉则站在大屏幕前看着上面的资料。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("海因里希·昆哈特……","莉琉")
	await novel_interface.show_dialog("一出现，就把我的人卷入了相位波动空间呢。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("初次见面~","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希平静的微笑着。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("虽然之前说过话，但正式见面还是第一次。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("这里看起来不像审讯室，我该为此表示感谢吗？","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉没有理会挑衅，盯着海因里希的履历。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("十岁进入莱比锡大学，十四岁成为炼金术士。","莉琉")
	await novel_interface.show_dialog("后来在巴塞尔大学，只用了四个月就获得医学博士学位。","莉琉")
	await novel_interface.show_dialog("记录的死亡时间是1605年，死因是实验室爆炸…\n…","莉琉")
	await novel_interface.show_dialog("有文献记载在爆炸发生前，一家荷兰注册的公司给了附近的居民一大笔钱并要求他们搬家。","莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("从当时巡查官的日记看来，爆炸物的烈度可能超过了两百多年后发明的甘油炸药。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("呵呵呵，那只是我脱离『那位』控制的手段罢了。","海因里希")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("不过那些炼金术士用了两百多年才追上我吗？","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希有些嘲讽的说道。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("两百多年后，炼金术士已经被称做“化学家”了。","莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("后来的炸药没有使用魔法刻印，普通人也能规模生产，是门很赚钱的生意~","莉琉")
	await novel_interface.show_dialog("虽然偶尔还是会炸死个亲戚什么的……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希心领神会的笑了笑。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("你唯一留下的字迹是《永恒智慧的露天剧场》的手稿，现被收藏于纽摩利达斯市立博物馆。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("当时花了我不少功夫呢，有机会去看看~","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("个人收藏以宝石为主，现留存于世的，只有代表自然元素的五件藏品，青金石柱是最重要的收藏……","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("那个被小怜摔碎的？其实一点也不重要~","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("——你留下的信息实在有限，以至于在行动前我们将你的性别都推断错了。","莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("有些难辨真伪的民间资料是你带着拉斐尔和小怜她们消失之后，由萨蒙顿追查出来的。","莉琉")
	await novel_interface.show_dialog("如果一开始就将这些信息纳入可信材料，我们无论如何也不会选择青金石柱进行实验。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("那么看来，我和主人的相遇是命中注定啊……","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女慵懒的伸了个懒腰。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("我好奇的是，在小怜的录音和你的描述中，都提到了『生命之树』是一种封印——","莉琉")
	await novel_interface.show_dialog("封印着让你所说的『那位』也感到恐惧的东西。","莉琉")
	await novel_interface.show_dialog("根据白烛的口供，那个东西——至少其中之一，是存在于深海中的巨大眼球状生物……","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("……","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("我可以不问『那位』是谁，也无需知道那个眼球是什么，那些东西可能比人类的历史要久远得多。","莉琉")
	await novel_interface.show_dialog("我现在只能以对待物理定律的方式，将它们的存在作为既定条件。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("很有智慧的判断……那么你想知道的是？","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("我想知道是——什么造成了封印的不稳定。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希看着莉琉坚定的眼神，这确实是一位务实的战略家能提出最合适的问题。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("关于这个……","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女伸出右手，随着图腾转动的光芒，一枚碧蓝色的宝石出现在她的手心。")
	await novel_interface.show_text_only("宝石中心，液体一样流动的物质包裹着一颗眼球形状的虚影。")
	await novel_interface.show_text_only("这颗被宝石封存的眼球投影，此时瞳孔正缩小并在不规则的抖动，正如人类进入深度睡眠时的状态。")
	await novel_interface.show_text_only("唯有枝杈状神经末梢还在宝石内部的液状物质中微微飘动，呈现着一股诡异的平静感。")
	novel_interface.show_character("heinrich_battle","bored")
	await novel_interface.show_dialog("虽然我也不知道“它”是什么。","海因里希")
	novel_interface.character_dark()
	await novel_interface.show_text_only("海因里希出神的盯着那只眼睛。")
	novel_interface.character_light(0.35,"serious")
	await novel_interface.show_dialog("但重要的是，原本一直在其体内抑制它的什么东西不见了……","海因里希")
	await novel_interface.show_dialog("否则，你认为人类用探针扎了这种东西之后的生还率会有多高？","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("……必死无疑。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希点点头，抛起宝石。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("第九原质是代表生命的『基础』，可能正是它修复生命体的能力，一直维持着那个小姑娘的状态。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("但这种状态已经稳定的维持了19年，为什么……","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("那个基地最有价值的数据，你都搜刮回来了吧~","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("你是说，培养槽的数据？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉操作手持设备，从庞杂的资料库中调出了白烛身体监测数据的时间轴。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("那里，七十多天前——","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("那个时间点出现了一次波动，然后越来越强烈……","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("或许七十多天前由于某些原因，让“那个东西”无法继续维持稳定了……","海因里希")
	await novel_interface.show_dialog("它通过那种蓝色液体与白烛产生了共鸣，生成能影响人类的梦境。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("或者完全相反——白烛在七十多天前由于某种原因无法再保持稳定，然后影响到那个眼球……","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("总之，是一个让双方都越来越难以稳定的叠加态\n而且是不久前才出现的。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("这与我们的推测一致……这些年来白皇后基地应该一直都是有人运作的。","莉琉")
	await novel_interface.show_dialog("但在战后，原来的机构似乎仅仅能进行最低限度的维护，并在极夜期间会将全部人员撤走。","莉琉")
	await novel_interface.show_dialog("那个机构很注重保密性，注册的公司向上追查全是空壳，运作资金也完全通过加密授信。","莉琉")
	await novel_interface.show_dialog("他们每年都会清除影像资料，如果不是因为在梦境中，你们在监控室应该什么都看不到。","莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("（但那块手表……）","莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("……等等。","莉琉")
	await novel_interface.show_dialog("七十多天前——","莉琉")
	await novel_interface.show_dialog("（不就是洛斯金杯消失的那时吗……）","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希摊了摊手。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("不清楚，那时我还没“醒来”。","海因里希")
	await novel_interface.show_dialog("而且，正如你刚才所说——","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("？","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("如果一开始你们就掌握了全部材料，肯定不会选择青金石，那么我也不会将她们带去南极了对吧？","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("……没错。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("但如果不是我们及时赶到南极，阻止了梦境范围进一步扩散的话……","海因里希")
	await novel_interface.show_dialog("Boom——！","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希做了个爆炸的手势，然后露出一个神秘的微笑。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("虽然我并不清楚之前的事情……","海因里希")
	await novel_interface.show_dialog("但你真的认为，你们只是碰巧选择了青金石柱吗？","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("你是说想，这也是『那位』的意志吗？","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("我原本也以为小怜之所以会被卷入因果之隙，是因为『那位』对她感兴趣。","海因里希")
	await novel_interface.show_dialog("或者想让小怜成为它的另一个奴役对象……","海因里希")
	await novel_interface.show_dialog("但是，她竟可以凭自己的意志扭曲因果之隙。","海因里希")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("这么看来，『那位』根本不够资格来命令小怜。","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希的声音有些兴奋。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("这一点，我倒不意外。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着对方有些惊讶的表情，莉琉接着拿出一份文件放在她面前。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("名义上，青金石柱是萨蒙顿提供的，那里也更接近你的出生地，而且你的存在也被萨蒙顿所知……","莉琉")
	await novel_interface.show_dialog("所以由于政治和外交方面的原因，我不能要求你留在这里。","莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("不过，如果你想了解真相的话，我倒是有个建议。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("哦？看来你也像『那位』一样，非常擅长奴役他人呢……","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("当然——","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉露出一个灿烂的笑容。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("但我可不会强迫你签订契约~","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她一边说着，一边用手指在文件上要求“签名”的地方敲了敲。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("在这里签字，你就能以拉斐尔随行人员的身份留在新丰洲，这样两国都可以接受。","莉琉")
	await novel_interface.show_dialog("而且——","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着海因里希怀疑的目光，莉琉取出一个试管样子的密封容器。")
	await novel_interface.show_text_only("随着她的动作，试管内的蓝色液体缓缓展出一个透明的轮廓。")
	await novel_interface.show_text_only("仿佛粘液一样的存在，凸出一个拇指大小的球形结构。")
	await novel_interface.show_text_only("——就像眼球一般。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("那是……？","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("对这个生物感兴趣吗？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉打开签字笔，微笑着递给了金发少女。")
	
	print("=== 深渊恐惧症篇第27话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
