# bathophobia_ep03.gd - 深海恐惧篇第3话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep03_script()

func play_script():
	pass

func bathophobia_ep03_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("莉琉走近盯着荧幕的爱衣，俯身看向桌面的显示屏上不断刷新的数据。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("这就是贝阿特丽切的检查报告吗？", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	await novel_interface.show_dialog("哈——很棒的样本！", "爱衣")
	novel_interface.change_2nd_expression("wink")
	await novel_interface.show_dialog("而且如果结合历史文献推演的话，就更有趣了。", "爱衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("目前掌握的所有数据库都没有她的资料，但是战时数据库确实存在断层。", "莉琉")
	await novel_interface.show_dialog("不过根据她的口述记录和你报告的资料看来……", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉在屏幕中调出贝阿特丽切的档案。")
	novel_interface.show_character("liliu_research","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","wink",0.25)
	await novel_interface.show_dialog("二十四岁……\n真是充满了活力的年龄呢~", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉和爱衣对视一眼，确认对方也注意到了相同的地方，二人视线又落回到屏幕。")
	novel_interface.show_character("liliu_research","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ai","wink",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这是发现她的当晚检测的结果？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal")
	await novel_interface.show_dialog("体内放射性元素几乎为零，不过血液中重金属的含量略高。", "爱衣")
	await novel_interface.show_dialog("可能是由于当年的饮食器皿或者中世纪的原始化妆品……", "爱衣")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("看来你已经有先入为主的判断了？", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("毕竟在她的自述文件中——", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣划过面前荧幕中的一条记录。")
	await novel_interface.show_text_only("“GMT+9 13:09:11\n目标自称生于公元1265年。”")
	novel_interface.show_character("liliu_research","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("——我还是第一次见到，来自过去的活体样本呢。", "爱衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("有没有可能是和安妮一样的情况？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("不一样哦~\n贝阿特丽切在自述中十分确定自己的死亡。", "爱衣")
	novel_interface.change_2nd_expression("think")
	await novel_interface.show_dialog("按照她的说法，导致她死亡的是一杯毒酒，而且是她自己选择喝下的。", "爱衣")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("虽然史料中也有类似的记录……但不能排除被篡改的可能性。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣调出了另一份检测报告。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("中世纪的欧洲有记录的毒剂种类不多——毒堇，颠茄，番木鳖……", "爱衣")
	await novel_interface.show_dialog("在发现她当晚抽取的血样中，确实能测出毒性生物碱的残留。", "爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("但第二天再次检验的时候，她血液中的生物碱和重金属残留就几乎消失了。", "爱衣")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("怪不得你这么激动……", "莉琉")
	novel_interface.character_light(0.35,"dizzy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不不不，这还不是最关键的！", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣的声音兴奋得有些颤抖。")
	novel_interface.show_character("ai","dizzy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("与安妮不同，贝阿特丽切的免疫特征完全就像新生儿一样，血清免疫球蛋白D的检测呈阴性。", "爱衣")
	await novel_interface.show_dialog("而且……她体内的菌群特征与小怜高度一致！！", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("……你到底是怎么想到检测这些项目的？", "莉琉")
	novel_interface.character_light(0.35,"blush_dizzy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("直觉！本能！和对异常样本的爱！！", "爱衣")
	await novel_interface.show_dialog("能够从虚无中瞬间构建出肉体……还精确的保留了那个最有趣的会吸引异性的“诅咒”。", "爱衣")
	await novel_interface.show_dialog("小怜真是……太棒了！！", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("说着，爱衣紧闭双眼，双手交叉抱住自己，露出一幅陶醉的神情。")
	await novel_interface.show_text_only("莉琉不知从哪抽出一卷报告书，毫不留情的敲在她的脑袋上。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("如果灵魂可以独立存在于异次元空间中的话……", "莉琉")
	await novel_interface.show_dialog("是依据什么来选择，塑成灵魂的容器的呢？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush")
	await novel_interface.show_dialog("是因为那个“黄金蝴蝶”吗？", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("不，如果类比安妮的球棒，应该是和那块绿色宝石有关……", "莉琉")
	await novel_interface.show_dialog("通过某种特定物品，“召唤”出与之相关的灵魂。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("涉及到时空转换、物质再造……", "莉琉")
	await novel_interface.show_dialog("（绝对不能让元老院知道这件事。）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("还能做到灵魂吸引啊……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣打断了莉琉的思考。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("嗯？", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("从虚空中带回既定之人的灵魂，并为其塑造灵魂的容器……听上去很像炼金术中禁忌的秘法呀。", "爱衣")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("如果不是生在这个时代，我恐怕会像那些炼金术士一样，尝试用元素和神做灵魂的交易了。", "爱衣")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("听上去挺像那些街头宗教宣扬的“神之子”，不过那些玩意在新丰洲没什么市场。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"blush_think")
	await novel_interface.show_dialog("唔，我倒是比较喜欢“圣女”之类的称呼，听上去就有种令人想要侵犯的禁欲感呢。", "爱衣")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("唉——我怎么会有你这样的手下……", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"blush")
	await novel_interface.show_dialog("嗯哼~也算是某种意义上的“灵魂吸引”吧~", "爱衣")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_heathRoom.png")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("——所以，就是这样。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("哈啊！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("保健室内刚刚结束例行身体检查的我，一边穿衣服一边和爱衣聊到贝阿特丽切的情况。")
	await novel_interface.show_text_only("如果对她身体状况的描述还算正常的话……")
	await novel_interface.show_text_only("关于“灵魂”的那套说辞，听起来完全就像是忽悠人的。")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("（还有“圣女”什么的……）\n（虽然我曾经在游戏里攻略过这样的类型）", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（但我才不想自己会被如此称呼啊！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我不禁抱紧自己打了个冷颤。")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("不、不要！！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("哦呀呀，你在想什么羞羞的事情啊~？", "爱衣")
	novel_interface.character_light(0.35,"bored")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所以……这就是最近检查项目增加的原因吗？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("嗯~是呢。", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣在不怀好意的坏笑，似乎在思考着什么。")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("（是她擅自增加的项目也说不定……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("可惜配套物资不是很到位，有些更加“有趣”的检查暂时没法进行……", "爱衣")
	novel_interface.change_expression("blush_wink")
	await novel_interface.show_dialog("对了，要不要试试看给你植入芯片的最大功率模式呀？", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("不，不要！！！", "小怜")

	print("=== 深海恐惧篇第3话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
