# bathophobia_ep29.gd - 深海恐惧症篇第29话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep29_script()

func play_script():
	pass

func bathophobia_ep29_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Baizhu_Sickroom_Evening.png")
	await novel_interface.show_text_only("护士敲了敲门。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("嗯？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("白烛小姐的理疗时间到了，抱歉。","护士")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("啊，都这么晚了吗？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("护士抱歉的笑了笑。")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("那我们明天再来看——","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("话没说完，我的胸口震动了两次。")
	await novel_interface.show_text_only("对哦，差点忘了，莉琉一定不会允许的吧……")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("（就连这次探望，也是我申请了很久才允许的。）","小怜")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("那……我们就先回去了？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("嗯，路上小心。","白烛")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("简单告别之后，我推着有些依依不舍的拉斐尔和安妮一起离开病房。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("啊，忘了一件事！","小怜")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Baizhu_Sickroom_Evening.png")
	await novel_interface.show_text_only("我抱歉地朝着走廊上的两人挥了挥手，又一个人走回白烛的房间。")
	novel_interface.show_character("baizhu_normal","shock")
	await novel_interface.show_dialog("怎么回来了？","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("嗯…嗯……\n（有些害羞呢……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我做了个深呼吸，鼓足勇气上前——")
	await novel_interface.show_text_only("直接拉过白烛的手，我掏出细管有色润唇膏，在白烛的手上写下了一串数字。")
	novel_interface.show_character("ren_battle","shy_left")
	await novel_interface.show_dialog("这是我的通讯号码，愿意的话，可以……\n可以联系我！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("呜哇啊——！！！\n超羞耻的！！！")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("……咳。","小怜")
	await novel_interface.show_dialog("（不过仔细想想，不管是随身携带着有色润唇膏）\n（还是在女孩子的手心写字，都很奇怪啊……）","小怜")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("我没别的意思，就是……","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("baizhu_normal","shock")
	await novel_interface.show_dialog("……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛的表情有些惊讶。")
	await novel_interface.show_text_only("当然会惊讶了吧！\n我刚才的举动好像有点太蠢了！")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("（早知道不回来了……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("明明是去年街头调查男性向浪漫幻想的十大名场面之一……")
	await novel_interface.show_text_only("等等，仔细回想的话那个场面应该是“住院时被探病的美少女在自己手心写下通讯号码”……")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("（好像搞错了什么……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我握着被自己涂上一串号码的白烛的手，有些不知所措。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("啊啊——这个……\n弄脏了……对不起！","小怜")
	await novel_interface.show_dialog("我帮你擦掉吧！！\n（然后就当什么都没有发生过！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我连忙用手蹭掉自己刚写下的数字。")
	novel_interface.show_character("baizhu_normal","shock")
	await novel_interface.show_dialog("……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我是不是吓到她了……")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("虽然有些冒犯，但是……\n小怜是男孩子吗？","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("诶？！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("怎怎怎怎怎怎怎么发现的？！！")
	await novel_interface.show_text_only("我吓得拿纸巾的动作都僵硬了，连抽了三张出来。")
	await novel_interface.show_text_only("莉琉特意警告过我，绝对不能透露自己的信息，否则就……")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("不知道，直觉吧……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("白烛顿了顿，接着又补了一刀——")
	novel_interface.show_character("baizhu_normal","smile")
	await novel_interface.show_dialog("会做出这种傻傻的事情，总觉得像是那种笨手笨脚的男孩子……","白烛")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("哈、哈哈……\n大概我属于比较粗神经的那种类型。","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("好不容易擦干净了白烛的手，我三步并作两步，赶忙朝着病房门口逃走。")
	await novel_interface.show_dialog("小怜——","白烛")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("怎、怎么了？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我僵硬的渐渐转回头，希望能晚点接受处刑。")
	await novel_interface.show_text_only("不会真的被看穿了吧？")
	await novel_interface.show_text_only("出乎意料的，白烛对我露出了开心的笑容。")
	novel_interface.show_character("ren_battle","sob")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_normal","mock",0.25)
	await novel_interface.show_dialog("你的号码，我记住了哦~","白烛")
	novel_interface.character_light(0.35,"timid")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊……","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我愣在那里，有些不知所措。")
	novel_interface.show_character("ren_battle","timid")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	await novel_interface.show_dialog("还有……","白烛")
	await novel_interface.show_dialog("醒来后，我拜托莉琉帮我调查过一些事情。","白烛")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("少女的笑容突然变得暗淡。")
	novel_interface.show_character("ren_battle","timid")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("baizhu_normal","sad",0.25)
	await novel_interface.show_dialog("虽然我不太愿意相信，但或许父亲一直以来…… 都向我隐瞒了很多事。","白烛")
	await novel_interface.show_dialog("如果是你的话……会怎么办呢？","白烛")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("这——位——小——姐——","护士")
	await novel_interface.show_text_only("护士姐姐很明显在催促我离去了。")
	novel_interface.show_character("anne_normal","happy")
	await novel_interface.show_dialog("该走了啦小怜~","安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮从门口探出头。")
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("啊，就来就来！","小怜")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("那个，你刚说……","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	await novel_interface.show_dialog("嗯，没事啦，就当我什么都没说~","白烛")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（怎么可能……）","小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("你快回去吧！\n对了，谢谢你送的抱枕，我很喜欢~","白烛")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯……","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛的身体，看上去还是有些虚弱。")
	novel_interface.show_character("ren_battle","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	await novel_interface.show_dialog("放心啦，我会联系你的。","白烛")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("白烛又朝我摆了摆手。")
	novel_interface.show_character("ren_battle","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("baizhu_normal","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哦、哦……那我先走啦~！","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("那几个吵吵嚷嚷的家伙离开之后，白烛出神地盯着自己的手。")
	await novel_interface.show_text_only("那里还留有一丝刚才被人握住写字的感觉。")
	await novel_interface.show_text_only("感受着掌心传来的温度，白烛微微笑了起来。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Baizhu_Cabin.png")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("机舱内。")
	await novel_interface.show_text_only("飞机正缓慢的在跑道上滑行，为离开南美洲的飞行做着最后的准备。")
	await novel_interface.show_text_only("白烛望向窗外，听着耳机中那个熟悉的声音。")
	await novel_interface.show_text_only("她被莉琉告知了白皇后基地曾经发生过的事，以及小怜和海因里希对监控录像的口述。")
	await novel_interface.show_text_only("面对着与自己记忆相差十九年，已经被战争和异质物所改造面目全非的世界，少女有些不知所措。")
	await novel_interface.show_text_only("如果说有什么能让她安心的东西……")
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	await novel_interface.show_dialog("“小~白~烛~”","Record牛奶")
	novel_interface.show_character("baizhu_normal","mock")
	await novel_interface.show_text_only("少女勾起嘴角，握紧了手中的播放器。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("SID的探员在恢复了牛奶手表内的数据后，将录音和部分信息复制到一台播放器上并交付给白白烛。")
	await novel_interface.show_text_only("此刻，她正反复听着牛奶出发前录下的那段语音。")
	await novel_interface.show_dialog("还有四个月就圣诞节了，有没有想好准备送给我的礼物呢？","Record牛奶")
	await novel_interface.show_dialog("嘿嘿，这么早就开始考虑礼物的事情，好像有点坏心眼啊……","Record牛奶")
	await novel_interface.show_dialog("不过，我真的超期待！","Record牛奶")
	await novel_interface.show_dialog("……真是奇怪，明明只相处了一年，却感觉和你认识了几个世纪一样。","Record牛奶")
	await novel_interface.show_dialog("你肯定又会害羞的说，太夸张了吧。","Record牛奶")
	await novel_interface.show_dialog("毕竟在我面前，小白烛是完全没有秘密的嘛！","Record牛奶")
	await novel_interface.show_dialog("嗯……还记得我们第一次相遇的时候，你告诉我那个教授的保险箱密码，是一组亲和数。","Record牛奶")
	await novel_interface.show_dialog("220，284，我到现在都还记得。","Record牛奶")
	await novel_interface.show_dialog("那是我第一次了解到这种密码构成方式呢~","Record牛奶")
	await novel_interface.show_dialog("不过话说你也太无所谓了吧！","Record牛奶")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Baizhu_Cafe.png")
	await novel_interface.show_dialog("明明看出我是伪装身份的调查员，居然还这么轻易的暴露了教授的秘密！","Record牛奶")
	await novel_interface.show_dialog("甚至在那之后……\n我请你喝咖啡，你都没有拒绝！！","Record牛奶")
	await novel_interface.show_dialog("一般人肯定会拒绝的吧？","Record牛奶")
	await novel_interface.show_dialog("……","Record牛奶")
	await novel_interface.show_dialog("不过呢，这也是你与众不同的地方。","Record牛奶")
	await novel_interface.show_dialog("或者说，是我们的常态……","Record牛奶")
	await novel_interface.show_dialog("有什么不好呢？","Record牛奶")
	await novel_interface.show_dialog("有时候，我甚至会觉得，也许我们的相逢是命中注定。","Record牛奶")
	await novel_interface.show_dialog("你和我……就像是灵魂的亲和数一样……哎哎哎太肉麻了！删掉删掉！重来！！","Record牛奶")
	await novel_interface.show_dialog("小白烛……","Record牛奶")
	await novel_interface.show_dialog("抱歉，我啊，当时，利用过你……","Record牛奶")
	await novel_interface.show_dialog("所以，如果你愿意利用我一次的话，那我们就扯平了！","Record牛奶")
	await novel_interface.show_dialog("今年的圣诞节，不知会在哪里过呢……","Record牛奶")
	await novel_interface.show_dialog("反正任务结束后肯定又是半年多的封闭训练吧……","Record牛奶")
	await novel_interface.show_dialog("哎，讨厌~Boss完全不给人放假嘛！","Record牛奶")
	await novel_interface.show_dialog("不过我有预感！明年的圣诞节——","Record牛奶")
	await novel_interface.show_dialog("嘛……小白烛大可以擅自期待一番哦！","Record牛奶")
	await novel_interface.show_dialog("话说，我这录的是什么啊……","Record牛奶")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("好友的声音戛然而止。")
	await novel_interface.show_text_only("白烛按下了Replay。\n耳机中再度传来了熟悉的声音。")
	await novel_interface.show_dialog("“小~白~烛~”","Record牛奶")
	await novel_interface.show_text_only("……")
	novel_interface.show_character("baizhu_normal","cry")
	await novel_interface.show_text_only("少女眼角含泪，低声笑了出来。")
	novel_interface.change_expression("tear")
	await novel_interface.show_dialog("笨蛋。","白烛")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Sonar.mp3")
	await novel_interface.show_text_only("『灵魂』是什么？")
	await novel_interface.show_text_only("是记录着意识的某种能量，还是无法观测的量子态的存在？")
	await novel_interface.show_text_only("或许『灵魂』仅仅是一种概念。")
	await novel_interface.show_text_only("就像物理学中『时间』的概念一样——")
	await novel_interface.show_text_only("只是一种幻觉……一场梦。")
	await novel_interface.show_text_only("唯一的问题是——")
	novel_interface.show_background("res://assets/images/bg/Baizhu/Baizhu_Niunai.png")
	await novel_interface.show_text_only("做梦的人是谁？")
	
	print("=== 潜渊症篇第29话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
