# bathophobia_ep01.gd - 深海恐惧症篇第1话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep01_script()

func play_script():
	pass

func bathophobia_ep01_script():
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	await novel_interface.show_text_only("封闭的会议室内，单方面的报告正在进行。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("……以上，是关于萨蒙顿考察团成员受到袭击事件的后续调查。", "莉琉")
	await novel_interface.show_dialog("拉斐尔·戴克斯由于“个人原因”，于上周再次来访了新丰洲。", "莉琉")
	await novel_interface.show_dialog("SID现已将其设为A类监控保护对象。", "莉琉")
	await novel_interface.show_dialog("和上次不同，这回萨蒙顿向外交部提交了非常详细的随行人员档案和物品申报清单。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("连陪同的安保人员曾经参与的军事行动都如实报告了，合规工作如此完备……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("就像在声明：如果戴克斯博士的宝贝孙女在新丰洲出了什么状况，就全都是我们的责任。", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("哼！那个老狐狸——", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("不过作为保护好那位大小姐的条件，他们承诺对新丰洲优先交割20%的农产品采购合约。", "华音泷")
	await novel_interface.show_dialog("从NBOT的行情看来……这笔交易十分划算。", "华音泷")
	await novel_interface.show_dialog("我已经签署禁止令，暂时不会有媒体骚扰那位大小姐了。", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("（打算借用元老院在市场上做价吗？）\n（而且还料到我不会插手……）", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("（哼哼，果然是个老狐狸～）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("既然那个小丫头这么重要，能不能从她身上再榨取一些情报呢？", "布莱特")
	await novel_interface.show_dialog("我们科学院对萨蒙顿的基因编辑技术和超级温室系统一直很感兴趣。", "布莱特")
	await novel_interface.show_dialog("如果能让她来我的实验室呆上几个小时……", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","speak")
	await novel_interface.show_dialog("布莱特博士——", "莉琉")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("您对精神类异质物“独特”的道德标准，早就名声在外了。", "莉琉")
	await novel_interface.show_dialog("恐怕那位大小姐一踏进您的实验室，萨蒙顿立刻就会宣布对新丰洲的贸易制裁吧。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("我有这么出名吗？\n啊哈哈哈哈——", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("咳咳，这个话题到此为止！", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("说起来，在天空酒店出现的那伙不明身份的武装分子……", "基尔斯")
	await novel_interface.show_dialog("他们袭击了萨蒙顿考察团并夺走了贵重的艺术品。", "基尔斯")
	await novel_interface.show_dialog("对此SID有什么发现吗？", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("（老狐狸对元老院隐瞒了黄金蝴蝶的事情，还把帐算到了雅各那伙人头上。）", "莉琉")
	await novel_interface.show_dialog("（他们在行动前瘫痪了酒店监控）\n（正好利用这个信息差……）", "莉琉")
	await novel_interface.show_dialog("『协约非武装区』不是SID的管辖范围，目前结合各方面情报，推测那伙人使用了特殊武器。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("特殊武器……是异质物武器吗？\n还是在埃癸斯的防护范围内？！", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("根据酒店房间地板上的树状灼烧痕迹，推测是大功率的串联谐振放电设备。", "莉琉")
	await novel_interface.show_dialog("将这种设备小型化，达到单兵可携带的程度，不是常规的技术可以做到的。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("根据考察团的口供，当晚那伙人约有十人，且全员都装备了一样的武器。", "莉琉")
	await novel_interface.show_dialog("埃癸斯的记录显示，事发当夜有10个左右的不明编号几乎同时离线，应该已经撤离了。", "莉琉")
	await novel_interface.show_dialog("SID控制了所有正常离境通道，这些人可能是通过外交通道逃走的。", "莉琉")
	await novel_interface.show_dialog("（或者因为行动失败被就地处决了……）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("……我明白了。", "基尔斯")
	await novel_interface.show_dialog("如果能这样规模化装备，倒不像是异质物武器。", "基尔斯")
	await novel_interface.show_dialog("不过，在监控录像被瘫痪之前，有两个可疑人物在楼道里袭击了保安。", "基尔斯")
	await novel_interface.show_dialog("一个穿着酒店的女仆服装，还有一个穿着御樱川的校服，是不是你派出的……", "基尔斯")
	novel_interface.character_dark()
	await novel_interface.show_text_only("屏幕中传来了尖锐的电子噪音。")
	novel_interface.character_light()
	await novel_interface.show_dialog("——？", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("哈哈哈哈，原来首席执政大人也和我一样，对小猫咪很感兴趣呢～", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("……小猫咪？", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("啊，这是援引莉琉阁下的说法——", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("（果然，这家伙……）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("那两位是叫安妮和怜吧？\n真是可爱的名字啊～", "#C")
	await novel_interface.show_dialog("或许御樱川还养着其他的猫也不一定——", "#C")
	await novel_interface.show_dialog("您说呢，莉琉阁下？", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("呵呵呵，看来她们俩的资料没有被泄露给保安军真是要感谢元老院了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("哪里哪里，您太客气了——\n看来莉琉阁下也没打算向我们隐瞒。", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("那么我在此补充一下简报信息。", "莉琉")
	await novel_interface.show_dialog("由于卫星检测到天空酒店的异常相位波动，但SID不便直接行动。", "莉琉")
	await novel_interface.show_dialog("所以我派遣了两名卧底探员前去调查。", "莉琉")
	await novel_interface.show_dialog("但在行动中遭遇了那群武装分子，其中一名叫安妮的探员还被那种武器击中。", "莉琉")
	await novel_interface.show_dialog("经过抢救她的情况已经稳定，而且我们采集到了那种武器的一些数据。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("……你刚才为什么没说？", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("首席执政大人，您刚才不也说萨蒙顿考察团遗失的只是“艺术品”吗？", "莉琉")
	await novel_interface.show_dialog("或许更充分的分享情报，对我们都更有利。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("您说是吗？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("……", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("那么莉琉阁下是想跟我们分享一下，您亲自收养的那只小猫咪吗？", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("（哼，没有被我抛出去的信息误导）", "莉琉")
	await novel_interface.show_dialog("（果然是个讨厌的家伙……）\n（只能赌一赌那套伪造的背景资料够不够完美了）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("莉琉阁下，您打算如何解释呢？", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("『七年战争』期间，一直有人试图用发展依靠人体也能发动『神迹』的技术。", "莉琉")
	await novel_interface.show_dialog("各种对作战人员秘密进行人体改造实验的传闻，相信各位都有所耳闻。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("……嗯。", "基尔斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉勾起嘴角，轻笑了一声。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("确实有些人生来就拥有特殊的天赋，这方面新丰洲科学院和播磨脑研也有记录。", "莉琉")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("如果实在要算的话，布莱特博士也是其中一员吧。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("我的状况不一样，有超能力记录的基本都是女性…", "布莱特")
	await novel_interface.show_dialog("不过像这样拥有特殊天賦的人，通常只会列入观察名单，并没必要特殊控制吧。", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("确实，但目前所有超能力者档案中，连可以达到B级异质物能力的人都没有。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("而且由于效果不稳定，战争中此类研究基本都被终止了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_taki")
	await novel_interface.show_dialog("也有人称这些拥有超能力的女性为“魔女”，放在几十年前可能会有人会大惊小怪吧……", "华音泷")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("不过这位名为“怜”的少女的特殊之处，是她拥有可以穿越相位波动空间的能力。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("——！！！","众人")

	print("=== 深海恐惧症篇第1话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
