# bathophobia_ep24.gd - 深海恐惧症篇第24话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep24_script()

func play_script():
	pass

func bathophobia_ep24_script():
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Control_Room.png")
	await novel_interface.show_text_only("牛奶回到监控室，用椅子将大门死死卡住。")
	await novel_interface.show_text_only("最近一组敌人还有几十秒就会抵达这里，而东翼的队友也会在两三分钟内与另一组敌人遭遇。")
	novel_interface.show_character("milk_battle","gratified")
	await novel_interface.show_dialog("是啊，我早该想到的……","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("如果我有一群行动力惊人、听觉异常敏锐、还有超强回复能力的士兵的话——")
	await novel_interface.show_text_only("为什么只给她们配备冷兵器呢？")
	await novel_interface.show_text_only("需要团队行动，只能以超强的个体战斗力弥补战术上的低效。")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("那些东西，早就不能称之为『人』了啊……","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("牛奶看了看主控台左侧的一排控制器，上面是白烛刚刚留在那里的样本箱。")
	novel_interface.show_character("milk_battle","normal")
	await novel_interface.show_dialog("现在任务已经不重要了……","牛奶")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("这里的攻击性防御策略还是挺全面的嘛~","牛奶")
	await novel_interface.show_dialog("希望那个扩音器还能用吧。","牛奶")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女深吸了一口气后下定了决心，在控制器前输入一连串指令……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Storehouse.png")
	await novel_interface.show_text_only("昏暗的仓库内，白烛焦急的不断摸索着。")
	novel_interface.show_character("baizhu_break","stare")
	await novel_interface.show_dialog("密码……\n密码是……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女颤抖的手指，已无法准确点按仓库内壁上的密码按键。")
	await novel_interface.show_text_only("如果白烛输入正确的密码，就能从这里出去与好友一起并肩作战。")
	await novel_interface.show_text_only("但是这次，门壁另一侧的牛奶没有留下任何破解密码的提示。")
	await novel_interface.show_text_only("又或者，再也不会给她任何提示了……")
	novel_interface.show_character("baizhu_break","angry")
	await novel_interface.show_dialog("不可能！！！\n不可能不可能不可能不可能不可能不可能……","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("即使白烛不计后果的疯狂敲击着壁门，她所期望的那一幕仍旧没有发生。")
	await novel_interface.show_text_only("在黑暗寂静的封闭空间内，少女想象着接下来壁门另一侧会发生的事情。")
	novel_interface.show_character("baizhu_break","puzzled")
	await novel_interface.show_dialog("不要……","白烛")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("（是因为……）","白烛")
	await novel_interface.show_dialog("（没有足够的力量吗……）","白烛")
	await novel_interface.show_dialog("（父亲也是……牛奶也是……）","白烛")
	await novel_interface.show_dialog("（为什么……会这样……）","白烛")
	await novel_interface.show_dialog("（无力。）","白烛")
	await novel_interface.show_dialog("（弱小。）","白烛")
	await novel_interface.show_dialog("（……又自私。）","白烛")
	await novel_interface.show_dialog("（为什么？）","白烛")
	novel_interface.show_character("baizhu_break","sad")
	await novel_interface.show_text_only("只是想抓住些微的温暖……")
	await novel_interface.show_text_only("为什么如此微小的愿望也……")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("黑暗中，少女泣不成声。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Storehouse.png")
	novel_interface.change_music("res://assets/audio/music/Wind.mp3")
	await novel_interface.show_text_only("白烛没有意识到刚才接连高强度的战斗，已经让自己的身体严重透支。")
	await novel_interface.show_text_only("深海后遗症逐渐将她的心智淹没。")
	await novel_interface.show_text_only("脑内轰鸣的水声一点一点将她的精神抽离。")
	await novel_interface.show_text_only("或许在黑暗的深海中，她并没看到那个存在……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/white_bg.png")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("少女仿佛身置一片冰川，细密而尖锐的冰碛深深的刺穿了她的心。")
	await novel_interface.show_text_only("她柔软的身体逐渐变得冰冷，血液似乎也开始凝\n结。") #换行问题
	await novel_interface.show_text_only("无数纯自的光团环绕在周围，直到完全覆盖了她的存在。")
	await novel_interface.show_text_only("痛苦也好，孤独也好。")
	await novel_interface.show_text_only("全都被涂抹的一干二净。")
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	await novel_interface.show_text_only("在一片纯白中，忽然响起一个熟悉的旋律。")
	await novel_interface.show_dialog("……牛奶？","白烛")
	await novel_interface.show_text_only("那是她和她最喜欢的歌。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling2.png")
	await novel_interface.show_text_only("白烛的体内突然爆发出数百个光团——")
	await novel_interface.show_text_only("少女渐渐睁开眼睛，随着刺眼的白光和一声巨响，壁门已经被整体吹飞。")
	await novel_interface.show_text_only("监控室的扩音器中正播放着牛奶手表里的歌，音乐在隧道中回荡。")
	await novel_interface.show_text_only("几十名循声而来的敌人聚集在附近，基地里潜伏的敌人远比她们刚刚看到的更多。")
	await novel_interface.show_text_only("十几个敌人已经聚拢在了监控室门前——")
	await novel_interface.show_text_only("此时少女距离中控室只有三十米左右的距离。")
	novel_interface.show_character("baizhu_break","cry")
	await novel_interface.show_dialog("（只要十秒……不，五秒！）","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她就可以出现在好友面前，阻止那个笨蛋。")
	await novel_interface.show_text_only("大群寄生士兵立刻涌向了白烛，几柄利刃突然从她身后袭来。")
	await novel_interface.show_text_only("白烛转身从枪刃中射出数发伴着强光的霰弹，瞬间将几个敌人打成了墙壁上的碎浆。")
	await novel_interface.show_text_only("她毫不停顿地向监控室奔袭，身上散发着从未如此耀眼的辉光。")
	await novel_interface.show_text_only("奔跑中巨大的能压剥落了隧道的内壁，闪耀的强光像是一曲神圣的挽歌。")
	await novel_interface.show_text_only("已经没人能阻止这股力量了……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Snedronningen_Light.png")
	await novel_interface.show_text_only("此时从白皇后基地射出无数道强光，极夜的星空也被照耀得恍若白昼。")
	await novel_interface.show_text_only("这一切……似乎在迎接神明的降临。")
	await novel_interface.show_text_only("突然整块大陆开始颤抖……")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling2.png")
	await novel_interface.show_text_only("在短短几秒内斩杀数十敌人的白烛，视野逐渐被光斑所侵染。")
	await novel_interface.show_text_only("体内激驰的力量似乎要将她自己一同吞噬。")
	await novel_interface.show_text_only("就在少女右手的利刃划开一个阻挡在面前敌人的瞬间。")
	await novel_interface.show_text_only("十几个敌人同时攻破了监控室的大门并一拥而入—")
	novel_interface.show_character("baizhu_break","angry")
	await novel_interface.show_dialog("笨蛋……等我……！","白烛")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("“我来了……”")
	await novel_interface.show_text_only("轰——！")
	await novel_interface.show_text_only("少女眼前，监控室内先是放出一道巨大的电弧，随后在一秒内传出数十次强烈地爆闪。")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("时间仿佛凝滞了。")
	await novel_interface.show_text_only("距离监控室仅有几米的地方，少女踉跄着停住了脚步。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling3.png")
	await novel_interface.show_text_only("此时，这片毫无慈悲、终年被冰架覆盖的大陆，如梦初醒般睁开了眼睛。")
	await novel_interface.show_text_only("黑暗中，从地底的冰层一直冲破隧道地板飞出一个金色的影子，无声的贯穿了少女的身体。")
	await novel_interface.show_text_only("那是一杆样貌朴素的长枪，只在枪头镶着金色的包边。")
	await novel_interface.show_dialog("……","白烛")
	await novel_interface.show_text_only("一股溫暖的热流划过枪尖，顺着枪身，和血液融合在一起。")
	await novel_interface.show_text_only("少女的双手无力垂下，双眼不甘地盯着前方，而瞳孔已经逐渐涣散。")
	await novel_interface.show_text_only("血液滴在地上。")
	await novel_interface.show_text_only("——啪嗒")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("极地的闪光熄灭了。")
	
	print("=== 深海恐惧症篇第24话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
