# bathophobia_ep22.gd - 潜渊症篇第22话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	bathophobia_ep22_script()

func play_script():
	pass

func bathophobia_ep22_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Reference_Room_Old.png")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("……似乎完全没信号了。","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("还是说，我们又进入那个『梦境』了吗……","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("无论如何，基地的换气系统依旧在运作，资料室的通风口传来风扇转动的声音。")
	await novel_interface.show_text_only("桌面上摊开的构造图显示，虽然年代久远，但这座基地绝对是按照保密机构的标准设计的——")
	await novel_interface.show_text_only("各区域的通行权限设置得极为严格，还用强化合金的门闸分隔出了很多功能不明的独立单元。")
	novel_interface.show_character("heinrich_battle","worry")
	await novel_interface.show_dialog("大部分房间都没有标注，要全部搜索一遍吗？","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("太复杂了……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("要将这些房间全检查一遍需要好几个小时，更何况我们并不知道要找的东西是什么样。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("而且不知会不会再遇到什么莫名其妙的敌人……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("刚才那几个奇怪的家伙让我现在还心有余悸。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("哼，我可不会在这里坐以待毙！","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔有些恼火的拍了下桌子，一团灰尘随之扬\n起。")
	await novel_interface.show_text_only("被突然的响声所吸引，金属横梁后的音感摄像头稍稍调整了下角度。")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我忽然想起一个刚才在补给站就想提出的问题。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("对了，你……能感知物质的材料？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女听到我的发问，有些得意的扬起嘴角。")
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("当然，这是『玫瑰十字会』的炼金术士所要掌握最基本的能力。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("那如果……有一根与外界绝缘的很长的金属线，你能追踪到它通向什么位置吗？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("如果我能触碰到的话，应该可以。","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("你是说……","拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我对心领神会的拉斐尔点了点头，然后一同将目光投向了房间那个漆黑的角落——")
	novel_interface.change_background("res://assets/images/bg/Baizhu/Red_Dot.png")
	await novel_interface.show_text_only("黑暗中，红色的小光点如呼吸般忽隐忽现。")
	await novel_interface.show_text_only("声音感应摄像头。")
	await novel_interface.show_text_only("庞大的地下基地中，遍布着这种监控装置。")
	await novel_interface.show_text_only("而它们必然通向同一个地方……")
	await novel_interface.show_dialog("——监控室。","小怜")
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Dispatched_Ship_Aisle.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("……被极地风暴阻断了么？","莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("小怜的芯片定位信息再次显示为离线状态。")
	novel_interface.character_light()
	await novel_interface.show_dialog("如果这种程度就丟失通讯的话，在高能带电粒子覆盖区域的任务也会受影响吧？","莉琉")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("战研部最近有些怠惰啊——","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("面对莉琉的白眼，爱衣做了个卖萌的表情。")
	novel_interface.show_character("liliu_uniform1","sigh")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_wink",0.25)
	await novel_interface.show_dialog("嘛……极端大气条件的影响确实被我低估了。","爱衣")
	novel_interface.change_2nd_expression("blush_stare")
	await novel_interface.show_dialog("不过肯定不会像刚才那样信号突然消失。","爱衣")
	novel_interface.character_light(0.35,"serious")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你是说现在的情况……有其他原因？","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"blush_dizzy")
	await novel_interface.show_dialog("虽然不知道是什么，但居然能做到这种程度…… 真是想想就让人心痒啊~","爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉低头若有所思的盯着手持设备上“通讯中断”的提示。")
	await novel_interface.show_text_only("一旁的爱衣则饶有兴致地观察着莉琉的表情。")
	novel_interface.show_character("liliu_uniform1","serious")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","think",0.25)
	await novel_interface.show_dialog("你还真像是在担心离家出走小宠物的饲主啊——","爱衣")
	novel_interface.character_light(0.35,"sigh")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不管怎么说，现在也只能静观其变了。","莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣长舒了口气，望向窗外。")
	novel_interface.show_character("liliu_uniform1","sigh")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("海拔37000米，看起来就像进入了太空一样呢。","爱衣")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("飞的再高雷达和常规通讯系统就无法工作了。","莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉看向了航船的工作区，30多名情报组的工作人员正在忙碌的梳理着世界各地传来的信息。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("难道说这架高速重型运载机……\n你早就想搞到手了？","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("哼，元老院手里还是有不少好东西的~","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("但是还要三个多小时才能到南极……","爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("要是小怜的身体被什么东西弄坏的话可就糟糕了。","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看到爱衣有些担心的咬起了指甲，莉琉弹了一下她的脑门。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("喂。","莉琉")
	await novel_interface.show_dialog("你以为那家伙，是谁调教出来的？","莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling.png")
	await novel_interface.show_text_only("白皇后基地。")
	await novel_interface.show_text_only("跟着海因里希的指引，我们循着监控设备的线缆来到了基地深处。")
	await novel_interface.show_text_only("这里的通道变得狭窄，裸露的墙体还有未完工的痕迹。")
	await novel_interface.show_text_only("幽长的隧道回荡着我们三人的脚步声，这种氛围让人不禁心跳加快。")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然时机非常糟糕……")
	await novel_interface.show_text_only("但紧张过度的我，越来越觉得……")
	await novel_interface.show_text_only("我默默停下脚步，举起手。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("那个……","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("又怎么了？","拉斐尔")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我……可不可以……","小怜")
	await novel_interface.show_dialog("……去……洗手间……","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我居然在全然没有门和岔路的隧道中央，对两个女生提出了这样的申请，好想去死。")
	novel_interface.show_character("ren_battle","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","perspire",0.25)
	await novel_interface.show_dialog("……","拉斐尔")
	novel_interface.change_2nd_expression("subtle")
	await novel_interface.show_dialog("你到底知不知道，现在是什么状况啊！","拉斐尔")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("对、对不起……我也……","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("面对拉斐尔鄙夷的神情，我有些不自在的并拢了双腿。")
	novel_interface.show_character("ren_battle","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","subtle",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（而且越紧张，越告诉自己不要在意，就越……）","小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("呼之欲出。")
	novel_interface.character_light(0.35,"sob")
	await novel_interface.show_dialog("（呜呜呜呜……）","小怜")
	await novel_interface.show_dialog("那个，或者能有个塑料瓶的话……","小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("——哈啊？！","拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("不对，我到底在胡说什么啊！！！")
	await novel_interface.show_text_only("拉斐尔看我的眼神，已经从变态变成了渣滓。")
	novel_interface.show_character("heinrich_battle","smile")
	await novel_interface.show_dialog("主人是需要什么盛具吗？确实有材料可以合成哦~","海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("海因里希看着我的窘态，有点幸灾乐祸的说道。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("我乱讲的！！！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看我快要哭出来的样子，炼金术士大发慈悲的走到隧道墙壁的一处位置，巧妙地切出一个开口。")
	await novel_interface.show_text_only("那堵墙后面，是一间昏暗的带卫生间员工宿舍。")
	await novel_interface.show_text_only("——炼金术万岁！")
	await novel_interface.show_text_only("在拉斐尔凌迟的目光中，我灰溜溜地钻了进去。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("这里的温度明显更低，墙壁上结了一层薄冰，我呼出的水气也加重许多。")
	await novel_interface.show_text_only("借着从隧道射入的灯光，我看到宿舍里的水银温度计指向-32度。")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("（不、不会一下子变成冰柱吧……）","小怜")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("（不不不，那也太不科学了……）","小怜")
	await novel_interface.show_dialog("（但……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Baizhu/BG_Base_Tunneling.png")
	await novel_interface.show_text_only("我羞红着脸，小心的回到隧道。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("磨磨蹭蹭的家伙。","拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","normal")
	await novel_interface.show_dialog("主人的脸好红啊……","海因里希")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("难道温玉的能量耗尽了？要不要换一块……","海因里希")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("不用、不用！！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("对不起，海因里希……\n只有这块温玉，我是绝对不会给任何人的！")
	await novel_interface.show_text_only("终于一身轻松的我，跟在海因里希和拉斐尔的后面继续顺着线缆的方向前进。")
	await novel_interface.show_text_only("我又回想刚才的场景，员工宿舍的桌面上放着半开的伏特加，墙面的冰似乎是黑色的。")
	await novel_interface.show_text_only("我在黑暗中走动的时候似乎踢到过的金属物品……\n是弹壳嘛？")
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("不对不对，我在胡思乱想什么啊……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("仔细观察四周，裸露水泥层的隧道墙壁上偶尔能看到一两块贴砖。")
	await novel_interface.show_text_only("等等，难道这些墙面不是未完工……")
	await novel_interface.show_text_only("而是整个隧道的内壁被什么力量剥落了？？")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_text_only("（这里……究竟发生了什么。）")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我们终于走到了监控室门前，已经卡死的门把手似乎很久没有被转动过。")
	await novel_interface.show_text_only("海因里希一番暴力操作，将把手带门锁一起敲掉。")
	await novel_interface.show_text_only("监控室的门缓缓打开——")
	novel_interface.show_character("heinrich_battle","shout")
	await novel_interface.show_dialog("——小心！！","海因里希")
	
	print("=== 潜渊症篇第22话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
