# chapter3_ep13.gd - 第3章第13话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep13_script()

func play_script():
	pass

func chapter3_ep13_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	await novel_interface.show_text_only("贝阿特丽切的睫毛微微闪动了一下，无意识地舔了一下嘴唇。")
	await novel_interface.show_text_only("我立刻感到小腹升起一股热流，迅速沿着身体各处的血管贲张开来。")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("小怜，小怜？！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","timid")
	await novel_interface.show_dialog("诶嘿嘿……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("——喂！！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我怔了怔，回过神来。\n可目光又不由自主地投向了贝阿特丽切。")
	novel_interface.show_character("beatrice_battle","smile3")
	await novel_interface.show_dialog("恕我冒昧，不过我现在很渴……\n不知这里有葡萄酒吗？", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她……她是在对我说话吗？\n我似乎能听到顺着颈动脉传来的心跳声。")
	novel_interface.show_character("ren_maid","timid")
	await novel_interface.show_dialog("是、是想喝水的意思吗？", "小怜")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("我马上就去拿！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("啊——气死我了！\n小怜这个大笨蛋！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔神色凝重地打量着这位不速之客，思考着她与黄金蝴蝶的关系。")
	await novel_interface.show_text_only("即使是这位挑剔的大小姐，对贝阿特丽切的容貌也很难进行贬低。")
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("这位小姐，你就这么出现在我的房间里，不觉得应该先解释一下自己的身份么？", "拉斐尔")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("看你的装束，是文艺复兴前期欧洲贵族的装扮。\n口渴的第一反应是索要葡萄酒……", "拉斐尔")
	await novel_interface.show_dialog("是从哪个历史爱好者聚会跑来的吗？怎么突然出现在这里的？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("黄金蝴蝶是魔导器的话……", "安妮")
	await novel_interface.show_dialog("又有小怜在场，那她会不会是……", "安妮")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("——魔女？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我正端着水向想递过去，听见『魔女』这个词，立刻警觉了起来。")
	novel_interface.show_character("beatrice_battle","normal")
	await novel_interface.show_dialog("魔女……", "贝阿特丽切")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("『裁判所』的教士们确实是这么称呼我的。\n既熟悉又陌生的称呼……", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切仿佛在努力思索着什么。")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("裁判所……\n曾经？", "安妮")
	novel_interface.change_expression("unhappy")
	await novel_interface.show_dialog("（喂喂，不会吧……）", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","normal")
	await novel_interface.show_dialog("是啊，在审判庭上，那些人逼我喝下了一杯酒……", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切接过我端来的水杯，停下了回忆，对我莞尔一笑。")
	novel_interface.show_character("ren_maid","heart")
	await novel_interface.show_dialog("（果然……还是，好漂亮啊~~）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("饮下忘川之水，才能获得新生。", "贝阿特丽切")
	await novel_interface.show_dialog("这是之前一个男孩为我写的诗……", "贝阿特丽切")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("你是那个赐予我新生的人吗？", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","timid")
	await novel_interface.show_dialog("我？\n那、那个……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("开什么玩笑……", "拉斐尔")
	novel_interface.change_expression("jeer")
	await novel_interface.show_dialog("你是想说这句诗是写给你的吗？你不会想说自己还曾经是在天国之门迎接那位诗人吧？", "拉斐尔") 
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("什么“魔女”……\n都是传说和野史的胡编乱造！", "拉斐尔") 
	await novel_interface.show_dialog("你们一个个，脑子都坏掉了吧？\n就算是『异质物』，也不可能做到这种事。", "拉斐尔")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("因为……\n因为！！", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("因为『异质物』的基本特性之一，是不会违反时间线上的因果逻辑。", "莉琉")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("莉琉？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("连这种研究生课程才会教的东西都知道，不愧是戴克斯博士最喜欢的小孙女。", "莉琉")
	novel_interface.show_character("ren_maid","sprite")
	await novel_interface.show_dialog("喂喂，你一说话我的胸部就会震动……", "小怜")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("这样………很痒啊！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","worry")
	await novel_interface.show_dialog("你的衣服里……有人在说话？", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("是身体里。\n不过我不想解释，抱歉。")
	await novel_interface.hide_background_with_fade()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("拉斐尔·戴克斯小姐，我是莉琉·冯·布劳恩，新丰洲市秘密情报局的主管。", "莉琉")
	await novel_interface.show_dialog("从昨晚开始，我们检测到『天空酒店』的位置出现了间歇性的时空相位波动。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("现在请你请务必配合我们的两位探员，否则我无法保证你的安全。", "莉琉")
	await novel_interface.show_dialog("刚才戴克斯博士已经将安全密匙交付与我——\n『Noblesse Oblige』", "莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("爷爷……", "拉斐尔")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("嘁，总把我当小孩子。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("位高，则任重……\n看来你的祖父是位优秀的人呢。", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("姑且先相信你们吧。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那么，你知道那个手提箱是怎么回事吗？", "莉琉")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("那就要问你的手下了——这个女装癖和小丫头。", "拉斐尔")
	await novel_interface.show_dialog("要不是她们闯进我的房间，我根本不会注意到。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","speechless")
	await novel_interface.show_dialog("女装？", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我下意识地揪了揪女仆装的裙角。\n想把它们掖起来。")
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("仔细想来……只有一件事比较奇怪吧。", "拉斐尔")
	await novel_interface.show_dialog("今天下午，我的保镖都有些精神恍惚，情绪焦躁。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("我想……我知道原因。", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("你知道？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("你项链上的那枚挂坠，是一枚绿宝石吧？", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切指了指拉斐尔的胸前。")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("你怎么知道？我明明戴在衣服里面……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔惊讶地拉出了项链，末端果然是一枚绿宝石挂坠。")
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("如果我没认错的话，那是父亲交付我的佩剑上镶嵌的宝石。", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("什么？！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("刚才，我在黑暗中感受到了强烈的共鸣，想必就是这颗宝石产生的感应吧。", "贝阿特丽切")
	await novel_interface.show_dialog("尽管是隔着一层屏障传来的微弱感觉，但是我不会认错属于自己的东西。", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("胡说！这个项链是戴克斯家族的藏品……已经有几百年的历史了。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("难道是魔女的遗物和魔导器之间产生的共鸣嘛？", "安妮")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("等等，那第一个应该影响的不应该是……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("先别说那些，门口的人要进来了。", "莉琉")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("喷，只知道白拿薪水的废物终于来了吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","smile")
	await novel_interface.show_dialog("呼，终于可以跟这身女仆装说再见了！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("正在我打算松口气的时候，突然感到一股寒意。")
	await novel_interface.show_text_only("门口的气凝胶干块出现一个圆形的白点，然后白点逐渐扩大，并发出“咯咯”的声音。")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("保安军……一般会配置液氮喷射器吗？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("随着“咔”的一声，气凝胶干块像玻璃一样整体碎裂成了无数小块。")
	await novel_interface.show_text_only("一群手持武器的人冲进屋内，将我们团团包围了起来。")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("……你们是什么人！", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然不知道他们的身份，但从那副奇怪的深蓝色面罩来看，他们绝不是保安军。")
	await novel_interface.show_dialog("想不到，这么快……", "男性的声音")
	await novel_interface.show_text_only("门后传来一个熟悉的男声。")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("你是——？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("诸位…我们又见面了。", "雅各")

	print("=== 第3章第13话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
