# chapter3_ep10.gd - 第3章第10话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep10_script()

func play_script():
	pass

func chapter3_ep10_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/diningRoom2.png")
	await novel_interface.show_text_only("由于斯库尔德的出现，那名叫法贝拉的暴力女仆似乎决定放我一马。")
	await novel_interface.show_text_only("而斯库尔德刚刚跟我们打过照面，就马上有好几位打扮讲究的宾客围上来跟她打招呼。")
	await novel_interface.show_text_only("明明是和伊露卡差不多年纪的小姑娘，却能对这样的社交场合应对自如……")
	novel_interface.show_character("ren_maid","worry")
	await novel_interface.show_dialog("（斯库尔德………是谁家的大小姐吗？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("趁法贝拉把注意力转移到她的小主人身上，我马上逃到了宴会厅的另一侧。")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("吓死我了……\n刚那两人是主仆关系吧？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那个女仆好像也没有要揭穿我的意思\n说那样的话是想要诈我吗？")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("小怜，找你好久了！", "安妮")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("我可能发现了关键线索哟！", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_maid","normal2",0.25)
	await novel_interface.show_dialog("哎？", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我刚才偷偷跟着考察团的人上到了行政楼层，看到拉斐尔的随从拿着一个特别的手提箱。", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire1")
	await novel_interface.show_dialog("手提箱……里面装了什么？", "小怜")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("没有看到，但是那个手提箱的材质，我在参加SID培训的时候学到过！", "安妮")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("灰绿色的金属，周围散发着那种特有的淡蓝色光晕——", "安妮")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"solemn")
	await novel_interface.show_dialog("蓝色光晕……\n难、难道是！！", "小怜")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("我也想起来，那是一种可以减弱或屏蔽精神和模因类『异质物』影响的合金所特有的性状。")
	await novel_interface.show_text_only("使用那种材料打造的容器装载『异质物』，可以避过绝大部分的色相扫描。")
	await novel_interface.show_text_only("那种合金自身也属于异质物，98%的质量由已知金属组成，剩下的2%为未知物质。")
	await novel_interface.show_text_only("由于其存量稀少，已经被不法人士在黑市上炒到了天价。")
	await novel_interface.show_text_only("所以那个手提箱里，几乎可以肯定是与『异质物』有关的东西。")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("这、这岂不是出大事了吗！！\n你报告给莉琉了吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("本次萨蒙顿的考察团入境，并未向元老院申报携带有任何『异质物』。")
	await novel_interface.show_text_only("如果高杀伤性的『异质物』被偷运到防护力场内，可能让新丰洲顷刻之间覆灭。")
	novel_interface.show_character("anne_uniform","relieve")
	await novel_interface.show_dialog("已经第一时间报告了，莉琉小姐现在应该正在向元老院申请调查令。", "安妮")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("但我只是一闪而过的看到，并没有拍到照片。\n估计很难仅凭我的证词就硬闯……", "安妮")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("所以，莉琉小姐刚才已经将我们的命令更改为“尽快取得证据并上传”了！~", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_maid","solemn",0.25)
	await novel_interface.show_dialog("如果这样，那我们得想办法潜入他们的房间才有机会查清楚……", "小怜")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯…那个贵族小姐的房间，估计难度不小呀", "安妮")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("唔…也只能走一步算一步了……", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomPassage.png")
	await novel_interface.show_text_only("我和安妮从员工电梯到达了被考察团包下的整层行政楼层。")
	await novel_interface.show_text_only("我推着从厨房“借”来一辆餐车，安妮就藏在餐车底下，向守在走廊的几个保安走去……")
	await novel_interface.show_dialog("喂！你是楼下宴会的女仆吧？\n这里不是你该来的地方，马上离开。", "保安")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("（果然和想像中一样守卫非常森严啊。）", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("哎？刚才皇室套房点了客房服务，指明要女仆现场制作火焰威士忌鹅肝呢。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("领头的保安仍然一脸严肃，丝毫不为所动。")
	await novel_interface.show_text_only("看来我想的还是太天真了，得另想办法才行……")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("啊哈哈……那可能是客房服务部搞错了，打扰了…", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我还没来得及把话说完，安妮已经一个箭步冲了上去，一个肘击正中领头保安的颈部。")
	await novel_interface.show_text_only("接着回转身体借力透出一枚棒球，精准的击中了十米外另一名保安的面门。")
	await novel_interface.show_text_only("剩下的保安被突如其来的攻击打乱了阵脚，还没来得及按下通讯器就被安妮一记飞踢击中了下巴。")
	await novel_interface.show_text_only("三名保安几乎同时倒地，而那枚掷出的棒球只在地上弹了一下便又回到了安妮手中。")
	novel_interface.show_character("ren_maid","wry_smile")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("好，解决啦！", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"perspire1")
	await novel_interface.show_dialog("你、你把他们怎么样了？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("放心吧，只是让他们稍微睡一会儿觉而已。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("哈哈，还真是符合安妮的风格啊……\n（唔…还好我和安妮是一国的！……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("而且刚才安妮并没有使用魔法吧？！\n莉琉平时都给她安排了什么样的训练啊……")
	await novel_interface.show_text_only("解决了走廊上的保镖之后，安妮带着我走向了最里面双开门的套房。")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("就是这里。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我和安妮对视一眼\n正准备在房门上偷听的时候——")
	await novel_interface.show_text_only("门从里面被人打开了，我们毫无防备的摔了进去。")
	await novel_interface.hide_background()
	novel_interface.show_character("ren_maid","sob")
	await novel_interface.show_dialog("疼疼疼疼疼……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我坐在地上，抬头看到了那个熟悉而高傲的面孔。")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("……拉斐尔？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔依旧一脸鄙夷的表情，她的身边还站着好几个保镖和随行人员。")
	await novel_interface.show_text_only("啊，居然都是御姐型的漂亮大姐姐呢……")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("嗯…~？你不是那所破烂学校里的女装癖吗？鬼鬼祟祟的干什么呢？", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("这次还换了女仆装，你这变态的特殊兴趣又更恶劣了吗……", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","wail")
	await novel_interface.show_dialog("好、好巧啊~\n我只是跟同学来酒店打工……", "小怜")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("啊对了，宴会厅是在楼下吧\n我们好像走错地方了。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮对不起，我真的太不擅长撒谎了！")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("奇怪了，保安没有拦住你们吗？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔疑惑地向走廊张望了一眼。")
	await novel_interface.show_text_only("注意到走廊上倒地不起的保安，拉斐尔露出震惊的表情。")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("——给我抓住她们！", "拉斐尔")

	print("=== 第3章第10话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
