# chapter3_ep01.gd - 第三章第1话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep01_script()

func play_script():
	pass

func chapter3_ep01_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("诡异的恶梦、意义不明的对话、梦中的黑影\n以及全网推送的AAA级通缉令……")
	await novel_interface.show_text_only("在我勉强接受了新的身份和生活，重新开始振作起来的时候，它们将所有的一切，都再次打乱了。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("——莉琉！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("嗯？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("你看到新闻了吗？\n他……不对，是我，我出现了啊！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("我又没瞎，当然看见了你正满头大汗的傻乎乎的站在我面前呢。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("不是啦——\n可恶，是新闻上！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("忙乱之中，我一时间不知应该从哪里说起\n莉琉哼了一声，用手刀敲了下我的脑袋。")
	novel_interface.show_character("ren_battle","perspire1")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("训练这么久，你怎么还是这么没用啊，连这点事都不能向长官准确回报。", "莉琉")
	await novel_interface.show_dialog("不就是一个和以前的你长得很相似的人，抢劫了第二学园都市的收容基地，被全世界通缉了吗？", "莉琉")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("对对对，就是这样没错！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("这种网上乱飞的消息，情报部门的人早就报上来\n了。", "莉琉")
	novel_interface.change_2nd_expression("speak2")
	await novel_interface.show_dialog("瞧你一幅花容失色的样子，实在太蠢了~", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉小姐扯了扯我的嘴角，我连忙抓住莉琉小姐乱动的手。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("……莉琉，现在是开诸（这）宗（种）玩笑的时候吗？", "小怜")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("被全球通缉诶，怎么能算小事？", "小怜")
	await novel_interface.show_text_only("我做梦也不会想到，第一次上新闻居然是因为这种事啊！")
	novel_interface.change_expression("wail")
	await novel_interface.show_text_only("而且是AAA级通缉！！我记得上一个获此殊荣的家伙是在南美的山区里被钻地弹直接打爆的。")
	novel_interface.change_expression("sob")
	await novel_interface.show_text_only("这个可恶的抢劫犯，就这么偷走了我的人生……想到这里我快要急得哭出来了。")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("如果那样……\n我能依靠的，只有莉琉了……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("虽然很想继续欣赏你花枝乱颤的样子……", "莉琉")
	novel_interface.change_2nd_expression("speak2")
	await novel_interface.show_dialog("不过嘛，你再确认一遍消息看看。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"sob")
	await novel_interface.show_text_only("这种事还需要再确认吗？新闻上的信息都已经一清二楚地印刻在我脑海里了。")
	await novel_interface.show_dialog("那上面的图像虽然不太清楚，但和我男生时样子完全一样，几乎就是我本人啊！", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("虽然嘴上这么说着，但我还是不服气地拿出手机打开了那个新闻页面。")
	novel_interface.character_light(0.35,"upset")
	await novel_interface.show_dialog("你看，这明明就——\n诶？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("今天清晨那则让我惊慌失措的通缉令，已经变成了一则普通的寻人启示。")
	await novel_interface.show_text_only("70岁的漫画家井上先生于近日走失\n如有能够提供线索者，请及时与警察联系……")
	await novel_interface.show_text_only("我又翻查其他的网站，甚至用关键词搜索，那则新闻就像从未存在过一样。")
	await novel_interface.show_text_only("望着眼前笑得有些不怀好意的莉琉，我心中涌上了一股感激之情。")
	novel_interface.show_character("ren_battle","timid")
	await novel_interface.show_dialog("是、是你做的吗？……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉走进，轻轻的擦了擦我的眼角。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("你看你，快要哭出来了。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("如果真的想要感谢的话，今后就为我做牛做马一辈子供我驱使吧~", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("而且……", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("你说着“我能依靠的只有莉琉了”这种话的样子实在是可爱的让人欲罢不能呢……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉用食指轻轻抬起我的下巴。")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("别、别捉弄我啦~！", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("而且从现状看来，我也一直在为你做牛做马嘛……")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("——虽然很想说是我有这个本事，但是能做到让全世界的媒体都乖乖听话的，目前只有一个机构。", "莉琉")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哎？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("是『联合议会』下达的强制令。", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("六个学园都市联合组成的最高议会……居然会下令撤除我的新闻？", "小怜")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("为什么……", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉定神打量了我片刻，勾起一个神秘的笑容。")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("你少自以为是了，他们这么做显然不是为了保护劫匪。", "莉琉")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("而是不能让公众知道，被抢走的是什么。", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那个劫匪究竟是谁，他为什么会以我的身份出现？", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("能闯入阿卡特拉兹收容基地并全身而退的人，十分值得钦佩啊~", "莉琉")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("真正的问题是，这样的人如果想要遮住样貌应该很简单。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("但那个家伙非但不遮挡，还很嚣张的在楼顶站了一会……", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("培训课程里学过，最容易被忽视的，是那些本该出现但却没有……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("——以及本不该有却出现了的信息。", "莉琉")

	print("=== 第三章第1话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
