# chapter3_ep04.gd - 第三章第4话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep04_script()

func play_script():
	pass

func chapter3_ep04_script():
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	await novel_interface.show_text_only("距离通缉令事件已经过去了几天。")
	await novel_interface.show_text_only("果然如莉琉所言，在普通民众的生活里，这件事并没有掀起什么波澜。")
	await novel_interface.show_text_only("就连莉琉说的信息扰乱工程，于现实生活也几乎毫无影响。")
	await novel_interface.show_text_only("整件事就好像一场恶梦。")
	novel_interface.show_character("iluka_normal","smile")
	await novel_interface.show_dialog("小伶姐姐，早安。", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("由于伊露卡的魔女身份和特殊能力，SID不得不对她进行收容管控。")
	await novel_interface.show_text_only("但这个小家伙对我似乎产生了依赖感，莉琉也顺势自称日行一善的将她送到我身边来。")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("早上好啊，伊露卡。\n今天想吃什么好吃的呢？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("喂！小孩子不能吃太多零食！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","worry")
	await novel_interface.show_dialog("呜……", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("没关系，偶尔吃一点嘛~", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","stare",0.25)
	await novel_interface.show_dialog("你的“偶尔”也太频繁了吧！", "安妮")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("而且伊露卡一直和我们待在一起，真的不要紧吗？", "安妮")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哎？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("她还是个小孩子吧……\n这个年龄不是应该去上学吗？", "安妮")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……大概不能用普通小孩的模式来定义伊露卡吧？", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"upset")
	await novel_interface.show_dialog("话是这么说，但还是有点担心……", "安妮")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("都怪小怜啦，总是给她投食，我都开始担心她的成长问题了呢！", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("iluka_normal","unhappy")
	await novel_interface.show_dialog("安妮，坏！", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡委屈地看着安妮，安妮被那道目光击中，露出了惨不忍睹的表情。")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("我好像，突然明白了被孩子讨厌的妈妈的心情……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("好啦，别这么严厉嘛。", "小怜")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("喏，伊露卡，今天只能再吃一块巧克力了啦~\n今天我们带你去学校转转。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("根据莉琉的要求，只有包括公寓和学校在内的一小块范围是我们被允许带伊露卡自由活动的。")
	novel_interface.show_character("iluka_normal","normal")
	await novel_interface.show_dialog("哦……", "伊露卡")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_centreSpace1.png")
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("……还是，难过。", "伊露卡")
	novel_interface.character_dark()
	await novel_interface.show_text_only("我轻轻地摸了摸伊露卡的头，和安妮一道带着伊露卡来到了学校。")
	await novel_interface.show_text_only("嗯~今天天气不错，微风拂过也不会觉得太热。")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_uniform","smile",0.25)
	await novel_interface.show_dialog("要乖哦，别难过啦。", "小怜")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("伊露卡突然抬起头，连嘴角沾上的巧克力都没有来得及舔掉，认真地望着我。")
	novel_interface.character_light(0.35,"gourmet")
	await novel_interface.show_dialog("小伶姐姐……", "伊露卡")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy_left")
	await novel_interface.show_dialog("（哇，别用这种眼神看着我啊！）", "小怜")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("伊露卡踮起脚尖，抓住我的手又放回了她的头上。")
	novel_interface.character_light()
	await novel_interface.show_dialog("再摸摸。", "伊露卡")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_text_only("这、这是向我发起的攻击吗！？\n报告指挥部，我今天要折损在这里了！！")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("还真是个无可救药的笨蛋萝莉控啊。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_normal","mock")
	await novel_interface.show_dialog("嘿嘿，我也这么认为呢。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯学姐的声音从我身后传来。")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("倪克斯学姐？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她是怎么悄无声息的出现到我们身后的……")
	novel_interface.show_character("ren_uniform","perspire1")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_normal","smile",0.25)
	await novel_interface.show_dialog("抱歉，吓到你了吗？", "倪克斯")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不、只是……\n没有啦！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("想到自己被学姐看到了对着伊露卡犯傻的样子，一股巨大的羞耻感涌了过来！")
	await novel_interface.show_text_only("幸好她没有抓住不放的捉弄我，跟优雅大方的人相处真好啊~")
	novel_interface.show_character("nyx_normal","smile")
	await novel_interface.show_dialog("你是叫伊露卡，对吗？", "倪克斯")
	await novel_interface.show_dialog("如果伊露卡喜欢甜点的话，下次带你去吃海绵蛋糕怎么样？", "倪克斯")
	await novel_interface.show_dialog("剧院街有一家店，她们特制的枫糖浆非常香醇，会有一点焦糖的味道。", "倪克斯")
	await novel_interface.show_dialog("而且蛋糕的内馅里还有店长特制的巧克力奶油，你一定会喜欢的。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡认真地思考了一会儿，终于没能抵抗住食物的引诱，乖巧地点了点头。")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("伊露卡，小孩子不能随便接受陌生人的食物啦！", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","smile",0.25)
	await novel_interface.show_dialog("有什么关系嘛，这是学姐诶。", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"worry")
	await novel_interface.show_dialog("唔，虽然是这样啦……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("是我的错觉吗？")
	await novel_interface.show_text_only("从第一次见面时起，安妮似乎就对倪克斯抱有微妙的警惕。")
	novel_interface.show_character("nyx_normal","smile")
	await novel_interface.show_dialog("那就说定了哦，伊露卡。", "倪克斯")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","smile")
	await novel_interface.show_dialog("嗯！~", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的手机忽然响了起来\n——是莉琉小姐的来电。")
	novel_interface.show_character("ren_uniform","normal1")
	await novel_interface.show_dialog("……喂？", "小怜")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("（又有什么任务给我吗？）\n（真是的，难得有空带伊露卡出来逛逛……）", "小怜")

	print("=== 第三章第4话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
