# chapter3_ep11.gd - 第3章第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep11_script()

func play_script():
	pass

func chapter3_ep11_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	await novel_interface.show_text_only("拉斐尔的保镖将我们团团围住，安妮对我使了个眼色——")
	await novel_interface.show_text_only("我心领神会，将安妮刚才在走廊里积累的能压一口气释放出来。")
	await novel_interface.show_text_only("房间内顿时出现了大量高速射出的棒球，击中一个人后又立刻弹向另一个。")
	await novel_interface.show_text_only("那些保镖显然没有应对这种场面的经验，纷纷乱了阵脚，中招倒地。")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("还是第一次对普通人用这招呢，这么快就全都打倒了啊……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("那是当然，保有理智的人类比暴走的女巫好对付多了~", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("可恶，一群饭桶……", "拉斐尔")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("居然敢来这里闹事，保安军不会放过你们的！", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我才发现拉斐尔的皇室套房已经被刚才的战斗搞得一片狼藉，她的保镖横七竖八的倒在地上。")
	await novel_interface.show_text_only("本来我和安妮只想偷偷搜集证据，但似乎制造了不得了的国际争端……")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("糟了………安妮！\n快，快把她……绑起来！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("慌乱中我，向安妮发出了奇怪的指令。")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("嘿~好哒！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮利落的压住拼命挣扎的拉斐尔，撕开在混战中散落的窗帘，三两下就将她五花大绑了起来。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("你、你竟敢——！！\n你这女装变态，到底要对我做什么？！", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("此时，新丰洲的国宾，第四学园都市市长的亲孙女正被绑在自己酒店房间的椅子上——")
	await novel_interface.show_text_only("安妮为什么这么熟练啊！！\n而且这样似乎完全无法洗刷变态的名声了……")
	novel_interface.show_character("ren_maid","upset")
	await novel_interface.show_dialog("实在抱歉，我们得确保你不会触发警报器……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我指了指墙边的红色按钮，那个一旦被按下，3分钟内就会有一队手持重武器的保安军将这里包围。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("哼，你们究竟想干什么？", "拉斐尔")
	await novel_interface.show_dialog("既不隐藏身份，似乎也没准备撤离方案——\n你们应该不是想索取赎金的绑架犯吧？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("就算被以如此不妙的姿势绑在椅子上，也依旧态度傲然，思路清晰……不愧是贵族大小姐。")
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("你们到底是什么人？\n刚才用的是『异质物武器』吗？", "拉斐尔")
	novel_interface.character_dark()
	await novel_interface.show_text_only("她这句话忽然让我想起了现在最重要的任务。")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_maid","solemn",0.25)
	await novel_interface.show_dialog("拉斐尔小姐，我们只是要弄清楚一件事。\n关于那个手提箱……", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("手提箱？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔露出了困惑的表情，好像完全不知道我在说什么。")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("好像……已经碎了呢！", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_maid","perspire1",0.25)
	await novel_interface.show_dialog("啊？！那种合金的强度应该很高吧？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我朝着安妮的手指望去，在不远处看到了一只被棒球砸出了数个大坑的手提箱。")
	await novel_interface.show_text_only("箱体外的黑色塑料壳已经破碎脱落，露出了里面泛着淡蓝色光晕的金属内层。")
	await novel_interface.show_text_only("这种塑料是一种常见的可拆卸伪装，安妮刚才应该是偶然看到了手提箱内层的材质。")
	await novel_interface.show_text_only("箱子的锁扣也已经被砸坏，内容物和一些金属碎片散落在旁边的地毯上。")
	novel_interface.show_character("anne_uniform","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_maid","perspire1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("奇怪，我的棒球应该只会追踪有生目标……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔似乎也看到了那个泛着淡蓝色光晕的金属材质，露出了惊讶和慌张的神情。")
	await novel_interface.show_text_only("一旁散落的减震海绵和金属碎片堆里，我发现了一个正在闪光的小东西。")
	await novel_interface.show_text_only("那是一个蝴蝶样式的金色饰品，造型栩栩如生，翅膀上的缕空花纹十分精美。")
	novel_interface.show_character("anne_uniform","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_maid","serious",0.25)
	await novel_interface.show_dialog("会不会是因为这个东西……手提箱才被你的棒球误当做目标的？", "小怜")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("小心啊！那可能是『异质物』——", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("这精巧的黄金蝴蝶似乎随时都会飞起来一样，连拉斐尔的注意力也被吸引了，我不禁伸手……")
	await novel_interface.show_dialog("喂喂，笨蛋。\n都叫你别碰了——", "莉琉")
	await novel_interface.show_text_only("莉琉的声音突然传出，我的身体忽然一阵酥麻，就好像她就在我身旁说话一样。")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("欸？\n什、什么啊！！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我慌张的在身上寻找着声音的源头，确定自己衣服里没有带着扬声器之类的东西。")
	await novel_interface.show_dialog("要是安妮的棒球能把洛氏硬度70的合金材料砸出这种坑，那几个保镖的脑袋早就开花了。", "莉琉")
	await novel_interface.show_dialog("多半是这个小东西自己想借助棒球的冲击力自己挣脱出来吧……", "莉琉")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("那些弹坑………是这个饰品自己造成的？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("呵呵，很有可能喔，所以说这么危险的东西你还敢乱碰吗？", "莉琉")
	novel_interface.show_character("ren_maid","wail")
	await novel_interface.show_dialog("不对，重点是——\n莉琉！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可恶，我找到音源了！")
	await novel_interface.show_text_only("声音是从我的胸部传出来的，怪不得莉琉一说话我就感觉麻麻的……")
	novel_interface.show_character("ren_maid","stare")
	await novel_interface.show_dialog("你果然，在我身上植入了什么奇怪的芯片吧！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("居然当着外人随意透露我们的机密技术，你是不是又皮痒想被我踩了？", "莉琉")
	await novel_interface.show_dialog("安妮，先让那位大小姐睡会吧~\n不过小心点，别伤到我们的贵宾。", "莉琉")
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("喂！你们想——！", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮对着拉斐尔的后颈使出一记轻巧的手刀，把她打昏了过去。")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("莉琉小姐，这类『异质物』未经申报不能带入新丰洲市内的吧？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("当然了，哼，居然我的眼皮底下偷运这种东西，看来戴斯博士必须得给元老院一个交待了。", "莉琉")
	await novel_interface.show_dialog("……等等，楼道里的保安似乎被发现了。", "莉琉")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("啊，这么快？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("现在楼下的保安军正在大厅集合。\n我正带着收容队赶来，预计8分钟内到达。", "莉琉")
	await novel_interface.show_dialog("安妮，你现在用气凝胶把大门封住。", "莉琉")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("好哒，收到！", "安妮")

	print("=== 第3章第11话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
