# chapter3_ep05.gd - 第三章第5话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep05_script()

func play_script():
	pass

func chapter3_ep05_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("刚回到总部，莉琉就支使安妮和伊露卡去执行别的任务。")
	await novel_interface.show_text_only("我有些忐忑，不知道是否又会面对奇怪的拷问……")
	novel_interface.show_character("ren_uniform","sprite")
	await novel_interface.show_dialog("发生什么事了？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("没事的话，你就想一直在伊露卡旁边像个变态一样傻笑吗？", "莉琉")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你、你果然在用学校的监控像头偷窥吧！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("呵呵呵~~你只能想到那么老土的方式吗？", "莉琉")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那还有什么方法……", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("比如说——", "莉琉")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("莉琉上下打量着我，露出了邪恶的神情。")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("战研部有一种晶片，植入以后连你什么时候想上厕所都能完美的控制。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","perspire1",0.25)
	await novel_interface.show_dialog("控、控制？\n那也太不妙了！！", "小怜")
	await novel_interface.show_dialog("这种奇怪的东西多半是爱衣做的吧……\n等等，你们不会偷偷给我植入了吧！", "小怜")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("开玩笑的。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("这么敷衍的回答，一点也不像开玩笑！！")
	novel_interface.show_character("liliu_uniform2","speak2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","perspire1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("还是说……你想到什么奇怪的事情了？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy")
	await novel_interface.show_dialog("唔，可恶……", "小怜")
	await novel_interface.show_dialog("（上次全校集会的时候我忽然闹肚子……）\n（难、难道是！？）", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哈哈哈哈~~你居然当真了吗？", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉大笑着揉了揉我的脑袋。")
	novel_interface.show_character("liliu_uniform2","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","shy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那种东西，爱衣只做了一个原型机就被我骂惨了\n怎么可能用在你这种没价值的目标身上。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy_right")
	await novel_interface.show_dialog("那还真是多谢了哈……", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("话说，你刚才在想什么丢人的画面啊~", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("呜呜……还好没有显示思考画面的机器，不然我真要找个地缝钻进去。")
	novel_interface.character_light(0.35,"speak2")
	await novel_interface.show_dialog("别马上摆出认命的表情嘛，这样就一点都不好玩儿了。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_text_only("让你失望了，真是对不起。")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哎，以你现在的能力，不知道能不能完成向重要目标套取信息的工作。", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉抹了抹因为爆笑而盈在眼角的泪水，转换成平时傲慢而自信的表情。")
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("重要人物……虽然比满足你的恶趣味有意义，但人家会跟我一个学生说什么啊。", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("就是要利用你学生的身份，这次的目标是第四学园都市考察团的代表——", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("拉斐尔·戴克斯，萨蒙顿市市长的孙女，可是如假包换的超贵族大小姐哦。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("是不是很激动？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("这有什么好激动的。", "小怜")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啧，果然只有小女孩才能让你兴奋起来吗……", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("不要把这种犯罪者的设定安到我身上啊！", "小怜")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("……咳咳。\n总之你要我向那位大小姐打听什么信息？", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("转移话题的功夫真差劲……\n你不会真的一上来就被识破吧。", "莉琉")
	await novel_interface.show_dialog("先不计较了，关于第四学园都市你有多少了解？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("唔……我记得是现在最大的粮食出口国？", "小怜")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("说起萨蒙顿市，第一印象就是莱茵河畔林立的几十层楼高的立体温室。")
	await novel_interface.show_text_only("那一大片从温室群的玻璃罩透出的生机盎然的绿色一向是屏幕壁纸的绝佳素材。")
	novel_interface.show_character("ren_uniform","normal1")
	await novel_interface.show_dialog("另外萨蒙顿好像有很多教堂，大家都有宗教信仰，还成立了一个『神圣联盟』之类的……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("只记得这些了，地理这种知识点分散又需要大段背诵的课程真是想想就胃和头一起疼。")
	novel_interface.show_character("ren_uniform","normal1")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("第四学园都市的经济和话语权，在很大程度上取决于他们对农作物基因的控制力。", "莉琉")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("不过『洛斯金杯』消失后发生的一系列事件，恐怕也威胁到了他们的根基。", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("威胁是指……空间异变？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("没错，虽然有报告侦测到第四学园都市境内也发生了多处异变，但一直无法判断其损失情况。", "莉琉")
	await novel_interface.show_dialog("从这几天谷物和豆类期货的异动看来，影响估计不小……会在局部地区引起饥荒也说不定。", "莉琉")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这么严重吗……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("虽然不懂那个什么市场，但我之前一直认为，异变最多威胁到小范围区域。")
	novel_interface.show_character("ren_uniform","upset")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("是啊，粮食减产引起的问题通常有一定的滞后，毕竟各国都有风险储备。", "莉琉")
	await novel_interface.show_dialog("看来另外五个学园都市里，首先按捺不住的就是他们。", "莉琉")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("萨蒙顿筹备了一支考察团，已经出发前往新丰洲\n了。", "莉琉")
	await novel_interface.show_dialog("我们作为主要粮食进口国，是无法拒绝他们的请求的。", "莉琉")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("难道他们……会怀疑到我和安妮头上吗？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("这就是我找你来的原因。", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("诶？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("虽然打着“艺术交流”的旗号，但这支考察团可是由皇家保卫局亲自负责保密和安全工作的。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("皇家保卫局……第四学园都市的情报机构，又称十字玫瑰（Rosenkreutz）。")
	await novel_interface.show_text_only("虽然是间谍组织，但却因为描写其7号特工的系列电影而众所周知。")
	novel_interface.show_character("ren_uniform","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那不是很麻烦吗？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("没错，SID就算想做个背景调查都会处处受限。", "莉琉")
	await novel_interface.show_dialog("目前得到的消息里，与你有关的，就是那位贵族大小姐会去参观御樱川女子中学。", "莉琉")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("来我的学校？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("这倒是不奇怪，她的年纪应该在读高二，也是高中生。", "莉琉")
	await novel_interface.show_dialog("所以需要你在她参观的过程中，搞清楚考察团的具体目的。", "莉琉")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("我让情报部将萨蒙顿和戴克斯家族的背景知识做成了一本小册子，回去好好温习一下吧。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("哎，又要背书啊……\n总之交给我吧！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("回家的时候要小心色狼哦。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("喂！什、什么啦！", "小怜")

	print("=== 第三章第5话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
