# chapter3_ep15.gd - 第3章第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep15_script()

func play_script():
	pass

func chapter3_ep15_script():
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/parkingLot_night.png")
	await novel_interface.show_text_only("根据莉琉的指引，我们一路来到地下停车场的指定位置汇合。")
	novel_interface.show_character("ren_maid","gratified")
	await novel_interface.show_dialog("莉琉刚才通知我，那些人并没有追来，已经从另一个通道撤离了。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("我看看她的伤势……我学过一些急救。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔示意我让安妮平躺在一旁的台子上，开始检查她的脉搏和呼吸。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("还好没造成室颤，不过她现在呼吸很微弱，身上有多处灼伤，不知道内脏的损伤程度……", "拉斐尔")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("那群疯子，居然对一个女孩子做这种事！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("呐，这位小姐——", "贝阿特丽切")
	await novel_interface.show_dialog("你身边是不是经常出现一些小动物？\n比如——", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我们循着贝阿特丽切指的方向看过去，有两只鸽子在附近围着我们。")
	await novel_interface.show_dialog("咕咕——", "鸽子")
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("这有什么奇怪的，各种地方不都有这些动物吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","wail")
	await novel_interface.show_dialog("不不，这里是地下3层的停车场……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("所以呢？\n也很常见啊~", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("咕咕咕——", "鸽子")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("（……难道这位大小姐偏偏在这种事情上没有常识吗？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("治愈类的魔法确实会吸引小动物，如果本人并不自知的话……", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切将我拉到拉斐尔身边，分别拉着我们两人的手腕。")
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("来，试试看——", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","upset")
	await novel_interface.show_dialog("嗯？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切将我和拉斐尔的手扣在一起，并用自己的手掌牢牢的在外侧按住。")
	novel_interface.show_character("ren_maid","upset")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","normal1",0.25)
	await novel_interface.show_dialog("你做什么——？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("想不到这位大小姐的手意外的柔软\n而且还很温暖……")
	await novel_interface.show_text_only("不对，等等！\n我们这是在——")
	novel_interface.show_character("ren_maid","perspire1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","normal1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("牵手……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔满脸意外和愤怒的表情，瞪着我的眼睛简直可以喷出火来。")
	await novel_interface.show_text_only("我脑海中已经浮现出自己被她一边骂着死变态一边打得鼻青脸肿的情景了。")
	await novel_interface.show_text_only("突然拉斐尔好像感觉到什么，疑惑的看向了贝阿特丽切，而后者则朝她轻轻点了点头。")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔认真的闭起了眼睛，贝阿特丽切按住我俩的手也逐渐松开。")
	novel_interface.show_character("ren_maid","stare")
	await novel_interface.show_dialog("（诶？难道我的手很好拉吗？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然间，我感觉一阵轻松，仿佛全身都被一团温暖的光包围着。")
	await novel_interface.show_text_only("呼——\n第一次觉得地下停车场的空气也这么清新~")
	await novel_interface.show_text_only("而且不知为何，刚才那恐怖的情景在我心里造成的阴霾似乎也瞬间消散了。")
	await novel_interface.show_dialog("咳，咳——", "安妮")
	novel_interface.show_character("ren_maid","happy")
	await novel_interface.show_dialog("安妮？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在我的注视下，安妮身上的灼烧伤痕正在以不可思议的速度变淡并消退着。")
	await novel_interface.show_text_only("那种温暖的感觉渐渐消散，然后拉斐尔长出了一口气，睁开眼看着我们。")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("小怜，这是哪……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮好像刚睡醒一样，迷迷糊糊的看着我。")
	novel_interface.show_character("ren_maid","gratified")
	await novel_interface.show_dialog("我们安全的逃出来了，正在等莉琉汇合。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.show_dialog("为什么……", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","worry")
	await novel_interface.show_dialog("你……从没发现过吗？", "贝阿特丽切")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("拥有如此美妙治愈能力的魔女大小姐\n真是让人心动不已呢~", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","happy")
	await novel_interface.show_dialog("真的呢拉斐尔，我也感觉到了！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("……什么魔女……你们都在胡说些什么！", "拉斐尔")
	novel_interface.character_dark()
	await novel_interface.show_text_only("拉斐尔依然眉头紧锁。")
	novel_interface.character_light()
	await novel_interface.show_dialog("你刚才对我做了什么！\n她的伤怎么突然恢复了？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这位贵族大小姐的世界观正面临着巨大的冲击，我一时也不知该如何跟她解释。")
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("还有，那群攻击保安军的家伙是什么人？\n居然敢在这种地方使用异质物武器……", "拉斐尔")
	await novel_interface.show_dialog("一个已经死了几百年的人突然活过来，而我居然还戴着她的遗物。", "拉斐尔")
	await novel_interface.show_dialog("而且我还看到了……\n那种东西……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("回想起刚才的情景，拉斐尔的声音还有些颤抖。")
	await novel_interface.show_text_only("我又看向贝阿特丽切的脸，无暇精致的面容露出从容淡定的微笑。")
	await novel_interface.show_text_only("绿宝石又恢复了原样，贝阿特丽切将它交还给了拉斐尔。")
	await novel_interface.show_text_only("似乎刚才那恐怖的一幕与她毫无关连。")
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("《七哲人书》上的魔法会影响人的心灵……\n第一次看到，会感到恐惧也是正常。", "贝阿特丽切")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("不过恐惧是人类很重要的情感，了解自己的弱小才能在危机四伏的环境中生存。", "贝阿特丽切")
	await novel_interface.show_dialog("真正可怕的，是被恐惧所支配内心的人们……", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切像是回想起了往事，露出非常悲伤的神色。")
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("话虽如此，我还是希望自己从没打开过那本书，没许过那样的愿望。", "贝阿特丽切")
	await novel_interface.show_dialog("没有得到过那诅咒般的能力……", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","normal1")
	await novel_interface.show_dialog("诅咒？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("魔导书赋予了我一种……\n我自己也无法控制的『吸引异性』的魔法。", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("（原来……！）", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切说着转头望向我，用食指指尖轻触了一下我的喉咙。")
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("呐，可以问你个问题吗？", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("是……请说！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("beatrice_battle","smile2",0.25)
	await novel_interface.show_dialog("你叫小怜对吧？\n你很特别呢……", "贝阿特丽切")
	await novel_interface.show_dialog("你明明是女孩子，应该完全不受这种魔法的影响才对，但为什么……你总会偷看我呢？", "贝阿特丽切")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("被戳穿了！\n啊啊啊啊不要说出来啊！！！")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("不过……你又不会像那些男人一样陷入疯狂般的…\n完全失控。", "贝阿特丽切")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（是魔法的关系吗……）\n（不不不，刚才我已经完全失控了啊！！）", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("贝阿特丽切又用食指慢慢的勾起了我的下巴，然后轻轻的点了一下我的鼻尖。")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("我并不讨厌……不，应该说是，很可爱呢~", "贝阿特丽切")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,false)
	await novel_interface.show_text_only("我反射性的吞了吞口水。")
	await novel_interface.show_text_only("真的只是……魔法吗？！")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("很快，一辆疾驰而来的黑色加长SUV停在了我们面前。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("小怜、安妮，快上车！", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("你是叫贝阿特丽切吧？希望你也能跟我们一起走。", "莉琉")
	await novel_interface.show_dialog("如果自己对当年认识的人的经历感兴趣，我已经让人备好了全部可以查到的资料。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("那个暗恋你的诗人，之后可是写了一些流传至今的东西呢。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("好吧，我对你们这个小可爱也很感兴趣呢。", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("和贝阿特丽切视线相交，我的脸一下又涨红了……")
	await novel_interface.show_text_only("真、真的只是魔法吗？！！")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("拉斐尔还是先回酒店吧，那群人已经撤了，现在这里很安全。", "莉琉")
	await novel_interface.show_dialog("而且考察团要是发现你失踪了非得炸锅不可。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("我们带来了禁运品……还引起了这么大的骚动。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔看了看贝阿特丽切\n你带的禁运品已经变成一个大美女了，可喜可贺。")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("你就这么放我走了？", "拉斐尔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("作为交换，戴克斯博士已经同意未来一年内萨蒙顿的农产品会优先供给我指定的交易商。", "莉琉")
	novel_interface.change_2nd_expression("speak2")
	await novel_interface.show_dialog("相应的，他老人家也会对我在第二学园都市期货交易所的行为睁一只眼闭一只眼。", "莉琉")
	await novel_interface.show_dialog("相关协议已经躺在我的办公桌上了，你尽管放心，SID可不会做赔本的买卖~", "莉琉")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("等等！你让我们出生入死是为了赚钱吗！？")
	novel_interface.character_light(0.35,"thinking")
	await novel_interface.show_dialog("哼——", "拉斐尔")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("好吧，我也答应你，在我没弄清楚一些事之前，今天的事情我不会告诉任何人。", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("和戴克斯家的人打交道真是愉快~", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("小怜，等回到萨蒙顿，我绝对会把所谓魔力之类的事调查清楚的。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","happy")
	await novel_interface.show_dialog("嗯！我觉得拉斐尔身上拥有非常了不起的力量~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔刚想转身离去，忽然停下来\n将她的绿宝石挂坠取下来扔给了我")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("这是你们家族的藏品吧，怎么能……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("现在是你的了。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("真是个有魄力的小姑娘，长大以后一定会成为出色的女人。", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("哼，你的底细我也会调查清楚的。", "拉斐尔")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("那么各位，再见了。", "拉斐尔")

	print("=== 第3章第15话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
