# chapter3_ep08.gd - 第3章第8话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep08_script()

func play_script():
	pass

func chapter3_ep08_script():
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_centreSpace1.png")
	await novel_interface.show_text_only("我忐忑地带着拉斐尔参观校园。")
	await novel_interface.show_text_only("没想到接近任务目标的这一步骤进行起来如此顺\n利。")
	await novel_interface.show_text_only("挖空心思筹备欢迎仪式却被放了鸽子的副校长，正猫在我们身后不远的地方，恨恨的咬着手帕。")
	await novel_interface.show_text_only("而这位大小姐，虽然并没有多么满意的样子，但心情似乎比刚才好了不少。")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("这就没有了吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("嗯？你是说参观内容吗？", "小怜")
	await novel_interface.show_dialog("再往那边就是校园外的商业区了……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("这里很多设计是仿照战前的知名建筑，试图提升自己的文化底蕴。", "拉斐尔")
	await novel_interface.show_dialog("然而园区面积太小，各种风格的建筑之间没有缓冲和过度的区域。", "拉斐尔")
	await novel_interface.show_dialog("在这种地方，你们不会感到郁闷吗？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("新丰洲是在废墟上重建的城市，本来就没留下多少有历史底蕴的建筑。")
	await novel_interface.show_text_only("而且在防护力场内这种寸土寸金的地方，如此的占地面积真的是相当奢侈了。")
	await novel_interface.show_text_only("突然被这么说，总觉得有些不爽……")
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("唔……", "小怜")
	await novel_interface.show_dialog("你应该就是来自第四学园都市的拉斐尔·戴克斯小姐吧？", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("既然这么看不上这里，为什么还来参观啊？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("哦？你知道我是谁啊。", "拉斐尔")
	await novel_interface.show_dialog("哼，要不是爷爷想安排我到其它学园都市留学……", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("像这种只知道模仿，没有神髓的地方——我连踏进一步的想法都不会有！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.show_dialog("（所以是不满意家里人的安排而心生怨气嘛……）（这么简单的事情说清楚不就好了！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("真是糟糕，被她一说，我也觉得学校里的建筑风格有点开始变得别扭不自然了。")
	await novel_interface.show_text_only("真是有毒的点评，快点忘掉！！")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("哎呀呀，既然对家人的安排这么不满意——", "倪克斯")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("为什么不直接说出自己的想法呢？", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯学姐从我们身后逐渐走过来，身姿还是那么优雅自然。")
	await novel_interface.show_text_only("学姐和拉斐尔眼神相遇的一瞬，我仿佛听到了高压放电击穿空气的声音。")
	await novel_interface.show_text_only("是……错觉吧？")
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("你又是谁？", "拉斐尔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_normal","smile",0.25)
	await novel_interface.show_dialog("我只是这所学校里，一名普通的学生罢了。", "倪克斯")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("倒是这位贵族大小姐，从刚才起，就对我们学校充满鄙夷呢。", "倪克斯")
	await novel_interface.show_dialog("既然这样，为什么还要纡尊降贵地来这里呢？是家族的压力吗？", "倪克斯")
	novel_interface.character_light(0.35,"angry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我和我家里的关系，不用你来指手画脚吧？", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("所以说到头，你根本就是不敢违抗父母命令的任性小孩——", "倪克斯")
	novel_interface.change_2nd_expression("sad")
	await novel_interface.show_dialog("又凭什么自认为高人一等，对给你免费当向导的人的校园指指点点呢？", "倪克斯")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"subtle")
	await novel_interface.show_dialog("哈？！我什么时候说过高人一等的话了？", "拉斐尔")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("喂，女装癖，我有说过那种话吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("倒也不算啦……", "小怜")
	await novel_interface.show_text_only("可恶，谁是女装癖啊！")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("你看，我明明没说过。", "拉斐尔")
	await novel_interface.show_dialog("而且话说回来，你脖子上戴的那个……", "拉斐尔")
	novel_interface.change_expression("jeer")
	await novel_interface.show_dialog("上学还戴着这种东西，真的没问题吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("其实我们学校没有禁止戴首饰的规定啦……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("而且学姐的项圈明明很可爱！")
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("虽然故意用低反光材料嵌底……战前从动荡的宫廷流出碎裂成了三块的『奥尔洛夫黑钻』。", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("实际价格能换这里几栋教学楼了吧？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("——啥！！？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("你不会还装出一副替平民发声的样子，想让这个女装笨蛋以为你和她是一边的吧？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_normal","normal2")
	await novel_interface.show_dialog("……", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("谁是女装笨蛋啊！！")
	await novel_interface.show_text_only("还有倪克斯学姐为什么突然露出心虚的样子啊？！")
	novel_interface.show_character("nyx_normal","normal2")
	await novel_interface.show_dialog("我只是戴了与自己相称的饰品而已。", "倪克斯")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("反而是你，又想表现得自由独立，又在仗着家族蒙荫趾高气昂的样子，真是太可笑了。", "倪克斯")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","mock",0.25)
	await novel_interface.show_dialog("我记得那三块黑钻后来落到了黑手党教父手里，用黑钱买的黑钻，真是和你很相称呢。", "拉斐尔")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不像您的家族，用垄断的粮食贸易带来的财富和贵族地位，连衣服都这么郁郁葱葱的。", "倪克斯")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("谁让只有我们的作物可以预防『黑缕病』呢，总不能像你一样，切开都是黑的。", "拉斐尔")
	novel_interface.character_light(0.35,"mock")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("明明用饥饿威胁着全世界，还宣扬着什么人不能失去信仰，你们平时不探究一下自己的灵魂吗？", "倪克斯")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"jeer")
	await novel_interface.show_dialog("我的灵魂不需要你这种人来探究，那绝对会成为我人生的污点。", "拉斐尔")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("哎呀真巧，我也不想踩到垃圾堆里研究废物的真实形态呢。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("下午的阳光温暖地洒在我们三人身上。")
	await novel_interface.show_text_only("我站在二人中间，看着两位似乎都很不得了的少女斗嘴，全然不知如何劝架。")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("（你们两位，真的是第一次见面吗？）", "小怜")
	await novel_interface.show_dialog("（真的不是从小到大的仇人吗？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("远处的副校长已经紧张的昏厥过去，被抬走了。")
	await novel_interface.show_text_only("算了，反正莉琉让我打听的情报已经到手了。")
	await novel_interface.show_text_only("……就不要在意了吧？")

	print("=== 第3章第8话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
