# chapter3_ep03.gd - 第三章第3话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep03_script()

func play_script():
	pass

func chapter3_ep03_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("难道……你打算把那个人相关的第三方资料都清除掉吗？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("不，正好相反，我会加入更多的信息。", "莉琉")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("什么？！", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉小姐露出了令人不寒而栗的笑容。")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("目前关于劫匪的情报，只基于由一段不甚清晰的录像而已。", "莉琉")
	await novel_interface.show_dialog("那么在全世界，与那张平庸无奇的面孔相似的人有多少个呢？", "莉琉")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("等一下，平庸无奇这四个字也太伤自尊了吧！")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("可就算会有人和“我”长得差不多，但稍微调查一下就能分清楚吧？", "小怜")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("那个人在当天去了哪里做了什么，只要调取监控录像就一目了然了。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("是啊，想调查一个真实存在的人并不是件难事。", "莉琉")
	novel_interface.change_2nd_expression("speak2")
	await novel_interface.show_dialog("但如果调查对象中有些人并不存在呢？", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你是说……", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0)
	await novel_interface.show_dialog("一群与嫌疑人面部重合度极高的伪造目标，他们就算搜寻到世界毁灭也不可能真的找到那些人。", "莉琉")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("而除了我们以外，在其他人看来，那些人和●●●●一样，都是离奇消失的失踪人口罢了。", "莉琉")
	novel_interface.change_2nd_expression("speak2")
	await novel_interface.show_dialog("这样要怎样才能分辨出，谁才是真正的目标呢？", "莉琉")
	await novel_interface.show_dialog("让桌上的米粒消失有两种办法，要么一粒粒的把米拿走，要么就在桌面上撒一整袋同样品种的米。", "莉琉")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ren_battle","upset",0.25)
	await novel_interface.show_dialog("听起来是个浩大的工程啊……", "小怜")
	novel_interface.character_2nd_light()
	novel_interface.character_dark()
	await novel_interface.show_dialog("让简单的事情变得复杂起来，让国民们认为他们缴纳的税费派上了大用场，才能让大家都幸福嘛。", "莉琉")
	novel_interface.character_2nd_dark()
	novel_interface.character_light(0.35,"stare")
	await novel_interface.show_dialog("每次听到你这样的言论都想报警。", "小怜")
	novel_interface.character_2nd_light(0.35,"normal1")
	novel_interface.character_dark()
	await novel_interface.show_dialog("话说回来，关于你原来的身份资料，我在核对的时候发现了矛盾之处。", "莉琉")
	novel_interface.character_2nd_dark()
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("哎？是什么？", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("你的父母。", "莉琉")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("当听父母这个词，我的心忽然一沉。")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("按照你的说法，母亲很早就去世，父亲失踪。", "莉琉")
	await novel_interface.show_dialog("就算这些是你不愿提及的回忆，但事出蹊跷，我还是想跟你核对清楚。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","upset",0.25)
	await novel_interface.show_dialog("好……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉调出了事先备份的我曾经的数据。")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("这里显示的内容是，母亲：2026年7月25日，\n『大灾难日』当天失踪，推测死亡。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Shot/seabed.png")
	await novel_interface.show_text_only("新丰洲西北侧海底的废墟，在『大灾难日』前曾是一座繁华的都市。")
	await novel_interface.show_text_only("我对那里只有很模糊的记忆了……")
	await novel_interface.show_text_only("那座都市被神迹武器毁灭的同时，埃癸斯系统的防护力场展开，新丰洲恰好处于力场的边缘。")
	await novel_interface.show_text_only("而且……那次事件是『七年战争』的开端。")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("父亲，2026年12月起行踪不明，推测……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("停一下……拜托了。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我讨厌那个冰冷冷的——推测……死亡。")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("父亲他可能，还活着……\n我一直这么想。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("……嗯，儿子长成了一个大美人，他老人家一定会感到欣慰呢。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我被莉琉意外的发言逗笑了\n讨厌，明明是在挖苦我。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("好啦，你先看这里。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉点开了属于我父母的记录，上面有两行编号。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("在这上面记载的内容——", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("母亲，编号离线\n父亲，编号离线")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("……有什么问题吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("如果你母亲是在埃癸斯展开前或者在防护力场范围外遇难的话，埃癸斯内是不会有她的编号的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("哎……？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉小姐若有所思地看着我。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("你也不清楚吗？\n应该不是记录问题，我会继续调查的……", "莉琉")

	print("=== 第三章第3话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
