# chapter3_ep07.gd - 第3章第7话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep07_script()

func play_script():
	pass

func chapter3_ep07_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_lawn.png")
	await novel_interface.show_text_only("距离莉琉给我交代任务过去了两天。")
	await novel_interface.show_text_only("就在昨晚，这支打着“艺术交流”旗号的考察团终于抵达了新丰洲国际机场。")
	await novel_interface.show_text_only("我的任务也要开始了吧？")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("不过我去套话……真的没问题吗？", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("说到底，对方是名门望族的大小姐，万一根本不搭理我怎么办？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("classmate_1")
	await novel_interface.show_dialog("看那边那个人的衣服，不是我们学校的人吧？", "同学甲")
	await novel_interface.hide_character()
	novel_interface.show_character("classmate_2")
	await novel_interface.show_dialog("身边还跟着一个时刻站的笔直的随从，是谁家的大小姐吗？", "同学乙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我顺着她们的视线望了过去，看见一位身姿修长穿着绿色外套的少女正站在草坪外。")
	await novel_interface.show_text_only("居然就是这次的目标——拉斐尔·戴克斯。")
	await novel_interface.show_text_only("刚才还看到副校长礼仪队正在大门外准备欢迎仪式，她就这么偷偷溜进来了？")
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("小姐，请这边走。", "随行人员")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("这幢教学楼是仿照了黄金时期的都铎式风格吧。", "拉斐尔")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("可惜庭院的格局太小，完全无法体现出空间的厚重感。", "拉斐尔")
	await novel_interface.show_dialog("护墙板上的雕刻也不够精美，根本没有达到结构和装饰的双重作用。", "拉斐尔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("servent","",0.25)
	await novel_interface.show_dialog("拉斐尔小姐果然对艺术有着非同常人的品位呢！", "随行人员")
	await novel_interface.show_dialog("像这样的建筑就应该把中厅的高度再增加一些才对啊。", "随行人员")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你说什么呢？\n一味地提升高度解决不了问题。", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("是啊是啊，如果能把庭院的草坪面积再加大一些就好了。", "随行人员")
	novel_interface.character_light(0.35,"mock")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哈？那样不就显得太突兀了吗？\n毕竟教学楼前面的花园也只有这么一点面积………", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("在拉斐尔小姐的眼里，像这种园艺缺乏规划植被凌乱的地方，连花园也称不上吧？", "随行人员")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("听到这样的话语，拉斐尔似乎有些不太满意。")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("……我才没有这么认为。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0)
	await novel_interface.show_dialog("啊——！\n拉斐尔小姐实在是很平易近人呢！", "随行人员")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("那位仪态标准的随行人员，你还没发现旁边那位大小姐的脸色已经越来越难看了吗？")
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("喂，那边的女装癖。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("……啊嘞？！", "小怜")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("（女装癖……是在说我吗？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("周围的人顺着拉斐尔的声音，齐刷刷的将目光转向了我。")
	await novel_interface.show_text_only("瞬间被这么多人围观，我感觉脸上一阵火热。")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("不，我不是、我没有……！\n（这件制服，是莉琉逼我穿的！）", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","jeer",0.25)
	await novel_interface.show_dialog("吞吞吐吐的像个男人吗？", "拉斐尔")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("真是的，原来新丰洲市已经开放到连你这种癖好也可以公然示在大众面前了啊。", "拉斐尔")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("莉琉，我现在拒绝这个任务，还来得及吗？")
	novel_interface.character_move_left(-0.3)
	novel_interface.character_2nd_move_left(0,0.3,false)
	novel_interface.show_3rd_character("classmate_1","",0.3)
	await novel_interface.show_dialog("那个……小怜是我们的同学喊，她就是女生啦。", "同学甲")
	await novel_interface.hide_character()
	await novel_interface.hide_3rd_character()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("什么？\n怎么可能？", "拉斐尔")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("拉斐尔露出了权威被挑衅的神色。")
	novel_interface.show_character("classmate_2")
	await novel_interface.show_dialog("我没有骗你啊，我们都可以作证的。\n小怜绝对是真正的女孩子！", "同学乙")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然很想感谢这位仗义执言的同学，但我绝对不是真正的女孩子。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("……啧，我还以为是个男人呢。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("我哪、哪里像男人了啊……\n（不、不对……）", "小怜")
	novel_interface.change_expression("upset")
	await novel_interface.show_text_only("啊——背叛自己的滋味，是这样的酸涩吗。")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","normal2",0.25)
	await novel_interface.show_dialog("算了，不跟你计较了。", "拉斐尔")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("你觉得这里的建筑水平怎么样呢？", "拉斐尔")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("建筑学什么的我完全不了解，就算你问我……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("你按照直觉回答就好了。", "拉斐尔")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("唔，作为教学楼来说，中厅的高度已经不算特别低了吧。", "小怜")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("会让你感到不顺眼，或许是因为……不够可爱？", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("我一边观察着拉斐尔的神色，一边为自己贫乏的词汇量自责。")
	await novel_interface.show_text_only("果然不出所料，她的脸上露出了轻蔑的笑容。")
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("可爱？！真是难以相信，居然会有人用这么肤浅的词汇来形容建筑。", "拉斐尔")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("只、只是一种感觉啦！", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("我是说树木的排列如果不那么整齐，可能就会好一点。", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("呃……\n比如……嗯……", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_text_only("所以说为什么要问我啊！")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("你是想说让树阵层次错落的交替布置，让视野纵深加强吧？", "拉斐尔")
	novel_interface.character_light(0.35,"sprite")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是。\n（您刚才在说什么？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,false)
	await novel_interface.show_text_only("拉斐尔听到这，终于露出了一点笑容。")
	novel_interface.character_2nd_light(0.35,"jeer")
	await novel_interface.show_dialog("虽然是个女装癖，但比这个只知道附和的家伙有用多了。", "拉斐尔")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("所以说我不是……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("大小姐……", "随行人员")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("好了，你可以去外面等我了。", "拉斐尔")
	novel_interface.change_expression("jeer")
	await novel_interface.show_dialog("你叫小怜？走吧，快点迫不及待地过来跟我炫耀一下这所学校的优点吧。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("诶……？\n好、好的！", "小怜")

	print("=== 第3章第7话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
