# chapter3_ep09.gd - 第3章第9话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep09_script()

func play_script():
	pass

func chapter3_ep09_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/diningRoom1.png")
	await novel_interface.show_text_only("昨晚开始，SID侦测到『天空酒店』的位置出现了数起间歇性的时空相位波动。")
	await novel_interface.show_text_only("巧合的是，萨蒙顿的考察团也于昨晚全员入住了这座地处『协约非武装区』的豪华酒店。")
	await novel_interface.show_text_only("今晚他们还要在酒店举行艺术品交流晚宴，并邀请了各个学园都市的名流。")
	await novel_interface.show_text_only("但拉斐尔和她的随从却没有出现在晚宴的名单上。")
	await novel_interface.show_text_only("——因此，我和安妮再次被莉琉派到了这个麻烦的地方执行任务。")
	await novel_interface.show_text_only("在富丽堂皇的宴会厅门口，我有些局促不安。")
	novel_interface.show_character("ren_maid","shy")
	await novel_interface.show_dialog("唔……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","smile",0.25)
	await novel_interface.show_dialog("怎么啦，你看上去很紧张呀？", "安妮")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("当然会紧张吧，这可是女仆装诶！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("没错，今晚我和安妮是以伪装身份潜入的会场。")
	novel_interface.show_character("ren_maid","awkward")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("而且为什么你是御樱川的学生会代表，我就是服侍宾客的女仆啊！！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("女仆装不是男人的梦想吗？", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"perspire1")
	await novel_interface.show_dialog("梦想里绝对不包括“自己穿女仆装”这项吧~！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("唔……\n也是呢~", "安妮")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("明明打扮的这么可爱，却无法欣赏到自己的身姿\n难怪你如此急躁………", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮退后几步，拿出手机\n“咔嚓”一下拍了张照片。")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("嗯……果然双马尾也很合适小怜呢。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","awkward")
	await novel_interface.show_dialog("不要拍啊——快删掉！", "小怜")
	await novel_interface.show_dialog("（这种羞耻的……）\n（万一被……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮的手机传出了信息发送成功的音效。")
	novel_interface.show_character("ren_maid","awkward")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("已经发给你和莉琉啦~", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("完蛋了。")
	novel_interface.show_character("ren_maid","awkward")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","smile",0.25)
	await novel_interface.show_dialog("嘿嘿，别害羞嘛~\n这种荷叶边和小怜的风格超级搭的！", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"shy")
	await novel_interface.show_text_only("我拿出手机，看到安妮发来的照片。")
	await novel_interface.show_text_only("似乎还……不错？")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("才、才没有嘞！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("此时，耳机里传来了熟悉的声音。")
	await novel_interface.show_dialog("好啦，小姑娘们的自拍时间到此为止，目前的状况你们都了解了吧。", "莉琉")
	await novel_interface.show_dialog("因为第四学园都市向联合议会的申请，今晚酒店周围的保安军戒备森严。", "莉琉")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("总之查明相位波动的原因就立刻撤离对吧？\n我知道啦~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("这回我不能像上次那样硬来了，所以你们俩都给我机灵点，尤其是小怜——", "莉琉")
	await novel_interface.show_dialog("打扮的这么可爱，万一被抓到了，说不定会被某个权贵看上拉回自己府内……", "莉琉")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("你够了喂！！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	await novel_interface.show_dialog("啊，那边萨蒙顿教育委员会的代表在叫我\n正好趁机去偷听一下谈话。", "安妮")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("小怜你也去找找机会吧！", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,false)
	await novel_interface.show_text_only("话音刚落，安妮就换上一幅商业笑容\n转身向几个穿着礼服的男人挥手然后跑过去了。")
	novel_interface.character_light(0.35,"upset")
	await novel_interface.show_dialog("安妮还真是得心应手啊……", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("可是女仆到底该做些什么啊？", "小怜")
	await novel_interface.show_dialog("这个酒盘，有点不好掌握平衡……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("请给我一杯Dom Perignon，谢谢。", "客人甲")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("啊？……好的！马上来！\n唔……请麻烦您再说一次，那个叫什么名字？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……", "客人甲")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("（糟糕，我好像问了很蠢的问题……）\n唔，呃……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没有接受过女仆的职业培训，我完全不知道这种时候该怎么应付啊。")
	await novel_interface.show_dialog("啧啧，明明是以女仆为特色的宴会厅\n居然这么不专业的吗？", "客人甲")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("对不起，那个……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("喂喂，你傻乎乎地戳在这发什么呆呢？", "粉色头发的女仆")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("啊？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我扭过头，面前出现一位粉色头发、长相清秀、戴着红框眼镜的女仆。")
	await novel_interface.show_text_only("她得体礼貌地向客人微笑了一下，在将脸转向我的瞬间表情迅速转为了愤怒。")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("快跟我去给客人取香槟！", "粉色头发的女仆")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_maid","perspire1",0.25)
	await novel_interface.show_dialog("诶？你是……？\n（这身装扮看起来好像不是这家酒店的………）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("粉色头发的女仆不由分说地拉起我的手走向没人的角落，我才发现她的力量大得惊人。")
	novel_interface.show_character("fabiola_maid","perspire")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_maid","perspire1",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("瞧你笨手笨脚的样子，一点都不专业！", "粉色头发的女仆")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("那、那个……我……", "小怜")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_text_only("对不起，我刚上任不到一个小时！")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_text_only("等等，明明你说话的语气也不像女仆啊……")
	novel_interface.character_light(0.35,"mock")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你那是什么眼神？\n难道是在质疑我身为女仆的权威吗？", "粉色头发的女仆")
	novel_interface.change_expression("confident")
	await novel_interface.show_dialog("你听好了——在我的主人面前，我绝对是万能的女仆！这一点任何人都不准怀疑。", "粉色头发的女仆")
	novel_interface.character_dark()
	await novel_interface.show_text_only("红框眼镜突然做出了自豪的宣言。")
	novel_interface.character_2nd_light(0.35,"perspire1")
	await novel_interface.show_dialog("好、好的……", "小怜")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("不管怎么说，刚才多谢你替我解围……\n要不然还真不知道怎么下台。", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal")
	await novel_interface.show_dialog("喂——所以说，你为什么会到这里来？", "粉色头发的女仆")
	novel_interface.character_dark()
	await novel_interface.show_text_only("面前的人突然语气严肃起来\n透出一丝寒气")
	novel_interface.character_light(0.35,"mock")
	await novel_interface.show_dialog("敢撒谎的话，我就把你烧成焦炭哟！", "粉色头发的女仆")
	novel_interface.character_dark()
	await novel_interface.show_text_only("红框眼镜一边威胁我，一边露出了爽朗的笑容，给人的感觉完全不像是在开玩笑！")
	novel_interface.character_light()
	await novel_interface.show_dialog("怎么？是在想着怎么编谎话吗？", "粉色头发的女仆")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("（糟糕，我的身份暴露了吗？）\n（她……到底是什么人啊！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","confident")
	await novel_interface.show_dialog("我可知道你的身份啦——\n毕竟……", "粉色头发的女仆")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("skuld","normal",0.25)
	await novel_interface.show_dialog("法贝拉，不能无礼哟。", "？？？")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("我循声望去，打断我们的，是一个穿着礼服式法兰裙袍的金发女孩。")
	await novel_interface.show_text_only("身姿娇小的少女，一头阳光般的金发编成的辫子乖巧的直落到腰间，眼神也如湖水般清澈明亮……")
	await novel_interface.show_text_only("这个精灵般的少女，不同凡俗的气质和眼前骄奢的宴会场显得有些格格不入。")
	novel_interface.character_light(0.35,"panic")
	await novel_interface.show_dialog("斯库尔德小姐！\n真的非常抱歉，居然让这种小事惊动了您。", "法贝拉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("刚才还凶神恶煞的女仆，居然在见到这个小女孩的时候，态度变得这么恭敬。")
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("你看她都不敢说话啦，一定被你吓坏了。", "斯库尔德")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("总之今天就先放过她吧，好不好？", "斯库尔德")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("遵命。", "法贝拉")

	print("=== 第3章第9话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
