# chapter3_ep16.gd - 第三章第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep16_script()

func play_script():
	pass

func chapter3_ep16_script():
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	await novel_interface.show_text_only("距离天空酒店的异变已经过去了一周。")
	await novel_interface.show_text_only("爱衣博士用构成手提箱外壳的那种异质物金属，为贝阿特丽切制作了一个小巧的手环。")
	await novel_interface.show_text_only("她现在终于可以选择性的开启或关闭那种能影响周围男性大脑的魔法效果了……谢天谢地。")
	await novel_interface.show_text_only("作为交换条件，贝阿特丽切像安妮一样，以探员的身份正式加入了SID。")
	await novel_interface.show_text_only("莉琉安排她住进了这套豪华公寓还空着的几间客房之一里。")
	await novel_interface.show_text_only("原本我还担心，保安军在调查的时候会从监控录像中发现活动在行政楼层的我们几个。")
	await novel_interface.show_text_only("但不知为何，无论是我们还是雅各那伙人，都没有留下任何影像证据。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("莉琉，SID的权力究竟有多大啊？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","normal",0.25)
	await novel_interface.show_dialog("嗯……？为什么突然问这个？", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这次牵涉到了好几个学园都市，我还以为扫尾工作会很麻烦，没想到这么顺利。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("虽然你相信SID的情报操作能力我很高兴……", "莉琉")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("但这次你和安妮能全身而退，肯定离不开元老院在联合议会的影响和活动。", "莉琉")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("不过基尔斯博士一贯都是保密主义，我也无法完全掌握那个老面瘫都做了什么。", "莉琉")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（老……面瘫？）\n元老院的情报不和SID共享的吗？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("傻孩子……", "莉琉")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("自情报组织诞生起，就从不会与本国元首或者统治者完全共享情报。", "莉琉")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("诶——真的！？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("所谓信息即权利，Knowing is Owning.", "莉琉")
	await novel_interface.show_dialog("元老院是新丰洲各种权利的整合者，而SID和元老院则是基于天然立场的合作关系。", "莉琉")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("那么，你会把公司机密无偿交给合作伙伴吗？", "莉琉")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("唔…当然不会啦……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("那么如果对方的机密很有价值，你很想知道呢？", "莉琉")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯……\n收买一个清洁工？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("没错，只要对方机构人数足够多，再严格的安保协议也可以被社会工程学击破。", "莉琉")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那……那照这个说法，难道SID内部也有间谍？！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("我们有上万名工作人员，肯定有不少渗透人员——来自元老院、外国情报机构的和各种组织的。", "莉琉")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("所以只要控制好关键情报的流通范围就可以了。", "莉琉")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那『象牙大厅』里该不会也有……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("这就不用你操心了，元老院的地盘可不是凭你这种天真的想法可以渗透的。", "莉琉")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("元老院成员都是异质物研究领域的权威，SS级的科学家只是最基本的要求。", "莉琉")
	await novel_interface.show_dialog("他们有不少实验性的异质物道具，你偷偷溜进去或许被洗了脑都不知道。", "莉琉")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("但这次的事件……就是很多疑点啊。", "小怜")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("比如萨蒙顿考察团的人为什么会将黄金蝴蝶偷运到新丰洲？", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("拉斐尔的那个项链款式很有年代感，她本人也似乎并不喜欢，平时都戴在衣服里面。", "小怜")
	await novel_interface.show_dialog("以她的性格…应该直接根本不会戴才对……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("确实，黄金蝴蝶的特性类似感染性模因类异质物，在平时用卡车那么大的屏蔽设备收容都不过分。", "莉琉")
	novel_interface.change_2nd_expression("angry")
	await novel_interface.show_dialog("他们却强行塞进一个手提箱里，结果逸散出来的能量连卫星都能侦测到。", "莉琉")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("而且真想偷运的话，也不用让官方人员运送\n他们为什么要冒这么大的政治风险呢？", "莉琉")
	novel_interface.character_light(0.35,"solemn")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("或许并不存在这种风险，或许是某些可以给他们保证的人要求他们这么做的……", "小怜")
	await novel_interface.show_dialog("考察团人员的随身行李不需报关，还特意选择了我们没有管辖权的地区的酒店。", "小怜")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("难道说……！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("你终于猜到了吗？", "莉琉")
	novel_interface.character_light(0.35,"solemn")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是元老院要求萨蒙顿这么做的？\n就是为了把SID排除在信息圈外……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("那个雅各是第四学园都市的人，从伊露卡的资料看来，他们研究魔女有一段时间了。", "莉琉")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("黄金蝴蝶也与魔女有关，并且雅各还想横插一杠\n如果将这两件事结合起来的话……", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("七年战争中出现过的，希望控制特殊力量的声音又会再次抬头了吗？")
	novel_interface.show_character("ren_battle","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_research","normal",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那今后会出现更多的被制造出来的魔女吗……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("看来，我们要为这场桌面之下的较量提前做好准\n备。", "莉琉")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_centreSpace1.png")
	await novel_interface.show_text_only("几周后")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("哈——好困~~\n昨晚在游戏里刷人马刷到没电……", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("喂，女装癖。")
	novel_interface.character_light(0.35,"wry_smile")
	await novel_interface.show_dialog("？？？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("似曾相识的声音……")
	await novel_interface.show_text_only("似曾相识的地点……")
	await novel_interface.show_text_only("似曾相识的称谓……")
	await novel_interface.show_text_only("出现在我面前的，果然是那个……")
	await novel_interface.show_text_only("毒舌又难缠的大小姐——拉斐尔！")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("拉、拉斐尔？\n你怎么来了？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("这所学校对礼仪方面的教导，居然如此忽视吗？", "拉斐尔")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("你现在应该称呼我为拉斐尔学姐。", "拉斐尔")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哎？！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔这么一说，我才意识到……\n她手上拿着书包，还穿着二年级的制服鞋。")
	novel_interface.show_character("ren_uniform","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","mock",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你不是很嫌弃这所学校……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("如果可以的话，我才不愿意来这里呢\n但贵国似乎也没什么像样的学校了~", "拉斐尔")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("而且既然我是魔女，还是来这里最适合。", "拉斐尔")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("不愧是拉斐尔，这么短的时间就调查到这种程度并坦然的接受了。")
	novel_interface.character_light(0.35,"upset")
	await novel_interface.show_dialog("你家里人……知道魔女这件事吗？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("这种小事，没有让他们徒增烦恼的必要。", "拉斐尔")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("不要把成为魔女说得像成为超市会员一样轻松啊！")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("只是因为一次无聊的采访，他们就想让我出国一段时间避开舆论的风头。", "拉斐尔")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("要是被他们知道了魔女的事，大概会像听到我去纹身了一样慌张得晕过去吧。", "拉斐尔")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("不不不，完全不是一个量级的事情！！！\n但你要是真的去纹身了的话，请务必给我看看！")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("你……到底做了什么惊世骇俗的发言啊？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("你是土著人吗？那段采访应该已经被不少无聊的家伙转载得遍布网络了吧？", "拉斐尔")
	novel_interface.character_light(0.35,"uneasy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("要说这一点我可不会输给你哦——\n我还是全球通缉犯呢……")
	novel_interface.character_dark()
	await novel_interface.show_text_only("不过最近沉迷NiS主机的《绿帽勇者》，确实错过了不少大新闻。")
	novel_interface.character_light(0.35,"stare")
	await novel_interface.show_dialog("别用这种目光看着我啊……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我拿出手机刷新闻，拉斐尔的大名果然在热搜榜的前列。")
	await novel_interface.show_text_only("随意点开其中一个视频，拉斐尔的声音传了出来。")
	await novel_interface.show_dialog("为什么总有人认为，只要向神祈祷就能够获得救赎呢？不过是摇尾乞怜般的寻求自我安慰罢了。", "拉斐尔")
	await novel_interface.show_dialog("……废物不管到哪都是废物，为什么国家要养着这种人？让他们烂死在淤泥里成为肥料就好了。", "拉斐尔")
	await novel_interface.show_text_only("作为萨蒙顿总督的孙女，这还真是爆炸性的发言\n啊！")
	novel_interface.show_character("ren_uniform","speechless")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","worry",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我记得萨蒙顿是全民信仰宗教的福利国家吧……\n居然敢说这种话，你真是太有勇气了。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("有那么多人以神的名义挑起战争，我有什么理由不敢说这些话呢？", "拉斐尔")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("战争？你是说……七年战争？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("当然是新的战争啊！", "拉斐尔")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("萨蒙顿只宣扬人要有信仰，其实对所有信仰都是包容的态度。", "拉斐尔")
	await novel_interface.show_dialog("但因为战后的大移民，各种专收废物的白痴团体纷纷贪得无厌的要求更多的利益与权利。", "拉斐尔")
	novel_interface.change_2nd_expression("angry")
	await novel_interface.show_dialog("爷爷真是对他们太宽容了，那些好吃懒做的废物就应该送到屠宰场去……", "拉斐尔")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不要突然说出这么恐怖的话啊……", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("……倒是你，明明身处这场异变的中心，却根本不会在意吗？", "拉斐尔")
	novel_interface.change_2nd_expression("thinking")
	await novel_interface.show_dialog("大概也只有你这样的蠢货，才能生活得这么阳光幸福了吧。", "拉斐尔")

	print("=== 第三章第16话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
