# chapter3_ep06.gd - 第3章第6话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep06_script()

func play_script():
	pass

func chapter3_ep06_script():
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	await novel_interface.show_text_only("从总部离开时，除了写满知识点的小册子，莉琉还将那位贵族大小姐的影像资料发到了我的手机。")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("拉斐尔·戴克斯，生于萨蒙顿的名门望族，祖父是蒙顿基因发展公司的主席托马斯·戴克斯博士。", "小怜")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("哇——这不是教科书上出现过的人物吗？\n不过，怎么有一种怪怪的感觉……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("抓到了一个落单的美少女！")
	await novel_interface.show_text_only("一双手从背后楼住了我的身体。")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("哇啊——！", "小怜")
	await novel_interface.show_dialog("……搞什么嘛，是爱衣啊。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉严格规定，要我每次进出异变区域都要接受爱衣的全面检查和修复。")
	await novel_interface.show_text_only("虽然很不想承认，但爱衣制造的造型像机器章鱼一样的仪器确实很有助于伤口恢复。")
	await novel_interface.show_text_only("更不想承认的是，我似乎已经对她这样那样乱来的举习以为常了……")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("什么嘛，一脸失望的表情！\n你这孩子，太让人受伤了。", "爱衣")
	await novel_interface.show_dialog("上次从变电所回来以后都没有好好照顾过你……", "爱衣")
	novel_interface.change_expression("dizzy")
	await novel_interface.show_dialog("所以我决定，现在就要带你去学校——\n进行爱的教育！", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("诶？等等——！", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("别这么拉我的衣服，这是在街上啊！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/School/BG_School_heathRoom.png")
	await novel_interface.show_text_only("我忽然回想起，刚才莉琉叫我回家的时候小心的大概就是这个家伙……")
	await novel_interface.show_text_only("我被爱衣一路拉到保健室，只能乖乖的躺在内部休息室的床上。")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("只是检查嘛……每次都说的那么吓人。", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_think",0.25)
	await novel_interface.show_dialog("你好像有点失望呢，果然应该加一些特殊项目吗？", "爱衣")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不！麻烦你！\n就做普通的体检就好！", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("（而且你的流程已经非常特殊了！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣和往常一样把她那架古怪的仪器搬了出来，成像仪上跳跃着难以理解的复杂图像。")
	await novel_interface.show_text_only("我躺在床上无聊，就拿出手机继续查看拉斐尔的资料。")
	await novel_interface.show_text_only("屏幕上的拉斐尔一头深灰色的长发，淡紫色的瞳孔明亮通透，仿佛能洞穿人心。")
	await novel_interface.show_text_only("看着她的照片，我感觉到自己的心脏忽然猛烈的跳动，全身也随之颤抖起来。")
	await novel_interface.show_text_only("然后很快，一切在瞬间又恢复了正常，爱衣还在摆弄着听诊器，似乎完全没注意到。")
	novel_interface.show_character("ren_uniform","solemn")
	await novel_interface.show_dialog("（刚才是怎么回事！？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("好像透过照片都能感受到，拉斐尔的周围有一种奇异的气场，与爱衣的仪器产生了共鸣。")
	novel_interface.show_character("ren_uniform","solemn")
	await novel_interface.show_dialog("这究竟是……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("滴滴滴——滴——")
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("什么声音？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我抬起头，看到屏幕上的波形正在剧烈的抖动。")
	novel_interface.show_character("ren_uniform","normal2")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","wink",0.25)
	await novel_interface.show_dialog("哦呀呀，忽然波动的这么厉害。", "爱衣")
	novel_interface.change_2nd_expression("blush_think")
	await novel_interface.show_dialog("难道是小怜在偷看什么让人脸红心跳的东西吗？", "爱衣")
	await novel_interface.show_dialog("比如说…你这个年纪的男孩子都会看的那种……", "爱衣")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"awkward")
	await novel_interface.show_dialog("才没有啦！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奇异的共鸣感消失了。")
	await novel_interface.show_text_only("是被爱衣的胡闹打断了吗……")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("刚才那个突然波动的是什么参数？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_think",0.25)
	await novel_interface.show_dialog("是……秘·密·哟~", "爱衣")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("……就不该问你的。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("你好，请问可以进来吗？", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯从保健室外间轻柔地走了进来。")
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("倪克斯学姐！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_normal","smile",0.25)
	await novel_interface.show_dialog("你好呀，小怜，没想到会在这里见面。", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("学姐疑惑地看了看我身边的仪器，试图搞明白我正在做什么。")
	novel_interface.show_character("ren_uniform","happy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("nyx_normal","speak",0.25)
	await novel_interface.show_dialog("请问这是……？", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("倪克斯指了指爱衣手中的蓝色四爪型道具。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("在做人体实验啦，人体实验~", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("等等！居然这么大方的承认了吗？")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("哦……", "倪克斯")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("对了，爱衣小姐，我身体有点不舒服，请问可以在这里休息一下吗？", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不愧是倪克斯学姐，面对这种发言居然可以忍住不吐槽，并且继续保持得体的微笑。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("没问题，你就在旁边那张床上休息好啦~\n小怜这边还需要15分钟左右。", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣边说边将屏幕从仪器上拿了下来，说她去上传一下刚才的数据。")
	novel_interface.show_character("nyx_normal","smile")
	await novel_interface.show_dialog("谢谢。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯学姐向爱衣点了点头，走到了我旁边的床上躺下。")
	await novel_interface.show_text_only("那张床距离我大概只有一米不到，学姐并没有拉上隔帘。")
	novel_interface.show_character("ren_uniform","blush")
	await novel_interface.show_dialog("（她这么毫无防备的躺下了吗？）\n（也对哦，都是女生有什么好防备的………）", "小怜")
	await novel_interface.show_dialog("（糟糕，心跳得好快。）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我侧过脸，偷偷看着背对我躺在一旁的学姐，连把发丝撩到耳后的动作也那么优雅。")
	await novel_interface.show_text_only("这样的距离，还可以闻到她身上淡淡的香味……")
	await novel_interface.show_text_only("在我有点沉浸在这样梦幻的氛围里的时候，倪克斯学姐转身把脸朝向我，正好和我四目相对。")
	novel_interface.show_character("ren_uniform","blush")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_normal","smile",0.25)
	await novel_interface.show_dialog("怎么了？", "倪克斯")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哎！啊？……\n那个……", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("我猛然清醒过来，就像做了坏事被抓到现形的小孩一样手足无措。")
	novel_interface.character_light(0.35,"perspire1")
	await novel_interface.show_text_only("怎么办，这种时候应该说点什么吗？")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("（不对，等等……）", "小怜")
	novel_interface.change_expression("perspire1")
	await novel_interface.show_text_only("好像刚才并不是因为害羞而紧张，而是……")
	await novel_interface.show_text_only("小腹处好像传来阵阵的燥热感……")
	await novel_interface.show_text_only("这是……和刚才看到拉斐尔的照片产生的感觉有点类似。")
	novel_interface.change_expression("sob")
	await novel_interface.show_text_only("啊啊啊，我不会已经堕落到对着哪个女生都会遐想连篇的程度了吧！？")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("你脸色看上去有点差，不要紧吧？", "倪克斯")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("没、没事的。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("啊，那是……？", "倪克斯")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("倪克斯学姐的目光停留在了我的手机上。\n她微蹙着眉，有些不悦地盯着屏幕上的照片。")
	novel_interface.character_light(0.35,"happy")
	await novel_interface.show_dialog("倪克斯学姐，你认识这个人吗？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("不，不认识。", "倪克斯")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"upset")
	await novel_interface.show_dialog("（可学姐明明那么厌恶的神情……）\n（我应该看错了吧？）", "小怜")

	print("=== 第3章第6话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
