# chapter3_ep02.gd - 第三章第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep02_script()

func play_script():
	pass

func chapter3_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("根据SID的记录显示，阿卡特拉兹收容基地收容着被联合议会禁止测试和研究的EX级『异质物』。")
	await novel_interface.show_text_only("收容基地的地下，还连接着严禁入内以至于连评级都无法完成的古代遗迹『夏特洞窟』。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("那个EX级的『异质物』……是什么特别危险的东西吗？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("大多是某些宗教相关的『圣物』，因为对教众有特别的意义，所以只许收容，不许研究。", "莉琉")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("感觉有点自欺欺人啊。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("呵呵呵，虽然我也是这么想的——\n不过也有他们的道理哦。", "莉琉")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("有些物品在宗教传说中拥有弑神的能力，或能开启末日审判，", "莉琉")
	await novel_interface.show_dialog("一旦激发可能会引起世界末日级的灾难。", "莉琉")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那确实……有些不妙。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("而另一些在宗教故事中特别神圣的物品，可能测试后发现只有很弱甚至尴尬的效果……", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("搞笑的效果？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("比如有位“圣人”的鞋子，亲吻鞋尖就会产生不可以抑制的裸奔冲动，这也太让教宗下不来台了。", "莉琉")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……还有这么恶趣味的东西啊\n那他们这次丢的是哪一类？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"serious")
	await novel_interface.show_dialog("……这次失窃的，是由所有学园都市共同监视和保护的EX『异质物』——『天命之矛』。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("哦哦！\n原来如此，好厉害！", "小怜")
	await novel_interface.show_dialog("那，『天命之矛』是什么呀？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("…………", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("你现在的样子，真是一脸的白痴。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","sob",0.25)
	await novel_interface.show_dialog("就是不知道啊！\n我只是普通的高中生而已……", "小怜")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("莉琉无奈的看着我，盘算着我要理解这个问题需要补习知识点。")
	novel_interface.character_light()
	await novel_interface.show_dialog("总的来说，是属于第一类，传说中有弑神能力的异质物。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("在公开文献中，对天命之矛只有两段非常简单的异常描述：『高温不会溶解』和『挥舞时会变重』", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("就……这么简单？", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("如果深入研究，这两条中任何一条的延伸都可能成为XK级『异质物』了。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("如果还有其他未表现的特质就更危险，所以一般这种东西会尽量避免在媒体面前曝光。", "莉琉")
	novel_interface.character_dark()
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("我不禁咽了下口水，XK级『异质物』可是连小孩子都知道的——")
	await novel_interface.show_text_only("能够造成世界毁灭级灾难或形成同等威慑力的『异质物』，目前世界上已知的只有六个。")
	await novel_interface.show_text_only("分别属于六个学园都市，或者说，拥有XK级『异质物』，才会被联合议会所承认。")
	novel_interface.character_2nd_light(0.35,"perspire1")
	await novel_interface.show_dialog("……哎？\n也、也就是说……？", "小怜")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("现在知道“你”犯下的罪有多重了吗？", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("因为太过震惊，我反而失去了实感。")
	novel_interface.character_2nd_light(0.35,"sob")
	await novel_interface.show_dialog("……对不起\n不对！道什么歉！并不是我偷的啊！！", "小怜")
	await novel_interface.show_dialog("（可恶，那个家伙岂不是超级危险！）", "小怜")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("不、不过新闻能被撤下也算不幸中的万幸……", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("笨蛋，新闻撤下是为了避免引起恐慌。\n通缉令还是会被秘密执行的。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("为了保密，通缉令不会下发到防卫厅，但各国的情报机构，包括SID在内应该都收到了通报。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("所以你想松一口气还早呢~", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("果然……我原来的样子还是很危险吧？", "小怜")
	novel_interface.change_2nd_expression("perspire1")
	await novel_interface.show_dialog("万一……我是说万一！\n有人根据通缉令的照片查到了原来的我身上……", "小怜")
	await novel_interface.show_dialog("就算我现在是女生，也很有可能被当作相关人员审问吧？", "小怜")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你终于意识到问题了呢~", "莉琉")
	await novel_interface.show_dialog("情报部爬取了所有能查到的监控录像，发现那个顶着你的脸的家伙，最近还在几个异变区出现了。", "莉琉")
	await novel_interface.show_dialog("而且既然我们能从第三方数据中查到，其他机构也差不多也应该掌握这个信息了", "莉琉")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"panic")
	await novel_interface.show_dialog("居然是个惯犯了吗？\n怎么感觉，我的前途已经一片黑暗了……", "小怜")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("我的脑海中瞬间划过无数严刑拷打的画面……")
	await novel_interface.show_text_only("总感觉，随时会被人带走，然后背上反人类什么的罪名……")
	await novel_interface.show_text_only("被关进最严格的监狱，判处两百年以上的刑期。")
	await novel_interface.show_text_only("没准遇到超恐怖的狱友，时不时还会……")
	await novel_interface.show_text_only("呜哇~打住！！！\n不要想了！！！")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("哈哈哈居然害怕到脸色发白啊……", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("安心，在新丰洲境内，我可以保证你的安全指数达到98%。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("也就是说，还有2%的可能会出现意外？！", "小怜")
	await novel_interface.show_dialog("（每100秒会有2秒出现意外吗！？）\n（这样一点安全感也没有啊！！）", "小怜")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("能让联合议会的老乌龟们史无前例的这么快达成一致……说不定，背后还有我不知道的力量。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("而这……就是那2%的不确定因素了。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("已经不敢想像这件事在那群大人物中引发了多大的轰动了……", "小怜")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所以，现在其他学园都市的情报部门也一定正投入大量的人力物力，全力搜捕画面中这个人。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("那、那我该怎么办才好？", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"speak2")
	await novel_interface.show_dialog("看得到的敌人都好对付，那些专业工作就交给SID吧。", "莉琉")

	print("=== 第三章第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
