# chapter3_ep14.gd - 第3章第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep14_script()

func play_script():
	pass

func chapter3_ep14_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("雅各·施密特\n伊露卡的管理员……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看到雅各身后，几个穿着保安军制服的人倒在门口。")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("他们只是晕过去了，我不准备在联合议会的地盘闹出人命。", "雅各")
	await novel_interface.show_dialog("本来只是想回收《七哲人书》那本邪典的书页，这次真是意外的收获啊……", "雅各")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("……", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("（《七哲人书》………）\n（就是『黄金蝴蝶』对应的魔导书吗？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("小怜……我帮伊露卡洗澡的时候，发现她的身上有非常多已经愈合很久的伤口。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("（帮伊露卡洗澡？）\n（什么时候！？）", "小怜")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("（不对，那不是重点）\n（如果是旧伤，就说明……！！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("那种强度的创伤，如果是普通的小孩子，估计身心早就崩溃了。", "安妮")
	await novel_interface.show_dialog("一定是这家伙……是这家伙！！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("哦——\n『那个东西』还没坏掉吗？", "雅各")
	await novel_interface.show_dialog("啧啧，估计用在『那个东西』上面的技术\n已经被SID逆向工程了吧。", "雅各")
	await novel_interface.show_dialog("早知道就在『那个东西』身上装个自爆装置，就不会如此麻烦了。", "雅各")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","shout")
	await novel_interface.show_dialog("你这——！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("——你这混蛋！！！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没等我反应过来，安妮已经暴起，一个飞身朝着雅各的脸踢了上去。")
	novel_interface.show_background("res://assets/images/bg/Baizhu/white_bg.png")
	await novel_interface.show_text_only("呲咔——！！！")
	await novel_interface.show_text_only("随着一声尖啸，一道巨大的电弧瞬间将整个房间染成了白色，我的视野顿时一片纯白。")
	await novel_interface.show_text_only("随着强光散去，我用了好几秒才慢慢恢复视野，依然觉得眼球刺痛。")
	novel_interface.show_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	novel_interface.show_character("ren_maid","shout")
	await novel_interface.show_dialog("安妮——！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮失去知觉，重重的摔在了地毯上，身上出现大片的树状的灼烧痕迹。")
	await novel_interface.show_text_only("雅各身边的一个士兵枪口还冒着烟……那就是刚才发射的武器吗？")
	await novel_interface.show_text_only("那个士兵熟练的上膛，枪的一侧飞出一枚霰弹大小的电池状物体。")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("只要方法得当，魔女也是可以物尽其用的。", "雅各")
	await novel_interface.show_dialog("啧啧，我希望尽量抓活的，不过SID的那个疯婆娘快要来了。", "雅各")
	await novel_interface.show_dialog("既然时间不多——", "雅各")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("雅各拿出一个巴掌大小的金属饼状物，灰绿色的金属外壳散发着熟悉的淡蓝色光晕。")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("那个难道是……异质物武器！？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("能感觉到，魔力的流动……", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("在中立区用这种东西，你想做什么！", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("（小怜）", "莉琉")
	await novel_interface.show_text_only("耳机里突然传来莉琉的声音。")
	await novel_interface.show_dialog("（他拿的是用『自缚纤维』制作的诱捕炸弹）\n（是非致命性『异质物武器』）", "莉琉")
	await novel_interface.show_dialog("（启动后3秒内就会爆炸）\n（炸开的纤维会散布整个楼层，你们逃不掉的）", "莉琉")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("——！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("（暂且别做无谓的反抗了）\n（我之后会想办法营救你们……）", "莉琉")
	await novel_interface.show_text_only("雅各慢慢抬起拿着诱捕炸弹的右手，渐渐浮现出了数条金色的亮线，看来炸弹已经准备好启动了。")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("那只手是……魔法刻印？", "小怜")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（终于，要体验一下异质物武器的滋味了吗……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("抱歉了……", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切突然拉住我的手，另一只手利落地扯过拉斐尔手中的项链。")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("转瞬间，绿宝石挂坠放出一道强光，在贝阿特丽切的手中变为了一把刻有铭文的大剑。")
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("妄图申辩挣扎的罪恶灵魂啊——", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("什……", "雅各")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("闭嘴！！！", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切将锐利的剑锋深深插入地板。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("雅各刚要张嘴，声音就如同被什么吞噬了一般\n房间里顿时只留下让人窒息的寂静。")
	await novel_interface.show_text_only("雅各脚下的地面出现了一条裂缝，露出的不是下层的地板或者建筑材料，而是一片漆黑。")
	await novel_interface.show_text_only("黑暗中传出像是数百万人在同时哀嚎一样凄厉恐怖的声音，有如被撕裂的地狱一角。")
	await novel_interface.show_text_only("就像厄运化作了实体，从地面的裂口喷涌而出。黑暗瞬间侵染了目力所及的每一个角落。")
	await novel_interface.show_text_only("被彻骨的寒意和无以名状的恐惧包围，我浑身汗毛倒竖，无法动弹……")
	novel_interface.show_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	await novel_interface.show_text_only("然后黑暗迅速的消散，一切都发生在短短几秒内\n那条裂缝像是从来就没有存在过一样。")
	await novel_interface.show_text_only("雅各像恐慌症发作一样跪倒在地，如发疯一般，用指甲在自己的脖子挠出了一道道血印。")
	await novel_interface.show_text_only("虽然在满脸通红的拼命倒气，但他的肺部似乎被瞬间抽成了真空，鼻孔传出持续的气鸣声。")
	await novel_interface.show_text_only("过了好一会，才从声音判断出他终于恢复了微弱的呼吸。")
	await novel_interface.show_text_only("此时这个身材高大的男人正蜷缩在地毯上，双手交叉抱在胸前止不住的颤抖。")
	await novel_interface.show_text_only("眼神中充满了恐惧，眼睛血丝密布，眼眶里充盈着因体内失压而从泪腺中分泌出的液体。")
	await novel_interface.show_text_only("此时他手上的纹路已完全消失，诱捕炸弹也滚落在地毯上失去了光泽。")
	await novel_interface.show_text_only("屋子里的蒙面士兵都怔在原地——不住的颤抖着。")
	await novel_interface.show_text_only("从他们努力想要站稳的行动看来，似乎还沉浸在刚刚那种超乎意识构建的恐怖当中。")
	await novel_interface.show_text_only("当你凝视深渊时……深渊也在凝视着你……")
	await novel_interface.show_text_only("而面对真正的恐怖，就算仅仅是呼吸……")
	await novel_interface.show_text_only("也会让你觉得自己被暴露在了那无可理喻的绝望存在面前。")
	novel_interface.show_character("beatrice_battle","angry")
	await novel_interface.show_dialog("快走！", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	await novel_interface.show_dialog("（小怜！快走啊！）", "莉琉")
	await novel_interface.show_text_only("我才回过神来，向贝阿特丽切点了点头，抱起安妮快速离开了房间。")
	await novel_interface.show_text_only("贝阿特丽切拉住还处于失神状态的拉斐尔，我们一行四人快速跑向了电梯……")

	print("=== 第3章第14话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
