# chapter3_ep12.gd - 第3章第12话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter3_ep12_script()

func play_script():
	pass

func chapter3_ep12_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	await novel_interface.show_text_only("『气凝胶喷雾』是爱衣博士发明的像发胶一样的罐装喷剂，可以瞬间喷出超大量的泡沫。")
	await novel_interface.show_text_only("泡沫在接触空气后会快速膨胀并凝固，凝固后的强度能够抵抗一般的步枪子弹。")
	await novel_interface.show_text_only("安妮拿着气凝胶喷雾在房门周围忙活的时候，我的注意力再次被地上的黄金蝴蝶吸引了。")
	novel_interface.show_character("ren_maid","normal1")
	await novel_interface.show_dialog("（看上去只是精巧的艺术品嘛……）", "小怜")
	await novel_interface.show_dialog("（但是…忍不住的…好想摸摸看……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在我意识有些朦胧时感到小腹一阵发热，眼前的光亮不断扩散，情不自禁的想要伸出手——")
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("喂！！小怜！！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮一把抓住了我的手腕，我才突然回过神来。")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("这东西可能会影响人的精神……所以他们才要装在那种手提箱里保存吧？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("啊！我差点……到底……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","unhappy",0.25)
	await novel_interface.show_dialog("这个黄金蝴蝶，有一种熟悉的气息……\n我怀疑，它是某种『魔导器』。", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("魔导器？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("唔，怎么说呢……", "安妮")
	await novel_interface.show_dialog("所谓魔法，其实是由一种特殊的『信息』经人的大脑转化而成的知识。", "安妮")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("但伴随着人类获得和积累这种知识，往往是以丧失理智为代价的……", "安妮")
	novel_interface.character_light(0.35,"solemn")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("我想到了之前在变电所遇到的女巫和异变空间中的那些敌人。")
	await novel_interface.show_text_only("那就是因为获得了自己无法承受的『知识』，而完全丧失了理智的状态吧。")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("那种『信息』其实是可以切割和分块存储的，魔导器就是能存储这种小块『信息』的载体。", "安妮")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("至于为什么有这样的设计，我猜可能是为了方便人们追求自己的极限吧……", "安妮")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("为了测试自己在不丧失理智的情况下所能承受的极限，而靠魔导器一点一点吸收魔法的知识？", "小怜")
	await novel_interface.show_text_only("这件事本身听起来就很疯狂了！")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("会不断的如饥似渴的探求新的知识，不如说这是人类的天性吧……", "安妮")
	await novel_interface.show_dialog("就算是注定会走向毁灭……", "安妮")
	novel_interface.character_light(0.35,"solemn")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那接触到魔导器的普通人，如果没有足够的天赋会不会也会像变电所的女巫那样……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("很有可能，而且魔导器上没有覆盖结界，任何人都可以直接触碰。", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"serious")
	await novel_interface.show_dialog("那岂不是超危险啊！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("——轰！\n——轰！")
	await novel_interface.show_text_only("外面突然传来木质大门受到重击的声音。")
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("是保安军！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("——喀啦啦！！\n只撞了两下，皇室套房的大门就被破门锤砸烂了。")
	await novel_interface.show_text_only("——咚~——咚~——咚~\n——咚~——咚~——咚~")
	await novel_interface.show_text_only("随后传来的，是破门锤徒劳的砸在气凝胶干块上的声音。")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("应该能拖到莉琉小姐到达吧……\n爱衣博士的装备真厉害呢。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我摸了摸自己被强行添加了扬声器功能的胸部。")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("啊哈哈……\n是很厉害呢……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然，不知何时醒来的拉斐尔连着绑着她的椅子向我摔了过来。")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("绝不会……让你拿走任何东西！", "拉斐尔")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("你这个内置音响的死变态！！", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔趁着椅子倒地的冲击力挣脱了束缚，紧接着就想要抢走地上的那只黄金蝴蝶。")
	await novel_interface.show_text_only("我见状立即扑了过去，眼看马上就要和拉斐尔撞在一起——")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("不行啊小怜！！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("砰——！")
	await novel_interface.show_dialog("（诶？我抢到了吗？）\n（不对……）", "小怜")
	await novel_interface.show_dialog("（这柔软的触感是……）", "小怜")
	await novel_interface.show_dialog("（有点熟悉的手感，似乎不久前还摸到过）", "小怜")
	await novel_interface.show_dialog("（等等，难道……！）", "小怜")
	await novel_interface.show_dialog("你……你这个！", "拉斐尔")
	await novel_interface.show_dialog("臭流氓！！！", "拉斐尔")
	await novel_interface.show_text_only("——啪！")
	await novel_interface.show_text_only("随着一个清脆的巴掌，一阵失重的眩晕感传来。")
	await novel_interface.show_text_only("许多支离破碎的影像碎片在我的脑海中闪过，周围的声音在刹那间全部消失了。")
	await novel_interface.show_text_only("我好像进入了另一个世界。但那种奇怪的感觉，转瞬即逝。")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.change_background("res://assets/images/bg/SkyHotel/guestRoomInner.png")
	await novel_interface.show_text_only("当我再次睁开眼时，发现自己依旧站在酒店的房间里。")
	await novel_interface.show_text_only("那个黄金蝴蝶的饰品好像活了一样展翅飞到了我的胸口上，变成了一道耀眼的闪光。")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("怎么会……？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("当光芒化作星沙，缓缓消失之后，我感觉脸颊被轻柔的抚过，有一种奇妙而温软的触感刻在了心里。")
	novel_interface.show_character("ren_maid","timid")
	await novel_interface.show_dialog("——咦？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("房间原本的空地上，出现了一位美艳动人的女性。")
	await novel_interface.show_text_only("淡红的双眸与长发，长的身姿，凝脂般无暇的肌\n肤，令人无法移开目光……")
	novel_interface.show_character("ren_maid","timid")
	await novel_interface.show_dialog("（……发生什么了？）\n（嘴唇，刚刚好像被什么给碰了一下！）", "小怜")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("（……哈哈哈，不对不对！）\n（我在想什么呢，这种事不可能的！）", "小怜")
	await novel_interface.show_dialog("（不、不可能的！！！）", "小怜")
	novel_interface.change_expression("timid")
	await novel_interface.show_dialog("（糟糕，这种感觉，这种感觉……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("啊，感受到了久违的温度呢。", "突然降临的女性")
	await novel_interface.show_dialog("晚上好啊，诸位年轻的小姐~", "突然降临的女性")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","timid")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的心跳不断加快，情不自禁的向她靠近，四肢都不听使唤了。")
	await novel_interface.show_text_only("就在众目睽睽下，我张开双臂，用力抱住了她。")
	novel_interface.show_character("beatrice_battle","worry")
	await novel_interface.show_dialog("哎，这位漂亮的小姐，你是身体不适吗…？", "突然降临的女性")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","timid")
	await novel_interface.show_dialog("请问……", "小怜")
	await novel_interface.show_dialog("你愿意告诉我你的名字吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奇怪，对方的身体好像在不断变重……\n连体温也在不断变热啊……")
	await novel_interface.show_text_only("我到底是……怎么了啊！！")
	novel_interface.show_character("beatrice_battle","smile2")
	await novel_interface.show_dialog("……哎呀呀\n真是不可思议。", "突然降临的女性")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("！！？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("——小怜！！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮一把将我从对方怀中拉开。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("你……究竟是谁？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","smile1")
	await novel_interface.show_dialog("如果我的名字在这个时代没有被列入禁忌的话……请唤我贝阿特丽切吧。", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","timid")
	await novel_interface.show_dialog("好好听的名字啊……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("小怜……\n小怜好像变成花痴了啊！！", "安妮")

	print("=== 第3章第12话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
