# side02_ep4.gd - 新年彩券屋篇第4话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	side03_ep4_script()

func play_script():
	pass

func side03_ep4_script():
	novel_interface.change_background("res://assets/images/bg/Struggle/BG_Desert.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("哎……好热……", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("因为天气太热了，少女醒后脱掉了外套。与此同时，她仔细观察着周围的环境，确认当前的状况。")
	novel_interface.show_character("raphaeluncoat","normal")
	await novel_interface.show_dialog("（我从未见过这种建筑风格，似乎本来就不是出自人类之手……）", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("建筑物外，一些理论上不应存在的生命体正迈着大步走来走去，看起来很不真实。")
	novel_interface.show_character("raphaeluncoat","Perplexed")
	await novel_interface.show_dialog("那是什么，应该不是……电影的道具吧。\n莫非是基因改造技术的产物……", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("突然响起了强烈的玻璃破碎声。紧接着，一阵慌乱的脚步声逐渐向少女逼近。")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphaeluncoat","Perplexed")
	await novel_interface.show_dialog("什么？！", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_battle","shout")
	await novel_interface.show_dialog("拉斐尔！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphaeluncoat","Perplexed")
	await novel_interface.show_dialog("小——", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("……哼，这不是女装癖吗？\n慌慌张张的，又怎么了？", "拉斐尔")
	novel_interface.character_move_left(-0.25)
	novel_interface.character_dark()
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("我可是来救你的啊！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("josette")
	await novel_interface.show_dialog("小怜~\n找到刚才的女人了吗？", "乔瑟特")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","jeer")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你认识那个大嗓门小孩？\n这么说来，怎么又是女孩子？这是你的兴趣？", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("误会啊！", "小怜")
	novel_interface.change_2nd_expression("sob")
	await novel_interface.show_dialog("……好痛！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("josette")
	await novel_interface.show_dialog("小怜，你是不是受伤了？", "乔瑟特")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("mekako")
	await novel_interface.show_dialog("探测到小怜生命体征异常。\n判定为2级裂伤，1级淤伤。", "咩卡子")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("josette")
	await novel_interface.show_dialog("我知道你想帮忙，但你太乱来了呀。", "乔瑟特")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("没关系，这点小伤……", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔默默地握住小怜的手，送去温暖的治愈气息。")
	novel_interface.show_character("mekako")
	await novel_interface.show_dialog("确认到治疗效果。\n生命体征，正常。", "咩卡子")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("拉斐尔……谢谢你。", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔优雅地松开手，有些不好意思地咳嗽了一声。")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("哼。毕竟情况特殊，没有你这样的变态也挺麻烦……", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("突然一声巨响，众人下意识地警戒起周围。\n但是周围却没有任何迹象。")
	novel_interface.show_character("mekako")
	await novel_interface.show_dialog("难道刚才的声响是幽鬼所致？", "咩卡子")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","perspire")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","uneasy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("幽鬼？", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("幽鬼好像就是逝者彷徨的记忆之类的……", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……你你你，你，你难道想说这里有幽灵吗？！\n你这——", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("不，不是的！幽鬼不是幽灵！\n是一种生物……！", "小怜")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("……啊，拉斐尔你该不会怕鬼吧？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔一言不发。\n敲了敲小怜的头，便匆匆离开了。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("真是……太不讲理了……", "小怜")


	print("=== 拉斐尔联动剧情 结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
