# chapter1_ep2.gd - 第一章第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter1_ep2_script()

func play_script():
	pass

func chapter1_ep2_script():
	var player_name = GameConfig.player_name
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/AEGIS.png")
	await novel_interface.show_dialog("登录成功！","系统语音")
	await novel_interface.show_dialog("您的ID：2519G1911\n姓名："+player_name,"系统语音")
	await novel_interface.show_dialog("年龄：15岁\n性别：男性","系统语音")
	await novel_interface.show_dialog("欢迎来到第五学园都市斯蒂尔蒙特收容研究中心。新丰洲境内最大的『异质物』收容与研究机构。","系统语音")
	await novel_interface.show_dialog("『异质物』又称『神迹』，指在特定情况下能引发超常物理现象的道具和工具的总称。","系统语音")
	await novel_interface.show_dialog("今天是研究中心的学园开放日。\n研究中心向市民和其他学园都市的考察团开放。","系统语音")
	await novel_interface.show_dialog("作为公众教育的重要一环\n会将部分『神迹』和研究成果和进行展览……","系统语音")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_passageNight.png")
	novel_interface.show_character("ren_male","normal")
	await novel_interface.show_dialog("Lucky！~总算在闭馆之前赶到了！",player_name)
	await novel_interface.show_dialog("大厅的电梯居然全都停运了，好在发现了还在运行的备用货梯。",player_name)
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("总之，只要去听个讲座盖章就能拿到学分了吧？",player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("不过……这层怎么也一个人都看不到？",player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我沿着二楼的走廊边走边四处张望。")
	await novel_interface.show_text_only("虽说这种地方平时人就不多，但现在居然连一个人影都看不到。")
	await novel_interface.show_text_only("而且空气里好像有股医院消毒水的味道，我不禁联想到闭馆后进行扫除作业的清洁人员。")
	novel_interface.show_character("ren_male","speechless")
	await novel_interface.show_dialog("讲座不会已经结束了吧？",player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一边找讲座的『会议厅』，一边拐到一个旋转楼梯边上。")
	novel_interface.show_character("ren_male","worry")
	await novel_interface.show_dialog("惨了惨了，果然不应该玩那个游戏……",player_name)
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("『下一回合』这种按钮真是有毒——啊啊啊啊唔嗯\n！！！？",player_name)
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("突然我的脖子被什么东西钩住并被迅速向后拉！")
	await novel_interface.show_text_only("身体马上要失去平衡的时候，感觉后脑勺靠在了一个柔软又坚实的物体上。")
	await novel_interface.show_text_only("等我回过神来，已经被拉进了楼梯拐角处一条狭窄的过道，周围的光线要暗上许多。")
	await novel_interface.show_dialog("呜——！！\n唔——！！！",player_name)
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/liliu_instPassageHiding.png")
	await novel_interface.show_text_only("还没叫出声，我的嘴就被一只手紧紧捂住，只能勉强用余光看到一个穿着白大褂的女人——")
	await novel_interface.show_text_only("此时她背靠墙壁，用一只手捂着我的嘴")
	await novel_interface.show_text_only("而我的一侧脸颊被紧紧贴在她的胸前……芬芳馥郁的香气不断钻进鼻子里。")
	await novel_interface.show_dialog("（诶？？好、好大！！！！脸埋进去了！！)",player_name)
	await novel_interface.show_dialog("（什么状况！！这个人是谁！？）",player_name)
	await novel_interface.show_dialog("嘘——！别出声！", "穿白大褂的女性")
	await novel_interface.show_text_only("身后的女人虽然刻意压低声音，但言语中透露着不容质疑的威严感。")
	await novel_interface.show_text_only("我的脑子乱作一团，感觉快要窒息了\n只能微微点头表示顺从……")
	await novel_interface.show_text_only("虽然我的嘴依然被捂着，但脖子上的压力小了一\n些。")
	await novel_interface.show_text_only("我将目光聚焦在近处，隐约看到她胸前的白大褂上别着的姓名牌上有一行小字：首席科学家……")
	await novel_interface.show_dialog("（科学家……她是研所工作人员吗？）",player_name)
	await novel_interface.show_text_only("此时我才发现她并没有看我，而是把头转向另一\n侧，专注的盯着走廊的方向。")
	await novel_interface.show_text_only("走廊远处传来了急促有力的脚步声。")
	await novel_interface.show_dialog("报告，这边没人。", "男性的声音A")
	await novel_interface.show_dialog("不过确实有一部独立的货运电梯，我去手动关停。", "男性的声音A")
	await novel_interface.show_dialog("（还有刚才跑过去的那个人似乎蒙着脸，手里还拿着……枪？）",player_name)
	await novel_interface.show_dialog("这里被入侵了哟，不想死就别动。", "穿白大褂的女性")
	await novel_interface.show_dialog("（入、入侵？什么状况……)",player_name)
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	await novel_interface.show_text_only("我在愣神的功夫，女人已经闪身跟了出去")
	await novel_interface.show_text_only("几秒后传来一记闷响和类似骨头折断的声音。")
	await novel_interface.show_text_only("没有预想中的倒地声，她顺势从后面接住蒙面男\n人，然后把他拖回了过道，并卸下了一把手枪。")
	await novel_interface.show_dialog("他是……？！",player_name)
	await novel_interface.show_text_only("女人并没有理我，而是熟练的打开墙边配电室的门\n，抬起高跟鞋一脚把浑身瘫软的壮汉踹了进去。")
	await novel_interface.show_text_only("虽然穿着白衬衫和贴身短裙，但动作一气呵成十分利落。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("哼~暂时应该不会有人过来了。", "穿白大褂的女性")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她拍了拍手，像是刚刚处理完大型垃圾一样，回过头来轻松的看着我。")
	await novel_interface.show_text_only("我的大脑已经无法处理刚刚发生的事情了，只能傻傻的看着她。")
	novel_interface.show_character("ren_male","shy")
	await novel_interface.show_dialog("（仔细一看，这个姐姐很漂亮啊！）\n（而且身材也好像模特一样……）",player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("（但是，她胸前的名牌上分明写着“科学家”）",player_name)
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("（所以刚才的事一定是幻觉吧！）",player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没错，现在配电室里并不存在一个蒙面壮汉。")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_liliu_leg1.png")
	await novel_interface.show_text_only("我心安理得的做出了这样的推断，并把视线移向了她的腿……")
	await novel_interface.show_text_only("（能跟这样的姐姐在一起工作可真好啊……）\n（异质物研究员也是一份不错的工作呢）")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("喂？小鬼，你眼睛在看哪里呢？", "穿白大褂的女性")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她一边说话，一边卸下手枪弹匣检查子弹。")
	novel_interface.show_character("ren_male","sob")
	await novel_interface.show_dialog("（我不要自己骗自己了啊！！！）",player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("你、你好\n你是……？",player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("嘛……你叫我莉琉好了\n我今天本来是要做个无聊的讲座", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她熟练的把枪组好，塞回了白大褂的口袋里。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("不过刚刚那群家伙劫持了会议厅。\n托他们的福，讲座取消了~", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_male","shock",0.25)
	await novel_interface.show_dialog("莉琉……莉琉·冯·布劳恩？！",player_name)
	await novel_interface.show_dialog("你、你不就是我要盖章的讲座的主讲人吗！\n还是元老院评定的SS级科学家！",player_name)
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哼，那帮老头子很好骗的~", "莉琉")
	await novel_interface.show_dialog("不过看你的样子是来混学分的吧？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("唔……实在抱歉！！",player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"speak")
	await novel_interface.show_dialog("该说你是不幸还是笨蛋呢，居然能在闭锁状态下找到上楼的电梯。", "莉琉")
	await novel_interface.show_dialog("不管你的话，怕不是要傻乎乎直接走进『会议厅』的劫持现场了。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("闭锁状态……？\n我拿出手机，果然一点信号都没有。")
	await novel_interface.show_text_only("终于明白为什么大厅正面的电梯全都停了……原来不是闭馆了啊！")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("现在你上来的那部电梯也被封死了，你就乖乖待在这等待防卫厅的救援吧。", "莉琉")
	await novel_interface.show_dialog("我得去会议厅看看状况，如果有人来你就躲起来。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("可、可是……你一个人……",player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("听明白了吗！", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("好的！！",player_name)

	print("=== 第一章第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
