# chapter1_ep5.gd - 第一章第5话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter1_ep5_script()

func play_script():
	pass

func chapter1_ep5_script():
	var player_name = GameConfig.player_name
	await novel_interface.enter_video_performance_mode([
		"res://assets/video/5-1.mp4"
	])
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Home_bedroom.png")
	novel_interface.show_character("ren_trans","normal")
	await novel_interface.show_dialog("（去洗手间反复确认过了……）\n（大脑要无法思考了……）",player_name)
	await novel_interface.show_dialog("（狠狠的捏了自己一把）\n（并不是在做梦！）",player_name)
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（而且感觉自己的身体软了许多）\n（手感还不错……）",player_name)
	novel_interface.change_expression("shock")
	await novel_interface.show_dialog("不错个鬼啊！！\n我在想什么！！",player_name)
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("可恶啊…昨天明明还很合身的T恤\n一下子就变得这么大了…",player_name)
	await novel_interface.show_dialog("其实是我的身体变小了吧……",player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("从镜中看去，是个穿着尺寸不合的服装的小巧女生好像电影里穿着男友衣服的少女……")
	novel_interface.show_character("ren_trans","shock")
	await novel_interface.show_dialog("……我为什么要脸红啊……",player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("果然……\n变成女生这种事，跟谁也说不出口吧……",player_name)
	await novel_interface.show_dialog("刚才仔细的检查了房间。\n唯一的异常是床边多出一根金属球棒。",player_name)
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("昨天的梦里研究中心遭到了袭击。\n我用这根球棒战斗过……",player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("如果那也能算作战斗的话……",player_name)
	await novel_interface.show_dialog("后来整个城市都灰飞烟灭了……",player_name)
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("对了，查一下手机！\n如果真的发生过，这样的事件一定有报导的！",player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("恐怖袭击之类的新闻，并没有……",player_name)
	await novel_interface.show_dialog("太好了，果然只是梦吗……",player_name)
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("咦？这是——？",player_name)
	await novel_interface.hide_character()
	novel_interface.show_special_centered_image("res://assets/images/bg/Shot/role25.png",410,1.0,1.0,0.3)
	await novel_interface.show_dialog("『洛斯金杯』在严密监视下突然消失。","新闻")
	await novel_interface.show_dialog("洛斯金杯于昨晚在12组监视设备的注视下从设置地点消失。","新闻")
	await novel_interface.show_dialog("斯蒂尔蒙特收容研究中心配有森严的管理和警备，失窃的可能性极低……","新闻")
	await novel_interface.hide_special_centered_image(0.3)
	novel_interface.show_character("ren_trans","stare")
	await novel_interface.show_dialog("感觉……必须再去一趟研究中心才行！",player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("关于昨天的梦，还有我身体的事。\n总觉得去了研究所说不定就能明白些什么了。",player_name)
	await novel_interface.show_dialog("好！我出门了！",player_name)
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street1.png")
	novel_interface.show_character("ren_trans","shy")
	await novel_interface.show_dialog("说来……\n我的样子，完全是可疑人士吧……",player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看到自己映在大楼入口处玻璃上的身姿，我还是感到有些后悔。")
	await novel_interface.show_text_only("衬衫明显不和尺寸，牛仔裤腿长到拖在地上。")
	await novel_interface.show_text_only("最极品的是，右手还拿着金属球棒。\n但这是唯一的证据了……")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside.png")
	novel_interface.show_character("ren_trans","normal")
	await novel_interface.show_dialog("嗯……一鼓作气就来到了这里，可是接下来该怎么办呢。",player_name)
	await novel_interface.show_dialog("不像是会发生恐怖袭击的样子啊，有那么多的保\n安。",player_name)
	await novel_interface.show_dialog("不过这也难怪，有收容品消失了嘛……",player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("nantetsu","speak")
	await novel_interface.show_dialog("……等等，小姑娘。", "警备员")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_trans","normal")
	await novel_interface.show_dialog("……",player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("nantetsu","speak")
	await novel_interface.show_dialog("那边的小姑娘，站住！！！！", "警备员")
	await novel_interface.show_text_only("讲话者是一位短发的男性，从袖口处露出的手臂可以看到线条粗犷，充满力量的肌肉。")
	await novel_interface.show_text_only("历经锤炼的身材配上和蔼炫目的笑容，像极了出演某个摔跤影片的主角。")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_trans","shock",0.25)
	await novel_interface.show_dialog("吓！？",player_name)
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("对，就是在叫你。", "警备员")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy")
	await novel_interface.show_dialog("什么小姑娘，蠢货！\n我是……我……是……",player_name)
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯？总之，昨天有重要的东西不见了。\n我们收到命令要对这一带进行封锁。", "警备员")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shock")
	await novel_interface.show_text_only("我也有重要的东西不见了……\n十分重要的东西，起床就不见了！")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("现在普通人禁止入内了，小姑娘你改日再来吧。", "警备员")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("还有！", "警备员")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("吓！又、又怎么了吗……？",player_name)
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("小姑娘你拿着球棒到处乱跑暂且不说，穿成这样很容易着凉的。", "警备员")
	await novel_interface.show_dialog("快回家吧！", "警备员")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_left(0)
	await novel_interface.show_text_only("警备员对我竖起拇指，又露出了炫目温暖的笑容。")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_trans","normal")
	await novel_interface.show_dialog("好……好的，那再见！",player_name)
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（小姑娘什么的称呼，好不习惯啊……）",player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("呜——肯定有什么线索。\n可是进不去……",player_name)
	await novel_interface.show_dialog("……只能乖乖回去了吧。",player_name)
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside_abnormal.png")
	await novel_interface.show_dialog("咦？我从刚才起就一直在往车站走，但道路好像不对劲？",player_name)
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("呃？\n怎么回事？？？",player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("我迷路了吗……",player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("witch_first")
	await novel_interface.show_dialog("唧——！\n…věta…hrích…！！","神情古怪的不良")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_trans","normal")
	await novel_interface.show_dialog("这群人怎么怪怪的……\n这些家伙……她们在说什么？",player_name)
	novel_interface.change_expression("shock")
	await novel_interface.show_dialog("呜哇啊啊啊啊！！！！",player_name)
	await novel_interface.show_dialog("这些家伙，冲我来了！？",player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("witch_first")
	await novel_interface.show_dialog("…Mors…！！","神情古怪的不良")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_trans","shock")
	await novel_interface.show_dialog("得赶快逃！",player_name)
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("……呼呼……！就算想逃……\n衣服和鞋都这么松垮，根本跑不快……！",player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("witch_first")
	await novel_interface.show_dialog("嚇啊啊啊啊！！！！","神情古怪的不良")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_trans","shock")
	await novel_interface.show_dialog("要被追上了……\n完了完了！！",player_name)
	await novel_interface.show_dialog("诶？球棒……？",player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我发现手中球棒上的花纹泛起了异色的光芒\n这、这是……！")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.enter_video_performance_mode([
		"res://assets/video/10005_2.mp4"
	])
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside_blue.png")
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("我是魔女，你可以叫我安妮\n……看来你遇到麻烦了呢~", "蓝色头发的少女")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_trans","shock")
	await novel_interface.show_dialog("安妮……魔女？？\n我今天遇到的麻烦可不是一般的大……",player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","smile",0.25)
	await novel_interface.show_dialog("虽然有很多想问你的事情。\n不过先来解决眼前的问题吧！","安妮")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("话说你穿的是什么嘛……松松垮垮的\n这身衣服太不适合运动了吧~", "安妮")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("我来帮你换一件合身的衣服\n要准备打架了哦！", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("打、打架？！",player_name)

	print("=== 第一章第5话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
