# chapter1_ep6.gd - 第一章第6话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter1_ep6_script()

func play_script():
	pass

func chapter1_ep6_script():
	var player_name = GameConfig.player_name
	novel_interface.change_music("res://assets/audio/music/Black Market.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside.png")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("……呼、哈……虽然不知道是怎么回事\n这算是，赢了吗……？",player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","normal",0.25)
	await novel_interface.show_dialog("……好像是呢。","安妮")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你、你到底是什么人！？\n从哪里冒出来的！？",player_name)
	await novel_interface.show_dialog("袭击我的那些家伙是什么东西！？\n这根球棒又是啥！？",player_name)
	await novel_interface.show_dialog("这里怎么了？！",player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("你冷静点！\n在我知道的范围内我会一一解答你的问题的。", "安妮")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("不过我也和你一样搞不清楚状况。\n你是什么人，我还想知道呢……。", "安妮")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("抱歉。我太慌乱了……",player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("没关系啦。\n对了，还没认真互相自我介绍呢。", "安妮")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("我的名字是安妮·巴斯。\n就叫我安妮吧~", "安妮")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……我叫"+player_name+"，请多关照。",player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog(player_name+"啊……彼此彼此。", "安妮")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("你的名字好像男生呢。好帅气~", "安妮")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("！？", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("怎么了，为什么那么惊讶？","安妮")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊，说来我现在……\n是女的啊……",player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("嗯？你就是女生呀\n你看这身变的衣服还合适吧？", "安妮")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("很可爱很可爱……\n这件『战服』就当做我送你的见面礼吧~", "安妮")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……战服？",player_name)
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("呀呀——啊啊啊啊啊啊啊啊！！！！",player_name)
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_girlchar_battleWearingShy.png")
	await novel_interface.show_text_only("反应过来才发现\n我居然穿着一身女装！！")
	await novel_interface.show_text_only("水手服……\n和短到难为情的短裙……！")
	await novel_interface.show_text_only("腿上的丝袜，是这样微妙的感觉吗……？")
	await novel_interface.show_dialog("而且胸口传来的紧缚感不会是……（摸）",player_name)
	await novel_interface.show_dialog("啊啊啊啊啊啊！！！",player_name)
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside.png")
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("外套和你的发色也很搭哦~\n是非常适合运动的款式。", "安妮")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("嗯……？怎么了嘛~~？", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","shy",0.25)
	await novel_interface.show_dialog("因为……\n因为……",player_name)

	print("=== 第一章第6话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
