# chapter1_ep3.gd - 第一章第3话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter1_ep3_script()

func play_script():
	pass

func chapter1_ep3_script():
	var player_name = GameConfig.player_name
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("这边的哨点一直没有回复，你去那边检查一下——", "男性的声音A")
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_1")
	await novel_interface.show_dialog("是！", "男性的声音B")
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("我去拿心跳检测仪来，你盯着点！", "男性的声音A")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","worry")
	await novel_interface.show_dialog("糟了，在这里躲不过的……",player_name)
	await novel_interface.show_dialog("他们的视线没有死角可以溜走，唯一的机会是趁他们分开偷袭其中一个",player_name)
	await novel_interface.show_dialog("大概没问题吧……\n既然那个女人赤手空拳都能撂倒对方……",player_name)
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("得找个东西作为武器……",player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("走廊的墙壁上挂着一根金属球棒，底下铭牌的小字上写着“莱博娜 自由光……”")
	novel_interface.show_character("ren_male","happy")
	await novel_interface.show_dialog("应该是展品吧……\n只是临时借用，嗯嗯，临时借用……",player_name)
	await novel_interface.show_dialog("……\n……",player_name)
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("那么……要上了！\n哈——！",player_name)
	await novel_interface.hide_character()
	await novel_interface.play_background_flash_effect(Color.WHITE,3,0.15,1.0,[Color.RED,Color.BLACK],true)
	await novel_interface.show_text_only("咚！！！")
	await novel_interface.show_text_only("我全力一击，打向蒙面人的后脑勺，发出了一声巨响。欸……声音这么大的吗？")
	await novel_interface.show_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	await novel_interface.show_text_only("但是对方并没有如我期待的那样倒下，而是眼中冒着怒火转过了身。")
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("这和游戏里不一样啊！！",player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("什么人！", "蒙面人A")
	await novel_interface.hide_character()
	await novel_interface.play_background_flash_effect(Color.RED,3,0.15,0.6,[],false)
	await novel_interface.show_text_only("蒙面人迅速挥动枪托向这边袭来，我连忙握紧球棒抵挡。")
	novel_interface.show_character("ren_male","shock")
	await novel_interface.show_dialog("不好——",player_name)
	await novel_interface.hide_character()
	await novel_interface.play_background_flash_effect(Color.BLACK,1,1.0,1.0,[],false)
	await novel_interface.show_text_only("对方压倒的力量顺着球棒施加在我的双手和肩上，正在我咬牙抵抗时蒙面人突然一记踢击。")
	await novel_interface.play_background_flash_effect(Color.BLACK,1,0.15,1.0,[Color.RED],true)  
	await novel_interface.show_text_only("脚狠狠踢在了我毫无防备的腹部。")
	await novel_interface.play_background_flash_effect(Color.WHITE,1,0.15,1.0,[],false)
	novel_interface.show_background("res://assets/images/bg/Baizhu/white_bg.png")
	await novel_interface.show_text_only("被踢中的我飞出并撞断了护栏，径直摔到了下一\n层。")
	await novel_interface.play_background_flash_effect(Color.RED,1,0.15,1.0,[Color.BLACK],true)
	await novel_interface.show_text_only("啊！！！！！！")
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("妈的，那个偷袭我的小鬼摔到楼下去了。\n我去宰了他！", "蒙面人A")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_male","hurt")
	await novel_interface.show_dialog("……我得快逃……\n……得藏到…那个展品的…阴影里去……",player_name)
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Shot/BG_RC_stairway.png")
	novel_interface.show_character("soldier_1")
	await novel_interface.show_dialog("等等…队长刚发来通知，自爆防盗装置解除成功了", "蒙面人B")
	await novel_interface.show_dialog("别浪费时间，马上去会议厅集合！\n等他醒来咱们早就撤了。", "蒙面人B")
	await novel_interface.hide_character()
	novel_interface.show_character("soldier_2")
	await novel_interface.show_dialog("是！", "蒙面人A")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	novel_interface.show_character("ren_male","hurt")
	await novel_interface.show_dialog("意识……渐渐……模糊了\n莉琉……",player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("与此同时 在会议厅")
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_liliu_instConfRoomWatching.png")
	await novel_interface.show_dialog("看来这群人是靠光学伪装混进来的……","莉琉")
	await novel_interface.show_dialog("竟然利用了收容所反光学侦测设施部分检修的时段看来内部有人走漏了风声。","莉琉")
	await novel_interface.show_dialog("还不清楚是什么来头……只能等待机会了。","莉琉")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_conferenceRoom.png")
	novel_interface.show_character("soldier_leader")
	await novel_interface.show_dialog("哼哼哼哈哈——","蒙面人首领")
	await novel_interface.show_dialog("我们终于取回了……！", "蒙面人首领")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Shot/BG_Shot_liliu_instConfRoomWatching.png")
	await novel_interface.show_dialog("那是——『洛斯金杯』！？","莉琉")
	novel_interface.change_background("res://assets/images/bg/Shot/losgrail.png")
	await novel_interface.show_text_only("考察团从突然出现在太平洋中部的洛斯群岛上找到的『异质物品』，杯子外面镶着四块宝石。")
	await novel_interface.show_text_only("杯子里有红色的液体状物质，但这些物质既无法倒出又无法触碰，就像幻影一样似乎不存在实体……")
	await novel_interface.show_text_only("研究所的老头子们用尽了各种办法没搞明白那是什么东西……")
	await novel_interface.show_text_only("一段时间后就将它的威胁等级降到了『Safe』\n允许进行公开研究了……")
	await novel_interface.show_dialog("嘁，也就那几颗宝石看来还值点钱。","莉琉")
	await novel_interface.show_dialog("不过宝石与杯身在分子水平上融为一体……","莉琉")
	novel_interface.show_character("soldier_leader")
	await novel_interface.show_dialog("就由我来分离，这不洁之物！！", "蒙面人首领")
	novel_interface.character_dark()
	await novel_interface.show_dialog("分离？怎么做得到——","莉琉")

	print("=== 第一章第3话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
