# side02_ep4.gd - 新年彩券屋篇第4话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	side02_ep4_script()

func play_script():
	pass

func side02_ep4_script():
	novel_interface.change_background("res://assets/images/bg/401/BG_401BeachHotel.png")
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	await novel_interface.show_text_only("海风、海鸥、海浪。")
	await novel_interface.show_text_only("夕阳照耀着海边的沙滩，在细细的沙砾上折射出金子般的光泽。")
	await novel_interface.show_text_only("莉琉半卧在松软宽大的床上，慵懒的望着远处的风景。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("不愧是南半球，新年是夏天啊。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她端起插着小阳伞的菠萝鸡尾酒喝了一口，身体不禁舒展开来，在靠垫中陷得更深了些。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("难得来海边，你不去游泳吗？", "爱衣")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("科学院那群天天泡在研究中心的大叔们可是热切期盼着看你的穿泳装呢。", "爱衣")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("那群变态，外面那么热我才不去。", "莉琉")
	await novel_interface.show_dialog("你在今晚会议上演的演讲如何了？\n那个实验项目……", "莉琉")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("收效远超预期呢！就是不知道小怜她们喜不喜欢这种新年礼物……", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣说着端起莉琉的鸡尾酒喝了一大口，被呛得眼皮直跳。")
	novel_interface.show_character("ai","blush")
	await novel_interface.show_dialog("这酒好烈！", "爱衣")
	await novel_interface.show_dialog("……身为SID的主管这么懈怠真的没问题吗？", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉继续陷在靠垫堆里，动都懒得动一下。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("我现在只是来参加学术会议顺便休假的科学家，别让我想那么多。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("联合议会的航母就停在近海，安保问题也不用我来操心，我只要喝酒就可以了。", "莉琉")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("你喝这种东西，不会是想在会场上撒酒疯吧？", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉默不作答，稍稍侧过身去，指着海岸线最远处的一片阴影没好气的说道。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("一群自称科学家的神经病聚在一起讨论要如何登陆到那种鬼地方，骂人才是正常的吧。", "莉琉")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("反正元老院对境外领土和海域一直持中立不侵犯的态度，咱们只要做做样子就好。", "爱衣")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("她们几个倒是玩的挺开心的，那个彩券屋我早就想试试，一直没找到合适的实验对象……", "莉琉")
	await novel_interface.show_dialog("目前总共试出了多少种奖品来着？", "莉琉")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("我们只是抽了最安全的四五等奖，但还是得到了意外的收获。", "爱衣")
	novel_interface.change_expression("blush_dizzy")
	await novel_interface.show_dialog("小怜真是个宝藏呐……", "爱衣")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("还差得远呢，她身上发生的事我们从来只知道结果不知道原因。", "莉琉")
	await novel_interface.show_dialog("而且那个笨蛋的运气每次都出奇的好。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("可真要进行什么复杂操作的话，搞不好会把新丰洲全境都变成那种鬼地方。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉直直的盯着远处海平面上那片浮动的阴影。")
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("反正这次就当做新年历险啦，她们几个都被折腾了一天。", "爱衣")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("四五等奖的彩票后面都有小字写着解决方法吧，虽然和花纹混在一起没那么容易发现……", "莉琉")
	await novel_interface.show_dialog("没想到还发现了新的环境。", "莉琉")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("那个浴场？\n你也说过嘛，小怜的运气一直好得出奇。", "爱衣")
	novel_interface.change_expression("dizzy")
	await novel_interface.show_dialog("好啦好啦，难得的假期，别老把脑筋绷那么紧～", "爱衣")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("可惜的是，我还挺想看看她们几个出糗的样子呢。", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉轻轻笑了笑。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("看还是能看到的……", "莉琉")
	await novel_interface.show_dialog("我记得有个奖品是自己绝对脱不掉的兔女郎装吧？", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("新年新气象。回去一定要给她试试……", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.hide_background() 
	await novel_interface.stop_music() 
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("指挥室内空无一人，只有系统主机在默默运转。")
	await novel_interface.show_text_only("深海中采集回的样本，静静的呆在玻璃容器中，仿佛从来都没有减少过。")
	await novel_interface.show_text_only("那来自未知生物的未知力量，仍旧静静的在等待被彻底挖掘。")
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	await novel_interface.show_text_only("大屏幕上的检测数据在不停的刷新，右下角的时间标签不知不觉跳到了新的一年。")
	await novel_interface.hide_background() 
	await novel_interface.show_text_only("法贝拉做了个甜甜的梦，在梦里她和那个曾被自己视作父亲的人并肩坐在大坝上看夕阳。")
	await novel_interface.show_text_only("索娅在梦中又看到了那束金色的光，但这一次她不再感到孤独和害怕。")
	await novel_interface.show_text_only("艾米莉欧梦见了自己的父母，和她一起生活在和平安乐的故乡。")
	await novel_interface.show_text_only("白烛翻了个身，牛奶在她的梦境中抱着口琴在轻声吹着那熟悉的旋律……")
	novel_interface.show_background("res://assets/images/bg/APT/bedRoom.png")
	await novel_interface.show_text_only("每个人都有着属于自己的，美好的、憧憬的梦。")
	await novel_interface.show_text_only("或长或短，或许宏大到不切实际，都不会随着简单的年份更迭瞬间成真。")
	await novel_interface.show_text_only("但这些梦，无论真实或荒谬，都让人生变得充满希望和色彩。")
	await novel_interface.show_text_only("即使表面看来，像是一个个棘手的麻烦。")
	await novel_interface.show_text_only("但也可能……这是等待被送出的礼物呢？")
	novel_interface.show_background("res://assets/images/bg/Stardust/BG_Stardust_Sways.png")
	await novel_interface.show_text_only("新的一年，一起充满期待吧。")

	print("=== 新年彩券屋篇第4话结束 ===")
	print("=== 新年彩券屋篇 完结 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
