# side02_ep3.gd - 新年彩券屋篇第3话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	side02_ep3_script()

func play_script():
	pass

func side02_ep3_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("无边无际的黑暗，完全看不到尽头，纯粹到让人完全失去探索边际的欲望……")
	await novel_interface.show_text_only("在一片混沌中，我眼前慢慢浮现出大家的身影，却完全看不出光源在何处。")
	novel_interface.show_character("anne_uniform","unhappy")
	await novel_interface.show_dialog("头好疼……刚才我们是怎么回事？", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("kiriseki","think")
	await novel_interface.show_dialog("我记得咱们最开始在餐厅，然后……", "雾夕")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("等等，最初我们是怎么到餐厅的？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔困惑的捂着脑袋，似乎在努力梳理着自己记忆中的矛盾点。")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("之后咱们不知怎么都被传送回了家里……？", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("iluka_normal","worry")
	await novel_interface.show_dialog("好像吃了好多东西，可还是很饿呐……", "伊露卡")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("伊露卡遗憾的揉了揉自己的肚子。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("我想起来了，咱们不是应该退回到现实世界中吗？难道有什么任务没有完成……", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("等等，仔细想来刚才最诡异的是我们自己吧……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮故意把声音压低，表情也十分凝重。")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("为什么我……不，我们所有人，刚才都能理所当然的接受那些明显有悖常理的情景呢？", "安妮")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("从被传送回家的那一刻起，咱们就应该瞬间警觉起来，意识到发生了非常严重的事件。", "安妮")
	await novel_interface.show_dialog("但我们仿佛做游戏般，瞬间接受了这样的设定……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我、拉斐尔、安妮和雾夕互相确认了一下眼神，表情都不由得严肃起来。")
	novel_interface.show_character("kiriseki","speak")
	await novel_interface.show_dialog("是某种幻术吗？", "雾夕")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("雾夕捻了捻手中的符纸，却不知面对无形的敌人要如何驱魔。")
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("也可能是梦境……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("无论是在南极还是播磨脑研的潜脑设备上，我似乎都经历过“忘记自己怎么来到这里”的情况。")
	novel_interface.show_character("ren_uniform","uneasy")
	await novel_interface.show_dialog("不过说到能让人理所当然的接受奇怪的设定，好像某部动画片也有一集类似的……","小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("——或者是异质物！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮突然的发言打断了我的思绪。")
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("能在我们毫无察觉的情况下影响到我们的意识……", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("模因类异质物！？", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("是那个彩券屋吗？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("果然天下没有免费的彩券！")
	await novel_interface.show_text_only("拉斐尔快速检查了一下自己的手机和腕表。")
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("手机没有电，大使馆给我的应急腕表也无法发射求救信号——", "拉斐尔")
	await novel_interface.show_dialog("咱们现在困在这片黑暗空间中，但在这里似乎我们的思维不会被影响。", "拉斐尔")
	novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("不一定，模因的特点就是即使你已经被感染依然觉得自己很正常，还是得尽快脱离这里。", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("小怜，你的那些彩券还在身上吗？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我把手伸进口袋，几张卡纸的感觉十分清晰。")
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("在！还有……大概七张吧。", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("看来想摆脱这种状况的话，还要再来上几次。", "拉斐尔")
	await novel_interface.show_dialog("我们大概得解决所有奖品带来的麻烦。", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("意思是我们还要进入那种奇怪的世界吗！我现在什么都不想吃了！", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("或许没那么复杂。", "拉斐尔")
	await novel_interface.show_dialog("上个次小怜刮开了三张，只有第一张附带环境，之后的几张都单纯只有奖品。", "拉斐尔")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("换句话说，如果我们愿意，可以把所有的彩券都一起刮开。", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("但如果刮开太多，只怕问题会很麻烦……", "小怜")
	await novel_interface.show_dialog("不知道还会抽到什么奇怪的奖品。", "小怜")
	await novel_interface.show_dialog("披萨盒被伊露卡吃掉了，可乐安妮喝完了也没有感到恐惧。", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（而且我内衣的挂钩也撑爆了……）","小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","shy")
	await novel_interface.show_dialog("我记得刚才小怜的胸部……", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("别说那个啦！！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("嗯，确实一张张刮开比较保险。", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔拍了拍我后背挂钩松开的地方，嘴角似乎浮现出一丝丝勉强忍住的微笑。")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","shy_left")
	await novel_interface.show_dialog("总、总总总之不把这些彩券都搞定不行吧，先刮哪一张你来选好了！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我把彩券一股脑塞给了拉斐尔。")
	novel_interface.show_character("kiriseki","smile")
	await novel_interface.show_dialog("随便选就可以，不用紧张。", "雾夕")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("那就……这张？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔抽出一张打算刮开的时候，我忽然想起了那部讲能让人理所当然的接受奇怪设定的动画片。")
	await novel_interface.show_text_only("动画的主题是天才爷爷带着傻乎乎的孙子在宇宙四处冒险——")
	await novel_interface.show_text_only("某一集出现了一种外星寄生虫，能发出脑电波制造虚假记忆，伪装成主角的家人。")
	await novel_interface.show_text_only("简直就像是……")
	novel_interface.show_character("ren_uniform","serious")
	await novel_interface.show_dialog("啊——", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我还没说出口，就感到一阵强烈的下坠感。")
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/401/BG_401ColosseumL.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("这里是……？")
	await novel_interface.show_text_only("再次睁开眼时，我看到房间内摆放着长椅，应该是休息室或者准备室吧。")
	await novel_interface.show_text_only("看着彩券上的奖品名称，我开始有些不那么赞成拉斐尔的话了……")
	await novel_interface.show_text_only("『百战巨兽』……")
	await novel_interface.show_text_only("非常不妙的名字啊！！！")
	novel_interface.show_character("anne_uniform","frustrate")
	await novel_interface.show_dialog("这个地方……背景时代会不会离我们太久了？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我顺着休息室的窗口望了出去。")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("这里……是斗兽场吗？！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("整座斗兽场看起来就像属于公元一世纪时古罗马帝国的样子，简单的由大块的石头搭建而成。")
	await novel_interface.show_text_only("与我们印象中唯一有些出入的，便是石头没有那么年代沧桑，仍然是青灰色的样子。")
	await novel_interface.show_text_only("但墙上的一些标识，还是带有着工业时代之后的印记，不免让人有些时空错乱。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("总之集中精力解决这次的问题吧，这次的奖品是什么？", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("奖品……可能是个大麻烦。", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我低下头，仔细读着彩票的奖品说明。")
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("『百战巨兽』是战争中幸存的王者怪兽，历史战绩百战百胜。", "小怜")
	await novel_interface.show_dialog("看这样的环境……不会是要把这东西打败吧！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("……会不会太直接了？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("抱歉！我完全不想知道对面的兽笼里关着的是什么东西。")
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("听起来比吃光500张披萨难度要小呢，是个好机会，争取在这个场景多刮开几张卡。", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("？？？？？？","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔的脑子是不是被什么东西影响了？\n还是说这才是见过世面的大小姐的气派吗？")
	await novel_interface.show_text_only("拉斐尔没等我阻止，立刻刮开了下一张彩券。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("下一张的奖品是……『全垒球棒』？\n功能似乎是每一记击打出的球都是全垒打。", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("是被信息统合思念体的对有机生命体接触用人形联系装置开过光的那种球棒吗？")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("那是不是只要不打出全垒打就好了？", "拉斐尔")
	novel_interface.change_expression("jeer")
	await novel_interface.show_dialog("安妮，对于你来说应该是小问题吧？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("这是哪来的自信啊！")
	await novel_interface.show_text_only("拉斐尔把突然出现在桌子上的球棒递给了安妮。")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("如果设定就是百分百都是全垒打，那可能稍微有点技术难度……", "安妮")
	novel_interface.change_expression("unhappy")
	await novel_interface.show_dialog("不过规则不一定是要用它打出非全垒打吧？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮虽然做出思考的样子，但言辞中显然不认为这是个困难的任务。")
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("总之我相信你一定能解决啦！\n那么继续刮～", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("还刮？！！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔拿出下一张彩券——")
	await novel_interface.show_text_only("可还没等她刮开，休息室侧面的墙壁就像车库大门一样打开了。")
	novel_interface.change_background("res://assets/images/bg/401/BG_401Colosseum.png")
	await novel_interface.show_text_only("然后休息室的地板开始向外移动，我们顺着被推到了竞技场内侧。")
	await novel_interface.show_text_only("我们站在竞技场内墙边缘，耳边传来一阵阵观众的喝彩声。")
	await novel_interface.show_text_only("然而看台上分明一个人影都没有！")
	await novel_interface.show_text_only("我们还在不知所措的观察着环境，空中突然传来一阵经扩音器放大后带有电流噪声的声音。")
	await novel_interface.show_dialog("欢迎大家来到今天的战斗现场！", "解说")
	await novel_interface.show_dialog("我知道你们每个人都期待已久，渴望再次看见我们战神威武的身影。", "解说")
	await novel_interface.show_dialog("希望你们一周的等待是值得的！让我们有请——战神帕克！！！", "解说")
	await novel_interface.show_text_only("伴随着不存在的观众山呼海啸的喝彩声，场地另一侧的兽笼缓缓打开。")
	await novel_interface.show_text_only("虽然还没见到样子，但漆黑的空间传出的沉重脚步声听得我直冒冷汗。")
	await novel_interface.show_dialog("而我们今天的挑战者……是一群美丽的妙龄少女！", "解说")
	await novel_interface.show_text_only("我们被挟持着来到场内，四周欢呼的声音几乎消失不见。")
	await novel_interface.show_dialog("在经历了178次屠杀之后，我们勇猛的战神，今天又会带来怎样的血腥盛宴，让我们拭目以待！", "解说")
	await novel_interface.show_text_only("观众的欢呼声渐渐压低，似乎在静悄悄的等待我们被那个东西碾碎。")
	await novel_interface.show_text_only("然而当我们真的面对那只怪物的时候，却都有些傻眼——")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("那、那东西……不是生物吧？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("这只所谓的巨兽，竟然是一只浑身散发着金属光泽的，体型巨大无比的机器蜘蛛！！！")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("啊啊啊啊不、不要过来啊！！", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我也搞不清楚刚刚还自信满满的拉斐尔，是被这只巨兽搞怕了，还是只是单纯的害怕蜘蛛。")
	await novel_interface.show_text_only("……反正我是都害怕！！")
	await novel_interface.show_text_only("然而有人一点都不怕——")
	await novel_interface.show_text_only("我还没反应过来，雾夕就二话不说的朝着蜘蛛冲了上去。")
	novel_interface.show_character("kiriseki","speak")
	await novel_interface.show_dialog("被怨灵淤积的怪物，接受你的惩罚吧！", "雾夕")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("雾夕将符纸像飞镖一样射向蜘蛛的腿部，每张符纸打到蜘蛛后都会爆开一团火焰。")
	await novel_interface.show_text_only("但蜘蛛似乎并不在意这种程度的攻击，它只是简单的抬了抬腿，雾夕就被迫后撤回来。")
	novel_interface.show_character("kiriseki","think")
	await novel_interface.show_dialog("不行……普通攻击完全打不动它呢。", "雾夕")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("怎、怎么办？！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我转头看向拉斐尔，却发现刚才还意气风发的她已经和伊露卡吓得抱作一团。")
	await novel_interface.show_text_only("喂喂……")
	await novel_interface.show_text_only("好在那蜘蛛也没有要扑上来的意思，反而缩回了洞口，用红色的眼珠幽幽的看着我们。")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("看我的吧！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮一边说，一边拉住我的手。")
	await novel_interface.show_text_only("按照我们早已形成的默契，这个动作说明她要放大招了。")
	await novel_interface.show_text_only("只不过这次她手上拿着的是刚才拉斐尔交给她的那只球棒——")
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("DARK☆ANGEL无限超合金HOME★RUN！！！", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("（要用那招吗！？）","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮能变出一个魔法棒球，打到目标后会分裂成三个球产生后续攻击，如果暴击就会再次分裂。")
	await novel_interface.show_text_only("忽然，我感到一股巨大的力量从身上抽离，我脚下发软几乎虚脱了过去。")
	await novel_interface.show_text_only("只见安妮“叮”的一记大力击球，棒球卷着烟尘电光火石般飞进了蜘蛛的兽笼。")
	await novel_interface.show_text_only("“轰”的一声过后，蜘蛛传出了痛苦的嘶叫。")
	await novel_interface.show_text_only("全场鸦雀无声。")
	await novel_interface.show_text_only("那个球棒的属性是打出的球100%造成全垒打，如果把全垒打理解成暴击的话……")
	await novel_interface.show_text_only("棒球在封闭空间里不停的反弹，每次击中都会分裂成三个。")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("（岂不变成……核裂变？）","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("漆黑的兽笼里开始不停传出“嘭嘭啪啪”的声音。")
	await novel_interface.show_text_only("随后就像放上千响的鞭炮一样，声音越来越快越来越密，直到竞技场的墙体都开始跟着震动起来。")
	await novel_interface.show_text_only("观众席传出不安的躁动。")
	await novel_interface.show_dialog("怎……怎么回事？！", "解说")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("那蜘蛛估计早已经变成金属碎屑了吧～", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("几秒钟后，先是三四个棒球快速飞出兽笼，紧接着几百上千只球一起飞了出来！")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("这也可以？！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("成千上万的棒球互相弹射，从洞口飞出后遮天蔽日的飞向了我们……")
	await novel_interface.hide_background() 
	await novel_interface.stop_music() 
	await novel_interface.show_text_only("在球要打到我们的瞬间，世界顿时陷入一片漆黑。")
	await novel_interface.show_text_only("这熟悉的感觉……")
	novel_interface.show_character("ren_uniform","wail")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_dialog("解、解决了？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("虽然拉斐尔刚才被吓得不清，但事情确实如她所说十分轻松的就解决了。")
	novel_interface.show_character("kiriseki","smile")
	await novel_interface.show_dialog("安妮，你刚用的招数真是玄妙，那是……", "雾夕")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","shy")
	await novel_interface.show_dialog("呃……其实我也没想到会变成那样，不过总之这就是棒球手的直觉吧！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("原来你是蒙的吗！")
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("为什么非要是蜘蛛啊！！", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("总觉得被吓得缩成一团的拉斐尔莫名的有点萌。")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("好啦好啦，没事啦……", "小怜")
	await novel_interface.show_dialog("还好彩券抽出那只球棒，不然还真不好对付呢。", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔稳定了一下心神，刚才的大蜘蛛对她的影响似乎很大。")
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("快点紧解决完，逃出这鬼地方吧。", "拉斐尔")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("下个场景可别再出现什么可怕的东西了！", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("我倒是希望下个场景可以轻松愉快一些……", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("那这次我来刮吧！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("说着，我刮开了下一张彩券。")
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/401/BG_401Museum.png")
	novel_interface.change_music("res://assets/audio/music/unkown/UI_Main_Funk.mp3")
	await novel_interface.show_text_only("好像这次不是什么野蛮的地方了。")
	await novel_interface.show_text_only("回过神来的时候，我们已经置身在一家博物馆里。")
	await novel_interface.show_text_only("可能是藏品不够丰富的原因，偌大的场馆显得有些空旷，只有一些照片和纪念品陈列其中。")
	novel_interface.show_character("ren_uniform","uneasy")
	await novel_interface.show_dialog("博物馆总比斗兽场好，大不了多动动脑筋嘛。", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我一开始还很庆幸，直到看到彩券上的文字说明。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("博物馆搞不好很难，甚至有可能让我们改写什么奇奇怪怪的历史啊。", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("我倒是觉得这是今天最正常的一件奖品了。", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("这座博物馆没那么危险，不过一点都不正常。", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("因、因为……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我感觉自己的脸已经烧起来了。")
	await novel_interface.show_dialog("这间博物馆的名称叫做『童年博物馆』……", "小怜")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("误，这里主题是小怜的童年吗？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我刚才为什么要手欠自己刮啊！！")
	await novel_interface.show_text_only("如果被她们看见我的童年，那我还是男孩子的日子不是全都被她们看光了吗！")
	await novel_interface.show_text_only("不、不会出现我的上网浏览记录吧……")
	await novel_interface.show_text_only("然而没等我开口，其他人已经津津有味的对展品开始了点评。")
	novel_interface.show_character("kiriseki","smile")
	await novel_interface.show_dialog("原来小怜之前是男孩子哦。", "雾夕")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("不过现在无所谓啦，大家都是好～姐～妹～", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔看着我在漫展买的画本封面，脸有些泛红。")
	novel_interface.show_character("anne_uniform","shy")
	await novel_interface.show_dialog("啊，原来你是那个网站的Premium会员吗？！\n啧啧……", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("啊啊啊啊不许看！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("（小声）回家之后账号借我用一下。", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("切，没想到你小时候还会对着电线杆尿尿啊……\n果然男人和狗没什么区别。", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("不是这么分类的吧！！")
	await novel_interface.show_text_only("就连伊露卡都对我小时候玩的玩具产生了极大的兴趣——甩着由几十个回形针连起来的链子玩。")
	await novel_interface.show_text_only("那不是我小时候自己做的“蜘蛛丝发射装置”吗！")
	await novel_interface.show_text_only("把整盒回形针连起来然后折叠放回原来的小盒，端用胶带固定住，另一端露出盒子。")
	await novel_interface.show_text_only("然后把小盒绑在手腕上，找适当的时机当着小伙伴的面一甩手，就能甩出整条金属链，中二感爆棚。")
	await novel_interface.show_text_only("虽然能享受大家片刻惊讶目光，但把链子收回去再次发射要收拾20分钟左右，整个过程非常丢人。")
	await novel_interface.show_text_only("我赶忙拉住伊露卡，试图阻止这场公开处刑。")
	await novel_interface.show_text_only("经过一些不可描述的暴力场面之后，她们终于停下了这场过度羞耻的现场大起底。")
	novel_interface.show_character("ren_uniform","shy_left")
	await novel_interface.show_dialog("好了啦！还是快想想怎么离开这个梦境吧！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("我没有任何思路……这里就像迷宫一样。", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("不过这里面的东西都是切实存在的啊，带你缅怀一下儿时的样子不也挺好……", "拉斐尔")
	await novel_interface.show_dialog("你又不可能把丢掉的东西找回来～", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("你说丢掉的东西是“童年”吧！")
	await novel_interface.show_text_only("可她说这话的时候为什么一直盯着我两腿之间啊！")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("那……我再刮两张看看有没有什么新的帮助？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我刮开第一张彩券，随后收到了一件……")
	await novel_interface.show_text_only("女仆装……")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("嗯，这件衣服可是一个让你很好摧毁童年养成的男性自觉的东西呢……", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("也可能她是男孩子的时候就想穿穿看？", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("总之快换上吧，没准我们就能出去了。", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("那可不一定——万一勾起了她从小就希望穿女装的回忆，这个记忆宫殿可就更深刻了。", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("反正奖品都要使用，先穿上再说～", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("这件衣服不是和我打工时候的一样吗？我不穿！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("穿不穿！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮掰了掰手指关节，一副要亲自操刀的架势。")
	novel_interface.show_character("ren_uniform","shy_left")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.show_dialog("那你们……", "小怜")
	novel_interface.change_expression("shy_right")
	await novel_interface.show_dialog("能不能转过去？", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("你有什么好害羞的啊！！？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("……")
	novel_interface.show_character("ren_maid","shy")
	await novel_interface.show_dialog("唔……感觉也太奇怪了！\n（比我原来那件的胸部勒得更紧啊……）", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("kiriseki","smile")
	await novel_interface.show_dialog("意外的合身呢。", "雾夕")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("果然没用吧。", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","shy")
	await novel_interface.show_dialog("我其实只想看她穿女仆装……可惜现在手机用不了没法照相啦。", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("你你你！！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("如果穿上也没用的话，那就继续刮？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我再次拿出彩券，刮开后是『好梦药剂』四个字。")
	novel_interface.show_character("iluka_normal","speechless")
	await novel_interface.show_dialog("啊呜……奖品呢？", "伊露卡")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("每次不都是立刻出现吗？", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_maid","shy")
	await novel_interface.show_dialog("那、那个……", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("好像在我的胸部中间夹着……刚才忽然冒出来的东西。", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我把那突然出现的奖品拉出来，上面是一瓶标示着『好梦药剂』的小玻璃瓶。")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("“可以唤起你最珍贵的记忆……”", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔读着彩券上的说明。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("这个看起来似乎比女仆装有用？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("要是没有这件女仆装，这瓶药剂出现在这个位置的话会因为我原来的内衣被撑爆而直接掉下去吧。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("而且按刚才的思路，管它有用没用，不喝掉估计是离不开这里的。","拉斐尔")
	novel_interface.change_expression("jeer")
	await novel_interface.show_dialog("先给小怜灌了，小怜的童年记忆还没有看够呢，刚好咱们继续。", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_maid","wail")
	await novel_interface.show_dialog("啥？！！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("你们就不能温柔一点吗！！")
	await novel_interface.show_text_only("唔！！！\n啊呜咕咚咕咚吨吨吨吨……")
	await novel_interface.hide_background() 
	await novel_interface.stop_music() 
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/401/BG_401HotSpring.png")
	await novel_interface.show_text_only("这里是……浴场？")
	await novel_interface.show_text_only("我好像有点印象，小时候开在家附近的小澡堂，我妈妈和这里的老板娘很熟。")
	await novel_interface.show_text_only("因为父亲常年不在国内，妈妈常常在晚上带着只有四五岁的我过来洗澡。")
	novel_interface.show_character("ren_nude","shy")
	await novel_interface.show_dialog("（不过我的衣服哪去了啊啊！！）","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("今天的客人特别少呢，我先帮你擦背吧？", "温柔的女性声音")
	novel_interface.show_character("ren_nude","timid")
	await novel_interface.show_dialog("诶——？？！","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("突然传来一个女性的声音，吓得我赶紧背了过去。")
	await novel_interface.show_dialog("哎呀，又不是第一次，还这么害羞。", "温柔的女性声音")
	await novel_interface.show_dialog("来来，坐好～", "温柔的女性声音")
	await novel_interface.show_text_only("她扶着我坐在椅子上，而她就这么坐在我身后。")
	await novel_interface.show_text_only("我完全没有反抗，很顺从的坐了下来，因为真的好久没听到这个声音了，那是我的……")
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	await novel_interface.show_text_only("妈妈……？")
	await novel_interface.show_dialog("本来想带儿子也过来，但他最近迷上了用平板电脑玩游戏，死活赖着不出门。", "妈妈")
	await novel_interface.show_text_only("她一边温柔的擦着我的后背，一边像和老熟人念叨家常似的自说自话。")
	await novel_interface.show_text_only("而我满脸通红的捂着胸部，低着头坐在那里完全不敢回头看她。")
	await novel_interface.show_text_only("妈妈对不起！\n儿子我现在已经有B罩杯了！")
	await novel_interface.show_dialog("不过你上次告诉我的那个方法还挺管用的误，与其限制不让他玩，不如给他设个高难度的目标～", "妈妈")
	await novel_interface.show_dialog("我要他打游戏必须打到SSS评价，结果他玩了20分钟就撅着小嘴说不玩，那样子特别可爱哈哈哈。", "妈妈")
	novel_interface.show_character("ren_nude","normal")
	await novel_interface.show_dialog("诶……？","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("原来妈妈对付我的那招是和别人学的吗？")
	await novel_interface.show_text_only("可后来我能够打到SSS评价的时候，您已经……")
	await novel_interface.show_dialog("他现在还每天都赖着要跟我睡，每次都流一枕头口水，真是的……", "妈妈")
	await novel_interface.show_dialog("可谁让他爸爸天天在外面出差。", "妈妈")
	await novel_interface.show_dialog("那小家伙那么怕黑，只能由我来保护他了～", "妈妈")
	await novel_interface.show_dialog("但他睡相真的可爱啊，我经常会忍不住捏一把呢哈哈哈～", "妈妈")
	await novel_interface.show_text_only("她的话里充满了宠溺，我一直低头不语，强忍着眼泪听她说。")
	await novel_interface.show_dialog("唉～～最近计算中心的工作累死了。", "妈妈")
	await novel_interface.show_dialog("新闻里不是也说了吗，新发现的异质物是一段可执行代码。", "妈妈")
	await novel_interface.show_dialog("结果政府为此投入巨资研发的超级计算机不知为何就是运行不了，主任的脸一天比一天臭了。", "妈妈")
	await novel_interface.show_dialog("好像只要他让我们每天加班就能给媒体和大臣一个交代似的……", "妈妈")
	novel_interface.show_character("ren_nude","normal")
	await novel_interface.show_dialog("啊嘞？","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("难道是埃癸斯……")
	novel_interface.show_character("ren_nude","shock")
	await novel_interface.show_dialog("今、今天是几号……？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("怎么刚过完新年你就忘了，今天是2026年的第一天哦，日子过糊涂啦？", "妈妈")
	await novel_interface.show_text_only("2026年……大灾日那年？")
	novel_interface.show_character("ren_nude","shame")
	await novel_interface.show_dialog("等一下……今年的7月25日千万不要去研究所！不、不然的话……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我猛然转身，妈妈惊讶的表情渐渐消散在雾气中。")
	await novel_interface.show_text_only("可恶，再等一下让我把话说完啊！")
	await novel_interface.show_text_only("妈妈……")
	await novel_interface.hide_background() 
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("哎呦，你醒了？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我居然就这样睁开了眼睛。")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("你梦到什么了呀，怎么好像还哭了。", "安妮")
	await novel_interface.show_dialog("可惜我们在博物馆参观得兴致正高。", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("我好像……梦到我妈妈了。", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("果然……我说那个博物馆里怎么会缺少关于你父母的记忆。", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("我只能听到她的声音，当我回头想去追的时候却怎么也追不上……", "小怜")
	await novel_interface.show_dialog("可能是因为太久没见了吧。", "小怜")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("我、我很想她……", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("iluka_normal","smile")
	await novel_interface.show_dialog("小怜姐姐……", "伊露卡")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("伊露卡的小手拉住了我，安妮也拍了拍我的后背。")
	await novel_interface.show_text_only("拉斐尔咳嗽了几声，打破了伤感的氛围。")
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("我大概知道些你的事，不过现在，你……你不是还有我们吗。", "拉斐尔")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("嗯嗯～", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("话说咱们这就算是出来了？", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("没错，大家都在这里啦～", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("（我怎么记得好像还有个巫女……）","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("不过记不清名字了，大概是错觉？")
	await novel_interface.show_text_only("无论是凭空出现的巫女还是免费彩券屋什么的，大概只有神经病才会相信吧……")
	await novel_interface.show_text_only("傍晚的小巷中，行人逐渐多了起来，灯火初上的道路终于开始有市井之中的烟火气。")
	await novel_interface.show_text_only("两边的小店也渐渐坐满，向出来相聚的男男女女提供者晚间的餐食，有的小店甚至还排起了队。")
	await novel_interface.show_text_only("新年的气氛也逐渐浓厚起来了……")
	await novel_interface.show_text_only("只是路口，就好像从来没有过一间彩券屋的样子。")
	await novel_interface.show_text_only("或许……我们应该趁新年去神社拜一拜？")

	print("=== 新年彩券屋篇第3话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
