# side02_ep1.gd - 新年彩券屋篇第1话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	side02_ep1_script()

func play_script():
	pass

func side02_ep1_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/white_bg.png")
	await novel_interface.show_text_only("嗯……\n好刺眼……")
	await novel_interface.show_text_only("这光线就像滋润万物的起源，一根又一根的穿透我每一寸的身体。")
	await novel_interface.show_text_only("世间诸般事宜，都逃不过这光明的洗礼。")
	await novel_interface.show_text_only("这是从未有过的感受……\n是什么？")
	await novel_interface.show_text_only("即使被刺痛的无法睁开眼睛，我仍然要一探究竟。")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom_daytime.png")
	await novel_interface.show_text_only("……………………")
	await novel_interface.show_text_only("太久没有睡过懒觉，以至于阳光照射的感觉都忘记了……")
	await novel_interface.show_text_only("临近年末，学院给大家都放了假。")
	await novel_interface.show_text_only("而难得的是，莉琉竟然也在这个时间选择了度假。")
	await novel_interface.show_text_only("“年底了，我又不是机器人。”\n“你们自己注意，别莫名其妙被人害死了”")
	await novel_interface.show_text_only("……不然还要中断假期回来帮你们收拾。")
	await novel_interface.show_text_only("于是……我终于享受到了久违的赖床时光。")
	await novel_interface.show_text_only("嗷呜……\n可是还是好困…………")
	await novel_interface.show_text_only("昨晚不该熬夜的………………")
	await novel_interface.show_text_only("都怪安妮……………………")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("昨晚")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("果然放假这种时候，最适合窝在家里打游戏了……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("湿冷的空气拍打在公寓隔音防寒窗上，似乎想将冷气直接注入到室内。")
	await novel_interface.show_text_only("而室内的中央温度调节系统正安静高效的运作，始终将室内温度保持在适宜人活动的26°C上下。")
	await novel_interface.show_text_only("但人的习惯并不会简简单单因为环境就有所改变。此刻我也正如往年一样整个人蜷缩在被炉之中。")
	await novel_interface.show_text_only("不同的是，今年的被炉明显更加拥挤。安妮、伊露卡和拉斐尔，一起把我挤在了这个狭小的角落里。")
	await novel_interface.show_text_only("四人像是被烘干的柔软棉被一样软塌塌趴在被炉上\n，人手一只掌机。")
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("小怜你怎么这么菜！你的操作呢！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("啊……我……我在操作了啊！", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（有哪个男生和三个女孩子窝在一起还有心思操作啊，真是的！）", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("真没劲，还以为你天天打游戏，轻轻松松就能带我们赢。没想到居然还要我们带你……", "拉斐尔")
	await novel_interface.hide_2nd_character()
	novel_interface.show_2nd_character("anne_uniform","panic",0.25)
	await novel_interface.show_dialog("又输了……\n什么嘛……再来再来！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("看着安妮不断的鼓起劲头，我也只好强打精神认真对待了起来。")
	novel_interface.show_character("ren_uniform","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("这种过冬的小玩意儿，真是舒服啊……", "拉斐尔")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("明明屋里并不冷嘛……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("但是瘫在里面的感觉是恒温系统提供不了的。\n我觉得这辈子自己都没这么懒过。", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("（……或许这就是大佬吧）")
	await novel_interface.show_text_only("不过里面确实是很舒服，再加上四个人挤在一起，打着打着就走神了，被骂实在也是正常。")
	await novel_interface.show_text_only("该认真起来了，给她们看看十二年老玩家的实力！但是……好像认真起来也……")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("我说，这种时候该让我的暴鲤龙极巨化才对吧！为什么拉斐尔非要抢着让被克制的沙奈朵极巨化啊！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("这不是理所当然的吗？", "拉斐尔")
	novel_interface.change_expression("jeer")
	await novel_interface.show_dialog("把沙奈朵这种优雅高贵的宝可梦作为主力极巨化是拥有正常审美观念的大多数人的选择吧。", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("还是说你真的想让那么丑的东西极巨化占满我的屏幕？", "拉斐尔")
	await novel_interface.show_dialog("你那只丑到能让鲤鱼王发射破坏光线的暴鲤龙就乖乖蹲在一边补刀就好了啊。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","sprite")
	await novel_interface.show_dialog("外形什么的只是次要吧，明明打团体战肯定要属性和技能强才行啦！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("小怜说得对，虽然我这只是霜奶仙可是我的63只霜奶仙里精挑细选的最强一只哦！", "安妮")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("果然还是安妮比较懂……哎？为什么会有63只霜奶仙？！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy")
	await novel_interface.show_dialog("嗯…嗯……当然是因为那个……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮似乎很不好意思的把视线挪开不看小怜。")
	novel_interface.show_character("anne_uniform","shy")
	await novel_interface.show_dialog("小仙奶根据糖饰时间和旋转方式不同，会进化出不同的样子哦！很厉害吧，一共有63种之多呢！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("安妮你也……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","unhappy")
	await novel_interface.show_dialog("伊布！使用帮助！", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡把游戏机高高举过头顶像是在接收太阳之力\n，接着放在桌子上用力按下按键。")
	novel_interface.show_character("iluka_normal","unhappy")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","sob",0.25)
	await novel_interface.show_dialog("等一下！伊露卡你的伊布怎么可能会使用帮助？！", "小怜")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哦……！哦！那……波克比！给装备了巨大根茎的沙奈朵小姐加血吧！", "伊露卡")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("摔跤鹰人先生也给小怜姐姐的暴鲤龙使用羽毛舞~", "伊露卡")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("谢谢……", "小怜")
	novel_interface.change_2nd_expression("gratified")
	await novel_interface.show_dialog("但是啊…极巨化团体战不能换宝可梦哦……而且学NPC的打法是不对的。", "小怜")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("呜……对、对不起。", "伊露卡")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("伊露卡脸上写满了委屈。\n只敢偷偷的伸出小手牵住我。")
	novel_interface.show_character("iluka_normal","smile")
	await novel_interface.show_dialog("为了小怜姐姐…伊露卡……会继续加油的！", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","blush")
	await novel_interface.show_dialog("……（噗通噗通噗通！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着伊露卡露出的可爱样子，小怜捂着胸口倒在被炉上一动不动。")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("小怜？小怜？！拉斐尔……小怜她……", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("真是的，为什么我要帮这种喜欢幼女的变态女装癖\n啊……", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔挥了挥手，小怜上空开始有点点绿色如雨烛的光点落下。")
	novel_interface.show_character("anne_uniform","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","stare",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("呐~伊露卡~你先拿小怜的手机去玩一会吧~", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮试图使小怜心脏超负荷的真凶暂时远离，而后者则很开心举着手机跑到沙发上缩成一团玩着。")
	novel_interface.show_character("anne_uniform","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("那里面会不会有那些不适合伊露卡看到的东西？", "拉斐尔")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("应该没有吧，而且小怜的相册是加锁的啦~", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("那种123456789当做密码真的有什么意义吗…这个笨蛋还没发觉到大家都猜出了这个密码吧？", "拉斐尔")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("没事，小孩子总不会发现的。", "安妮")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("现在更大的问题是……哄好了伊露卡，我们三个就没法组队了。", "安妮")
	await novel_interface.show_dialog("说好的今天晚上要通宵奋战呢？！", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("你平时如果有打游戏一半努力，在任何一个领域取得成功都是理所应当的事。", "拉斐尔")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("可是现在放假嘛……不打游戏做什么？", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("放假的时候就要在家打游戏吗？", "拉斐尔")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("对呀。", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("……安妮，小怜的性别是不是转到你身上去了？", "拉斐尔")
	novel_interface.change_2nd_expression("jeer")
	await novel_interface.show_dialog("这么大好的空闲时光，明明就应该拿来逛街。", "拉斐尔")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("大晚上逛什么街……就算逛街也明天再说。\n今天晚上必须奋斗通宵！换个游戏！", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("我怎么好像又被随便安排了……", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom_daytime.png")
	await novel_interface.show_text_only("于是……\n我们昨晚就真的……换游戏打了个通宵……")
	await novel_interface.show_text_only("嗷……\n好困……")
	await novel_interface.show_text_only("太阳这么好，也不知道几点了……")
	await novel_interface.show_text_only("我随手抄起旁边的闹钟，看了一眼上面的时间。\n才十点五十嘛……五点钟我才躺下……")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("十点五十了？！\n拉斐尔约的我们十一点在市中心见面吃午饭！")
	await novel_interface.show_text_only("如果鸽了她，我明年一年大概都要被各种毒舌骂死吧！")
	await novel_interface.show_text_only("完了完了……还没有洗澡洗头挑衣服啊啊啊啊女孩子出门好麻烦！！！")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/Soya/Escalator.png")
	await novel_interface.show_text_only("临近年终，市中心的广场上车水马龙。\n到处装点着圣诞树与彩灯，一派浓厚的节日气氛。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("小怜真是的……怎么也学会迟到的毛病了？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("可能是因为……睡过头了吧……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("话说完，安妮也忍不住打了个哈欠。")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("十一点已经很晚了，她还能十二点起不成？", "拉斐尔")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("你怎么也一脸没睡醒的样子，没精神逛街是逛不动的。", "拉斐尔")
	await novel_interface.show_dialog("你看伊露卡，小孩子都不困。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","frustrate")
	await novel_interface.show_dialog("……伊露卡昨天一点就睡着了好吗……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("抱歉！！！\n路上太……太堵了……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("那我下次找家里的车来接你。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("额……不……不用了哈，太麻烦了！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("……下回记得编个像样一点的理由……\n你今天头发都没干……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("……是我不好！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("好了，别浪费时间了。\n快吃完了去逛街，我等新年打折已经等了很久了。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("……拉斐尔你最近也缺钱了吗？\n只能等打折？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("我又不像你，钱全花在游戏上了。\n再说打折购物是一种快感，跟钱多少关系不大。", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("我还买彩券呢。\n我像是很缺那几千万的样子吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("………………", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","frustrate")
	await novel_interface.show_dialog("………………", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","worry")
	await novel_interface.show_dialog("饿……", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("饿就快点走，绕过这幢建筑，再走五分钟就到了。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("……我也想要这么有钱。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","frustrate")
	await novel_interface.show_dialog("没事，你还没睡醒，我原谅你。\n毕竟我也没醒……", "安妮")
	novel_interface.change_expression("relieve")
	await novel_interface.show_dialog("话说我们为什么不直接在店里碰头呢……\n走过去好累……太困了……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("店的位置很不起眼，你们肯定找不到的。", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("放心，本小姐的私藏食肆，不会让你们失望。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street1.png")
	await novel_interface.show_text_only("一行人越走越偏，路也越来越窄。\n逐渐连行人都看不见多少了。")
	await novel_interface.show_text_only("两边临街的店铺也越来越少，我才知道新丰洲市中心还有如此僻静的地方。")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("这种店……真的会好吃吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("你在怀疑我？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("没有没有……\n但是客流这么少，开店一定会赔的要死的。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("隐藏珍馐的店，是不在乎位置的！\n他们家烧肉饭是真的非常好吃，每次去人都很多。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("好了小怜你就姑且信她吧。\n不然我们还要再走回去……", "安妮")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("再说了，这里可能人也没那么少吧？\n毕竟前面还有一家彩券屋呢。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("刚刚才说要买彩券。\n现在居然就在这看见了彩券屋……")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("刚刚你不是说想买吗？呐，送到你眼皮底下了。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("彩券屋看起来是一间小型的移动亭屋。\n由于位置不好，似乎并没有什么人光顾。")
	await novel_interface.show_text_only("搞不懂这种随建随拆搬起来很方便的建筑，为什么会在这么偏僻的小路上展开呢……")
	await novel_interface.show_text_only("明明不远处就是市中心。")
	await novel_interface.show_text_only("而且，房屋侧面的『JUMBOOOO0OOOO!!!!!!』招牌真是透露出浓浓的山寨感啊……")
	await novel_interface.show_text_only("但很明显，此时四个人——包括伊露卡的注意力，都被彩票屋上的两行字吸引了。")
	await novel_interface.show_text_only("——『新年彩券屋』\n——『完全免费，100%中奖，即刻兑现』")
	novel_interface.show_character("ren_uniform","solemn")
	await novel_interface.show_dialog("免费？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","unhappy")
	await novel_interface.show_dialog("还一定中？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("马上就能兑奖？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","speechless")
	await novel_interface.show_dialog("骗子！", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("新年大福利吗？！\n哪有这么好的事情！")
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("咳咳……我觉得伊露卡这次说的就有道理了。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("诶呀怕什么，我们还能被诈骗吗？\n他敢坑我们，我们就把这拆了。他这是自寻死路。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然而在她们俩争吵时，我已经鬼使神差的走到了彩券屋旁边。")
	await novel_interface.show_text_only("出售窗口是关闭着的。\n但贴在玻璃上的奖品目录吸引了我的注意：")
	await novel_interface.show_text_only("『绿色眼药水』清新薄荷感，视力瞬间清晰明澈！（小字备注：注意不要滴在尸体上）")
	await novel_interface.show_text_only("『灵异感可乐』一口，透心凉！凉到手脚冰凉！")
	await novel_interface.show_text_only("『舒爽史莱姆』告别粘腻的感觉，清爽舒适高弹！")
	await novel_interface.show_text_only("『监禁体验卷』与世隔绝的奇妙旅程，全长共251天！")
	await novel_interface.show_text_only("『性别转换器』……")
	await novel_interface.show_text_only("这都是什么鬼！")
	await novel_interface.show_text_only("奖品目录的下方，还有一行小字：\n『皆可为您提供新奇如梦境般的奇妙体验。』")
	await novel_interface.show_text_only("新奇如梦境般……\n很想问他这个梦境包含噩梦吗……")
	await novel_interface.show_text_only("话未出口，彩券屋的窗口突然打开了。")
	novel_interface.show_character("ren_uniform","shout")
	await novel_interface.show_dialog("请问完全免费是……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("话没说完，漆黑的窗口中就递出来了一沓彩券。")
	await novel_interface.show_text_only("彩票看起来很普通，居然是老式的手刮硬卡纸。")
	await novel_interface.show_text_only("最近都是网络开奖，很久没见过这种需要自己刮开的彩券了。")
	await novel_interface.show_dialog("按需自取，多少随意，随心刮开，即刻兑现。", "冰冷的声音")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("是拿多少都免费吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("按需自取，多少随意，随心刮开，即刻兑现。", "冰冷的声音")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.show_dialog("那什么时候刮开都能……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("按需自取，多少随意，随心刮开，即刻兑现。", "冰冷的声音")
	await novel_interface.show_text_only("伴着冰冷的声音与漆黑的窗口，我感觉面前的彩票亭，就像一个黑洞，谁也不知道里面有什么。")
	await novel_interface.show_text_only("心跳其实又快又慌张。但是……这种莫名的诱惑仿佛拽着我的手，鬼使神差般的伸向了窗口。")
	await novel_interface.show_text_only("可能这种力量叫做穷？")
	await novel_interface.show_dialog("按需自取，多少随意，随心……", "冰冷的声音")

	print("=== 新年彩券屋篇第1话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
