# side02_ep2.gd - 新年彩券屋篇第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	side02_ep2_script()

func play_script():
	pass

func side02_ep2_script():
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.change_background("res://assets/images/bg/401/BG_401restaurant.png")
	await novel_interface.show_text_only("十分钟之后，我们抵达了拉斐尔私藏的这家食肆。")
	await novel_interface.show_text_only("小店不大，只有四张桌子。但是每一张桌子上面都满满的坐着四名食客，只留了角落的桌子给我们。")
	await novel_interface.show_text_only("我们在角落坐下。店内时不时的传出惊呼声，以及隐隐约约对食物的赞美。")
	await novel_interface.show_text_only("或许拉斐尔所言不虚，这家店确实很好吃。\n可是……")
	await novel_interface.show_text_only("就连伊露卡的注意力都没有在店里的食物上面。")
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("你什么都没说…彩券亭里的人就把这些奖券递给你了？", "拉斐尔")
	novel_interface.change_expression("thinking")
	await novel_interface.show_dialog("也没要钱？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("对啊……我还想问问他具体情况，但是……里面的人翻来覆去只有一句话。", "小怜")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("“按需自取，多少随意，随心刮开，即刻兑现。”", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("你看清楚那个人的模样了吗？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("没有。\n亭子里面漆黑一片，什么都看不见。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔拿起一张彩券，反复的翻看。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("这不正常。\n里面很有可能有诈。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可是翻来覆去，这种老式的彩券怎么看都只是一张纸啊……")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("不露于外的危险才是危险的真正危险之处哦。\n这种反常情况，我们应该第一时间报告SID。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("……拉斐尔你忘了，莉琉也去度假了。\nSID只有芩教官还在值班。", "安妮")
	await novel_interface.show_dialog("而且以芩的性格……这些东西在她眼里估计都是些小问题。她不会在意的。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("……总之不能放任不管！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("kiriseki","normal")
	await novel_interface.show_dialog("……小怜？", "雾夕")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("好巧，你们也爱吃这里的烧肉饭？", "雾夕")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我抬起头，身着传统服饰的巫女雾夕不知何时正羞涩的站在我们桌子旁边。")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("啊……不是啦，是拉斐尔向我们推荐这里的。\n所以今天才会过来看看。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("kiriseki","smile")
	await novel_interface.show_dialog("他们家在市中心真的蛮有名的，我经常会过来吃。", "雾夕")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("只是……今天又满人了……\n我……我可以和你们拼一桌吗？", "雾夕")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("当然可以啦，巫女大人。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("kiriseki","smile")
	await novel_interface.show_dialog("多……多谢啦！", "雾夕")
	await novel_interface.show_dialog("话说，你们刚刚在讨论什么？\n有什么棘手的事情吗？", "雾夕")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("小怜在一个奇怪的屋子里取出了一些奇怪的彩券。我们正在考虑是否要上报SID。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("kiriseki","speak")
	await novel_interface.show_dialog("奇怪的东西？", "雾夕")
	await novel_interface.show_dialog("难道是又有妖灵祸乱人间！", "雾夕")
	await novel_interface.show_dialog("庇护吾等诸神啊，祓魔！", "雾夕")
	await novel_interface.show_dialog("天方四式，地角八灵，媚妖灵怪，诛灭不迨！缚！", "雾夕")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不止我们四人，就连屋内的食客都开始用奇怪的眼光看着雾夕。")
	await novel_interface.show_text_only("只有彩券完全没有任何异样。")
	novel_interface.show_character("kiriseki","think")
	await novel_interface.show_dialog("唔……", "雾夕")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("雾夕整个脸蛋变得通红，整个身体都因为害羞而扭捏了起来。")
	novel_interface.show_character("iluka_normal","sleepy")
	await novel_interface.show_dialog("饿……", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("彩券看起来似乎没什么问题……伊露卡也饿了，不如我们先点东西吃吧？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("在搞清楚危险之前，不能有丝毫的懈怠。\n虽然看起来没有问题，但反常本身就是问题。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("其实不用那么麻烦……\n想搞清楚，刮开一张看看不就知道了？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("……安妮说的对哦！", "小怜")
	await novel_interface.show_dialog("我们刮开彩券，不就知道这些东西有没有危险了？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("那……那我们先刮开一张看看好了。\n看看这彩票能带给我们什么梦境体验。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我随便抽了一张出来，仔细的揭开上面的覆层。")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("『披萨……派对』？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("接着，四周就瞬间被黑暗所笼罩。")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom_daytime.png")
	await novel_interface.show_text_only("再反应过来的时候，我们……\n回到了家里？")
	await novel_interface.show_text_only("可是怎么有些不太一样？")
	await novel_interface.show_text_only("昨天在家里打了一宿游戏，今天又走的很匆忙，连被子带房屋都没来得及收拾。")
	await novel_interface.show_text_only("可是现在\n屋内的环境却是很整齐，像是被专人打扫过一样。")
	await novel_interface.show_text_only("客厅的电视不知道为什么是打开着的，正在播着从来没有见过的广告。")
	await novel_interface.show_dialog("『快来小凯撒披萨连锁店，尊享千种口味披萨美食\n！』", "电视广告")
	await novel_interface.show_text_only("为什么印象中从来不知道有这么一家……")
	await novel_interface.show_text_only("更过分的是，这条广告居然是循环播放的。\n真……有……钱……")
	await novel_interface.show_text_only("其余四人经过了短暂的失神，也清醒了过来。")
	await novel_interface.show_text_only("她们四周看看，确认了周围的环境，立即变得大失所望。")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("所谓新奇的梦境体验……难道就是这样不知不觉的睡一觉然后再把人送回家吗？！", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("那它为什么不干脆叫回城券呢！", "拉斐尔")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("真是的……购物计划又要泡汤了！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("不过……小怜，你什么时候变得这么爱干净了？\n这可不像你。", "安妮")
	await novel_interface.show_dialog("我第一次知道你的房间居然是这样一个格局。\n原来你的房间这么大啊？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("安妮说的，才是关键……", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("这里并不是我的房间……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("那这里是哪？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("不是，这是我的房间……\n哎呀我该怎么和你解释！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("是你的房间，但是……有人进来打扫过？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("没有人进来过……\n就是……这不是我真正的房间。", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("你们是不是对怎么到的这里一点印象都没有？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("我懂了……小怜的意思是，这里其实就是梦境。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("对对对……就是这样。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("……那这个梦境，真的有点美好哦。\n能把你的房间变得这么干净，梦寐以求吧？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("此时，门铃响起，外面传来了小哥干净的嗓音。")
	await novel_interface.show_dialog("您的外卖！", "外卖小哥")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("伊露卡，你定的？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","worry")
	await novel_interface.show_dialog("不是我……虽然我很饿。", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("那我们有谁定外卖了吗？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一边说着，拉斐尔一边起身去开门。")
	await novel_interface.show_text_only("门外并没有人，只在地上放着一个披萨盒，盒上写着“吃掉它”，下面还有大大的“500”字样。")
	await novel_interface.show_text_only("拉斐尔捡起盒子确认安全之后，将盒子拿了进来。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("我记得，彩券的主题是『披萨派对』。", "拉斐尔")
	await novel_interface.show_dialog("那么不管是谁定的，这大概就是用来开派对的披萨了。", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("真是的，一张披萨怎么可能开起来派对。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔小心翼翼的打开披萨盒，一股浓郁香气扑面而来。")
	await novel_interface.show_text_only("只见一张超大尺寸薄饼底的披萨，配上牛排培根及三文鱼刺身，上面满满铺上一层芝士。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("『小凯撒披萨店』……新丰洲有这么一家店吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("我没印象。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("kiriseki","think")
	await novel_interface.show_dialog("我……我也没有。", "雾夕")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("我只知道，电视上的广告就是他们家的。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("几人转头看向电视，广告一直在循环播放，根本停不下来。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("看起来为了宣传不遗余力啊。", "拉斐尔")
	await novel_interface.show_dialog("说不定连彩票都是这家披萨店为了宣传煞费苦心搞的鬼。", "拉斐尔")
	await novel_interface.show_dialog("打他们的订购电话就知道了。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我拿出手机，拨打了电视上的号码。\n回应我的却只有无限的忙音……")
	novel_interface.show_character("ren_uniform","bored")
	await novel_interface.show_dialog("电话也打不通。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("事情果然有诈。\n尽快报告SID才是正确的选择。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("可是现在…联系不上SID啊。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","hungry")
	await novel_interface.show_dialog("唔……好，好吃！", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("众人转头看向伊露卡。")
	await novel_interface.show_text_only("只见伊露卡一手拿着一角披萨，张开小嘴便是一大口，满脸都是幸福。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("又趁我们不注意在偷吃东西……\n好在没出什么问题。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("而且这至少证明了披萨本身没什么问题。", "安妮")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("大家也没吃饭，不如边吃边分析吧。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我拿起一块披萨，披萨的料很足，看起来口味就应该不错。")
	await novel_interface.show_text_only("当我把披萨送进嘴里的一瞬间……")
	await novel_interface.show_text_only("嗯！好吃！！！！")
	await novel_interface.show_text_only("肉类汁水充盈，三文鱼丰腴，饼皮酥脆，更是带有浓浓的芝士香气。")
	novel_interface.show_character("kiriseki","smile")
	await novel_interface.show_dialog("好吃诶！", "雾夕")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看来大家对这款披萨都很满意，就连拉斐尔也不住的点头。")
	await novel_interface.show_text_only("一张披萨一扫而空，而紧接着，空出的盒子中就冒出了另一块披萨。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("我说嘛……一张披萨怎么能开派对呢~\n这才像样。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("第二张榴莲菠萝蜜的披萨没有在盒子中停留太久。")
	await novel_interface.show_text_only("紧接着出现了第三张……\n第四张……")
	await novel_interface.show_text_only("每一张居然都是不同的口味，并且都非常出色。")
	novel_interface.show_character("kiriseki","smile")
	await novel_interface.show_dialog("虽然没有吃到烧肉饭……但是有如此美味的披萨，也是感觉十分幸福呢~", "雾夕")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("大家都点点头表示同意，只不过因为吃了不少，实在是有些装不下了。")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("这彩券……不错嘛。\n回头我也要去拿一些。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("我们现在过去吧。吃的也差不多了，是时候再次出发继续购物的计划了。", "拉斐尔")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("剩下的彩券回头再刮，这种惊喜，还是不要连续来的好。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可当我们想要开门的时候……却发现门无论如何都打不开了。")
	novel_interface.show_character("anne_uniform","stare")
	await novel_interface.show_dialog("常规的方法都试过了吗？\n那只好试试暴力破门了。", "安妮")
	novel_interface.change_expression("unhappy")
	await novel_interface.show_dialog("哈呀！！！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("说着安妮利落地一脚踢在门中央，能感觉到整扇门都随着冲击力颤动了一下。")
	novel_interface.show_character("anne_uniform","frustrate")
	await novel_interface.show_dialog("……痛痛痛！！！！！！！！！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然而门仍然是纹丝未动。")
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("看来这个梦境……不是想来就来想走就走的地方。", "拉斐尔")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("小怜，从窗户可以翻出去吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("有防盗窗，恐怕不行。\n门都打不开，防盗窗怕是没有希望了。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("那去看看，彩券上有没有写离开方法？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我抽出彩券，在名称下面发现了一行小字。")
	await novel_interface.show_text_only("『由小凯撒披萨连锁店提供，500张披萨现货一次性交付。』")
	novel_interface.show_character("ren_uniform","normal1")
	await novel_interface.show_dialog("没有写任何离开方法。\n只是特别强调了……500张？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔似乎意识到了什么，她连忙扣上盒盖，盖子上那个大大的“500”赫然变成了——")
	await novel_interface.show_text_only("“495”。")
	await novel_interface.show_text_only("旁边的伊露卡偷偷的取走了盒中最后的一块。盒子顶上的数字，也随即变成了“494”。")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("我明白了……\n恐怕……", "拉斐尔")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("我们离开的方法，就是吃光这盒子中不断出现的\n500张披萨。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("……都吃光！\n那我们要吃多久！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("这次体验的设计可能就是这样。\n“吃掉它”就是给我们的要求。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("小怜你要不要试一下再刮一张，看有没有机会带我们去下个场景？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我飞快的刮开了一张，但这次上面的奖品明显是一个名词。")
	await novel_interface.show_text_only("『灵异感可乐』")
	await novel_interface.show_text_only("我印象中在彩券店的奖品目录中见过这个。")
	await novel_interface.show_text_only("看名字大概是会让人感受到恐怖灵异现象存在的可乐。")
	await novel_interface.show_text_only("……最好还是不要招惹吧。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("很明显了，彩票不能带我们跳出一个梦境。\n把500张披萨吃完才是我们唯一的解……", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("不一定啊，这500张只要消耗完就好了。\n丢掉不是也一样吗？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("说罢，安妮抄起整整一张，直接丢出了窗台。")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("乱抛垃圾是要罚款的！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("又不是真实世界，你怕什么……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("盒中冒出了新的披萨。但是盒子顶部的数字却没有任何改变。")
	novel_interface.show_character("anne_uniform","frustrate")
	await novel_interface.show_dialog("看来丢掉并不行，似乎的确没有别的办法了……\n……那么，开始吃吧……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("几个人只能对着披萨开始狼吞虎咽。")
	await novel_interface.show_text_only("开始几张感觉尚可，可又吃了几张，口味就变得奇怪了起来。")
	await novel_interface.show_text_only("再加上吃的过多，逐渐就感觉越来越难以下咽。")
	novel_interface.show_character("kiriseki","afraid")
	await novel_interface.show_dialog("啊，这张披萨上的鱼居然还是活的，好恶心！", "雾夕")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("活鱼毕竟还是食物的范畴……我这张，居然是鼻屎味的……呕……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("小怜你居然吃过鼻屎？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("多味豆里有鼻屎口味啊，因为实在太奇特我就记下了，以便以后避开……", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("谁能想到今天居然可以吃个够……", "小怜")
	await novel_interface.show_dialog("我不行了……我感觉自己吃了好多。\n快看看还差多少……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔关上盒盖，一个令人泄气的“477”写在了盒顶上……")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("不吃了不吃了，这才吃了23张！\n500张会撑死的，我感觉已经吃到嗓子眼了。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("其他人也停了下来，只有伊露卡仍在不停的吃。")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("伊露卡加油！我们出去的希望都寄托在你身上了！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("大概一个小时后。")
	await novel_interface.show_text_only("……伊露卡也在不知疲倦的吃了十几张披萨之后瘫倒在地上，小肚皮鼓的浑圆。")
	novel_interface.show_character("iluka_normal","sleepy")
	await novel_interface.show_dialog("我……嗝……不想……嗝……\n再吃披……嗝……萨了……嗝……", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("嗯嗯，我们都知道你尽力了。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("她再能吃，体型能装下的食物也还是有限的。\n500张对她这样瘦小的体型来说，根本不现实嘛…", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("好了，现在剩下这四百多张……只能在这里等到消化完毕之后再吃了。", "小怜")
	await novel_interface.show_dialog("屋子里有水吗？\n我吃的好渴……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("我也有些渴，但没看到有水呢。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("呐，你可以把这瓶可乐开掉。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("我才不要……那么奇怪的东西……谁知道喝完了会有什么糟糕的感觉……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("那你也可以选择再刮一张，看能不能刮出其它的饮料。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我半信半疑的抽出一张，刮开。\n似乎还真是一种饮料。")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("『丰满纯牛奶』？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("看看说明是什么？", "拉斐尔")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("“牛奶强身健体……丰满立竿见影。”\n“享受绷紧的感觉。”", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("咳咳……", "拉斐尔")
	await novel_interface.show_dialog("听起来不错哦。\n这个蛮适合你的，还没有副作用。", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("边说，边拿起牛奶瓶往我怀里塞。")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.show_dialog("……我……我不需要！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","worry",0.25)
	await novel_interface.show_dialog("就是，小怜一个男孩子，要这个干嘛。\n万一迷倒了其他男生，不就尴尬了？", "安妮")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……安妮你要是想要，你也可以直说的。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy")
	await novel_interface.show_dialog("我，我我是为你好！你想喝就喝吧！！", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"shy")
	await novel_interface.show_dialog("我才不想……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("可是你口渴了。", "拉斐尔")
	await novel_interface.show_dialog("我不认为你的运气会好到第三张还是一瓶饮料。\n这两瓶，二选一，你挑吧。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","shy_right")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("强烈的口渴感轻易战胜了理智。")
	novel_interface.show_character("ren_uniform","shy_right")
	await novel_interface.show_dialog("算了，我还是选牛奶吧。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我拿起牛奶，揭开瓶盖，一股浓郁的奶香就飘了出来。")
	novel_interface.show_character("ren_uniform","shy_left")
	await novel_interface.show_dialog("闻起来还不错，就是期望效果不会太明显……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("随着一口牛奶下肚，乳制品特有的甜香便在我嘴中晕开。")
	await novel_interface.show_text_only("一同晕开的还有……胸前的一股暖流。")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("起效很快啊，肉眼可见！", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("有趣，回头要问问海因里希，有没有如此强效的药品。至少这事，物理操作上是完全做不到的。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我觉得我的脸已经红成了樱桃。")
	novel_interface.show_character("anne_uniform","shy")
	await novel_interface.show_dialog("小怜，感觉怎么样？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("你可以来试试啊！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","shy")
	await novel_interface.show_dialog("哼！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("感觉……胸前热热的……\n再有就是有一些涨……", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("我还是很渴，可是我不敢再喝了！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","mock",0.25)
	await novel_interface.show_dialog("没什么，自信一点。\n拿出你穿女装的勇气来。", "拉斐尔")
	await novel_interface.show_dialog("你现在已经是女孩子了，这个尺寸才算正常。", "拉斐尔")
	novel_interface.character_light(0.35,"sob")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("可是我怕它……过头了啊！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"jeer")
	await novel_interface.show_dialog("相信我，多少人都在梦寐以求。\n所以赶快把它干了吧！", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我一闭眼，仰头一饮而尽。")
	await novel_interface.show_text_only("当我睁开眼睛时，只看见三个人雾夕、拉斐尔与安妮都在捂嘴偷笑。")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("完了……\n这次回去没脸见人了！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我感觉我的某些部位正在飞速的增大。")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("这次可能真的要大过头了，我现在感觉呼吸好辛苦\n！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("……我们忘了一件事。\n小怜穿的还是之前的内衣，尺码可能太小了。", "拉斐尔")
	await novel_interface.show_dialog("一会一定会被撑坏的。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("可是我们手头也没有合适的尺寸了。\n先看看会变成什么样子吧。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("会变成很可怕的样子！")
	await novel_interface.show_text_only("我逐渐看不见脚尖的样子了。不过尺寸还在急剧的膨胀，丝毫没有停下来的迹象。")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("勒的好疼……\n怎么办！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("终于，某些地方不堪重负，“啪”的一声……断掉了。")
	await novel_interface.show_text_only("但随着这一声断裂，我清晰的感觉到尺寸开始肉眼可见的变小，直到恢复成了我熟悉的状态。")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("诶，把内衣撑爆……就能变回来吗？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","mock",0.25)
	await novel_interface.show_dialog("可能你享受过了紧绷的感觉，达到了它的描述，之后效果就自动消失了。", "拉斐尔")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.show_dialog("等等。", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我还沉浸在刚才的羞耻当中，面色通红。\n于是听到这一声也是一愣。")
	novel_interface.show_character("ren_uniform","awkward")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("raphael","stare",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("怎么了？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("如果只要与描述相符效果就会消失……那么，我们是不是不用吃掉500张披萨就可以离开了？", "拉斐尔")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("彩券的描述让我们吃掉500张啊？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("彩券只描述了有500张披萨，而没有说一定要我们吃掉它。", "拉斐尔")
	await novel_interface.show_dialog("写明让我们吃掉的是——披萨盒。", "拉斐尔")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("有区别吗？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("如果我们直接把披萨盒吃掉，我们是不是就完成要求了呢？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔猛地转向伊露卡。")
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("伊露卡，你以后是不是再也不想吃披萨了？", "拉斐尔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_normal","worry",0.25)
	await novel_interface.show_dialog("不想……嗝……了……", "伊露卡")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那现在，只要你把这个盒子吃掉，就再也不会有披萨吃了。", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speechless")
	await novel_interface.show_dialog("真的……？", "伊露卡")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("没等拉斐尔回话，伊露卡便抄起盒子，凶猛的咬了下去。")
	await novel_interface.show_text_only("她眼睛泛着绿光，看来披萨真的给她造成了很深的伤害。")
	await novel_interface.show_text_only("没用几口，披萨盒和里面的披萨就被伊露卡啃得干干净净。")
	await novel_interface.show_text_only("吃完了披萨盒的伊露卡又瘫回到了地板上。\n这次果然没有新的披萨出现。")
	await novel_interface.show_text_only("但是……我们仍然没有离开这里。")
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("为什么啊？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("……可能是……\n可乐还没喝？", "小怜")
	await novel_interface.show_dialog("可乐是在空间中凭空出现的。不解决掉它，这个空间可能还不算彻底完成。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("没想到小怜你还是躲不过这罐可乐。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("呃……我肚子里……完全没地方了！\n不如你来试试？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("我不喝可乐。\n这种东西太不健康，高糖分对身体负担非常大。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","normal2")
	await novel_interface.show_dialog("……那就只有我来喝了。\n总不能让巫女大人来喝。", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("kiriseki","normal",0.25)
	await novel_interface.show_dialog("没关系……我……我喝也可以的！", "雾夕")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("但是喝了之后有可能会看见灵异的事。\n我倒是不怕，可我不知道你怕不怕。", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("灵异……妖灵？", "雾夕")
	await novel_interface.show_dialog("庇护吾等诸神啊，祓魔！", "雾夕")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("巫女大人你冷静一点……\n还是我来吧。一会如果有恙大人帮我被魔就好了。", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("说罢，安妮打开了可乐，干了一大口。")
	await novel_interface.show_text_only("我们在一旁担心的看着她，生怕出了什么差池。")
	novel_interface.show_character("anne_uniform","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","perspire1",0.25)
	await novel_interface.show_dialog("感觉……怎么样？", "小怜")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("没什么不一样的啊……只是感觉屋子里人似乎多了一些。", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("这一句话就够我汗毛倒竖了好吗？")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("你……你快些喝吧……\n避免再出意……意外……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮继续端起可乐灌进肚子里。\n这个速度与幅度，真是为她担心……")
	await novel_interface.show_text_only("喝到快见底的时候，安妮突然打了一个趔趄，险些摔倒。")
	novel_interface.show_character("anne_uniform","frustrate")
	await novel_interface.show_dialog("谁挤我！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("安妮！快！就剩一口了！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可别出差错了！")
	await novel_interface.show_text_only("安妮胆大，我在一边可是已经瑟瑟发抖了。\n人越来越多……这屋子里可就我们这几个人啊！")
	await novel_interface.show_text_only("那剩下的都是什么！")
	await novel_interface.show_text_only("我偷偷瞄了一眼拉斐尔，她虽然表面镇定自若，但细心不难发现，她的手也在微微颤抖。")
	novel_interface.show_character("kiriseki","smile")
	await novel_interface.show_dialog("淘气的小怨灵们，速速退去！莫要让姐姐对你们极尽凶残之能事！", "雾夕")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮稳了稳自己的身形，将最后一口可乐也送到了嘴边，喝了下去。")
	novel_interface.show_character("anne_uniform","frustrate")
	await novel_interface.show_dialog("挤死啦！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("随着安妮的一声呐喊，眼前的房间凭空消失了。")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("我们出来啦！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("欢呼声刚出来，一股异样就出现在我的感觉中。")
	await novel_interface.show_text_only("为什么这黑色的时间会这么久……\n我们不是该回到现实世界吗？")
	await novel_interface.show_text_only("我转过身，却看见同样身处在黑暗中的安妮、拉斐尔、雾夕与伊露卡。")
	await novel_interface.show_text_only("安妮不必说，就连拉斐尔的脸上也尽是疑惑。")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("梦境我们退出来了，可是这又是哪？", "拉斐尔")

	print("=== 新年彩券屋篇第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
