# apocalypse_ep20.gd - 天启篇第20话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第20话剧本
	apocalypse_ep20_script()

func play_script():
	pass

# 天启篇第20话 - 正式剧本
func apocalypse_ep20_script():
	# 开场宇宙哲学思考
	novel_interface.show_background("res://assets/images/bg/Soya/Universe.png")
	await novel_interface.show_text_only("小时候，我总会被各种宏大而富有想象力的假说所吸引。")
	await novel_interface.show_text_only("或许我们是存在于缸中的大脑、或许我们生活在一段虚拟程序中，或许地球是一个小孩的试验……")
	await novel_interface.show_text_only("这些假设让人痴迷、沉醉，浑身起鸡皮疙瘩。")
	await novel_interface.show_text_only("直到有一天，我开始思考──")
	await novel_interface.show_text_only("那个水缸、那个编写程序的人、还有那个小孩，他们所处的世界又是什么样的呢？")
	await novel_interface.show_text_only("其实我们和它们，甚至它们的它们，全都被困在这宇宙之中，谁也无法逃脱。")
	await novel_interface.show_text_only("就像《加州旅馆》中的那句歌词──你可以随时结账，但你永远无法离开。")
	await novel_interface.show_text_only("那些神明在仰望星空时，也与我们一样好奇、一样憧憬、一样恐惧。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("小怜！")
	
	# 小怜醒来
	novel_interface.show_background("res://assets/images/bg/Soya/Lounge.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_dialog("──！！！！", "小怜")
	await novel_interface.show_text_only("被某种刺激性气味惊醒，我发现自己正躺在一张柔软的床上。")
	await novel_interface.show_text_only("爱衣拿着嗅盐在床边看着我，莉琉则站在床尾在用手机录像。")
	await novel_interface.show_dialog("诶诶──？？", "小怜")
	await novel_interface.show_text_only("我连忙擦掉脸上的口水和眼泪，才发现枕头居然被浸湿了一大块。")
	await novel_interface.show_text_only("好像睡了很久，还做了一个很悲伤的梦……")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("小怜的睡相真是蠢得可爱呐~", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉微笑着收起手机，走到床边摸了摸我的额头。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("今天是周六，你已经昏睡十几个小时了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("十几个小时……这是哪？", "小怜")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("──索娅！！", "小怜")
	await novel_interface.hide_character()
	
	# 回忆爆炸
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N2.png")
	await novel_interface.show_text_only("我忽然想起，在那道电光过后变为一团火球的直升机坠落在教堂后面──")
	await novel_interface.show_text_only("我绝望的望着那团冒着浓烟的火光，想喊却喊不出声。")
	await novel_interface.show_text_only("几秒之后，又发生了第二次更剧烈的爆炸……")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("爆炸的冲击把你震晕了……", "爱衣")
	novel_interface.show_background("res://assets/images/bg/Soya/Lounge.png")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("那架直升机的油箱被高压电弧击穿，艾尔加纳和机上的五名士兵都烧成了焦炭。", "爱衣")
	await novel_interface.show_dialog("天国之门的复制品也被烧毁，街上那些灯罩的效果在同一时刻立即消失了。", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣有些惋惜的说道。")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("索娅呢，她怎么样了？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("在场的探员全都目睹索娅乘上了飞机，而且确定坠落过程中没人跳下来……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到这里，我心中一沉。")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("但在残骸中并没有发现索娅的尸体，她在爆炸时应该拿着电池，却连一丁点生物残留都检测不到。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("什么？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("虽然残骸的清理工作不是由SID进行的，但情报应该很可靠的──", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("毕竟我们回收了保安军指挥官的小女儿。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉露出一副得意的神情。")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("（回、回收……？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("而且那种爆炸应该无法损坏异质物加固的脚环，但脚环的信号却突然消失了……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣停顿了一下，看着莉琉。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("就像上次，小怜从方舟基地消失时一样……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到那个词，我不由紧张起来。")
	await novel_interface.show_text_only("那是本是一座战前建成的巨型地下排水设施，莉琉用元老院的经费将其改造成了地下试验基地。")
	await novel_interface.show_text_only("我曾在那个地方召唤出十六世纪的炼金术士海因里希·昆哈特。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/CauseAndEffect.png")
	await novel_interface.show_text_only("接着就和她一起被卷入因果之隙──一个没有时间和方位概念的奇异空间。")
	await novel_interface.show_text_only("当我们离开那个空间时，居然已经到了南极……")
	novel_interface.change_background("res://assets/images/bg/Soya/Lounge.png")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("虽然与索娅的设计有偏差，但或许还有一线生机。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("一线生机……什么意思！\n我、我能做点什么吗！！？", "小怜")
	await novel_interface.show_dialog("还有……她的设计？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("面对我连珠炮似的追问，莉琉无奈的叹口气──")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("你还不知道吗？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("知道什么啊──！！")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("那脚环本来是为了防止假释的犯人逃脱所设计。", "莉琉")
	await novel_interface.show_dialog("每一只这种脚环都具有主动窃听功能，索娅自己肯定也知道这一点。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("所以她明白，自己说的每句话都可能被我所监听。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我疑惑的点了点头。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("回想一下你们昨天的经历──", "莉琉")
	await novel_interface.show_dialog("下午一起逛街的时候，索娅就在细致入微的观察你和伊露卡。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("（确实，在美术馆她还向拉斐尔卖弄……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("在街上看到漂亮的女生，小怜会忽然冒出淡粉色的气息，在不扭头的情况下把眼球转到极限偷瞄。", "索娅")
	await novel_interface.show_dialog("或者假装看向那个女生身后的远方，看够了再把头转向完全不相干的方向，以为这样就能洗清嫌疑。", "索娅")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Lounge.png")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("从美术馆出来后，她向你逼问出女巫与魔导书相关的情报。", "莉琉")
	await novel_interface.show_dialog("其实当时她还透露过教廷对女巫掉落的魔导书残页的处置方法。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("魔导书？是书本之类的吗……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅似乎忽然想到了什么，一幅恍然大悟的样子。")
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_dialog("之前消灭女巫的时候，确实经常会见到书页一样的东西……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅一边回想一边说道──")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("但修道院的嬷嬷说那些东西的感染性太强，圣赦院的人会在事后清理时统一收集焚烧。", "索娅")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Lounge.png")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("圣赦院……？\n（似乎有点耳熟？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("后来你们在电器街见到了贝阿特丽切，她发现你们俩身上都有“很干净的味道”。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣突然插话──")
	novel_interface.show_character("liliu_research","speak")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("之前我也发现，小怜和贝阿特丽切体内的放射性同位素比新生儿从母体继承的还要低~", "爱衣")
	novel_interface.change_2nd_expression("dizzy")
	await novel_interface.show_dialog("共感觉连这种事都能看出来吗？\n真想好好做一番试验呐……", "爱衣")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("结合这些信息，当她在教堂门口向我提出交易要求时就猜到了，但转念一想也不是什么坏事。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉拍了拍我满是问号的脑袋。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("当时她已经决定要成为魔女了吧~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("──！！？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("一开始她宁愿与我合作，也不想被爱衣检查，就是怕自己身体的秘密被发现。", "莉琉")
	await novel_interface.show_dialog("但后来，她用那个秘密只交换了两件事──", "莉琉")
	await novel_interface.show_dialog("第一，要求我解锁了脚环的最大距离，给予自己行动的空间。", "莉琉")
	await novel_interface.show_dialog("第二、她想知道贝阿特丽切和你的关系，为了确保情报的真实性还要求由你亲口讲述。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("我想她早就知道，教廷并没有将魔导书烧掉，而是秘密封存起来。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("就当艾尔加纳在教堂里帮你治疗时──", "莉琉")
	await novel_interface.show_dialog("她去艾尔加纳的房间，偷出圣赦院封存在秘匣中的魔导书残页。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("诶？？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("特工清点艾尔加纳个人物品时，发现那个匣子里已经空了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("确实……艾尔加纳好像问过她……", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N_Door.png")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("索娅，圣赦院封存的秘匣是你打开的吗？", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("……", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("唉──你总是这么管不住自己的好奇心啊……", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Lounge.png")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("当时卫星也检测到，新丰洲纪念教堂突然出现时空相位波动，但只持续不到5秒。", "爱衣")
	novel_interface.change_expression("dizzy")
	await novel_interface.show_dialog("能让魔女之茧瞬间蒸发……果然很有天赋呢~", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("在之后的电话里，她再次向贝阿特丽切确认过她的身份。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("哼哼！小怜全都告诉我了哦~！！", "索娅")
	await novel_interface.show_dialog("你真的是但丁笔下的那个大美人？", "索娅")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Lounge.png")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("不得不说是场豪赌啊……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("不过还好她当时那么做了──", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("还……好？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("成为魔女是很沉重的负担吧……")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("不然在第一大道遇袭时，你以为你们几个是靠什么解围的？", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣的声音逐渐更加兴奋。")
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("要不是我特意改装了一下，当时无人机上的玻尔兹曼探测器就又要爆掉了！！", "爱衣")
	await novel_interface.show_dialog("那像绞肉机一样绚丽华美的──哎呀~", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉重重的敲了下爱衣的头打断她。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("好奇心强的人想要离开安全地带，往往会遭遇比常人多得多的危险。", "莉琉")
	await novel_interface.show_dialog("这时更需要随时观察周围信息，冷静分析并大胆下注，才可能从困境中生存下来。", "莉琉")
	await novel_interface.show_dialog("可能这几年，索娅对艾尔加纳的行为也有预感吧。", "莉琉")
	await novel_interface.show_dialog("她偷走电池的时候，就已经做了最坏的打算──", "莉琉")
	await novel_interface.show_dialog("在乘直升机前用河豚毒素麻痹你，是怕你泄露电击脚环的事情让那些人起疑。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("还在临别前把自己的武器垫在你身后，这就是她的设计──", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("那孩子还是真优秀呢……", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣揉着脑袋上鼓起的包说道。")
	await novel_interface.show_text_only("我的眼睛一亮，马上从床上跳起来。")
	novel_interface.show_character("ren_fishnet","happy")
	await novel_interface.show_dialog("是那个电锯吗！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("如果能像安妮和贝阿特丽切时那样，由我触碰一下武器就将她带回来的话……")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("可能没那么简单……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉走到门口，回头对我说道。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("你准备好就出来吧。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("我稍稍整理了一下，就迫不及待的冲出门──")
	
	 #方舟基地
	novel_interface.show_background("res://assets/images/bg/Baizhu/bedstand.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("欸──", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这里是……")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("方舟基地？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("好久不见啊──主人。", "？？？")
	await novel_interface.show_text_only("等等，这熟悉的称谓……")
	novel_interface.show_character("ren_fishnet","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("heinrich_battle","smile",0.25)
	await novel_interface.show_dialog("听说主人最近在打工做“服务性职业”呢。", "海因里希")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("海因里希？", "小怜")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("别听拉斐尔瞎说！\n我、我……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("一定非常特别吧？改天我也去捧场。", "海因里希")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("请务必不要！！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("主人很紧张呢……难道是那种职业？", "海因里希")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("哪种职业啊！！")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("heinrich_battle","mock",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("怎么你也在这……拉斐尔没和你一起吗？","小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("因为这次的事件和『门』有关，我只是来收集一下研究材料。", "海因里希")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我回想起海因里希似乎说过，她曾用炼金术打开了一扇大门……")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("heinrich_battle","mock",0.25)
	await novel_interface.show_dialog("对了，这是我最近做出来的──", "海因里希")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("海因里希得意的拿出一枚弹球大小的无色宝石。")
	novel_interface.show_character("ren_fishnet","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("heinrich_battle","mock",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哈，这是治愈宝石吗？\n昨天多亏了它呢~~", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("治愈……？","海因里希")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("海因里希似乎有些奇怪，接着恍然大悟的样子。")
	novel_interface.show_character("ren_fishnet","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("heinrich_battle","speechless",0.25)
	await novel_interface.show_dialog("哦──是拉斐尔给你的话，就是治愈效果了。", "海因里希")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("这种宝石就像充电电池一样，可以临时存储一部分魔法效果。", "海因里希")
	await novel_interface.show_dialog("充电和放电的时候，只要与体液接触就可以。", "海因里希")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("体、体液？！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("昨天……主人亲自试过啦？", "海因里希")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("海因里希的脸上露出一个神秘的微笑。")
	await novel_interface.show_text_only("停！不要乱想！！\n不要胡思乱想！！！")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("咳咳──", "莉琉")
	await novel_interface.show_text_only("喇叭中传出莉琉的声音，同时我们面前升起一座通往对面平台的浮桥。")
	novel_interface.show_background("res://assets/images/bg/Soya/Base2.png")
	await novel_interface.show_dialog("我和爱衣在观察室，一会海因里希也上来吧。", "莉琉")
	await novel_interface.show_dialog("电锯已经放在基台上了，规矩你都知道吧──", "莉琉")
	await novel_interface.show_dialog("这次武器系统全都关闭了，如果遇到极端情况可以从基台右侧地板上的安全门进入地下隔离区。", "莉琉")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("只是索娅的话，不用这么兴师动众吧……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("heinrich_battle","smile",0.25)
	await novel_interface.show_dialog("还是小心一点为好。", "海因里希")
	novel_interface.change_2nd_expression("bored")
	await novel_interface.show_dialog("索娅不是说过，她可能被那家伙讨厌了吗？", "海因里希")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那家伙……是你说的『那位大人』？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("那个强迫海因里希用灵魂签订契约的家伙……")
	novel_interface.show_character("ren_fishnet","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("heinrich_battle","bored",0.25)
	await novel_interface.show_dialog("是有这种可能，不过──", "海因里希")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("但如果是主人的话，我相信一定没问题。", "海因里希")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("海因里希用从容而坚定的眼神看着心虚不已的我。")
	novel_interface.show_character("ren_fishnet","uneasy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("heinrich_battle","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("对了，要不要准备点衣服？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("嗯？", "海因里希")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("万一又像你刚被召唤出来时……\n（全、全裸……）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("不过好像贝阿特丽切那次就不是？")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("heinrich_battle","mock",0.25)
	await novel_interface.show_dialog("哈哈哈哈，应该不需要。", "海因里希")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("主人应该是以我记忆中最根深蒂固的印象将我创造出来的。", "海因里希")
	novel_interface.change_2nd_expression("mock")
	await novel_interface.show_dialog("我在工作时习惯保持最天然的状态，这样最利于大脑的思考~", "海因里希")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("天然……的状态？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("等等，你现在也那样在实验室里跑来跑去吗？！")
	await novel_interface.show_text_only("海因里希向我抛了个媚眼，便转身走向通往观察室的电梯。")
	await novel_interface.show_text_only("我压抑着自己的胡思乱想，一路通过浮桥来到基台面前。")
	await novel_interface.show_dialog("准备好了就开始吧──", "莉琉")
	await novel_interface.show_dialog("记得不要太逞强。", "莉琉")
	await novel_interface.show_text_only("看着那个电锯，我不禁紧张起来。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("（万一，什么都没有发生……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然每一次都毫无实感，但我从未如此期待自己的能力可以应验。")
	await novel_interface.show_text_only("感受着自己加速的心跳，我慢慢将手伸向了基台上的电锯……")
	await novel_interface.show_text_only("……")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("──")
	await novel_interface.show_dialog("？", "小怜")
	await novel_interface.show_text_only("在我碰到电锯的瞬间，四周突然陷入一片漆黑──")
	await novel_interface.show_text_only("基地内设备运转的背景噪音也突然消失，周围就这样变得一片死寂。")
	await novel_interface.show_text_only("我甚至能清晰的听到自己逐渐加速得心跳和呼吸。")
	await novel_interface.show_dialog("这是……怎么回事？", "小怜")
	await novel_interface.show_dialog("莉琉？", "小怜")
	await novel_interface.show_text_only("我能感受到重力，而且自己正踩在某个平面上。")
	await novel_interface.show_dialog("（还能呼吸……但说话完全没有回声。）", "小怜")
	await novel_interface.show_text_only("就像置身于空无一物的旷野之中。")
	await novel_interface.show_text_only("在纯黑的环境下我不敢迈步，似乎一脚踏空就会坠入无尽的深渊。")
	await novel_interface.show_text_only("我只能双脚站在原地，伸出手试着向四周摸索。")
	await novel_interface.show_dialog("索娅……", "小怜")
	await novel_interface.show_dialog("索娅──！！", "小怜")
	await novel_interface.show_text_only("在黑暗中，我大声呼喊着她的名字。")
	
	# 门的出现
	novel_interface.show_background("res://assets/images/bg/Soya/Gateseam.png")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_text_only("突然像是回应我的呼唤般，虚空中一道竖直的金色细线将黑暗划成两半。")
	await novel_interface.show_text_only("在黑暗的空间里，从看不到尽头的底部一直延伸到无限遥远的顶部。")
	await novel_interface.show_dialog("那是……门缝？", "小怜")
	await novel_interface.show_text_only("我顾不得脚下马上朝着亮光跑去，却好像怎么跑也无法接近。")
	await novel_interface.show_text_only("不知跑了多久，体力耗尽的我只能双手扶膝盖停下喘着粗气。")
	await novel_interface.show_text_only("完全的黑暗会模糊距离的概念，分不清那道光是近在眼前还是在无限远的地方。")
	await novel_interface.show_text_only("也不知那是希望还是绝望。")
	await novel_interface.show_dialog("小怜……", "？？？")
	await novel_interface.show_text_only("冥冥中传来一个熟悉的声音。")
	await novel_interface.show_dialog("索娅！？", "小怜")
	await novel_interface.show_text_only("我猛然伸出手，那条金线似乎突然就被我拉到我的面前。")
	await novel_interface.show_text_only("我把手伸进门缝中，用力向外拉。")
	await novel_interface.show_text_only("门后那道奇异的金色光芒似乎是光线和声音的混合体，盯着它的时候会有杂乱的噪音涌入脑中。")
	await novel_interface.show_dialog("小怜……", "索娅")
	await novel_interface.show_text_only("索娅的声音就像隔着厚厚的屏障，逐渐被那噪音覆盖，越来越微弱。")
	novel_interface.change_background("res://assets/images/bg/Soya/Openedthegate.png")
	await novel_interface.show_text_only("我用尽全力扒开那道门，眼看缝隙被我越拉越大，那股噪音也越来越强。")
	await novel_interface.show_text_only("停下──！！\n住手！！！！")
	await novel_interface.show_text_only("杂乱的噪音渐渐融为一体，就像无数人在同时对我呐喊。")
	await novel_interface.show_dialog("我管你那么多──！！", "小怜")
	await novel_interface.show_text_only("无视那个巨大意识体的阻挠和咒骂，我用尽全力将门拉开到足够让人通过的程度。")
	await novel_interface.show_text_only("虽然除了刺眼的金光外什么都看不到，但我能强烈的感到索娅就在门的另一侧。")
	await novel_interface.show_text_only("我做了个深呼吸，将胳膊伸进门内，拉住那只柔软手腕的一瞬间我就知道是她──")
	await novel_interface.show_text_only("我一把将索娅拽出来，门内的金光像是被撕开逆鳞的巨龙一般，突然发出凄烈刺骨的嚎叫。")
	await novel_interface.show_dialog("小怜！", "索娅")
	await novel_interface.show_text_only("索娅娇小的身躯在我怀中吓得不停发抖，眼看那道光就要夺门而出将我们吞噬。")
	await novel_interface.show_text_only("我左手轻轻抚着她的头，扭头盯着那道已经泛出微红色光晕的暴怒的光芒──")
	await novel_interface.show_dialog("滚回去。", "小怜")
	await novel_interface.show_text_only("那光就像笼中的猛兽般对我不停愤怒的嘶吼着，却无法越出大门半步。")
	await novel_interface.show_text_only("我伸出右手，将那道门缓缓合上。")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("别碰──", "索娅")
	novel_interface.show_background("res://assets/images/bg/Soya/Handprint.png")
	await novel_interface.show_text_only("索娅一把将我的手拉回来，却发现手掌并没有什么异样。")
	await novel_interface.show_text_only("反倒是门上像烙铁一样，印上了我的手印。")
	await novel_interface.show_dialog("没事。", "小怜")
	await novel_interface.show_text_only("我对她笑笑，继续用力推门，直到光线与声音渐渐消失在黑暗中……")
	
	# 回到基地
	novel_interface.change_background("res://assets/images/bg/Soya/Base2.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("在门完全关闭的同时，周围的光线与背景噪音瞬间恢复。")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("这里是……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅不安的张望着四周。")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("放心，我们回来了。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看到我们，海因里希从浮桥另一侧冲了过来。")
	novel_interface.show_character("heinrich_battle","serious")
	await novel_interface.show_dialog("主人！\n你消失了两个多小时──", "海因里希")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	await novel_interface.show_dialog("主人？", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索娅瞄我一眼。")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("啊？有那么久吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("感觉上只有十分钟左右……")
	await novel_interface.show_text_only("海因里希追问我们刚才的情况，听到我在门上留下手印的时候，忍不住大笑起来。")
	await novel_interface.show_text_only("我看着宏伟的基地大厅，刚刚的一切有种恍若隔世的感觉。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("与此同时，浮桥另一侧。")
	novel_interface.show_background("res://assets/images/bg/Baizhu/bedstand.png")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("在他们回来之前有5秒左右的时间，全世界都接收到剧烈的时空相位波动。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("不过因为信号太过强烈，估计他们无法判断出源头。", "爱衣")#换行问题
	await novel_interface.show_dialog("除非……", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("除非什么？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("除非有人像我这样──", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣将手中的平板设备递给莉琉。")
	novel_interface.show_background("res://assets/images/bg/Soya/Earthperspective.png")
	await novel_interface.show_text_only("屏幕上，一道金红色的光芒穿过大气层直冲天际。")
	await novel_interface.show_dialog("这是……", "莉琉")
	await novel_interface.show_dialog("这道光持续有5秒左右，虽然肉眼无法看到，是我将探测相位波动的卫星调集过来拍到的──", "爱衣")
	await novel_interface.show_dialog("当时我鸡皮疙瘩都出来了，以为世界末日终于要降临了呢。", "爱衣")
	await novel_interface.show_text_only("爱衣的声音有些颤抖，不知是恐惧还是激动。")
	novel_interface.change_background("res://assets/images/bg/Baizhu/bedstand.png")
	await novel_interface.show_text_only("爱衣望着浮桥对面的三人。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("你不是想收编她吗？要不要用保险措施……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉对着平板叹了口气，望向远处正抱住小怜疯狂骚扰索娅")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("暂时……不需要吧。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("第二天。")
	
	# 第二天的报告
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_dialog("今天中午，联合议会的闭门会议结束，并于今天下午一点召开了新闻发布会。", "新闻")
	await novel_interface.show_dialog("发布会上公布了数十项合作计划，第三学园都市总理施恩内曼宣布将在未来三年内逐步裁军。", "新闻")
	await novel_interface.show_dialog("为了应对可能的突发情况，各国同意逐步将一批\nEX异质物运往萨蒙顿进行保管。", "新闻")#换行问题
	await novel_interface.show_dialog("戴克斯博士表示近期将宣布一个重大消息……外界对此猜测不断。", "新闻")
	await novel_interface.show_text_only("莉琉关上了大屏幕上的新闻。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("果然对那么大规模的游行只字不提──", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("索娅的检查结果怎么样了？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("经过爱衣的全面检查，确认索娅体内的那种黑色异质物已全部消失。", "莉琉")
	await novel_interface.show_dialog("不过不像贝阿特丽切和海因里希，她的身体还保持着原来的样子──", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("无论抗体结构和还是体内的放射性同位素，都是\n14岁少女的正常状态。", "莉琉")#换行问题
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到这里我长舒一口气。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("不过奇怪的是，索娅的脚环也消失了，要知道她的衣服上还残留着那些黑衣士兵的血迹……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("是因为脚环上有异质物金属吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("不清楚，不过我从没见过爱衣那么累……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("……啥？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("昨天爱衣的实验室里不断传出不知是大笑还是惨叫的声音，持续了一整晚。", "莉琉")
	await novel_interface.show_dialog("两个人出来时双双累的虚脱，爱衣回办公室在沙发上倒头就睡，现在还没醒。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她们俩到底做了什么啊！！！")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("另外……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉在大屏幕上调出一份档案。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("经过SID和保安军的全面统计，天国之门的感染者总共只有326人。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("……才这么点？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("而且这326人中实际参加游行的只有两百多人。", "莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("可以说正是这两百多个小火星，点燃了总计十几万人的游行示威，并引发了七处暴乱。", "莉琉")
	await novel_interface.show_dialog("人一旦成为群体的一员，他的所作所为就不会再承担责任，每个人都会暴露出自己不受约束的一面。", "莉琉")
	await novel_interface.show_dialog("一个狂热分子顶多能煽动周围的几十个人，但这些人的情绪可以互相加强，并向更广的地方蔓延。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到这里，我不禁背脊发凉……")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("不过我还是想问你，在那个黑暗空间的时候，你怎么知道那道光不会冲出门？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("其实我也不确定……", "小怜")
	await novel_interface.show_dialog("但如果它能自己出来，就不用蛊惑人去开门了吧？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉笑着摸了摸我的头。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("冷静分析，大胆下注……", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("没准你也挺有天赋的呢~", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("过奖了！其实我当时也吓傻了，昨晚回家通宵打游戏一夜都没敢睡……")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("教宗大人似乎对艾尔加纳的研究并不知情，相关经费也都是通过电子加密货币调拨的。", "莉琉")
	await novel_interface.show_dialog("天堂之门原是弗洛伦撒圣约翰洗礼堂的大门，诗人但丁当年就是在那里受洗的。", "莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("唉，可惜在战争中被毁掉了……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("圣……约翰？", "小怜")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("（啊哈哈，只是巧合吧？）", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("（说来，不知道那家伙伤势怎么样了……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	await novel_interface.show_text_only("昏暗的房间内，少年一瘸一拐的拿着手机。")
	novel_interface.show_background("res://assets/images/bg/Soya/Theroom.png")
	await novel_interface.show_dialog("啊──疼疼疼疼疼……", "约翰")
	novel_interface.show_character("john","perspire")
	await novel_interface.show_dialog("唉，还是太冲动了啊……", "约翰")
	await  novel_interface.hide_character()
	await novel_interface.show_text_only("为了接触她不惜消除自己的记忆，这样值得吗！？")
	await novel_interface.show_text_only("电话另一头传来责备的声音。")
	novel_interface.show_character("john","smile")
	await novel_interface.show_dialog("啊哈哈──别这么生气嘛。", "约翰")
	await  novel_interface.hide_character()
	await novel_interface.show_text_only("约翰憨憨的笑了笑，走到桌边敲击着键盘。")
	novel_interface.change_background("res://assets/images/bg/Soya/Titor.png")
	await novel_interface.show_dialog("还是…挺值得的嘛……", "约翰")
	
	print("=== 天启篇第20话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
