# apocalypse_ep13.gd - 天启篇第13话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第13话剧本
	apocalypse_ep13_script()

func play_script():
	pass

# 天启篇第13话 - 正式剧本
func apocalypse_ep13_script():
	# 开场序章 - 关于疼痛的感受
	novel_interface.show_background("res://assets/images/bg/Soya/Hypnosis2.png")
	await novel_interface.show_text_only("或许你曾听说过这样的故事――")
	await novel_interface.show_text_only("士兵在厮杀结束之后，才发觉自己的身体早已严重受伤甚至开膛破肚。")
	await novel_interface.show_text_only("登山运动员看到自己被冻僵坏死手指之后，才开始感觉到冻伤的剧痛。")
	await novel_interface.show_text_only("甚至有人可以用催眠的手段暂时关闭对象的痛觉。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("因为疼痛，是一种很主观的感受。")
	# 场景转移到小巷
	novel_interface.show_background("res://assets/images/bg/Soya/Dark_alley.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("戴眼镜的男生果然对这一带非常熟悉――")
	await novel_interface.show_text_only("他领着我们拐进路边的一家餐厅，和老板娘打了个招呼就推开厨房的后门。")
	await novel_interface.show_text_only("绕过几条狭长的暗巷之后，我们终于甩掉了那几个不依不饶的亲卫队员。")
	await novel_interface.show_text_only("小巷两侧的墙上挂满了空调排风扇，路边堆着一排排的垃圾桶和不知谁会光顾的自动贩卖机。")
	await novel_interface.show_text_only("没想到繁华的电器街背后，还有这样错综复杂如迷宫一样的地方。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("几分钟后，通过一道铁丝网构成的栅栏门，我们终于来到了大路上。")
	
	# 到达新井中心公园外
	novel_interface.show_background("res://assets/images/bg/Soya/Night_Park_Out.png")
	novel_interface.show_character("john", "smile")
	await novel_interface.show_dialog("那边就是你们要去的新井中心公园吧？", "戴眼镜的男生")
	novel_interface.show_character("ren_fishnet", "happy")
	await novel_interface.show_dialog("居然这么快就到了！\n看手机地图要绕好大一圈呢……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我观察着四周的环境，街对面亮灯的巨型拱门就是新井中心公园的东大门。")
	await novel_interface.show_text_only("与热闹的电器街相比，这条没有民居和商铺的街道显得格外冷清，走路时甚至能听到自己的脚步声。")
	await novel_interface.show_text_only("了无生气的路灯发出滋滋的电流音，空气中似乎有一股淡淡的血腥味。")
	novel_interface.show_character("ren_fishnet", "gratified")
	await novel_interface.show_dialog("咱们快点过去吧……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我想尽快离开这里，而且一直背着酣睡的伊露卡跟在我们后面的索娅也发出了抗议。")
	novel_interface.show_character("soya_uniform", "cry")
	await novel_interface.show_dialog("这小丫头沉死了！", "索娅")
	await novel_interface.show_dialog("身为男生都不懂得主动搭把手吗？", "索娅")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("对、对不起――", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("john", "worry", 0.25)
	await novel_interface.show_dialog("啊抱歉，刚刚只顾着跑……", "戴眼镜的男生")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("看到我也下意识的道歉，金发少年有些莫名，索娅则露出一副不怀好意的笑容。")#文字错误
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("哦厚――？", "索娅")
	novel_interface.show_character("ren_fishnet", "panic")
	await novel_interface.show_dialog("（诶？该不会……）", "小怜")
	novel_interface.show_character("soya_uniform", "relieve")
	await novel_interface.show_dialog("算了，她的重量对我来说不算什么。", "索娅")
	await novel_interface.show_dialog("不像有些人――\n被大姐姐迷得神魂颠倒，还流鼻血……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("刚才我丢人的样子果然被她发现了！！")
	await novel_interface.show_text_only("还有谁流鼻血了？！")
	
	# 贝阿特丽切出现
	novel_interface.show_character("beatrice_regular", "smile1")
	await novel_interface.show_dialog("被迷得神魂颠倒？", "女性的声音")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切从我们身后的阴影中走了出来。")
	novel_interface.show_character("beatrice_regular", "smile3")
	await novel_interface.show_dialog("你们几个还挺快的嘛~", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("你什么时候到这里的？", "小怜")
	novel_interface.show_character("soya_uniform", "afraid")
	await novel_interface.show_dialog("喂喂，你隐蔽气息的能力也太強了吧……", "索娅")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("我从小就习惯了~\n不想男人看到就要把自己藏好――", "贝阿特丽切")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("嘘！先躲起来。", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切警觉的将我们拉到暗处，远处一辆装甲车飞速驶来，在我们面前呼啸而过。")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("这条路经常有军队的车经过，咱们换个地方。", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	
	# 进入公园主干道
	novel_interface.show_background("res://assets/images/bg/Fabiola/Night_Park.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("我们来到新井中心公园的主干道，索娅轻轻的将睡熟的伊露卡放在路边长椅上。")
	await novel_interface.show_text_only("这里虽看不到人，但隐约能听到远处小孩和宠物玩耍的声音，让人觉得安心了许多。")
	await novel_interface.show_text_only("贝阿特丽切打量着刚才帮我们解围的向导。")
	novel_interface.show_character("beatrice_regular", "normal")
	await novel_interface.show_dialog("这位是――？", "贝阿特丽切")
	novel_interface.show_character("john", "shy")
	await novel_interface.show_dialog("啊！都忘了自我介绍……", "戴眼镜的男生")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少年面对贝阿特丽切有些慌张，似乎不知该把眼睛放在哪。")
	await novel_interface.show_text_only("他本想直视对方的脸，眼睛却总被下面那对壮观的东西吸引，只得欲盖弥彰的扭开头。")
	novel_interface.show_character("ren_fishnet", "uneasy")
	await novel_interface.show_dialog("（嗯嗯，我懂的！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("但没想到这个掩饰的动作如此明显――")
	novel_interface.show_character("ren_fishnet", "uneasy")
	await novel_interface.show_dialog("（看来以后不能用了……）", "小怜")
	novel_interface.show_character("john", "worry")
	await novel_interface.show_dialog("我叫约翰，在电器街的店里打工。", "戴眼镜的男生")
	novel_interface.show_character("soya_uniform", "afraid")
	await novel_interface.show_dialog("约翰？真是普通的名字。", "索娅")
	novel_interface.show_character("john", "shy")
	await novel_interface.show_dialog("是、是有点普通啦……", "约翰")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("约翰腼腆的推了推眼镜。")
	novel_interface.show_character("john", "shy")
	await novel_interface.show_dialog("抱、抱歉！刚才我在远处看到你在花车上很帅气的骂人，就情不自禁的……", "约翰")
	novel_interface.show_character("beatrice_regular", "bored")
	await novel_interface.show_dialog("情不自禁的？", "贝阿特丽切")
	novel_interface.show_character("john", "shy")
	await novel_interface.show_dialog("偷偷用手机录了像……", "约翰")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("嘛……是为了回家慢慢回味吧~", "索娅")
	novel_interface.show_character("ren_fishnet", "wry_smile")
	await novel_interface.show_dialog("（虽然我理解，但这种事情不可以招供的啊！）", "小怜")
	novel_interface.show_character("john", "shy")
	await novel_interface.show_dialog("我无意间拍到了旁边的花车，后来看到你们被人追，也、也不知哪来的勇气……", "约翰")#换行问题
	await novel_interface.hide_character()
	await novel_interface.show_text_only("约翰偷偷瞄了我一眼，脸一下子红到了脖子根，说话的声音也越来越小。")
	novel_interface.show_character("ren_fishnet", "speechless")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我想起以前在网游里玩女性角色，结果一个经常和我组队的男生吱吱呜呜想对我告白的情景。")
	await novel_interface.show_text_only("我只是不想玩游戏的时候一直对着人类男性角色壮硕的屁股而已……")
	novel_interface.show_character("ren_fishnet", "wry_smile")
	await novel_interface.show_dialog("（唉，那时还觉得还挺对不住人家的~）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切走到他身边，低下头温柔的说道――")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("男生看到漂亮的女孩子落难，都会变得有勇气。", "贝阿特丽切")
	novel_interface.show_character("john", "perspire")
	await novel_interface.show_dialog("对、对不起，录像我会删除的！打碎的招牌我也会去向店家赔罪的！！", "约翰")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("约翰一边说一边鞠躬道歉赔罪，一看就是从小在新丰洲长大的。")
	novel_interface.show_character("soya_uniform", "smile")
	await novel_interface.show_dialog("真是个好孩子啊……", "索娅")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet", "stare", 0.25)
	await novel_interface.show_dialog("你还好意思说――", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("不过看他现在的样子，真的难以想象和刚才果断摔碎灯箱拦住亲卫队的是同一个人。")
	await novel_interface.show_text_only("当时灯泡爆裂玻璃碴砸碎了一地，短路的电线还在灯箱里呲呲作响，场面让人印象十分深刻。")
	novel_interface.show_character("ren_fishnet", "bored")
	await novel_interface.show_dialog("（估计他自己也没料到动静会那么大吧……）", "小怜")
	novel_interface.show_character("beatrice_regular", "smile3")
	await novel_interface.show_dialog("哈哈哈，没关系的。", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切拍了拍他的肩膀，")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("我也是忍了好多年，今天才第一次发泄出来，觉得格外舒畅呢~", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("今天是第一次吗？真是太有天赋了！")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("以后要不要经常试试呢……", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet", "sprite")
	await novel_interface.show_dialog("（会引起暴动的！）", "小怜")
	novel_interface.show_character("beatrice_regular", "smile3")
	await novel_interface.show_dialog("啊对了――", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切向我走来，一只手绕到后面轻轻扶住我的腰。")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("看你刚才走路的样子……你的腰受伤了？", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她手稍稍一按，疼得我眼泪都出来了。")
	await novel_interface.show_text_only("我本能的想要躲开，却一下倒进她怀里，贝阿特丽切有些心疼的摸着我的头说道――")
	novel_interface.show_character("beatrice_regular", "sad")
	await novel_interface.show_dialog("应该是扭伤了，得在状况恶化之前尽快处理。", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切看了看自己的手。")
	novel_interface.show_character("beatrice_regular", "sad")
	await novel_interface.show_dialog("并没有出血……", "贝阿特丽切")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("本部离这里太远，我送你去附近的医院？", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("我现在应该是被通缉的状态，这附近的医院和保安军都是联网的吧？", "小怜")
	novel_interface.show_character("soya_uniform", "smile")
	await novel_interface.show_dialog("如果是扭伤的话，艾尔加纳嬤嬤应该有办法。", "索娅")
	novel_interface.show_character("beatrice_regular", "normal")
	await novel_interface.show_dialog("艾尔加纳？", "贝阿特丽切")
	novel_interface.show_character("john", "worry")
	await novel_interface.show_dialog("被通缉……嬤嬤？", "约翰")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("约翰听着我们的对话，完全搞不清状况。")
	novel_interface.show_character("soya_uniform", "smile")
	await novel_interface.show_dialog("是我小时候在修道院的嬤嬤，上周才被枢机院指派到新丰洲教区新建成的一座教堂，离这很近。", "索娅")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("她之前专为信理部和圣赦院配药，针对肌肉和筋腱损伤的疗效比医院的常规药物好多了。", "索娅")
	novel_interface.show_character("john", "smile")
	await novel_interface.show_dialog("总之就是很厉害的医生？那我们快走吧！", "约翰")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切意味深长看了看比我还急切的约翰。")
	novel_interface.show_character("john", "shy")
	await novel_interface.show_dialog("我、我是说……\n我也陪你们去吧……", "约翰")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("有人好像很关心你呢，小兔子~", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet", "awkward")
	await novel_interface.show_dialog("啊啊啊啊你别说那件事啊！！！！", "小怜")
	novel_interface.show_character("soya_uniform", "laugh")
	await novel_interface.show_dialog("什么事什么事？？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅摇着尾巴凑了过来。")
	novel_interface.show_character("ren_fishnet", "shy_left")
	await novel_interface.show_dialog("什么也没有！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切清了清嗓子，表情严肃的总结了一下现状。")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("那咱们先去教堂看看，我派车去那边待命，如果不行就直接送你回总部治疗。", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet", "normal1")
	await novel_interface.show_dialog("也只能如此了。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她随即拨通了电话――")
	novel_interface.show_character("beatrice_regular", "angry")
	await novel_interface.show_dialog("洗衣店吗？\n给我安排一下车队……", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("待贝阿特丽切布置好，索娅再次背起了伊露卡。")
	await novel_interface.show_text_only("索娅说的教堂确实离这里很近，距离公园步行只需要十分钟左右。")
	
	# 到达教堂
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_character("ren_fishnet", "happy")
	await novel_interface.show_dialog("好大――！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这座教堂是棕黄色的石质建筑，外墙有一幅巨大的宗教壁画。")
	await novel_interface.show_text_only("教堂的广场中央有一个小型喷泉，大理石边缘还有防水条的施工痕迹，看起来这里才建成不久。")
	await novel_interface.show_text_only("主体建筑顶部的十字架一直伸向漆黑的夜空，引人注目的大门在灯光映衬下显得金碧辉煌。")
	novel_interface.show_character("beatrice_regular", "normal")
	await novel_interface.show_dialog("……", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet", "wry_smile")
	await novel_interface.show_dialog("大门上的那个光泽……难道是黄金？", "小怜")
	novel_interface.show_character("soya_uniform", "smile")
	await novel_interface.show_dialog("估计是镀金吧……反正这里用的是教廷和联合议会的预算，客气什么~", "索娅")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("而且和萨蒙顿的那些教堂比起来，这种规模简直不能再穷酸了。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("确实，在新丰洲这个崇尚科学的地方，很难见到如此规格的宗教建筑。")
	await novel_interface.show_text_only("但如果拉斐尔见到的话，估计会嗤之以鼻吧？")
	await novel_interface.stop_music()
	novel_interface.show_character("john", "perspire")
	await novel_interface.show_dialog("前面……马上就……", "约翰")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("约翰，你的脸色有点――", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我还没说完，只见他失去血色的嘴唇笑了一下，接着就失去意识栽倒在地。")
	novel_interface.show_character("ren_fishnet", "serious")
	await novel_interface.show_dialog("怎么回事！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切立刻上前查看，她的手刚碰了一下，立刻就抽了回来。")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("beatrice_regular", "angry")
	await novel_interface.show_dialog("这是……血！？", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("约翰的黑色长裤上有一大片已经干涸的血迹，是由单一出血点渐渐浸润造成的。")
	await novel_interface.show_text_only("我们刚才以不同形式感觉到的血腥味都来自于此。")
	await novel_interface.show_text_only("他面色苍白，脉搏快速而微弱，一切都符合失血过多的症状。")
	await novel_interface.show_text_only("贝阿特丽切立刻让停在教堂门口的黑色SUV将约翰送往最近的医院，她自己也跟了过去。")
	await novel_interface.show_text_only("同时她安排了另外两辆车，一辆将还在睡觉的伊露卡送回SID本部，另一辆留在教堂门口待命。")
	await novel_interface.show_text_only("临走前她再三叮嘱我们不要随意外出。")
	novel_interface.show_character("beatrice_regular", "angry")
	await novel_interface.show_dialog("今晚实在太诡异了……", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅检查时在约翰的大腿上发现了一处两厘米大小的伤口，上面还插着一小片玻璃。")
	await novel_interface.show_text_only("应该是他刚才放倒灯箱时被割伤的，带着这样的伤口走路本应是极痛苦的事。")
	await novel_interface.show_text_only("然而不知为何，他全程似乎没有一点感觉……")

	print("=== 天启篇第13话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
