# apocalypse_ep10.gd - 天启篇第10话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第10话剧本
	apocalypse_ep10_script()

func play_script():
	pass

# 天启篇第10话 - 正式剧本
func apocalypse_ep10_script():
	# 场景：秋叶原夜晚
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("我和索娅赶回了灯火通明的电器街。")
	await novel_interface.show_text_only("猫丸电器本店三四层外墙的大屏幕上，正循环播放着赞助商的广告视频。")
	await novel_interface.show_text_only("几辆由货车改造而成的巡游花车，在步行街中央整整齐齐排成一列。")
	await novel_interface.show_text_only("花车的两侧都印着巨幅广告喷绘，车顶是装饰精致的围栏，一些工作人员正在调试音响设备。")
	novel_interface.show_character("soya_uniform", "speechless")
	await novel_interface.show_dialog("这是要举办什么活动吗？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("现在电器街的人比我们刚离开时只多不少，而且游客还在不断涌入。")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("啊，今天难道是……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我忽然想起曾在网上见到过类似的场面，迅速拿出手机搜索。")
	await novel_interface.show_text_only("果然——今晚是电器街一年一度的特殊庆典。")
	await novel_interface.show_text_only("五年前，随着新丰洲的局势逐渐稳定，元老院宣布废除了《社会公序法》等多个文化类管制法案。")
	await novel_interface.show_text_only("决议执行前一晚的午夜，很多人自发聚集在猫丸电器的大屏幕下倒计时，庆祝这一“伟大的胜利”。")
	await novel_interface.show_text_only("后来网上有人恶搞，将这一事件改编成了御宅族前辈反抗暴政，奋勇抵抗最终拯救世界的故事。")
	await novel_interface.show_text_only("不料引发了一群“老战士”的集体创作，众人纷纷用回忆的形式对『那场战争』进行补完。")
	await novel_interface.show_text_only("还煞有介事的说战后政府决定进行世界范围的记忆消除，仅保留部分战争功臣的记忆……")
	await novel_interface.show_text_only("而那次倒计时，就是记忆消除前夜，幸存者们一边读秒一边热泪盈眶的缅怀战争烈士。")
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("（蠢爆了！谁会信啊！！）", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（亏我当年看得那么燃……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不过商家抓住了这个机会，将这一天打造成年度促销庆典，还吸引了大批赞助商。")
	novel_interface.show_character("ren_fishnet", "uneasy")
	await novel_interface.show_dialog("怪不得今天下午免费发周边……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我有些眼红的看着路人手中的黄色小旗子。")
	novel_interface.show_character("soya_uniform", "wordless")
	await novel_interface.show_dialog("如果活动要持续到12点的话……这个时间的气氛也过于热烈了吧？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看了看表，还不到8点，但街上的人群似乎异常兴奋。")
	await novel_interface.show_text_only("由于今年的人数远超预期，现场维持秩序的保安警显得完全力不从心。")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("话说……咱们应该算逃犯吧？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看着附近的几个警员，不知这次他们会被索娅用什么新花样撂倒。")
	novel_interface.show_character("soya_uniform", "relieve")
	await novel_interface.show_dialog("低调点——", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅掐了一下我，指向街对面。")
	novel_interface.show_character("soya_uniform", "smile")
	await novel_interface.show_dialog("看见那两辆黑色的装甲车了吗？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我朝着她手指的方向看去，那种装甲车应该是待命中的保安军……搞不好是纽摩利达斯攻击队。")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("万一把那群家伙吸引过来，我可没法帮你挡子弹~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅看了看我毫无肌肉的大腿露出鄙视的微笑，不会躲子弹真是抱歉了啊！")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("不过这么多人，不知道能不能找到伊露卡……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我不安的环视着四周熙熙攘攘的人群，想到伊露卡在这种环境下迷茫无助的小眼神就一阵揪心。")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("那丫头的话，不就在那儿呢吗~", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("啥！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅用下巴指指前面被装饰成神龛的花车，坐在神位上的那个小萝莉正是伊露卡。")
	await novel_interface.show_text_only("那不知是哪家赞助的花车，前面挂着一个巨大的灯笼，灯笼后还有两个人在敲太鼓。")
	await novel_interface.show_text_only("此时花车下面密密麻麻的围了上百号人，正用朝圣般的眼神注视着车上的大萌神。")
	await novel_interface.show_text_only("还有十几个人穿着应援服站成一排，每人手中拿着两个黄色的小旗子随着太鼓的节奏打call。")
	await novel_interface.show_text_only("只见伊露卡从面前的贡品台上捧起一个巧克力奶油卷，没用几口就吃掉了。")
	
	# 显示伊露卡，使用iluka_hide而不是iluka_uniform
	await novel_interface.show_dialog("诶嘿嘿……","伊露卡")
	await novel_interface.show_text_only("——随后亮出了一个没心没肺的幸福笑容。")
	await novel_interface.show_text_only("众人看她吃完，立刻一阵欢呼，应援队也掀起一阵高潮。")
	await novel_interface.show_text_only("接着伊露卡又满眼星星的挑选起下一件“贡品”。")
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("………………………", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("这什么情况？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "laugh")
	await novel_interface.show_dialog("哦呀呀~似乎完全燃起来了。", "索娅")
	await novel_interface.hide_character()
	
	# 场景转换
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("我俩绕着花车勘查了一圈。")
	await novel_interface.show_text_only("在那群把花车围得密不透风的“亲卫队”面前，似乎没有任何暴力突入以外的方法。")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("可万一引起保安军的注意……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我们远远看着在花车上大吃特吃的伊露卡，既然确定她没有危险，似乎也不用那么着急了。")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("呐~为什么有人对小萝莉那么狂热呢？在欧洲人们会认为这种行为很变态哦——", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅一脸坏笑的问我。")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("变、变态？\n不会吧……", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("你看，就像有人喜欢动物的幼崽一样——单纯、认真、又有点笨拙……", "小怜")
	await novel_interface.show_dialog("那种美好的、让人不忍伤害想要保护的感觉……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我极力试图为那些人和我自己辩解，但似乎越说越不妙了。")
	novel_interface.show_character("ren_fishnet", "shy_left")
	await novel_interface.show_dialog("要论变态，你和他们根本不是一个等级吧！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "laugh")
	await novel_interface.show_dialog("嘿嘿，变态有什么不好的~", "索娅")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("如果“普通”的定义是特定环境中所有人的平均状态，那么与平均值相差过大的人就会被当做变态。", "索娅")
	await novel_interface.show_dialog("所以变态本身就是出众的意思，完全不需要隐藏。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅一脸自豪的将手放在自己胸前——")
	novel_interface.show_character("soya_uniform", "relieve")
	await novel_interface.show_dialog("变态就是变态，坦然承认就好，不需要用普通人的逻辑为自己注解。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅拍了拍我的肩，用人生导师的语气说道。")
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("（还有这种不要脸的自我解读吗？）\n（以及我怎么好像被强行归类了！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("欧洲人认为萝莉控变态，可能只是因为他们都喜欢丰满的女性而已，比如——", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅顺势将手移到我的胸前捏了捏。")
	novel_interface.show_character("ren_fishnet", "awkward")
	await novel_interface.show_dialog("欸？", "小怜")
	await novel_interface.hide_character()
	
	# 贝阿特丽切出场，使用beatrice_show_hide效果
	await novel_interface.show_dialog("看来还不是很成熟呢。","女性的声音")
	await novel_interface.show_text_only("我们身后传来一个熟悉的声音。")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("贝、贝阿特丽切？！\n你怎么在这……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("好久不见了，小可爱——", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "laugh")
	await novel_interface.show_dialog("哇——！！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅看着贝阿特丽切的胸部就要扑过去，被我一把薅住。")
	novel_interface.show_character("soya_uniform", "cry")
	await novel_interface.show_dialog("放、放开我！", "索娅")
	await novel_interface.show_dialog("这个人和小怜的味道一样干净，但是大得多——", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("什么大得多啊！！！")
	await novel_interface.show_text_only("贝阿特丽切优雅的理了理头发，顺便调整了一下紧绷的衬衫。")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("莉琉要我暗中跟踪并保护你们。", "贝阿特丽切")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("其实全程不被发现挺困难的呢，尤其你们还遇到了那个瑟蕾莎……", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "panic")
	await novel_interface.show_dialog("跟、跟踪？", "小怜")
	# 显示双角色位置移动
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform", "afraid", 0.25)
	await novel_interface.show_dialog("从什么时候开始的？我都没察觉到……明明是这么甜美的气味！", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索娅被我拉着脖领，像小狗一样拼命将鼻子探向贝阿特丽切。")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("从今天下午开始，我一直都在你们附近。", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切妩媚的一笑，我觉得脸颊有些发烫。")
	await novel_interface.show_text_only("似乎她最近确实在帮SID处理一些“特殊事务”。")
	await novel_interface.show_text_only("这位自称死于700多年前的姐姐，是我在天空酒店通过拉斐尔家的挂坠召唤出的魔女。")
	await novel_interface.show_text_only("据说贝阿特丽切身上带有会让所有异性迷恋自己的『诅咒』。")
	await novel_interface.show_text_only("一定是因为那个诅咒的缘故，害我每次见到她都会慌张的不知所措……")
	novel_interface.show_character("ren_fishnet", "shy")
	await novel_interface.show_dialog("等等，那我们俩刚才被拘留——", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "worry")
	await novel_interface.show_dialog("你们刚被捕我就联系了莉琉，但她可能在忙别的或者处在信息屏蔽区域，一直没有回复……", "贝阿特丽切")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("我判断有索娅在，你们两个应该很快就能脱身，于是就留在了这边继续监视伊露卡。", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "shy_right")
	await novel_interface.show_dialog("那个……伊露卡到底是怎么跑到那上面的？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我和贝阿特丽切对话的时候总是视线游离，实在不知把目光落在哪里好。")
	await novel_interface.show_text_only("而索娅已经放弃挣扎，开始饶有兴致的观察起我的表情来，真是烦人！")
	novel_interface.show_character("beatrice_regular", "worry")
	await novel_interface.show_dialog("索娅把你按在墙上的时候，那个小朋友就跟着一个送外卖甜品的人跑了。", "贝阿特丽切")
	novel_interface.change_expression("bored")
	await novel_interface.show_dialog("你们啊……唉。", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切语重心长的叹了口气，怎么说的好像我们在做什么奇怪的事情似的！")
	novel_interface.show_character("beatrice_regular", "smile1")
	await novel_interface.show_dialog("后来伊露卡去了你们下午去的甜品店，老板不仅免单，还介绍她作今晚宣传活动的演员。", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "stare")
	await novel_interface.show_dialog("（没想到那个有点谢顶的老板这么有眼光！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "smile1")
	await novel_interface.show_dialog("因为不熟悉她，一开始我认为只是小孩子贪吃，但现在看来确实有些不对劲……", "贝阿特丽切")
	await novel_interface.show_dialog("索娅没有看出什么问题？", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "wordless")
	await novel_interface.show_dialog("并没有——", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅看向伊露卡的方向。")
	novel_interface.show_character("soya_uniform", "speechless")
	await novel_interface.show_dialog("没有被胁迫，没有被下药。", "索娅")
	await novel_interface.show_dialog("没有不适或痛苦的感觉，行为完全符合自身的心智和欲望。", "索娅")
	novel_interface.change_expression("wordless")
	await novel_interface.show_dialog("要说有什么问题的话，就是她吃的也太多了吧……", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "grieved")
	await novel_interface.show_dialog("从刚才的新闻看，今晚协约非武装区里已经有6个区域的示威游行出现暴力冲突了。", "贝阿特丽切")
	novel_interface.change_expression("sad")
	await novel_interface.show_dialog("虽然性质不同，但这里很可能会变成第7个。", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "panic")
	await novel_interface.show_dialog("怪不得连军队都来了……\n那咱们得尽快带伊露卡离开！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "wordless")
	await novel_interface.show_dialog("但想在那群人眼皮底下把人带走没那么简单吧？", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("我可以帮你们分散一下他们的注意力，但在人这么多的场合估计只能坚持30秒……", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "worry")
	await novel_interface.show_dialog("要怎么——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的话还没问出口，就被贝阿特丽切打断。")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("你们有没有发现这里的人有什么共通点？", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("他们都很兴奋？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切抬起右手，微微一笑。")
	novel_interface.show_character("beatrice_regular", "smile2")
	await novel_interface.show_dialog("这群笨蛋，基本上都是男人啊——", "贝阿特丽切")
	await novel_interface.hide_character()
	
	print("=== 天启篇第10话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
