# apocalypse_ep18.gd - 天启篇第18话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第18话剧本
	apocalypse_ep18_script()

func play_script():
	pass

# 天启篇第18话 - 正式剧本
func apocalypse_ep18_script():
	# Scene 1 - 开始
	novel_interface.show_background("res://assets/images/bg/Soya/Parade.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("我们从大楼出来，车已经停在了门口，胖胖的司机迎上来塞给我们两只微型骨膜耳机。")
	await novel_interface.show_dialog("刚才老板叫我把这个给你们。", "司机")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("老、老板？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我和索娅把耳机戴上，立刻听到了爱衣的声音。")
	await novel_interface.show_dialog("游行队伍里噪音太大，用手机怕你们听不见。", "爱衣")
	await novel_interface.show_dialog("我刚才确认了下，整个协约非武装区，确实只有发生暴动的七个区域是黄色的路灯。", "爱衣")
	await novel_interface.show_dialog("因为全都是繁华地段，有太多干扰光源，就算看着航拍画面也很那发现问题……", "爱衣")
	await novel_interface.show_dialog("回收队已经出动，但我估计拦也拦不住你，注意保护好小怜就可以了。", "爱衣")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("……拦什么？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅听到后对一直跟着我们的无人机点了点头，接着不由分说的拉着我冲进了人群。")
	
	# Scene 2 - 切换场景
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Soya/Parade.png")
	await novel_interface.show_text_only("我被拉着来到一盏周围人比较少的黄色路灯下，抬头看了看足足有七八米高的灯柱。")
	await novel_interface.show_text_only("在之前SID的训练课程上，我对这种体能类项目都是很有自信的──")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("（爬杆，0分。）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("每次都是助跑跳到杆子上，像考拉一样抱住，然后绝望的一点点出溜下来……")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("嘿嘿……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅从她的挎包中抽出一只沉甸甸的金属箱，侧面有一张A4纸那么大，约7、8厘米厚。")
	await novel_interface.show_text_only("金属箱中央一圈显眼的亮银色包边，显然是可转动部件，侧面还有粉色的金属条纹。")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("猜猜这是什么──", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅提着箱子顶部的弧形把手，得意的问道。")
	await novel_interface.show_text_only("看这个大小和做工，那又大又帅气的像风扇一样的转动部件，还有炫目的像灯带一样的东西……")
	novel_interface.show_character("ren_fishnet","smile")
	await novel_interface.show_dialog("最新型号的显卡？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅拉了一下箱子把手上的机关，粉色条纹那一侧呈剪刀状张开。")
	await novel_interface.show_text_only("从中层层递进的弹出一系列黑色机械构件，加上最后弹出的长板，总长度接近1米。")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("什么东西！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("这是只有『审判骑士』才有资格使用，以异质物作为核心动力部件的武器~", "索娅")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("是圣赦院根据我的要求制作的──", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅扭了一下把手，从箱子中沿着长板顶部边缘的轨道划出一条闪着金属光泽的链齿。")
	await novel_interface.show_text_only("链齿沿着长板末端的圆弧再向回返，最终又回到了箱子中。")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("这是电锯！？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","normal",0.25)
	await novel_interface.show_dialog("差不多啦，不过不是靠电力驱动，是我最喜欢的武器哦~", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索娅笑着启动了“电锯”，链齿飞速旋转起来，但声音比我预想中小得多。")
	
	novel_interface.show_character("ren_fishnet","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("soya_uniform","normal",0.25)
	novel_interface.character_2nd_dark()
	
	await novel_interface.show_dialog("你不会是想……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索娅毫不犹豫的对着金属柱切了下去，顿时火花四溅，银灰色的灯柱发出了撕心裂肺的哀嚎。")#多字问题
	await novel_interface.show_text_only("巨大的噪音引得附近人一阵围观，还有几个不明所以的大叔在旁边兴奋的叫好。")
	await novel_interface.show_text_only("十几秒后，灯柱里传出两声炸响，索娅的动作停了下来。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅抬头看着已经熄灭的路灯，我才发现直径20\n厘米的灯柱此时只靠一点点金属维持着竖立状态。")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("倒……", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("倒啦──！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("这才像话嘛~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅坏笑着朝没人的方向敲了一下灯柱。")
	await novel_interface.show_text_only("那一小段苦苦维持大局的金属终于放弃抵抗，在一阵悲鸣中缓缓向那一侧折断。")
	await novel_interface.show_text_only("随着一声巨响，整根路灯狠狠的将柏油路面拍出几道裂纹，溅起无数小石块。")
	await novel_interface.show_text_only("围观的人群沉默了几秒，随后爆发出震耳欲聋的欢呼。")
	await novel_interface.show_dialog("自由万岁──！！！！\n和平万岁──！！！！", "游行群众")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("什么和什么啊！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我们迅速跑到路灯头部检查，索娅利落的将灯体锯断，那台无人机也跟着降到了贴地的高度。")
	await novel_interface.show_dialog("这个摄像头的清晰度一般，先把灯罩打开我看看LED型号吧。", "爱衣")
	await novel_interface.show_text_only("为了避开那帮人狂热的视线，我搬起灯体就朝着\nSUV的方向落荒而逃。")#换行问题
	await novel_interface.show_text_only("然后索娅按照爱衣的指导，把灯体大卸八块──微型监控、电池、灯芯、镇流器。")
	await novel_interface.show_dialog("这些零件和LED的编号都没问题啊……", "爱衣")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("话说──", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我拿着她们拆下的灯罩，透过远处的光源说道。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("如果灯罩是黄色的，怎么也不可能射出白光吧？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("灯罩上密集的黄色条纹，摸上去有细密的凸起，是要经过精密加工才会呈现出的状态。")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("好像藏着什么信息，不过用直接看的话……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅也拿着灯罩透着光看了看，然后摇摇头。")
	await novel_interface.show_dialog("车上有3D扫描装置，把灯罩放进去发给我看看。", "爱衣")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("车上连那种东西都有！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那当然，SID的载具还有全套的自动武──", "爱衣")
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("小心！！！", "索娅")
	await novel_interface.hide_character()
	
	# Scene 4 - 被攻击场景
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("“呲咔──！！！！”")
	novel_interface.show_background("res://assets/images/bg/Soya/Beingshot.png")
	await novel_interface.show_text_only("突然从拐角处射出一道炫目的白光，直接击中我的胸口。")
	await novel_interface.show_text_only("瞬间尖锐的电流声从我耳旁呼啸而过，我的心脏似乎停止了跳动。")
	await novel_interface.show_text_only("隐约中感觉司机接住了朝后倒下的我，索娅帮着把我拖到了车的另一侧。")
	await novel_interface.show_text_only("七八个身材魁梧，穿着黑色特种作战服手持冲锋枪的人朝我们冲了过来……")
	await novel_interface.show_text_only("周围的一切似乎都覆上了一层诡异的色彩，我的大脑异常清醒，甚至看所有人就像慢动作一样。")
	await novel_interface.show_text_only("索娅和爱衣都在大声呼喊着我的名字，可声音就像隔着一堵厚厚的墙壁……")
	await novel_interface.show_text_only("司机大叔从车架后面抽出一把霰弹枪，熟练的单手上弹，用防弹的车门做掩护对着那群人射击。")
	await novel_interface.show_text_only("原来大叔你这么厉害啊……")
	await novel_interface.show_text_only("可惜，那帮人训练有素，而且看武器和战术应该就没想留活口，就算是索娅也……")
	await novel_interface.show_text_only("我失去意识前最后的记忆是，索娅拿着电锯拉住了我的手──")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("以及一连串凄厉中带着惊恐的惨叫声。")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	
	# Scene 5 - 瑟蕾莎场景
	novel_interface.change_background("res://assets/images/bg/Soya/Backstreet.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("距第一大道300米处。")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("啧啧──", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎一边懒洋洋的通过耳机与什么人通话，一边从倒在地上的士兵身上切下一块黑色衣料。")
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("这帮人只是他们作为后备支援的B组吗？\n装备真舍得花钱……", "瑟蕾莎")
	await novel_interface.show_dialog("活口？", "瑟蕾莎")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("……啊！", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎拍了一下脑袋，在原地僵住了5秒钟。")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("我忘了……", "瑟蕾莎")
	await novel_interface.show_dialog("不能怪我嘛！那家伙的脑袋突然就炸成烟花，吓得我把他们几个全都给砍了。", "瑟蕾莎")
	novel_interface.change_expression("boring")
	await novel_interface.show_dialog("而且看起来就算抓了活的，从他们身上也查不出什么吧──", "瑟蕾莎")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("全员烧掉指纹，两侧臼齿植入了炸药，侦测到生命体征濒死就立刻把牙齿带着整张脸一起炸掉。", "瑟蕾莎")
	novel_interface.change_expression("blink")
	await novel_interface.show_dialog("──就是说啊！", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎和耳机那边的人抱怨道。")
	novel_interface.show_character("cereza","speek")
	await novel_interface.show_dialog("你想想看，我摸到那家伙后面一刀下去，还想给对方留点时间转身看清我帅气的脸──", "瑟蕾莎")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("结果那家伙的头就突然就爆掉了！", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她用那块衣料擦了擦刀上的血迹，然后嫌弃的甩在那具尸体血肉模糊的脸上。")
	novel_interface.show_character("cereza","wordless")
	await novel_interface.show_dialog("真是没品……", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎将闪着寒光的武士刀收入刀鞘。")
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("刚才从小路突然冲出两辆没有车牌的冲锋车，总共十几个人，我也不可能正面硬上。", "瑟蕾莎")
	await novel_interface.show_dialog("不过他们三个居然能从第一组人手里逃掉，那个司机有点水平啊……", "瑟蕾莎")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("什么──？", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎把手放在耳机上，以为自己听错了。")
	novel_interface.show_character("cereza","uneasy")
	await novel_interface.show_dialog("那组人被全灭了！？", "瑟蕾莎")
	await novel_interface.show_dialog("而且溅到旁边写字楼外墙上的血迹，最高的飞到了5层楼……", "瑟蕾莎")#多符号
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("难道说──", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎似乎得到了耳机那边的确认。")
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("果然是因为那个小家伙吗？今天接触她时我也感觉到了……", "瑟蕾莎")
	novel_interface.change_expression("blink")
	await novel_interface.show_dialog("哈──", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎懒洋洋的打了个哈欠。")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("今天一大早就把我叫起来，困死我了……", "瑟蕾莎")
	await novel_interface.show_dialog("总之，你想要的情报都收集全了吧？", "瑟蕾莎")
	await novel_interface.hide_character()
	
	# Scene 6 - 莉琉与伦伯特对话
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("耳机那头传来一个自信的女声。")
	await novel_interface.show_dialog("是啊…用作这次谈判的筹码足够了。", "女性的声音")
	novel_interface.show_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("脚环上有监听装置，索娅那么详细的陈述加上你找到的这个──", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉拿着手机站在一间封闭地下室中央，瞟了一眼手中发黄的照片。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("辛苦你了，瑟蕾莎。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("或者说……町田凛子？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("手机那边传来一阵苦笑，随后直接挂断了电话。")
	await novel_interface.show_text_only("几秒钟后，随着“叮”的一声，左侧黑色的电梯门打开，从中走出一个穿着考究西服的男人。")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("真是精妙的设计……", "伦伯特")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("入口分别在两条大街，背靠背的两栋大厦，电梯却能通往同一间地下密室。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("伦伯特爵士──\n谁让我们的身份都很敏感呢~", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("你不是前两天还在电视上说，想要跟我进行一次公开对话吗？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("看来已经没必要了。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特指指莉琉手上那张发黄的照片。")
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("那么说说看，你知道了多少？", "伦伯特")
	await novel_interface.hide_character()
	
	# Scene 7 - 小怜醒来
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("不知过了多久，我隐约能感觉到颠簸和晃动。")
	await novel_interface.show_text_only("有只手一直轻轻的抚着我的额头，让我觉得周身都很温暖。")
	await novel_interface.show_dialog("小怜……", "索娅")
	novel_interface.show_background("res://assets/images/bg/Soya/Wakingup.png")
	await novel_interface.show_text_only("我用尽全力睁开眼，视野内还是一片模糊。")
	await novel_interface.show_dialog("小怜──", "索娅")
	await novel_interface.show_dialog("你醒了！？", "索娅")
	await novel_interface.show_text_only("索娅的语气明显有些激动，眼角似乎还闪着泪光。")
	await novel_interface.show_dialog("我这是……", "小怜")
	await novel_interface.show_dialog("呜──", "小怜")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我感觉嘴里含着一个坚硬异物，条件反射般的吐了出来。")
	novel_interface.show_background("res://assets/images/bg/Soya/Backseat.png")
	await novel_interface.show_text_only("我揉了揉眼睛，发现自己正在SUV的后座上，手里攥着刚吐出来的东西。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("这是……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那是一颗弹球大小的透明宝石，形状与拉斐尔之前塞给我的一模一样，只是颜色已完全褪去。")
	await novel_interface.show_dialog("嚯！这么快就醒了？", "司机")
	await novel_interface.show_dialog("快躺着别乱动，刚才真够呛，还以为我们要交代了。", "司机")
	await novel_interface.show_dialog("放心吧，咱们一会就到医院。", "司机")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("医院？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我努力回想着刚才的情景，好像我们被什么人袭击了，然后……")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("你还好吧？有没有觉得哪里不对劲？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅拉着我的手，关切的问道。")
	await novel_interface.show_text_only("她在我的左右耳边分别打了个响指，确认两侧听力正常后又让我眼睛盯着她的手指转了一圈。")
	await novel_interface.show_text_only("我上下摸索了一遍，似乎没发现哪里特别疼。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("我好像……被一道闪电打中了？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("还好击中你的是放电武器，刚才真吓死我了──", "爱衣")
	await novel_interface.show_text_only("爱衣在耳机里长舒了一口气。")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("还、还好？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你不知道吗？", "爱衣")
	await novel_interface.show_dialog("你今天穿的衣服、袜子和鞋，都是由加入了导电碳纤维的复合材料制作的。", "爱衣")
	await novel_interface.show_dialog("本来是怕你被电击脚环的效果误伤──", "爱衣")
	await novel_interface.show_text_only("等一下，这个老往下掉的网袜难道是什么高级货？")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("（而且就不能设计得稍微没那么羞耻吗？！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那道电弧击中你的时候，衣服形成了一个天然的法拉第笼，导走了大部分能量。", "爱衣")
	await novel_interface.show_dialog("不过那一发的能量实在不小，已经超出衣服的设计承载极限，你还是被打晕过去了。", "爱衣")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("原来拉斐尔给你的宝石是这么用的啊……还好没让你咽下去。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("你要对失去意识的我做什么？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然不知道那个什么笼子的原理，不过法拉第，谢谢你！")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("刚才那些家伙到底是什么人──", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我瞥到了后车窗上的血迹。")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("到底……发生了什么？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一阵沉默之后，司机率先打破了尴尬的气氛。")
	await novel_interface.show_dialog("总之你没事就好。", "司机")
	await novel_interface.show_dialog("啊，那个扫描的结果是不是已经出来了？", "司机")
	await novel_interface.show_dialog("我已经发到小怜的手机，但看起来似乎还需要进一步的分析。", "爱衣")
	novel_interface.change_background("res://assets/images/bg/Soya/Ripple.png")
	await novel_interface.show_text_only("我连忙打开手机，看到一幅诡异的画面──")
	await novel_interface.show_dialog("这是……", "小怜")
	await novel_interface.show_text_only("三维空间内，无数纵横交错的小方格扭曲的交织在一起，似乎携带着相当大的信息量。")
	await novel_interface.show_text_only("索娅也凑了过来。")
	await novel_interface.show_dialog("看起来……像张立体画？", "索娅")
	novel_interface.change_background("res://assets/images/bg/Soya/Backseat.png")
	await novel_interface.show_dialog("画……", "爱衣")
	await novel_interface.show_dialog("啊！我怎么没想到！", "爱衣")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("刚才一直是从数学层面分析那些曲线……", "爱衣")
	await novel_interface.show_dialog("但如果把每个方块都当做一个像素点的话──", "爱衣")
	await novel_interface.show_text_only("爱衣一阵忙活，很快我又收到一张她发来的图片。")
	novel_interface.change_background("res://assets/images/bg/Soya/Solomon2.png")
	await novel_interface.show_dialog("这个是──！！", "小怜")
	await novel_interface.show_text_only("所罗门王和示巴女王，像极了那座教堂大门上的浮雕──")
	await novel_interface.show_dialog("那艾尔加纳……", "小怜")
	await novel_interface.show_text_only("我和索娅对视了一眼，默契的点了点头。")
	print("=== 天启篇第18话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
