# apocalypse_ep04.gd - 天启篇第04话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第04话剧本
	apocalypse_ep04_script()

func play_script():
	pass

# 天启篇第04话 - 正式剧本
func apocalypse_ep04_script():
	 #scene1 - 继续电器街
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我观察着拉斐尔的脸色，呼吸都小心翼翼的。")
	await novel_interface.show_text_only("此时她正满脸通红的捻着书页的一角，手指在纸页边缘犹豫不决的颤抖着。")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("是~M~哟~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅居然将那件黑色蕾丝束缚式内衣迎着夕阳的方向高高举起，引起路人阵阵惊叹。")
	novel_interface.show_character("soya_uniform","laugh")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_uniform","speechless",0.25)
	await novel_interface.show_dialog("哦哦――是Ｍ！！", "伊露卡")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("伊露卡在一旁不明所以的附和道。")
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("小怜小姐，物品清点完毕，是否需要我派人送到府上？", "随行人员")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔终于回过神来，一本正经的清了清嗓子，然后将书沿着装订线卷起来……")
	await novel_interface.show_text_only("接着，她用手中的厚重纸卷对着索娅的脑袋就是一记猛击，发出的巨响连街对面都听得到。")
	await novel_interface.show_text_only("十几只女巫都无法伤其分毫的银发修女居然没来得及做出任何反应，头上立刻长出一个大包。")
	novel_interface.show_character("soya_uniform","cry")
	await novel_interface.show_dialog("你、你干什么啦！！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅捂着脑袋蹲在地上，眼中带着泪花。")
	await novel_interface.show_text_only("拉斐尔一脸杀气的走上前去，居高临下的看着她。")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("真当我不知道你是谁吗？", "拉斐尔")
	await novel_interface.show_dialog("教廷全靠萨蒙顿的庇护才能生存，信理部的派遣人员资料也都要提交到萨蒙顿大使馆。", "拉斐尔")
	await novel_interface.show_dialog("索娅·安赫莱斯――", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔面朝索娅，右手却指着我的脸。")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("你以为你手里的那件内衣……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("只见拉斐尔的右手稍稍下移，指向了我的胸部。")
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("这个女装癖，她塞得进去吗！？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哦――", "路人A")
	await novel_interface.show_dialog("嗯……", "路人B")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("……………………", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","hungry")
	await novel_interface.show_dialog("喔~", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡依旧有样学样的点着头。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("名侦探拉斐尔的推理终于帮我洗清了冤屈。")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_text_only("（但为什么感觉更糟了！！）")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("嘁――", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅露出一副扫兴的样子，就好像恶作剧失败的小孩一样。")
	await novel_interface.show_text_only("她默默的揉着头上的包站了起来，给拉斐尔的随行人员写下一个地址。")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("麻烦您帮我送到这里，拜托啦~", "索娅")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("servent","",0.25)
	await novel_interface.show_dialog("明白！", "随行人员")
	await novel_interface.hide_all_characters()
	
	# scene2 - 美术馆
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("为了脱离围观的人群，拉斐尔将我们拉到街边一家相对清静的美术馆。")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("所以说，你整个下午都在带她们俩逛街？", "拉斐尔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","wry_smile",0.25)
	await novel_interface.show_dialog("大致是这样……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("下午我们三人都在这一带游荡，先后去了甜品店和游戏厅，索娅都兴致索然。")
	await novel_interface.show_text_only("但来到电器街后，这个家伙就完全刹不住车了……")
	await novel_interface.show_text_only("她一幅天真无邪的样子，却总钻进“超限制级”的区域逛！")
	await novel_interface.show_text_only("而且挑出来的东西，都实在让人无法相信她是第一次来这里……")
	await novel_interface.hide_background()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("印刷品会留下曾触碰过它的人的痕迹――", "索娅")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("只要是那种散发着粉红色气息的本子，就可以直接买哦~！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这家伙的能力平时都用在这些奇怪的地方吗！？")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_text_only("结果我一手拎着购物袋，一手捂着身前伊露卡的眼睛，在那个区域门口等了好久……")
	novel_interface.change_expression("shy_right")
	await novel_interface.show_text_only("进进出出的人总免不了对我上下打量一番，实在不堪回首……")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	await novel_interface.show_text_only("拉斐尔像看白痴一样对着我叹了口气，然后表情严肃的说道——")
	novel_interface.show_character("ren_fishnet","shy_right")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","normal2",0.25)
	await novel_interface.show_dialog("你不知道今天下午的事吗？", "拉斐尔")
	await novel_interface.stop_music()
	novel_interface.character_light(0.35, "upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("诶？发生什么了？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("今天中午各个学园都市首脑和代表开始了为期48小时的封闭会议，这件事你总知道吧？", "拉斐尔")
	novel_interface.character_light(0.35, "perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("好像…在新闻里听过……？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("抱歉，并没有听过，这种政治新闻我都是看到就换台的。")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("封闭会议开始两小时后，会场外的第三学园都市议长忽然发布了一个爆炸性的声明。", "拉斐尔")
	await novel_interface.show_dialog("声明中宣布，马萨达堡的『自动反击系统』已经建造完成并正式投入运行了。", "拉斐尔")
	await novel_interface.show_dialog("这个系统建立在完全闭锁的物理环境内，由不与外界联网的AI模组控制。", "拉斐尔")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("一旦开始运行，在20年内都无法被关闭。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("有种阴谋的味道……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("然而，那根本不是之前外界猜想的，由AI自动对各种外界攻击进行自动反击的系统。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔露出一种复杂的表情——恐惧、愤怒、似乎还有些许悲伤。")
	await novel_interface.show_text_only("她顿了一下，快速整理好自己的情绪。")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("这个系统只有一个功能——就是当它判断马萨达市区毁伤程度达50%时，就会启动『末日程序』。", "拉斐尔")
	novel_interface.show_background("res://assets/images/bg/Soya/Doomsday1.png")
	await novel_interface.show_dialog("通过异质物『幻想军势』向全世界所有大型城市无差别投放核弹。", "拉斐尔")
	await novel_interface.show_dialog("就是说无论谁对马萨达堡造成了毁灭性打击，这个系统都会拉上全世界一起陪葬。", "拉斐尔")
	await novel_interface.show_dialog("这是被写死在系统固件上的底层机制，即使是国家元首也无法关闭。", "拉斐尔")
	await novel_interface.show_dialog("如果强行破坏、关闭或改写系统逻辑，会立刻触发末日程序的启动。", "拉斐尔")
	novel_interface.show_background("res://assets/images/bg/Soya/galleries.png",0.5)
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("哦呀呀……", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("这……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然还有很多细节不甚清楚，但仅仅那几个关键词就足以说明事态之严重。")
	await novel_interface.show_text_only("『幻想军势』是第三学园都市的战略级异质物，地位类似『埃癸斯』之于新丰洲。")
	await novel_interface.show_text_only("那是一种空间类异质物，从特定空间发射的武器可以获得威力倍化的异常效果——")
	await novel_interface.show_text_only("当那些武器击中大气层内的目标时，能产生几倍到几百倍于原设计值的破坏力。")
	await novel_interface.show_text_only("由于马萨达严格的保密措施，外界对其具体参数知之甚少。")
	await novel_interface.show_text_only("甚至『幻想军势』这个名字也是代称，源自某位敌方将领的嘲讽――")
	await novel_interface.show_text_only("当年西奈半岛补给线被切断，那位将军四处叫嚣想要守住马萨达只能凭幻想。")
	await novel_interface.show_text_only("后来他的阵地被一枚“威力大到匪夷所思”的反坦克导弹所夷平……（所以说不要随便立Flag）")
	await novel_interface.show_text_only("外界并不知道『幻想军势』的准确位置，据说整个马萨达堡都是围绕它建造的。")
	await novel_interface.show_text_only("经过多年的加强，现在那座堡垒都市甚至能轻易应对洪水、地震、台风等自然灾害了。")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("（我记得即使是被幻想军势加强的武器，也会被埃癸斯完美防御吧，而且这是公开的信息……）","小怜")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("不过AI什么的……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在所有的科幻作品中，把核按钮交给人工智能从来就没有过什么好事。")
	await novel_interface.show_text_only("我脑中回想起全裸兄贵机器人和戴着墨镜在轮椅中瘆笑的博士……")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("声明的附件中有相关AI的全部测试数据，毕竟他们是第一个将人工智能投入实战的国家。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔有些焦虑的看向窗外。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("我不担心程序，我担心的是人――", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("今天电器街的人群，似乎比以往多了几倍……")
	
	# scene3 - 大使馆
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("与此同时，协约非武装区内，纽摩利达斯大使馆。")
	await novel_interface.show_background("res://assets/images/bg/Soya/Embassy.png")
	await novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("马萨达用这个系统将『幻想军势』封存起来，放弃了主动使用它的权利。", "伦伯特")
	await novel_interface.show_dialog("在保证共同毁灭的表象之下――", "伦伯特")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("这个系统的本质，也可以说是一种强制和平声明。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("讲话的男性穿着讲究的手工定制西装，将手中的威士忌酒杯放在了桌上。")
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("我同意。", "戴眼镜的女性")
	await novel_interface.show_dialog("但您事前知道那套系统的情报吧？", "戴眼镜的女性")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("……你还是这么喜欢单刀直入呢，秋子。", "伦伯特")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("这种系统在建造完成并正式启动之前绝不能走漏半点风声，不然全世界都会来阻止。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("老骗子。", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("秋子面无表情的扶了扶眼镜。")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("……", "伦伯特")
	await novel_interface.show_dialog("总之，现在木已成舟，民众在抗议一阵之后也只能接受这个现实。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("老骗子。", "秋子")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("……抱歉，我不该向你隐瞒。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("哼。", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特清了清嗓子。")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("马萨达现在最希望的，就是控制住负面舆论，尽量避免联合议会成员国的经济制裁。", "伦伯特")
	await novel_interface.show_dialog("两年前纽摩利达斯终止了对马萨达的贷款之后，他们只能变本加厉的掠夺周边地区。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("杀鸡取卵。", "秋子")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("但是去年萨蒙顿开始接收难民，一方面是为了对冲逐年减少的本国人口数量――", "伦伯特")
	await novel_interface.show_dialog("另一方面也借难民形成了一条缓冲带，将马萨达封锁在欧洲之外。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("这下鸡也没了。", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("秋子翻了个白眼。")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("由于连年战争，马萨达军队和相关系统已经占据了全国人口的15%，国家财政已经不堪重负了。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("所以他们还想借这次公布自动反击系统进行裁军？", "秋子")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("这只是节流，还要开源――", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("军火交易。", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("秋子立刻想到了马萨达唯一的土特产。")
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("或者说，贩卖“国防解决方案”。", "伦伯特")
	await novel_interface.show_dialog("抵抗军一直被认为是潜伏在马萨达周边的世界级恐怖组织……", "伦伯特")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("但这些都是马萨达刻意运作的媒体宣传。", "伦伯特")
	await novel_interface.show_dialog("那么一个内部分裂、从管理到技术都被甩开一个时代的组织，被吹捧成为全人类的威胁。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("要想贩卖安全，必先散布恐惧…", "秋子")
	await novel_interface.show_dialog("几十年前卖安全软件的都明白这个道理。", "秋子")#文本错误
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("那么在这件事情上，你的诉求是？", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特在桌面展开的地图上，指向了亚洲与非洲的交界处。")
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("哼，我想也是。", "秋子")
	await novel_interface.hide_character()

	print("=== 天启篇第04话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
