# apocalypse_ep06.gd - 天启篇第06话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第06话剧本
	apocalypse_ep06_script()

func play_script():
	pass

# 天启篇第06话 - 正式剧本
func apocalypse_ep06_script():
	# scene1 - SID指挥室
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("指挥室内，莉琉眉头紧锁的盯着大屏幕上循环播放的视频。")
	await novel_interface.show_text_only("那是几小时前马萨达堡议长在发布会上介绍『自动反击系统』时的录像――")
	await novel_interface.show_text_only("画面中的大叔面带微笑谈吐自然，就像在给主妇介绍新款烤箱的推销员。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("面部分析结果出来了？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("确认是议长本人无误，而且基本没发现伪装的情绪或微表情――", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣似乎对结果有些失望。")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("也就是说，他在给公众介绍世界末日时，脸上的微笑是发自真心的？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("切，我也可以~", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣有些不服气，被莉琉敲了回去。")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("他又不是你――", "莉琉")
	await novel_interface.show_dialog("这位马萨达议长从政将近20年了，他应该非常清楚这种行为会导致的后果……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉看了看屏幕顶部一排新闻画面，萨蒙顿靠近西亚的几座城市已经爆发了难民示威游行。")
	await novel_interface.show_text_only("在那排画面下方，是新丰洲的热点分布图，几块高亮的地区说明抗议的人群正开始聚集。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("媒体管控做的如何了？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("虽然我们没有签发禁止令的权利，但大多数公司知道SID介入后，都选择了乖乖配合。", "爱衣")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("那几家态度坚决的，目前都因“未知来源”的网络攻击全面瘫痪中。", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣做了个鬼脸，莉琉的嘴角微微上扬。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("不过咱们也拦不住全世界的媒体呐……", "爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("目前只有华云宫一如既往的进行着新闻管制，其他几国都炸开锅了。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("那就不是我们要操心的了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_dizzy")
	await novel_interface.show_dialog("那要不要对协约非武装区的网络也……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉对爱衣摆了摆手。")
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("这几天联合议会对任何攻击都敏感的要死，你就别惹事了。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉注视着每秒刷新一次的城市热点图，在思考如何让防卫厅和市政部门的官僚们乖乖配合。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("哎，元老院那帮家伙开封闭会议，只留下个什么事都不管的大猩猩在外面……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她在手持设备上选中几个电车站，然后拨通手下探员的电话。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("现在我们要分散热点地区的人流，给交通局发一套爆炸物警告，告诉他们这几个车站一律禁止停车。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("明白。", "SID探员")
	novel_interface.show_character("agent")
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("啊，记得叫拆弹组去装装样子~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("遵命。", "SID探员")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("派人盯着市区里这五个重点区域，这些地方今天都比往常聚集了更多的人群。", "莉琉")
	await novel_interface.show_dialog("现场注意随机应变，如果情况不对就穿着防化服在街上散布二氧化硫气体，伪装成瓦斯泄露什么的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("好的。", "SID探员")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉挂断电话，看到爱衣正一脸期待的看着自己。")
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("你往西北地区打两发碘化银炮弹，下场雨就都老实回家了。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("记得算好风向，别影响到协约非武装区——国际公约可是很麻烦的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("嘿嘿，没问题~", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	
	# scene2 - 美术馆与瑟蕾莎
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("cereza","wordless")
	await novel_interface.show_text_only("我偷偷打量着面前这位姐姐的衣服。")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","timid")
	await novel_interface.show_dialog("（好、好大！）\n（运动的时候不会跳出来吗……）","小怜")
	#await novel_interface.show_text_only("")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她似乎看穿了我的想法，拉了拉束缚着丰满胸部的皮带，有些轻佻的笑着说。")
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("有它们兜着呢，出不来~", "黑发女性")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("额……啥？\n（我的想法被看穿了？）", "小怜")
	#await novel_interface.show_text_only("")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("（不、不用继续拉了啊！都勒出色情的形状了！）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("瑟蕾莎——你怎么过来了？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔身后不远处，头上还冒烟的索娅拉着伊露卡怒气冲冲的朝我走来。")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("还不是布勒那老巫婆！给我打了十几个电话，困死我了……", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎满脸倦怠的打着哈欠伸了个懒腰，顺势用一只胳膊搂住了我的脖子。")
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("呐~这就是莉琉手下的那个“小怜”吧？\n上次联合行动跟你一起的那个？", "瑟蕾莎")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("(她知道上次联合行动的事？)","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔“啊”了一声，就将脸转向一侧，回避着对方的目光。")
	await novel_interface.show_text_only("瑟蕾莎也不含糊，不由分说的移到我身后，两只手掐住我的肩膀捏了捏。")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("嗯，根骨不错，但缺乏锻炼。", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("实在抱歉，没有肌肉让您见笑了。")
	await novel_interface.show_text_only("接着她将食指勾起，用指关节顶住我的脊柱两侧向下滑，滑到腰窝的时候稍一用力――")
	await novel_interface.show_text_only("我顿觉一阵温热酥麻的感觉传遍全身，忍不住叫出声来。")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("啊~", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("厚？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔一幅见惯不怪的态度，而索娅似乎对我的叫声提起兴趣凑了过来。")
	await novel_interface.show_text_only("这人只三两下蜻蜓点水的手法，我就意识到自己根本无力反抗，只得乖乖站好任由她摆弄。")
	await novel_interface.show_dialog("乖，闭上眼――", "瑟蕾莎")
	await novel_interface.show_text_only("瑟蕾莎在我耳边轻轻说道。")
	await novel_interface.show_dialog("想象你的右手小臂想要向前弹出去，但是被手指卡住无法动弹，只能慢慢蓄力。", "瑟蕾莎")
	await novel_interface.show_text_only("我顺着瑟蕾莎的指引将右臂抬起，将右手手指扣住我的左肩。")
	await novel_interface.show_dialog("深呼吸……………………", "瑟蕾莎")
	await novel_interface.show_dialog("放――", "瑟蕾莎")
	await novel_interface.show_text_only("我只觉随着右手手指放开，整只手臂像拉满的弓弦一样弹了出去，半空中似乎切到了什么――")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_text_only("索娅刚巧站在我面前一臂开外的距离，刘海上一缕银发被我的指甲利落的切开。")
	novel_interface.change_expression("afraid")
	await novel_interface.show_dialog("欸？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我们俩对视愣在原地，看那缕银发缓缓飘落……")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("对、对不起！\n没伤到你吧？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("厄呜~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅发出了小动物一样的声音。")
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("你刚才的气息，好像穿透了我的身体……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅满脸红晕的看着我说道，似乎还很陶醉的样子！")#换行问题
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("嘿嘿，怪不得我们家大小姐非要留在新丰洲……", "瑟蕾莎")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("少废话——你到底做什么来的！？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","jest")
	await novel_interface.show_dialog("我来送你回大使馆啊。", "瑟蕾莎")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("你究竟是……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("啊，姑且自我介绍一下――", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎调整了一下胸部的位置。")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("我是十字玫瑰的格斗总教官瑟蕾莎。", "瑟蕾莎")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("就是专门教人打架的——虽然都是我打别人。", "瑟蕾莎")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("大小姐惹事的时候，偶尔会客串一下保镖。", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎对拉斐尔抛了个媚眼，被拉斐尔无情的白了回去。")
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("她爷爷还给过我一枚同袍勋章呢~", "瑟蕾莎")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("所以说，究竟发生什么事了？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("嗯……我也才睡醒，不过据老巫婆说。", "瑟蕾莎")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("马萨达堡议长…在酒店房间吞枪自杀了。", "瑟蕾莎")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","angry")
	await novel_interface.show_dialog("什么——？！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("怎么回事？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("我的情报只有这些，那个什么议长你们认识？", "瑟蕾莎")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("啊——！", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎拍了下脑门大叫一声，扭头看着我。")
	novel_interface.show_character("cereza","boring")
	await novel_interface.show_dialog("这个情报似乎应该保密……", "瑟蕾莎")
	novel_interface.change_expression("blink")
	await novel_interface.show_dialog("嘛……算了算了～", "瑟蕾莎")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("算、算了？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("反正SID应该也知道了，就连保安军都提升到二级警戒状态了。", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎清了清嗓子，收起吊儿郎当的姿态，挺直腰板拿起了手中的日本刀。")
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("所以呢——根据安保协议，我来护送大小姐回使馆。", "瑟蕾莎")#换行问题
	await novel_interface.hide_character()

	print("=== 天启篇第06话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
