# apocalypse_ep19.gd - 天启篇第19话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第19话剧本
	apocalypse_ep19_script()

func play_script():
	pass

# 天启篇第19话 - 正式剧本
func apocalypse_ep19_script():
	# Scene 1 - 神曲开场
	novel_interface.show_background("res://assets/images/bg/Soya/DivinaCommedia.png")
	await novel_interface.show_text_only("那片平和的金红色光芒\n位于中央，灿烂辉煌")
	await novel_interface.show_text_only("而四面八方的光焰则一概减弱光亮")
	await novel_interface.show_text_only("我看见正是在那中央\n有一千多位欢乐喜庆的天使在展翅飞翔")
	await novel_interface.show_text_only("它们各有各的技艺和亮光……")
	await novel_interface.show_text_only("──《神曲》天堂篇-XXXI")
	
	# Scene 2 - 地下密室对话
	novel_interface.change_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("莉琉的手指玩弄着那张照片，同时仔细观察着面前的这个头发花白的男人。")
	await novel_interface.show_text_only("关于他的情报十分有限，就连伦伯特（Lambot）这个没有姓氏的名字是不是真名都无人知晓。")
	await novel_interface.show_text_only("但他因对“和平事业的杰出贡献”而以这个名字被授勋却是不争的事实。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("（既然有秋子的确认，应该是个可谈判的对象。）", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("绝大多数人认为，所谓联合议会，是因为各国元首聚集于此，所以才成为了世界的权力中枢。", "莉琉")
	await novel_interface.show_dialog("历史上确实有过那种机构，只不过组织松散且各成员之间争吵不休，主席更像个和事佬和要饭的。", "莉琉")
	await novel_interface.show_dialog("然而联合议会的预算规模和影响力与之前那些机构完全不可同日而语。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉将照片收起来，正色说道。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("利益产生信任，信任产生权力，而权力通过对资源的协调与分配，又能制造更大的利益──", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特的眉头上扬。")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("这是沃克尔的基础社会模型。", "伦伯特")
	await novel_interface.show_dialog("政治人物由利益团体选择出来，作为承载民众信任的代理人。", "伦伯特")
	novel_interface.change_expression("relax")
	await novel_interface.show_dialog("如果代理人无法维持并制造更大的利益，就会被剥夺权力换个新的。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("虽然从宏观历史上确实如此，但民众从来不是理性的，正如勒庞所说──", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("群体追求和相信的从不是什么真相和理性，而是盲从、残忍、偏执和狂热，只知道简单极端的感情。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特自言自语的接话，莉琉微笑着点了点头。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("有太多手段可以绕过利益的环节，直接取得民众的信任了。", "莉琉")
	await novel_interface.show_dialog("那样的领袖也从不惮以巨大的牺牲为代价，成就自己的功业──", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("但在七年战争之后，那些真正维持着人们生活和国家运转的人开始反思。", "莉琉")
	await novel_interface.show_dialog("最终由那些人成立了『联合议会』这样一个由“利益相关方”直接进行协作与博弈的组织。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("所以真相是：能进入联合议会的人，才有资格成为国家元首。", "莉琉")
	await novel_interface.show_dialog("而这个组织的第一次行动，是在三年前──", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉停顿了片刻，伦伯特盯着她，屏住了呼吸。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("三年前，联合议会和教廷在南美秘密测试EX级异\n质物，在强压之下，当地的军阀也只能乖乖配合。", "莉琉")
	await novel_interface.show_dialog("然而试验失控，造成了4.6万人死亡。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Bernadotte.png")
	await novel_interface.show_dialog("后来那次事件被包装成『丘伦河大屠杀』，嫁祸给了当时唯一没有配合你们的军阀卡洛斯·布兰科。", "莉琉")
	await novel_interface.show_dialog("这一惨案受到世界各大媒体的关注和轮番报导，民众的厌战情绪在那次事件中集中爆发。", "莉琉")
	await novel_interface.show_dialog("而以联合军事行动处决那个军阀，也成为了联合议会合法性的重要基础之一。", "莉琉")
	novel_interface.change_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("但在试验现场，那数万具尸体以一座教堂为中心呈放射状的排列，实在太不自然了……", "莉琉")
	await novel_interface.show_dialog("我猜为了掩盖真相，你们向那个地方投放了能干扰半径三公里内一切电磁波的异质物武器。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("类似的异常曾在西亚战场上出现过，因为光也是一种电磁波，以至于卫星都无法拍出正常的画面。", "莉琉")
	await novel_interface.show_dialog("这就是为什么在那扇门被关闭后，整个区域的电磁干扰依然持续了几周的时间。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉故意强调了『那扇门』三个字的语气，听到这里，伦伯特默默闭上了眼睛。")
	novel_interface.change_background("res://assets/images/bg/Soya/Churun.png")
	await novel_interface.show_text_only("莉琉端详着手中的照片。")
	await novel_interface.show_dialog("清理那么多尸体需要大量的工作人员，很难做到严格管理。", "莉琉")
	await novel_interface.show_dialog("我猜你怎么也想不到，现场有人用老式机械相机和已经发霉的胶片拍下了这张照片。", "莉琉")
	await novel_interface.show_dialog("而照片中远景的异常模糊，就是异质物武器扭曲光线的效果所致。", "莉琉")
	novel_interface.change_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.show_character("lambert","usually")
	await novel_interface.show_dialog("你怎么知道我有参与呢？", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("你在此一个月前刚被任命为联合议会『禁止异质物武器试验条约组织』的执行秘书长。", "莉琉")
	await novel_interface.show_dialog("这个组织明面上是要禁止任何人进行异质物武器试验，因而拥有非常可观的资源和情报能力。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("你不可能对这种规模的事件毫无了解，而之所以选择默不作声，是因为那次试验就是由你主导的──", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特并没有表示反驳，莉琉乘胜追击。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("最后是教廷出面回收那个异质物，事后他们也因此得到了联合议会超乎寻常的资助和授权。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("那个异质物，是一扇半开的漆黑大门，门后面闪烁着刺眼的金光──", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("够了！不用说了。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特打断了莉琉，举起双手表示认输。")
	await novel_interface.show_text_only("他收紧西服领子，稍稍调整了一下嗓音。")
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("我们的工作，确实是要保证没有人可以随意进行异质物武器试验。", "伦伯特")
	await novel_interface.show_dialog("因为异质物太过危险，稍有不慎就会导致文明的毁灭，但是那次试验不得不做……", "伦伯特")
	await novel_interface.show_dialog("那扇门背后传来的敲门声一次比一次急促，而门被打开已是无法避免的──", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("敲门……？", "莉琉")
	await novel_interface.hide_character()
	
	# Scene 3 - 天堂之门
	novel_interface.change_background("res://assets/images/bg/Soya/BlackGate.png")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_dialog("『天堂之门』……", "伦伯特")
	await novel_interface.show_dialog("每个宗教和神话体系都有自己定义的天堂，或许那些定义都系出同源。", "伦伯特")
	await novel_interface.show_dialog("根据历史记载，在那扇门被打开前，其门后会传来\n“咚咚咚──”的连续三下敲门声。", "伦伯特")
	await novel_interface.show_dialog("据说那声音低沉深邃，像是在敲击听者的灵魂……", "伦伯特")
	await novel_interface.show_dialog("当敲门声开始出现时，最初的间隔是一周，接着间隔时间会越来越短。", "伦伯特")
	await novel_interface.show_dialog("当间隔小于到90秒时，门随时可能被打开──", "伦伯特")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("随你怎么定义门后的存在，但它拥有能造成世界末日级灾难的能力，这一点是毋庸置疑的。", "伦伯特")
	await novel_interface.show_dialog("比如超大型洪水吗……", "伦伯特")
	await novel_interface.show_dialog("在教廷的文献中，唯一能压制“门”的办法，就是要在以门为中心在小范围内聚集数万人……", "伦伯特")
	await novel_interface.show_dialog("是某种献祭？", "莉琉")
	await novel_interface.show_text_only("伦伯特并没有直接承认这种说法，接着说道。")
	await novel_interface.show_dialog("这种事每几百年就会出现一次，而每次的死者都会以门为中心呈放射状排列。", "伦伯特")
	await novel_interface.show_dialog("这种仪式大多都是秘密进行，但因间隔太久，偶尔会被特定时代的人利用──", "伦伯特")
	await novel_interface.show_dialog("比如1572年，发生在巴黎的圣巴多罗买之夜。", "伦伯特")
	await novel_interface.show_dialog("圣巴托罗缪纪念日前夜，发生了被称为“数个世纪中最可怕的宗教屠杀”，死亡人数达到7万。", "伦伯特")
	await novel_interface.show_dialog("巴黎……", "莉琉")
	novel_interface.show_background("res://assets/images/bg/Soya/Paris.png")
	await novel_interface.show_dialog("以门为中心呈放射状排列！？", "莉琉")
	await novel_interface.show_text_only("莉琉忽然想到那座城市道路交通最显著的特点。")
	await novel_interface.show_dialog("那可能算是历史开的一个玩笑吧~", "伦伯特")
	await novel_interface.show_text_only("伦伯特声音中带着一丝戏谑。")
	novel_interface.change_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("既然是可以被敲的门，应该是有形的物质，为什么不毁了它或者用火箭抛出太阳系呢？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("『天堂之门』只是一个概念，最初的时候，门每次出现的位置都不一样。", "伦伯特")
	await novel_interface.show_dialog("就算在没有门的地方，那扇门甚至能直接在古城墙的墙面上显现。", "伦伯特")
	await novel_interface.show_dialog("虽会带来灾厄，但也是最能显现神迹的圣物。", "伦伯特")
	await novel_interface.show_dialog("历史上各个宗教势力对这个概念归属权的争夺从没停过……", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("概念要怎么争夺？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("历史记载中，圣索菲亚大教堂拥有天堂之门最长时间的归属权。", "伦伯特")
	await novel_interface.show_dialog("后来15世纪弗洛伦撒的雕塑家吉贝尔蒂用毕生精\n力创作的作品将那个“概念”夺了过来。", "伦伯特")
	await novel_interface.show_dialog("1452年，那个作品完成后被作为圣母百花圣殿洗礼堂的大门，终于成为了被世人认可的天堂之门。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("原来是这样──", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("人类争夺一个概念最古老的办法，就是用最奢华宏伟的作品进行自证。")
	await novel_interface.show_text_only("无论金字塔、神庙、宫殿、皇冠或是王座。")
	await novel_interface.show_text_only("为的都是证明自己的正统，证明自己是最被认可的存在。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("等一下，那作品完成的第二年，圣索菲亚大教堂所在的君士坦丁堡就被攻占了，难道是因为……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特摇了摇头。")
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("那段历史是一团迷雾，并没有直接的证据。", "伦伯特")
	await novel_interface.show_dialog("然而确定的是，吉贝尔蒂的作品在七年战争中被毁了……", "伦伯特")
	await novel_interface.show_dialog("想要准确控制那扇门出现的位置，并保证它下次打开时处在一个可控区域内的话──", "伦伯特")
	novel_interface.change_expression("relax")
	await novel_interface.show_dialog("就只能联合教廷制造一个复制品。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("但试验中出现了偏差，不知为何门并没有被顺利关闭，所以教廷才会如此的不惜代价……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉终于将零散线索完整的串联在一起，每一方的行为都有了合理的理由。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("那之后一系列的情报覆盖和媒体引导都是大师级的操作，选择的替死鬼也堪称完美……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到莉琉的自言自语，伦伯特无奈的笑了笑。")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("我该说过奖吗？", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("不， 如果有一天人类不得不面对那种强大的力量的话──", "莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("怀抱着道德底线自欺欺人，用无知来安慰自己是最愚蠢不过的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","serious")
	await novel_interface.show_dialog("但人类就是这样脆弱的生物，为了安全感，宁愿放弃安全。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉的嘴角挑起，提高了声调。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("所以说，“道德”终归是有价值的。", "莉琉")
	await novel_interface.show_dialog("在那次试验中掩盖真相也是你分内的工作，而现在真相在我手里──", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","serious")
	await novel_interface.show_dialog("确实如此，说你的条件吧。", "伦伯特")
	await novel_interface.show_dialog("虽然我也不过是一介代理人，连那一系列决定是由联合议会的哪位做出都不知道。", "伦伯特")
	await novel_interface.hide_character()
	
	# Scene 4 - 交易谈判
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("放心，不会超出你的能力范围的。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("我的条件是，第三学园都市，施恩内曼总理的接替者，不能是军方的人。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特显然对这个要求有些意外。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("虽然从账面上，只要联合议会给马萨达开放武器售卖的权限，就能维持他们稳定地区局势的军备。", "莉琉")
	await novel_interface.show_dialog("但政治不只是算账，权力也是人心所向──", "莉琉")
	await novel_interface.show_dialog("在民众开始厌恶战争和仇恨的时候，维持庞大军备的基础已经松动了。", "莉琉")
	await novel_interface.show_dialog("你没发现最近马萨达的媒体越来越多的使用“学园都市”而不是马萨达堡称呼自己的首都了吗？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特沉默不语。")
	await novel_interface.show_text_only("这时左侧电梯黑色的大门传出“叮”的一声，一位戴着眼镜的女性提着一只小型手提箱从电梯走出。")
	novel_interface.show_character("lambert","surprise")
	await novel_interface.show_dialog("秋子？", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("下午和那个死胖子偷偷会面也就算了──", "秋子")
	await novel_interface.show_dialog("莉琉可是我介绍的，见面都不通知我一下吗？", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特看向莉琉，莉琉无奈的摊了摊手。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("她追问得太凶了，我也没办法。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("额……", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","serious")
	await novel_interface.show_dialog("老骗子。", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("秋子说着打开手提箱，里面是12只被海绵固定得\n整整齐齐的电池。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("这些电池的参数我想你已经知道了。", "莉琉")
	await novel_interface.show_dialog("马萨达加班加点的赶工，要趁着和平论坛展示他们高能量密度的电力存储产品……", "莉琉")
	await novel_interface.show_dialog("是想要像1900年巴黎世博会上展出电灯一样，向世界宣布他们在军事技术转向民用转化的成果吧。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("毕竟，这件事是施恩内曼总理亲自下令推进的──", "莉琉")
	await novel_interface.show_dialog("而且根据我们的情报，他的身体状况应该支撑不到下个逾越节了。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到这里，伦伯特似乎有所触动。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("至于保持航路的畅通……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉走近一步，盯着伦伯特的眼睛说道。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("自然是由“利益相关方”共同负担成本才最稳妥，不是吗？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","usually")
	await novel_interface.show_dialog("好吧……", "伦伯特")
	await novel_interface.show_dialog("不过这样你能得到什么好处──", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉没有回答，而是从箱子里拿起一只电池，像闻雪茄一样吸了吸。")
	novel_interface.show_character("akiko","perspire")
	await novel_interface.show_dialog("变态。", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉用电池撩拨了一下秋子的头发，后者“哼”了一下，不屑的扭过头。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("哦？你还是这么喜欢戴平光镜啊~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("平光镜？", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("而且你也有好处，如果马萨达的计划能够实现，就会需要大量纽摩利达斯的资本。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("……我明白了。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("至于人选，走一步看一步吧~", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉将电池放回箱子，对伦伯特伸出右手。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("成交？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特握住莉琉的手表示同意，几秒钟后却发现她并没有松手的意思。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("那么接下来，第二件事──", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("你们今天的这次试验……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("……", "伦伯特")
	novel_interface.change_expression("usually")
	await novel_interface.show_dialog("哦？你是怎么看出来的。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("马萨达议长的妻子和女儿几年前死于一次车祸，他曾多次想要尝试自杀。", "莉琉")
	await novel_interface.show_dialog("但是性格懦弱的他一直没能成功，今天居然死得这么干脆。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特慢慢抽回了手，脸上带着微笑。")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("不错的理论，但这只是推测。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("再加上那些暂时失去痛觉的病例──", "莉琉")
	await novel_interface.show_dialog("我想这次试验异质物的效果，是能够暂时屏蔽人们包括痛觉在内的负面感受吧？", "莉琉")
	await novel_interface.hide_character()
	
	# Scene 5 - 切回小怜视角
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("在空无一人的宽阔路口，一辆黑色SUV突然调头。")
	novel_interface.show_background("res://assets/images/bg/Soya/Backseat.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("发现了灯罩中的秘密后，我们临时决定改道去新丰洲纪念教堂。")
	await novel_interface.show_dialog("这个灯罩会将一小部分光线以特定的角度偏转，但上面还有很多说不通的设计啊……", "爱衣")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("什么意思？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("首先，偏转光线的范围极窄，只有大概1度夹角左右的范围能观察到这张图。", "爱衣")
	await novel_interface.show_dialog("从其他角度看，只会接收到普通的黄色光线。", "爱衣")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("如果是那种人山人海的集会现场，只有1度夹角也能覆盖到很多人吧……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("这就是最奇怪的了──", "爱衣")
	await novel_interface.show_dialog("在灯罩偏转光线时，会将可见光转化为人眼无法观测到的波长。", "爱衣")
	await novel_interface.show_dialog("所以就算真的身处特定角度，人也不会受到影响。", "爱衣")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("……怎么会？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那不是完全没法发挥作用了吗？")
	await novel_interface.show_dialog("回收队在现场找了30多个身处特定角度的人，发\n现他们的身体状况全都是正常的。", "爱衣")
	await novel_interface.show_text_only("车厢内再次陷入了沉默……")
	await novel_interface.show_text_only("又回到起点了吗。")
	await novel_interface.show_text_only("目前只知道4个患者的详细状况──")
	await novel_interface.show_text_only("被伊露卡电过的那位萝莉控大叔、纽摩利达斯的女记者、电力公司的维修工和约翰……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我闭上眼，努力想象任何将他们关联起来的东西。")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	await novel_interface.show_text_only("那个萝莉控大叔的工口抱枕和他紧握着的手机壳上印的都是幼女的图样。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Night_Park.png")
	await novel_interface.show_text_only("约翰在公园里交代，他在电器街看到贝阿特丽切在花车上骂人时偷偷录了视频。")
	novel_interface.change_background("res://assets/images/bg/Soya/Cordon.png")
	await novel_interface.show_text_only("冲到了游行队伍前面却按不动快门的女记者……")
	novel_interface.change_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	await novel_interface.show_text_only("我推倒那个跪在地上的警员时，好像被一个穿着电力公司制服的维修工偷拍了……")
	novel_interface.change_background("res://assets/images/bg/Soya/Parade.png")
	await novel_interface.show_text_only("如果我身处那样史无前例的大型集会之中，会情不自禁的怎么做呢……")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("掏出手机──", "小怜")
	novel_interface.show_background("res://assets/images/bg/Soya/Backseat.png")
	await novel_interface.show_dialog("嗯？", "爱衣")
	novel_interface.show_character("ren_fishnet","normal1")
	await novel_interface.show_dialog("中招的人，是不是都在路灯附近使用过手机或者其它什么摄像设备……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("啊──你是说！", "爱衣")
	await novel_interface.show_text_only("爱衣一幅恍然大悟的样子。")
	novel_interface.change_background("res://assets/images/bg/Soya/infrared.png")
	await novel_interface.show_dialog("确实，有些电子类相机会将一些肉眼看不到的光线转化为可见光。", "爱衣")
	await novel_interface.show_dialog("就像用很多手机的镜头对着红外遥控器的发射端并且按遥控器的话，就能拍到一道很刺眼的光线。", "爱衣")
	await novel_interface.show_dialog("如果那些人恰好在特定角度用手机拍到了路灯，就会看到那个画面。", "爱衣")
	novel_interface.change_background("res://assets/images/bg/Soya/Backseat.png")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("我的手机也可以吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你的手机是SID定制，镜头上覆盖高级摄像器材才有，能过滤不可见光的滤膜。", "爱衣")
	await novel_interface.show_dialog("但很多手机都没有，还有的相机为了追求画面效果的真实感，特意去掉了那种滤膜。", "爱衣")
	await novel_interface.show_dialog("太有趣了！我去找几个D级人员做一下试验──", "爱衣")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("啥……啥！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("耳机那头传来爱衣撒欢般跑远的声音，之后便是一片死寂。")
	await novel_interface.show_text_only("哈，哈哈……不知又有谁要倒霉了。")
	await novel_interface.show_text_only("我看着一直望向窗外沉默不语的索娅。")
	await novel_interface.show_text_only("艾尔加纳是从小把她带大的人吧……")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("（对她而言，可能是像母亲一样的角色？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我轻轻拍了拍索娅的后背，她扭过头对我淡淡一笑。")
	await novel_interface.show_text_only("就像镜头的滤膜一样，人们似乎总想追求更纯净的画面，但其实只是蒙住了一部分眼睛去观察。")
	await novel_interface.show_text_only("真实的世界本来就不是那么纯净的吧。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("而索娅眼中的世界，到底是怎样的呢……")
	
	# Scene 6 - 教堂场景
	novel_interface.change_background( "res://assets/images/bg/Soya/Church_N.png")
	await novel_interface.show_text_only("再次回到教堂时，门外的路上已经聚集了几十名荷枪实弹的保安军。")
	await novel_interface.show_text_only("我们和索娅在门口下车，远远就看到艾尔加纳端庄的站在金色大门前，像是在迎接我们的到来。")
	await novel_interface.show_text_only("几名SID特工已经控制了她，并且正在把她的个人物品一箱箱搬到门口的空地上。")
	await novel_interface.show_text_only("在特工的允许下，我们走到艾尔加纳面前。")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N_Door.png")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("刚才走得很突然呢，你的腰好一点了吗。", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我没有回答，艾尔加纳看着地上一箱箱被特工贴上\n“证物”标签的物品，脸上的笑意突然收敛起来。")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("索娅，圣赦院封存的秘匣是你打开的吗？", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("……", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她长叹了口气。")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("你总是这么管不住自己的好奇心啊……", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳见我一直警觉的盯着她，似乎想对我解释什么。")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("教堂上的这扇大门，是我这些年不断进行试验和改良的作品──以『天堂之门』为基础的仿制品。", "艾尔加纳")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("现在我已经能做到用精准的触发方式，暂时解除人类大脑中的一小部分抑制系统了。", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她介绍的时候，语气中带着些许自豪，好像今晚的游行和暴动是她亲手制作的解药一样。")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("每个人的心底都藏着很多想法和欲望，但总被各种现实的理由压抑着。", "艾尔加纳")
	await novel_interface.show_dialog("那些人们想做而不敢做的事情──", "艾尔加纳")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("我受到了『门』的启发，借助它的力量将人们被压抑的欲望解放出来。", "艾尔加纳")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("这才是达成自我救赎的最好方式吧？", "艾尔加纳")
	await novel_interface.show_dialog("──这样，有什么错吗？", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳保持着优雅的姿态，但声音有些颤抖。")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("啊……你可能无法理解吧。", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她抬起头，好像陷入了回忆──")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("我故乡的那座小村庄只有一百多人，十几年前在教堂做礼拜时，闯进来一伙强盗。", "艾尔加纳")
	await novel_interface.show_dialog("一百多人被四个强盗劫持了全部财物，其中只有两个人有枪。", "艾尔加纳")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("他们的领头是个逃兵，说要按军队对付逃兵的十一抽杀律，从所有村民中抽签杀掉十个人。", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我心中一惊，在七年战争开始前，有些国家早已陷入了长年累月的地区冲突。")
	await novel_interface.show_text_only("为了补充兵员进行强制征兵，甚至恢复了一些很野蛮的惩罚措施。")
	novel_interface.show_character("el","sad")
	await novel_interface.show_dialog("我在保护自己女儿时被他们用枪托打晕了……", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("女儿……？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("el","sad")
	await novel_interface.show_dialog("那一百多名村民看着强盗用刀一个个杀掉抽到签的十个人，无论老人还是小孩……", "艾尔加纳")
	await novel_interface.show_dialog("全程没有一个人敢挺身而出，大家只是暗自期待自己不要被选中。", "艾尔加纳")
	await novel_interface.show_dialog("后来追缉这些强盗的宪兵赶到并抓捕他们时，发现那四个人加起来只有两发子弹。", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳眼角中带着泪光，忽然笑了出来。")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("两发子弹……", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我沉默的看着艾尔加纳，无法想象她见到自己女儿被杀害而没有一个人敢挺身而出时的绝望。")
	await novel_interface.show_text_only("或许没有约翰解围的话，今天我和索娅也无法从电器街全身而退吧。")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("（等等，伊露卡的左眼是军用电子义眼，难道她也这样中招了才──）", "小怜")
	await novel_interface.show_dialog("什么将被压抑的欲望解放出来……", "小怜")
	await novel_interface.show_dialog("那几个强盗，才是将他对军队压抑的怨气全都放出来了吧？！", "小怜")
	await novel_interface.show_dialog("你利用的那扇门……你知不知道索娅为了控制住它付出多大的牺牲？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("el","surprised")
	await novel_interface.show_dialog("控制？", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳不解的看着我，忽然情绪激动了起来。")
	novel_interface.show_character("el","surprised")
	await novel_interface.show_dialog("如果能解除所有的限制归于一体，难道不是人类最好的状态吗？", "艾尔加纳")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("你知不知道，索娅是第一个被神明回应的人，而她居然拒绝了？！！", "艾尔加纳")
	await novel_interface.show_dialog("说什么牺牲？修道院的孩子本来就是为了这个目的被养大的──", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳指着索娅。")
	novel_interface.show_character("el","shout")
	await novel_interface.show_dialog("她，不是一开始就知道吗！！？", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我实在难以抑制内心的怒火，用尽全力一巴掌扇过去，把旁边的特工都吓了一跳。")
	await novel_interface.show_text_only("艾尔加纳似乎被打蒙了，缓缓低下头，没有再发出声音。")
	await novel_interface.show_text_only("我也没想到自己居然真的打上去，稍稍整理了一下心绪后冷冷的说道。")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("没什么好跟你说的了，你在国际领土进行异质物试验，会被押送联合议会的法庭进行审判吧。", "小怜")
	await novel_interface.hide_character()
	
	# Scene 7 - 切回地下密室
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("与此同时，地下密室内。")
	novel_interface.change_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("伦伯特认真的听着莉琉揭露这次试验的内容。")
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("反正事后也要统计，我提前问一下，你们接到的病例全都恢复了吗？", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("无一例外，有些还没被送到医院就恢复了痛觉，叫得鬼哭狼嚎的。", "莉琉")
	await novel_interface.show_dialog("但你的行动队似乎对我的人很不客气啊──", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("见到莉琉眼中射出的凶光，伦伯特立刻举起双手退后两步，笑着耸了耸肩。")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("我明白了，但是……", "伦伯特")
	await novel_interface.show_dialog("我发誓，这次试验我一点都不知道，也没派出过任何行动队。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("什么──？！", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("我刚才只是顺着你的话模糊的接下去，想多收集些信息罢了。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("akiko","normal")
	await novel_interface.show_dialog("早跟你说了，这家伙就是个老骗子。", "秋子")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("秋子合上了手提箱，不屑的看了一眼伦伯特。")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("等等，如果连你都不知道的话──", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉拿出手机，大脑飞速的思考着。")
	await novel_interface.show_text_only("她赶忙拨通瑟蕾莎的电话，响了很久之后终于传来一个睡意朦胧女声。")
	await novel_interface.show_dialog("哈？我刚脱光了躺下，你还让不让人睡觉了啊……", "瑟蕾莎")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("你只要回答我一个问题就好──", "莉琉")
	await novel_interface.show_dialog("戴克斯博士参加封闭会议之前，让你给拉斐尔带话的内容是什么？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("啊？只是担心他孙女想让她早点回家什么的吧……", "瑟蕾莎")
	await novel_interface.show_dialog("博士答应了大小姐帮她弄到伏尼契的手稿。", "瑟蕾莎")
	await novel_interface.show_dialog("条件是在他开会的这两天，路灯一亮起来，就要立刻回家。", "瑟蕾莎")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("……那老狐狸果然知道！", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉挂断电话后立刻接通小怜。")
	
	# Scene 8 - 最终场景
	await novel_interface.hide_background()
	await novel_interface.show_text_only("耳机中突然传出莉琉的声音，我连忙走开几步跟她通话。")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","normal1")
	await novel_interface.show_dialog("莉琉？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("小怜，你马上撤离，车就停在门口！", "莉琉")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("怎、怎么了……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看着那些忙碌的SID特工和站在那里低头不语的索娅，不理解莉琉的紧张从何而来。")
	await novel_interface.show_dialog("现在派出的六支回收队都被保安军拦截了，那边给SID的临时监控权限也刚刚被收回……", "莉琉")
	await novel_interface.show_text_only("我看到教堂门口那些保安军一阵骚动，似乎接到了新的命令。")
	await novel_interface.show_dialog("总之你快点离开教堂！能做到这种事的只有──", "莉琉")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("没等莉琉说完，耳机中就传来一阵干扰的杂音，随后信号就被切断了。")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N3.png")
	await novel_interface.show_text_only("我抬起头，猛然发现周围的气氛变得诡异起来。")
	await novel_interface.show_text_only("刚才远处还清晰可见的楼群忽然一片扭曲模糊，天空也瞬间暗沉了下来。")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("天上的星星……不见了？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("两辆没有车牌的黑色装甲运兵车从大街疾速驶入教堂，同时一架黑色直升机也正从上空缓缓降落。")
	await novel_interface.show_text_only("门口的保安军跟运兵车一起冲进广场，迅速解除了那些正在搬运资料探员的武器。")
	await novel_interface.show_text_only("艾尔加纳向我走过来，脸上带着阴冷的微笑。")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("到底怎么回事？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳举起手，我以为她要把那巴掌还给我，但她只是轻轻拍了拍我的脸。")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("……你说审判我？谁来审判？", "艾尔加纳")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("你以为，是什么人在支持这项研究？", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳转身看着教堂上气势恢宏的壁画。")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("在协约非武装区中心地段，规划出这么大一块用地来建设教堂……", "艾尔加纳")
	await novel_interface.show_dialog("短时间内对整个城区的路灯进行改造，还有──", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她扭过头来看着我。")
	novel_interface.show_character("el","mock")
	await novel_interface.show_dialog("还有提前解除电器街的限行措施……", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的大脑顿时嗡的一下，头皮一阵发麻──")
	await novel_interface.show_text_only("那些从运兵车和直升机下来的士兵，全都穿着熟悉的黑色特种作战服。")
	await novel_interface.show_text_only("但他们并未理会我和那些探员，而是直接去拆卸教堂的大门。")
	novel_interface.show_character("el","mock")
	await novel_interface.show_dialog("这次实验足以证明，我终于找到了安全且可逆的影响人们心智的方法。", "艾尔加纳")
	await novel_interface.show_dialog("你知道这是多大的成就吗？", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N1.png")
	await novel_interface.show_text_only("那些黑衣士兵很快便将教堂大门封装进木箱并运上直升机。")
	await novel_interface.show_text_only("艾尔加纳拍了拍我的脑袋，我看到索娅缓缓向我们这边走来。")
	novel_interface.show_character("el","mock")
	await novel_interface.show_dialog("你和那丫头只接触了一天，就自以为有多了解她。", "艾尔加纳")
	await novel_interface.show_dialog("要是没有我对异质物的研究和调配的药，你觉得她的身体可能支撑到今天吗？", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	
	# Scene 9 - 地下密室终场
	await novel_interface.show_text_only("地下密室内。")
	novel_interface.show_background("res://assets/images/bg/Soya/Underground_Hall.png")
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("如果确实如你所说，那东西的价值太大了……", "伦伯特")
	await novel_interface.show_dialog("试想一下，如果在视频中插入几帧短暂的画面，就能影响数千万人。", "伦伯特")
	await novel_interface.show_dialog("只要是那种能激发人们欲望和冲动的内容，就能轻易将无数人变为忠诚的消费者、信徒或者士兵。", "伦伯特")
	novel_interface.change_expression("usually")
	await novel_interface.show_dialog("还有能比这更能快速获取权力的方式吗？", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉拿着失去信号的手机，沉默不语。")
	novel_interface.show_character("lambert","usually")
	await novel_interface.show_dialog("不管背后主导这次实验的人是谁，他们应该知道不会得到我的支持。", "伦伯特")
	await novel_interface.show_dialog("但你是怎么突然想到戴克斯博士的？", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("排除法──", "莉琉")
	await novel_interface.show_dialog("如果联合议会背后真的存在这样一个组织，必然要保证六大学园都市的力量都参与其中。", "莉琉")
	await novel_interface.show_dialog("但每家都有自己的国情和历史包袱……", "莉琉")
	await novel_interface.show_dialog("华云宫的内阁成员明显分为两个派系，纽摩利达斯董事会的十七位绅士各怀鬼胎。", "莉琉")
	await novel_interface.show_dialog("马萨达军方与民间本来就有很大矛盾，军队内部的派系还很难协调。", "莉琉")
	await novel_interface.show_dialog("新丰洲的元老院是按照学术准入的，那几个老家伙的情报能力还不如我。", "莉琉")
	await novel_interface.show_dialog("莱博娜群岛三大黑帮谁也不服谁，只是依靠轮流坐馆的制度才勉强维持和平。", "莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("六个学园都市里，只有萨蒙顿……无论科技、经济还是政治，都没有任何人能与戴克斯博士抗衡。", "莉琉")
	await novel_interface.show_dialog("那些所谓的“贵族”，不过是一帮附庸在他集团下的小股东罢了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("确实……", "伦伯特")
	await novel_interface.show_dialog("能以一人之力推进难民接收计划，这在其他学园都市是不可想象的。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("所以，如果真的存在一个能凌驾于各国最高领导层之上的组织，戴克斯博士必然是其中一员。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_dialog("只是不知道，那只老狐狸扮演的是什么角色……", "莉琉")
	
	# Scene 10 - 最终告别
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N1.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_text_only("索娅走到我们旁边，说想和我单独聊几句。")
	await novel_interface.show_text_only("艾尔加纳不屑的走开，吩咐士兵将地上那些标着证据的材料也搬上直升机。")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("小怜……", "索娅")
	await novel_interface.show_dialog("抱歉刚才一直瞒着你，但我不知道怎么开口。", "索娅")
	await novel_interface.show_dialog("但我今天才知道嬷嬷一直在研究这些东西。", "索娅")
	await novel_interface.show_dialog("虽然我可以自由出入各个国家，但一直不能离开她很远。", "索娅")
	await novel_interface.show_dialog("这次来新丰洲，也是因为她要过来……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅低着头，声音越来越小。")
	novel_interface.show_character("soya_uniform","snivel")
	await novel_interface.show_dialog("而且她说得对──", "索娅")
	await novel_interface.show_dialog("修道院收养的孤儿，本来就会被培养成黑衣修士。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着浑身颤抖的索娅，我轻轻的抱住了她。")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("笨蛋，刚才在车上你就一直很为难吧……", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_text_only("她在我怀里小声说道。")
	await novel_interface.show_dialog("呐……", "索娅")
	await novel_interface.show_dialog("今天拉着小怜的手，我感觉身体被一团微暖的东西包裹着，似乎体内充满了力量。", "索娅")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("（拉着……我的手？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳站在直升机旁呼喊着索娅过去，但她就像舍不得分别的孩子，突然紧紧抱住我。")
	await novel_interface.show_text_only("声音带着哭腔──")
	await novel_interface.show_dialog("对不起，要是能多和你玩会儿就好了……", "索娅")
	await novel_interface.show_text_only("我的大腿外侧忽然感到一阵微小的刺痛，刚想检查一下时却发现手指都无法移动。")
	await novel_interface.show_text_only("我想要发出声音，嗓子却完全使不上力气。")
	await novel_interface.show_dialog("（……河豚毒素？！）", "小怜")
	await novel_interface.show_dialog("（索娅你……）", "小怜")
	await novel_interface.show_text_only("由于肌肉被麻痹，我连惊愕的表情都无法做出来。")
	await novel_interface.show_text_only("她小心的扶着我，缓缓将我放倒在地上，将我的身体靠在喷泉的石台边。")
	await novel_interface.show_text_only("她还拿了什么东西垫在我的身后，使我腰部的压力缓解了不少。")
	await novel_interface.show_text_only("那些黑衣士兵似乎已经完成任务，坐上运兵车驶出大门。")
	await novel_interface.show_text_only("索娅又看了一眼瘫坐在地上的我，扭头就跑向直升机──")
	await novel_interface.show_text_only("几十秒后，我听到直升机起飞的声音，那些保安军也开始按顺序撤退。")
	await novel_interface.show_text_only("我用尽全力想抬头看她一眼，却完全做不到。")
	await novel_interface.show_text_only("随着直升机的声音渐远，信号屏蔽也终于解除，耳机中再次传来莉琉焦急的声音。")
	await novel_interface.show_dialog("喂喂──小怜你怎么样了？？", "莉琉")
	await novel_interface.show_dialog("刚才司机发现，你们拆下的电灯里的电池不见了！", "莉琉")
	await novel_interface.show_dialog("爱衣说输入电压超过32伏的话，哪怕只有一瞬，都会引起爆炸！", "莉琉")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("等等，那个放电脚环的最大距离是……")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N2.png")
	await novel_interface.show_text_only("突然间，远处传来一声尖锐的炸响，整个夜空瞬间亮如白昼。")
	await novel_interface.show_text_only("接着就是直升机爆炸的剧烈轰鸣。")
	print("=== 天启篇第19话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
