# apocalypse_ep14.gd - 天启篇第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第14话剧本
	apocalypse_ep14_script()

func play_script():
	pass

# 天启篇第14话 - 正式剧本
func apocalypse_ep14_script():
	# 开场设置
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("我目送着接伊露卡回SID本部的车渐渐消失在道路尽头，又想起刚刚那一幕。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("约翰他应该没事吧……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅盯着手中那片沾满血迹的玻璃，若有所思的说道──")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("这东西虽然割断了一些肌肉组织，但没伤到他的主要血管，能及时治疗的话问题不大……", "索娅")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("但他居然能带着那种伤走上20多分钟，一般人应该早就疼晕了。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("……难道是『无痛症』之类的？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我想起之前看过的动画和电视剧都曾有症状类似的角色。")
	await novel_interface.show_text_only("由于感觉不到疼痛，即使是普通的阑尾炎都可能恶化到致命的腹膜穿孔什么的。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("那至少应该有触觉吧──", "索娅")
	await novel_interface.show_dialog("裤子上那么大片的凝固血液不可能感觉不到，可他却没流露出一丁点不适的气息，简直……", "索娅")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("太有趣了！！", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("要不要过两天去医院试试看，什么样的刺激才能让那小子有反应……", "索娅")
	await novel_interface.show_dialog("难道是因为小怜？", "索娅")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("啧啧，那样的话还得想办法绕过那个母猩猩把小怜给拐出来……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅自言自语的念叨着一些很不妙的事情，我忽然感到胸部一阵酥麻。")
	await novel_interface.show_dialog("哪个母猩猩啊~","莉琉")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("莉、莉琉！？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅惊恐的环视四周，但除了捂住胸部躲在一旁的我，周围空无一人。")
	await novel_interface.show_dialog("小怜想我了吗？", "莉琉")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("你就不能打手机吗！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","laugh",0.25)
	await novel_interface.show_dialog("居然……", "索娅")
	await novel_interface.show_text_only("索娅终于发现了音源，立刻露出一副“请务必让我检查一下胸部”的表情。")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("就像看到归家主人的大型犬一般，摇着尾巴向我飞扑了过来──")
	await novel_interface.show_text_only("突然她的脚踝闪出一道耀眼的弧光，飞在半空的身体瞬间就被拍了下去。")
	await novel_interface.show_text_only("只见索娅脸贴地面，先是右侧的胳膊和腿抖动了两下，很快就以半身不遂的姿态爬了起来。")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("（似乎……复活得越来越快了？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她眼中闪烁着泪花，一边揉着尚未恢复的左臂，一边抬起头对着天空抗议。")
	novel_interface.show_character("soya_uniform","cry")
	await novel_interface.show_dialog("喂！这破脚环还能遥控吗？！", "索娅")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/UAV.png")
	await novel_interface.show_text_only("我顺着索娅看的方向望去，一个小红点幽幽的浮在半空。")
	await novel_interface.show_dialog("无人机？", "小怜")
	await novel_interface.show_dialog("这一带不是禁飞区吗……", "小怜")
	await novel_interface.show_text_only("虽然SID平时都无视这种限制，但莉琉前几天才强调过，国际和平论坛期间绝不许踩红线。")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("（不知袭警、越狱和挑起暴动算不算……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("今天情况特殊，目前第一大道那边聚集的示威人群已经超过五万人了。", "莉琉")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("这么多？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("现在总共7个区域发生了暴动，保安军总部也乱成了一锅粥。", "莉琉")
	await novel_interface.show_dialog("我跟他们的指挥官说，如果这次事件处理不当，很有可能会殃及新丰洲──", "莉琉")
	await novel_interface.show_dialog("顺便稍稍给了他和他的家人一点压力，那家伙就很干脆的决定与SID共享安保权限了。", "莉琉")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("（“稍稍”个鬼啊！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("他们为了这次和平论坛真是下本，统一更换了协约非武装区内所有市电路灯的照明和监控系统。", "莉琉")
	await novel_interface.show_dialog("居然把每盏路灯都变成了一台监控摄像机，还配套安装了相应的网路和控制单元。", "莉琉")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("可市电路灯的覆盖范围本来就有限吧，你还不是得用无人机。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅抓住机会想要吐槽，莉琉却表示认同。")
	await novel_interface.show_dialog("这种监控方案成本和收益根本不成正比，而且还有很大的政治风险──", "莉琉")
	await novel_interface.show_dialog("万一被媒体发现，肯定会把乔治奥威尔之类的抬出来对联合议会口诛笔伐一番。", "莉琉")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_dialog("不过我真正想要的情报正是这个。", "莉琉")
	novel_interface.change_background("res://assets/images/bg/Soya/Club.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("只要给一些人施加很小的影响，就能让全世界最有权力的机构做出明显愚蠢的决策。", "莉琉")
	await novel_interface.show_dialog("关键是如何锁定那些人……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉满意的看着手持设备刚录入的几千份档案，每份档案都标明了身份、账号、金额和备注信息。")
	await novel_interface.show_dialog("什么意思……", "小怜")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("比如新丰洲城市邦联的最高权力机构是元老院，那元老院在新丰洲的权力是无限的吗？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你好像就不怎么听他们的……", "小怜")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("所以说，每个国家都有复杂的权力体系，影响因素可能有经济、军事、历史、文化、宗教等等原因。", "莉琉")
	await novel_interface.show_dialog("而一国元首，只是在各方的复杂博弈中，被推选出负责维持均衡的代理人。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("从古至今，无论是民主、独裁、共和或者是学院政体，从来没有什么真正的王──", "莉琉")
	await novel_interface.show_dialog("有的只是不断妥协，在一个个电车难题中替众人做出抉择，并以自己的人格背负全部谴责的人。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉顿了顿，望向远处一排穿着防辐射服正在引导人员疏散的回收队员。")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("背负着这些东西的人看似强大，但身上早已伤痕累累。", "莉琉")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅单手捂在胸前沉默不语，我却听得一头雾水。")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("还是没听懂……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("因为不是说给你听的……笨蛋。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅调整了一下呼吸，郑重其事的问道。")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("你已经掌握了足够的筹码，但还缺关键的最后一块拼图，所以想跟我做个交易，对吗？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("没错。", "莉琉")
	await novel_interface.show_text_only("莉琉的回答简单干脆。")
	await novel_interface.show_dialog("据我所知，『审判骑士』本意是“持有真理之印的黑衣修士”，500多年里只有不到20人获此殊荣。", "莉琉")
	await novel_interface.show_dialog("历史上战斗天赋异禀的黑衣修士并不在少数。", "莉琉")
	await novel_interface.show_dialog("但要想获得代表神之国最高豁免权的真理之印，需要被教廷认定作出了重大贡献。", "莉琉")
	await novel_interface.show_dialog("你的真理之印是在两年前，由已故的上任教宗卡利克斯特四世亲自颁发的──", "莉琉")
	await novel_interface.show_dialog("而那时你还不到12岁吧？", "莉琉")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("调查的很清楚呐……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那么我就直接问了。", "莉琉")
	await novel_interface.show_dialog("三年前，你在圭亚那高的那次“净化”任务，究竟做了什么？", "莉琉")
	await novel_interface.show_text_only("索娅沉吟了片刻，之后抬起头。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("我知道你想要什么，但你得先答应我几个条件~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你说吧。", "莉琉")
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("第一，马上解除这个脚环！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("做不到。", "莉琉")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("哈？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("解除脚环需要SID的特殊设备，目前只能先把你和小怜的安全距离设为最大的200米。", "莉琉")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("好吧……总比10米强。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不一会，索娅脚环上的黄灯闪了几下。")
	await novel_interface.show_dialog("设置好了。", "莉琉")
	await novel_interface.show_text_only("索娅盯着我小心翼翼的后退，直到我们距离肯定超过10米的程度才松了一口气。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("第二，我要知道贝阿特丽切和小怜的关系，让小怜亲口跟我说。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉沉默了好一阵。")
	await novel_interface.show_dialog("可以，但你要保证不能对其他人透露。", "莉琉")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("真、真的没问题？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切本人在13世纪去世，根据爱衣的说法\n，她现在的身体是我在召唤她的那一刻制造的。")#换行问题
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("（我制造了那么棒的身体吗？一点实感都没……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然而这件事被列为绝对机密，即使对元老院都严格保密。")
	await novel_interface.show_text_only("目前只有我、安妮、贝阿特丽切、拉斐尔、戴克斯博士、莉琉、爱衣和海因里希8个人知情。")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("（她们俩要交换的究竟是什么级别的情报啊……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("我保证不对别人说。", "索娅")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("不过小怜要是撒谎的话，我一眼就能看出来哦~", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("知道啦知道啦！\n就你厉害……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然后，索娅饶有兴致的听我讲了之前在天空酒店通过拉斐尔的宝石项链召出贝阿特丽切的全过程。")
	await novel_interface.show_text_only("在莉琉的默许下，连贝阿特丽切打退雅各以及她身上的诅咒都说了出来。")
	await novel_interface.show_text_only("索娅两眼放光，像听故事的小孩子一样，边听边发出阵阵惊叹。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("所以拉斐尔家那条祖传项链上的绿宝石，最初是镶嵌在贝阿特丽切佩剑上的？", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("嗯，爱衣鉴定之后确认了。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("贝阿特丽切·波尔蒂娜，原来被但丁写在诗里的那个人是魔女……", "索娅")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("真是太有趣了！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("咳咳──", "莉琉")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("你想要的证据就在我身体里，如果是那个爱衣的话应该能检查出来。", "索娅")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("但我还想陪小怜再多玩会儿，明天中午12点前我\n们一起回SID可以吗？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那好吧……", "莉琉")
	await novel_interface.show_dialog("对了小怜，爱衣已经把无人机和保安军的监控画面衔接在一起了，你也有权限，用手机就能看。", "莉琉")
	await novel_interface.show_dialog("今晚的暴乱，不知是不是跟异质物有关，你们一定要小心。", "莉琉")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("说罢，莉琉结束了通信。")
	novel_interface.change_background("res://assets/images/bg/Soya/Club.png")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("至于你们几个──", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉看着地上几个被五花大绑，扒得只剩内裤，嘴上还贴着胶条的拍卖会组织人员。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("是想要死于辐射泄露呢……", "莉琉")
	await novel_interface.show_dialog("还是乖乖合作，之后来一次愉快的记忆消除呢？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("地上的那几位一边扭动身体，一边惊恐的发出“呜呜”的声音。")
	await novel_interface.show_text_only("莉琉踩住其中一人，露出女王般的微笑。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("哼，我猜也是──", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("诶嘿嘿嘿──", "索娅")
	await novel_interface.show_text_only("看到莉琉离线，索娅立刻露出了不怀好意的笑容。")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("你、你要干嘛……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("嘿嘿，刚才就想问，怕那个母猩猩不让说──", "索娅")
	await novel_interface.show_dialog("既然会被贝阿特丽切魅惑，那么小怜是男生？", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("诶？", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("我、我是……女孩子……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这要我怎么回答啊！！")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("真实中夹杂着谎言的颜色……", "索娅")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("果然所有事情里，最有趣的就是小怜啊！", "索娅")
	await novel_interface.show_dialog("还有你的胸部究竟是什么原理──", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("你走开啊！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我向教堂大门的方向逃走。")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("你、你不是刚联系了那个嬷嬷说很快就到吗？\n结果让老人家等那么久──", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("哎呀呀~你就是小怜吧？", "女性的声音")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N_Door.png")
	await novel_interface.show_text_only("一个温柔的声音问道。")
	novel_interface.show_character("el","smile")
	await novel_interface.show_text_only("我循声望去，一位修女正站在教堂大门外，面带微笑的看着我。")
	await novel_interface.show_text_only("她大概三十多岁，看得出保养得很好，一头金色长发直垂到腰间。")
	await novel_interface.show_dialog("看你们这么久都没到，我有点担心就出来看看。", "艾尔加纳")
	await novel_interface.show_dialog("我叫艾尔加纳。", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("艾尔加纳……嬷嬷？", "小怜")
	await novel_interface.hide_character()
	
	print("=== 天启篇第14话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
