# apocalypse_ep11.gd - 天启篇第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第11话剧本
	apocalypse_ep11_script()

func play_script():
	pass

# 天启篇第11话 - 正式剧本
func apocalypse_ep11_script():
	# scene1 - 开始
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("这群笨蛋，基本上都是男人啊——", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切微笑着举起右手，露出那个灰绿色金属质地、微微泛着淡蓝色光晕的手环。")
	await novel_interface.show_text_only("那是爱衣用能屏蔽模因类异质物影响的特殊合金制作的可以压制『诅咒』效果的道具。")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("等等，你是想……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我记得莉琉几周前对我说过，那个『诅咒』会让所有看到她的男性陷入疯狂的迷恋。")
	# scene2 - 回忆莉琉的解释
	novel_interface.show_background("res://assets/images/bg/Soya/FusiformGyrus.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_dialog("准确的说，是她的脸——", "莉琉")
	await novel_interface.show_dialog("爱衣的一系列试验发现，直视贝阿特丽切的脸会使男性大脑的梭状回和杏仁核区域高度兴奋。", "莉琉")
	await novel_interface.show_dialog("但仅限于距离80米内的直视——照片、录像、或\n镜面反射都不会产生效果。", "莉琉")
	await novel_interface.show_dialog("这种兴奋持续一段时间后，会使观察者的大脑产生不可逆的变化，并改变整个人的行为模式。", "莉琉")
	await novel_interface.show_dialog("由迫切想要占有她，转为求而不得的焦虑、狂躁、仇恨……甚至会产生自残、纵火和暴力倾向。", "莉琉")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("还真是对恋爱的现实写照啊——", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉无奈的叹了口气。")
	await novel_interface.show_text_only("我刚想问这种可怕的试验爱衣是如何做的，但思量了一下觉得还是不知道为好……")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("（还好我不是她的小白鼠~）", "小怜")
	await novel_interface.show_dialog("……", "小怜")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("等等！你昨天命令我穿着『那种衣服』单独给贝阿特丽切做历史介绍。", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("不会也是爱衣的试验……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","shock")
	await novel_interface.show_dialog("你才反应过来？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("果然是吗？！")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("喷喷……那贝阿特丽切昨天戴的手环是假的，这件事你也还不知道吧？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉有些失望的看着满脸震惊的我。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("指定那身衣服，是想避免你的主观感受污染试验数据，所以用『羞耻感』来混淆『爱慕感』。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("而且……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她突然双手捏住我的肩膀，脸上露出微妙的笑容。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("让你穿兔女郎装果然很有意思~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("啊啊啊啊啊啊啊啊啊——！！！\n不要再提了啊啊啊啊啊啊啊啊！！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那地狱般的一个多小时，我穿着兔女郎装在封闭的房间里和贝阿特丽切面对面。")
	await novel_interface.show_text_only("满脸通红的我紧张得一句整话都说不出来，走路都顺拐了…")
	await novel_interface.show_text_only("贝阿特丽切也全程强忍着笑意安慰我……")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("爱衣说当时你大脑的3D扫描像烟火表演一样，要不是后来脑压过高，她才不愿喊停呢。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("不过现在能确认，虽然你的大脑会像男性一样对贝阿特丽切表现出兴奋，却不会留下任何创伤。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("换成其他人的话，短则四十秒，最长八分钟，就会留下永久的烙印。", "莉琉")
	await novel_interface.show_dialog("是不是很安心啊？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("安心个屁啊——！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("最近希望消除掉的回忆有点太多了。")
	
	# scene3 - 回到现场
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("（所以，如果在这里解除手环的话……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切对我温柔的笑了笑，随后将我抱住，双手搭在我身后。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我的视野被整个遮挡，面前一片漆黑。")
	await novel_interface.show_dialog("唔？", "小怜")
	await novel_interface.show_dialog("一会我说“开始”之后，你们有30秒的时间。", "贝阿特丽切")
	await novel_interface.show_dialog("救出伊露卡后咱们分开行动，在附近的新井中心公园汇合，那一带没有示威的人群。", "贝阿特丽切")
	await novel_interface.show_dialog("——听明白了吗？", "贝阿特丽切")
	await novel_interface.show_text_only("我点了点头，尽量不去想象面前软软的触感。")
	await novel_interface.show_dialog("我、我也要——", "索娅")
	await novel_interface.show_text_only("“咯”")
	await novel_interface.show_text_only("金属卡扣碰撞的声音，手环被解除了。")
	# scene4 - 索娅的视角
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN1.png")
	await novel_interface.show_text_only("在索娅眼中，整个电器街瞬间被笼罩了一层粉红色的光幕。")
	await novel_interface.show_text_only("下午跟小怜她们逛书店的时候，凡是散发出这种颜色气息的书，内容似乎都“很有保证”。")
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("你也是魔女？！", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("哦？你能辨别魔女的特征吗？", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","shy")
	await novel_interface.show_dialog("但和伊露卡、拉斐尔她们有些不一样——", "索娅")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("你和小怜的气息，都像婴儿一样纯净！", "索娅")
	await novel_interface.show_dialog("……简直，太有趣了！！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅的声音异常兴奋，拼命摇着我的后背。")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("唔唔哇呜咿呃！！\n（要无法呼吸了！！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("这幅身体确实比我印象中轻呢——\n多亏了这个小可爱~", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("巨乳大姐姐将怀中的小怜抱得更紧了些。")
	await novel_interface.show_text_only("小怜似乎很激动，手拼命的在空中比划。")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("……你究竟是什么人？", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("啊，似乎忘了做自我介绍呢~\n我叫贝阿特丽切·波尔蒂纳。", "贝阿特丽切")
	await novel_interface.hide_character()
	
	# scene5 - 90分钟前的场景
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("90分钟前。")
	novel_interface.change_background("res://assets/images/bg/Soya/Club.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("协约非武装区内，新丰洲鹭华园酒店。")
	await novel_interface.show_text_only("顶层宴会厅——听鹂堂门外。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("居然在99层修了个露天庭院……是不是华云宫的\n人都喜欢这么干？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉看着庭院顶部大厦的玻璃屋顶不屑的笑笑。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("可能越高越显得尊贵吧……而且99这个数字听起\n来比较吉利？", "斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女困惑的挠了挠头。")
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("你到底是怎么锁定这场拍卖会的？", "斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉目光转向了宴会厅门口的喷绘。")
	await novel_interface.show_text_only("大标题是“致元博物馆秋季拍卖会”\n下面一行小字：艺术与金融交汇新模式")
	await novel_interface.show_text_only("蓝底白字的设计非常刺眼，让人很难相信这是艺术品拍卖会。")
	novel_interface.show_character("skuld","perspire")
	await novel_interface.show_dialog("太难看了吧？一幅诈骗的样子……", "斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉笑着点了点头。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("但这场拍卖会的五百个位置座无虚席，63件拍品\n已经卖出去了60件，没有一件流拍。", "莉琉")
	await novel_interface.show_dialog("目前这60件拍品的累积成交额已经超过15亿了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("这么多？！这属于世纪级拍卖会了吧？\n怎么我都没听过……", "斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("你之前提供的那些电子加密货币账户里，总共有几十亿的资金。", "莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("数目虽不算少，但也就能造两栋这样的大厦而已。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("想用这点钱影响联合议会几万亿的重建基金，只有一种可能——", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("特意用加密数字货币的话……用来行贿？", "斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("虽然账户是加密的，可交易会在全网广播，这种规模的转移想不引起注意是不可能的——", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("所以需要提供一个合理的解释……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德歪头飞速思考着，忽然眼前一亮。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("拍卖会！", "斯库尔德")
	await novel_interface.show_dialog("用无法定价的古董很容易转移大额资金，瓷器玉器古画这种艺术品拍出几百万也不会惹人注意。", "斯库尔德")
	await novel_interface.show_dialog("又是发生在国际领土的交易，各国税务部门都有追税权力，结果反而无法收税。", "斯库尔德")
	await novel_interface.show_dialog("只要联系好交易双方，再以某个私人博物馆的名义卖点垃圾就能名正言顺的做到。", "斯库尔德")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("但不能让会场有懂行的人，否则可能被戳破……", "斯库尔德")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("啊，所以才座无虚席！\n都是他们安排好的自己人？", "斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉摸了摸斯库尔德的头。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("你每天在御樱川的初中部上课不会无聊吗？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("秘密~", "斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德有些得意的看着莉琉。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("哼，那我再教你点东西吧——", "莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("『战后重建基金』本质上是联合议会放的贷款，借钱的政府不敢倒债，否则就是与六大国为敌。", "莉琉")
	await novel_interface.show_dialog("但历史上这种贷款基本没有能按期还上的，这里就会产生很大的谈判空间。", "莉琉")
	await novel_interface.show_dialog("以董事会那几人的财力，应该只是想把最有利可图的那小块切走，比如电力和通信这种基础设施。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("只要跟政府首脑说电力设施的贷款不用还了，条件是永久占有电网30%的股份。", "莉琉")
	await novel_interface.show_dialog("那种手头缺现金的政府多半会同意，甚至国家元首私下主动要求返利也说不定。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("那要怎么才能切走那小块呢？", "斯库尔德")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("得让联合议会同意跨国企业进驻基金，而且能有一定的自主选择权吧……", "斯库尔德")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("这种让步也太大了，真的可能吗？", "斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉没有回答，而是提了个问题。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("这个喷绘如此粗糙，说明什么？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("说明伪装工作不上心。", "斯库尔德")
	await novel_interface.hide_character()
	
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("这么大的交易额，花钱包下了酒店顶层，还雇了几百号人，为什么不好好伪装呢？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("嗯……", "斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德一时接受了太多信息，脑子有点转不动。")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("因为这种事在这里或其他地方，早已发生过不知多少次了——", "莉琉")
	await novel_interface.show_dialog("从没被发现或质疑过，所以不会上心。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("贿赂本身也是种学问，尤其是这种地下交易，更需要收集大量情报，安排好上下各级人员的利益。", "莉琉")
	await novel_interface.show_dialog("为了这些情报，不知要长年累月的进行多少调查、拉多少人下水、做多少次今天这种利益交换——", "莉琉")
	await novel_interface.show_dialog("协调官员、媒体、工会、非政府组织甚至犯罪团体中哪些位置的哪些人……", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("就可以影响联合议会的关键决策。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉两眼放光的看着宴会厅的大门。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("——这才是这场拍卖会中最有价值的东西。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德垂下头叹了口气。")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("好讨厌……感觉又被碾压了。", "斯库尔德")
	novel_interface.change_expression("talk")
	await novel_interface.show_dialog("等等，你一开始就是这么打算的吧！？", "斯库尔德")
	await novel_interface.show_dialog("根本不是想将影响重建计划的人绳之以法……", "斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然，宴会厅的大门打开一道小缝，法贝拉伸出一只手比着“OK”的手势。")
	await novel_interface.show_text_only("那是拍品全部拍完，进入电子加密货币转账环节的信号。")
	await novel_interface.show_text_only("莉琉拿起对讲机——")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("回收队封锁99层的电梯通风管和全部出口，通知\n酒店98层检测到了大剂量的辐射污染物。", "莉琉")
	await novel_interface.show_dialog("切断大楼的有线网络和所有频段通信信号，行动开始后全员进入无线电沉默。", "莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("行动！", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("…………")
	
	# scene6 - 回到现场
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Brooklyn.mp3")
	await novel_interface.show_text_only("贝阿特丽切终于放开憋得满脸通红的我，将我调转方向背对着她并耳语了几句。")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("一会等我说“开始”，还有不要偷看哦~", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("之后她就将我推向了伊露卡花车的方向——我拼命挤进人群，索娅跟在后。")
	await novel_interface.show_text_only("贝阿特丽切气定神闲的走向附近的另一辆花车，像女王一样一个个推开了挡在前面的男人。")
	await novel_interface.show_text_only("那些被推开想发火的家伙一看到她的脸，立刻就进入发呆模式。")
	await novel_interface.show_text_only("贝阿特丽切轻巧的爬上了一辆没有表演的花车，两个工作人员正在车顶调试音响。")
	await novel_interface.show_text_only("她毫不费力的要来了麦克风，看着我和索娅摸到了伊露卡附近后示意工作人员开到最大音量。")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("开始！", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到她声音清晰的从背后传来，我对索娅点了点头。")#换行问题
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("行动！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切的下一句发言将透过那台刚调试好，功率开到最大的音响，穿彻整个商店街。")
	await novel_interface.show_text_only("只见她站在车头，闭上眼睛后深深的吸了一口气。")
	novel_interface.show_character("beatrice_regular","angry")
	await novel_interface.show_dialog("你们这群渣滓——", "贝阿特丽切")
	await novel_interface.show_dialog("不折不扣的变态！！", "贝阿特丽切")
	await novel_interface.hide_character()
	
	print("=== 天启篇第11话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
