# apocalypse_ep01.gd - 天启篇第01话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第01话剧本
	apocalypse_ep01_script()

func play_script():
	pass

# 天启篇第01话 - 正式剧本
func apocalypse_ep01_script():
	# scene1
	novel_interface.change_background("res://assets/images/bg/Soya/Marie_Curie.png")
	await novel_interface.show_text_only("我们一直被教育，要学习那些优秀的品格。")
	await novel_interface.show_text_only("很多人都读过居里夫人小时候专心看书，完全不受旁人影响的故事。")
	await novel_interface.show_text_only("姐姐和同学们为了试探，悄悄在她身后搭起了几张凳子，只要她稍有移动，凳子就会倒下来。")
	await novel_interface.show_text_only("但直到居里夫人读完整本书，凳子依然立在那里。")
	await novel_interface.show_text_only("后来这个小姑娘凭借这样的品格，成为了第一位两次获得诺贝尔奖的科学家。")
	await novel_interface.show_text_only("然而你是否曾有过这样的念头——")
	await novel_interface.show_text_only("“人们对同一件事的感受，天生是一样的吗？”")
	await novel_interface.show_text_only("不停的吸收知识、每天只睡很短的时间……")
	await novel_interface.show_text_only("记忆大量的信息、长时间的集中注意力……")
	await novel_interface.show_text_only("很多人无法做到或难以坚持的事，是否可能对另一些人而言天生就觉得很轻松呢？")
	await novel_interface.show_text_only("或许那个波兰小姑娘看物理书的时候，与你全神贯注看漫画时的感觉是一样的。")
	await novel_interface.show_text_only("而所谓的“磨炼品格”，只是我们在徒劳的对抗着自己的基因表达。")
	await novel_interface.show_text_only("可能你从未如此思考过——")
	await novel_interface.show_text_only("但从此刻开始，这个念头就被植入到了你的脑中。")
	novel_interface.change_background("res://assets/images/bg/Soya/Marie_Curie2.png")
	await novel_interface.show_text_only("那么——")
	await novel_interface.show_text_only("下次你的意识中闪过这个念头时，脑内用的声音会是谁的呢？")
	
	# scene2
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("咔哒。")
	await novel_interface.show_text_only("枪械上膛的声音。")
	await novel_interface.show_text_only("伴随着NTBC新闻台的开场音乐，传来了女主持人熟悉的声音。")
	await novel_interface.show_dialog("「第四届国际和平论坛将于三天后在新丰洲协约非武装区内举行。」", "新闻")
	await novel_interface.show_dialog("「作为拥有最大科研系统的中立都市，新丰洲本周将迎来其他五大学园都市的交流团队——」", "新闻")
	await novel_interface.show_dialog("「本次和平论坛将会围绕异质物能源化开发规划及『重建计划』等重要议题进行讨论……」", "新闻")
	await novel_interface.show_dialog("「马萨达堡议长在近期的非正式演讲中表示，近期将公布一套全新的军事方案以重建西亚秩序。」", "新闻")
	await novel_interface.show_dialog("「萨蒙顿新闻部发言人对此表示不予评论……」", "新闻")
	novel_interface.show_background("res://assets/images/bg/Soya/Abduction_warehouse.png")
	await novel_interface.show_text_only("老式仓库内，昏暗的吊灯发出滋滋的电流声。")
	await novel_interface.show_text_only("仓库一侧，白色的灯光落在一位满头银发的男性身上。")
	await novel_interface.show_text_only("他被绑在一张坚固的座椅上，座椅的四脚与地面的钢板焊死，完全无法移动。")
	await novel_interface.show_character("lambert","frown")
	await novel_interface.show_text_only("男人刚被摘下头套，正适应着周遭的光线，劣质船舶钢丝将他的高档订制西装磨出失礼的毛边。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("注意到枪械的声音，他缓缓的抬起头。")
	await novel_interface.show_text_only("在他正对面架着一台摄像机，摄像机旁一个头戴黑色面罩的绑匪正用枪指着他。")
	await novel_interface.show_text_only("男人竭力的张望四周，仓库的远端还坐着一个手持突击步枪的守卫。")
	await novel_interface.show_text_only("他们蒙面黑色头巾的样式和迷彩服的搭配，俨然是那个臭名昭著的恐怖组织成员。")
	await novel_interface.show_text_only("银发的男子极力扭头，视野极限处隐约可以看到他的身后挂着一面黑色的旗帜……")
	await novel_interface.show_text_only("前方摄像机上面固定着一台手机，被开到最大音量播放着新闻。")
	await novel_interface.show_dialog("「『禁止异质物武器试验条约组织』执行秘书长伦伯特爵士今日接受媒体采访。」", "新闻")
	await novel_interface.show_dialog("「该机构是按照《全面禁止异质物武器试验条约》成立的防止异质物武器化的重要机制组织。」", "新闻")
	await novel_interface.show_dialog("「伦伯特爵士表示，目前已在全球建立了大量监测站点，负责监控全球范围内的异质物试验。」", "新闻")
	await novel_interface.show_dialog("「伦伯特认为，学园都市军事合作应成为邦交常态化的一部分……」", "新闻")
	await novel_interface.show_dialog("「他表示支持马萨达堡反击系统的研发和测试，称合理的威慑才是维持和平的基础。」", "新闻")
	await novel_interface.show_dialog("「并公开表示希望能有机会对话新丰洲科学院的莉琉·冯·布劳恩博士……」", "新闻")
	await novel_interface.show_text_only("听到这里，被绑在椅子上的男人轻轻勾起了嘴角。")
	await novel_interface.show_text_only("他一头银发向后梳拢得一丝不苟，水蓝色的瞳孔漠然的盯着另一侧墙壁上的几张照片。")
	novel_interface.change_background("res://assets/images/bg/Soya/Churun.png")
	await novel_interface.show_text_only("那张发黄的照片上，几个穿着防化服的工作人员正在处理着堆积如山的尸体。")
	await novel_interface.show_text_only("从照片的颗粒感可以判断，那应该是用老式机械相机和胶片拍摄的。")
	await novel_interface.show_text_only("他清晰的记得，当时为了防止有人拍摄，对周围数公里范围的区域进行了强电磁干扰。")
	await novel_interface.show_text_only("根据左下角的信息，那张照片拍摄于3年前，圭亚那高地，丘伦河畔……")
	novel_interface.change_background("res://assets/images/bg/Soya/Abduction_warehouse.png")
	await novel_interface.show_text_only("咔——")
	await novel_interface.show_text_only("黑衣人关掉手机，一脚踹在那男人的肚子上。")
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("呃——咳，咳咳咳……", "穿西装的男性")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("爵士大人，你也受不了自己在电视上那张虚伪的面孔了吗？", "绑匪")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("虚、虚伪吗？\n我可是……很真诚呢。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("黑衣人走近伦伯特并猛然将他的头发向后拽，迫使他的脸朝向屋顶的光源。")
	await novel_interface.show_text_only("他掏出一把弯刀，将刀尖对准伦伯特的眼球。")
	await novel_interface.show_dialog("那不知你这张脸值多少钱呢……", "绑匪")
	await novel_interface.show_text_only("强光如利刃般，迫使那对水蓝色的瞳孔急剧收缩。")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("所以说，你开价吧。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特余光瞄着对准自己眼球的大马士革钢材质刀刃。")
	novel_interface.show_character("lambert","serious")
	await novel_interface.show_dialog("你们能潜入新丰洲，掌握我的行程，并在两分钟内干掉我的保镖…", "伦伯特")
	await novel_interface.show_dialog("还有本事搞到那些照片……", "伦伯特")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("如此大费周章，总不会只为了录一段斩首视频吧？", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特从容的应答，让黑衣人有些意外。")
	await novel_interface.show_text_only("他放开了对伦伯特的钳制，并往后者脸上盖了一张清单。")
	await novel_interface.show_dialog("少废话，六十秒，决定是否成交！", "绑匪")
	await novel_interface.show_text_only("那张纸缓缓滑落到伦伯特的西裤上——内容是十二个不同的加密货币账号和具体金额。")
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("不错嘛，还能快速控制情绪……", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特看了看窗外接近黎明的天色。")
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_text_only("（将绑架对象囚禁十二小时后，开始目的明确的交易谈判。）")
	await novel_interface.show_text_only("（经过专业的训练？……）")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特低头眯起眼睛，瞟了一眼清单上的数字。")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("按照汇率换算，每个金额都能跟联合议会最近公开的恐怖分子保释金对应上……", "伦伯特")
	await novel_interface.show_dialog("你们不是『抵抗组织』的人吧？", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特的突然发问让绑匪猝不及防。")
	await novel_interface.show_dialog("？！", "绑匪")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("虽然在细节上下了不少功夫伪装成恐怖分子，但我猜是马萨达堡的摩诺拉——", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("少废话！！", "绑匪")
	await novel_interface.show_text_only("黑衣人气急败坏的转身走向伦伯特想先敲晕他。")
	await novel_interface.show_text_only("而后者突然提高嗓门用希伯来语大喊道——")
	novel_interface.show_character("lambert","surprise")
	await novel_interface.show_dialog("（希伯来语）有炸弹！！快卧倒！！", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("仓库远端的守卫先下意识的抬起手想保护头部，发现不对后才端起枪瞄准这边。")
	await novel_interface.show_text_only("黑衣人没想到伦伯特会做出这样的举动，看到同伴的反应后意识到身份已经暴露。")
	await novel_interface.show_text_only("男人的脸上露出挑衅的笑容。")
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("如果剧本是抵抗军的恐怖分子绑架我，并声称掌握联合议会进行非法异质物试验的证据的话……", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特又扫了一眼墙上的照片。")
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("我是目前唯一公开支持马萨达堡建造自动反击威慑系统的人，抵抗组织绑架我合情合理。", "伦伯特")
	await novel_interface.show_dialog("而且以我的身份，足够给他们抹黑，进一步坐实抵抗组织的“恐怖分子”丧心病狂的形象。", "伦伯特")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("同时以那几张照片要求联合议会用加密货币支付赎金，本是一石三鸟的计划。", "伦伯特")
	await novel_interface.show_dialog("由于加密货币的交易在公链上广播，那边一旦交钱就相当于公开承认确实进行过非法异质物试验。", "伦伯特")
	await novel_interface.show_dialog("日后马萨达堡可以以此要挟其他学园都市支持你们的自动反击系统，并尽量避免各方的制裁。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("精准到可怕的分析让黑衣人僵在那里，一时不知该如何处置。")
	await novel_interface.show_text_only("伦伯特此时虽被限制着行动，却已完全反客为主的控制住了局势。")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("特意用剪辑好的新闻做信息暗示，是为了掩盖你不太地道的口音。", "伦伯特")
	await novel_interface.show_dialog("但摄像机、我身后的黑旗，还有那把故意亮出来的大马士革弯刀都太画蛇添足了……", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("盯着神态窘迫的黑衣人，伦伯特故意顿了顿。")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("虽然有明显的受训痕迹，但你们都是被摩诺拉淘汰下来的吧？", "伦伯特")
	await novel_interface.show_dialog("听说被淘汰的学员，只要通过“意志审查”还可以被吸收为特殊编外人员。", "伦伯特")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("专门执行这种可能引起政治纠纷的行动，因为是随时都能抛弃的棋子……", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……", "绑匪")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("你们的任务目标应该明确说明过不许伤害到我，毕竟我是马萨达堡目前唯一的支持者…", "伦伯特")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("不过现在我可以给你和你的同伴一个机会——", "伦伯特")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("按照摩诺拉的常规作战部队配置，除了仓库里的你和那个守卫。", "伦伯特")
	await novel_interface.show_dialog("应该还有一名技术作战人员、一名重火力支援以及一名狙击手守在外面吧？", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特用看着猎物一样锐利的眼神刺向黑衣人，一字一句的说道。")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("只要跟我共享情报，我可以假装什么都不知道，继续陪你们演戏。", "伦伯特")
	await novel_interface.show_dialog("否则行动失败，你们就等着回去被组织处理掉吧～", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("当、当然是……合作，合作！", "绑匪")
	await novel_interface.show_text_only("黑衣人没有任何犹豫便做出判断，立刻转身取钳子想给伦伯特松绑。")
	await novel_interface.show_text_only("忽然“嗡”的一声，传出好似空气被划开的声音。")
	await novel_interface.show_text_only("黑衣人仿佛石化一般，登时定在原地。")
	novel_interface.show_character("lambert","surprise")
	await novel_interface.show_dialog("你怎么——？", "伦伯特")
	await novel_interface.hide_character()
	
	# scene3
	await novel_interface.hide_background()
	await novel_interface.show_text_only("伦伯特话音未落，仓库内的灯光忽然熄灭。")
	await novel_interface.show_text_only("外面传来几声巨响。")
	await novel_interface.show_text_only("轰——！\n碰——！！")
	novel_interface.show_background("res://assets/images/bg/Soya/Abduction_warehouse2.png")
	await novel_interface.show_text_only("一股强大的气流掀飞了这间老旧仓库的窗户，几束探照灯的强光同时射进来，让人睁不开眼。")
	await novel_interface.show_dialog("所有人不许动！！！", "防卫厅士兵")
	await novel_interface.show_text_only("暮色中，十几名都市防卫厅的特警荷枪实弹，瞬间制服仓库外围的守卫，从大门鱼贯而入。")
	await novel_interface.show_text_only("直升机螺旋桨的转动声遮住了所有警报。")
	await novel_interface.show_text_only("在营救组的帮助下，伦伯特摆脱束缚，活动着手脚站起身。")
	await novel_interface.show_text_only("一位特警拍了下刚才的黑衣人，只见那人的上半身应声从腰部断裂，一分为二的栽了下去。")
	await novel_interface.show_text_only("而他两条腿还完好的站在原地。")
	await novel_interface.show_text_only("周围的几个营救队员先是吓了一跳，然后对着这具奇怪的尸体面面相觑。")
	novel_interface.show_character("lambert","frown")
	await novel_interface.show_dialog("这种切口……", "伦伯特")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("——不对，照片！", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特扭头看向刚才贴着照片的墙面，早已空空如也。")
	await novel_interface.show_text_only("毫无光源的监控死角，一缕沾染着血迹的黑色长发渐渐融入夜色……")
	
	print("=== 天启篇第01话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
