# apocalypse_ep16.gd - 天启篇第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第16话剧本
	apocalypse_ep16_script()

func play_script():
	pass

# 天启篇第16话 - 正式剧本
func apocalypse_ep16_script():
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_text_only("朦胧的灯光下，索娅面颊微红，水珠从她褪去丝袜的纤细小腿缓缓滑落，浸湿了地面。")
	await novel_interface.show_text_only("她像一只毫无防备的小动物坐在喷泉的石台上，眼神迷离的看着我──")
	await novel_interface.show_text_only("我的心脏猛烈的抽动了几下，感到脸上一阵发烫。")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("索娅……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着这一幕，我刚听到她遭遇时那股热血上涌的冲动瞬间烟消云散，只觉得大脑一片空白。")
	await novel_interface.show_text_only("就像气势汹汹的冲到对方面前告白，结果在关键时刻卡壳的笨蛋──")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("（啊啊啊刚才的气势去哪了，快给我回来啊！！）", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","smile",0.25)
	await novel_interface.show_dialog("呐……", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索娅舔了舔嘴唇，露出一个淡淡的微笑。")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("soya_uniform","normal",0.25)
	await novel_interface.show_dialog("你现在的气息……很有趣呢~", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她顺着石台向我爬了过来，右侧脚踝上的放电脚环隐约反射着蜂窝形的反光纹路。")
	await novel_interface.show_text_only("那是战研部用异质物装甲材料制作的脚环，虽然只有薄薄一层，但坚固程度非比寻常。")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("果然……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅抓住我的手，鼻子凑到我的腹部深深的吸了一口，然后陶醉的说道──")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("小怜是最棒的啊！！", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("什、什么啊？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我连忙挣开后退了几步，奇怪才这么一会功夫她是怎么了。")
	await novel_interface.show_text_only("索娅懒洋洋的坐起来，在石台上理了理头发。")
	novel_interface.show_character("ren_fishnet","awkward")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","smile",0.25)
	await novel_interface.show_dialog("艾尔加纳告诉你了吧……", "索娅")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你的身体……到底怎么回事？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("本来不想让你知道的──", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索娅轻轻扭过头，说话的声音很小。")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("所有听说那个秘密的人，都变得很冷淡……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我想起了刚才艾尔加纳对索娅的态度。")
	await novel_interface.show_text_only("可能因为知道索娅活不久，便不敢再对她倾注感情了吧……")
	await novel_interface.show_text_only("也可能对教廷的人而言，无法进入圣所的她还有某种不祥的意味。")
	await novel_interface.show_text_only("那张拥有最高豁免权的『审判骑士』资格，或许亦是对她下达的“驱逐令”……")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("不过无所谓啦，我知道你不会像他们一样……", "索娅")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("对吗？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅看着我小心翼翼的问道，我的嘴唇微微颤动了一下，走上前去摸了摸她的头。")
	await novel_interface.show_text_only("索娅微笑着闭上眼，在我的掌心蹭了蹭。")
	await novel_interface.show_text_only("随后她张开双臂舒展了一下身体，望着夜幕下教堂顶部的壁画。")
	await novel_interface.show_dialog("我大概被那家伙讨厌了吧……","索娅")
	await novel_interface.show_dialog("虽然他也从没喜欢过我的样子。","索娅")
	await novel_interface.show_text_only("我刚想问“他”是谁，索娅就一脸坏笑的看向了我的裙子。")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("──话说，小怜也有很多秘密吧~", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我刚感到话头不妙，就被她一把抱住。")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("知道刚才为什么我没有趁机问莉琉吗？", "索娅")
	novel_interface.change_expression("laugh")
	await novel_interface.show_dialog("因为最有趣的谜题，当然要留给自己探索啦──", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("喂！！", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("那、那里……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("忽然我的手机响起来，是贝阿特丽切的来电，索娅还是不情愿松手。")
	await novel_interface.show_text_only("我一手接电话，一手糊在摸来摸去的索娅脸上。")
	await novel_interface.show_dialog("唔──呜呜──！","索娅")
	await novel_interface.show_dialog("小怜吗？我在医院。", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("贝阿特丽切！约翰他怎么样了？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅跳起来一把抢过我的手机，打开了免提。")
	await novel_interface.show_dialog("他正在输液，已经脱离危险……刚打了止疼药睡过去了。", "贝阿特丽切")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("……他能感到疼了？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是，据护士讲，他已经是今晚第四个短期失去痛觉的病例了──", "贝阿特丽切")
	await novel_interface.show_dialog("一个中年男人在电器街暴动时为了能看得更清楚，光着脚踩在灼热的汽车引擎盖上──", "贝阿特丽切")
	await novel_interface.show_dialog("周围人闻到了奇怪的味道才发现，只是不知为什么那家伙的头发也被烧焦了。", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("（不会是被伊露卡电过的那位吧……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("另一个是纽摩利达斯的女记者，她冲到游行队伍前面却按不动快门，才发现自己的手指骨折了。", "贝阿特丽切")
	await novel_interface.show_dialog("还有个华云宫城的维修工，作业时触电引发了内出血，却和同事在电话里兴奋的聊了半小时……", "贝阿特丽切")
	await novel_interface.show_dialog("直到他的一只眼睛因充血看不到才发现异常。", "贝阿特丽切")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切描述的状况让我有些背脊发凉。")
	await novel_interface.show_text_only("四个年龄、性别、国籍、工作毫无共性的人，居然表现出了相同的症状……")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("莉琉说今晚的暴乱或许跟异质物有关……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("确实可能。", "贝阿特丽切")
	await novel_interface.show_dialog("爱衣已经完成了保安军监控信息的接入，你的手机也有临时权限吧？", "贝阿特丽切")
	await novel_interface.show_dialog("我在记录中回溯这几个人的历史路径时，发现他们今天下午都曾去过七个暴动区域中的至少一个。", "贝阿特丽切")
	await novel_interface.show_dialog("而那个维修工，还是江森重工的安全巡查主管……", "贝阿特丽切")
	await novel_interface.show_dialog("我发现在今晚6点多，他曾与一个穿风衣的男人在电器街附近的路口交谈了5分钟。", "贝阿特丽切")
	await novel_interface.show_dialog("那人的行动路线有意避开了所有监控区域，却还是在一条小路转身时被拍到了脸──", "贝阿特丽切")
	await novel_interface.show_text_only("贝阿特丽切放慢了语速，一字一句的说道。")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("就是那次在天空酒店突袭我们的男人。", "贝阿特丽切")
	novel_interface.show_background("res://assets/images/bg/Soya/Monitor_Y.png")
	await novel_interface.show_text_only("同时我收到了她分享的监控画面。")
	await novel_interface.show_dialog("雅各？！","小怜")
	await novel_interface.show_text_only("雅各·施密特，第三学园都市马萨达堡派驻联合议会的武官。")
	await novel_interface.show_text_only("那个将伊露卡做为武器和工具使用的管理员──")
	await novel_interface.show_text_only("后来他在天空酒店率领一群人袭击我、贝阿特丽切\n、安妮和拉斐尔，还使用了异质物武器。")
	await novel_interface.show_text_only("安妮被他们的一种放电类武器打成重伤，还好当时拉斐尔在场……")
	await novel_interface.show_text_only("莉琉也查不到这个人的资料，只是猜测他隶属于第三学园都市的情报机构摩诺拉。")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("等等，江森重工……是巡查江森变电所吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我和安妮最初就是在江森变电所遇到伊露卡和雅各\n，要不是莉琉出手，我们那次不可能全身而退。")
	await novel_interface.show_dialog("我稍稍审问了一下那个维修工，但他只知道雅各是总公司认可的合作代表。", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("他们和雅各合作什么……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("因为联合议会在两周前才决定，要赶在和平论坛之前完成监控系统的全面升级──", "贝阿特丽切")
	await novel_interface.show_dialog("虽然摄像机已经到位，但市政照明是独立供电，绝大多数的街区都没时间完成线路扩容。", "贝阿特丽切")
	await novel_interface.show_dialog("所以只能用合作方的电池作为临时供电方案。", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("电池？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("拇指大小的透明容器，两头是电极，里面有发光的粘稠液体，据说能维持监控设备20天的运转。", "贝阿特丽切")
	await novel_interface.show_dialog("我已经让人把样本送到总部去检测了。", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("听起来像伊露卡一开始当做食物给我的东西……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("作为我给她巧克力的回礼，看起来完全不能吃嘛！")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("呐呐，你们说的雅各，是不是那个被你狠狠教训了一顿的家伙？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅像好奇宝宝一样迫不及待的问道。")
	await novel_interface.show_dialog("小怜啊……", "贝阿特丽切")
	await novel_interface.show_dialog("虽然你们俩关系很“亲密”，但你透露的情报是不是有点多了？", "贝阿特丽切")
	await novel_interface.show_text_only("谁和她很亲密了！！")
	await novel_interface.show_dialog("你不怕莉琉又罚你……", "贝阿特丽切")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("我才没──", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("呜……唔唔──！","小怜")
	await novel_interface.show_text_only("索娅一手高举手机，又一手糊在我的脸上。")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("哼哼！小怜全都告诉我了哦~！！", "索娅")
	await novel_interface.show_dialog("你真的是但丁笔下的那个大美人？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("听到电话那头打闹的声音，贝阿特丽切噗嗤一下笑了出来。")
	novel_interface.change_background("res://assets/images/bg/Soya/University_Hospital.png")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("连这种事都知道的话，想必你已经有莉琉的授权了吧。", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("所以呢所以呢？","索娅")
	await novel_interface.show_text_only("索娅摇着尾巴期待的追问。")
	novel_interface.show_character("beatrice_regular","smile3")
	await novel_interface.show_dialog("嗯，确实我就是你说那个贝阿特丽切，我的父亲是福尔科·波尔蒂娜。", "贝阿特丽切")#文字错误
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("但其实我只见过但丁一次，是在五朔节的家庭聚会上，当时我比伊露卡的年纪还小。", "贝阿特丽切")
	novel_interface.change_expression("grieved")
	await novel_interface.show_dialog("后来我才知道，他写《神曲》的时候，我已经喝下那杯毒酒十几年了──", "贝阿特丽切")
	await novel_interface.show_dialog("所以说，很多爱情只是一厢情愿……", "贝阿特丽切")
	novel_interface.change_expression("smile2")
	await novel_interface.show_dialog("不过呢，我很喜欢他的诗。", "贝阿特丽切")
	await novel_interface.show_dialog("敢用那样的作品揶揄教宗，还把我描写成在天堂之门等着他，并带他游历九重天的人。", "贝阿特丽切")
	novel_interface.change_expression("smile1")
	await novel_interface.show_dialog("可能那是他的理想，同时也是一种复仇吧。", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("复仇？","小怜")
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("那是我的秘密了哦──", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("贝阿特丽切抬头望着星星点的夜空。")
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("你们知道吗……", "贝阿特丽切")
	await novel_interface.show_dialog("围绕太阳系运转的其中一颗小行星，是后人因他的作品而以我的名字所命名。", "贝阿特丽切")
	await novel_interface.show_dialog("有机会的话，真想好好回应一下呢……", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("贝阿特丽切说还要联系一下莉琉就挂断了电话。")
	await novel_interface.show_text_only("索娅顺势坐在石台上玩起了我的手机，一点也没有要还给我的意思。")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("嘁~还给照片设置了加密文件夹，简直不打自招。", "索娅")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","stare",0.25)
	await novel_interface.show_dialog("总比被你乱翻好吧……", "小怜")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("先看看监控吧，用无人机偷窥真是个好主意──", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("快放弃你那危险的想法！")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("唔──", "索娅")
	await novel_interface.show_dialog("这里是……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我也凑了上去，手机上显示的是第一大道联合议会大厦前的无人机实时监控画面。")
	novel_interface.change_background("res://assets/images/bg/Soya/Cordon.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("保安军在大厦前面拉起了一道森严的警戒线。")
	await novel_interface.show_text_only("那一大排防爆盾牌的两侧，荷枪实弹的军队和躁动不安的示威人群之间似乎一触即发。")
	await novel_interface.show_text_only("人群中不时跳出几个挑头的去冲击盾墙，还有很多躲在远处的人群里朝保安军丢东西。")
	await novel_interface.show_text_only("在我们的注视下，一颗土制燃烧弹划着诡异的弧线被丢进了防线后面，立刻烧成一片。")
	await novel_interface.show_text_only("几名军警立刻提着灭火器把火扑灭，并把受伤的士兵拉到后方处理，好像已经有相当的处理经验了。")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("soya_uniform","wordless")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","upset",0.25)
	await novel_interface.show_dialog("好像……很不妙的样子啊。", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("要是刚才那个东西不小心丢进人群的话……")
	await novel_interface.show_text_only("索娅的注意力似乎并不在此，她又切换到其他几组无人机的画面，皱起了眉头。")
	await novel_interface.show_text_only("接着她聚精会神的对比着各组镜头，又将那些画面的位置在大地图上做比对──")
	await novel_interface.show_text_only("直到她在地图上将7个暴动区域拼成一个六芒星的顶点和中心点的形状。")
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_dialog("该不会是……", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("发现什么了吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("小怜，我得立刻去趟这里。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她指着手机地图上第一大道中段的位置，神情严肃的看着我。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("放心，我不会冲进人群里的，你只要在我200米以内安全的地方就可以。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("到底怎么──", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("啊，我先取个东西，你在这等我！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没等我说完，索娅就穿上鞋跑向了自己的房间。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	await novel_interface.show_text_only("回来时，索娅跨上了一个黑色的小包，里面装着的东西看起来很有分量。")
	await novel_interface.show_text_only("她不由分说拉起我的手钻进了在门口待命已久的黑色SUV。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("我们去第一大道。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("可那边不是在游行……", "司机")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("绕开人群就可以，我来指路！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("还没到午夜，路面却意外的畅行无阻，身材有些发福的司机不禁感叹起来。")
	await novel_interface.show_dialog("嘿，这条路平时在晚上也得堵上半天，今天还真好走，估计不想惹麻烦的都早早回家了吧。", "司机")
	await novel_interface.show_text_only("抱歉，我感觉我们正在去惹麻烦的路上！")
	novel_interface.show_background("res://assets/images/bg/Soya/Parade.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("我在车上试图联系莉琉和贝阿特丽切，但都无人接听。")
	await novel_interface.show_text_only("只用了十多分钟，我们就抵达了第一大道中段东侧的小路上。")
	await novel_interface.show_text_only("司机说他就在原地等，还提醒我们两个小姑娘夜里要注意安全。")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("哈、哈哈……", "小怜")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("（SID还有这种热心的大叔啊……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("街对面就是浩浩荡荡的游行队伍，那群人打着横幅喊着参差不齐的口号，一片嘈杂。")
	await novel_interface.show_text_only("南北走向的第一大道上，目力所及全都是人，队伍看起来在缓缓前行，但其实永远也无法到达终点。")
	novel_interface.show_character("ren_fishnet","speechless")
	await novel_interface.show_dialog("这帮人要是能走到议会大楼，前面的一万人得被顶进海里吧……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("你没发现这群人有什么异常吗？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("类似的抗议游行我在新丰洲也见过不少，但规模都远比不上眼前这只队伍。")
	await novel_interface.show_text_only("与警戒线那边剑拔弩张的氛围不同，处在中段的这帮人有些确实在声嘶力竭的呐喊──")
	await novel_interface.show_text_only("而另一些人则更像在参加节日庆典，在闪烁的广告屏幕下面，微笑的拿着咖啡和零食。")
	await novel_interface.show_text_only("自然还有很多人用手机各种摆姿势拍照，然后迅速加美颜滤镜分享到社交网络。")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("好像……也不是很紧张呢~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("而且附近几乎没有保安军的影子，他们也不想把宝贵的人力投入到这种地方吧。")
	novel_interface.show_character("ren_fishnet","stare")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	await novel_interface.show_dialog("本来大规模的游行就是这个样子的，只是他们的边界太过清晰了──", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索娅提醒后我才发现，几乎所有人都集中在人行横道的对面，我们所在的这一侧几乎没什么人。")
	novel_interface.show_character("ren_fishnet","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是『羊群效应』之类的……？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("融入集体才有安全感，就像抱团的企鹅一样自觉的形成了一条边界。")
	novel_interface.show_character("ren_fishnet","speechless")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	novel_interface.character_2nd_dark(0)
	await novel_interface.show_dialog("不过你到底是来做什么呀？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speechless")
	await novel_interface.show_dialog("嘛……先上楼──", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索娅拉着我钻进了路边的一栋写字楼，熟练敲晕了保安后用他脖子上的门卡坐电梯上到了顶楼。")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("这么多人──！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我被眼前的景象震撼了。")
	await novel_interface.show_text_only("从这个高度看下去，一个人只有蚂蚁大小，但即使是蚂蚁，也不会这么密集的聚在一起吧……")
	await novel_interface.show_text_only("索娅从包里拿出一个小型望远镜，在下面的人群中寻找着什么。")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("没有……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她依然不死心的拿来我的手机，反复切换着附近所有的路灯和无人机监控画面。")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("那边也没──", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("慢慢的，她心中的大石头好像终于落了地，坐下来长舒了一口气。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("只是巧合吗……", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("你到底来这边找什么啊？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("找一扇门……", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("门？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅默默的坐在天台上望着楼下的人海，没有理会我的追问。")
	await novel_interface.show_text_only("既然没什么紧急状况，我也不再坚持，便坐到她旁边，和她一起看着下面的芸芸众生。")
	await novel_interface.show_text_only("似乎在这样的视角下，什么事都能看的很开。")
	await novel_interface.show_dialog("这下面起码有数万人吧……"," 索娅")
	await novel_interface.show_dialog("可能吧……","小怜")
	await novel_interface.show_dialog("你看着他们，会觉得自己是那个种群中的一员吗？","索娅")
	await novel_interface.show_text_only("我没有说话，只是微微的摇了摇头。")
	await novel_interface.show_text_only("街道上密密麻麻的人群，好像共同构成了一个新的生命体，随着每个人的攒动缓慢的呼吸着。")
	await novel_interface.show_text_only("而我能明确的感觉到，自己不想成为其中之一。")
	await novel_interface.show_dialog("呐……","索娅")
	await novel_interface.show_dialog("嗯？","小怜")
	await novel_interface.show_dialog("小时候我在修道院看过一部纪录片。","索娅")
	await novel_interface.show_dialog("在南极，四处都是白茫茫的冰原，没有任何地标可以作为参考。","索娅")
	await novel_interface.show_dialog("帝企鹅只能靠本能辨别方位，每年为了繁衍后代都要完成两次大规模的迁徙。","索娅")
	await novel_interface.show_dialog("小企鹅出生后的第一次迁徙就要学会跟上队伍，一起向能找到食物的大海进发。","索娅")
	await novel_interface.show_dialog("最多时有二十万只帝企鹅在南极大陆的冰架上，排着整齐的队伍面朝同一个方向前进。","索娅")
	novel_interface.change_background("res://assets/images/bg/Soya/Penguin.png")
	await novel_interface.show_dialog("但每年都会有一些小企鹅，一生下来就固执的想要朝着相反的方向走。","索娅")
	await novel_interface.show_dialog("不管如何被成年的企鹅纠正方向，不管身边有没有同类，都会顶着暴风雪，义无反顾的向冰山前进。","索娅")
	await novel_interface.show_dialog("然而南极是一块孤立的大陆，那里严酷的环境不会给这种小家伙任何机会。","索娅")
	await novel_interface.show_dialog("但在遭遇数百万年一遇的环境剧变时，或许只有那些朝相反方向走的小企鹅能活下来。","索娅")
	await novel_interface.show_dialog("──它们是这个种群的保险机制。","索娅")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	await novel_interface.show_text_only("索娅一边回忆一边描述着那个纪录片里的情景，忽然沉默了许久。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("我从小就觉得，世界上一定有很多有趣的东西自己还没见过。", "索娅")
	await novel_interface.show_dialog("如果可能的话，我都想亲历一次。", "索娅")
	novel_interface.change_expression("wordless")
	await novel_interface.show_dialog("但好奇心总是有代价的──", "索娅")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("刚才贝阿特丽切描述的那种症状，和七个暴动区域的位置，都让我想起了三年前的那个任务……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我心中一惊，她之前见到过那样的症状？")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("当时南美一个地区发生了大规模异变，很可能引发XK级世界末日。", "索娅")
	await novel_interface.show_dialog("信理部派去的第一批黑衣修士全数阵亡，其他的前辈也都拒绝出动。", "索娅")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("只有我自告奋勇的独自去了，就像那只小企鹅……", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("到底发生什么了……", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/BlackGate.png")
	await novel_interface.show_dialog("当地一座小教堂的墙壁上，凭空出现一对纯黑的大门，半开的大门后面，只能看到刺眼的金光。","索娅")
	await novel_interface.show_dialog("大门周围三公里的区域，电子设备全部失效，所有进入那个区域的人则一概有去无回。","索娅")
	await novel_interface.show_dialog("这就是当时全部的情报。","索娅")
	await novel_interface.show_dialog("按照教宗的说法是──天堂的大门被提前打开了。","索娅")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("而我的任务，就是把那扇门关上。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我听着索娅的陈述，不由屏住了呼吸。")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("哼，天堂？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她无奈的摇了摇头。")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("我发现以那座教堂为中心的六个对称方向，呈散射状均匀分布着上万具扭曲的尸体。", "索娅")
	await novel_interface.show_dialog("那些人无论男女老幼，都是互相残杀而死，每个人的身上都有重伤后剧烈运动和扭打的痕迹。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("（听起来有点像女巫的行为？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("如果有地狱的话，应该就是那副景象吧……", "索娅")
	await novel_interface.show_dialog("我能活着走到那扇门前，可能因为当时区域里只有我一个人。", "索娅")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/BlackGate.png")
	await novel_interface.show_dialog("站在那扇门前，并不会觉得光线刺眼，反而有种温暖和放松的感觉，像是要把我吸进去一样。","索娅")
	await novel_interface.show_dialog("有个非常有存在感的精神体在不停的劝我将门完全打开或者走进门中。","索娅")
	await novel_interface.show_dialog("虽然没有言语的表达，但我却能完全理解。","索娅")
	await novel_interface.show_dialog("如果我走进那扇门，就能在欢愉和喜悦中与其中的金光融为一体。","索娅")
	await novel_interface.show_dialog("如果我完全打开大门，就能让所有人都成为那束光的一部分。","索娅")
	novel_interface.change_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("不巧的是，我对“融为一体”从来没什么兴趣。", "索娅")
	await novel_interface.show_dialog("于是在那个意志愤怒到抓狂的咒骂中，我慢慢关上了那扇大门……", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("哈──", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我和她对视了一眼，都忍不住笑了起来。")
	await novel_interface.show_text_only("下面是数万游行人群，我俩坐在一百多米高的天台上笑得前仰后合。")
	await novel_interface.show_dialog("唉──","索娅")
	await novel_interface.show_text_only("笑到眼泪都流出来的索娅调整了一下呼吸。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("大门完全关闭之后，那扇门就消失了，只剩下光秃秃的墙壁。", "索娅")
	await novel_interface.show_dialog("那次事件之后，教廷就获得了联合议会的支持。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("所以从连运营都难以维持的状态，忽然就有钱修那么大的教堂了啊。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("但要关上那扇门，就要接触到大门纯黑的那一面。", "索娅")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("那些黑色物质后来慢慢侵入了我的身体，那就是我要为此付出的代价吧……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅有些低落的垂下了头。")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("索娅。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我双手扶着她纤细的肩膀，认真的看着她的眼睛。")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("驱使小企鹅的是它自己的意志，而不是什么种群繁衍的保险机制。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("？", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("只是对山那边的景色怀着强烈的憧憬和好奇而已。", "小怜")
	await novel_interface.show_dialog("我们的祖先中的那一小部分人，就是靠这种意志从非洲走到了全世界。", "小怜")
	await novel_interface.show_dialog("在世界上最冷和最热的地方、在每年有半年是白天和半年是黑夜的地方，甚至在大海的另一头！", "小怜")
	await novel_interface.show_dialog("你才不是什么保险措施，你是──", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("我是……？", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("嗯。", "小怜")#文字错误
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","wordless",0.25)
	await novel_interface.show_dialog("嗯？", "索娅")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("内个……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("啊啊啊啊啊啊啊啊啊啊啊啊！！！")
	await novel_interface.show_text_only("刚才明明那么帅气，说到一半又卡壳了！！")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("soya_uniform","jest",0.25)
	await novel_interface.show_dialog("哦──？", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索娅用胳膊肘顶了顶我的肚子。")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("耍帅不要只耍一半啊~", "索娅")
	await novel_interface.hide_character()
	
	print("=== 天启篇第16话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
