# apocalypse_ep17.gd - 天启篇第17话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第17话剧本
	apocalypse_ep17_script()

func play_script():
	pass

# 天启篇第17话 - 正式剧本
func apocalypse_ep17_script():
	novel_interface.show_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_text_only("索娅一边笑着吐槽，身体一边慢慢倾向我，把头靠在我的肩膀上。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("……谢谢你，小怜。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("等回去让爱衣帮你检查一下吧……\n她很厉害的，总会有──", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅突然将左手食指放在我嘴前摇了摇头，见我没再继续说下去，她又将头靠了过来。")
	await novel_interface.show_text_only("我们就这么静静的看着楼下的流光溢彩，明明是繁华喧闹的集会，却能感到一种异样的宁静。")
	await novel_interface.show_text_only("到底该怎么形容她呢……")
	await novel_interface.show_text_only("先驱？开拓者？冒险家？")
	await novel_interface.show_text_only("那些词都曾在我的脑海中一闪而过，但每次话到嘴边又觉得不对──")
	await novel_interface.show_text_only("无论索娅还是那些人类的祖先，在离开熟悉的家园去探索未知区域时，都要面对巨大的恐惧吧。")
	await novel_interface.show_text_only("在那种明明怕的要死、却又充满期待和兴奋的心情中…")
	await novel_interface.show_text_only("一边谨慎观察周围环境，一边小心择路斩荆前行…")
	await novel_interface.show_text_only("那时谁还有空管什么“对种群和历史的意义”啊。")
	await novel_interface.show_text_only("游行队伍里那些变换各种姿势拍照的家伙们，才是在拼命证明着自己的意义吧？")
	await novel_interface.show_text_only("每个人都想方设法彰显自己的与众不同，却不自觉的构成了下面这只庞然大物……")
	await novel_interface.show_text_only("在来这里的车上，广播报道一个记者在现场采访示威人群。")
	await novel_interface.show_text_only("随机受访的23个人里，只有一人能在世界地图上\n指出马萨达堡的大致位置。")
	await novel_interface.show_text_only("有一半人甚至说不出他们参加的游行在反对什么。")
	await novel_interface.show_text_only("……意义真的那么重要吗？")
	await novel_interface.show_text_only("忽然，手机的来电震动声将我的思绪拉回，我接听时自觉的打开了免提。")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("莉琉吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("两个小家伙真不乖呀──", "爱衣")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("爱衣？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("话说你俩怎么跑到第一大道去了！\n还在那么高的位置，去看人海吗！？", "爱衣")
	await novel_interface.show_text_only("爱衣的语气罕见的有些担心，我发现一台无人机正悬停在斜前方的半空中，幽怨的看着我们。")
	await novel_interface.show_dialog("莉琉不知道去哪了，我是来告诉你们刚才贝阿特丽切送来电池的分析结果……", "爱衣")
	await novel_interface.show_dialog("总之先说要紧的──", "爱衣")
	await novel_interface.show_dialog("可以确定，那个电池与异质物有关，而且是马萨达堡的军工企业制造的。", "爱衣")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("果然……是异质物武器？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("至少那种发光的粘稠液体在生产过程中有异质物的参与……目前还无法解析出它的成分。", "爱衣")
	await novel_interface.show_dialog("基本上可以把那东西当做一种燃料电池，封装在电池外壳内的液体会随着放电被消耗。", "爱衣")
	await novel_interface.show_dialog("不知为什么，可能因为他们急着出货，连MMI的\n出厂编码都没磨掉就重新喷装了", "爱衣")
	await novel_interface.show_dialog("就连限压器也是外置在电池盒上的……", "爱衣")
	await novel_interface.show_text_only("爱衣的语气中带着一些困惑。")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("电池盒……限压器？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("啊，你们没见过那东西的样子吧？", "爱衣")
	await novel_interface.show_dialog("7.2厘米高的金属圆柱体，除了两头的正负级，周身覆盖着绝缘层，就像一节放大的AA电池──", "爱衣")
	await novel_interface.show_dialog("电池侧面有个机械结构的挡板，推开下面是两个金属触点。", "爱衣")
	await novel_interface.show_dialog("只要在触点上施加一个很低的电压，就能控制电池正负极的放电强度。", "爱衣")
	await novel_interface.show_dialog("外置电池盒上有个40微伏的限压器，那个结构正\n好可以推开挡板并限制触点的输入电压。", "爱衣")
	novel_interface.show_character("ren_fishnet","speechless")
	await novel_interface.show_dialog("为什么听起来像是用电池驱动的电池……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("给光能手电筒用做备用电源吗？！")
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_dialog("因为它们最初并不是作为电池被制造出来的──", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅的表情严肃起来。")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("简直就像是……武器的机械保险和点火装置。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("我测算了一下电池的能量──", "爱衣")
	await novel_interface.show_dialog("确实如电力公司的情报描述：一节电池可以让功率为6瓦的微型监控设备运转20天左右。", "爱衣")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("似乎……没什么大不了的？", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（功率是什么乘什么来着？？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣对我无可救药的物理默哀了一秒。")
	await novel_interface.show_dialog("2.88千瓦时，足够你的手机用半年了……", "爱衣")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("这么厉害！！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("因为我最近越来越习惯用伊露卡给手机和掌上游戏机充电，总被安妮念叨……")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("等等，如果去掉限压器会怎样？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("我打电话就是为了提醒你们……", "爱衣")
	await novel_interface.show_dialog("我发现输入在1到500微伏范围内，输出也会成正比放大，但超过500微伏后就没有输出了。", "爱衣")
	await novel_interface.show_dialog("然后我一路升高电压到32伏时，电池突然放出一\n道强烈的白光……", "爱衣")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("──！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("高速摄像机显示，电池里的液体在不到1毫秒的时间里瞬间耗尽──", "爱衣")
	await novel_interface.show_dialog("剧烈的放电把隔离室的天花板都烤糊了，墙面和地板都布满了树状分布的焦痕。", "爱衣")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("什么？？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我忽然想到，之前在天空酒店被雅各突袭，他手下使用的放电武器……")
	await novel_interface.show_text_only("一道强光之后，房间内也是遍布着那种树状灼痕。")
	await novel_interface.show_dialog("上次打在安妮身上的能量要比这个小得多，而且武器上有指向性装置，不然房间里谁都逃不了。", "爱衣")
	await novel_interface.show_dialog("而32伏，是马萨达国防军电子脉冲点火武器通用\n的下限激发电压。", "爱衣")
	await novel_interface.show_text_only("接着，爱衣停顿了片刻──")
	await novel_interface.show_dialog("2.88千瓦时的能量，相当于2.5公斤的TNT炸药…", "爱衣")
	await novel_interface.show_dialog("虽然电池不像炸药能产生破坏力强劲的冲击波，但也足以对半径10米内的人员造成致命伤害。", "爱衣")
	await novel_interface.show_dialog("而现在协约非武装区的每个路灯上，都装着那种东西……", "爱衣")
	await novel_interface.show_text_only("我看着楼下密密麻麻人群，不禁倒抽了一口凉气。")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("可恶！雅各那家伙……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform","speechless",0.25)
	await novel_interface.show_dialog("等一下──", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索娅忽然打断我们。")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("按刚才爱衣的说法，马萨达应该是最不希望那些电池爆炸的吧？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("确实如此。", "爱衣")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("仓促的没有磨掉编码就喷涂，用现有的武器库存临时套上一个限压器……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("听起来更像是为了应付联合议会突如其来的大规模订单？", "爱衣")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("万一爆炸的话，每颗炸弹上都刻着自家的出场编号\n…岂不太蠢了。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("而且这种大规模市政改造工程，有无数人要参与物流、安装和维护工作……情报控制太困难了。", "爱衣")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("好像……确实是这么回事？", "小怜")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("要说现在最奇怪的，还是贝阿特丽切报告的那几个病例吧？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("莉琉让疾控中心发布了4级感染警告，目前全市20多个病例全都集中在协约非武装区内。", "爱衣")
	await novel_interface.show_dialog("但这种电池确实不会产生精神类的效果，模因检测的色相也全都正常……", "爱衣")
	await novel_interface.show_text_only("我们沉默不语，一切似乎又回到了原点。")
	await novel_interface.show_text_only("我出神的盯着楼下，密不透风的人群中，每隔十几米就有一盏路灯……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("刚在下面，索娅和我讨论的那个问题是什么来着？")
	novel_interface.show_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.show_character("ren_fishnet","normal2")
	await novel_interface.show_dialog("游行队伍的边界是不是太清晰了──", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("嗯？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("什么意思……", "爱衣")
	await novel_interface.show_text_only("会不会答案一直都在我们眼前，但因为街道上存有太多干扰，才一直被忽略了──")
	novel_interface.show_character("ren_fishnet","normal1")
	await novel_interface.show_dialog("我记得莉琉说过，这次联合议会的市政改造统一更换了市电路灯的照明和监控系统吧？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("没错。", "爱衣")
	await novel_interface.show_dialog("──那为什么，会有明显两种颜色的路灯？", "小怜")
	await novel_interface.show_text_only("第一大道上，发着暖黄色光的路灯为游行的人群勾勒出了清晰的边界。")
	await novel_interface.show_text_only("而旁边几乎没人的分支道路上，路灯却是白色的自然光。")
	await novel_interface.show_text_only("电话那边传来一阵急促的敲击键盘声。")
	await novel_interface.show_dialog("我查了一下，这次统一更换的是4500K色温的长\n效LED灯芯，应该是偏白色的自然光。", "爱衣")
	await novel_interface.show_text_only("我和索娅四目相对，努力回想着今晚的经历。")
	novel_interface.change_background("res://assets/images/bg/Soya/Cordon.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("刚才从监控中看到联合议会大厦门口的警戒线，确实有大面积的黄色光源。")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("电器街的路灯，好像也是暖黄色的……", "索娅")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	await novel_interface.show_text_only("发生骚乱的电器街密布着炫目的霓虹招牌和广告灯箱，暖黄色的路灯完全能自然的融入。")
	await novel_interface.show_dialog("今天电器街的气氛，确实兴奋得有些不正常……", "小怜")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("相反的，路灯颜色发白的街道，似乎都没什么人。", "小怜")
	novel_interface.show_background("res://assets/images/bg/Soya/Police_Station.png")
	await novel_interface.show_dialog("咱们逃出来的那个警局外面！", "索娅")
	await novel_interface.show_dialog("还有……", "小怜")
	novel_interface.change_background("res://assets/images/bg/Soya/Night_Park_Out.png")
	await novel_interface.show_text_only("新井中央公园门外，那条冷清的小路──")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("难道说……", "索娅")
	novel_interface.show_background("res://assets/images/bg/Soya/First_Avenue.png")
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_dialog("门的后面──", "索娅")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","upset",0.25)
	await novel_interface.show_dialog("嗯？", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那刺眼的金光……", "索娅")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"solemn")
	await novel_interface.show_dialog("该不会是──", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("索娅二话不说，拉起我的手就向电梯跑去。")
	print("=== 天启篇第17话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
