# apocalypse_ep08.gd - 天启篇第08话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第08话剧本
	apocalypse_ep08_script()

func play_script():
	pass

# 天启篇第08话 - 正式剧本
func apocalypse_ep08_script():
	# scene1 - 街上对话
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("所以呢……所以啊！ \n你说的那种『知识』要怎么才能得到呢？", "索娅")
	await novel_interface.show_dialog("小怜的身上就没有那种味道，但你一定是某种很特殊的存在吧？！", "索娅")
	await novel_interface.show_dialog("你的味道实在……太纯净了！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅用鼻子凑近我的胸前深深吸了一口，然后一脸陶醉的看向我。")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_text_only("那充满期待的眼神就像叼紧飞盘扒着主人拼命摇尾巴的小狗——")
	await novel_interface.show_text_only("满脸都是“陪人家玩嘛~”的表情。")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我……是很特殊的存在吗？")
	await novel_interface.show_text_only("似乎爱衣之前说过——")
	novel_interface.show_background("res://assets/images/bg/Fabiola/AI.png")
	await novel_interface.show_dialog("小怜能以超常的效率激活魔女的魔法……", "爱衣")
	await novel_interface.show_dialog("就像是超级电池塞进了有震动电机的硅胶棒一样！", "爱衣")
	await novel_interface.hide_background()
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("（不，我不承认这个比喻！！）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("就算你问我……", "小怜")
	await novel_interface.show_dialog("我只知道，记录着那种信息的是一种被称作『魔导书』的载体。", "小怜")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("对了！你和女巫战斗的时候应该见过吧？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("魔导书？是书本之类的吗……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅似乎忽然想到了什么，一幅恍然大悟的样子。")
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_dialog("之前消灭女巫的时候，确实经常会见到书页一样的东西……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅一边回想一边说道——")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("但修道院的嬤嬤说那些东西的感染性太强，圣赦院的人会在事后清理时统一收集焚烧。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("（被当成生物污染品之类的吗？）","小怜")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("（好像也没什么不对……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("“咔——!!”")
	await novel_interface.show_text_only("突然，街对面忽然一声炸裂，就像高压电击穿空气的声音，随后便是一阵喧闹。")
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("怎么回事？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅的表情认真起来，那片人群聚集处显然传来了不妙的味道。")
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("等等……伊露卡去哪了？？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("刚被分散了注意力，我才发现一直跟在身旁的伊露卡不见了！")
	await novel_interface.show_text_only("我的大脑嗡的一下一片空白，带孩子逛街转眼就不见了原来是这种感觉吗？")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("不、不会被拐走了吧――", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡那孩子……")
	await novel_interface.show_text_only("稍有不慎的话……")
	await novel_interface.show_text_only("可是随便就能放出上百万伏的高压电啊！！")
	await novel_interface.show_text_only("索娅二话不说，径直向骚动的人群冲去，我也紧随其后。")
	await novel_interface.show_text_only("附近巡逻的警员已经吹着警哨先我们一步奔向事发地点，并试图疏散附近的人。")
	await novel_interface.show_dialog("让一让！大家散开――！！", "保安警A")
	await novel_interface.show_dialog("喂！你！别过来了！", "保安警B")
	await novel_interface.show_text_only("两名警员看到冲过来的索娅，试图阻止她前进。")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("不、不好意思，我们的朋友走丢……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没等我说完，只见索娅用右手虎口对着其中一名在喊话的警员喉咙位置打了一下。")
	await novel_interface.show_text_only("那名身材魁梧的警员突然失声，像被人掐住了脖子一般跪倒在地。")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("欸？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("另一名警员没料到这种情况，眨眼的功夫已被索娅绕到身后击中了脖颈。")
	await novel_interface.show_text_only("银发少女的动作干净流畅，就像事先排演过无数次一般。")
	await novel_interface.show_text_only("不到三秒的时间里，一名警员倒地，另一个跪在地上拼命倒着气，索娅则迅速消失在人群中。")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("………………", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我小心地绕过那个昏迷的警员，心怀歉疚拍了拍喉部痉挛跪在一旁拼命呼吸的那个人。")
	await novel_interface.show_text_only("谁知那大汉只被我拍了一下，上半身就支撑不住倒在地上，发出一声闷响。")
	await novel_interface.show_text_only("周围的行人警觉的看向我，带着小孩的女性也拉着孩子快步离开。")
	await novel_interface.show_text_only("还有一个穿着电力公司制服的维修工边后退边掏出手机来录相。")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("不、不是我！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然而怎么看都是我！")
	await novel_interface.show_text_only("我硬着头皮逃离了现场，挤进前方被围得里三层外三层的人群中——那就是刚才发出响声的地方。")
	await novel_interface.show_text_only("散布着树枝状灼痕的地面上，四脚朝天躺着一个大叔，头发被烧焦，似乎已没了气息。")
	await novel_interface.show_text_only("他穿着一件几年前动画片的主题T恤，奶黄色布料上三个小萝莉的图案被烤糊了大半。")
	await novel_interface.show_text_only("从地上的工口抱枕和他紧握着的手机壳图样判断—")
	await novel_interface.show_text_only("毫无疑问，这个萝莉控被电劈了。")
	await novel_interface.show_text_only("此时索娅正蹲在他身旁，左手扶在那人胸前，右手攥拳高高举起……")
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("索娅！你刚才―――", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我话还没出口，索娅就猛然落拳，重砸在自己左手手背上，力道经过缓冲传入那人的胸腔。")
	await novel_interface.show_text_only("沉静几秒后，那个大叔忽然哆嗦了一下，咳出两口黑烟，引得围观众人的一阵惊叹。")
	await novel_interface.show_text_only("接着索娅把他的头拉过来，扇了两巴掌。")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("喂喂，醒醒――", "索娅")
	await novel_interface.show_dialog("你刚才有没有看到一个蓝色头发的小姑娘……就是跟你那抱枕上的样子有点像的。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那人看了看地上的抱枕，发出一声诡异的哀嚎后连滚带爬的跑开了，裤子裤裆的部位湿了一大片。")#文本错误
	novel_interface.show_character("ren_fishnet","speechless")
	await novel_interface.show_dialog("（这是受到了心理创伤？……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅扭头生气的看着我。")
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("伊露卡的能力原来这么恐怖吗？\n你们叫她跟我一起来是想干嘛！", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("你还说！刚那两个警察……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("嘁，他们死不了～", "索娅")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("不把那两个撂倒的话，万一他们把你拦住，我们又会超过距离……", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","sprite")
	await novel_interface.show_dialog("所以你就袭警吗？被电到也活该！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我刚想教训索娅，忽然觉得后背被什么东西扎了两下。")
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("呃？", "小怜")#文本错误
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","yell")
	await novel_interface.show_dialog("你后面！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("随着泰瑟X46电击枪的放电，猛烈的灼烧感让我全身肌肉一阵痉挛。")
	await novel_interface.show_text_only("紧接着我只觉眼前一黑――")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("不知过了多久，我似乎听到晚间新闻的插曲。")
	
	# scene2 - 拘留室
	novel_interface.show_background("res://assets/images/bg/Soya/Police_Cells.png")
	novel_interface.change_music("res://assets/audio/music/Brooklyn.mp3")
	await novel_interface.show_dialog("新丰洲电车炸弹客又发新预告，之前几枚炸弹已被排除，现场进一步清理中。", "新闻")
	await novel_interface.show_dialog("燃气集团发言人表示正在紧急排查市区的输气管道泄露点，请市民出行避开相关区域。", "新闻")
	await novel_interface.show_dialog("联合议会总部所在的第一大道已经聚集了超过一万名抗议者……", "新闻")
	await novel_interface.show_dialog("国际和平论坛的封闭会议仍在进行中，有抗议者要求各国领导人立刻终止会议出面表态……", "新闻")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("嘛，你醒了？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我迷迷糊糊的睁开眼，擦了擦口水，发现这间屋子里已经坐满了人。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("我们……是在哪……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("警局的临时拘留室，就在电器街附近。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("哦……啊？！", "小怜")
	await novel_interface.show_dialog("警局？拘留！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一下清醒过来，观察着周围的环境――")
	await novel_interface.show_text_only("临时拘留室两面是墙，一面是受理台，一面是合金栅栏，里面的人并没被手铐之类的束具限制行动。")
	await novel_interface.show_text_only("房间里已坐满了人，一侧墙边坐着几个满身酒气的肌肉男，每个人身上都有几处伤痕。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("（是酒后打架吗?脸上还在流血啊……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("对面受理台的墙角蹲着几个小混混，一直在上下打量着我和我旁边三个打扮得花枝招展的姐姐。")
	await novel_interface.show_text_only("新丰洲的某些职业在国际领土是违法的，不过据说使馆区总有阔佬想跨境交易……")
	await novel_interface.show_text_only("等等！那几个姐姐和我一样都穿着渔网袜，我们四人的大腿齐刷刷一排――")
	novel_interface.show_character("ren_fishnet","shy_left")
	await novel_interface.show_dialog("（我，我不是啊！！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然最近经历了不少事，但被抓进警察局还是第一次，不禁忐忑起来――")
	await novel_interface.show_text_only("我想象着自己被关进监狱的场景，万一遇到把裤兜翻到外面的变态或者“笑容可掬”的肌肉叔叔……")
	await novel_interface.show_text_only("我打了个冷战。")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("（啊不对，应该是……女子监狱？）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("――完、完全无法想象！！")
	await novel_interface.show_text_only("但到现在我还没收到莉琉的指令，也就是说任务目标并没有变……")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("对了，伊露卡呢！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅摊了摊手。")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("虽然这些警察今天好像特别忙，但还没听说又有人被电到。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("现在刚开始晚间新闻……已经过去一个多小时了？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("我也才醒过来，新型电击枪的电针上似乎有精神类药物。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅把头凑到我耳边，小声说道。")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("你恢复好了么？咱们该出去了~", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("怎、怎么出去？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅拧下自己披风上的一枚纽扣——露出一根不到两厘米的短针。")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("说到精神类药物……", "索娅")
	await novel_interface.hide_character()

	print("=== 天启篇第08话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
