# apocalypse_ep15.gd - 天启篇第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第15话剧本
	apocalypse_ep15_script()

func play_script():
	pass

# 天启篇第15话 - 正式剧本
func apocalypse_ep15_script():
	# 开场设置
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N_Door.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("嬷嬷──", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅看到艾尔加纳突然就老实了，迅速将扒着我衣服的双手抽了回去。")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("安赫莱斯，刚才有个包裹，已经送到西院你的房间了。", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("好~~~~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳的话语透着威严，索娅回复时却故意拉长了声调──")
	await novel_interface.show_text_only("就像故意在班主任面前卖乖的小学生。")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("……嬷嬷？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("啊…小怜不习惯这种称呼吧？\n叫我艾尔加纳就可以。", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("您、您好……艾尔加纳。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我想起曾看过一部欧洲老电影，修道院的嬷嬷大概是老师兼宿管阿姨之类的角色吧。")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("听说你的腰拉伤了？", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("嗯，一不小心……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一不小心被一百公斤的孩子砸到了。")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("快进来看看吧，我已经把药准备好了。", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳露出慈祥的笑容，和刚才对索娅说话时的感觉完全不同。")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("（索娅这家伙，大概从小没少惹麻烦……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳推开了教堂厚重的大门，我也紧跟其后。")
	novel_interface.show_character("ren_fishnet","happy")
	await novel_interface.show_dialog("这上面的雕刻都好精致啊──", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我走近些才看清，大门左右各镶嵌着五块方形金属浮雕，每块似乎都代表一个故事。")
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("这是吉贝尔蒂浮雕的复制品，虽然原作在战争中被毁了……", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳的脸上略过一丝哀伤，那应该是她很喜欢的艺术家吧？")
	novel_interface.change_background("res://assets/images/bg/Soya/Solomon.png")
	await novel_interface.show_text_only("虽然并不知道吉贝尔蒂是哪位，但并不影响我盯着其中一块看得出神。")
	await novel_interface.show_dialog("这块讲的是示巴女王和所罗门王的传说。", "艾尔加纳")
	await novel_interface.show_dialog("上代教宗大人要求所有的新建教堂都添加一些历史艺术品的元素──", "艾尔加纳")
	await novel_interface.show_dialog("或许是想提醒大家，不要让战争抹杀我们曾经如此辉煌的文明吧……", "艾尔加纳")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_N_Door.png")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("似乎是个很不错的人呢……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("按照莉琉的说法，上代教宗大人应该就是给索娅授予『审判骑士』资格的那位。")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("啊，索娅你不来吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅并没跟上来，只是乖巧的目送我们进门。")
	novel_interface.show_character("soya_uniform","worry")
	await novel_interface.show_dialog("我不进去……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她就站在原地，柔和的暖光打在她的脸上，竟宛如我初次见她时那样沉静温和。")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("总之你好好治伤，应该要不了多久的──\n我先去后院看看~！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("说罢索娅就一溜烟的跑向了教堂西侧的走廊。")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("（其实是急着回去拆包裹吧……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("暂且无视索娅有些异样的举动，我跟着艾尔加纳走进了教堂。")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_L.png")
	novel_interface.show_character("ren_fishnet","happy")
	await novel_interface.show_dialog("好大──！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("两侧雄伟的石柱和气势恢弘的穹顶，让生平第一次亲身进入教堂的我不禁连连惊叹。")
	await novel_interface.show_text_only("布满宗教壁画的屋顶和远处的彩绘玻璃在灯光的映照下显得圣洁而宁静。")
	await novel_interface.show_text_only("教堂后排座位上放着一个胡桃木质地的药箱，应该是特意准备的吧。")
	novel_interface.show_character("ren_fishnet","happy")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("el","smile",0.25)
	await novel_interface.show_dialog("来，快让我看看~", "艾尔加纳")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("然而我突然意识到一个问题──")
	novel_interface.show_character("ren_fishnet","shy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("el","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（这身连衣裙要想露出后腰的话……）", "小怜")
	await novel_interface.show_dialog("（只能从后面连着裙子整个掀起来啊！！）", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("其、其实也没什么大不了的~", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("腰伤可不能掉以轻心，处理不好会落下病根的。", "艾尔加纳")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("唔……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("乖，要听话──！", "艾尔加纳")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("艾尔加纳表现出了长辈似的不满和担忧，不由分说的把我按在了铺着软垫的长凳上。")
	await novel_interface.show_text_only("我小心翼翼的趴下，这才发现腰部在上半身刚刚抬起但胳膊还没找到支撑点的时候特别疼。")
	await novel_interface.show_text_only("她将我的裙子掀开，我还想用手遮住渔网袜下面的内裤。")
	await novel_interface.show_dialog("不用不好意思，这个兔子的图案很可爱呢~", "艾尔加纳")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("啊啊啊啊那只是游戏周边！周边！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("太失策了──我居然忘了今天穿的是某个射击游戏里会驾驶机械装甲自爆的角色主题内裤。")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("（而且屁股凉飕飕的……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("别乱动……嗯，是这里吧？", "艾尔加纳")
	await novel_interface.show_text_only("艾尔加纳一下就按到了我受伤的部位，剧烈的疼痛瞬间抹杀了全部羞耻感。")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("疼疼疼──！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她从药箱中取出药罐，将散发着浓烈草药气味的糊状软膏均匀的抹在我的后背上，并轻轻的按摩。")
	await novel_interface.show_text_only("一股凉凉的酥麻感从后腰处传来。")
	await novel_interface.show_dialog("很快就好了，不要乱动哦──", "艾尔加纳")
	await novel_interface.show_text_only("我像小猫一样乖乖趴好，一动也不敢动。")
	novel_interface.show_character("ren_fishnet","worry")
	await novel_interface.show_dialog("听索娅说，这是您自己配制的？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是我故乡的药草，配方是小时候母亲教我的。", "艾尔加纳")
	await novel_interface.show_dialog("怎么样，觉得好点吗？", "艾尔加纳")
	await novel_interface.show_text_only("她的声音轻柔温婉，像一首催眠曲。")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("嗯……", "小怜")
	await novel_interface.show_dialog("这里只有您一个人打理吗？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("el","smile",0.25)
	await novel_interface.show_dialog("本来应该有神父来管理，但这几年神职人员严重不足，就先把我调了过来。", "艾尔加纳")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("不过没关系──", "艾尔加纳")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("前几年最困难的时候，我要四处走访做布道筹款才能勉强维持修道院的运营……现在条件好太多了。", "艾尔加纳")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("艾尔加纳的声音沉稳，好像面对什么恶劣的状况都能淡然处之，给人一种安心感。")
	novel_interface.show_character("ren_fishnet","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark(0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("el","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("索娅小时候在您的修道院吧……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("听到索娅的名字，她轻叹了一声──")
	novel_interface.show_character("ren_fishnet","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark()
	novel_interface.show_2nd_character("el","normal",0.25)
	novel_interface.character_2nd_dark(0)
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("那孩子刚从波多西送来的时候还不到三岁，一个家人都没有了……", "艾尔加纳")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("不过她很聪明，对什么都充满好奇，修道院所有孩子里也属她最淘气。", "艾尔加纳")
	await novel_interface.show_dialog("上课的时候总提各种奇怪的问题为难修女，弄得我还要一个个去安抚老师，真是……", "艾尔加纳")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("艾尔加纳回忆的声音中带着笑意和慈母般的怜爱。")
	novel_interface.show_character("ren_fishnet","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark(0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("el","smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("但她好像有点怕您呢……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("艾尔加纳沉默了片刻，对我问道。")
	novel_interface.show_character("ren_fishnet","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark()
	novel_interface.show_2nd_character("el","normal",0.25)
	novel_interface.character_2nd_dark(0)
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("小怜，你觉得人跟人对同样体验的感受，会是一样的吗？", "艾尔加纳")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("应该……不是吧？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("那孩子的好奇心就特别强，遇到她觉得有趣的东西就会不顾一切的刨根问底……", "艾尔加纳")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我趴在长凳上默默点头，表示深有同感。")
	novel_interface.show_character("el","smile")
	await novel_interface.show_dialog("可能因为她看到的世界，和普通人不一样吧……", "艾尔加纳")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("局势动荡的时候，就算是小孩子也明白要自保，而她却一直敞开双臂迎接未知的事物。", "艾尔加纳")
	await novel_interface.show_dialog("因为这样的性格，她作为最突出的学生，很早就被信理部发现并加以培养──", "艾尔加纳")
	await novel_interface.show_dialog("但也因为好奇心，她会尝试很多危险的事，完全不在乎自己是否会受伤……", "艾尔加纳")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳的语气让我产生了一丝不妙的预感。")
	novel_interface.show_character("ren_fishnet","normal1")
	await novel_interface.show_dialog("她……发生什么了？", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("el","sad")
	await novel_interface.show_dialog("几年前，有个非常危险、但十分重要的任务。", "艾尔加纳")
	await novel_interface.show_dialog("我不知道具体的内容，但当时没有一个黑衣修士愿意接手，她却自告奋勇……", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","normal1")
	await novel_interface.show_dialog("（难道是莉琉说的那件事──）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("艾尔加纳的声音有些颤抖。")
	novel_interface.show_character("el","sad")
	await novel_interface.show_dialog("后来任务完成了，可代价是她的身体被一种不知名的异质物侵入了──", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","serious")
	await novel_interface.show_dialog("什么！？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("el","normal")
	await novel_interface.show_dialog("她没告诉你吗……", "艾尔加纳")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Toxin.png")
	await novel_interface.show_dialog("那是一种无法测定化学成分的黑色物质，像癌症一样正在一点点夺去她的身体。", "艾尔加纳")
	await novel_interface.show_dialog("之所以上代教宗那么早就授予她真理之印，是因为所有的医生都判断她活不到成年。", "艾尔加纳")
	await novel_interface.show_dialog("与其说是异质物，更像是一种『恶意』──", "艾尔加纳")
	await novel_interface.show_dialog("因为那东西还有另外一个效果：只要她暴露在教堂或修道院之类的圣所中，就会立刻浑身剧痛。", "艾尔加纳")
	await novel_interface.show_dialog("……她成为了“被神厌弃的孩子”。", "艾尔加纳")
	novel_interface.change_background("res://assets/images/bg/Soya/Church_L.png")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("…………", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我想起索娅刚才说“我不进去”时落寞的表情，不知说什么才好。")
	await novel_interface.show_text_only("对她这样被修道院收养的孤儿，那就相当于第二次被从家里赶出来一样吧？")
	await novel_interface.show_text_only("所以她才对莉琉说证据就在自己的身体里……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("而且她还说过──")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("我还想陪小怜再多玩一会儿。", "索娅")
	await novel_interface.show_dialog("明天中午12点前我们一起回SID可以吗？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("那个笨蛋……！", "小怜")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_L.png")
	await novel_interface.show_text_only("我翻身从长椅上爬起来，虽然疼痛感确实缓解了不少，但依然隐隐作痛。")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("欸哎呦──", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("el","smile",0.25)
	await novel_interface.show_dialog("你还疼呢？别乱动……", "艾尔加纳")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我依然咬着牙整理好衣服，向教堂前方直接通往西侧走廊的侧门跑了过去。")
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("在加密频道，莉琉接通了目前唯一能联系到的元老院成员。")
	novel_interface.show_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("莉琉？找我有事吗？\n他们几个还关在小黑屋里开封闭会议呢──", "布莱特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("布莱特显然没做准备，说话的时候嘴里还嚼着什么东西。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("（这个大猩猩……）", "莉琉")
	await novel_interface.show_dialog("咳咳──布莱特博士，你知不知道现在第一大道上的暴乱快要失控了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("失控不了，不是还有帕兰蒂尔的雇佣兵吗。\n哪年没暴乱啊，顶多死几十个人~", "布莱特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这种结果确定的事件显然无法引起他的兴趣。")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("等等，你联系我……是因为有『模因』的影响？", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("现在并没有直接证据，但我有几个关于模因类异质物的问题想请教您。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("原来还没找到啊，那能不能过会再说，我还有几个会要开……", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("布莱特博士！！", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉一向对布莱特脱线的性格不爽，但不得不承认他是研究模因类异质物的顶级学术权威。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("我弄到一些卡文迪什香蕉──", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("嚯！？怎么弄到的？\n我还以为那东西早就绝种了！", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("是在萨蒙顿的无菌温室重新育种的果实样本，要是您能帮我解答一个问题，这就派人送到府上。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("啊哈哈，那说吧你想问什么~", "布莱特")
	await novel_interface.show_dialog("不过我只回答一个问题，你可想好啊。", "布莱特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉料到他会这么说，将那个问题直接抛了出来。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("关于模因类异质物，通常的认知是“会引发异常的信息”。", "莉琉")
	await novel_interface.show_dialog("可您不止一次的在公开场合表达过对这种观点的不屑，却从没发表论文解释您反对它的原因。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("我想请您解释一下。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("情报工作做得不错啊，还以为你不会关注那些无聊的学术会议……", "布莱特")
	await novel_interface.show_dialog("凡是能够说的，都能够说清楚；凡是不能说的，必须保持沉默。", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("这是维特根斯坦的名言……你是说答案在语言的边界之外？这可不算什么回答。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("我是说，『模因』能改变这个世界的底层机制，而语言是更高级的产物。", "布莱特")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Meme.png")
	await novel_interface.show_dialog("你应该知道，即使没有异质物特性的『模因』，也能轻易改变我们的语言、文化甚至基础认知。", "布莱特")
	await novel_interface.show_dialog("一开始只是网上流行的片段，却逐渐在传播中被赋予了本身并包含的意义。", "布莱特")
	await novel_interface.show_dialog("最后新的意义完全替代原来的意义，成为新的底层机制。", "布莱特")
	await novel_interface.show_dialog("模因连我们解读信息的解释器都能轻易扭曲，怎么能说那只是“会引发异常的信息”呢？", "布莱特")#多字问题
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("如果仅仅是这样，只要接受被改变的概念就好，语言不就是一直这么演化至今的吗。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("异质物能引发的超常物理现象，说到底依然是物理现象，否则就不可能用科学的方法研究。", "布莱特")
	await novel_interface.show_dialog("同样的道理，模因类异质物可以完成一般模因难以完成的概念替换，而且不仅能作用于人脑。", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("这我当然知道，『埃癸斯』就是模因类异质物，一段电脑程序运行之后却能产生绝对的物理防壁……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("那是对质量、矢量和能量等物理概念进行了替换。", "布莱特")
	await novel_interface.show_dialog("但如果一个强大的模因能将全世界“红色”和“绿色”意义交换呢？", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("如果只替换称呼而不改变本质的话……\n应该没什么变化？", "莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("等等，如果将“0”和“1”的意义交换的话，就\n能瞬间瘫痪所有的计算设备……", "莉琉")
	await novel_interface.show_dialog("甚至造成世界末日级的灾难──", "莉琉")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("所以说，信息只是模因传播的形式，而最后真正被替换的是概念本身！！", "布莱特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("布莱特无奈的叹了口气。")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("历史上曾有机构致力于隐瞒异质物的存在，那时他们认为这样才能保护人类这个脆弱的物种。", "布莱特")
	await novel_interface.show_dialog("他们认为不能让那种荒谬的存在动摇人们来之不易的理性与秩序。", "布莱特")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Spy1.png")
	await novel_interface.show_dialog("甚至还成立了一个精英小组，专门负责控制模因类异质物的扩散。", "布莱特")
	await novel_interface.show_dialog("现在联合议会也有一个部门负责这件事吧，之前还邀请过你去做主席。", "莉琉")
	await novel_interface.show_dialog("哈哈哈，那帮笨蛋认为，模因类异质物只渗透并改变了世界上大约3%的基础概念。", "布莱特")
	await novel_interface.show_dialog("那……实际呢？", "莉琉")
	await novel_interface.show_dialog("实际上，我们的世界早就被那些东西彻底渗透了！", "布莱特")
	await novel_interface.show_dialog("那群所谓“精英”付出巨大代价最终测算出的数据，也使得整个机构彻底崩溃──", "布莱特")#换行问题
	await novel_interface.hide_background()
	await novel_interface.show_text_only("莉琉听到这里不由冷汗直冒，布莱特短暂的停顿使她屏住了呼吸。")
	novel_interface.show_background("res://assets/images/bg/Soya/Spy2.png")
	await novel_interface.show_dialog("模因类异质物的渗透率已经超过2000%", "布莱特")
	await novel_interface.show_dialog("──！！", "莉琉")
	await novel_interface.show_dialog("就像细菌一样，更强的模因会不断覆盖曾经的获胜者。", "布莱特")
	await novel_interface.show_dialog("想将世界恢复到最初的状态早已不可能了──", "布莱特")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("光线、声音、文字、图像、代码，一切都可以成为模因类异质物的传播途径。", "布莱特")
	await novel_interface.show_dialog("联合议会的那种表面机构只是做给别人看，实际上他们自己也会使用模因。", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("什么？！", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("不然你以为，『新凯旋门计划』是怎么让全世界如此快就接受了学园都市这个称谓的？", "布莱特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉感到浑身颤抖。")
	await novel_interface.show_text_only("那是恐惧吗？\n不，更多的是兴奋。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("我明白了……", "莉琉")
	await novel_interface.show_dialog("被模因类异质物感染的人，就算被严重扭曲了感官也不会觉得自己有任何不妥。", "莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("因为人们的大脑总能将自身的状况合理化，却不能容忍无法解释自己的选择。", "莉琉")
	await novel_interface.show_dialog("我说的，没错吧？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉的嘴角难以自抑的上扬。")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("新丰洲纪念教堂西院。")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N_Backyard.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("那个笨蛋……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我跑出教堂侧门的一瞬间，忽然感到一阵窒息。")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("（是刚才治疗的作用吗？）\n（不对，这个感觉……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("时间仿佛凝滞了几秒，最后伴随着整个空间微微的抖动，那种异样的感觉才终于消失。")
	novel_interface.show_character("ren_fishnet","solemn")
	await novel_interface.show_dialog("怎么回事！？", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("等等……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅不在这边，她现在在教堂门口的广场上。")
	await novel_interface.show_text_only("不知为何，我就是有那种强烈的感觉。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Soya/Church_N.png")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("果然──", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我来到广场，索娅正光着脚坐在喷泉边玩水。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("小怜，你来啦……", "索娅")
	await novel_interface.show_text_only("她将丝袜脱下来踩在水池里，捏起一缕头发绕在指尖打转。")
	await novel_interface.show_text_only("朦胧的灯光下，她好像喝醉了一般，面颊微红的看着我──")
	await novel_interface.show_text_only("我的心脏一阵猛烈的跳动。")
	await novel_interface.hide_character()
	
	print("=== 天启篇第15话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
