# apocalypse_ep07.gd - 天启篇第07话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第07话剧本
	apocalypse_ep07_script()

func play_script():
	pass

# 天启篇第07话 - 正式剧本
func apocalypse_ep07_script():
	# scene1 - 继续美术馆对话
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("马萨达议长自杀了？怎么可能！", "拉斐尔")
	await novel_interface.show_dialog("看他在发布会上的状态，回去开香槟还差不多……是不是其他什么人做的？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("嘛，虽然我也想跟摩诺拉的特勤队玩玩……", "瑟蕾莎")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("但以那群家伙的水平，想偷偷潜入把人做掉还伪装成自杀，应该不太可能。", "瑟蕾莎")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("难道是被威胁了？", "拉斐尔")
	await novel_interface.show_dialog("还是说他本来就是一枚弃子……", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","smile")
	await novel_interface.show_dialog("好了别瞎猜啦，乖乖听话~", "瑟蕾莎")
	await novel_interface.show_dialog("现在联合议会总部所在的第一大道上，聚集抗议的人群已经快要控制不住了。", "瑟蕾莎")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("而且你不是答应过你爷爷吗――", "瑟蕾莎")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("瑟蕾莎拍拍拉斐尔的后背，对她耳语了几句。")
	novel_interface.show_character("ren_fishnet","normal2")
	await novel_interface.show_dialog("（看瑟蕾莎的样子，不是欧洲人吧？）\n（而且还拿着那么招摇的武士刀上街……）","小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("（虽说使馆区附近确实不怎么检查这个~）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她们说完，拉斐尔对瑟蕾莎点点头，随后示意大家一起下楼。")
	
	# scene2 - 夜晚电器街
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("我们走出美术馆，回到了街上――")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("此时天刚擦黑，街边的路灯已经亮了起来，暖色的灯光映衬着电器街熙熙攘攘的烟火气。")#不确定
	novel_interface.show_character("iluka_uniform","speechless")
	await novel_interface.show_dialog("哇――", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("人可真不少……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("这附近是有什么活动吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("刚才我查了一下，前一阵的限行导致这条街上很多店铺停业了几天――", "随行人员")
	await novel_interface.show_dialog("但昨晚管制提前解除，原定于下周一举行的开市活动也被提前到今天。", "随行人员")
	await novel_interface.show_dialog("内容好像是免费派送某部动画的限定周边。", "随行人员")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("难、难道是……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我发现街上很多人都拿着印有“禁止通行”的黄色小旗子，那是最近很火的一部动画中的道具。")
	await novel_interface.show_text_only("一大群穿着幼稚园服装拿着小旗子努力工作的小萝莉着实萌翻了许多人——比如说我。")
	novel_interface.show_character("ren_fishnet","smile")
	await novel_interface.show_dialog("（啊啊啊是那个那个！！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我不禁有些激动。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("嗯？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("（还、还是先别说了……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我熟练的收敛气息缩了回去。")
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("我得先回去了，你们几个最好也别在这一带乱晃。", "拉斐尔")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("今晚估计不会太平……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔把一颗弹球大小的绿色宝石塞进我手里。")
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("这是海因里希做的，受伤的时候可以救急。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔似乎有些不好意思的回避着我的目光。")
	novel_interface.show_character("ren_fishnet","gratified")
	await novel_interface.show_dialog("啊……海因里希……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("说来有段时间没见到那个总叫我“主人”的炼金术士了。")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("（不知她要是听说我最近经常穿着女仆装对别人叫主人会作何感想……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","worry")
	await novel_interface.show_dialog("总之，你自己小心。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没等我回话，那位大小姐和瑟蕾莎一行人就转身快步走远了。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我目送着她们三人的背影消失在电器街的人群中。")
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("嘛……她好像还紧紧攥着那本刚才用来打我的书呢。", "索娅")#换行问题
	await novel_interface.hide_character()
	await novel_interface.show_text_only("怪不得跑的那么快！")
	novel_interface.show_character("ren_fishnet","smile")
	await novel_interface.show_dialog("话说，要不咱们也去看看那个活动，然后回――", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我正盘算着去搞个限定周边，突然被索娅推到了街角的墙上。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("吶……你刚才电我电得很开心呢~", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("噫！？\n对、对不起！", "小怜")
	#await novel_interface.show_dialog("", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我才意识到，自己好像有点太得意忘形了。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("从今天下午开始，我就好奇的不得了――", "索娅")
	await novel_interface.show_dialog("那个瑟蕾莎、拉斐尔和伊露卡……", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("（她们……三个？）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("她们全都散发着和女巫差不多的气息，却还保有着人类的颜色……", "索娅")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("――这和我之前了解的，不太一样呢？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅用右手食指和中指戳在我心脏的位置，冰冷的目光传达着明确的信息:")
	await novel_interface.show_text_only("“如果说谎，就会死。”")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("你是说瑟蕾莎……也是魔女？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("魔女？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看着索娅的脸，小心的组织着语言。")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("就是那些获取了魔法的『知识』，同时还能保有理智的女生。", "小怜")
	await novel_interface.show_dialog("但很多人没法承受那些信息，就会因此丧失理性沦为女巫。", "小怜")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("这就是二者的区别……大概。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅盯着我眼睛看了一会，接着问道。")
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("那些失去理性的人，可能恢复吗？", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("我记得爱衣说过，从理论上没可能……", "小怜")
	await novel_interface.hide_character()
	
	# scene3 - 回忆场景
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("几周前。")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("播磨脑研对样本女巫大脑的扫描完成了，发现了一些有趣的事情呢~", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("你是说前一阵军方花了“很大代价”从北部山区抓来的那几只？", "小怜")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("（还好我只需要处理埃癸斯范围内的异变……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("嘛，虽然制作束具花了点功夫……\n过程先不描述，直接告诉你结论吧~", "爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("第一，女巫的身体依然受大脑支配，但完全不会考量身体的物理极限。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/Hypnosis.png")
	await novel_interface.show_dialog("通常人出于自我保护，会给身体设置一个意识层面的极限值，可以通过催眠之类的方法暂时解除。","爱衣")
	await novel_interface.show_dialog("比如被催眠的人可以只依靠头和脚部的支撑，像木板一样躺在中间完全悬空的架子上。","爱衣")
	await novel_interface.show_dialog("同时腹部还能承受数十公斤的额外压力……在神志清醒的时候，人类是无法做到的。","爱衣")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("而女巫的大脑完全将身体当做消耗品，可以获得超常爆发力，但丝毫不考虑对身体的损耗。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("（所以才能常常将关节扭曲成那种非人的状态吗……）","小怜")#换行问题
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("第二，女巫的大脑即使在电磁屏蔽环境中，也一直在接收着未知来源的信息，且速率每秒都在提升。", "爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("就像一块不停被写入和擦除的硬盘，理论极限带宽取决于全部脑细胞写入和擦除一次的速度。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("但那个时候，细胞就会因超负荷工作大量死亡，剩下的细胞则要承担更大的负载，使情况加速恶化。", "爱衣")
	await novel_interface.show_dialog("而脑内原本的人格意识，早就像融入大海的一滴水，彻底消散了。", "爱衣")#换行问题
	await novel_interface.show_dialog("综上，女巫是有极限的――肢体性能受物理材料的限制，魔法能力受到物理大脑的限制。", "爱衣")
	await novel_interface.show_dialog("可以认为女巫从身体到大脑，都是一块注定被消耗殆尽的电池。", "爱衣")
	await novel_interface.show_dialog("这块电池的极限性能，取决于其短路状态下能承受的最高放电强度。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我知道爱衣调取过那几个人生前的全部档案，也一定尝试了各种方法试图恢复她们的人格。")
	await novel_interface.show_text_only("而她对女巫完全去人格化的描述，是为了让我在不得不面对那些东西的时候放下心理负担吧……")
	await novel_interface.show_text_only("人类的理性如同一座大坝，虽然平时看来坚不可摧，但从溃堤的那一刻，就注定了结局。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("索娅的工作就是在溃堤发生后当机立断的止损。")
	await novel_interface.show_text_only("想必是件很残酷的事吧……")
	
	# scene4 - 回到现在
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraN.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("索娅听到我的回复，好像如释重负般慢慢的松开了手。")
	await novel_interface.show_dialog("……是吗。","索娅")
	await novel_interface.show_text_only("她说话的声音很小，低着头同时带着些许颤音。")
	await novel_interface.show_dialog("你知道吗，刚才瑟蕾莎引导你挥出手臂时……","索娅")
	await novel_interface.show_dialog("我以为会被你们杀掉――","索娅")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("从她接触你的身体到你蓄力的那段时间，你们的气息提升了几十……不，可能是上百倍。","索娅")
	await novel_interface.show_dialog("一般人在那种情况下早就被吞噬了。","索娅")
	await novel_interface.show_dialog("然而眼看着那道贯穿整座大厦的红色气息穿过我的身体，却没有伤到我分毫……","索娅")
	await novel_interface.show_text_only("索娅猛然抬起头时已是满脸红晕。")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("――我从没见过那么漂亮的东西！！", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("（她究竟是被什么气息穿透了啊！！）","小怜")
	await novel_interface.hide_character()

	print("=== 天启篇第07话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
