# apocalypse_ep09.gd - 天启篇第09话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第09话剧本
	apocalypse_ep09_script()

func play_script():
	pass

# 天启篇第09话 - 正式剧本
func apocalypse_ep09_script():
	# scene1 - 拘留室越狱
	novel_interface.show_background("res://assets/images/bg/Soya/Police_Cells.png")
	novel_interface.change_music("res://assets/audio/music/Brooklyn.mp3")
	await novel_interface.show_text_only("我疑惑的看着索娅手中纽扣上的短针，又观察了一下四周和金属门上的锁孔――")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("你是想……撬锁？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拘留室周围起码有四组摄像监控，而且那种锁不是随便就能撬开的吧。")
	await novel_interface.show_text_only("索娅没理会我，轻飘飘的走到一名靠墙坐着的肌肉壮汉面前，挑衅的盯着对方的脸。")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("咦？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","trance")
	await novel_interface.show_dialog("啊，你脸上好像……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅用人畜无害的表情看着他，同时指了指自己的脸。")
	await novel_interface.show_text_only("那壮汉先是一愣，随后也跟着抹了抹自己的脸。")
	await novel_interface.show_text_only("银发少女摇摇头，微笑着伸手要帮他擦，那个肌肉男居然露出了有些害羞的表情。")
	await novel_interface.show_text_only("她就着探身上前的动作，另一只手突然将纽扣短针拍进了那位壮士的大腿。")
	await novel_interface.show_text_only("只见他大叫一声，刚想起身骂人，却怎么都无法站起来，张开的嘴也没继续发出声音。")
	await novel_interface.show_text_only("索娅摆出一幅不知所措小女孩的样子喊道――")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("他、他好像有点不对劲！你们快看看！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她边叫边推着壮汉的上半身向一侧倾倒，并顺手把扎在他腿上的纽扣取走。")
	await novel_interface.show_text_only("随着身材魁梧的肌肉男浑身僵硬的栽倒在地，临时拘留室内乱成一片。")
	await novel_interface.show_text_only("两个小混混探过来想看看究竟，而那几位花枝招展的姐姐则在远离壮汉的同时发出阵阵惊叫。")
	await novel_interface.show_text_only("索娅趁乱拉我在栅栏门附近的墙边站好，让我背对着大门。")
	await novel_interface.show_text_only("我们默默用眼神交流――")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("（眼神）你又干什么好事了！？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("（眼神）嘿嘿嘿嘿……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("很快就赶来三个警卫，其中两人进门检查那人的状况，还有一人守在门口。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("有人在守门啊……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅露出一个缺德的笑容，伸出一只脚勾住我的脚腕，接着对准我的肚子一推――")
	await novel_interface.show_dialog("（诶？！）","小怜")
	await novel_interface.show_text_only("见我快要后仰着摔在地上，看门的警卫下意识向前两步扶住了我。")
	await novel_interface.show_text_only("我刚要扭头道谢，却看到他已被索娅找到空当击中后颈翻了白眼。")
	await novel_interface.show_text_only("我一边在心里拼命道歉，一边和索娅将那人轻轻的放在拘留室门口座椅的靠背上。")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("（对不起对不起对不起！！）\n（不过管不了那么多了，先找到伊露卡要紧！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我们二人踞手蹑脚的溜出了拘留室。")
	await novel_interface.show_text_only("索娅在走廊转角处按下火灾警报，然后冲到办公区大喊“那边犯人暴动了！”吸引了大部分警员。")
	await novel_interface.show_dialog("（她为什么这么熟练啊！！）","小怜")
	
	# scene2 - 逃出警局
	novel_interface.show_background("res://assets/images/bg/Soya/Police_Station.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("我们趁乱混出警局时，外面已经天黑了。")
	await novel_interface.show_text_only("索娅拉着我迅速跑到马路对面，我回头看了看惨白刺眼的路灯后警铃大作的看守所。")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("他们应该已经发现了吧……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这是国际领土，而我并没有索娅的豁免权，万一被保安军抓到的话――")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("（故意伤害、袭警、越狱、破坏公共财物……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我想象着自己身穿黑白条纹的囚服在铁窗后默默流泪的场景……")
	await novel_interface.show_dialog("喂，你，鬼鬼祟祟的在那干嘛呢？", "保安警")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一个巡逻归来的警员向这边走来，在我反应过来时索娅已经消失在路旁的阴影中了。")
	await novel_interface.show_text_only("那个保安警有些不屑的上下打量着我。")
	await novel_interface.show_dialog("最近做这种事的女孩年纪越来越小了……\n身份证拿出来！", "保安警")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("（喂喂，他不会以为我是——）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我犹豫了一会，期待着索娅突然出现把他撂倒……")
	await novel_interface.show_text_only("但她似乎完全没有准备帮我的意思。")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("嗯……\n那个……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我只能做出一幅可爱的样子，扭捏地抓紧裙角，露出为难和害怕的表情，轻声细语的说道――")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("人家和同学来这边逛街走散了……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我边说边调整着略带哭腔的声音，尽量让自己显得无害。")
	novel_interface.show_character("ren_fishnet","shy_left")
	await novel_interface.show_dialog("再、再不回家的话，妈妈会担心的……", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（不过我把伊露卡弄丢了，莉琉妈妈绝对会搞死我的！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("他没料到我的反应，僵硬的看着我有些犹豫的吞了吞口水。")
	novel_interface.show_character("ren_fishnet","shy_left")
	await novel_interface.show_dialog("（我到底在做什么啊——！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然那个保安警好像被什么刺了一下，还没来得及扭头就浑身瘫软倒地，露出猫在身后的索娅。")
	await novel_interface.show_text_only("索娅从他背后取下纽扣短针，贱兮兮的学着我的样子说道――")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("再、再不回家的话，妈妈会担心的~", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","shy_right")
	await novel_interface.show_dialog("讨厌！你故意拖时间的吧！？", "小怜")
	novel_interface.change_expression("shy_right")
	await novel_interface.show_dialog("而且又弄倒一个警察，万一被抓了……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("被抓到的话你说是被我绑架就可以了，反正他们不能拿我怎么样~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅边说边将那枚纽扣短针折起来，重新别到披风上。")
	novel_interface.show_character("ren_fishnet","stare")
	await novel_interface.show_dialog("那个短针上是什么东西？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("嘛……河豚毒素提取物，能让人的肌肉麻痹，但不会影响心脏和呼吸系统。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅得意的介绍道――")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("在毒性持续期间虽然动不了也不能说话，但头脑是完全清醒的，神经感觉也不会消失……", "索娅")
	novel_interface.change_expression("relieve")
	await novel_interface.show_dialog("这时无论做什么都可以哦~！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她为什么一脸期待的看着我啊！？")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("莉琉居然没把那么危险的东西收走吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","wordless")
	await novel_interface.show_dialog("切，那个母猩猩不是安排了更危险的家伙跟来监视我吗！", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("啊！伊露卡……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("已经这么晚了，想到伊露卡一个人在街上，我不禁担心起来。")
	novel_interface.show_character("soya_uniform","normal")
	await novel_interface.show_dialog("要去电器街找找吗？那边好像有些骚动呐~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅望向不远处闪烁着霓虹招牌的街道，人群正散发出异样的颜色……")
	await novel_interface.hide_background()
	novel_interface.change_music("")
	await novel_interface.show_text_only("与此同时，协约非武装区内。")
	await novel_interface.show_text_only("天空酒店。")
	
	# scene3 - 天空酒店对话
	novel_interface.show_background("res://assets/images/bg/SkyHotel/Soya_Lounge.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("一个穿着白色教袍的老者来到休息区，示意两个年轻随从在门口等候。")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("从清奈远道而来辛苦了，一直没来得及恭喜您晋升呢——南印度圣公会，米勒总主教…", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("miller")
	await novel_interface.show_dialog("伦伯特啊，今天的事你早就知道了吧……", "米勒")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("身材肥硕的总主教大人叹了口气，缓缓落座。")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("虽然我很早就表达了对第三学园都市的支持――", "伦伯特")
	novel_interface.change_expression("usually")
	await novel_interface.show_dialog("但我也没料到他们的议长会在这个时间就公布反击系统的消息，而且在发布会刚结束就自杀。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("miller")
	await novel_interface.show_dialog("是“某些人”想将消息在封闭会期间放出？", "米勒")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","usually")
	await novel_interface.show_dialog("目前无法确定是不是个人行为，但应该不是出自施恩内曼总理的授意。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("miller")
	await novel_interface.show_dialog("且不论时机，那个东西被建造出来这件事本身意味着什么，你不会不知道吧？", "米勒")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("这也是我今天来见您的目的――", "伦伯特")
	novel_interface.change_expression("usually")
	await novel_interface.show_dialog("主动放弃战略异质物的使用权，将其纳入一个自己无法干预的被动反击系统。", "伦伯特")
	await novel_interface.show_dialog("结合马萨达的经济形式看来……", "伦伯特")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("这个国家，应该已经开始厌恶战争了。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("miller")
	await novel_interface.show_dialog("哼！那群抵抗军还不是他们自己捅出来的篓子。", "米勒")#文字错误
	await novel_interface.hide_character()
	await novel_interface.show_text_only("米勒总主教不以为然的摇了摇头。")
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("但如果施恩内曼总理开始裁军，马萨达的控制范围必然收缩，恐怕会放弃对西奈半岛的控制。", "伦伯特")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("这样也没关系吗？", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("miller")
	await novel_interface.show_dialog("你是说，苏伊士运河……", "米勒")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","relax")
	await novel_interface.show_dialog("我相信无论是戴克斯博士还是教宗大人，都不希望这种状况发生吧。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特将身体靠到椅背上，露出一丝微笑。")
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("我想寻找一条持续稳定的道路，让马萨达有足够的资源和动力维持西亚的稳定。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("米勒总主教沉默的点了点头。")
	novel_interface.show_character("lambert","serious")
	await novel_interface.show_dialog("以目前的国际公约，马萨达只能向非洲和南美输出他们的“国防解决方案”。", "伦伯特")
	await novel_interface.show_dialog("但联合议会成员国和附属区域都被排除在允许的市场之外，这样是无法维持马萨达国防军的。", "伦伯特")
	await novel_interface.hide_character()
	novel_interface.show_character("miller")
	await novel_interface.show_dialog("可施恩内曼那个老顽固要是决议裁军……", "米勒")
	await novel_interface.hide_character()
	novel_interface.show_character("lambert","sedation")
	await novel_interface.show_dialog("他已经老了――", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特打断了米勒的发言。")
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("可他的儿子和两个侄子都还在国防军任职。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特故意停顿，米勒沉思良久之后打破了沉默。")
	novel_interface.show_character("miller")
	await novel_interface.show_dialog("施恩内曼已经承诺卸任之后要重新选举，这一点你不会不知道……", "米勒")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特拿起酒杯，看着休息室墙面上被灯光效果刻意制造出的摇曳竹影。")
	novel_interface.show_character("lambert","smile")
	await novel_interface.show_dialog("权力来自民众的信任，而信任源于人心――", "伦伯特")
	novel_interface.change_expression("sedation")
	await novel_interface.show_dialog("『安全』和『安全感』就像事物的本体和投射在这墙壁上被放大许多倍的影子。", "伦伯特")
	await novel_interface.show_dialog("民众总会为了『安全感』而放弃『安全』，在人们心里，些许安慰远比实际的保障更有价值。", "伦伯特")
	await novel_interface.show_dialog("我只是希望萨蒙顿和教廷方面，能提前对下一任马萨达总理给予一些政治上的支持。", "伦伯特")
	novel_interface.change_expression("relax")
	await novel_interface.show_dialog("毕竟――", "伦伯特")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("选举这种东西，是我们发明的。", "伦伯特")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伦伯特举杯向米勒致敬，然后一饮而尽。")

	print("=== 天启篇第09话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
