# apocalypse_ep03.gd - 天启篇第03话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第03话剧本
	apocalypse_ep03_script()

func play_script():
	pass

# 天启篇第03话 - 正式剧本
func apocalypse_ep03_script():
	# scene1 - 电器街下午
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("下午五点，猫丸电器街。")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("喂喂，你别拉着伊露卡跑那么快啊~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("此时，我正提着一个死沉死沉的纸袋，吃力的跟在一脸兴奋的银发少女身后。")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("明明……应该是你跟着我走才对吧！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("人声嘈杂的电器街路口，我刚刚发出的无力抗议迅速被喧闹的背景音吞没。")
	await novel_interface.show_text_only("战争期间，元老院为了调和不同地区移民之间的文化和宗教冲突，颁布了『社会公序法案』。")
	await novel_interface.show_text_only("原本繁荣的文娱产业因此受到了不同程度的限制。")
	await novel_interface.show_text_only("在埃癸斯的范围内，只有新使馆区和附近的一小片区域不受该法案的约束。")
	await novel_interface.show_text_only("自九年前在此处开业第一家女仆咖啡厅开始，越来越多贩卖“限制类商品”的店铺在此地聚集。")
	await novel_interface.show_text_only("今天那个法案已经废止，但这条横跨协约非武装区边界的街道却已发展成了新的御宅族圣地。")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("（话说，莉琉规定我穿的这套服装――）","小怜")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("（为什么配的是渔网袜啊！！）","小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（第一次穿这种袜子，感觉怪怪的……）","小怜")
	await novel_interface.show_dialog("（还有这双短靴的鞋跟有点高呢）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一边提着袋子追赶索娅，一边用手调整着网袜的位置，全然不顾路人异样的目光。")
	await novel_interface.show_text_only("他们不知道，此时我前方不远处那位银发少女右脚脚踝上的设备，正实时监测着和我之间的距离。")
	await novel_interface.show_text_only("只要我和索娅相距超过10米，那个异质物金属加固的脚环就会立刻进行两万伏的高压放电。")
	await novel_interface.show_text_only("毫无疑问……这又是爱衣的杰作。")
	await novel_interface.show_text_only("突然，我在转角的台阶处脚下一滑，身体瞬间失去平衡――")
	await novel_interface.show_text_only("手中的纸袋顺着惯性，在我面前划出一道抛物线。")
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("“啪”")
	await novel_interface.show_text_only("纸袋重重拍在地上，塞得满满当当的内容物也随之散落出来。")
	await novel_interface.show_text_only("在我觉得自己也马上就要完成穿着渔网袜平地摔的壮举时，一只手突然从后面揽住了我。")
	await novel_interface.show_text_only("接着，我听到一个熟悉的声音。")
	await novel_interface.show_dialog("喂，女装癖――", "女性的声音")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("拉、拉斐尔？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("好像因为和平论坛的缘故，这位萨蒙顿总督的孙女已经在学校缺席好几天了。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("跑这么急，又去那家女仆咖啡打工吗？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔看着我狼狈的样子，露出一个意味深长的笑容，她的随行人员心领神会的跑去帮我捡东西。")
	novel_interface.show_character("ren_fishnet","awkward")
	await novel_interface.show_dialog("不、不是啦！！是新的任务……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("上次不知怎么被她知道我被安排在那家店打工，她居然特意跑来光顾好几次。")
	
	# 回忆场景
	await novel_interface.hide_background()
	await novel_interface.show_text_only("你能想象吗？！")
	await novel_interface.show_text_only("我，穿着白色吊带袜女仆装，站在拉斐尔面前――")
	novel_interface.show_character("ren_maid","shy")
	await novel_interface.show_dialog("欢迎回来……主人！", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("今、今天想吃点什么呢喵~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("噗――", "拉斐尔")
	await novel_interface.show_dialog("哈哈哈哈哈！！！", "拉斐尔")
	novel_interface.show_character("ren_maid","stare")
	await novel_interface.show_dialog("主人，您的红茶喷出来了喵……", "小怜")
	await novel_interface.hide_character()
	
	# 回到现实
	novel_interface.show_background("res://assets/images/bg/Soya/Akihabara.png")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("（啊啊啊，好想找爱衣做个记忆消除！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔上下打量着我，我连忙把连衣裙向下按了按。")# 换行问题
	await novel_interface.show_text_only("她却依然饶有兴致的盯着我的腿――")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("哦？这次是去勾引哪个政府要员吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","panic")
	await novel_interface.show_dialog("才不是啦！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔的随行人员抱着一大摞东西跑了回来。")
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("怜小姐，袋子破掉了，您的东西都在这里，我帮您清点一下。", "随行人员")
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("不用……别！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔好奇的随手拿起两本。")
	novel_interface.show_character("servent")
	await novel_interface.show_dialog("《妄想监禁》、《被捆绑的异世界生活》、《转生的私密治疗》……", "随行人员")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("“捆绑、痛楚，是我赐予你的自由……”", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔似乎看到了让她面红耳赤的画面，虽然想立刻把我臭骂一顿，但她情不自禁的又翻了一页。")
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","thinking")
	await novel_interface.show_dialog("……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("空气凝固了。")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("不不不不不，这些不是我买的――", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("短款束缚式内衣、马鞭……\n还有小怜小姐签名的收据。", "随行人员")
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("我、我只是结账……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的声音越来越小，好想找个地缝钻进去。")
	await novel_interface.show_text_only("旁边的路人开始议论起来。")
	await novel_interface.show_dialog("――喂喂，那个女生是M吗？", "路人A")#文本错误
	await novel_interface.show_dialog("脸蛋明明这么可爱……", "路人B")
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("（不是女生！）\n（更不是M！！）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("哦呀呀，确实是M呢――", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这时索娅也凑了过来，拿起那件内衣，指尖划过大写的“M”码尺寸标签。")
	await novel_interface.show_text_only("她勾着笑意的眼角像小猫一样上扬，殷红的舌尖俏皮地划过嘴唇。")
	await novel_interface.show_text_only("――居然露出了一幅得意的表情！")
	novel_interface.show_character("iluka_uniform","speechless")
	await novel_interface.show_dialog("小怜姐姐……M？", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","sob")
	await novel_interface.show_dialog("（啊啊啊，让我死了吧！！！）","小怜")
	await novel_interface.hide_character()
	
	# scene2 - 回忆审讯室
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/SID/hearingRoom.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("今天早些时候，SID审讯室。")
	novel_interface.show_character("soya_nun","relieve")
	await novel_interface.show_dialog("嘛……", "索娅")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("像是女巫、狼人、僵尸、恶魔、吸血鬼什么的，都是我的净化对象哦~", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("你说的那些东西……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","smile")
	await novel_interface.show_dialog("只是人们对各种异质物感染生物一厢情愿的称呼罢了，但我觉得没什么区别――", "索娅")
	await novel_interface.show_dialog("只要是散发着颜色浑浊不清的气息，闻起来有咸咸的味道，甚至让人嘴里有些发苦的话……", "索娅")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("那种东西不用犹豫，直接干掉就可以了。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着玻璃后面这个小女孩貌似天真无邪的笑容，莉琉的表情认真起来。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("你是说，你有『共感觉』……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("共感觉又称『通感』，是指在接受一种型态的感官刺激时，会自行将之转化成另一种型态的感觉。")
	await novel_interface.show_text_only("比如有人看到某种形象时能闻到特定气味，或是听到某种声音时能触发特定的视觉刺激。")
	await novel_interface.show_text_only("只有极小比例的人拥有这种特异功能般的能力。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("所以你才能够那么流畅的躲避攻击吗？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","relieve")
	await novel_interface.show_dialog("唔……可能吧~", "索娅")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("这次我被派驻到新丰洲教区，是为了预防那个什么论坛期间任何可能发生的“特别事件”。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("就是说，你只是偶然在路上发现了一群女巫，于是顺手解决掉了？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","normal")
	await novel_interface.show_dialog("对呀~所以我才招呼让它们自己过来嘛。", "索娅")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("要不是碰巧撞上了，我可追不上那些东西~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅摊了摊手，做了个鬼脸。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉有些不爽，她的“举手之劳”让规划了十多天，执行已超过80个小时的追踪行动瞬间泡汤。")#换行问题
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("那么，下一个问题――", "莉琉")
	await novel_interface.show_dialog("你刚才每句话都在故意暴露关键情报……", "莉琉")
	await novel_interface.show_dialog("你想提出的交易是？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","normal")
	await novel_interface.show_dialog("大姐姐你果然很擅长审问呢……", "索娅")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("嗯……刚才站在你位置的那个人。", "索娅")#文本错误
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("（刚才进来过的人是……爱衣？）","莉琉")
	await novel_interface.hide_character()
	
	# 背景切换
	novel_interface.change_background("res://assets/images/bg/Soya/AI.png")
	await novel_interface.show_text_only("索娅回想着几分钟前的情景，认真的说道。")
	await novel_interface.show_dialog("虽然那人没说话，但我感到她有种非常强大的……", "索娅")
	await novel_interface.show_dialog("希望把一切未知之物都吞噬殆尽的冲动。", "索娅")
	await novel_interface.show_dialog("……", "索娅")
	
	novel_interface.change_background("res://assets/images/bg/SID/hearingRoom.png")
	await novel_interface.show_text_only("小女孩的身体微微颤了一下，但很快恢复了常态。")
	novel_interface.show_character("soya_nun","smile")
	await novel_interface.show_dialog("我的条件是，只要别让那个人接近我，我就可以跟你合作。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("（爱衣确实符合她的描述，但她极少做出会伤害实验对象的事……）","莉琉")
	await novel_interface.show_dialog("（甚至可以说，对于有趣的样本，她有种发自内心的爱意。）","莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("你有不想发现的秘密吧？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉的嘴角微微挑起。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("我明白了，成交。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("几小时后，当天中午。")
	novel_interface.show_background("res://assets/images/bg/SID/hearingRoom.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("我刚才进来的时候，几个朝外走的探员似乎向我投来了同情的目光。")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("什、什么情况？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("放心，只是个普通的接待任务。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("顺着莉琉的手指，我隔着单向玻璃打量起审讯室里的女生。")
	await novel_interface.show_text_only("银色的长发、精致的面孔，一言不发的坐在那里。")
	await novel_interface.show_text_only("小姑娘给我的第一印象非常清秀典雅。")
	await novel_interface.show_text_only("直到她抬起头，漠然的目光穿透玻璃，扫在我身上的那一刻――")
	await novel_interface.show_text_only("我似乎看到她身上瞬间燃起了粉红色的火焰。")
	novel_interface.show_character("soya_nun","shy")
	await novel_interface.show_dialog("这、这个味道……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女瞬间起身，将脸贴在了我面前的玻璃上。")
	await novel_interface.show_text_only("就像觅食的小猫一样在玻璃前嗅个不停，好像口水都要流下来了。")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然在封闭模式下应该没有任何信息传到对面，但我还是本能的屏住了呼吸。")
	await novel_interface.show_text_only("莉琉咳了几声，将玻璃调整为交流模式。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("这位是索娅·安赫莱斯。", "莉琉")
	await novel_interface.show_dialog("索娅，这是小怜。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","laugh")
	await novel_interface.show_dialog("嘿嘿嘿~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女的心情很好，就像拿到新玩具的小孩。")
	await novel_interface.show_text_only("如果她有个尾巴，现在一定在兴奋的摇来摇去吧。")
	await novel_interface.show_text_only("莉琉又按了一下，玻璃瞬间变为不透明的白色，上面浮现出索娅的档案和新丰洲地图。")
	await novel_interface.show_text_only("莉琉和我简要介绍了一下索娅的情况，接着把地图放大。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("你的任务是，今天下午带着索娅和伊露卡在这片区域逛街。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","bored")
	await novel_interface.show_dialog("这不是你让我潜入的那家店旁边嘛……就在协约非武装区边界靠近使馆区的地方。", "小怜")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("不过这儿几天前就限制通行了吧？\n店铺好像一直歇业到下周论坛结束呢……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("联合议会昨晚突然解除这一带的管制，防卫厅这一带的人手也被元老院调走了大半。", "莉琉")
	await novel_interface.show_dialog("目前情报十分有限，但好像两边很默契的腾出了一个安保真空地带。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("所以我们其实是去巡逻吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("不，那一带的摄像监控十分密集――", "莉琉")
	await novel_interface.show_dialog("联合议会方面知道索娅的身份和能力，而元老院则能在第一时间就发现你。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("你们一起出现在那个区域，比你们去做什么更重要。", "莉琉")#换行问题
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("那如果她想逃跑怎么办？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("总觉得我根本打不过她……")
	await novel_interface.show_text_only("莉琉冷笑一下，将玻璃调为双向透明但隔声的状态，索娅正有些无聊的靠在墙边。")#换行问题
	await novel_interface.show_text_only("莉琉操作手持设备，银发少女脚踝上的金属环开始闪烁着红色的小灯。")
	await novel_interface.show_text_only("索娅对着莉琉露出一副严重抗议的表情，口型好像在说着“又来？”。")
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("紧接着，索娅的脚踝闪出一道淡蓝色的电弧，少女应声倒地，身上冒出一缕青烟。")
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("…………………………", "小怜")
	await novel_interface.show_dialog("……她", "小怜")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("……挂了？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("几秒后，修女的身体先是动了一下，然后慢慢自己爬了起来，她刚想对着玻璃这边大骂――")
	await novel_interface.show_text_only("莉琉面无表情的点了一下按钮，玻璃立刻变为不透明状态。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("你看，她跑不了~\n实在不行伊露卡还可以作为后备方案。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("你、你是恶魔吧！！？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("哦？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她一把将我按到墙上，把嘴贴到我的耳边。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("听好了，你的身体可是SID重要的财产――", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("擅自冒你不能承受的风险的话……\n是会被惩罚的哦~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("……！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我瞬间羞红了脸。")
	novel_interface.show_character("ren_uniform","shy_left")
	await novel_interface.show_dialog("我、我不会的啦！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉笑了笑，把我推出审讯室。")
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("知道你不敢。", "莉琉")
	await novel_interface.show_dialog("这次任务有着装要求，快去试试吧~", "莉琉")
	await novel_interface.hide_character()

	print("=== 天启篇第03话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
