# apocalypse_ep02.gd - 天启篇第02话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第02话剧本
	apocalypse_ep02_script()

func play_script():
	pass

# 天启篇第02话 - 正式剧本
func apocalypse_ep02_script():
	# scene1 - 客厅早晨
	novel_interface.show_background("res://assets/images/bg/APT/livingRoom_daytime.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("周五一早，电视新闻里就开始滚动播放当天凌晨营救人质的跟拍片段。")
	await novel_interface.show_text_only("由于SID及时封锁了埃癸斯范围内的所有通道，绑匪只能临时选择在一座老式仓库中囚禁人质。")
	await novel_interface.show_text_only("毫无悬念的，四名涉嫌绑架联合议会高层官员的恐怖分子被逮捕。")
	await novel_interface.show_dialog("在国际领土明目张胆的进行谋杀和绑架，是对联合议会所有成员国的公然挑衅！", "伦伯特")
	await novel_interface.show_dialog("这次事件充分说明了恐怖主义的渗透力，最近频发的时空相位波动也可能与恐怖活动有关。", "伦伯特")
	await novel_interface.show_dialog("作为经历过那场战争的幸存者，我始终认为……威慑是保证安全与和平最重要的手段。", "伦伯特")
	await novel_interface.show_text_only("我忍不住跳过了那段看上去套话连篇的采访，嘴里一边嚼着薯片一边说道。")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("这家伙好像差点屎掉诶！（嚼）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("刚被救出来就这么慷慨激昂的发表演说啊~还真是\n…嗯嗯…", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("不过防卫厅悬降攻入的那段好酷，简直像在拍特工片！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","smile")
	await novel_interface.show_dialog("嗯嗯——好酷！", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡认真的点着头。")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("那是后期特效和配乐的功劳啦，现在大家都喜欢搞这种夸张的效果。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这几天由于市里举办重大活动，学校上午10点半\n才上课，放学的时间也早了很多。")
	await novel_interface.show_text_only("此时我、安妮和伊露卡像仓鼠一样窝在沙发里，安妮还从我手里抢走了一半薯片。")
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("这次主要是靠SID的情报支援吧？\n新闻里一句都没提……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("没办法，情报机构需要保密嘛。还是低调一些比较好呢~", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","panic")
	await novel_interface.show_dialog("小怜姐姐……\n巧克力，没有了……", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡的小脑袋突然从我和安妮之间冒了出来。")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("巧克力味的Pocky吗？\n楼下便利店好像被我们买断货了……", "小怜")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("下次我去超市帮你买~", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","sleepy")
	await novel_interface.show_dialog("可是…可是，现在就没有了……", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡举着空荡荡的盒子，可怜巴巴的一边摇晃盒子一边看着我。")
	await novel_interface.show_text_only("然而这一阵的天气莫名燥热，我实在懒得出门，只想在空调房里当蘑菇。")
	await novel_interface.show_text_only("由于第四届国际和平论坛的缘故，协约非武装区来了不少大人物，莉琉最近也忙的不可开交。")
	await novel_interface.show_text_only("而且这次论坛规模空前，新丰洲之外的五大学园都市都派了上百人的代表团前来。")
	await novel_interface.show_text_only("这种高规格的政府首脑会议给大家的日常生活带来了诸多麻烦。")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("现在好多地方都临时禁止单人电动车通行，搞得外卖都没人送啦。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮一边翻看手机，一边倒向沙发另一侧，把头埋进抱枕里。")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("知道啦知道啦，我去买零食……\n安妮有什么想要带的吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("哼哼~", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_uniform","smile",0.25)
	await novel_interface.show_dialog("诶嘿嘿……", "伊露卡")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她们两人一幅奸计得逞的样子，毫不客气的列出一长串购物清单。")
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	
	# scene2 - 扶梯上
	novel_interface.show_background("res://assets/images/bg/Soya/Escalator.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_dialog("热——", "小怜")
	await novel_interface.show_dialog("好热啊……", "小怜")
	await novel_interface.show_text_only("这个时间超市才刚开门，但外面已经闷热难耐。")
	await novel_interface.show_text_only("我提着一大兜食物，这几天街上的警备员明显比平时多了好几倍。")
	await novel_interface.show_text_only("动不动就交通管制，还必须随身携带身份卡以应付临检……")
	await novel_interface.show_text_only("公共交通站点也都安排了防卫厅的巡逻车和安保助理。")
	await novel_interface.show_text_only("协约非武装区周边大范围交通限行，主干道的路灯上全都加装了新的监控装置。")
	await novel_interface.show_text_only("据说因为保安军不够用，联合议会把帕兰蒂尔的雇佣兵都雇满了……")
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("（不过也难怪他们如临大敌……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我从天桥向下望去，一个十几人的游行团体正好经过，旁边还有媒体的人扛着摄像机跟拍。")
	await novel_interface.show_text_only("由于战争才结束不久，这段时间全世界的记者和各种组织团体都涌入新丰洲。")
	await novel_interface.show_text_only("那些团体的诉求各异——地域冲突、民族矛盾、难民问题、宗教压迫、经济制裁，不一而足。")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("居然还有来趁机传教的……是嫌不够乱嘛？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("根据莉琉的说法，之前三届国际和平论坛，每次都不太平。")
	await novel_interface.show_text_only("本来上届和平论坛应该在马萨达堡，但因为周边恐怖袭击太频繁最终将会场转移到萨蒙顿了。")
	await novel_interface.show_text_only("结果戴克斯博士在去年的论坛上突然宣布萨蒙顿全面接收难民，会上直接炸开了锅。")
	await novel_interface.show_text_only("拉斐尔也因在那之后发表了“政治不正确”的大胆言论而被家里人送来新丰洲。")
	await novel_interface.show_text_only("不过据说前年论坛期间恐怖分子直接炸翻了纽摩利达斯市的一个街区，连武装直升机都用上了。")
	novel_interface.show_character("ren_uniform","bored")
	await novel_interface.show_dialog("唉，真是难以想象……", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Soya/protest.png")
	await novel_interface.show_text_only("前两天斯库尔德参与了使馆区的一个公益活动，捐助南美的饥饿儿童。")
	await novel_interface.show_text_only("居然撞到欧洲的素食主义组织在会场外呼吁禁止屠宰动物……")
	await novel_interface.show_text_only("还有人脱光了躺在地上亲自扮演牛排。")
	await novel_interface.show_text_only("在电视直播中，一个女仆往那块“牛排”身上浇了一锅紫色的混合着触手之类配菜的酱汁。")
	await novel_interface.show_text_only("那个可怜的阿姨“嗷”的一声尖叫着跑开了……")
	novel_interface.change_background("res://assets/images/bg/Soya/Escalator.png")
	await novel_interface.show_text_only("今天那个组织的网站上贴出声明，说成员受到了严重的心理创伤。")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("哈哈哈哈……\n（原来法贝拉知道自己的料理有多恐怖吗？！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("忽然，兜里的手机传来一阵震动\n是莉琉的留言——")
	novel_interface.show_character("ren_uniform","bored")
	await novel_interface.show_dialog("嗯……今天中午去总部报到？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("十个小时前。")
	
	# scene3 - SID指挥室
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("SID指挥室，23点15分。")
	await novel_interface.show_text_only("红发的女性身着军装，双手环抱在胸口，紧盯着屏幕上黑白画面中的十几个红色方框。")
	await novel_interface.show_text_only("屏幕下方忽然弹出一个对话窗口——")
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("报告长官，根据编号记录，被绑架的伦伯特还在埃癸斯范围内。", "SID探员")
	await novel_interface.show_dialog("监控回溯分析绑匪最可能出现在这三个区域中，湾区的一处老式仓库出现了异常用电……", "SID探员")
	await novel_interface.show_dialog("要通知防卫厅进行营救吗？", "SID探员")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("先不用，缩小包围圈，等我命令。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("明白。", "SID工作人员")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("窗口关闭后，莉琉切换到军用通讯频道。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("前面是山区，注意直升机高度，不要打草惊蛇。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("收到，卫星的热感影像很清晰。", "士兵A")
	await novel_interface.show_dialog("不过这种移动速度……它们真的是人类吗？", "士兵A")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("准确的说……『曾经』是。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("那些家伙前进的方向已经提前做好疏散了吧？如果出现异动——", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("火炮和区域毁伤武器已经待命！", "士兵B")
	await novel_interface.show_text_only("莉琉点了点头，她并不想向军方透露太多信息。")
	await novel_interface.show_text_only("而且从这次追踪行动一开始，莉琉就有种不祥的预感……")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("（那些新丰洲市区外产生的『女巫』，通常处理方式是由军方以提前布置好的重火力强行歼灭。）", "莉琉")
	await novel_interface.show_dialog("（根据以往的经验，那些东西在魔女之茧消失后会随机对周围生物及设施进行攻击。）", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（但最近两周开始，那些无理智的生物似乎突然呈现出了某种一致的行为规律……）", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("等等，前方好像……有个人影！", "士兵A")
	await novel_interface.show_dialog("这家伙…好像还拿着电锯，是附近的伐木工么？", "士兵B")
	novel_interface.show_character("liliu_uniform1","angry")
	await novel_interface.show_dialog("蠢货！会有人在夜里11点砍树吗？！\n模因检测的结果是——", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("色相为绿色，是人类！", "士兵A")
	await novel_interface.show_dialog("好像还是个小女孩？", "士兵B")
	novel_interface.change_background("res://assets/images/bg/Soya/thermal_Imaging.png")
	await novel_interface.show_text_only("莉琉立刻切到近距模式。")
	await novel_interface.show_text_only("热成像画面中，那个小女孩似乎戴着头巾，手中拿着与体型完全不相称的电锯。")
	await novel_interface.show_text_only("而此刻她居然在朝着那群高速狂奔的女巫招手。")
	await novel_interface.show_text_only("领头的几只听到声音，立刻向她的方向扑了过去。")
	await novel_interface.show_text_only("这种规模的女巫群落，往往需要一个有过应对经验且全副武装的重机枪排才能保证无损歼灭。")
	await novel_interface.show_text_only("就在莉琉准备通知清理小组一会去为少女收尸时，她却毫不犹豫的提起电锯迎了过去……")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("只见她随着电锯挥舞的角度调整着步伐，避开攻击的同时将链刃调整到恰好能切开对方身体的位置。")
	await novel_interface.show_text_only("那些女巫就像被塞进大功率切割机的生肉一般，纷纷顺着自身奔跑的方向被锯成碎块。")
	await novel_interface.show_text_only("小姑娘借着惯性和离心力流畅衔接着移动和攻击动作，却看不出任何超出常人的力量。")
	await novel_interface.show_text_only("就连她手中的电锯，似乎也是根据敌人特点和自身力量计算而选择的最有效率的武器。")
	await novel_interface.show_text_only("在不到30秒的时间内，那十几只SID联合军方追踪四天三夜的女巫就被切成了满地的肉块。")
	await novel_interface.show_dialog("怎、怎么办？", "士兵A")
	await novel_interface.show_text_only("莉琉无奈的叹了口气。")
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("该死……", "莉琉")
	await novel_interface.show_dialog("打开探照灯，地狱火导弹瞄准——", "莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("用喇叭喊话，让她知道自己的处境，敢轻举妄动就把她和这座山一起炸平。", "莉琉")
	await novel_interface.show_dialog("把那个人给我带回来！！！", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	
	# scene4 - SID审讯室
	novel_interface.show_background("res://assets/images/bg/SID/hearingRoom.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("几小时后，SID审讯室。")
	await novel_interface.show_text_only("莉琉在单向玻璃旁翻阅着手持设备上的档案。")
	await novel_interface.show_text_only("姓名：索娅·安赫莱斯")
	await novel_interface.show_text_only("年龄：14岁…？")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("所属机构……", "莉琉")
	await novel_interface.show_dialog("萨蒙顿教廷特别行政区——信理部。", "莉琉")
	await novel_interface.show_dialog("前身是『宗教裁判所』吧？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","smile")
	await novel_interface.show_text_only("随着莉琉的点按，玻璃变为双向透明，一名身着修女服的少女安静地坐在对面。")
	await novel_interface.show_text_only("娇小的身躯，被暗红色的宝石扣禁锢在黑色天鹅绒质地的连衣裙内。")
	await novel_interface.show_text_only("修女帽被私自改造出一对猫耳，倒是意外的符合她的样貌。")
	novel_interface.change_expression("jest")
	await novel_interface.show_text_only("银色长发和水蓝色的瞳孔本应十分惹人怜爱，然而她脸上那股无所谓的笑意却带着森寒的锐利。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉快速掠过相关事件报告，看到最下面的一行红字——")
	await novel_interface.show_text_only("此人受联合议会《萨蒙顿公约》特别条款保护，联合议会成员国机构控制时间不得超过12小时。")
	novel_interface.show_character("liliu_uniform1","speak")
	await novel_interface.show_dialog("喂，新丰洲军方针对你的调查令已经被取消了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","normal")
	await novel_interface.show_dialog("是吗？\n人家好怕呢~", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","serious")
	await novel_interface.show_dialog("怕的是他们才对吧？刚刚押运你的士兵主动申请要进行C级的记忆消除……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("双手被锁起来的银发少女舔了舔自己的嘴唇，露出兴奋的笑容。")
	novel_interface.show_character("soya_nun","relieve")
	await novel_interface.show_dialog("那群家伙的汗味实在是太臭了嘛，但我也没伤害他们呀。", "索娅")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("嗯……那大姐姐你要拷问我吗？你的味道很好闻呢！\n", "索娅")# 换行问题
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女紧紧的盯着莉琉，一副很感兴趣的表情。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("哦？你叫索娅对吧……", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("拷问可是我的“特长”之一呢。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉流露出一丝兴奋。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("不过，在此之前——", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女歪过脑袋，好奇的看着莉琉从档案袋中取出她的身份证明。")
	await novel_interface.show_text_only("上面是与学园都市身份卡截然不同的复古花纹，黑色卡面上雕刻着代表『裁判所』的金色符号。")
	await novel_interface.show_text_only("反面的认证信息区域一片空白，只有利用生物指纹技术才能进一步读取信息。")
	await novel_interface.show_text_only("使用档案袋中索娅指纹采样的复制品接触卡片，一行金色花体字浮现在光滑的背面。")
	await novel_interface.show_text_only("『理性、秩序与征服。』")
	await novel_interface.show_text_only("随着金色字样消退，卡片上出现了另外三行简短的文字。")
	await novel_interface.show_text_only("『代行神圣意志的骑士——』")
	await novel_interface.show_text_only("『索娅·安赫莱斯』")
	await novel_interface.show_text_only("『签署人：卡利克斯特四世』")
	await novel_interface.show_text_only("这张由教宗大人亲自签署的身份卡，正是索娅有恃无恐的原因。")
	await novel_interface.show_text_only("莉琉面前这个14岁的小姑娘，是官方认证的处理\n异质物感染及相关问题的“专业人士”。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("『审判骑士』，在收容异质物的同时，有权不经评估直接抹杀有潜在危险的感染对象……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","relieve")
	await novel_interface.show_dialog("嗯哼~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("『七年战争』末期，由于教廷在异质物感染方面的特殊贡献——")
	await novel_interface.show_text_only("联合议会决定授予部分执行人员六大学园都市的最高豁免权。")
	await novel_interface.show_text_only("《萨蒙顿公约》进一步约定此类宗教“净化”，不受世俗法律的约束。")
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("换句话说，就是隶属教廷的特别探员吗……", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("以宗教名义解决各国都很棘手的“异质物感染”问题，真是聪明的设计。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_nun","relieve")
	await novel_interface.show_dialog("嘛……\n像是女巫、狼人、僵尸、恶魔、吸血鬼什么的——", "索娅")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("都是我的净化对象哦~", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅的脸上再次露出天真无邪的笑容。")
	
	print("=== 天启篇第02话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
