# apocalypse_ep05.gd - 天启篇第05话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第05话剧本
	apocalypse_ep05_script()

func play_script():
	pass

# 天启篇第05话 - 正式剧本
func apocalypse_ep05_script():
	# scene1 - 盲点序章
	novel_interface.show_background("res://assets/images/bg/Soya/Blindspot.png")
	await novel_interface.show_text_only("盲点――视网膜上动静脉和视神经穿过的地方，这个区域没有感光细胞，因而不能引起视觉。")
	await novel_interface.show_text_only("但我们无法在自己的视野中找到盲点的位置，因为图像里缺失的那部分会被大脑自动填补。")
	await novel_interface.show_text_only("我们的大脑总是如此，会千方百计的将自身状态合理化。")
	await novel_interface.show_text_only("以至于很多人都会认为：凡是自身天生的，就是天然正确的。")
	await novel_interface.show_text_only("而事实并非如此――")
	await novel_interface.show_text_only("曾有人7岁时才意识到，自己的左眼早已失明。")
	await novel_interface.show_text_only("先天失聪的人如果不被提醒，也会认为这世界就是静音的。")
	await novel_interface.show_text_only("如果一种异常被当做了“初始设定”，你就不会感到任何不妥。")
	await novel_interface.show_text_only("直到某一天，当你不得不直面那些矛盾的时候，才会恍然大悟。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("那么…是否存在某种人类共有的先天缺陷，让所有人都习以为常呢？")
	novel_interface.show_background("res://assets/images/bg/Soya/Doomsday1.png")
	await novel_interface.show_text_only("直到某一天――")
	await novel_interface.show_text_only("人们都不得不面对那无法回避的矛盾时……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	
	# scene2 - 美术馆继续
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("我还在试着消化那条爆炸性新闻。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("（总觉得是很严重的事情，但又理不清头绪……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("就算新丰洲能抵御第一轮核打击，但接下来的污染问题、环境问题和粮食问题都是致命的――")
	await novel_interface.show_text_only("“在XK级世界末日中，没有幸存者。”")
	await novel_interface.show_text_only("这句总在新闻中被提到的话，正是联合议会能结束当年那场战争并维系和平的基础。")
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("其实无差别核反击体系并不是什么新鲜的东西，冷战期间类似的东西就被设计出来了。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","perspire1")
	await novel_interface.show_dialog("诶？那么久之前就有！？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("只是这东西很少被人提及――", "拉斐尔")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("你知道为什么吗？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("作为历史白痴的我，保持着“我啥也不知道”的礼貌笑容，吃了拉斐尔一记白眼。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("因为各国都有默契：这种东西互相知道就好，不要对公众宣传。", "拉斐尔")
	await novel_interface.show_dialog("长期以来，无论是审查制度严格还是倡导新闻自由的国家，此类话题都是媒体的禁区。", "拉斐尔")
	await novel_interface.hide_character()
	
	# 背景切换
	novel_interface.change_background("res://assets/images/bg/Shot/storyBGPol.png")
	await novel_interface.show_text_only("当年联合议会成立并宣布停战的时候，确实也只说了“为了文明和未来”之类冠冕堂皇的理由。")
	await novel_interface.show_text_only("大家都心照不宣的对各自的XK级『异质物』保持沉默——尽管那才是结束战争的根本原因。")
	await novel_interface.show_text_only("而且为了挽回民众对未来的信心，那次大会上还宣布了后来被称为“新旋转门计划”的决议――")
	await novel_interface.show_text_only("六个常任理事国一致通过，对各自的首都启用『学园都市』（AcademyCity）的称谓。")
	
	novel_interface.change_background("res://assets/images/bg/Soya/Guidepost.png")
	await novel_interface.show_text_only("这场声势浩大的运动包括政府重组、发行新币和新国债、修改机场地标名称、甚至更换路牌等等……")
	await novel_interface.show_text_only("虽然只是改了个名字，各国的信用体系却奇迹般的在数月内从战争状态中恢复了过来。")
	await novel_interface.show_text_only("连上市公司都纷纷提出更名申请——只要与『学园都市』概念沾边，就能立刻推高股价。")
	novel_interface.change_background("res://assets/images/bg/Soya/galleries.png")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("因为人们总倾向于幻想美好的未来。", "拉斐尔")
	await novel_interface.show_dialog("民众只是需要一个可以给幻想凭依的符号――", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("嘛……就像男孩子的“施法材料”一样对吧？", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","smile")
	await novel_interface.show_dialog("嗯？", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wail")
	await novel_interface.show_dialog("…………", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔攥紧手中的纸卷，亮出一个“你皮痒了？”的眼神，索娅立刻缩到了我的身后。")
	novel_interface.show_character("ren_fishnet","upset")
	await novel_interface.show_dialog("确实，这应该是一次蓄谋已久的公众宣传……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一般情况下，这种事只要在高层闭门会议中内部通知就可以了。")
	await novel_interface.show_text_only("就算是对那些无法参会的小国甚至恐怖分子，也有很多办法能了解到这个信息。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("现在六国能下达媒体禁止令的人全在那个屋里子开着封闭会议。", "拉斐尔")
	await novel_interface.show_dialog("全世界的媒体都希望能在禁令下达前，将这个爆炸性新闻的关注度和点击量压榨干净。", "拉斐尔")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("肆无忌惮的把焦虑和恐惧散布给公众的话……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔不安的看向窗外的人群。")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("平时……这里会有这么多人吗？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("虽然这条街的属性与政治事件基本绝缘，但今天电器街的人确实比平日多出不少。")
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.show_character("soya_uniform","relieve")
	await novel_interface.show_dialog("嘛……应该不用担心。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我们所在的大厅位于二楼，索娅走到落地窗附近环视了一圈，很有把握的说道。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("这些人的气息并没有过多愤怒的颜色，而且焦虑的烟熏味在这种密度的人群中也算正常。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("那就是你档案里说的……『共感觉』？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("应该算是吧~", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("那么，你平时看我们都是什么样子的？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅色香味俱全的发言引起了这位大小姐的好奇。")
	novel_interface.show_character("soya_uniform","smile")
	await novel_interface.show_dialog("嗯……你的感觉有点矛盾呢。", "索娅")
	await novel_interface.show_dialog("像是雨后田野的气息，还有种温暖的感觉，即使产生了负面情绪也很快能被冲刷掉。", "索娅")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_fishnet","perspire1",0.25)
	await novel_interface.show_dialog("（……所以她才无法躲避拉斐尔的攻击吗？）","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("然而索娅的表情有些困惑。")
	novel_interface.show_character("soya_uniform","speechless")
	await novel_interface.show_dialog("一般这种人都是温柔治愈的大姐姐，怎么会是你这种脾气臭又暴力的母――", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅的话才说到一半，我似乎看到了拉斐尔头上猛然腾起的怒火。")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("其、其实这代表你内心非常温柔宽容大度慈爱一定不会随便使用暴力的对不对。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅的语速忽然加快，并立刻转换话题。")
	novel_interface.show_character("soya_uniform","relieve")
	await novel_interface.show_dialog("咳咳——不过用小怜来举例的话，她的颜色是我见过最纯粹的哦。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","wry_smile")
	await novel_interface.show_dialog("欸？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("哦？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔的怒火迅速消散并提起了兴趣。")#文字错误
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("比如在甜品店吃芭菲的时候，每吃一口都能听到她内心发出类似“噫————好吃！”这样的叫声。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("什、什么啊！\n（不要说出来啊！！！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("每次叫完才会吃下一口，非常有趣呢。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("哈~不愧是你，真是蠢得可以。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("而伊露卡呢，就像仓鼠一样开心的一直吃。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","smile")
	await novel_interface.show_dialog("诶嘿嘿~", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡好像被夸奖了一样憨憨的笑起来。")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("在街上看到漂亮的女生，小怜会忽然冒出淡粉色的气息，在不扭头的情况下把眼球转到极限偷瞄。", "索娅")
	await novel_interface.show_dialog("或者假装看向那个女生身后的远方，看够了再把头转向完全不相干的方向，以为这样就能洗清嫌疑。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("哼，变态。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔白了我一眼。")
	novel_interface.show_character("ren_fishnet","shy_left")
	await novel_interface.show_dialog("别、别说了……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我还以为自己掩饰得很好呢……为什么要那么细致入微的观察我啊！？")
	novel_interface.show_character("soya_uniform","jest")
	await novel_interface.show_dialog("小怜看到漂亮的衣服会产生两种矛盾的颜色互相交战，不过通常是浅红色的那边赢。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("哦？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔扭头上下打量着我，视线又落在我的腿上。")
	novel_interface.show_character("ren_fishnet","shy_right")
	await novel_interface.show_dialog("（我不知道！我什么都不知道！！）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("对了，如果她忽然收敛气息，像要从人群中消失一样的话，就是打算偷偷调整内衣或网袜了。", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","hungry")
	await novel_interface.show_dialog("喔――", "伊露卡")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","mock",0.25)
	await novel_interface.show_dialog("呵呵~", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("伊露卡和拉斐尔听得津津有味，索娅也和她们越说越起劲。")#文字错误
	await novel_interface.show_text_only("不行了，这里已经没法待下去了。")
	await novel_interface.show_text_only("我收敛起气息偷偷后撤了两步――")
	novel_interface.show_character("soya_uniform","laugh")
	await novel_interface.show_dialog("啊啊还有，小怜在想上厕所的时候呀……", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没等索娅下半句说完，她脚环上的灯就开始闪烁。")
	novel_interface.show_character("soya_uniform","afraid")
	await novel_interface.show_dialog("啊嘞？", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("随着“咔”的一声，美术馆大厅的窗边闪过一瞬淡蓝色的弧光。")
	await novel_interface.show_text_only("只见银发少女身体挺直的摔在地上，身上又冒出一缕白烟。")
	await novel_interface.show_text_only("伊露卡蹲在地上戳了戳一息尚存的索娅，用无辜的眼神向拉斐尔表示这不是她干的。")
	await novel_interface.show_text_only("拉斐尔回头的时候，我已经跑到了楼梯口。")
	novel_interface.show_character("ren_fishnet","uneasy")
	await novel_interface.show_dialog("（对不起，只能想到这个办法让你闭嘴了！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("嘭――")
	await novel_interface.show_text_only("慌不择路的我似乎撞到了什么人身上。")
	await novel_interface.show_text_only("但那人并没有被我撞倒，反而顺势将我扶住了。")
	novel_interface.show_character("ren_fishnet","timid")
	await novel_interface.show_dialog("（这、这种弹性……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_background("res://assets/images/bg/Soya/Galleries.png")
	novel_interface.show_character("cereza","wordless")
	await novel_interface.show_dialog("小心点啊，小家伙……", "黑发女性")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("黑发的大姐姐似乎困意正浓，打了个哈欠。")
	novel_interface.show_character("ren_fishnet","shy")
	await novel_interface.show_dialog("啊、对、对不起~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她手中拿着一把日本刀，精致的刀鞘、刀镡和刀柄处处散发着顶级艺术品的气息。")#文字错误
	novel_interface.show_character("cereza","normal")
	await novel_interface.show_dialog("你是叫小怜吧？", "黑发女性")
	novel_interface.change_expression("jest")
	await novel_interface.show_dialog("小脸蛋长得还挺可爱的嘛~", "黑发女性")
	await novel_interface.hide_character()

	print("=== 天启篇第05话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
