# apocalypse_ep12.gd - 天启篇第12话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放天启篇第12话剧本
	apocalypse_ep12_script()

func play_script():
	pass

# 天启篇第12话 - 正式剧本
func apocalypse_ep12_script():
	# scene1 - 开场黑屏到秋叶原
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	novel_interface.change_music("res://assets/audio/music/Brooklyn.mp3")
	await novel_interface.show_text_only("贝阿特丽切拿着麦克风，一只脚踩在护栏上。")
	await novel_interface.show_text_only("功率全开的音箱将她的声音传遍了整个电器街。")
	novel_interface.show_character("beatrice_regular", "angry")
	await novel_interface.show_dialog("你们这群渣滓——", "贝阿特丽切")
	await novel_interface.show_dialog("不折不扣的变态！！", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("诶？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform", "jest", 0.25)
	await novel_interface.show_dialog("哦呀呀……", "索娅")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（是、是为了转移注意力才这么说的吧……？）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("贝阿特利切的劲爆发言果然使人们将目光纷纷转向了她。")
	await novel_interface.show_text_only("她看着车下面那群张着嘴仰着头，对自己红色高跟鞋底和短裙阴影浮想联翩的家伙——")
	novel_interface.show_character("beatrice_regular", "bored")
	await novel_interface.show_dialog("你们这帮社会垃圾、又脏又臭的虫子！其实一直都等着被踩死的那一天吧？", "贝阿特丽切")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("——你们不觉得羞耻吗！？", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "panic")
	await novel_interface.show_dialog("（怎、怎么听着像是积怨已久的爆发……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("多数人的注意力都被她吸引过去，连其他花车上唱唱跳跳的吉祥物也停了下来。")
	await novel_interface.show_text_only("我和索娅抓住空档钻进去，顺着花车侧面的楼梯摸到车顶，一眼就看到了伊露卡。")
	await novel_interface.show_text_only("她正坐在神龛的御座上，一脸满足的摸着自己鼓成小山的肚子，面前的贡台上还散落着几十个空盘。")
	novel_interface.show_character("ren_fishnet", "upset")
	await novel_interface.show_dialog("这些……都是她吃的吗！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我环视四周，盘算着要如何神不知鬼不觉的把这个小吃货带走，却没注意伊露卡已经扑了过来。")
	novel_interface.show_character("iluka_uniform", "smile")
	await novel_interface.show_dialog("小怜姐姐~！！", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我紧张的扭过头，想做出“嘘”的动作示意她小点声——")
	await novel_interface.show_text_only("却发现她已经高高跃起，正张开手脚，从半空朝着我的面部下坠……")

	# scene2 - 回忆场景
	novel_interface.change_background("res://assets/images/bg/Soya/Recall.png")
	await novel_interface.show_text_only("对啊，回想第一次见到伊露卡的时候，她就在半空中和女巫战斗吧……")
	await novel_interface.show_text_only("后来爱衣为她检查过的结论是：骨龄在11到12岁左右，身体接受过大量的机械改造。")
	await novel_interface.show_text_only("而且经历过多次记忆消除，甚至连自己的左眼什么时候被替换成了军用电子义眼都不记得。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("还有一点就是——虽然她可以利用电磁场漂浮在半空，但实际体重却接近我的两倍……")
	# scene3 - 回到秋叶原
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	await novel_interface.show_text_only("咔——")
	await novel_interface.show_text_only("伊露卡从空中落下，双腿夹住我的两肋，鼓起的肚子贴在我的脸上，而两只手则紧紧抱住我的后颈。")
	await novel_interface.show_text_only("我的颈椎、腰椎和肩膀瞬间感到了巨大的压力。")
	await novel_interface.show_text_only("她用整个身体包住了我的胸和头，还很开心的在我的头顶蹭着脸蛋。")
	novel_interface.show_character("iluka_uniform", "smile")
	await novel_interface.show_dialog("诶嘿嘿，最喜欢小怜姐姐了嗝~", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡红着脸说话吱吱呜呜，好像喝醉了一样。")
	novel_interface.show_character("soya_uniform", "afraid")
	await novel_interface.show_dialog("你的骨头……刚才好像发出了奇怪的声音？", "索娅")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_fishnet", "wail")
	await novel_interface.show_dialog("…………………………", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我僵直的站在原地，总觉得随便移动的话头会失去颈部的支撑向后翻过去。")
	await novel_interface.show_text_only("刚才的动静似乎引起了一些人的注意，还有声音朝着我们问“那是什么？”。")
	await novel_interface.show_text_only("那是一只穿着渔网袜的蓝色大头怪。")
	await novel_interface.show_text_only("贝阿特丽切见状突然提高了音调，像是在为我们争取最后的撤离时间。")
	novel_interface.show_character("beatrice_regular", "angry")
	await novel_interface.show_dialog("你们这群满脑子都龌龊幻想的垃圾！杂种！变态！猪！", "贝阿特丽切")
	await novel_interface.show_dialog("全都给我——", "贝阿特丽切")
	await novel_interface.show_dialog("去死吧！！！！", "贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("骂到高潮时刻，那两台大功率音箱也终于顶不住发出了尖锐的爆音。")
	await novel_interface.show_text_only("喇叭正对着广告灯箱里的灯管“啪！啪！”的炸裂开来。")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("——整个电器街一片诡异的宁静。")
	await novel_interface.show_text_only("人们对着花车上英姿勃发的红发女王看得发懵。")
	await novel_interface.show_text_only("索娅费了好大劲才把年糕一样糊在我脸上的伊露卡扒下来背在自己背上。")
	await novel_interface.show_text_only("而她这会功夫居然已经呼呼的睡着了。")
	novel_interface.show_character("soya_uniform", "afraid")
	await novel_interface.show_dialog("这小鬼……居然这么沉——！", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("终于松了口气的我揉着腰观察四周，大家沉默的氛围着实让人不安。")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("不会把他们骂急眼了吧……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然而片刻之后，一阵骚动由远及近的传来——")
	novel_interface.change_music("res://assets/audio/music/Brooklyn.mp3")
	await novel_interface.show_dialog("“啊啊啊啊啊啊好棒！！！！”","路人A")
	await novel_interface.show_dialog("“请尽情的辱骂我吧！！！！”","路人B")
	novel_interface.show_character("ren_fishnet", "stare")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("接着，整条电器街爆发出了一浪又一浪的狂欢！！")
	await novel_interface.show_text_only("——人群，彻底沸腾了。")
	await novel_interface.show_text_only("街对面的黑色装甲车上跑下来一群拿着自动武器的士兵，一脸困惑的看着这边突然暴动的人群。")
	await novel_interface.show_text_only("我想提醒贝阿特丽切，指了指街对面，却不小心看到了她的脸——")

	# scene4 - 被美色迷惑
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN1.png")
	novel_interface.show_character("ren_fishnet", "timid")
	await novel_interface.show_dialog("糟——", "小怜")
	novel_interface.change_expression("heart")
	await novel_interface.show_dialog("………好、好漂亮！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看到她脸的一刹那，我顿时感觉小腹中一股温热的暖流传遍全身。")
	await novel_interface.show_text_only("只觉两颊发烫、双腿酥软……")
	novel_interface.show_character("ren_fishnet", "heart")
	await novel_interface.show_dialog("（好想——）", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform", "speechless", 0.25)
	await novel_interface.show_dialog("……小怜？", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("人们的情绪随着有节奏的欢呼声越来越激烈，贝阿特丽切的花车也被推得摇晃起来。")
	await novel_interface.show_text_only("几个家伙试图从侧面爬上车顶，纷纷被她对着面门一脚踹下去。")
	novel_interface.show_character("ren_fishnet", "heart")
	await novel_interface.show_dialog("（好想被踩啊~！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她看着我犯花痴的蠢样微笑着摇摇头，重新扣上了那个手环。")
	await novel_interface.show_text_only("然后她从胸部抽出一个拇指大小的银色胶囊，猛然朝着自己脚下一丢——")
	await novel_interface.show_text_only("一阵白烟过后，贝阿特丽切已消失得无影无踪。")
	# scene5 - 逃跑
	novel_interface.show_background("res://assets/images/bg/Soya/AkihabaraNN.png")
	await novel_interface.show_text_only("我还沉浸在刚才粉红色的感觉中，忽然被索娅一把拉住了手腕。")
	novel_interface.show_character("ren_fishnet","heart")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soya_uniform", "yell", 0.25)
	await novel_interface.show_dialog("楞什么呢！军队都要过来了，而且……", "索娅")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("烟雾散尽，失去焦点的众人原本节奏整齐的声浪渐渐凌乱。")
	await novel_interface.show_text_only("我和索娅带着伊露卡跑出没多远，就有亲卫队发现他们刚才顶礼膜拜的大萌神也不见了。")
	await novel_interface.show_dialog("“伊露卡大人呢！？”","亲卫队A")
	await novel_interface.show_dialog("“在那边！那个渔网袜把伊露卡大人拐跑了！”","亲卫队B")
	novel_interface.show_character("ren_fishnet", "wry_smile")
	await novel_interface.show_dialog("（渔网袜？伊露卡……大人？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("“是诱拐犯吗？快叫警察！”","亲卫队C")
	await novel_interface.show_dialog("“追啊——！！”","亲卫队A")
	await novel_interface.show_text_only("一大群穿着应援服的家伙义愤填膺的朝着我们杀了过来，后面还跟着几个保安警。")
	await novel_interface.show_text_only("哪有穿渔网袜的诱拐犯啊！！")
	novel_interface.show_character("ren_fishnet", "perspire1")
	await novel_interface.show_dialog("快跑！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然而索娅背着伊露卡，我的腰还在隐隐作痛，根本无法甩开距离。")
	await novel_interface.show_text_only("而且前面似乎还有一组巡警在向这边张望……")
	await novel_interface.show_text_only("打又不能打，跑又跑不动，简直是绝境。")
	await novel_interface.show_text_only("忽然，我们身后传来一阵玻璃碎裂的声音。")
	await novel_interface.show_text_only("一个穿着黑色风衣的金发男生放倒了路边的老式广告灯箱。")
	await novel_interface.show_text_only("周围环绕的圆形灯泡碎了一地，慌忙闪躲的路人挡住了后面亲卫队的视线。")
	await novel_interface.show_text_only("那个男生转过头看着我和索娅，露出一个人畜无害的笑容——")
	novel_interface.show_character("john", "smile")
	await novel_interface.show_dialog("前面有小路，我带你们走吧？", "戴眼镜的男生")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我和索娅面面相觑，这是在模仿某部电影吗？")
	await novel_interface.show_text_only("戴眼镜的男生一头蓬松的金发，穿着格子衬衫，碧蓝色的眼睛透着腼腆的感觉。")
	await novel_interface.show_text_only("他看我们没有回应，有点难为情的解释道。")
	novel_interface.show_character("john", "shy")
	await novel_interface.show_dialog("我、我在附近的店打工刚下班……", "戴眼镜的男生")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("他眼神游移到我的腿上，又很快把头转向旁边。")
	novel_interface.show_character("ren_fishnet", "uneasy")
	await novel_interface.show_dialog("（好吧，果然不能用这种方法偷瞄女生……）\n（实在太明显了……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("john", "smile")
	await novel_interface.show_dialog("看到你们……好像在被坏人追？", "戴眼镜的男生")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("索娅稍稍松口气，放松了戒备。")
	novel_interface.show_character("soya_uniform", "smile")
	await novel_interface.show_dialog("嘛……他的气息没有恶意。", "索娅")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然从各种意义上，我们才是坏人。")
	novel_interface.show_character("soya_uniform", "jest")
	await novel_interface.show_dialog("快带路吧~", "索娅")
	await novel_interface.hide_character()
	
	print("=== 天启篇第12话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
