# side01_ep1.gd - 侧边故事01第1话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	side01_ep1_script()

func play_script():
	pass

func side01_ep1_script():
	await novel_interface.show_text_only("现在即将发生的、亦或是过去也许发生过的可能性存在着无数种。")
	await novel_interface.show_text_only("这无数的可能性不断的跨越无数的世界，将世界拉伸的无限宽广。")
	await novel_interface.show_text_only("那么存在于无数个世界中的『真实』……是什么？")
	await novel_interface.show_text_only("就像沉入黑夜中的镜子，虽然可以触摸它，可以抚摸它。")
	await novel_interface.show_text_only("但其中所映射的内容…是否还与平时相同呢。")
	await novel_interface.show_text_only("镜中的一切…他们存在着怎么样的意志？")
	await novel_interface.show_text_only("Δ13 SID作战指挥室")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("气氛紧张的作战指挥室中，数块全息屏幕正不停轮放着讯息。")
	await novel_interface.show_text_only("一位身形娇小的银发少女此刻目光正紧紧盯着闪烁不停的荧幕，并不时发出淡淡的叹息。")
	await novel_interface.show_text_only("这时门禁发出“滴—”的清脆音效，随后一行身着各异的少女走进指挥室中。")
	novel_interface.show_character("kin")
	await novel_interface.show_dialog("报~告~魔女小队集结完毕！", "芩")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("为首持有双刀的少女朝着对方，十分娇俏可爱的敬了个礼。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("辛苦了，芩。很抱歉打断大家的休假…", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣微微沉下头稍作停顿之后，似乎又鼓足了勇气目光如炬的注视着众人。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("这次之所以会急匆匆召集大家，是因为有一件原本被判定为『Safe』级的异质物突然被唤醒。", "爱衣")
	await novel_interface.show_dialog("突然被唤醒的原因我们还没能掌握，但它在脱离收容前的危险等级已经攀升至…『EX』级。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","perspire")
	await novel_interface.show_dialog("什…什么！？", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("啊…听起来就超麻烦的…我今天可还没睡够15个小时啊……", "瑟蕾莎")
	await novel_interface.hide_character()
	novel_interface.show_character("heinrich_battle","mock")
	await novel_interface.show_dialog("异质物还存在着这种形式的变化啊…倒是有趣。", "海因里希")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("就在少女们议论纷纷时，其中最为娇小的一位拽了拽一直紧紧跟在她身边气质优雅的少女。")
	novel_interface.show_character("iluka_normal","gourmet")
	await novel_interface.show_dialog("呐，倪克斯姐姐……", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("紫发的优雅少女俯下身，充满怜爱得抚摸着伊露卡的头发。")
	novel_interface.show_character("iluka_normal","gourmet")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nyx_full","smile",0.25)
	await novel_interface.show_dialog("伊露卡不用担心，无论发生什么姐姐都会保护你\n的。", "倪克斯")
	novel_interface.character_light(0.35,"hungry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("巧克力…再来一块…", "伊露卡")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("接着少女舔掉了嘴角的巧克力。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("……咳，请诸位安静一下。", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣触碰了一下屏幕，屏幕马上开始显示出一只金黄色的杯状器物。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("目标异质物于23时被发现收容失效。", "爱衣")
	await novel_interface.show_dialog("其外形通体金色且镶有难以分离的宝石，形似宗教传说中所描述的圣杯。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("唔……圣杯？", "斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德双眉紧蹙，似乎若有所思的用手托着下\n巴。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("斯库尔德小姐，你能察觉到什么吗？", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("抱歉，自从上次的事之后我的能力就很不稳定…", "斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("嗯，那也没办法了。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("不过这件异质物的特别之处就是，它虽然有着形似传说中圣杯的外形，但其内部始终承装着天妇罗…", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女一行人的动作突然凝固下来，似乎一时间还难以接受这样的设定。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("准确的说…是炸虾和炸鱿鱼两种天妇罗。", "爱衣")
	await novel_interface.show_dialog("而且就算是从中全部取空，只要杯体脱离取出人的视线就会自动填满。", "爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("除此之外并没有其他特别的性质，所以一直被判定为『Safe』级。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("kin")
	await novel_interface.show_dialog("哟吼~如果里面的天妇罗可以吃的话，老朽可就势在必得了啊~", "芩")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("回过神的芩突然挽了一下袖子，两眼放光十分有精神的做出了宣言。")
	novel_interface.show_character("emilio","shout")
	await novel_interface.show_dialog("肯定不行的吧…那种从异质物内部突然出来的奇怪东西。", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("事实上…经常会有收容管理人员试图“品尝”一下里面的炸物。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","worry")
	await novel_interface.show_dialog("真是值得称赞的勇气…然后呢。", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("然后也就是今晚22时，某位D级探员偷吃了一枚炸虾天妇罗之后一切就陷入了异常。", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣说着开始操作起面前的终端，屏幕上的内容也马上变为监控摄像头所拍下的画面。")
	await novel_interface.show_text_only("画面中，一位手提着一打可乐的少年走进存放着\n『Safe』等级的异质物收容区。")
	await novel_interface.show_text_only("只见他悠哉悠哉的将一台有红蓝双色手柄的游戏设备放到一边支起，然后对屏幕点了“下一回合”")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("接着他就以研究用途取出了天妇罗锅。", "爱衣")
	await novel_interface.show_dialog("对于『Safe』等级的异质物的收容我们还存有漏洞……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("或许是对收容设施外部安保的自信，被判定为『S\nafe』等级的异质物并没有额外的保全手段。")
	await novel_interface.show_text_only("少年熟练地解除了收容限制并夹出其中最大的一枚炸虾，然后一边大快朵颐一边玩起游戏。")
	await novel_interface.show_dialog("『下一回合』这种按钮真是有毒——嗝！", "屏幕中的少年")
	novel_interface.show_character("kin")
	await novel_interface.show_dialog("…怎么说呢，这个吃相还真是豪放，蛮可爱的呐！", "芩")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","normal")
	await novel_interface.show_dialog("炸虾…吸溜……", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("快进入重点啦，瑟蕾莎这家伙都要睡着了！不对，这不是已经睡着了吗！！", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","blink")
	await novel_interface.show_dialog("啊…啊！我、我没……呲溜", "瑟蕾莎")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_full","sad")
	await novel_interface.show_dialog("伊露卡…不要像那边那个没出息的姐姐一样总吸口水…", "倪克斯")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("艾米艾米，这家伙是可口党哎！和你一样呢！", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","mock")
	await novel_interface.show_dialog("嗯…不过我现在已经改喝少糖的怡泉啦！", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("好啦好啦，你们这些家伙精力这么旺盛的话，下次都来协助我的实验啊…", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("…………", "众人")
	await novel_interface.show_text_only("少女们马上一副心领神会的表情安静下来。")
	await novel_interface.show_text_only("在经过数个『下一回合』后，享受到瘫坐一团的少年突然站起，双眼无神的仰望着前方。")
	await novel_interface.show_text_only("这时大家才注意到，原本留在收容设备内的天妇罗锅正漂浮在半空中。")
	await novel_interface.show_text_only("锅体外的宝石如跑马灯般轮番闪烁，放射出的光芒将整个室内气氛照射得越发诡异。")
	await novel_interface.show_text_only("众人紧紧盯着屏幕中少年下一步的举动。")
	await novel_interface.show_dialog("如果，如果说……", "屏幕中的少年")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_dialog("真的有『神』存在的话。", "屏幕中的少年")
	novel_interface.show_character("skuld","perspire")
	await novel_interface.show_dialog("……！？", "斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("我希望…", "屏幕中的少年")
	await novel_interface.show_dialog("我希望……！", "屏幕中的少年")
	await novel_interface.show_dialog("我希望现在就玩到赛博朋克30XX！！", "屏幕中的少年")
	await novel_interface.show_text_only("话音刚落监控画面就剧烈的闪烁起来，在十几秒的闪烁和雪花过后画面又归于正常。")
	await novel_interface.show_text_only("收容室内依旧如同之前一般的风平浪静，但原本漂浮在半空的『天妇罗锅』和少年都已消失不见。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("所以就是…这个女装变态一样的家伙偷走了你们收容的宝贝吗？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("不，他并不是入侵了监视系统或者躲进监控死角，而且他没穿女装。", "爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("所有收容设施内的人员和异质物都有进行标记追踪", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("那个赛博朋克30XX是一款游戏的名字呢…", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","smile")
	await novel_interface.show_dialog("不愧是薇拉~是最近新出的游戏吗？", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("嗯…差不多几十年后会出的新游戏吧……！", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("果然…这样推测就成立了。", "爱衣")
	novel_interface.change_expression("blush_dizzy")
	await novel_interface.show_dialog("我们怀疑…画面中的探员与圣杯… 啊不天妇罗锅…做了某种的交易，或是说契约。", "爱衣")
	await novel_interface.show_dialog("探员吃掉了由它产生的炸物，与它产生连接…而它允诺探员可以实现某种愿望。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("哈……简直和许愿机一样真是可笑。", "拉斐尔")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("不管是奇迹还是魔法都不可能是免费的吧。", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_think")
	await novel_interface.show_dialog("正是如此，这位少年希望的是提前玩到这款未发售的游戏，但它的回应方式…", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_battle","worry")
	await novel_interface.show_dialog("是将他送到了未来……？", "贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_wink")
	await novel_interface.show_dialog("没错。", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣朝贝阿特丽切点点头以示确认。")
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("任性又乱来啊……", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("kin")
	await novel_interface.show_dialog("呜姆…这种事老朽倒是闻所未闻。", "芩")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("天妇罗锅似乎会以某种方式判断『许愿者的价值』和『愿望的价值』。并将二者置于天秤进行比较。", "爱衣")
	await novel_interface.show_dialog("视频中探员是以最容易的方式实现了愿望——被丢到未来去玩刚刚发售的游戏。", "爱衣")
	novel_interface.change_expression("blush_think")
	await novel_interface.show_dialog("但如果存在想要世界毁灭的愚蠢家伙，天妇罗锅会说不定先杀掉许愿者。", "爱衣")
	await novel_interface.show_dialog("然后在世界范围内随机挑选等同价值的人一起陪\n葬。", "爱衣")
	novel_interface.change_expression("blush_dizzy")
	await novel_interface.show_dialog("甚至…真的可能出现改写历史进程的家伙。", "爱衣")
	await novel_interface.show_dialog("SID必须确保自己所有的收容物都不能对一般大众造成伤害！", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("众人很明显的能感觉到，爱衣虽然名义上说着是保护大众。")
	await novel_interface.show_text_only("但比起那些事，她对产生这种特殊性质的异质物有着更狂热的兴趣。")
	novel_interface.show_character("emilio","speechless")
	await novel_interface.show_dialog("不过既然它已经消失了，还会有这种担心吗？", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("和少年彻底消失的信号不同，『天妇罗锅』的信号是在新丰洲市范围内分裂为了更多个。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("nantetsu","speak")
	await novel_interface.show_dialog("MD的特遣部门已经把目前掌握的情报同步过来\n了。", "南哲")
	await novel_interface.hide_character()
	novel_interface.show_character("cereza","uneasy")
	await novel_interface.show_dialog("……！？那个肌肉男就一直站在爱衣旁边吗！……", "瑟雷莎")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","speechless")
	await novel_interface.show_dialog("哦…！哦……！忍者先生……！", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("emilio","shout")
	await novel_interface.show_dialog("薇拉…", "艾米莉欧")
	await novel_interface.hide_character()
	novel_interface.show_character("valkyrja","shy")
	await novel_interface.show_dialog("…我也完全没注意到那里有人。", "薇拉")
	await novel_interface.hide_character()
	novel_interface.show_character("nantetsu","smile")
	await novel_interface.show_dialog("…………抱歉。", "南哲")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一直站在爱衣不远处却完全未被发现的筋肉军官只能挤出一个爽朗的笑容。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("虽然不知道你在道歉什么，但是感觉太可怜了。", "拉斐尔")
	await novel_interface.show_dialog("爱衣小姐，请继续吧。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("咳…MD传回的讯息已经证实了虽然天妇罗锅本体已经消失。", "爱衣")
	await novel_interface.show_dialog("但其中的炸物正四散在新丰洲市内的各个角落里。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","proud")
	await novel_interface.show_dialog("说不定它是在寻找那个…可以“改写历史”的人\n喔。", "斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("也许正是这样，为了避免这种情况魔女小队必须马上出发取回所有『炸虾天妇罗』和『鱿鱼天妇罗』", "爱衣")
	await novel_interface.show_dialog("根据MD的情报，天妇罗也吸引了大量失控的『女巫』聚集。", "爱衣")
	await novel_interface.show_dialog("行动过程中SID异质物回收科会与MD灾厄行动小组一同为魔女小队提供支援。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("芩，你与斯库尔德、贝阿特丽切、倪克斯，伊露卡一队并负责现场指挥。", "爱衣")
	await novel_interface.show_dialog("艾米莉欧，你和拉斐尔、瑟蕾莎、薇拉，海因里希作为另一队分头行动。", "爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("更详细的作战情报会在路上传达给大家。", "爱衣")
	novel_interface.change_expression("blush_dizzy")
	await novel_interface.show_dialog("现在马上出发！把东西给我抢回来！！", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是！", "众人")
	await novel_interface.stop_music()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………")
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("大概就是这样的情况了……", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("（本想通过观测平行世界对未来的作战提供更多情报）", "莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("（结果都是些奇奇怪怪的东西啊……）", "莉琉")
	await novel_interface.show_dialog("（下次观测……只能一年后了吗）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("哈…那个世界好像都没有我存在的样子啊。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("嗯…", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("（八成那个偷吃炸虾的人就是“另一个”小怜吧）", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("（我和小怜在那个世界…没能“活下来”吗？）", "莉琉")
	await novel_interface.show_dialog("（所以爱衣成为了SID的“Madam”…）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("不过照莉琉小姐的描述，“魔女小队”里有很多从未听说过的人呢。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("世界线收束的影响下，小怜大概率会与她们相遇\n的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("唔……那按照这个说法，她们应该都是我们的友方吧！", "小怜")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("完全不想和她们产生暴力冲突啊……啊哈哈。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("不能这么说啊~毕竟被卸掉两条腿爱衣也有办法装回去，不会影响到世界线的走向。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("卸、卸掉…？！想想就疼死了啊！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","hungry")
	await novel_interface.show_dialog("哦…！腿是装饰！", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("好啦~莉琉姐和伊露卡今天就不要一直欺负小怜了吧~", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("是呢~今天可是小怜的“好日子”啊~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("斯库尔德和拉斐尔都来的话…法贝拉和瑟蕾莎也会来吧！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("嗯，贝阿特丽切迟一些也会到场，白烛也给你发过信息吧。", "莉琉")
	await novel_interface.show_dialog("没想到才过了这么一点时间…小怜也算是“后宫成群”了吧？", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("嗯哼~还真有点…“魔女小队”的意思哦？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("噫…那个说法不知道为什么超羞耻，所以请不要再说了！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","gourmet")
	await novel_interface.show_dialog("姆…小怜姐姐…该出发了…", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮抱过伊露卡，仔细的擦掉少女嘴角的巧克力。")
	await novel_interface.show_dialog("呐，莉琉姐？", "小怜＆安妮")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("好~！我们现在就出发！", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("今晚一定不醉不归啊！！", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("我们根本不能喝酒吧！！！", "小怜")
	await novel_interface.stop_music()
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("Δ？？ 未知地点")
	novel_interface.change_music("res://assets/audio/music/Chaostic Daily.mp3")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("可恶的SID狗……竟敢一次次阻挠我。", "雅各")
	await novel_interface.show_dialog("你这家伙，再表演一下那个！", "雅各")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("soldier_leader","",0.25)
	await novel_interface.show_dialog("嗯？！还要来吗！！", "蒙面人首领")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("对，就那个，快点！", "雅各")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("………………", "蒙面人首领")
	await novel_interface.show_dialog("就由我来分离，这不洁之物！！", "蒙面人首领")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("HAHAHAHA", "蒙面人首领＆雅各")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("就由我来分离，这不洁之物！！！！", "蒙面人首领")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("HAHAHAHAHAHAHA", "蒙面人首领＆雅各")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("就由我来分离，这不洁之物！！！！！！！！", "蒙面人首领")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("HAHAHAHAHAHAHAHAHAHAHAHAHA", "蒙面人首领＆雅各")

	print("=== 侧边故事01第1话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
