# imperialpresence_ep01.gd - 帝国临在篇第1话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	imperialpresence_ep01_script()

func play_script():
	pass

func imperialpresence_ep01_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Versailles_BR_AuG.png")
	await novel_interface.show_text_only("咚咚咚……！！\n咚咚咚……！！")
	await novel_interface.show_text_only("雕刻繁复精美的木质大门传出一阵急促的敲击声，镶在门板上的镀金包边被震得有些松动。")
	await novel_interface.show_dialog("奥古斯塔陛下，请不要让我们为难。", "侍卫长")
	await novel_interface.show_text_only("一个低沉的男声说道——")
	await novel_interface.show_dialog("宰相大人的命令，请您尽快前往镜厅。", "侍卫长")
	await novel_interface.show_dialog("弗雷德里希大公和他的长子已经等候多时了……", "侍卫长")
	await novel_interface.show_text_only("门外男性的话语，在保持着恭敬的同时透出一种强制和威胁的味道。")
	novel_interface.show_character("augusta","worry")
	await novel_interface.show_dialog("嘁——", "奥古斯塔")
	await novel_interface.show_dialog("连我的禁卫都被换掉了吗……", "奥古斯塔")
	await novel_interface.show_text_only("金发少女眉头微皱，她正了正领口，看着卧室墙边巨大更衣镜中的自己，握紧了手中的权杖——")
	await novel_interface.show_text_only("这是她身为国家最高元首和军队最高统帅的象征。")
	await novel_interface.show_dialog("（至少是在名义上……）", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("当下，那些贵族和大臣们还不能撤掉这个他们在几年前强加给自己的头衔。")
	await novel_interface.show_text_only("虽然这更像是她一直都试图摆脱的枷锁。")
	await novel_interface.show_text_only("每当奥古斯塔以这样的身份和姿态出现在战争动员会或阅兵式上，人们便会立刻兴奋起来——")
	await novel_interface.show_text_only("那些年轻的士兵，好像迫不及待的想沉浸在虚假的概念和符号带来的满足感和认同感里。")
	await novel_interface.show_text_only("她一直都无法理解，为什么总有些人会在那种氛围下激动到热泪盈眶，争相发誓要永远效忠。")
	await novel_interface.show_text_only("她也无法认同，一群素不相识的人只因自己继承了某种血脉，就恨不得立刻为她上前线赴死。")
	await novel_interface.show_text_only("然而那些廉价的忠诚和热血就如恋人的誓言，当战争结束激情退去，便迅速被抛在脑后。")
	await novel_interface.show_text_only("现在奥古斯塔只能孤身一人，面对那扇被缓缓打开的大门……")
	await novel_interface.show_text_only("虽然握着权杖的手在隐隐发抖，但她依然鼓足勇气挺起自己娇小的身躯。")
	await novel_interface.show_dialog("陛下——", "侍卫长")
	await novel_interface.show_text_only("面色灰白的侍卫长推开卧室大门，奥古斯塔感到一股寒意涌来。")
	await novel_interface.show_dialog("您一会要去见自己的未婚夫，却还穿着军装，是想挑衅邦国制造外交事故吗。", "侍卫长")
	novel_interface.show_character("augusta","shout")
	await novel_interface.show_dialog("少废话——！！", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("侍卫长疏离冷淡的语气让少女心中莫名火大，她一边怒斥一边用权杖底部敲击着地板。")
	novel_interface.show_character("augusta","serious")
	await novel_interface.show_dialog("居然要我嫁给魏玛大公的那个笨蛋儿子……", "奥古斯塔")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("不怕婚礼当天我在所有人面前把他宰了吗？！", "奥古斯塔")
	await novel_interface.show_dialog("跟俾斯麦说，让她自己嫁给大公的瘸腿小舅子去！", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("侍卫长平静的注视着激动的奥古斯塔，片刻之后，转身对门口的女仆冷冷的吩咐道——")
	await novel_interface.show_dialog("玛丽亚，你和这几个女官帮陛下更衣。", "侍卫长")
	await novel_interface.show_text_only("为首的女仆赶忙答应，张罗着另外几个女仆将挂着淡蓝色蕾丝晚礼服的推车推进卧室。")
	await novel_interface.show_text_only("侍卫长回到走廊对两旁的人使了个眼色，几个女官分成两列进入卧室。")
	await novel_interface.show_text_only("那些女官的制服裸露着胳膊，所有人都有一幅明显受过专业作战训练的矫健身形。")
	novel_interface.show_character("augusta","worry")
	await novel_interface.show_dialog("你、你们……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔后退几步，女官们步步紧逼。")
	await novel_interface.show_text_only("侍卫长回避到走廊上，淡然的望向窗外花园中整齐的银杏树，完全无视卧室传出的阵阵叫骂声。")
	await novel_interface.show_text_only("虽然少女不停挥动着权杖，却还是被一步步逼到墙角——")
	await novel_interface.show_text_only("奥古斯塔意识到已没有退路，将权杖大力戳在地板墙壁的拐角处，打算做最后的抵抗。")
	novel_interface.show_character("augusta","worry")
	await novel_interface.show_dialog("都给我……", "奥古斯塔")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("滚开！！！！", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("咯——\n咔咔——！！！！！")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	novel_interface.show_background("res://assets/images/bg/Versailles/BG_Versailles_BR_Shake_AuG.png")
	await novel_interface.show_text_only("忽然，地板从权杖撞击的地方出现一个裂痕，并很快向四周蔓延出无数进发着强光的裂缝。")
	await novel_interface.show_text_only("大地好似被某种巨大的力量挤压和撕扯，发出阵阵低沉的轰鸣，周围的空间也跟着变形扭曲。")
	await novel_interface.show_text_only("奥古斯塔看着几个女官的身体似乎被弯曲到不可思议的角度，她们却似乎并没有察觉")
	await novel_interface.show_text_only("同时房间内的空气似乎也瞬间变得稀薄起来，她感到呼吸困难，各种声音似乎都被拉得很远——")
	novel_interface.show_character("augusta","worry")
	await novel_interface.show_dialog("什么……？！", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着几个女仆尖叫着跑出卧室，侍卫长立刻冲回房内。")
	await novel_interface.show_dialog("怎么回事！！？", "侍卫长")
	await novel_interface.show_text_only("在他踏入大门的一瞬间，整个房间就像被拉到极限的弓弦般——")
	await novel_interface.show_text_only("所有扭曲的光影汇聚于一点，房里的光芒也忽然暗淡下来……")
	await novel_interface.show_text_only("门外一个女仆满脸惊恐的瘫在地上，口中不断念着祈求神明拯救和宽恕的悼词。")
	await novel_interface.show_text_only("巨大的不祥感降临在在场所有人心中。")
	await novel_interface.show_text_only("眼前的一切似乎都是在准备迎接某种远古邪恶存在的降临。")
	await novel_interface.show_text_only("片刻沉寂之后，汇聚的黑点猛然炸裂开来。巨大的冲击席卷了目力所及的一切事物。")
	await novel_interface.show_text_only("女仆、女官和侍卫长都感到灵魂在一刹那被震出体外，堕入了虚无之中。")
	await novel_interface.show_text_only("魁梧的侍卫长如被风吹掉的枯叶般，毫无抵抗能力得倒了下去")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("房间内的光芒渐渐暗淡下来。")
	novel_interface.show_background("res://assets/images/bg/Versailles/BG_Versailles_BR_Summon_AuG.png")
	await novel_interface.show_text_only("奥古斯塔睁大眼睛瘫坐在地上，呆呆的看着地上躺倒的几个女官，门外的侍卫长也全然没了动静。")
	await novel_interface.show_text_only("爆发过后，房间内的光芒渐渐向墙角最初开裂的那个点收敛，一个扭曲的身影在强光中浮现。")
	await novel_interface.show_text_only("影子的轮廓逐渐清晰，似乎是个人形")
	novel_interface.show_character("augusta","shock")
	await novel_interface.show_dialog("这、这是……？", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她的心脏一阵狂跳，看着这不可思议的一幕——")
	await novel_interface.show_text_only("那个生物的头和上半身顶在墙角的地板上，躯干和臀部紧贴墙壁呈倒立的姿势向上。")
	await novel_interface.show_text_only("两条腿大喇喇的悬空岔开，裙子自然下垂，露出蓝白条纹的……")
	await novel_interface.show_text_only("奥古斯塔还没来得及看清，那贴在墙壁上的躯干似乎无力继续支撑，顺着墙壁向一侧倒了下去。")
	await novel_interface.show_text_only("少女握紧权杖，看着上面繁复华丽的纹样，忽然冒出一个奇异的念头——")
	novel_interface.show_character("augusta","shock")
	await novel_interface.show_dialog("难道是……被我召唤出来的吗？", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("召、召唤兽？")
	await novel_interface.show_text_only("她想试着用权杖的尖端戳一下那个生物，对方突然发出一声长长的悲鸣——")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("呜……………………", "小怜")
	await novel_interface.show_dialog("到底……", "小怜")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("怎、怎么回事啊啊啊……？？！！！", "小怜")

	print("=== 帝国临在篇第1话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
