# imperialpresence_ep05.gd - 帝国临在篇第5话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	imperialpresence_ep05_script()

func play_script():
	pass

func imperialpresence_ep05_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("巴黎郊外，伊芙琳省某处。")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_CountryRoad_AuG.png")
	await novel_interface.show_text_only("呼——呼——\n哈……")
	await novel_interface.show_text_only("我刚才像一辆失控的重型卡车，撞飞了数十名士兵和好几道路障。")
	await novel_interface.show_text_only("直到逃离那里之后，我才回望确认身后的建筑物就是凡尔赛宫。")
	await novel_interface.show_text_only("虽然不知当时跑得有多快，但那绝对是常人无法企及的速度——")
	await novel_interface.show_text_only("迎面的风吹得我睁不开眼，而身后追击的车队不一会就被甩得没影了。")
	await novel_interface.show_text_only("奥古斯塔全程紧闭双眼缩在我怀中，搂着我的脖子不肯松手……")
	await novel_interface.show_text_only("我从没试过跑步时双腿甩开那么大角度，甚至有段时间，校服的裙子完全翻上去了。")
	novel_interface.show_character("ren_uniform","shy_left")
	await novel_interface.show_dialog("（那种丢人的姿势……快点给我忘掉啊！！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在跑到这条乡间小路之后，我的速度终于降到了近乎散步的水平。")
	await novel_interface.show_text_only("奥古斯塔也在刚才如梦方醒的睁开了眼睛，一边跟我聊天一边四下观察。")
	novel_interface.show_character("ren_uniform","shy_left")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("augusta","panic",0.25)
	await novel_interface.show_dialog("咱们这是到哪了？", "奥古斯塔")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我还想问你呢……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("而且您是不是可以下来自己走了！")
	await novel_interface.show_text_only("奥古斯塔没理我，出神得盯着远处夕阳下的小镇看了好一阵，才伸手指向前方右侧的岔口。")
	novel_interface.show_character("ren_uniform","stare")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("augusta","happy",0.25)
	await novel_interface.show_dialog("去那边看看~", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("虽然我很想拒绝，但身体却很听话。")
	await novel_interface.show_text_only("我索性抬头望着天边被映成金红色的云霞，巴黎乡间的傍晚美得让人沉醉。")
	await novel_interface.show_text_only("这条路很安静，只有微风拂过树梢的声音。")
	await novel_interface.show_text_only("空气中混杂着青草和泥土的味道，隐约中还有股淡淡的汽油味。")
	await novel_interface.show_text_only("无论是远处石墙下被烧得焦黑的战车，还是路面上坑坑洼洼的被重型履带碾过的痕迹……")
	await novel_interface.show_text_only("都暗示着这里不久前才经历过一场战事。")
	await novel_interface.show_text_only("我在脑内默默整理了一下刚从奥古斯塔了解到的关于这个世界的情报——")
	await novel_interface.show_text_only("这里是1871年，我所知道的六座学园还不存在，或者说还都以它们原始的形态存在着。")
	await novel_interface.show_text_only("但不知为何，这边某些方面的技术已经达到了非常先进的水平——比如铁路、汽车、飞机和互联网。")
	await novel_interface.show_text_only("连移动通讯和监控设备都大面积普及了，甚至还有卫星定位系统……")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("（似乎都是从军事技术转化而来的……？）", "小怜")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("话说你们才刚刚占领巴黎不久吧……就这么跑出来会不会有什么危险？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("augusta","smile",0.25)
	await novel_interface.show_dialog("放心吧~", "奥古斯塔")
	novel_interface.change_2nd_expression("gratified")
	await novel_interface.show_dialog("前一阵我们抵达这里的时候，本地的新闻标题是：\n“奥古斯塔陛下于今日抵达她忠诚的巴黎。”", "奥古斯塔")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("…………", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("完全没法让人放心啊！")
	novel_interface.show_character("augusta","happy")
	await novel_interface.show_dialog("而且本来统治这儿的就不是什么正统，我们已经宣布会将大部分领土交还给流亡近百年的法国王室。", "奥古斯塔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("流亡……近百年？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("augusta","happy")
	await novel_interface.show_dialog("就是那件事啊——\n大概一个世纪以前，1777年的一天……", "奥古斯塔")
	await novel_interface.show_dialog("凡尔赛宫上空被一团紫色的光芒笼罩，夜空被照得恍若白昼，全巴黎的人都目睹了那次异象。", "奥古斯塔")
	await novel_interface.show_dialog("光芒渐渐熄灭之后，原先驻守在凡尔赛宫内的军队\n、仆人、全部贵族以及皇室成员都消失了。", "奥古斯塔")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("根据禁卫军的记录，他们赶到的时候只看到几十名身着统一制服的陌生人，大多神情慌张。", "奥古斯塔")
	await novel_interface.show_dialog("那些奇怪的人召唤出了强大的人形生物，能像恶魔般随意扭曲自己的关节，迅速击溃了禁卫军。", "奥古斯塔")
	await novel_interface.show_dialog("然后那些人在更多援军到来前，迅速消失在了黑夜之中，从此音讯全无。", "奥古斯塔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","solemn")
	await novel_interface.show_dialog("（大规模失踪和……扭曲的人形生物？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我立刻想到了莱博娜巨蛋体育场，五万名观众同时消失的事件，安妮当时也被卷入了那场异变。")
	await novel_interface.show_text_only("而扭曲的人形生物难道是——")
	novel_interface.show_character("ren_uniform","solemn")
	await novel_interface.show_dialog("（女巫……？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("augusta","happy")
	await novel_interface.show_dialog("那件事导致异质物第一次为世人所知，同时也造成了法国几个革命派别和贵族的大混战……", "奥古斯塔")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("不过这些都是最基本的历史知识吧，你连这些都不知道吗？", "奥古斯塔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("我应该知道吗？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("augusta","panic",0.25)
	await novel_interface.show_dialog("别的召唤兽还挺有常识的，你怎么这么笨……", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她不满的白了我一眼。")
	await novel_interface.show_text_only("小丫头信不信我把你丢到地上！")
	novel_interface.show_character("augusta","gratified")
	await novel_interface.show_dialog("不过……还好。", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔轻声说道。")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("嗯？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("augusta","gratified")
	await novel_interface.show_dialog("召唤兽是强大的上古生灵，传说只会对拥有天命之人效忠，也是各国皇室遴选继承人的标准", "奥古斯塔")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("小时候皇兄死于意外，我被匆忙扶上皇位之后的质疑声就没停止过", "奥古斯塔")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("其实我也觉得自己没有资格，但又不敢承认……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔把头轻轻靠在我的胳膊上，轻声说道。")
	novel_interface.show_character("augusta","tear")
	await novel_interface.show_dialog("还好……", "奥古斯塔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我不知该如何回应。")
	await novel_interface.show_text_only("虽然还不清楚具体细节，但从她的反应看来，被召唤来的应该是本就属于这个世界的生灵。")
	await novel_interface.show_text_only("但我来自另一个世界啊……")
	novel_interface.show_character("augusta","happy")
	await novel_interface.show_dialog("放心吧——", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔好像看透了我的心思。")
	novel_interface.show_character("augusta","smile")
	await novel_interface.show_dialog("召唤兽只能在现世维持一小段时间，能量耗光后你就能回到自己来的地方。", "奥古斯塔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","panic",0.25)
	await novel_interface.show_dialog("能量是指？", "小怜")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("比如维多利亚女王的召唤兽是公认最强的，每次足以摧毁一辆战车。", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我刚才撞飞好几辆算不算……")
	novel_interface.show_character("augusta","happy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","panic",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("能量大概两亿焦耳左右。", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("等等，这边连焦耳他老人家也有吗？！")
	novel_interface.show_character("augusta","happy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_uniform","bored",0.25)
	await novel_interface.show_dialog("怎么快点把能量耗光啊……\n（那样我就能回去了吧？）", "小怜")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不知道……\n（刚才这一路早该耗光了……）", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("2037年，凡尔赛宫。")
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Versailles_BRM_AuG.png")
	await novel_interface.show_text_only("拉斐尔接过安妮的手机，上面是再普通不过的wiki页面。")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("时间之神『埃安』又称柯罗诺斯，他创造了宇宙的银蛋，银蛋孕育出了最初之神『法涅斯』……", "拉斐尔")
	await novel_interface.show_dialog("这个神话体系太古老了，现在没什么人知道了吧？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("你接着看下面~", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","smile")
	await novel_interface.show_dialog("『法涅斯』既是男性，也是女性……处于隐形的神性世界和突显的人性世界之间。", "拉斐尔")
	novel_interface.change_expression("perspire")
	await novel_interface.show_dialog("这个……\n难道说……是指那个女装癖？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔表情复杂的抬头看向安妮，发现安妮正以同样玩味的表情看着自己。")
	novel_interface.show_character("raphael","subtle")
	await novel_interface.show_dialog("柯罗诺斯将银蛋放入了夜之女神的体内……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……体、体内？？！")
	await novel_interface.show_text_only("拉斐尔惊异的将目光移向桌上的彩蛋，这东西的做那么小，难难难道是为了……")
	await novel_interface.show_text_only("安妮点了点头，做出一副“你懂了吧？”的表情。")
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("（莫莫莫莫莫莫莫莫莫莫非……？？！）", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔吞了吞口水，脸一下红到了脖子根，伸向彩蛋的右手有些颤抖。")
	await novel_interface.show_text_only("不料安妮先一步拿起了彩蛋，将它对着窗外的夕阳说道——")
	novel_interface.show_character("anne_uniform","unhappy")
	await novel_interface.show_dialog("传说中『法涅斯』诞生自含水的深渊，出生时撕裂了原有世界的黑暗状态……", "安妮")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("我们把它放到完全不透光的水箱中试试？", "安妮")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("嗯……？\n你的脸怎么那么红？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("——没什么！！\n这里太热了！！", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("我抱着奥古斯塔走进小镇。")
	await novel_interface.show_text_only("虽然被丢得满地的传单上再三保证军队不会征用居民财物，但镇上的居民还是跑光了。")
	await novel_interface.show_text_only("不愧是“陛下忠诚的巴黎”。")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Merrygoround_AuG.png")
	await novel_interface.show_text_only("天色渐暗，我们来到镇上的广场，四周的商店门口还挂着减价特卖的招牌。")
	await novel_interface.show_text_only("广场东侧有一座旋转木马，奥古斯塔让我将她放下来，至此我才终于恢复了对身体的控制。")
	await novel_interface.show_text_only("恢复知觉的关节和肌肉并未感觉不适，反而是喉咙干渴到发痒，我赶忙冲到路边的石质饮水池喝水。")
	await novel_interface.show_text_only("奥古斯塔自作主张的钻进售票亭打开了电源，旋转木马缓缓转动起来，昏暗的广场瞬间被点亮了。")
	await novel_interface.show_text_only("空无一人的小镇上，广场地面的石板反射着回转的绚丽灯光，好似童话中的画面。")
	novel_interface.show_character("augusta","happy")
	await novel_interface.show_dialog("哇——！", "奥古斯塔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("……你没玩过吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔微微摇了摇头，像小孩子一样张着嘴，惊讶的看着这奇异的情景。")
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("来~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我拉着她登上转动的基台，坐到一个马车车厢造型的双人座上。")
	await novel_interface.show_text_only("她显得很兴奋又有些害怕，不停的左顾右盼，但眼中一直闪着光亮。")
	await novel_interface.show_text_only("我靠在车厢背上，看着镶在天花板的镜面中反射她的笑颜，心情稍稍放松了下来。")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("（不知什么时候才能把能量耗完……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("而且耗完后真的能回去吗，甚至真的能耗完吗？")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("（唉，顺其自然吧~）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("augusta","happy")
	await novel_interface.show_dialog("呐……", "奥古斯塔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("嗯？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("augusta","happy")
	await novel_interface.show_dialog("你刚才是不是想问我关于学园都市的事来着？", "奥古斯塔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("我记得你说……第四学园都市是柏林？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("augusta","happy")
	await novel_interface.show_dialog("那个称号还没公开，是一个月前各个战胜国在伦敦会议中决定的事项。", "奥古斯塔")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("虽然是宰相代我参会，但我认为这个名字挺好——", "奥古斯塔")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("铁与血的代价太过高昂了……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我若有所思的点了点头。")
	await novel_interface.show_text_only("虽然还没出现核武器，但异质物武器在这个世界的普及程度却超乎我想象的高。")
	await novel_interface.show_text_only("刚看到那台被烧焦的量产战车，从主炮的形状看来绝不是发射动能炮弹的。")
	await novel_interface.show_text_only("也可想而知刚刚结束的那场战争有多么惨烈……")
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("你总提到的那个宰相……和你很亲吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我注意到刚才卫戍军使用的都是麻醉武器，而且明显有种投鼠忌器的感觉。")
	novel_interface.show_character("augusta","worry")
	await novel_interface.show_dialog("嗯……", "奥古斯塔")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("至少曾经是的……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔脸上闪过一丝失落，抬起头看着天花板上的镜子，似乎陷入了回忆。")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.show_character("augusta","worry")
	await novel_interface.show_dialog("哥哥在我8岁那年，死于一场意外……", "奥古斯塔")
	await novel_interface.show_dialog("我被带到议员们面前，看他们为了继承权问题吵个不停，心里怕极了", "奥古斯塔")
	await novel_interface.show_dialog("当时只有一个人过来安慰我，说只要我能忍住不在议会大厅里哭出来，她就有办法保护我", "奥古斯塔")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("——她就是莱昂妮·冯·俾斯麦。", "奥古斯塔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("是怎么做的……？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("augusta","normal")
	await novel_interface.show_dialog("她在议会上发表了一次差点引起多数派议员们暴动的演说——", "奥古斯塔")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("“当代的重大问题不是通过演说和多数派决议所能解决的，而是要用铁和血来解决。”", "奥古斯塔")
	await novel_interface.show_dialog("“为了避免我们再度陷入分裂，必须由霍亨索伦家族唯一的继承人来接替皇位”", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听着奥古斯塔模仿那个人说话的样子，让我感觉有些熟悉。")
	await novel_interface.show_text_only("接着，她笑着摇了摇头。")
	novel_interface.show_character("augusta","worry")
	await novel_interface.show_dialog("从那时起就是这种不留余地的性格呢……", "奥古斯塔")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("她发表完演说之后，立刻将我从已经炸锅的议会大厅护送回了后台。", "奥古斯塔")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("当时我终于忍不住，哗的就哭了出来。觉得外面那些人一定会把我俩拉到歌剧广场上处决掉……", "奥古斯塔")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("但她却说，人应该选择一个体面的死法，死于政治暗杀、死在绞刑架上和死在战场上并没有区别。", "奥古斯塔")
	await novel_interface.show_dialog("或许我还不懂，但为了达成我父兄的遗志，她会陪我一起，抗争到底。", "奥古斯塔")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("所以从那天起，她就成为了我的首相。", "奥古斯塔")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("根据普鲁士宪法，首相只需听从君主，并不需要搭理议会，她是我一个人的首相。", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔说起这段往事时嘴角微微扬起，面容也变得温暖而柔和，就像说起自己重要的家人一般。")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("那之后怎么……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("augusta","tear")
	await novel_interface.show_dialog("自从我在凡尔赛宫加冕之后，一切都不一样了……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她缓缓低下了头。")
	novel_interface.show_character("augusta","tear")
	await novel_interface.show_dialog("之前她都会在议会和大臣对我提出无理要求的时候立刻站出来否决。", "奥古斯塔")
	await novel_interface.show_dialog("可上周议会提议让我与魏玛大公的儿子联姻，陆军大臣和贸易大臣都站出来表示赞成。", "奥古斯塔")
	await novel_interface.show_dialog("她明知那家伙的儿子都是什么货色，却不但没有反对，还着手安排了今天的会面。", "奥古斯塔")
	await novel_interface.show_dialog("从那天之后，她就一直拒绝与我见面，就连陆军大臣换掉我的禁卫她也不管……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("旋转木马随着音乐结束渐渐停了下来，奥古斯塔也陷入了沉默。")
	await novel_interface.show_text_only("我回想起在凡尔赛宫的卧室她跟我报出的那一连串头衔，然后轻轻拍了拍她的后背。")
	novel_interface.show_character("ren_uniform","normal1")
	await novel_interface.show_dialog("你的那个首相……\n现在的头衔已经变成宰相了吧？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("augusta","tear",0.25)
	await novel_interface.show_dialog("嗯……", "奥古斯塔")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那是因为你现在已经不仅仅是普鲁士的女王，而是德意志全境的皇帝了。", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("大战结束之后，迫切希望恢复经济的民众与手握军权的大臣之间是最需要小心制衡的。")
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("所以，放心吧~", "小怜")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("虽然我还不知道自己是怎么来到这个世界的，以及那股控制我的强大力量来自何处……", "小怜")
	await novel_interface.show_dialog("但这次事件应该制造了足够的筹码，来让那个人说服议会，让他们认同你的价值远超他们的想象了。", "小怜")
	await novel_interface.show_dialog("我说的没错吧——", "小怜")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("宰相小姐？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我盯着向售票亭上的监控摄像头，从我们来到广场开始，它就一直正对着我们的方向。")
	novel_interface.show_character("augusta","shock")
	await novel_interface.show_dialog("什、什么意思？", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没等我解释，一辆装饰着金质镶边的白色豪华汽车就从广场远端的拐角缓缓驶出。")
	await novel_interface.show_text_only("汽车一直开到旋转木马旁边，司机殷勤的拉开后排车门，毕恭毕敬的邀请我们。")
	await novel_interface.show_text_only("车里坐着一位身穿白色礼服的女人，从我的角度看不到她的上半身。")
	await novel_interface.show_text_only("奥古斯塔立刻从座椅上跳下来跑了过去。")
	novel_interface.show_character("augusta","timid")
	await novel_interface.show_dialog("莱昂妮！？", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("与此同时，广场远端的拐角开出几辆装甲车，对面房顶上也有数个黑影在动。")
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("（果然，真像那个人呢……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我能看出这些手段，也是因为一直在她身边耳濡目染吧~")
	await novel_interface.show_text_only("奥古斯塔开心的回头叫我一起上车，我笑着对她摆了摆手。")
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("下次吧~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("从刚才我就已经感觉到……")
	await novel_interface.show_text_only("——是时候了。")
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("我靠在旋转木马的座椅上，慢慢闭上了眼睛。")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("………………")
	await novel_interface.show_text_only("黑暗中，强烈的眩晕向我袭来。")
	await novel_interface.show_text_only("接着是一阵刺眼的亮光和强烈的坠落感，我不禁大叫了起来——")
	await novel_interface.show_text_only("当坠落感突然消失时，我感觉自己好像正趴在柔软的纺织品上。")
	await novel_interface.show_text_only("同时耳边传来了安妮的欢呼和拉斐尔的尖叫声。")
	novel_interface.show_background("res://assets/images/bg/Versailles/BG_Versailles_BRM_AuG.png")
	novel_interface.show_character("anne_uniform","happy")
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	await novel_interface.show_dialog("小怜回来啦？！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮打开卧室的灯，我发现自己正以一种奇怪的姿势跪在床上——上半身紧贴床面，屁股高高翘起。")
	await novel_interface.show_text_only("而我的脸正对着的是……")
	await novel_interface.show_text_only("——坐在床上的拉斐尔岔开的两腿之间？！")
	await novel_interface.show_text_only("还没等我看清，就被她一脚蹬中面门，从床上踹了下去。")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("啊啊！！屁股疼疼疼……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我刚想揉，发现自己手里攥着那枚湿乎乎的彩蛋。")
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("怎么……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮手里拿着一个黑色的物体，但完全无法分辨它的形状。")
	await novel_interface.show_text_only("直到她把它放在桌子上，我才发现那是一个被涂黑的玻璃水杯。")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("果然所谓“不透光”指的不仅仅是可见光，还要能屏蔽一切电磁波啊。", "安妮")
	await novel_interface.show_dialog("虽然我也不知道什么叫电磁波，不过还好拉斐尔的画室里有这种反光率超低的碳纳米管材料。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("……哈？\n你说什么呢？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("……可是刚才拉斐尔为什么要叫我关了灯在门外等着啊？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我正被安妮的话搞得摸不着头脑，接着就被拉斐尔丢过来的枕头击中，失去了知觉。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("一段时间之后。")
	await novel_interface.show_text_only("第五学园都市，新丰洲境内。")
	await novel_interface.show_text_only("莉琉揉着还在发胀的脑袋，蓬头垢面的从洗手间走出来，手机收到了情报组发来的简报。")
	await novel_interface.show_dialog("安妮把那个小笨蛋找回来了？", "莉琉")
	await novel_interface.show_dialog("我就说没什么事儿吧……", "莉琉")
	novel_interface.show_background("res://assets/images/bg/Soya/Universe.png")
	await novel_interface.show_text_only("莉琉随意的向下刷着简报，却看到了完全意料之外的内容——")
	await novel_interface.show_dialog("1871年……德意志帝国？？", "莉琉")
	await novel_interface.show_dialog("如果不排除记忆植入，或许只能解释为观测到了异世界或另一维度的宇宙……", "莉琉")
	await novel_interface.show_dialog("钻进了兔子洞吗……", "莉琉")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………")
	novel_interface.show_background("res://assets/images/bg/Versailles/BG_Versailles_BR_AuG.png")
	await novel_interface.show_text_only("当夜，奥古斯塔回到卧室，侍卫已经换回了自己熟悉的那几个人。")
	await novel_interface.show_text_only("女仆早就将卧室重新整理好，桌上还摆着宰相差人送来的一盘马卡龙。")
	novel_interface.show_character("augusta","wordless")
	await novel_interface.show_dialog("可恶，又在晚上给我送甜食……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔摸了摸自己的小肚子，然后从盘子上偷偷抽走一块。")
	await novel_interface.show_text_only("刚刚在款待魏玛大公及其家人的晚宴上，宰相以一份炼钢产业联营的合约替代了先前提出的婚约。")
	novel_interface.show_character("augusta","uneasy")
	await novel_interface.show_dialog("那份合约明明早就拟定好了吧……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔走到阳台上，看着漫天的繁星，做了个深呼吸。")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Moon_AuG.png")
	await novel_interface.show_dialog("月色真美啊……", "奥古斯塔")

	print("=== 帝国临在篇第5话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
