# imperialpresence_ep03.gd - 帝国临在篇第3话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	imperialpresence_ep03_script()

func play_script():
	pass

func imperialpresence_ep03_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Versailles_BR_AuG.png")
	await novel_interface.show_text_only("房间里的光芒已完全消失，倒在地上的女官和侍卫长丝毫没有苏醒的迹象。")
	await novel_interface.show_text_only("小怜像鸵鸟一样撅在墙角，垂下的头发挡在脸上。")
	await novel_interface.show_text_only("金发少女蹲下来，试探性用权杖的尖端戳了戳那只“不明生物”翘起来的屁股。")
	await novel_interface.show_text_only("只见那东西全身条件反射似的颤抖了一下，同时发出“咿！”的叫声。")
	novel_interface.show_character("augusta","shock")
	await novel_interface.show_dialog("居、居然……", "奥古斯塔")
	await novel_interface.show_dialog("是女孩子？", "奥古斯塔")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("（难道不是瓦格纳老师说的那个人……）", "奥古斯塔")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Parsifal_AuG.png")
	await novel_interface.show_text_only("少女回想起教自己文学和历史的家庭教师。")
	await novel_interface.show_text_only("瓦格纳老师在留给她的手抄本中反复提及一个人。")
	await novel_interface.show_text_only("“终有一日，少年将于圣光中降临，效忠并拯救万岁胜者桂冠之主。”")
	await novel_interface.show_text_only("虽然那本书用词晦涩难懂，而且不久后瓦格纳还因为“精神问题”被送去了巴伐利亚疗养院。")
	await novel_interface.show_text_only("但『万岁胜者桂冠』确实是她家族代代相传权杖的名字，这让少女一直对书中的预言深信不疑。")
	await novel_interface.show_text_only("奥古斯塔不知幻想过多少次与少年相遇的情景，但绝不是像今天这样——")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("况且这个穿着丝袜的家伙怎么可能是少年啊！")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Versailles_BR_AuG.png")
	await novel_interface.show_text_only("小怜双手撑地缓缓抬起头，强忍着剧烈的晕眩感，眯起眼睛环视四周。")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("这是……哪啊？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这里与刚才的卧室有几分相似，但肯定不是同一个房间——")
	await novel_interface.show_text_only("温度忽然凉爽了许多，地毯也变成了地板，那股灰尘和淡淡的霉味也被柠檬罗勒味的熏香替代。")
	await novel_interface.show_text_only("小怜揉着屁股慢慢坐起来，一旁的奥古斯塔难掩失望。")
	await novel_interface.show_text_only("那迷离的眼神、柔软的腰肢和凌乱的头发——活脱脱一幅无助少女的模样。")
	novel_interface.show_character("augusta","stare")
	await novel_interface.show_dialog("（她……是被我召唤出来的吗？）", "奥古斯塔")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("（看起来好弱……）", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("不过至少，应该会听命于我吧。")
	await novel_interface.show_text_only("想到这里，奥古斯塔轻咳了两下。")
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("诶？\n你、你是……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("穿着军礼服的少女刚准备展示出王者的威严，却忽然被小怜扑过来一把抱住大腿。")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("小妹妹，你、你知不知道刚才怎么回事？？！", "小怜")
	await novel_interface.show_dialog("那个彩蛋……\n诶——怎怎怎么怎么地上还躺着好几个？！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着小怜半跪在地板上手足无措的样子，奥古斯塔挣脱并皱着眉头后退几步。")
	novel_interface.show_character("augusta","panic")
	await novel_interface.show_dialog("（如此不矜持，该不会是乡下来的吧……）", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女转过身背对着小怜，看着她那副花容失色的蠢样实在没法严肃的报出名号。")
	novel_interface.show_character("augusta","stare")
	await novel_interface.show_dialog("咳咳——\n听好了……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你这只愚蠢的召唤兽。", "奥古斯塔")
	novel_interface.show_character("augusta","stare")
	await novel_interface.show_dialog("吾乃被授予天命的霍亨索伦家族的后裔，普鲁士的女王——", "奥古斯塔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("背对着自己的少女故意拉长尾音，显然话还没有说完，但小怜已经意识到了什么……")
	novel_interface.show_character("augusta","jest")
	await novel_interface.show_dialog("德意志联邦主席，统一德意志全境的皇帝！", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("穿着红黑两色斗篷的少女一边提高音量一边举起双臂，做出“赞美太阳”的姿势。")
	await novel_interface.show_text_only("小怜猛然想起前两天历史讲座上似乎听过那几个词\n，惊讶的站起身上前两步却欲言又止……")
	novel_interface.show_character("augusta","jest")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","wry_smile",0.25)
	await novel_interface.show_dialog("（等等，普鲁士和德意志是什么关系来着？）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("那不重要啦！！！\n关键的问题是——")
	await novel_interface.show_text_only("难、难道说……")
	novel_interface.show_character("augusta","jest")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_uniform","sob",0.25)
	await novel_interface.show_dialog("（我穿越时空了！！？）", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("以及——", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("奥古斯塔压低了音调，似乎要用最后的头衔为那个不妙的猜测一锤定音。")
	novel_interface.show_character("augusta","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","sob",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("第四学园都市的最高元首——赫尔米娜·奥古斯塔·路德维希！", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("金发少女将权杖重重的戳在地上，用清脆的敲击声作为气势恢宏的收尾。")
	novel_interface.show_character("augusta","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_uniform","sob",0.25)
	await novel_interface.show_dialog("………………", "小怜")
	novel_interface.change_2nd_expression("wail")
	await novel_interface.show_dialog("哈？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("小怜的大脑一片空白，张大嘴巴愣在原地。")
	novel_interface.show_character("augusta","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","wail",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("还有，给我记住了……", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("似乎压抑许久的怒火终于找到了爆发的机会，奥古斯塔乘着刚才的气势，一边转身一边大喊。")
	novel_interface.show_character("augusta","shout")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","wail",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我已经15岁了！！\n才不是什么小妹妹——", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("没想到小怜已经起身并走到自己身后，奥古斯塔转身一头埋进了小怜的胸部。")
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("房间内空气凝固了五秒钟之后。")
	novel_interface.show_character("ren_uniform","uneasy")
	await novel_interface.show_dialog("好矮……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("终于回过神的小怜不经意间说出了在这座行宫里足以被判处死刑的发言。")
	await novel_interface.show_text_only("接着，就感到胯下遭受了一记重击……")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("与此同时。")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Versailles_BRM_AuG.png")
	await novel_interface.show_text_only("看着落在地毯上的彩蛋，安妮立刻冲向卧室的百叶窗，将大半个身子探出去寻找小怜的踪迹。")
	await novel_interface.show_text_only("拉斐尔怕安妮摔下去，赶忙把她拉回来，二人喘着粗气坐在壁炉旁四目相觑。")
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("小怜她……", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","smile",0.25)
	await novel_interface.show_dialog("……不见了？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔起身捡起地上的彩蛋仔细端详。")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Faberge_Egg_AuG.png")
	await novel_interface.show_text_only("这颗彩蛋比普通鸡蛋稍大，在法贝热的诸多作品中算是相当小巧的。")
	await novel_interface.show_text_only("当年法贝热为沙皇打造的彩蛋大多内有玄机，但这颗彩蛋经过扫描，确定里面是实心的。")
	await novel_interface.show_text_only("安妮刚想凑过去看看，手机却突然响起，接通后另一头传来莉琉有些含糊的声音。")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Versailles_BRM_AuG.png")
	await novel_interface.show_dialog("喂？安妮……", "莉琉")
	await novel_interface.show_dialog("小怜的信号怎么又、又突然消失了……", "莉琉")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("莉琉？\n你……怎么听起来有点怪怪的……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一向强势的莉琉今天的声音却特别轻柔，说话伴着呼吸声，有种暧昧的感觉。")
	await novel_interface.show_dialog("刚、刚晚上和老同学喝了点……", "莉琉")
	await novel_interface.show_dialog("爱衣给了我……一片……据说是她研制的，可以防宿醉的……安眠药？", "莉琉")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("爱衣的药也敢吃啊？！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("看、看我明天不好好修理她……", "莉琉")
	await novel_interface.show_dialog("我刚吃药没一会就收到自动报警，那孩子就不能让人省点儿心吗……", "莉琉")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("啊对了！小怜她碰到了一个彩蛋，然后就在我们眼皮底下消失了！！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("电话另一头传来了手拍在脸上的声音。")
	await novel_interface.show_dialog("我怎么好像养了个特别容易被拐卖的傻女儿……", "莉琉")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("你……在问我？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("安妮，记住你的训练……", "莉琉")
	await novel_interface.show_dialog("遇到问题先收集信息，越难以理解的复杂状况越要回归常识……", "莉琉")
	await novel_interface.show_dialog("比、比如……\n呼…………", "莉琉")
	await novel_interface.show_text_only("莉琉的声音越来越小，说着说着就没了动静。")
	novel_interface.show_character("anne_uniform","serious")
	await novel_interface.show_dialog("喂？喂——！\n莉琉？莉琉！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("几秒之后，安妮听到一声熟悉的闷响，和她在家里经常能听到的小怜从床上滚下去的声音一模一样。")
	await novel_interface.show_text_only("同时听筒中还传来“呀～”的一声尖叫，随后就陷入了沉默。")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("挂、挂断了……？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("等等！刚才那个叫声是谁的？！")
	await novel_interface.show_text_only("拉斐尔走过来把彩蛋递给安妮，并从手机中调出这只彩蛋的资料。")
	novel_interface.show_character("anne_uniform","panic")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("raphael","stare",0.25)
	await novel_interface.show_dialog("看来莉琉暂时帮不上忙了？", "拉斐尔")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("过了这么久十字玫瑰的保镖都没冲进来，应该是没监测到什么异常波动。", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮点了点头，观察着手中沉甸甸的彩蛋。")
	novel_interface.show_character("anne_uniform","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","normal2",0.25)
	await novel_interface.show_dialog("这东西的原料是从尤戈尔斯基半岛的陨石坑里找到的，外层是黑色的宝石级刚玉。", "拉斐尔")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("外层……？", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("目前只知道内核没有磁性和放射性，对电磁辐射的吸收性极好，只能通过密度猜测化学成分……", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔不满的把手机丢到床上。")
	novel_interface.show_character("anne_uniform","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","subtle",0.25)
	await novel_interface.show_dialog("基本上就是个黑体嘛！\n鬼知道里面是什么……", "拉斐尔")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这上面应该没有魔女的刻印，不然小怜触碰它的瞬间就会有反应。", "安妮")
	novel_interface.change_expression("unhappy")
	await novel_interface.show_dialog("对了，这个十字章上的字母是什么意思？\n字母A的顶部还有两个小点——", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("ÄON，德语中“永恒”的意思。", "拉斐尔")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("大概是沙皇希望两国的友谊万古长存吧……", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔轻蔑的笑了笑——")
	novel_interface.show_character("anne_uniform","unhappy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("raphael","mock",0.25)
	await novel_interface.show_dialog("结果这个礼物送出的三年后，没常识的新任德皇就拒绝了俄国希望续订条约的请求——", "拉斐尔")
	await novel_interface.show_dialog("自以为是的摧毁了前任首相处心积虑建立起的欧洲秩序，后来还葬送了自己的帝国。", "拉斐尔")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("收集信息……常识……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮回想着莉琉刚才的话，默默掏出手机。")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Versailles_BR_AuG.png")
	await novel_interface.show_text_only("小怜挨了那一下，本能的捂着被打的地方蜷缩在地上颤抖着。")
	await novel_interface.show_text_only("奥古斯塔以为自己下手太重，想说些什么却欲言又止，僵在原地小声嘀咕着——")
	novel_interface.show_character("augusta","tear")
	await novel_interface.show_dialog("谁、谁叫你说我！……", "奥古斯塔")
	novel_interface.change_expression("wordless")
	await novel_interface.show_dialog("我又没使劲，有那么疼吗……", "奥古斯塔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("（好像……并没那么疼？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("嗯，大概是幻肢痛。")
	await novel_interface.show_text_only("小怜缓缓坐起，靠在床边调整了一下呼吸。")
	await novel_interface.show_text_only("终于冷静下的她开始试着搞清楚自己到底卷入了什么状况。")
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("所以，你刚才说……\n第四学园都市？", "小怜")

	print("=== 帝国临在篇第3话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
