# imperialpresence_ep04.gd - 帝国临在篇第4话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	imperialpresence_ep04_script()

func play_script():
	pass

func imperialpresence_ep04_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Versailles_BR_AuG.png")
	await novel_interface.show_text_only("如果这个装束奇怪的女生刚才那番发言不是中二病发作的话，状况就很严重了。")
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("你刚才说第四学园都市？\n还有这到底是哪啊？我刚才明明在……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("augusta","shout",0.25)
	await novel_interface.show_dialog("还轮不到你来发问！", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("少女用权杖指着我的鼻尖斩钉截铁得说道。")
	novel_interface.show_character("ren_uniform","panic")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("augusta","shout",0.25)
	await novel_interface.show_dialog("身为召唤兽，先要恭顺的向自己即将效忠之人报上真名，这是基本常识吧！", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("你这句话里有哪个词像常识啊！")
	novel_interface.show_character("ren_uniform","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("augusta","shout",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你是说名字吗？\n我叫怜……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("虽然不知算不算是“真名”……")
	novel_interface.show_character("ren_uniform","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("augusta","stare",0.25)
	await novel_interface.show_dialog("『怜』什么？", "奥古斯塔")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("就是怜啊，叫我小怜就可以～", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("奥古斯塔有些难以置信的盯着我。")
	novel_interface.show_character("ren_uniform","wry_smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("augusta","panic",0.25)
	await novel_interface.show_dialog("只、只有……一个音节？\n居然存在如此没气势的名字吗！？", "奥古斯塔")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哈？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wordless")
	await novel_interface.show_dialog("（小声）我还以为会叫圣安福塔斯或者齐格弗里德之类的呢……", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("哪有叫齐格弗里德的女高中生啊！")
	await novel_interface.show_text_only("奥古斯塔似乎备受打击，一拳打在墙边的柜子上自言自语的说道。")
	novel_interface.show_character("augusta","serious")
	await novel_interface.show_dialog("可恶，是因为我的资质太差吗……", "奥古斯塔")
	await novel_interface.show_dialog("按书上的方法失败了那么多次，还每天都在想象第一次召唤成功会是什么样的。", "奥古斯塔")
	novel_interface.change_expression("tear")
	await novel_interface.show_dialog("我真是个笨蛋……\n瓦格纳老师也会失望吧……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("嗯，听起来确实是中二病才有的发言。")
	await novel_interface.show_text_only("她无精打采的抬起头，像看乞丐一样打量着我。")
	novel_interface.show_character("augusta","stare")
	await novel_interface.show_dialog("你大概只是个低等魅魔吧……\n哼，男人会喜欢这种装束吗？", "奥古斯塔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","shy",0.25)
	await novel_interface.show_text_only("额……\n（这个问题你叫我怎么回答……）")
	novel_interface.change_2nd_expression("shy_right")
	await novel_interface.show_text_only("“喜欢，而且有些人还会自己穿？”")
	novel_interface.change_2nd_expression("wry_smile")
	await novel_interface.show_text_only("另外魅魔又是什么设定！\n召唤兽种类这么丰富的吗？")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嘘！", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("我脑中还在盘算接下来的问题，奥古斯塔突然警觉得望向门外。")
	await novel_interface.show_text_only("我顺着她的目光看去，一个身穿黑色军服、头盔上印着皇家徽记的卫兵正颤巍巍的站在门口。")
	await novel_interface.show_text_only("他环视着屋里横七竖八躺倒的女官和侍卫长，然后满脸惊恐的将目光落在了我的身上。")
	await novel_interface.show_text_only("等等，不是我干的！！")
	await novel_interface.show_dialog("有……", "卫兵")
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_dialog("——有刺客！！！", "卫兵")
	await novel_interface.show_text_only("那个卫兵按住肩头像对讲机一样的东西大喊，同时哆哆嗦嗦的从腰间掏出武器。")
	await novel_interface.show_text_only("虽然武器侧面装饰的银质雕纹护板很抢眼，但那东西的结构很明显是某种左轮手枪。")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("诶？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("见到枪口忽然对准自己，我本能的想后退，却被地毯绊得一屁股坐到了地上。")
	await novel_interface.show_text_only("看着马上就要扣动的扳机的士兵和愚蠢到想要伸手去挡子弹的我，奥古斯塔立刻挥动起权杖。")
	novel_interface.show_character("ren_uniform","wail")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("augusta","shout",0.25)
	await novel_interface.show_dialog("住手！！", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("膨——！膨——！膨——！\n膨——！膨——！膨——！")
	await novel_interface.show_text_only("随着六声炸响，卫兵将弹仓里的子弹倾泻而出。")
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Versailles/BG_Versailles_BR_AuG.png")
	await novel_interface.show_text_only("我闭着眼睛蜷在地上，浑身上下摸了摸，似乎没有受伤？")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("（一枪都没打中？）\n（……人体描边大师？！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那卫兵看我挨了六枪居然还在地上扭来扭去也懵了\n，想了好久才反应过来要换弹。")
	novel_interface.show_character("ren_uniform","wail")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("augusta","shout",0.25)
	await novel_interface.show_dialog("你这召唤兽……别在那儿丢人现眼了！！\n快给我起来反击啊！！", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("奥古斯塔气得将权杖戳到了地上，金属撞击发出的嗡嗡声好像能穿透我的灵魂，一直在我耳边回荡。")
	await novel_interface.show_text_only("一股强烈的“必须要反击”念头瞬间涌入了我的大脑，驱使我的身体自己动了起来。")
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("怎么回事！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我眼看着自己干净利落的站起来，径直冲向那个刚换好子弹准备开始第二轮射击的卫兵。")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("（这是送死吗！？给我停下来啊！！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在奥古斯塔的视角，那只不中用的召唤兽眨眼间就起身闪到了卫兵面前，侧身轻松躲过了一枪。")
	await novel_interface.show_text_only("她趁重心下移顺势一掌打中对方腹部，卫兵的黑色军服在猛烈的冲击下顿时崩裂成一条条布片。")
	await novel_interface.show_text_only("只见那个身高近一米八左右的卫兵随着一声巨响飞出了足足六、七米远。")
	await novel_interface.show_text_only("在落地后，还在惯性驱使下滑了一段距离，随后便陷入了沉默。")
	await novel_interface.show_text_only("………………")
	await novel_interface.show_text_only("感觉身体再度恢复控制的我张大着嘴巴盯着躺在远处的卫兵，又扭头看了看奥古斯塔。")
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("刚才……是你？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("绝对是这个女孩在搞鬼吧？！")
	await novel_interface.show_text_only("没想到奥古斯塔比我还要惊讶，声音有些颤抖。")
	novel_interface.show_character("augusta","uneasy")
	await novel_interface.show_dialog("好、好强……！", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("原来你也没数的吗！")
	await novel_interface.show_text_only("我刚才那套动作风格很像安妮的体术，但即使是她也没有那么大的力量吧……")
	await novel_interface.show_text_only("而且仔细想想，黑色金边军服、镶着徽记的头盔还有枪上的银质雕纹，这些都是一战前的风格。")
	await novel_interface.show_text_only("但那个类似对讲机的通信装置，还有可以六发子弹同时装填的新式左轮，肯定不是那个年代的技术。")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("所以这不是什么时间穿越……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这里是……异世界！？")
	await novel_interface.show_text_only("来异世界不是应该有个笨蛋女神或者贤者爷爷什么的吗！？这和书上写的不一样啊！！")
	await novel_interface.show_text_only("而且手机也因为昨晚看动画时睡着而没电了……这简直是最糟糕的状况了吧！？")
	await novel_interface.show_text_only("咚——！！")
	await novel_interface.show_text_only("奥古斯塔用权杖敲了一下我的后脑勺，我头上瞬间鼓起一个大包。")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("你干嘛啊——！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("augusta","stare",0.25)
	await novel_interface.show_dialog("肉体强度这么弱，是怎么做出那种力度的攻击的？", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("奥古斯塔全然无视我的抗议，托起下巴认真思考\n着。")
	novel_interface.show_character("ren_uniform","stare")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("augusta","stare",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……什么意思？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("牛顿第三定律没学过吗？\n果然低等召唤兽都没什么文化……", "奥古斯塔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("这里也有那个家伙吗？果然去哪都要学物理吗？！这个异世界也太奇怪了吧！！！")
	await novel_interface.show_text_only("奥古斯塔走到我刚才摔到的地方，从地上捡起一枚被压扁变形的弹头。")
	novel_interface.show_character("augusta","stare")
	await novel_interface.show_dialog("难道瓦格纳老师教的那个术式……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔回头看着蹲在那委屈的揉脑袋的小怜，将弹头在手里攥紧。")
	novel_interface.show_character("augusta","normal")
	await novel_interface.show_dialog("『莱茵的黄金守护』……能够在她身上生效？", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然，外面传出一阵尖锐的金属断裂的响声。")
	await novel_interface.show_text_only("奥古斯塔从卧室门口望出去，走廊尽头的铁闸正缓缓打开，门后是数十名严阵以待的卫戍军。")
	await novel_interface.show_text_only("一个军官模样的人正在指挥士兵分小队前进，每队前进几米就架好武器掩护后面的小队。")
	await novel_interface.show_text_only("与此同时，窗外也传来一阵躁动，不知从哪冒出来的几十名士兵此时已经瞄准了卧室的窗口。")
	await novel_interface.show_text_only("远处还陆陆续续不断有士兵聚集到楼下的广场，将整栋建筑物围了个水泄不通。")
	novel_interface.show_character("augusta","worry")
	await novel_interface.show_dialog("糟，被她知道了！", "奥古斯塔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","wail",0.25)
	await novel_interface.show_dialog("她……？\n咱们怎么办？！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("现、现在道歉还来得及吗？")
	await novel_interface.show_text_only("奥古斯塔把卧室门关上，并马上将我从窗口拉开推向墙角。")
	novel_interface.show_character("augusta","serious")
	await novel_interface.show_dialog("别靠近窗户，小心狙击！", "奥古斯塔")
	await novel_interface.show_dialog("刚才你没被打死可能只是侥幸……\n一会记得离我近点！", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看她严肃的表情，我乖乖的点了点头，走廊的脚步声离这里越来越近")
	await novel_interface.show_text_only("奥古斯塔用身体护住我，双眼紧盯着大门，防止一会冲进来的士兵二话不说直接将我射杀")
	novel_interface.show_character("augusta","stare")
	await novel_interface.show_dialog("还是这么不留余地吗……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔紧握住权杖，回头扫了一眼自己身后那只快要缩成蘑菇的低等魅魔。")
	novel_interface.show_character("augusta","stare")
	await novel_interface.show_dialog("只能赌一赌了……", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她将权杖抬起，重重的戳到地上，发出“当”的一声巨响。")
	novel_interface.show_character("augusta","stare")
	await novel_interface.show_dialog("我命令你——", "奥古斯塔")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("带我离开这！", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那种熟悉的感觉再度出现，犹如大钟在山谷中回荡的余韵，萦绕着我的全身。")
	await novel_interface.show_text_only("怎么离开？这个世界有传送门？")
	await novel_interface.show_text_only("不对，有牛顿的地方怎么可能有传送门！")
	await novel_interface.show_text_only("还是说这个女生是我的Master，我能带她一起瞬移到别的地方？")
	await novel_interface.show_text_only("我的脑子开始胡思乱想。")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("（带她离开这里……）\n（嗯……离开……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然而，身体纹丝不动。")
	await novel_interface.show_text_only("我就像看着主人把飞盘丢下悬崖的狗狗，一脸茫然的看着她。")
	novel_interface.show_character("ren_uniform","uneasy")
	await novel_interface.show_dialog("……怎、怎么离开？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("奥古斯塔红着脸把头扭了过去。")
	novel_interface.show_character("augusta","timid")
	await novel_interface.show_dialog("我哪知道啊！！", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("此时，门外的脚步声消失了。")
	await novel_interface.show_text_only("在一片死寂中，我几乎能想象门外那些士兵摆好阵势，随时准备破门而入的画面。")
	await novel_interface.show_text_only("奥古斯塔的呼吸也变得急促，似乎做好了顽抗到底的准备。")
	await novel_interface.show_text_only("我的身体突然动了起来，只见我单膝跪地，右手扶住她的后背，左手隔着披风揽住她的大腿。")
	novel_interface.show_character("augusta","wordless")
	await novel_interface.show_dialog("你、你干嘛！？", "奥古斯塔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("说实话，我也很好奇！")
	await novel_interface.show_text_only("随后我双臂上钩，将她整个横着抱了起来。")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("（……公主抱？）\n（不过好像并不觉得沉……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她本想挣脱，但很快就明白这大概是我对她命令的回应。")
	await novel_interface.show_text_only("奥古斯塔不再抵抗，还很配合的搂住了我的脖子。")
	await novel_interface.show_text_only("我抱着她走到房门左侧，贴墙站好，我们都默契的屏住了呼吸，静静的等着那个时刻——")
	await novel_interface.show_text_only("几秒之后，木质大门“轰”的被炸开，同时一枚冒着蓝烟的黑色金属物体被丢了进来。")
	novel_interface.show_character("ren_uniform","serious")
	await novel_interface.show_dialog("（什么东西？！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的身体比意识更快一步，一脚就把那东西踢出了窗外，楼下的广场传来一阵骚动。")
	await novel_interface.show_text_only("回头看向门口，几个端着武器、头戴防毒面具的士兵还没理解刚才发生的一幕。")
	await novel_interface.show_text_only("我快步上前对着中间那个倒霉蛋的面门就是一脚。")
	await novel_interface.show_text_only("那家伙顿时像橄榄球一样飞了出去，还撞倒了后面几名士兵。")
	await novel_interface.show_text_only("我抱紧奥古斯塔，抓住这短暂的空档冲向走廊，然后迈开大步就开始飞奔——")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("（不会是要一路跑出去吧？！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可这速度也……")
	await novel_interface.show_text_only("太快了啊啊啊啊啊啊啊啊啊啊！！！！！！！！")
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("与此同时，在另一侧。")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Versailles_BRM_AuG.png")
	await novel_interface.show_text_only("安妮正用手机搜索着任何能将『永恒』和『彩蛋』联系起来的线索。")
	await novel_interface.show_text_only("即使在SID和新丰洲科学院的数据库中也找不到什么有价值的信息。")
	await novel_interface.show_text_only("拉斐尔给萨蒙顿境内对沙皇时期艺术品有过研究的教授挨个打了电话，但同样所获甚少。")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("三十分钟……", "拉斐尔")
	novel_interface.change_expression("subtle")
	await novel_interface.show_dialog("三十分钟内再找不到线索，我就向爷爷求助。", "拉斐尔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","upset",0.25)
	await novel_interface.show_dialog("那样就算能把小怜找回来，戴克斯博士也不会轻易放过她吧……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮头也没抬的回道。")
	novel_interface.show_character("raphael","subtle")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","upset",0.25)
	await novel_interface.show_dialog("毕竟他也知道小怜的价值。", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("有我在就不允许——", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔并没有底气把话说完，她的记忆中，爷爷总有办法达成自己的目的。")
	await novel_interface.show_text_only("她刚刚甚至想过，这次事件会不会就是爷爷一手设计的，但很快就打消了这个念头。")
	novel_interface.show_character("raphael","normal1")
	await novel_interface.show_dialog("（爷爷是不会用我做诱饵的。）", "拉斐尔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","unhappy",0.25)
	await novel_interface.show_dialog("对了，你刚才说这枚彩蛋是二战期间德军从巴黎撤退时留在这的？", "安妮")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("没错，在此之前彩蛋一直保存在慕尼黑。", "拉斐尔")
	await novel_interface.show_dialog("当时把彩蛋带过来的是一个叫『祖先遗产学会』的组织，专门为纳粹搜寻各种传说中的圣物。", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("就是收集『EX级异质物』吧？", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("可以这么说……但当时人们对异质物的认识还很粗浅，也没有相应的探查手段。", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("他们是希望用这枚彩蛋获取某种EX级异质物吗？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔无奈的摇了摇头。")
	novel_interface.show_character("raphael","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","stare",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那个组织在1944年因为某个事件被完全抹杀了，没有留下任何文件，甚至连活口都没有……", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("……啊！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮眼睛一亮，好像找到了什么。")
	novel_interface.show_character("raphael","subtle")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","panic",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("怎么？", "拉斐尔")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("我刚才忽然想到可以试试在神话传说中搜索——", "安妮")
	novel_interface.change_2nd_expression("unhappy")
	await novel_interface.show_dialog("『永恒』是俄耳甫斯神话中表时间的神明埃安，埃安创造了宇宙的银蛋，又被称作俄耳甫斯蛋……", "安妮")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("埃安确实和『ÄON』的发音接近……", "拉斐尔")
	await novel_interface.show_dialog("不过那个神话系和希腊以及罗马神话之间本来就有很多互相借鉴的东西。", "拉斐尔")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("而且那些神话传说和小怜有什么关系？", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮微笑着将手机递给了拉斐尔。")

	print("=== 帝国临在篇第4话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
