# imperialpresence_ep02.gd - 帝国临在篇第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	imperialpresence_ep02_script()

func play_script():
	pass

func imperialpresence_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Versailles_SR_AuG.png")
	await novel_interface.show_text_only("萨蒙顿辖内所属，巴黎西南郊外，伊夫林省。")
	await novel_interface.show_text_only("凡尔赛宫历史博物馆。")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("啊呜……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小怜偷偷把讲解附近艺术品历史的导游耳机摘下来\n，一脸哭丧的扑向安妮。")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("安妮！\n我、我不行了……", "小怜")
	await novel_interface.show_dialog("什么路易十三十四十五……居然一直排到了十九！他们到底有多喜欢“路易”啊！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一旁的安妮早已宕机，头顶冒出一股青烟，任由小怜摇晃。")
	novel_interface.show_character("ren_uniform","sob")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","frustrate",0.25)
	await novel_interface.show_dialog("是啊……而且无论背下多少年号和人名，只要睡上一觉都会被大脑自动删除呢……", "安妮")
	await novel_interface.show_dialog("哈哈……这是身体的排异反应吧？", "安妮")
	await novel_interface.show_dialog("免疫系统将外来的有害物质排出体外，一定是这样的……", "安妮")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("安妮……安妮你不要坏掉啊！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("这次『教学旅游』……")
	await novel_interface.show_text_only("和我们想象的，完全不一样啊啊啊！！！！")
	novel_interface.show_background("res://assets/images/bg/Versailles/BG_Versailles_SR_AuG.png")
	await novel_interface.show_text_only("本以为只是找个借口大家出去旅游，没想到每到一个城市校方都会请当地名人和学者给我们讲课。")
	await novel_interface.show_text_only("更过分的是，听课和参观都要写报告，行程结束后会把所有的报告编纂成书，派发全校，永久存档。")
	await novel_interface.show_text_only("这（对我与安妮而言）和游街示众有什么区别！！精英教育这么可怕的吗？！")
	await novel_interface.show_text_only("怪不得莉琉问都没问就在监护人同意书上签了字！")
	await novel_interface.show_text_only("而且不知为何，这次萨蒙顿的接待规格异常之高。")
	await novel_interface.show_text_only("今天凡尔赛宫历史博物馆居然被我们包场，不对一般游客开放。")
	await novel_interface.show_text_only("此时，这座全世界最大的单体建筑宫殿里，只有御樱川高一年级的学生在三三两两的结伴参观。")
	await novel_interface.show_text_only("美术社的女生甚至悠闲的架起了画板现场写生……")
	await novel_interface.show_text_only("而在画廊的某个角落，两个笨蛋正相拥而泣——")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("那个……小怜……", "安妮")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("你说咱们能不能……找两本导游小册子，参观报告就“借鉴”一下……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("好哇好哇，昨天咱们不是拿了几本，就放在酒店茶几上……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("笨蛋！那个是卢浮宫的啦。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("喂，女装癖~", "？？？")
	await novel_interface.show_text_only("背后突然传来熟悉的声音，我吓得浑身一激灵。")
	await novel_interface.show_text_only("就像察觉到天敌接近的狐獴般，我瞬间挺直了身\n体。")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("拉斐尔！？", "小怜")
	await novel_interface.show_dialog("你……是二年级吧？\n怎么在一年级的——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("话说到一半我忽然意识到，这位可是萨蒙顿总督的孙女，这种地方大概像她家后院一样吧。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("我回来看望爷爷，顺便帮海因里希找点东西……\n听说你们今天来参观就过来玩玩咯~", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("果然是自家后院！")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("诶，那今天凡尔赛宫突然决定不对外开放难道……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("是爷爷不想让媒体来打扰我吧~", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔耸耸肩，无奈的笑了笑。")
	await novel_interface.show_text_only("这位大小姐不久前因对宗教和移民问题的不当言论在国内引发的风波还没有平息吧。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("对了，你们这几天怎么样？\n看着快被烤熟了似的……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("已经外焦里嫩了！")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("是不是觉得这里的历史厚重得承受不了，在琢磨怎么能让参观报告蒙混过关呢？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没错！")
	novel_interface.show_character("ren_uniform","shy_right")
	await novel_interface.show_dialog("不是！没、没有啦……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我本能的想要辩解，安妮却拉了拉我的衣角，有些难为情的说道。")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("拉斐尔……你是不是从小就很熟悉这种艺术品一大堆的地方呀？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("向来强悍的安妮居然露出一幅“拜托帮帮忙”的可怜神情。")
	await novel_interface.show_text_only("等等，这种“妻子跟娘家借钱帮废柴老公还债”的颓废感是怎么回事……")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("艺术品？", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔有些不解的看着我们。")
	novel_interface.show_character("raphael","stare")
	await novel_interface.show_dialog("你们到底有没有听导游耳机的讲解啊……", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那东西早就摘掉了！")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("凡尔赛宫在大革命时期被暴民洗劫过好几次，后来残余的艺术品也被运到卢浮宫去了。", "拉斐尔")
	novel_interface.change_expression("jeer")
	await novel_interface.show_dialog("现在这里陈列的不是复制品就是没什么价值的便宜货，很多装修也是事后修复的。", "拉斐尔")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","panic",0.25)
	await novel_interface.show_dialog("诶？", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不过你们要是想看点特别的东西……", "拉斐尔")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拉斐尔好像突然想到了什么，转身向东侧门廊的方向走去。")
	novel_interface.show_character("raphael","jeer")
	await novel_interface.show_dialog("跟我来~", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("我和安妮跟着拉斐尔穿过长长的走廊，来到一扇被隔离杆拦住的大门面前。")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("这个……是禁止通行的意思吧？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("对呀~", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔一边说一边旁若无人的把铜质隔离杆上的金属挂链摘了下来，熟练的推门走进房间。")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("诶？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("进屋后她随手把挂链丢在椅子上，用鞋尖打开墙边的一个矮木柜，露出里面的电箱。")
	novel_interface.show_background("res://assets/images/bg/Versailles/BG_Versailles_BRM_AuG.png")
	await novel_interface.show_text_only("拉斐尔蹲下来一口气把所有的电源全都拨开，昏暗的房间内顿时灯火通明，通风口也开始吹出冷气。")
	await novel_interface.show_text_only("然后她走到床边，抽出一把18世纪欧洲宫廷风格的蕾丝面女士手扇，一边扇一边抱怨——")
	novel_interface.show_character("raphael","normal2")
	await novel_interface.show_dialog("真是热死了……", "拉斐尔")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("凡尔赛宫的房间通风特别差，真不知道没有空调的时候，那些住在这里贵族是怎么活过夏天的。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我和安妮目瞪口呆的看着拉斐尔一连串操作，不知该从哪一步开始吐槽。")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("额……", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","perspire1",0.25)
	await novel_interface.show_dialog("那、那个……", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("博物馆的管理员不会报警吗？\n我们是不是在做什么不得了的事情啊？！", "小怜")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("没事你们随便坐，这里的家具都是现代材料仿造的复制品，真品都锁在卢浮宫地库里呢。", "拉斐尔")
	await novel_interface.show_dialog("几年前勒沃库森泄露事故的时候，我和家里人来这边住过几个月，当时我就睡在这个房间", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","normal2")
	await novel_interface.show_dialog("那次生化原料泄露？我似乎有印象。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("当时国际新闻轮番播报了好几周，而事故后续莱茵河的清理工作持续数年之久。")
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("嘛……至少官方说法是那样的~", "拉斐尔")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("总之，这里一直是凡尔赛宫的主卧，最早就是由那个家伙设计建造的。", "拉斐尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("拉斐尔用下巴指了指壁炉上的人像油画，对我露出一个意味深长的微笑。")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("？", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","mock")
	await novel_interface.show_dialog("这个亲自为自己发明了高跟鞋，并在法国第一个带头穿丝袜的男人——", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("诶？好像安妮给我讲过……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("是路易十四！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮率先抢答得分，接着似乎想到了什么，也将目光投向我……")
	await novel_interface.show_dialog("你你你们都看我干嘛？！\n我和这家伙没有半点共同点好吗！！！", "小怜")
	await novel_interface.show_text_only("我不自在的扯了扯腿上的黑色过膝袜，还好这双玛丽珍皮鞋的后跟没那么高……")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("所、所所以这房间里全都是仿造品吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我生硬的岔开话题，假装在仔细研究书架上的工艺品。")
	await novel_interface.show_text_only("拉斐尔看着我羞红的脸，满意的清了清嗓子，开启了一本正经的授课模式。")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Faberge_Egg_AuG.png")
	await novel_interface.show_dialog("法贝热彩蛋——150年前俄国珠宝大师法贝热打造的珠宝艺术中的经典之作。", "拉斐尔")
	await novel_interface.show_dialog("文献记载法贝热一生共制作了69颗彩蛋，现在随便一颗都能拍卖出过亿的高价。", "拉斐尔")
	await novel_interface.show_dialog("而有一只隐藏彩蛋，是1887年德、俄两国签订再保险条约后，沙皇为向威廉一世示好特意打造的。", "拉斐尔")
	await novel_interface.show_dialog("由于是为两国达成秘约打造的礼物，这个彩蛋从未被法贝热的团队记录在案。", "拉斐尔")
	await novel_interface.show_dialog("而那未被记录的第70颗隐藏彩蛋，现在就在——", "拉斐尔")
	novel_interface.change_background("res://assets/images/bg/Versailles/BG_Versailles_BRM_AuG.png")
	await novel_interface.show_text_only("拉斐尔的话说到一半忽然卡住了，满脸惊异的看着我。")
	await novel_interface.stop_music()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("就在……？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("嗯？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("raphael","perspire")
	await novel_interface.show_dialog("就在你手上拿着呢！！！", "拉斐尔")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Chaostic Daily.mp3")
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("哈？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我在这全是赝品的房间里随便拿起来的小玩意居然是惟一的真货吗？！")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("——啊啊啊啊哇！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("激动之下我捏着彩蛋的手指一发力，那东西“嗖”的飞了出去。")
	await novel_interface.show_text_only("我赶忙伸出双手去接，却像打排球一样把彩蛋托得更高了！！")
	await novel_interface.show_text_only("见状我立刻改换策略，想用手从两侧接住彩蛋，但左手不争气的比右手慢了半拍……")
	await novel_interface.show_text_only("啪——")
	await novel_interface.show_text_only("眼看下落中的彩蛋被我一巴掌扇了出去，径直飞向墙壁。")
	await novel_interface.show_text_only("房间里所有人都石化了。")
	await novel_interface.show_text_only("惊诧、紧张、愤怒等复杂的情绪快速在拉斐尔的脸上变换，她刚才说这东西值多少钱来着？")
	await novel_interface.show_text_only("不关键了，反正把我卖了也赔不起……")
	await novel_interface.show_text_only("我绝望的两腿同时发力，打算最后拼死挣扎一下。")
	await novel_interface.show_text_only("却发现身体仿佛瞬间失去重量，双腿趁上半身没反应过来，在地的反作用力下腾空而起——")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("欸——？？！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("接着我整个人以这种倒栽葱的姿态，像被卷入台风的纸片般，狠狠的向墙壁拍了过去。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("嘭！！")
	await novel_interface.show_text_only("一声闷响过后，小怜的身体好似穿过了墙体般，消失得无影无踪。")
	await novel_interface.show_text_only("只留下那颗彩蛋落打着转，安稳的落在了地毯上。")

	print("=== 帝国临在篇第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
