# traumareflex_ep02.gd - 创伤反射篇第02话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第02话剧本
	traumareflex_ep02_script()

func play_script():
	pass

# 创伤反射篇第02话 - 正式剧本
func traumareflex_ep02_script():
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("第五学院都市，学区东道。")
	await novel_interface.show_text_only("傍晚商业区热闹的街道旁，随处可见穿着附近私立学校校服的学生。")
	await novel_interface.show_text_only("一位身着女仆装的少女疾速穿过人群。")
	await novel_interface.show_text_only("由于临街就有一家24小时营业的女仆咖啡厅，她的这身装束并没引起太多注目。")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("主人！别跑那么快！遇到危险怎么办！","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("嘿嘿，没关系啦~\n难得能像今天这样自由自在呢。","斯库尔德")
	novel_interface.character_dark()
	await novel_interface.show_text_only("金发少女轻快的转过身，露出一个阳光般耀眼的笑容。")
	novel_interface.character_light(0.35,"normal")
	await novel_interface.show_dialog("放松一点嘛~！\n这里可是全世界最安全的地方，而且——","斯库尔德")
	novel_interface.change_expression("proud")
	await novel_interface.show_dialog("还有法贝拉在我身边呢~","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉追到小小的主人身边，看着她开心的样子只能无奈叹了口气。")
	novel_interface.show_character("fabiola_maid","smile")
	await novel_interface.show_dialog("偶尔……自由一下吗……","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("确实，新丰洲既不像纽摩利达斯允许全民持枪，也不像萨蒙顿那样满大街的难民和流浪汉……")
	await novel_interface.show_text_only("曾经势力很大的几个暴力团也纷纷在战争期间转移到莱博娜群岛。")
	novel_interface.change_background("res://assets/images/bg/Shot/storyBGPol.png")
	await novel_interface.show_text_only("并且由于下个月的『国际和平论坛』，现在全城的警备都有所加强。")
	await novel_interface.show_text_only("法贝拉也难得可以陪主人出门而不携带自动武器。")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("那也不能乱跑，还要注意交通安全，说了多少次别离开我的视线……","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("知道啦知道啦~","斯库尔德")
	novel_interface.character_dark()
	await novel_interface.show_text_only("金发少女打断法贝拉的唠叨，迎上去一把抱住她，并用脸蛋在对方胸前乖巧的蹭了蹭。")
	novel_interface.character_light(0.35,"perspire")
	await novel_interface.show_dialog("倒是你呀，还在里面穿着防弹衣啊——","斯库尔德")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("不会觉得太拘束吗？\n明明那么软……","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","blush")
	await novel_interface.show_dialog("欸？","法贝拉")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("好、好了啦……\n（小声）还有人看着呢……","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("嘿嘿，就知道法贝拉最好了~多亏你帮我伪造门禁骗过了大使馆的人才能溜出来。","斯库尔德")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("fabiola_maid","normal",0.25)
	await novel_interface.show_dialog("回去还不知道要被哈格蒂那个老头子怎么骂呢……不过『那个人』真的会在这一带出现吗？","法贝拉")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我记得是的……上次在天空酒店遇到的时候，我有强烈的感觉“就是那个人”。","斯库尔德")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("就是那个笨手笨脚的女仆？","法贝拉")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不过明明应该是男孩子才对，奇怪……","斯库尔德")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("咳咳……\n其实，那样的家伙也有不少啦~","法贝拉")
	novel_interface.character_light(0.35,"perspire")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("呃？","斯库尔德")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"mock")
	await novel_interface.show_dialog("就是那种虽然是男生，但是会打扮成女孩子……","法贝拉")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哦厚~？","斯库尔德")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"laugh")
	await novel_interface.show_dialog("有些穿上各种可爱的衣服化上妆真的超——级——萌！","法贝拉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("然后呢然后呢？","斯库尔德")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("天赋好的话连说话的声音也毫无破绽，在网络上也很受欢迎呢！！","法贝拉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("法贝拉的声音稍微有些兴奋的颤抖。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("嗯嗯我知道，法贝拉的Instagraph收藏夹我看过。","斯库尔德")
	novel_interface.change_expression("pleased")
	await novel_interface.show_dialog("要是这么说的话，确实有可能……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女认真的思考起来。")
	novel_interface.show_character("fabiola_maid","panic")
	await novel_interface.show_dialog("额……诶诶？","法贝拉")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("主、主人你你你你不、不要乱翻我的手机啊~！！","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","stare")
	await novel_interface.show_dialog("你的手机是加密线路嘛，不会被父亲的人监听，而且密码那么好猜——","斯库尔德")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("我可没让你把密码设成我的生日哦~","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德对法贝拉做了个鬼脸，然后扭过头。")
	await novel_interface.show_text_only("少女遥望着天边被夕阳染红的云，神情有些失落。")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("不管是男是女，都这个时间了，应该遇不到那个人啦……","斯库尔德")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("嘿嘿，就当出来兜兜风也不错嘛。","斯库尔德")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("fabiola_maid","normal",0.25)
	await novel_interface.show_dialog("……要回去了吗？","法贝拉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("先陪我去个地方吧，就在大使馆附近。","斯库尔德")
	await novel_interface.show_dialog("还记得三一教堂安东神父吗？","斯库尔德")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("我记得只见过一次……就是在纽摩利达斯那个从小就总会耐心听主人倾诉的神父？","法贝拉")
	novel_interface.character_light(0.35,"think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯，他昨天发来一段信息，不过内容只有一行字—","斯库尔德")
	await novel_interface.show_dialog("“新丰洲纪念教堂”","斯库尔德")
	novel_interface.character_light(0.35,"thought")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我用你的手机拨回去一直没人接听，稍微有点担心……","斯库尔德") #换行问题
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("嗯……这个教堂的地址在协约非武装区，又是大使馆附近，应该蛮安全的。","法贝拉") #文字错误
	novel_interface.change_2nd_expression("perspire")
	await novel_interface.show_dialog("不过主人是什么时候用了我的手机？居然完全没发现，我真是太失职了！","法贝拉")
	novel_interface.character_light(0.35,"perspire")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哈哈……不要在意啦……\n你那时候在专心研究料理呢……","斯库尔德")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("提到法贝拉的料理，斯库尔德的嘴角不自觉的抽搐了一下。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church_Dusk.png")
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	await novel_interface.show_text_only("二人面前的这座教堂是棕黄色的石质建筑，外墙有一幅巨大的宗教壁画。")
	await novel_interface.show_text_only("建筑顶部的十字架庄严肃穆，正面精雕细刻的拱门层叠出厚重的质感。")
	novel_interface.show_character("fabiola_maid","normal")
	await novel_interface.show_dialog("使馆附近还有这么大的教堂啊……","法贝拉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("skuld","normal",0.25)
	await novel_interface.show_dialog("新丰洲是『学院政体』嘛，这个科学至上的地方本来就没有多少宗教建筑——","斯库尔德")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("法贝拉将电子地图切换到『卫星图像』，想从卫星3D地图上了解一下建筑和附近的地形构造。")
	await novel_interface.show_text_only("这是她以前在攻击队养成的习惯。")
	novel_interface.show_character("fabiola_maid","thinking")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("skuld","normal",0.25)
	novel_interface.character_dark()
	await novel_interface.show_dialog("奇怪……这么大的教堂居然没有模型，因为国际领土的扫描管制吗？","法贝拉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("因为是最近才启用的吧？应该是为了下个月的大会才修建的，壁画还很新~","斯库尔德")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("下个月你父亲也会过来吧……身为『董事会』的成员之一。","法贝拉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("应该是……总之我们快进去看看吧！","斯库尔德")
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church.png")
	await novel_interface.show_text_only("走进教堂，仿佛步入了最古老的圣殿一般。")
	await novel_interface.show_text_only("大理石砌成的墙壁，森然罗列的巨大石柱，穹顶的油画和四周的玻璃彩窗构成了一种神圣的宁静。")
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("快来快来~这里的构造和三一大教堂很像哎。","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","panic")
	await novel_interface.show_dialog("等、等等我啦！","法贝拉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("斯库尔德开心的打量着四周，法贝拉进门时警觉的保持着教堂大门打开的状态。")
	novel_interface.character_light(0.35,"normal")
	await novel_interface.show_dialog("（那边台阶上还有没拆卸的木架……）","法贝拉")
	await novel_interface.show_dialog("（这座教堂应该还没完工吧？）","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉往前走了几步，感觉周身的空气产生了细微的波动，浑身立刻像起了静电一样汗毛竖立。")
	await novel_interface.show_text_only("这是她从小在南美战场上练就的生存本能，身体会比大脑更早一步察觉到危险。")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("（等等，有点不对劲……）","法贝拉")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("在法贝拉面前几米地方，斯库尔德突然沉默的呆在原地，双手下垂一动不动。")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("不好，快出去！！！","法贝拉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church_Stained_Glass1.png")
	await novel_interface.show_text_only("突然间，法贝拉觉得视线开始模糊，教堂两侧描绘圣经故事的彩绘玻璃变得异常闪耀。")
	await novel_interface.show_text_only("接着玻璃上的画面开始扭曲、变形、似乎要逐渐占据全部的视野。")
	await novel_interface.show_text_only("玻璃窗外的夕阳，逐渐蠕动变成诡异的色彩。")
	await novel_interface.show_text_only("颜色似乎逐渐化开，蔓延至听觉和嗅觉，像是一阵从远处传来逐渐靠近的沙沙声。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church.png")
	await novel_interface.show_text_only("法贝拉拼尽全力想要集中精神。")
	await novel_interface.show_text_only("等她回过神来，发现就在离自己不远的地方，斯库尔德已经倒在了地毯上……")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("可恶！！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她刚要冲过去，没想到一发力自己脚下就是一个趔趄。")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("……要看不清了……","法贝拉")
	await novel_interface.hide_character() 
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church_Stained_Glass2.png")
	await novel_interface.show_text_only("两侧的彩色玻璃，如融化的油画般扭曲逼近自己的视野。")
	await novel_interface.show_text_only("画面上的一切，都在以怪异的姿态重新呈现。")
	await novel_interface.show_text_only("女仆的身躯摇摇欲坠，眼看着就要陷入昏迷——而精神的侵染并未停下。")
	await novel_interface.show_text_only("透过玻璃的光线，将阴影投射在地板上，像是将一点点吞噬掉最后的理智。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Church.png")
	await novel_interface.show_text_only("法贝拉猛然蜷起身体，从靴子一侧拔出匕首。")
	await novel_interface.show_text_only("转瞬间找准位置避开主要血管，接着毫不犹豫的刺进了自己的大腿。")
	await novel_interface.show_text_only("鲜血染红了少女白暂的皮肤，而剧烈的疼痛换来片刻意识清醒。")
	await novel_interface.show_text_only("法贝拉咬着牙冲向斯库尔德，一把将她揽在腰间。")
	await novel_interface.show_text_only("她立刻转身，费力的走了几步。")
	await novel_interface.show_text_only("在她再度失去意识之前，向着大门的亮光方向，用尽全力将斯库尔德甩了出去……")
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("看着那个瘦小而模糊的身影被推出大门外，法贝拉的视野逐渐被黑暗吞噬……")
	
	print("=== 创伤反射篇第02话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
