# traumareflex_ep05.gd - 创伤反射篇第05话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep05_script()

func play_script():
	pass

func traumareflex_ep05_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/BAR.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("斯库尔德随几位探员来到了一间位于高层的酒吧。")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("这是哪……我的朋友她怎么样了？","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("请您在此稍候。","SID探员")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("酒吧的环境很舒适，从装修环境到地毯、沙发、靠垫、玻璃杯都透出高级的质感。")
	await novel_interface.show_text_only("在舒缓的背景音乐中，看着窗外城市的夜景，金发少女的心情稍稍平复了下来。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("呐，这儿的景色还不错吧？","莉琉")
	await novel_interface.show_dialog("我时不时就会来喝一杯~","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("你是……？","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("不过你还太小，给你点了果汁。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉没有回应对方的疑问，自顾自的叫侍应端来了饮料。")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("莉琉·冯·布劳恩博士……？","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("叫我莉琉就可以了~","莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("放心吧，你的朋友在医疗中心，虽然还在昏迷但应该没有生命危险。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉边说边将一台平板递给斯库尔德，屏幕上同时显示着四组法贝拉病房的高清实时监控。")
	await novel_interface.show_text_only("四个画面中能清晰的看到躺在病床上的法贝拉以及她身边的设备，有一个镜头恰好能看到病房窗外。")
	await novel_interface.show_text_only("虽然画面很小，但窗外一栋大厦顶部，那个巨大的红蓝两色广告牌格外显眼。")
	await novel_interface.show_text_only("斯库尔德稍稍扭头看向酒吧窗外，她所坐的位置恰好能看到同一栋建筑……")
	await novel_interface.show_text_only("金发少女低着头，看着平板中戴着呼吸面罩的法贝拉，身体开始微微颤抖。")
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("求你……一定要救救她……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她的声音有些哽咽，吸了吸鼻子。")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("法贝拉是我，是我最重要的朋友……\n求求你……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("似乎积累了很久的压力在一瞬间释放了出来，大滴的眼泪啪嗒啪嗒的滴在了平板上。")
	await novel_interface.show_text_only("莉琉看着抱着平板缩成一团的小姑娘，拿起酒杯喝了一口。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("这个调酒师真厉害……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她起身走到斯库尔德身边坐下，轻轻拍着小女孩的肩膀，凑到她耳边轻柔的说道——")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("你的父亲，是董事会成员吧？据说下个月还要来新丰洲参加和平论坛……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德依然低头抹着眼泪。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("你看咱们前面——那组吊灯上，有个微型相机。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("抽泣的声音渐渐停了下来。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("第二学园都市高层领导人的女儿和别国情报机构的主管亲密的说着悄悄话——","莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("这样的照片如果“不小心”传出去……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德抬起头叹了口气，伸手从茶几上拿了两块纸巾擦干眼泪，然后调整了一下呼吸。")
	await novel_interface.show_text_only("莉琉帮斯库尔德整理了一下头发，然后摸了摸她的头——")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("这就对了嘛~女孩子别老哭哭啼啼的。","莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("skuld","thought",0.25)
	await novel_interface.show_dialog("你这样会被人讨厌的……","斯库尔德")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("讨厌我的人干不掉我就可以了~","莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉笑容灿烂的回应道。")
	await novel_interface.show_text_only("斯库尔德拿起桌上的饮料喝了一口，与她在纽摩利达斯最喜欢甜品店的味道一模一样。")
	novel_interface.show_character("liliu_research","happy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("skuld","talk",0.25)
	await novel_interface.show_dialog("……你们连这种情报都不放过吗？","斯库尔德")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我就说调酒师很厉害嘛~","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("你刚才……心里在偷笑吧……","斯库尔德")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("斯库尔德有些不满的问道。")
	novel_interface.show_character("liliu_research","smile")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light(0)
	novel_interface.show_2nd_character("skuld","talk",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("还挺让人印象深刻的。","莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("不愧是在十岁时，就能把绑架自己的笨蛋绑匪挑拨到起内讧的小丫头。","莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("看着莉琉得意的表情，金发少女也不甘示弱。")
	novel_interface.show_character("liliu_research","happy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("skuld","stare",0.25)
	await novel_interface.show_dialog("你也没传说中的那么凶嘛。","斯库尔德")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("这里的灯光、音乐和香氛都是特意设计的吧？\n作为“审讯室”而言太温柔了！","斯库尔德")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉拿起酒杯又喝了一口。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("谁让你是小屁孩呢……","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("你明明占尽优势，却不一上来就摊牌，害我觉得搞不好可以试试……","斯库尔德")
	novel_interface.change_expression("thought")
	await novel_interface.show_dialog("不对，吊灯上根本没有什么微型相机吧！！","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着金发少女委屈的样子，莉琉轻轻搂住她。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("所以——","莉琉")
	await novel_interface.show_dialog("我救出了你重要的朋友，要怎么报答呢？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德抬起头，认真的盯着莉琉。")
	novel_interface.show_character("liliu_research","smile")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("skuld","normal",0.25)
	await novel_interface.show_dialog("……你要保证，不能有任何人知道我找过你。","斯库尔德")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("没问题，大使馆那边也会拿到一个完美的解释。","莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("斯库尔德摘下了自己钥匙形状的发卡，扭开底部的机关之后抽出一张微型存储卡。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("董事会里有人想要干预『重建计划』，虽然还不知道是谁，但应该是在下个月……","斯库尔德")
	await novel_interface.show_dialog("这是电子加密货币的账户所对应的实际控制人，应该是那些人的白手套。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉并没有掩饰自己惊讶的表情，朝远处打了个响指，侍应过来取走了存储卡。")
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("我一直劝父亲下个月不要来可他就是不听……但仅靠这些情报我也查不到更多东西了。","斯库尔德")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","smile",0.25)
	await novel_interface.show_dialog("我也想有你这样一个女儿了。","莉琉")
	novel_interface.character_light(0.35,"thought")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你能不能……不要把我父亲卷进来？","斯库尔德")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("如果他确实没牵涉其中的话~","莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("斯库尔德犹豫了一下，终于小心翼翼的问出了那个憋了很久的问题——")
	novel_interface.show_character("skuld","painful")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_research","speak",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("法贝拉的状况……很麻烦吗？","斯库尔德")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("……","莉琉")
	novel_interface.character_light(0.35,"painful")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我还以为只会是一个干部级别的人来审问……","斯库尔德")
	await novel_interface.show_dialog("看到SID主管亲自出面的时候，我就知道事情比想象的严重。","斯库尔德")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("医生们发现她的身体情况很特殊，如果你想救她的话，最好把她的情报都给我们。","莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯……能带我去见见她吗？我愿意全告诉你。","斯库尔德")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("好！","莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉拍了拍手，酒吧的窗户立刻变成全黑，中间浮现出SID的标志。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/BAR2.png")
	novel_interface.show_character("skuld","perspire")
	await novel_interface.show_dialog("这、这些窗户……都是屏幕？？","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("会实时追踪你的眼球，模拟视角变化~","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("所以…这里到底是哪？","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉拿起酒杯一饮而尽。")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("法贝拉就在楼下，咱们走吧~","莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/APC.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("运兵车内，攻击队员们正围着“新人”吵吵嚷嚷。")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("诶——？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("我听见了！还真是个妹子！！","男声A")
	await novel_interface.show_dialog("咱们小队终于有女……","男声A")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("咳咳！咱们队长不就是女的吗？","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("啊……","男声A")
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("哦？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉掏出一把匕首，在副驾驶座位背后的金属甲板上划了一下。")
	await novel_interface.show_text_only("金属与金属之间的撞击，伴随着火星发出一道刺耳的声音。")
	await novel_interface.show_dialog("法、法贝拉大姐最美！！永远支持大姐！！！","男声A")
	await novel_interface.show_text_only("见他们稍稍转移了注意力，我终于能松了口气，被这么多人盯着真不自在……")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("（这到底是怎么回事儿？？）","小怜")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("（——等等，我手里还拿着枪？？）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("这次护送任务就是在城里兜风，倒挺适合给新人混外勤记录的。","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("咳，那帮有钱人是不是总觉得有人惦记着，去个拍卖会都要武装护送……","男声A")
	novel_interface.show_character("fabiola_battle","wink")
	await novel_interface.show_dialog("反正『帕兰蒂尔』是商业机构，只要肯出钱，叫咱们帮他武装遛狗都可以。","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("听说这次咱们护送的是董事会一个老板的女儿？","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那个老板一开始居然还想出动反地雷M133，被交通局给怼回去了。","男声A")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("哈哈，打仗的时候亏心事做太多没有安全感吧？","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("坐在旁边的卡塞尔扭过头来上下打量着我。")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("话说看你这身……不会也是哪家的大小姐来体验生活的吧？","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("刚才我就想问，那是Newcon的蝰蛇式目镜战术面罩吗？","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("什么？？！","男声A")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("我记得这玩意儿在达奇的店里卖六万多……","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("有吗？？！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我差点把手里的枪丢地上。")
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("呵呵呵，我猜卡塞尔说的不是那个意思——","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉探过身来，将我腿上的战术背包拿开。")
	await novel_interface.show_text_only("下面传来阵阵凉意，这个熟悉的感觉……")
	novel_interface.show_character("fabiola_battle","wink")
	await novel_interface.show_dialog("呦厚~","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("坐在我旁边的卡塞尔咽了咽口水。")
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("虽然队里没有着装要求，不过穿着丝袜出勤的还是头一回见——","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("副驾驶传来一阵从座位上摔下来的声音。")
	await novel_interface.show_text_only("法贝拉继续饶有兴致的打量着我。")
	novel_interface.show_character("fabiola_battle","wink")
	await novel_interface.show_dialog("这身搭配，效果还真不错啊……","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("副驾驶位置的甲板传来一阵猛烈的拍打声。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("我说你也用不着这么兴——","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("轰！！！")
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("罗素话音未落，传来一声巨响。")
	await novel_interface.show_text_only("车内投影屏中，行驶在我们前面的那辆车突然腾空而起")
	await novel_interface.show_text_only("瞬间橘红色的火光冲天，那辆车迅速被火焰吞没。")
	await novel_interface.show_text_only("驾驶员立刻踩刹车，打死方向盘，车里的人一片东倒西歪。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("敌袭！！所有人！！下车戒备！！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("我靠！快下——","男声A")
	await novel_interface.show_text_only("——轰！！！！！")
	await novel_interface.show_text_only("又是一声巨响。")
	await novel_interface.show_text_only("紧接着一股巨力从前方袭来。") #文字顺序错误
	
	print("=== 创伤反射篇第05话结束 ===")
	await novel_interface.end_story_episode(0.5)
