# traumareflex_ep07.gd - 创伤反射篇第07话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep07_script()

func play_script():
	pass

func traumareflex_ep07_script():
	novel_interface.change_background("res://assets/images/bg/Shot/Soul_Sacrifice.png")
	await novel_interface.show_dialog("『世界终结之时』……的记忆？","小怜")
	await novel_interface.show_dialog("（等等，难道那次灾难波及到了全世界！？）","小怜")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("不过第二天大家不都好好的嘛——")
	await novel_interface.show_text_only("唯一被“终结”的只有我的……")
	await novel_interface.show_dialog("（呜呜呜呜……）","小怜")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.show_character("skuld","normal")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_dialog("只不过那段记忆中，你是男孩子哦~","斯库尔德")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_maid","awkward",0.25)
	await novel_interface.show_dialog("……诶？","小怜")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("到底是不是呢……小怜姐姐？","斯库尔德")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy_left")
	await novel_interface.show_dialog("额？啊啊~~！\n那、那个……我不——","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("恍惚中，我脑中快速闪过一堆《女装变态夜半潜入幼女病房》之类的新闻标题。")
	await novel_interface.show_text_only("斯库尔德慢慢靠近，露出一幅“被我逮到了吧？”\n的得意表情。")
	await novel_interface.show_text_only("我却有种偷偷穿女孩子的衣服上街，暴露之后被人逼到暗巷墙角的感觉……")
	await novel_interface.show_text_only("我下意识的捂住了胸部往后退，又觉得有点不对，然后试图用手挡住裙子……")
	novel_interface.show_character("ren_maid","shy")
	await novel_interface.show_dialog("（这么短完全挡不住嘛！！）","小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("（诶？等等……我在慌什么啊！）","小怜")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("我、我就是女生嘛~~\n啊哈哈哈哈……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我现在应该和男生的时候外貌差蛮多的。")
	await novel_interface.show_text_only("而且莉琉应该已经做足了情报修饰工作，就算是顶级机构也不可能把我和以前的身份联系起来吧……")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("我记得新丰洲废墟中的那个背影，确实是个男孩。","斯库尔德")
	await novel_interface.show_text_only("斯库尔德走到我的面前，目不转睛的盯着我。")
	novel_interface.show_background("res://assets/images/bg/Fabiola/YumeRen.png")
	await novel_interface.show_dialog("一阵白光之后，我看到了你的脸——","斯库尔德")
	await novel_interface.show_dialog("虽然只是一瞬…但我绝对不会记错！","斯库尔德")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.show_character("skuld","proud")
	await novel_interface.show_dialog("你，就是我记忆中的那个人。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我被面前这个瘦小女生的气势压得后背紧紧贴在走廊墙壁上。")
	await novel_interface.show_text_only("怪不得那些经典奇幻小说中，再宏大的世界观也最多就能容下那么一两个预言家。")
	novel_interface.show_character("ren_maid","sob")
	await novel_interface.show_dialog("（这种能力简直像作弊一样嘛……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("但毕竟只是支离破碎的片段，而且记忆总会被我们不停的修饰——","斯库尔德")
	await novel_interface.show_dialog("仅凭脑海中的一张脸，我也不能确认你是男是女。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女稍稍探回身体，给了我一些喘息的空间。")
	novel_interface.show_character("skuld","stare")
	await novel_interface.show_dialog("不过刚才抱你的时候确认过了，无论身体、骨架还是头发——","斯库尔德")
	await novel_interface.show_dialog("虽然原因不明，但小怜姐姐现在绝对是如假包换的女孩子。","斯库尔德")
	novel_interface.change_expression("proud")
	await novel_interface.show_dialog("还……软软的呢~","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德露出一个调皮的笑容。")
	novel_interface.show_character("ren_maid","awkward")
	await novel_interface.show_dialog("软、软的……？什么啊！！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("刚才她主动抱我，还把头埋在我胸口，就是为了确认这些事吗？")
	await novel_interface.show_text_only("而且那么短的时间里，连头发都检查过了……")
	novel_interface.show_character("ren_maid","sob")
	await novel_interface.show_dialog("（感觉我回去又要被莉琉骂了！！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德抬起头，清了清嗓子。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("那……我们就是彼此交换过秘密的朋友了，对吗？","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她小心翼翼的问道，眼神在期待着我的回复。")
	await novel_interface.show_text_only("我心里忽然抽动了一下，直觉告诉我这才是她卸下伪装和防御的样子。")
	await novel_interface.show_text_only("她应该从小就生活在不得不怀疑提防周围所有人的环境中吧？明明只是十二三岁的小女孩……")
	await novel_interface.show_text_only("虽然只是模糊的预言能力，但不知会被多少心怀不轨的人觊觎。")
	await novel_interface.show_text_only("这个秘密一旦被公开，她所面临的处境可想而知。")
	await novel_interface.show_text_only("而她却在很可能会被莉琉监听的情况下，将这种能力告诉了我……")
	await novel_interface.show_text_only("如果可以的话，她应该很希望跟人坦诚相待吧？")
	novel_interface.show_character("ren_maid","gratified")
	await novel_interface.show_dialog("嗯……你的秘密我会好好守护的。","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我伸出手，做了个“拉勾”的手势。")
	novel_interface.show_character("ren_maid","blush")
	await novel_interface.show_dialog("因为我是你『最特别』的那个人嘛！！","小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（这句台词说出来简直蠢爆了……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德先是一愣，接着噗嗤一下笑了出来。")
	await novel_interface.show_text_only("然后我们二人的小拇指勾在一起。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/BAR.png")
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	await novel_interface.show_text_only("爱衣走进酒吧，一眼就看到莉琉正坐在窗边的沙发里，拿着一杯酒轻轻摇晃。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("原型机的『保险措施』已经按你的要求配置好了。","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("还挺快的嘛~","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("随时检查小怜迷走神经的应激反射，有异常就立刻切断链接……这样会不会太粗暴了？","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("只能起到“保险丝”的作用吧……现在科学界对记忆的作用形式的理解还是太少了。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("也不知道会不会像那部电影里所说，“一旦出现互相矛盾的记忆，大脑就会烧掉”之类的……","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣一脸跃跃欲试——")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("偷偷找几十个家伙做个试验不就知道了~","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉举高酒杯，透过灯光端详着其中球形的冰块。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("我猜不会——","莉琉")
	await novel_interface.show_dialog("即使同时拥有两套完全矛盾的记忆，人也总会为自己找到一条出路。","莉琉")
	await novel_interface.show_dialog("用“前世记忆”或“平行宇宙”之类的说法来安慰自己，或者干脆说自己受到了神谕。","莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("没准还能骗来一群信徒呢~","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("话是这么说……","爱衣")
	await novel_interface.show_dialog("但你不是还特地要求播磨脑研的人这次不要激活她的前额叶皮质，保证记忆区被阻断嘛……","爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("这样她醒来之后就会像做梦一样，很快就忘掉绝大部分的情报吧~","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉扭头看了看窗外模拟的城市夜景。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("法贝拉从小是童子军，被南美一个军阀所收养。","莉琉")
	await novel_interface.show_dialog("有些情报她不一定能承受得了~","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("哦~？","爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("你不是要斯库尔德去亲自取得小怜的同意吗，进展如何了？","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("那个笨蛋估计不到五秒就会被小丫头拿下吧~","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("真是简单易懂的青春期呢……","爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("那你为什么还多此一举——","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("说到一半，爱衣突然恍然大悟的样子。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("你是要给小怜埋下一个记忆锚点？","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉笑了笑，拿起酒杯小酌一口。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("有时候可能老方法更有效哦。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("你对她也太溺爱了吧~","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("时间差不多了，咱们走吧。","莉琉")
	
	print("=== 创伤反射篇第07话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
