# traumareflex_ep09.gd - 创伤反射篇第09话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep09_script()

func play_script():
	pass

func traumareflex_ep09_script():
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("――什么？嫌疑人死了！？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("对方将寓所改造得像个堡垒，并在收容队赶到后用重武器疯狂攻击……","SID探员")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("收容队装备的不都是非致命武器吗？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是的，目标身上未发现致命伤。","SID探员")
	await novel_interface.show_dialog("推测死因是神经类药物摄入过量或失血过多……","SID探员")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("……我明白了，你下去吧。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("是。","SID探员")
	await novel_interface.show_text_only("正当莉琉有些烦躁的翻阅着嫌疑人资料，爱衣走进了指挥室。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("小怜已经顺利潜入了？","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("嗯，应该已经稳定了~","爱衣") #文字错误
	await novel_interface.show_dialog("这是……嫌疑人的尸检报告？","爱衣")
	await novel_interface.show_dialog("安东尼奥·何塞·乌尔基萨……七年战争期间在南美活跃的军阀，只能勉强算个小头目吧。","爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("可惜药物把他整个脑子都烧坏了，不然正好可以试试看用那个设备“拷问”一下的。","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣手中拿着一摞文件，边翻边十分惋惜的说道。")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("南美的话……果然袭击目标是法贝拉吗？","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("还不能确定。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉盯着在大屏幕上展开的目标资料，神色凝重的摇了摇头。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("从教堂找到的化学散布装置里，检测到微量的放射性标记物。","莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("然后很轻松的就找到了有同样放射性标记特征的地理位置……就在新丰洲市内。","莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","dizzy",0.25)
	await novel_interface.show_dialog("哦呀？自己主动送到嘴边的犯人呢~","爱衣")
	novel_interface.character_light(0.35,"angry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所以才不可信――","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("安东尼奥……这个家伙有伤害法贝拉的动机吗？","爱衣")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("有，而且非常充分。","莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("战争的第二年，南美经济全线崩溃，之后就陷入了长期的军阀混战……","莉琉")
	await novel_interface.show_dialog("当时法贝拉在战乱中失去双亲，被一个上校收养后一直在军队长大。","莉琉")
	await novel_interface.show_dialog("后来她展现出了野兽般的战斗天赋，还成了年龄最小的亲卫队员。","莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("据说她曾单枪匹马潜入敌方阵地，悄无声息的干掉了对面的指挥官——安东尼奥的长子。","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wink")
	await novel_interface.show_dialog("这样的动机倒是说得过去……","爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉调出了一张男性的军装照，并示意爱衣抬头看屏幕。")
	novel_interface.show_character("liliu_research","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ai","wink",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("而收养法贝拉的那个上校，就是卡洛斯·布兰科。","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("那个“丘伦河屠夫”布兰科！？","爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("六大学园都市组成联合议会不久，就发生了震惊全球的“丘伦河大屠杀”。")
	await novel_interface.show_text_only("4.6万名平民在丘伦河畔被处决，血液一路沿河而下，将下游的安赫尔瀑布染成了红色。")
	await novel_interface.show_text_only("连续几周全世界的媒体轮番报导，并认为当时最大的军阀卡洛斯·布兰科是那次大屠杀的主谋。")
	await novel_interface.show_text_only("一幕幕触目惊心的画面激起了民众积压已久的反战情绪，“丘伦河屠夫”的外号也被迅速传开。")
	novel_interface.change_background("res://assets/images/bg/Shot/storyBGPol.png")
	await novel_interface.show_text_only("很快，联合议会宣布卡洛斯·布兰科犯有反人类罪及种族灭绝罪，并进行了第一次联合军事行动。")
	await novel_interface.show_text_only("随着一枚LAnCEr钻地弹精准的打入布兰科藏身的山洞，南美的军阀割据时代也就此结束。")
	await novel_interface.show_text_only("联合议会借此机会树立了和平与正义的形象，并宣布将六个成员国首都改名为『学园都市』。")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("――至少，历史书上的官方版本是这样的。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉嘴角划过一抹冷笑，爱衣也心领神会的点了点头。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("那之后，南美的其他六个军阀就像约好了一样人间蒸发，地盘也乖乖交给联合议会的傀儡接管……","爱衣")
	await novel_interface.show_dialog("你一定知道里面的内情吧？","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣像只好奇的小猫一样凑近莉琉，用胳膊肘蹭了蹭她的腰。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("屠杀确实发生过，只不过死者分别来自那六个军阀的地盘。","莉琉")
	await novel_interface.show_dialog("他们不约而同的将人运到一处然后……","莉琉")
	await novel_interface.show_dialog("是因为有人许以重金给他们做这样的指示。","莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("而唯一拒绝接受的，就是卡洛斯·布兰科。","莉琉")
	await novel_interface.show_dialog("于是他就被塑造成为这个时代的“必要之恶”。","莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("做出指示的难道是——！？","爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("爱衣恍然大悟。")
	novel_interface.show_character("liliu_research","speak")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ai","think",0.25)
	await novel_interface.show_dialog("所以那几个人间蒸发的军阀，应该是达成交易拿了一大笔钱，然后改名换姓逍遥快活去了……","爱衣")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("而这些送到嘴边的证据，一开始应该是给联合议会保安军准备的。","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("联合议会发现安东尼奥又跑回来报仇的话，一定希望尽快结案而不会深查。","爱衣")
	await novel_interface.show_dialog("怪不得有那么多别扭的地方……","爱衣")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哦？说说看~","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("死者血液里检出的致幻剂，与法贝拉体内检出的类型一致。","爱衣")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这我知道。","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("还检测到一种兴奋剂，是军阀常用来保持士兵神经机警敏锐的药物——这种药物过量才是其死因。","爱衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这些在报告里也有写。","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("那种兴奋剂可以放大神经感官，不管是听力、触觉都会变得十分敏感——","爱衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("以他的血药浓度，被橡胶子弹打中的话，痛感应该会像被炮弹击中一样才对。","爱衣")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("但交战持续了20分钟，目标先后数次被击中……","莉琉")
	await novel_interface.show_dialog("根据现场录像，从交战第五分钟就能清晰的看到目标，期间未有注射药物的动作。","莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("解剖也没发现神经系统病变……","爱衣")
	novel_interface.change_2nd_expression("blush_dizzy")
	await novel_interface.show_dialog("这、这难道就是抖M的极致吗！？","爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉熟练的拿起纸卷，敲了下爱衣的脑袋。")
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("呜……对了，将斯库尔德带到公园的人查到了吗？","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("那个人完美的避开了每一个摄像头，如果是绑架犯的话手艺堪称是教科书级的。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("熟悉附近的摄像头位置，背着小萝莉在市区内走了两公里还不会被人怀疑嘛……","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("线索就这么多了。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉一只手摸着下巴思考。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("如果安东尼奥是被特意安排的“凶手”……","莉琉")
	await novel_interface.show_dialog("估计幕后主使指向的是法贝拉『魔女』的身份。","莉琉")
	await novel_interface.show_dialog("我估计他们并没达到目的。","莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("但因为样本太宝贵，与其让她死在自己手上不如留给联合议会……","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("所以才消耗了一只这么宝贵的“替罪羊”吗？","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("体内寄宿了火焰魔法的魔女……\n『活的信息』……","莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("信息！ ？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉看向爱衣，二人同时明白了什么。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("如果那些人的目的是窃取信息的话……","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("播磨脑研的设备所用的技术是基于一些公开发表的论文作为原理的……","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("那么他们应该和我们遇到了相同的问题――","莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/TheWall.png")
	await novel_interface.show_text_only("前四名潜入法贝拉大脑的探员，看到的都是那堵无限延伸的墙壁。")
	await novel_interface.show_text_only("就像防止入侵者的防火墙一样……")
	await novel_interface.show_dialog("如果是攻击性防火墙的话——","爱衣")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("爱衣，随时准备唤醒小怜。","莉琉")
	
	print("=== 创伤反射篇第09话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
