# traumareflex_ep12.gd - 创伤反射篇第12话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第12话剧本
	traumareflex_ep12_script()

func play_script():
	pass

# 创伤反射篇第12话 - 正式剧本
func traumareflex_ep12_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	novel_interface.change_music("res://assets/audio/music/War Drum.mp3")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("你好呀，小怜姐姐。","斯库尔德")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("我们又见面了~","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("诶？斯库尔――","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我突然觉得不对，把说到一半的话吞了回去。")
	await novel_interface.show_text_only("这是法贝拉两年前的记忆，那时我和斯库尔德应该没见过面吧。")
	novel_interface.show_character("ren_mercenary","stare")
	await novel_interface.show_dialog("（难道是因为她那种特殊的预言能力？）","小怜")
	await novel_interface.show_dialog("（斯库尔德确实说过，在记忆中看到过我……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("那个……你就是法贝拉吧？\n还有罗素、卡塞尔。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德转向其他攻击队员，一脸天真无邪的说\n道。") #换行问题
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("哦？连我们这些护卫的名字都记下了？\n不愧是那位老板的女儿~","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("（哈哈哈，我好像想多了……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("你好你好！\n我都不知道，您真人比照片上漂亮多――","卡塞尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("罗素一记肾击打断卡塞尔的发言。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("省省吧，刚在拍卖会上你没少看。","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德被卡塞尔的样子逗得咯咯直笑，众人也稍稍舒缓了战斗的紧张情绪。")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("大家听着，支援部队还被拖在外围，我们要自己想办法抵达撤离点。","培尔纳德")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("现在咱们混编为一队，由培尔纳德队长指挥。","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉对培尔纳德点点头，并把几个步枪弹匣递给他，自己则拿起霰弹枪。")
	novel_interface.show_character("ren_mercenary","worry")
	await novel_interface.show_dialog("（很信任的样子，是老战友吗？）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("一会很可能还要应对战斗，现在开始全员修整五分钟，清点检查装备弹药。","培尔纳德")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("刚才我就偷偷检查过，在随身的挎包里还有3个弹匣，1个小型急救包和1罐气凝胶喷雾。")
	await novel_interface.show_text_only("气凝胶喷雾是像发胶一样的罐装喷剂，喷出的泡沫在接触空气后会快速膨胀并凝固。")
	await novel_interface.show_text_only("之前在天空酒店安妮用气凝胶封锁过客房大门。")
	await novel_interface.show_dialog("（我怎么还带了这种东西……）","小怜")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	await novel_interface.show_text_only("大家清点装备时，法贝拉将培尔纳德拉到马路对\n面。") #换行问题
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("这次的敌人显然是有备而来……","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("嗯，对方提前掌握了我们的护送路线图，而且放出假消息疏散民众的时间也把控的恰到好处。","培尔纳德")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("也就是说……他们连拍卖会的进度也知道？","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("路被炸断之后，你们那边遇到多少敌人？","培尔纳德")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("一个狙击手和一架『黄雀』，你们呢？","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("三个狙击手，四架挂载自动武器的无人机。","培尔纳德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉才发现培尔纳德风衣上的血迹，有些紧张的问道。")
	novel_interface.show_character("fabiola_battle","panic")
	await novel_interface.show_dialog("那么多敌人！？你没受伤吧……","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("只是轻伤，莉娜枪法很好，把那几个狙击手一个个都干掉了。","培尔纳德")
	await novel_interface.show_dialog("这一带是高楼密布的市区，狙击手要提前就位，说明对方知道“包裹”在阿尔法小队的车上。","培尔纳德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉屏住了呼吸――")
	novel_interface.show_character("fabiola_battle","panic")
	await novel_interface.show_dialog("不是那位大小姐从拍卖会出来之后，才临时决定坐哪辆车的吗？","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("我们可能被渗透了。","培尔纳德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("培尔纳德和法贝拉在阴影中看向正围着金发大小姐有说有笑的四名攻击队员。")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("这次行动应该是针对她，但目的并不是击杀。","培尔纳德")
	await novel_interface.show_dialog("对方有太多机会将我们都干掉了。","培尔纳德")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","bored")
	await novel_interface.show_dialog("……是想绑架？","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("那至少要派出地面部队或者载人战车吧。","培尔纳德")
	await novel_interface.show_dialog("总之咱们接下来尽量避免开阔地，借着建筑物掩护前进。","培尔纳德") #原文多字
	await novel_interface.show_dialog("你保护好自己。","培尔纳德")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("嗯……你也是。","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("马路另一侧，我正在听他们三人和斯库尔德讨论着今晚的拍卖会。")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("今天你拍下来的那件古文本，花了三千六百万！？","卡塞尔")
	await novel_interface.show_dialog("不就只是一张发黄的纸卷吗……上面写了未来十期的乐透号码？","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("别在这儿一惊一乍的，你这种笨蛋又不懂文物的价值。","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","pleased")
	await novel_interface.show_dialog("其实我也不太懂文物啦，只是有强烈的“应该买下来”的感觉……","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("哦哦~我每次看到GTR的时候也有这种感觉！","卡塞尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("卡塞尔做出一副“我理解了”的样子。")
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("（你理解个头啊！）\n（斯库尔德的感觉是是因为她自身的能力吧……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("战争期间确实流失了不少古代文本，前段时间阿基米德的手稿也拍了上千万呢。","莉娜")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("那你买的这个是？","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("碳14鉴定说有几千年的历史，是用古文字撰写的\n食谱之类的东西，其实我也看不懂啦……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("说着，斯库尔德从手上那个黑色鳄鱼皮包裹的精致文件夹中抽出了一张发黄的纸页。")
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("（就这么直接拿出来了吗？！ ）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("发黄的纸上有像纺织物一样的纹路，密密麻麻的写着奇怪的字符，还有类似章鱼触手的配图。")
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("这是莎草纸？也不像……几千年的话保存的也太完整了。","莉娜")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("不、不用戴个手套什么的吗？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("没关系，表面有气密喷雾涂层~","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("嚯嚯，三千六百万的食谱得是什么菜……","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("罗素你还不快记下来让你老妈学学，上次吃得我差点住院。","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("去你的吧，那是因为你吃了整整一锅。","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("你说……那帮人是不是来抢这个的？","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("一架『黄雀』的造价就得两千多万吧，除非这上面有什么隐藏的高价值信息……","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld")
	await novel_interface.show_dialog("隐藏信息？","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德将手稿拿高，迎着对面大楼射下来的探照灯观察。")
	await novel_interface.show_text_only("他们三人立刻围了上去，我也忍不住去凑热闹。")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("嗯……","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("似乎……","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("没什么特别的？","莉娜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	novel_interface.show_character("ren_mercenary","worry")
	await novel_interface.show_dialog("其实，要说有什么特别的话……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("从我们到这条街开始，就觉得有点奇怪。")
	await novel_interface.show_text_only("虽然这一带有夜店、酒吧和很多广告灯箱……")
	novel_interface.show_character("ren_mercenary","worry")
	await novel_interface.show_dialog("为什么这个探照灯照射的位置，既没有广告也不是哪家店的门口呢？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("……还真是。","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("快——！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("马路对面的法贝拉突然朝我们大声喊道。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("快闪开！！！！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("轰——！！！！")
	await novel_interface.show_text_only("我们才刚散开两步，一个巨大的黑影紧接着从天而降，重重的砸在探照灯照射的地面上。")
	await novel_interface.show_text_only("在地板碎裂扬起的烟尘中，传出不祥的金属摩擦和机械关节转动的噪音。")
	await novel_interface.show_text_only("首先探出烟雾的，是一只泛着淡蓝色金属寒光的尖刺。")
	await novel_interface.show_text_only("从尖刺向后延伸，工整平滑的机械臂逐渐露出支撑其庞大身躯的粗壮关节。")
	await novel_interface.show_dialog("那……是什么东西！","小怜")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Big_Spider.png")
	await novel_interface.show_text_only("尽管法贝拉早就提醒敌人可能有机械部队，但在看到利爪主人的全貌时，我依然倒抽了一口凉气。")
	await novel_interface.show_text_only("由八只灵活而锋利的金属尖刺构成的“脚”，支撑着不停发出机械异响的“躯体”。")
	await novel_interface.show_text_only("那是一只全身由合金覆盖的机械蜘蛛，高度接近一米，每只脚末端的尖刺都能轻易刺穿人类的躯体。")
	await novel_interface.show_text_only("这只周身散发着杀戮气息的机械猎食者，正用头部闪烁的红点凝视着我们。")
	await novel_interface.show_dialog("开玩笑吧……","莉娜")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	await novel_interface.show_text_only("法贝拉和贝尔纳德立刻举起手中的武器开始射击。")
	await novel_interface.show_text_only("大量铅弹打在合金装甲上，溅起阵阵火花。")
	await novel_interface.show_text_only("机械蜘蛛似乎并未受到什么伤害，摇了摇身体转向法贝拉，朝着街对面以极快的速度飞扑过去。")
	await novel_interface.show_text_only("培尔纳德向一侧闪开，法贝拉低下身体一个滑铲从蜘蛛下腹部钻了过去。")
	await novel_interface.show_text_only("我身后忽然爆出一声巨响把我吓了一跳，莉娜也开始举枪射击。")
	await novel_interface.show_text_only("蜘蛛的腿被打得震了一下，然而莉娜的反器材狙击枪也只能在它的合金装甲上留下一个浅坑。")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("（怎么办……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("气凝胶？不行，还没喷完我就变成烤串了。")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("（快、快想想……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("此时那个东西正奔向培尔纳德，后者则利落地打破一扇停在路边面包车车窗钻了进去。")
	await novel_interface.show_text_only("还没来得及发动引擎，车门就被机械蜘蛛整个卸了下来。")
	await novel_interface.show_text_only("培尔纳德看准时机从空档滚出车外，在被反扑的前一刻扛起了掉在地上的车门。")
	await novel_interface.show_text_only("蜘蛛脚的尖刺穿过车门后难以移动，培尔纳德被压在地上，满脸通红的想固定住车门的位置。")
	novel_interface.show_character("ren_mercenary","shout")
	await novel_interface.show_dialog("只能试试看了！！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我心一横，将整罐气凝胶朝着蜘蛛丢了出去。")
	await novel_interface.show_text_only("同时将短剑冲锋枪的保险拨到连发模式，对着飞在空中罐子的方向，死死的扣住了扳机……")

	print("=== 创伤反射篇第12话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
