# traumareflex_ep15.gd - 创伤反射篇第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第15话剧本
	traumareflex_ep15_script()

func play_script():
	pass

# 创伤反射篇第15话 - 正式剧本
func traumareflex_ep15_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Anton's_Blindness.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("安东盲目症。")
	await novel_interface.show_text_only("这种疾病表现为：患者虽已失明，却仍坚定地认为自己能够看见。")
	await novel_interface.show_text_only("即使身上有多处因磕碰而造成的外伤，病人依然会脑补虚构出各种情节将之合理化。")
	await novel_interface.show_text_only("大脑就是这样——为了给无法接受的现象一个合理的解释，会不停编造虚假的记忆。")
	await novel_interface.show_text_only("这是人类在面对未知事物时一种自我保护的原始本能。")
	await novel_interface.show_text_only("或许因为我们还没做好准备，直面星空背后的那片黑幕……")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Factory.png")
	await novel_interface.show_text_only("如果那些蜘蛛不是一开始袭击我们的人所安排……")
	await novel_interface.show_text_only("那如此大规模的机械兵器就这么堂而皇之的出现在第二学园都市，简直不可思议——")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("（还有其他人在影响这段记忆吗？）","小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("或者其他“有意识的东西”。")
	await novel_interface.show_text_only("我记得行动之前……")
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("斯库尔德说法贝拉是体内寄宿了火焰魔法的魔女。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","stare")
	await novel_interface.show_dialog("寄宿……？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("与伊露卡那种能直接操作电场的类型不同，法贝拉的状况是『某种庞大的信息』将她作为了宿主。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("怎么说的好像活物一样……","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("确实如此。当信息的密度足够大，熵值足够低，就很可能产生自我意识。","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("随着法贝拉自身的理性离线，那种『活的信息』开始慢慢侵蚀她的身体……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("活的信息……侵蚀？")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Factory.png")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("难道说——！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那些机械蜘蛛，是寄宿在法贝拉体内的东西所制造的！？")
	await novel_interface.show_text_only("因为那个『意识体』扭曲了法贝拉的记忆，所以我才不得不介入吗……")
	await novel_interface.show_text_only("但重复那么多次，每一次我都失败了吧…")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("（到底，要怎么对付那种东西……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我不安的检查着身上所剩的装备，如果每件道具都是如此重要的话——")
	await novel_interface.show_text_only("唯一还没使用的，只剩下一个小型急救包。")
	novel_interface.show_character("ren_mercenary","sob")
	await novel_interface.show_dialog("（怎么想都是“微量回复生命”的低级道具吧！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我摸着挎包里那个柔软包装的立方体小袋子。")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("（等等……）\n（这个手感——）","小怜")
	await novel_interface.hide_character()
	
	# 战斗部分剧本
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("糟了！那群东西爬上来了！！","罗素")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/War Drum.mp3")
	await novel_interface.show_text_only("我循声看过去，十几只蜘蛛已经顺着电梯井爬了上来，后面还有更多在往上涌。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("准备迎击！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突击队员立刻进入战斗状态开始射击。")
	await novel_interface.show_text_only("法贝拉单手给霰弹枪上膛，左手反持匕首，将枪架在左手小臂上开始射击。")
	await novel_interface.show_text_only("她先是两枪干掉了两只蜘蛛，然后用匕首和右脚直接扯碎了第三只，似乎要将满腔怒火都发泄出来。")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("我快没子弹了！！","卡塞尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("罗素将弹匣扔给卡塞尔。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("最后一个了！你去看看货架那边有什么能当武器\n的！","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("卡塞尔换上弹匣一边点射一边后退，闪进一排货柜后面。")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("斯库尔德，站到我身后！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我紧握着冲锋枪，调成单发模式。")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("（这是最后十几发子弹了……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("嘿！罗素你猜我发现什么了！！\n一整箱15年前的波兰蒸馏伏特加――","卡塞尔")
	await novel_interface.show_text_only("货架后突然传来卡塞尔兴奋的声音。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("白痴，你是想做燃烧弹吗？","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("不行吗？这玩意上写着酒精含量96%啊，真的是\n给人喝的吗。","卡塞尔")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("莉娜刚才确实说过，那些小蜘蛛是靠热成像探测目标的……","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("『莫洛托夫鸡尾酒』可不是那么好做的――","法贝拉")
	await novel_interface.show_dialog("需要密封好瓶口，否则很容易先烧到自己，并且还要布条之类能吸水的引信。","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉此时已经干掉了近十只小蜘蛛，但更多的蜘蛛正从电梯口争相涌进这间仓库。")
	await novel_interface.show_text_only("随着弹药不断消耗，我们三人只能逐渐收拢阵型后撤。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("咱们的衣服都是防水加强纤维的，去哪找合适的材料，撕自己的内裤吗？","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("那、那个……试试这个！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我将那个“小型急救包”丢给卡塞尔，然后立刻转身跑开。")
	await novel_interface.show_dialog("嗯？什么玩意儿？","卡塞尔")
	await novel_interface.show_dialog("F系列……18枚，棉柔无荧光剂……","卡塞尔")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("别……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("生理中……敏感肌，250mm……\n难道是——？？！","卡塞尔")
	novel_interface.show_character("ren_mercenary","shy_left")
	await novel_interface.show_dialog("不要念了啊笨蛋！！！！！！！","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("哦？那个应该再合适不过了~","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉向我投来一个微妙的眼神。")
	await novel_interface.show_dialog("我靠这么好用！？\n吸水之后还会膨胀，正好能封住瓶口！","卡塞尔")
	novel_interface.show_character("ren_mercenary","sob")
	await novel_interface.show_dialog("（不需要这么详细的说明！拜托了！！！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("不一会，卡塞尔带着做好的燃烧弹意气风发的从货架后跑出来。")
	await novel_interface.show_text_only("在法贝拉的指挥下，我们掩护卡塞尔突进到电梯口附近。")
	await novel_interface.show_text_only("几发燃烧弹丢过去，电梯口马上成为一片火海。")
	await novel_interface.show_text_only("之后我们用尽最后的弹药和近战武器，终于将仓库内的小蜘蛛清理干净。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("暂时应该能拖一会了……","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("罗素的胳膊上被划出几个口子，卡塞尔的腿也被狠狠的扎了一下。")
	await novel_interface.show_text_only("法贝拉在激战后稍稍平复情绪，走到我身边一言不发的拍拍我的后背。")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("（什、什么意思？）","小怜")
	await novel_interface.show_dialog("（为什么她那么意味深长的看着我笑啊~~）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("弹匣里只剩下最后两发子弹。")
	await novel_interface.show_text_only("虽然暂时渡过了危机，但现在已经用掉所有的道具了。")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("（该不会上一次，我就是止步于此吧……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我不安的盯着电梯口那片橘红色的火光，一个疑问在心中盘旋――")
	await novel_interface.show_text_only("这样一次次的轮回，真的有用吗？")
	await novel_interface.show_text_only("可能我重复再多次，有再多的装备都无济于事……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我会被永远困在这里吗。")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	await novel_interface.show_text_only("……")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("你要尽量找到目标回忆中的关键信息，不能放过每一个细节。","莉琉")
	await novel_interface.show_dialog("目标现在处于深度昏迷中，我们对她的过往经历了解不多，不知道她被锁定在了哪段回忆中。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("就是说，即使目标要去洗澡，你也不能放过哦~！","爱衣")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("不对，这段对话到底是发生在医院还是在SID总部来着……")
	await novel_interface.show_text_only("我的记忆也开始模糊了吗？")
	await novel_interface.show_text_only("莉琉所说的『关键信息』到底是什么……")
	await novel_interface.show_text_only("或者她…真的说过这段话吗……")
	await novel_interface.show_dialog("小怜姐姐~","斯库尔德")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Factory.png")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("小怜姐姐――","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德的小手扯了扯我的衣服，将我的思绪拉\n回。")
	novel_interface.show_character("ren_mercenary","gratified")
	await novel_interface.show_dialog("嗯？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("刚才你给卡塞尔的这个……是什么呀~？","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德手里拿着一个方形的无纺布包，一脸好奇的看着我。")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("啊……那个——","小怜")
	await novel_interface.show_dialog("（救命！别当着大家的面问我这种事啊！！）","小怜")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("你、你还没到用那个的年纪啦……啊哈哈哈哈。","小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("（其实我也是新手……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我生硬的想要支开话题，总觉得要是给这么小的女孩子讲这种东西的话，我就……")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("这么小的女孩子——？")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("（我第一次见到斯库尔德时，她只比伊露卡稍微大一点吧……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("可这是法贝拉两年前的记忆……两年的时间里，这个年纪的小孩子应该有很大变化才对。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_text_only("但现在我面前的斯库尔德，与之前在医院见到的一模一样――")
	await novel_interface.show_text_only("无论服装、发型、身高、样貌……甚至头发上那股淡淡的奶香，都完全一致。")
	await novel_interface.show_text_only("她……是按照我的记忆构建的？")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉原本是第二学园都市情报机构『帕兰蒂尔』的攻击队队长。")
	await novel_interface.show_text_only("后来却成为了斯库尔德的女仆兼保镖。")
	await novel_interface.show_text_only("如果这是她们第一次相遇的话，到底是什么契机造成了这样的转变……")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("该死，那些东西又从天台爬进来了！！","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("罗素突然指着天花板喊道。")
	await novel_interface.show_text_only("几只小蜘蛛顺着仓库顶部的通风口爬了进来，紧跟在后面更多的蜘蛛开始侵入。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("所以说……我最讨厌这种小虫子了！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我愣愣的看着斯库尔德，并没有像其他三人那样拿起近身武器准备最后一搏。")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("（我不停在这个世界，添加自己需要的东西…) ","小怜")
	await novel_interface.show_text_only("但其实，一直以来压制着那个『意识体』的则是法贝拉本人。")
	await novel_interface.show_text_only("我真正应该改变的，在第一只机械蜘蛛袭击之前就出现过了……不是吗？")
	await novel_interface.show_text_only("那个一直在吸引我的，让我不禁想要伸手触碰的—")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Factory.png")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("斯库尔德，这个借我一下……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我将斯库尔德一直拿在手中的黑色鳄鱼皮文件夹接过，抽出那张发黄的古文本。")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("从我的手接触到文稿那一刻，上面的文字和图案就开始扭曲变化，直到变成完全无法理解的状态。")
	await novel_interface.show_text_only("仔细观察，文稿上每个古代字母我都可以看清，然而一旦想连起来读，就马上变成糅杂的乱码。")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("（果然……和第一次遇到伊露卡那时一样。）","小怜")
	await novel_interface.show_dialog("（这个古代文本，是某本『魔导书』的残页……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("天花板的小蜘蛛纷纷坠下来并向我们逼近，攻击队员们开始用铁棒和撬棍做着顽强的抵抗。")
	await novel_interface.show_text_only("我趁着攻击的空档，把法贝拉拽到自己身边。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("你干什么――！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我没有回答，而是一把拉过她的手，和斯库尔德的手搭在一起。")
	novel_interface.show_character("ren_mercenary","solemn")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_dialog("虽然我也无法解释，但你应该很快就能明白……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("因为这是属于你的——你的『魔导书』")
	await novel_interface.show_text_only("是你在两年前第一次遇到斯库尔德时，自己选择背负的东西。！")
	
	# 重要的结局部分
	novel_interface.change_background("res://assets/images/bg/Fabiola/FactoryLF.png")
	await novel_interface.show_text_only("我将古文本放在法贝拉手上，那张发黄的纸页立刻化作一道炫目的强光。")
	await novel_interface.show_text_only("一个周身被火焰包围的巨大光球赫然出现在仓库中央，像个跳动着的精灵般缓缓下落。")
	await novel_interface.show_text_only("光球随着下落越来越小，逐渐融入进法贝拉身体里\n……")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Factory.png")
	await novel_interface.show_text_only("法贝拉的手臂包裹着一层跃动的火焰，但我拉着她的手却丝毫不觉得烫。")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("火焰的……魔法……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然一只小蜘蛛跳起，径直扑向斯库尔德。")
	await novel_interface.show_text_only("法贝拉下意识的反击一拳打在它身上，黑色的机械蜘蛛顿时被一团火焰所吞噬。")
	await novel_interface.show_text_only("那台机体先是碎裂成无数细小的零件，然后在坠落到地面之前，所有的零件就都烧成了灰。")
	novel_interface.show_character("fabiola_battle","panic")
	await novel_interface.show_dialog("这是——？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉困惑的看着自己手上的火光，它们正向四周的空间蔓延，形成一个没有实体的屏障。")
	await novel_interface.show_text_only("任何蜘蛛只要稍稍靠近屏障的边缘，就会自己燃烧起来。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/FactoryL.png")
	await novel_interface.show_text_only("火焰屏障的范围越来越大，就像在三维空间中燃烧一张二维平面上的画一般——")
	await novel_interface.show_text_only("仓库内的空间似乎被更高维度的烈焰所点燃，四周都闪烁着异样的白光。")
	await novel_interface.show_text_only("在难以名状的高维火焰中，仓库内的小蜘蛛开始迅速蒸发。")
	await novel_interface.show_text_only("同时消融的，还有仓库四周的墙壁……")
	await novel_interface.stop_music()
	novel_interface.show_background("res://assets/images/bg/Fabiola/white_bg.png")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("头痛。")
	await novel_interface.show_text_only("剧烈的头痛。")
	await novel_interface.show_text_only("又是那种把一袋水泥倒进我的脑袋里，然后慢慢搅拌……")
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Dementium.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("睁开眼后，能看到头顶巨大的半弧形设备，那是播磨脑研的大脑潜入装置。")
	novel_interface.show_character("ren_maid","upset")
	await novel_interface.show_dialog("已经……过去多久了……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我揉着眼睛起身，打了个哈欠后向四处查看，病房的窗外依然是夜晩。")
	await novel_interface.show_text_only("远处大楼顶部播放着《哔咔之星》45周年新版游戏的广告，粉红色的主角翱翔在蓝天中……")
	await novel_interface.show_text_only("我扭头看向另一张病床，金发小姑娘正趴在那边睡觉，口水顺着嘴角浸湿了一小片。")
	await novel_interface.show_text_only("虽然看不到被设备挡住的法贝拉的表情，但此时她的手正温柔地轻抚着斯库尔德柔顺的头发。")
	await novel_interface.show_text_only("我试着活动了一下胳膊，似乎做了个非常复杂的梦\n，脑子完全没有得到休息。")
	await novel_interface.show_text_only("法贝拉稍稍起身对我做了个“嘘”的手势，然后露出一个坏笑，小声朝我说——")
	novel_interface.show_character("fabiola_maid","mock")
	await novel_interface.show_dialog("你穿白色的丝袜也不错呢~","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","awkward")
	await novel_interface.show_dialog("……什、什么意思？？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("根据屏幕上的时间，我只睡了不到两个小时。")
	await novel_interface.show_text_only("爱衣提醒过，我醒来之后就会像做梦一样，将刚才的绝大部分经历都忘掉。")
	await novel_interface.show_text_only("这是莉琉对我的“特别关照”。")
	novel_interface.show_character("ren_maid","stare")
	await novel_interface.show_dialog("（不就是个梦嘛，有什么了不起的……）","小怜")
	await novel_interface.hide_character()

	# 与此同时的场景
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("与此同时")
	novel_interface.show_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("SID指挥室，加密频道通话。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("那几个电子加密货币账户的实际控制人，你这么快就核实了？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("当然，确认无误。","女性的声音")
	await novel_interface.show_dialog("『帕兰蒂尔』的情报主任罗素一直欠我个人情呢。","女性的声音")
	await novel_interface.show_dialog("不过话说回来，你是怎么搞到这种东西的？","女性的声音")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("哼哼，商业秘密~","莉琉")
	await novel_interface.show_dialog("对了，下个月你会和『董事会』的代表一起来参加国际和平论坛吧？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("当然，想和老同学喝一杯叙叙旧？","女性的声音")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("你不怕我又把你灌醉然后……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("无聊！不想跟你说了。","女性的声音")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("哈哈哈哈，下次见咯——秋子。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这边刚结束通信，莉琉就收到另一条视频邀请。")
	await novel_interface.show_text_only("屏幕上出现一个身着白色衬衫的女性。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("状况如何？","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("纽摩利达斯大使馆的哈格蒂大使完全接受我们的剧本，并十分乐意配合。","贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("你那边进展的很顺利嘛。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile2")
	await novel_interface.show_dialog("呵呵，这些小伙子们都很可爱呢。","贝阿特丽切")
	await novel_interface.show_dialog("尤其是那个叫卡塞尔的队长……\n我还没解除手环，他就殷勤的不得了~","贝阿特丽切")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("因为你的“说服力”太强了……","莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("总之辛苦你了~","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("beatrice_regular","smile1")
	await novel_interface.show_dialog("哪里，是我主动要求介入此次事件的。","贝阿特丽切")
	await novel_interface.show_dialog("我们只是，各取所需。","贝阿特丽切")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("大屏幕上突然弹出一个病房监视器的视频窗口。")
	await novel_interface.show_text_only("屏幕中斯库尔德抱着病床上的法贝拉哭个不停，而爱衣正把小怜按在床上做着强制检查。")
	await novel_interface.show_text_only("视频下面有一行留言：“任务完成，两人的身体和精神状态正常~”")
	await novel_interface.show_text_only("莉琉的脸上露出满意的微笑。")
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	
	# 几天后的场景
	await novel_interface.show_text_only("几天后。")
	novel_interface.show_background("res://assets/images/bg/APT/livingRoom_daytime.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_character("fabiola_maid","normal")
	await novel_interface.show_dialog("所以，一会要去你们的学校参观吗？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("嗯嗯，等我刷个牙……","小怜")
	novel_interface.show_character("iluka_uniform","normal")
	await novel_interface.show_dialog("小怜姐姐好慢。","伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","perspire")
	await novel_interface.show_dialog("没、没关系，预约的时间还要90分钟呢~\n而且吃了东西以后，确实应该好好…刷、刷牙……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德有些颤抖的帮我打着圆场。")
	novel_interface.show_character("fabiola_maid","thinking")
	await novel_interface.show_dialog("小怜是对我的料理有什么不满吗？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉用毫无掩饰的威胁语气说道。")
	await novel_interface.show_dialog("——绝！对！没！有！","小怜")
	await novel_interface.show_text_only("法贝拉今天带来了她的“特制料理”作为答谢。")
	await novel_interface.show_text_only("大章鱼触手、番茄、深海鱼类、大葱之类完全不知该如何互相搭配的食材……")
	await novel_interface.show_text_only("全部混合在难以名状的粘稠紫色汁液中……还在不断浮上气泡。")
	await novel_interface.show_text_only("我只尝了一口，就好像看到一条大河，河对岸有个老奶奶在招我去……")
	await novel_interface.show_text_only("冲进洗手间已经二十分钟了，不知是不是心理作用\n，到现在那股味道还萦绕不去。") #换行问题
	await novel_interface.show_text_only("该不会……那个味道已经刻在灵魂里了？！")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("小怜呀~","安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("唔？","小怜")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("以后拍这种照片的时候，要把镜头拉远一点，更贴近胸口一些。","安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("什么照片……","小怜")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("啊啊安妮你又看我手机——！！","小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Stockings.png")
	await novel_interface.show_text_only("我冲到客厅，发现安妮正卧在沙发上玩我的手机。")
	await novel_interface.show_text_only("屏幕上正是前几天我穿女仆装练习的时候，偷偷拍的那张。")
	await novel_interface.show_text_only("更糟的是，斯库尔德、法贝拉和伊露卡都凑过去围观着……")
	await novel_interface.show_text_only("这是今天的公开处刑吗！！！")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom_daytime.png")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("谁让你的密码那么好猜~","安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮一幅得意的表情说道。")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("下次按我说的方法，会显得腿更修长哦。","安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","laugh")
	await novel_interface.show_dialog("对呀，其实裙子应该再拉高一点，反正这个视角别人也看不出来——","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","stare")
	await novel_interface.show_dialog("打开美颜的话效果会更好呢~","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","speechless")
	await novel_interface.show_dialog("喔~~~哦哦！","伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡听她们说话好像都很厉害的样子，不停的点着头。")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("我就是……偶尔…碰巧…拍一下……","小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("完全不想知道这些知识啊啊！！","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","relieve")
	await novel_interface.show_dialog("对了，你家里人同意你留在新丰洲了吗？","安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("嗯……莉琉好像很轻松的就说服了父亲呢。","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","bored")
	await novel_interface.show_dialog("（不不，被她说服，你老爸绝不会觉得轻松……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("——而且，多亏了小怜姐姐。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德对我露出一个太阳般温暖的微笑。")
	novel_interface.show_character("fabiola_maid","normal")
	await novel_interface.show_dialog("你真的……什么都不记得了？","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("嗯……完全是一片模糊，你还都记得吗？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","smile")
	await novel_interface.show_dialog("我也只是好像做了个印象清晰的梦，梦里还见到一些故人……","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉脸上略过一丝悲伤的表情。")
	novel_interface.show_character("fabiola_maid","laugh")
	await novel_interface.show_dialog("不说啦不说啦~~","法贝拉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("从这里走到你们的学校只要15分钟吧？\n那还有些时间呢……","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉走向阳台，望向窗外城市的风景。")
	novel_interface.show_character("fabiola_maid","normal")
	await novel_interface.show_dialog("这里的风景真不错呢……","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","smile")
	await novel_interface.show_dialog("小怜姐姐，我想打游戏。\n《哔咔之星》！","伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("咱们一会就出门了……\n好啦好啦，就陪你玩一会~","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	await novel_interface.show_dialog("啊啊啊啊啊啊！！！","法贝拉")
	await novel_interface.show_text_only("阳台突然传来法贝拉的大叫声。")
	novel_interface.show_character("ren_uniform","shout")
	await novel_interface.show_dialog("怎么了？？！","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_maid","blush")
	await novel_interface.show_dialog("有蜘蛛——！！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉指着阳台角落的蜘蛛网，立刻从腿上拔出手枪打算射击。")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("法贝拉！不可以在别人家用武器哦！","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("哇！那是P226吗？\n好帅气——！","安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","speechless")
	await novel_interface.show_dialog("喔~~帅气！","伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("拜托，饶了我吧……","小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("看着小怜和嬉闹的众人，斯库尔德闭上了眼睛。")
	await novel_interface.show_dialog("小怜姐姐……","斯库尔德")
	novel_interface.show_background("res://assets/images/bg/Fabiola/YumeRen.png")
	await novel_interface.show_text_only("我记得在一阵白光之后，看到了你的脸——")
	await novel_interface.show_text_only("虽然只是一瞬，但我绝对不会记错。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/YumeRen2.png")
	await novel_interface.show_text_only("只是和我印象中的样子——")
	await novel_interface.show_text_only("稍稍有点不同呢……")
	
	print("=== 创伤反射篇第15话结束 ===")
	print("=== 创伤反射篇全部完成 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
