# traumareflex_ep06.gd - 创伤反射篇第06话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep06_script()

func play_script():
	pass

func traumareflex_ep06_script():
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("——轰！！！！！！")
	await novel_interface.show_text_only("随着一声巨响，车头猛然抬起，我被重重的甩到了地板上。")
	await novel_interface.show_text_only("异质物特种加固的车体装甲几乎没有什么形变，所有冲击都原封不动的传到了车厢内部。")
	await novel_interface.show_text_only("随着车辆翻滚倒地，我感到小腹一阵痉挛，好像能把半个胃给吐出来。")
	await novel_interface.show_text_only("是啊，如果无法攻破装甲，只要炸飞地面一样可以将这种运兵车瘫痪掉。")
	await novel_interface.show_text_only("真是昂贵而愚蠢的设计——")
	novel_interface.show_background("res://assets/images/bg/Fabiola/APC_Blur2.png")
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("头痛……")
	await novel_interface.show_text_only("耳畔嗡嗡作响，视线完全无法对焦。")
	await novel_interface.show_text_only("好在穿着那种有非牛顿流体填充物的战术夹克，我才没在刚才那下冲击中散了架。")
	await novel_interface.show_text_only("虽然不知是谁给我选的装备，真是谢天谢地……")
	novel_interface.show_character("ren_mercenary","awkward")
	await novel_interface.show_dialog("（但我为什么下面穿的是丝袜啊……）\n（已经破洞洞了啊！！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("砰！砰！砰！砰！砰！砰！砰！砰！")
	await novel_interface.show_text_only("法贝拉一拳敲碎了车内紧急脱出钮的保护罩，车顶的两条爆炸索依次炸开。")
	await novel_interface.show_text_only("翻倒在一侧的车顶瞬间被炸开个大洞，刺鼻的浓烟伴随着火光立刻涌入了车厢内。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("该死……！都给我下车！！！","法贝拉")
	novel_interface.change_expression("thinking")
	await novel_interface.show_dialog("咳咳——喂！！新人还活着吗？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("还在恍惚中游离的我，被法贝拉一把揪起来丢出了车外……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("浓烟刺激着我的眼睛，眼泪止不住的涌出，完全遮蔽了视线。")
	await novel_interface.show_text_only("由于不小心吸了两大口，我感觉气管好像要从里面烧起来似的……")
	await novel_interface.show_text_only("连续神经反射式的干咳让人完全喘不上来气。")
	await novel_interface.show_text_only("我被呛得弓起身子，忽然看到了垂在脖子上的那个面罩，立刻用手将它紧紧按到了鼻子上。")
	await novel_interface.show_text_only("呼——")
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	await novel_interface.show_text_only("播磨脑研，实验医疗部。")
	await novel_interface.show_text_only("莉琉和爱衣给我介绍完法贝拉的基本情况，就说要先去楼下调试设备，让我在这里待命。")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("她们两……就这么走掉了？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("半夜里空无一人的医院走廊有种莫名的压迫感。")
	await novel_interface.show_text_only("我穿着与环境完全不搭调的女仆装坐在靠墙的座椅上。")
	novel_interface.show_character("ren_maid","sob")
	await novel_interface.show_dialog("怎么有点像某个R级的僵尸游戏……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("怎么会有僵尸呢，一般都是闹鬼吧~","？？？")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("哈哈哈哈~~是啊僵尸什么的也太——","小怜")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("——诶啊啊？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("空荡荡的楼道突然冒出一个接话的声音，我吓得腾的一下从椅子上跳了起来。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("啊啊~~非常抱歉，吓到你了吗？","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一个身姿娇小的少女从拐角处探出头来。")
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("我们……又见面了呢，小怜姐姐~","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女一头金发编成的辫子乖巧的垂落到腰间，那种散发着灵气的超然气质只要见到一次就无法忘掉。")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("你是……斯库尔德？","小怜")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("（她刚才……叫我姐姐吗？）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德有些羞涩的笑了一下向我走来，神情中似乎透露着焦虑与不安。")
	await novel_interface.show_text_only("与上次在天空酒店的酒会上见到她时那种优雅大方的感觉不一样——")
	await novel_interface.show_text_only("啊对了！法贝拉……就是她的女仆。")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("虽然这是莉琉的要求……\n但我本来就想亲自拜托你……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她有些犹豫，娇小的身躯微微颤抖着，说话时好像在强忍着不哭出来。")
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("拜托你……救救法贝拉……","斯库尔德")
	await novel_interface.show_dialog("要不是我缠着她想偷跑出来……","斯库尔德")
	await novel_interface.show_dialog("我也没想到会变成这样……","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("你、你别着急……","小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("（诶诶诶她好像快哭了~~）\n（怎、怎么办！！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我情不自禁的想要伸手安慰一下她，但又觉得穿着吊带袜女仆装在半夜的医院走廊抱小萝莉的话……")
	await novel_interface.show_text_only("我的胳膊还僵在半空，她突然一把抱住了我。")
	await novel_interface.show_text_only("一头柔软的金发散在我的胳膊上，有一股淡淡的奶香，我的心跳止不住的加快，大脑嗡的一下——")
	novel_interface.show_character("ren_maid","blush")
	await novel_interface.show_dialog("（啊啊啊啊好小只啊——！！）\n（好、好可爱……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她比看起来还要瘦小，将脸埋在我的胸前，身体像小动物一样微微发抖。")
	await novel_interface.show_text_only("刚才爱衣解释了一大通的大脑潜入之类的东西是什么来着？不管了——")
	novel_interface.show_character("ren_maid","smile")
	await novel_interface.show_dialog("我、我一定会帮你的！！\n放心吧！！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("啊啊啊啊，大脑要无法思考了！！就算她拜托我去炸元老院我都会一口应下来吧……")
	novel_interface.show_character("ren_maid","blush")
	await novel_interface.show_dialog("没、没事的、有我在……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我安慰人的功夫真是蹩脚到家了……其实我也不知道我有什么用，但好像气氛上都会这么说吧？")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("嗯。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("怀中的斯库尔德轻轻的点了点头。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("如果是你的话，一定可以。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("诶？我真的可以吗？")
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("因为你是我记忆中……最特别的那个人。","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","awkward")
	await novel_interface.show_dialog("嗯嗯……昂？","小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（我的女仆装给你留下了这么深刻的印象吗？）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德稍稍平复了一下情绪，擦干眼泪之后用十分确信的眼神看着我。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("所以，我的秘密全都可以告诉你。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("出人意料的展开，让我一时不知怎么应对。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("虽然你可能觉得难以置信，但请务必听我说。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("面前这个瘦小的女生忽然严肃起来的口气，让我不得不认真起来。")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("我有一种……很特殊的能力。","斯库尔德")
	await novel_interface.show_dialog("我能记得一些并未发生过的事，或者说未来才会发生的事，但对我而言却像是回忆一样……","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","upset")
	await novel_interface.show_dialog("回忆……未来？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("那些片段一开始就在我的记忆中，所以我也无法分辨哪些是过去的回忆，哪些是还未发生的未来。","斯库尔德")
	await novel_interface.show_dialog("直到终于亲眼看到熟悉的那一幕发生了，我才能确认。","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","gratified")
	await novel_interface.show_dialog("感觉像预言之类的能力？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这几个月来发生的事，让我已经习惯了对看起来不可思议的事抱着“姑且先接受”的态度。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("就好像给你形容某种糖，不是太甜、有恰到好处的酸味、并且在口中化开的时候感觉凉凉的。","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("似乎我吃过那种，但记不清了……","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("就是那种感觉！","斯库尔德")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("你能生动的形容出那种糖的口感和味道，但就是说不上来在哪吃到的。","斯库尔德")
	await novel_interface.show_dialog("只有某天你真的吃到了，才会恍然大悟就是它！","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我好像有点懂了，如果记忆中存在不知是不是未来才会发生的片段，是根本无法表达的。")
	await novel_interface.show_text_only("与预知未来并不一样，因为无法分辨什么是未来。")
	novel_interface.show_character("ren_maid","worry")
	await novel_interface.show_dialog("（等等……但时间总会留下一些痕迹吧？）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德像是读懂了我的想法，继续说道——")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("可能你会觉得，下个月的情景或许无法分辨，但十年后的环境总会有明显的差别吧？","斯库尔德")
	await novel_interface.show_dialog("但记忆并不是像录像一样的东西……其实我们只会记住一些关键的碎片——","斯库尔德")
	await novel_interface.show_dialog("当刻意去回想的时候，才会在大脑中重新组建起那时的情景。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我忽然想起来，似乎曾经在某部电影里看到过——")
	await novel_interface.show_text_only("“记忆只是一种演绎，而非记录。”")
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("所以，回忆中能标识时间特征的碎片其实很少。\n而且更麻烦的是——","斯库尔德")
	novel_interface.change_expression("thought")
	await novel_interface.show_dialog("你是不会没来由的去回忆某些事情的。","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","worry")
	await novel_interface.show_dialog("嗯？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("比如你不会突然去回想小学某节数学课上老师讲了满黑板的一道题具体是什么样的……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("抱歉，这种记忆通常在老师刚开始讲时就断掉了。")
	novel_interface.show_character("ren_maid","gratified")
	await novel_interface.show_dialog("还是觉得……很不可思议。","小怜")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("等等，你刚才说记忆的我，难道是——","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德点了点头。")
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("但在我的记忆中，只有一件我能确信是最后才发生的事情……","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Shot/Soul_Sacrifice.png")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("我屏住了呼吸，忽然猜到她想到的是哪件事——")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("——那是世界终结之时的记忆。","斯库尔德")
	await novel_interface.show_dialog("只不过那段记忆中，你是男孩子。","斯库尔德")
	
	print("=== 创伤反射篇第06话结束 ===")
	await novel_interface.end_story_episode(0.5)
