# traumareflex_ep14.gd - 创伤反射篇第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第14话剧本
	traumareflex_ep14_script()

func play_script():
	pass

# 创伤反射篇第14话 - 正式剧本
func traumareflex_ep14_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Brain.png")
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	await novel_interface.show_text_only("很多人认为，记忆就像视频文件。")
	await novel_interface.show_text_only("回忆时只需找到相应的时间点，按下播放键就能观看。")
	await novel_interface.show_text_only("但人脑在编码记忆时，并非是如摄影机那样工作的——而它只会记录下一些碎片。")
	await novel_interface.show_text_only("在回忆时，大脑会给这些记忆碎片提供一个想象空间，然后用推理的方法还原“当时”的场景。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Memory.png")
	await novel_interface.show_text_only("所以，就像某部电影中所说的――")
	await novel_interface.show_text_only("『记忆只是一种演绎，而非记录。』")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("在斯库尔德好奇的目光下，我盯着手中的糖盒头皮一阵发麻。")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Billboard.png")
	await novel_interface.show_text_only("这个糖盒上的图案，还有外面的广告牌——")
	await novel_interface.show_text_only("绝不可能出现在法贝拉两年前的记忆中。")
	await novel_interface.show_text_only("爱衣和莉琉也不会用这么特殊的标识。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Factory.png")
	await novel_interface.show_text_only("如果它们是被什么人有意放在这个世界中，就只有一种可能――")
	novel_interface.show_character("ren_mercenary","normal1")
	await novel_interface.show_dialog("（那个人，就是我自己。）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我在法贝拉的记忆中，放入了本不该存在的东西。")
	await novel_interface.show_text_only("不过，到底是什么时候……")
	await novel_interface.show_text_only("我做这些，又是为什么？")
	await novel_interface.show_text_only("……头痛。")
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("（完全想不起来~~）","小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("（那么除了这个图案，还有什么是本不该存在于这段回忆中的吗……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("对了，气凝胶！")
	await novel_interface.show_text_only("――我带的那罐还是爱衣两周前为南极任务改良的最新型号。")
	await novel_interface.show_text_only("要是没有它，很大几率会被那个大蜘蛛团灭吧……")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("（应该还有，再想想……）","小怜")
	await novel_interface.show_text_only("潜入之后，那些特殊而至关重要的道具――")
	await novel_interface.show_text_only("非牛顿流体填充的战术夹克。")
	await novel_interface.show_dialog("（好像《SID探员作战装备指导》上有介绍过！）","小怜")
	await novel_interface.show_text_only("如果不是这件有点宽大的外套，最初翻车的那一系列冲击可能已经让我散架了……")
	await novel_interface.show_text_only("蝰蛇式战术面罩。")
	await novel_interface.show_text_only("那时被呛得快室息，全靠它才能走出浓烟。")
	await novel_interface.show_text_only("短剑冲锋枪，体贴的超低后坐力，是SID射击训练场里我最喜欢的武器。")
	await novel_interface.show_text_only("我靠它打中了气凝胶喷罐，而三个备用弹匣正好够抵御那群小蜘蛛。")
	await novel_interface.show_text_only("甚至还有――")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("（丝袜……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这个牌子的颜色和弹性都刚刚好，没穿的话我们可能在狙击手那里就被干掉了。")
	novel_interface.show_character("ren_mercenary","uneasy")
	await novel_interface.show_dialog("（嗯嗯……战术丝袜！）","小怜")
	await novel_interface.show_dialog("（这些装备似乎无论少了哪样，我都死定了…）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("诶？等一下……")
	await novel_interface.show_text_only("『死』定了……吗？")
	novel_interface.show_background("res://assets/images/bg/Fabiola/AI.png")
	await novel_interface.show_dialog("我亲自升级了保险装置，绝不会出现那种脑内受伤或死亡会牵连本体的状況。","爱衣")
	await novel_interface.show_text_only("……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("对啊……")
	await novel_interface.show_text_only("这段回忆中最不该存在的，不就是我自己吗？")
	await novel_interface.show_text_only("就算我在这个世界中死掉，也不会牵连本体……")
	await novel_interface.show_text_only("一道光忽然划过我的脑海――")
	await novel_interface.show_dialog("（在此之前，我已经死过多少次了？）","小怜")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Factory.png")
	await novel_interface.show_text_only("我感觉脊背发冷，手无法抑制的开始颤抖。")
	await novel_interface.show_text_only("这样一切都说得通了……")
	await novel_interface.show_text_only("并不是斯库尔德说的那种预知能力——")
	await novel_interface.show_text_only("而是每次死掉，我都添加了新的应对策略。")
	await novel_interface.show_text_only("那些面对危险的预感，那个广告牌，那诡异的探照灯位置，都是我在提醒自己……")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("（这不是什么预言，而是我的亲身经历啊。）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("小怜姐姐，没事吧？\n你的脸色好差……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德关切的拍了拍我的后背。")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("没，只是想起一些事……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("对呀，无论她们当年遇到了什么危险，法贝拉和斯库尔德应该都平安度过了。")
	novel_interface.show_character("ren_mercenary","upset")
	await novel_interface.show_dialog("（那为什么我会重复了这么多遍？）\n（是因为法贝拉说的间谍吗……）","小怜")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("突然，耳机中传来一阵刺耳的爆音，随后是几声枪响。")
	await novel_interface.show_dialog("啊啊啊啊啊啊啊――――！！！！","女声")
	await novel_interface.show_text_only("砰！砰！砰！砰！砰！")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("怎么回事！！","罗素")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("是莉娜吗！？","卡塞尔")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("莉娜，报告你的位置！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("咳咳……咳咳咳咳——","女声")
	await novel_interface.show_text_only("一阵撕心裂肺的呛咳过后，是带着杂音的大口呼吸音。")
	await novel_interface.show_text_only("那种典型的外伤导致肺部积液的气鸣声。")
	await novel_interface.show_text_only("伤者每次呼吸都会比上次更加困难，直到从身体内部被积液溺死……")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("你受伤了！？\n你在什么位置？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("已经，无所谓了……\n咳咳咳――","莉娜")
	await novel_interface.show_dialog("你们在的仓库，也被那群东西包围了……","莉娜")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("――！！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("从刚才起，四周的墙壁和铁门就传来微小而密集的金属撞击声。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("该死……在寻找入口吗。","法贝拉")
	await novel_interface.show_dialog("有办法封锁电梯井吗？","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("这是工业电梯，开放程度太高了。","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("它们主要是靠热成像探测目标……","莉娜")
	await novel_interface.show_dialog("我的同伴也都联系不上了，这该死的东西到底是\n从哪冒出来的……咳咳——","莉娜")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("……同伴？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哼…小丫头……你还没想明白吗……","莉娜")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("难道……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("纽摩利达斯…真是个开放的城市啊……","莉娜")
	await novel_interface.show_dialog("无论什么人，都能获得第二次机会――","莉娜")
	await novel_interface.show_dialog("包括施瓦茨那种刽子手…咳—！！","莉娜")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("施瓦茨……刚才阿尔法队阵亡的那个施瓦茨？","卡塞尔")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("他以前…是马萨达清扫队的成员…我亲眼看着他…杀了我手无寸铁的母亲和姐姐……","莉娜")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("清扫队，莉娜的彩色头巾……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我忽然想到前几年看过的新闻，联合议会向马萨达堡质询其周边发生的人道主义灾难。")
	await novel_interface.show_text_only("虽然那时我根本不懂“人道主义灾难”是什么，但电视画面中反复出现的彩色头巾让我印象深刻。")
	await novel_interface.show_dialog("很可笑吧……我的族人本以为马萨达堡是与自己有着共同敌人的“盟友”……","莉娜")
	await novel_interface.show_dialog("但在消灭了那些敌人后，咳――！……他们立刻将枪口调转对准我们――","莉娜")
	await novel_interface.show_dialog("划定所谓的“保护区”…所有限期内不迁往区内居住的人……直接被视为恐怖分子……","莉娜")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("你和你的同伴，都是抵抗组织的人？","法贝拉")
	await novel_interface.show_dialog("如果想干掉施瓦茨派个暗杀小队就可以了，为什么要在纽摩利达斯搞这么大动静？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("咳—……你还是什么都不懂……","莉娜")
	await novel_interface.show_dialog("马萨达堡一直参与周边战争…还大力投入研发新型武器…那么你觉得资金是由谁……","莉娜")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("……主要贷款方是纽摩利达斯。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("董事会一边控制信贷，一边承销证券…流入马萨达的贷款在这个城市…被打包发行成债券……","莉娜")
	await novel_interface.show_dialog("“绅士”老爷们在收佣金的时候咳――！…可不会考虑那些钱买来的炮弹…会落在谁的头上。","莉娜")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("所以你们趁着国际和平论坛期间……","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("只要是胜利的那方…就必然是正义的…因为只有活下来的……政府才能偿还债务……对吧……","莉娜")
	await novel_interface.show_text_only("斯库尔德低头不语。")
	await novel_interface.show_dialog("咳——！！咳咳咳――！！","莉娜")
	await novel_interface.show_text_only("耳机中再次传出莉娜剧烈的呛咳声。")
	await novel_interface.show_text_only("莉琉曾对我说，钱和钱的交流是世界上最纯粹的。")
	await novel_interface.show_text_only("没有语言、文化、制度、历史种种障碍，是世界上最亲密无间直截了当的尔虞我诈。")
	await novel_interface.show_dialog("呼——选择那位大小姐……是因为她的父亲…是董事会中唯一不赞成和马萨达堡交易的人。","莉娜")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("那为什么――","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("所以…我们要给他一个在董事会发言时……能支持他立场的充分理由……","莉娜")
	await novel_interface.show_text_only("莉娜娜的声音和呼吸渐渐变得虚弱。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("所以故意让『黄雀』在市区坠毁，并且让他的女儿亲历险境……","罗素")
	await novel_interface.show_dialog("怪不得你一个人干掉了那边全部的狙击手，是你的同伴在配合演戏――","罗素")
	await novel_interface.show_dialog("等等，你向黄雀开枪，也是为了掩饰那台机体并没有装载攻击模块吧？！","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("呵呵…罗素吗…你很有天分……","莉娜")
	await novel_interface.show_dialog("可惜………","莉娜")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("喂喂——莉娜？莉娜！！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("耳机那头陷入了长长的沉默。")
	novel_interface.show_character("fabiola_battle","sob")
	await novel_interface.show_dialog("可恶……可恶！可恶！可恶！！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉一拳重重的锤在金属货架上，发出的声响在仓库中回荡。")
	novel_interface.show_character("fabiola_battle","sob")
	await novel_interface.show_dialog("为了政治权谋和利益，还要牺牲多少无辜的人……","法贝拉")
	novel_interface.change_expression("sob2")
	await novel_interface.show_dialog("培尔纳德……","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉低头小声抽泣着，鲜血顺着她的指尖不断滴下。")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("（等等，……那些蜘蛛并不是他们安排的？！）","小怜")
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("（在这段记忆里，到底哪些才是真实的……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("稍早之前。")
	novel_interface.show_background("res://assets/images/bg/Fabiola/BAR2.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_text_only("播磨脑科学综合研究中心，顶层酒吧。")
	await novel_interface.show_text_only("莉琉坐在沙发上，拿着一份印有“极秘”字样的纸质档案翻看着。")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("卡洛斯·布兰科，从新丰洲纪念教堂回收的那个女仆的前任长官……","莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("原AUC上校，那个烂到骨髓的系统里难得能出这么一位治军严厉的军官嘛。","莉琉") #换行问题
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("埃卢尔解散议会后，他在手臂纹上了“打倒暴君”字样的刺青，率旧部起义。","莉琉")
	await novel_interface.show_dialog("曾带领部队在一天内翻越了安第斯山脉，指挥反埃卢尔联军参加波多西战役。","莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("有意思……所以才得到了这个与卡尔十四世·约翰同名的外号吧？","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉被档案的内容吸引，用手指捏着酒杯的上沿在手里打转。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("之后在恩维拉作战时捡到了奄奄一息的法贝拉。","莉琉")
	await novel_interface.show_dialog("革命成功后几支起义军统领都想掌权，于是再度刀兵四起……","莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("真是老套的故事。","莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("后来他作为南美最大的军阀，被怀疑是丘伦河大屠杀的主谋，被媒体称为“丘伦河屠夫”。","莉琉")
	await novel_interface.show_dialog("真实原因是只有他拒绝了联合议会的提议。","莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("控制媒体确实可以为所欲为呢~","莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("然后联合议会宣布卡洛斯·布兰科犯有反人类及种族灭绝罪，并送去了几发钻地弹。","莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("真是空有一腔热血，却不懂政治权谋的笨蛋――","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉将档案随手丢在茶几上。")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("正应了卡尔十四世形容拿破仑的那句名言……","莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Bernadotte.png")
	await novel_interface.show_dialog("“因他只依赖自己的才智，所以上帝才惩罚他。”","莉琉")
	await novel_interface.show_dialog("――卡尔十四世·约翰，让-巴蒂斯特·培尔纳德","莉琉")
	await novel_interface.show_dialog("果然从那个家伙之后，南美的革命军都喜欢戴贝雷帽吗……","莉琉")
	novel_interface.change_background("res://assets/images/bg/Fabiola/BAR2.png")
	await novel_interface.show_text_only("一位侍应走到莉琉身边。")
	await novel_interface.show_dialog("斯库尔德的车已经到楼下了。","侍应")
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("知道了，把这份文件收好，带那个小丫头上来吧。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("好的。","侍应")
	novel_interface.change_background("res://assets/images/bg/Fabiola/BAR.png")
	await novel_interface.show_text_only("莉琉拍了拍手，原本只有一个SID标志的黑色屏幕立刻变为了高层夜景的实时画面。")
	await novel_interface.show_text_only("她看着窗外大厦顶部那巨大的红蓝两色广告，将杯中酒一饮而尽。")

	print("=== 创伤反射篇第14话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
