# traumareflex_ep03.gd - 创伤反射篇第03话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep03_script()

func play_script():
	pass

func traumareflex_ep03_script():
	await novel_interface.show_text_only("呐……你有没有过那种感觉？")
	await novel_interface.show_text_only("蓦然回想起某个画面，却忘记了是何时的记忆。")
	await novel_interface.show_text_only("并不是那种很多人都经历过的，被称为“幻觉记忆\n”的体验。")
	await novel_interface.show_text_only("而是你早就知道会发生的一幕，终于被验证了。")
	await novel_interface.show_text_only("你已经预知到，甚至看到了闪回般的画面，只是当时无法确认。")
	await novel_interface.show_text_only("而所谓『既视感』，仅仅是对这种预知的验证。")
	await novel_interface.show_text_only("你早知事情会变成这样的——")
	await novel_interface.show_text_only("不是吗？")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Night_Park.png")
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("唔……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发少女迷迷糊糊的醒来，揉了揉眼睛，发现自己正躺在一张长凳上。")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("法贝拉……这是在哪儿？","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("形影不离的女仆并未如往常那样，第一时间出现在自己面前。")
	await novel_interface.show_text_only("空无一人的道路两旁的路灯整齐的延伸到远处，让少女产生了一种恍若隔世的诡异宁静感。")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("我记得……刚刚在教堂……","斯库尔德")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("啊——法贝拉！！！","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("强忍着剧烈的头痛，斯库尔德猛然从长椅上站起。")
	await novel_interface.show_text_only("刚才好像做了噩梦，彩绘玻璃上扭曲恐怖的画面还在深深刻在脑海之中。")
	await novel_interface.show_text_only("最后似乎是法贝拉将自己从黑暗中推了出去……")
	await novel_interface.show_text_only("斯库尔德检查了身上，手机、财物和饰品都完好。")
	await novel_interface.show_text_only("少女拿出手机，32个未接来电。")
	await novel_interface.show_text_only("如果不是法贝拉帮自己装了反追踪软件，大使馆的人早就找来了吧……")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("22:18…已经这么晚了吗？","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女坐在长椅上，闭上眼调整着呼吸，想要将纷乱的记忆与信息整理清晰。")
	await novel_interface.show_text_only("父亲和法贝拉之前都教过自己应对方法——越是面临复杂危险的环境，越要保持头脑清醒。")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("那座教堂……还有安东神父的简讯，应该是特意针对我的陷阱。","斯库尔德")
	await novel_interface.show_dialog("那么对方真正的目标应该是我、父亲、或者法贝拉三者之一。","斯库尔德")
	await novel_interface.show_dialog("能隐约听到附近道路的车声，远处还有街头乐队演奏的声音，行动自由应该没有被限制。","斯库尔德")
	await novel_interface.show_dialog("看手机定位，这里是新井中心公园，离那座教堂不到两公里……","斯库尔德")
	await novel_interface.show_dialog("——将我带到这里的人，应该没有敌意。","斯库尔德")
	await novel_interface.show_dialog("但不知设置陷阱的，和将我带来这里的是不是同一势力……不能贸然回去。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉的号码始终没有接通，少女查了所有的记录\n，这段时间也没有任何她联系自己的痕迹。") #换行问题
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("法贝拉……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女握紧手机，拨通父亲的号码。")
	await novel_interface.show_text_only("电话几乎是拨通的瞬间就被接起，听筒中传来一个焦急的声音")
	await novel_interface.show_dialog("喂？斯库尔德吗？","父亲")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("爸爸……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你跑哪去了！现在都不回去！那边已经晚上十点多了吧？","父亲")
	await novel_interface.show_dialog("你和那个女仆都不接电话，偷跑出去就算了还玩这么晚！现在哈格蒂大使在派人四处找你……","父亲")
	await novel_interface.show_text_only("听到父亲劈头盖脸的一顿责骂，斯库尔德稍稍松了口气——")
	await novel_interface.show_text_only("并没有人在过去的几个小时里利用自己威胁他。")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("我现在很安全，但是你听我说——","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("电话那头的男人听到女儿严肃的口气，立刻意识到了问题。")
	await novel_interface.show_dialog("……你那边有其他人吗？","父亲")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("没有，我一个人。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你等我换个电话打过去。","父亲")
	await novel_interface.show_text_only("挂断电话，很快收到一个『未知号码』的来电。")
	await novel_interface.show_dialog("好了，发生什么了？","父亲")
	await novel_interface.show_text_only("斯库尔德再次做了个深呼吸，根据现在的信息有两种可能——")
	await novel_interface.show_text_only("如果设置陷阱和将自己带到这的是同一拨人，那么对方的目标一开始就是法贝拉。")
	await novel_interface.show_text_only("如果两拨人并非同一阵营，那么对方的目标并未达成，法贝拉和安东神父则是他们手上的筹码。")
	await novel_interface.show_text_only("无论如何，那个对自己最重要的人目前肯定处于危险之中……")
	await novel_interface.show_text_only("但如果是第二种情况，自己去找法贝拉无异于自投罗网，还可能给对方机会威胁父亲和董事会。")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("我需要您先帮我做一件事，去确认一下三一教堂安东神父的安全。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("好，我这就让人去确认。\n现在可以说你遇到什么状况了吧？","父亲")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("刚才，我和法贝拉在大使馆附近被埋伏了，应该是某种迷幻类药剂或者异质物武器。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("什么——？？！","父亲")
	await novel_interface.show_text_only("在国际领土使用化学或者异质物武器，如果被发现背后的支持者，无异于向联合议会发布宣战声明。")
	novel_interface.show_character("skuld","thought")
	await novel_interface.show_dialog("法贝拉拼命救出了我，但她自己现在下落不明……","斯库尔德")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("那些人应该是伪装成安东神父…给我发信息诱导我过去的。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……我明白了。","父亲")
	await novel_interface.show_dialog("下个月就要召开和平论坛，早说过不要在这个敏感的时间来新丰洲你偏不听……","父亲")
	await novel_interface.show_dialog("那帮人敢这么做，肯定会特别小心地隐藏起自己的身份。","父亲")
	await novel_interface.show_dialog("法贝拉之前在南美的长官虽然不在了，但也还有不少仇家……","父亲")
	await novel_interface.show_dialog("你现在在什么位置？\n我先给你安排外交通道回纽摩利达斯。","父亲")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("您先跟我保证，一定要救法贝拉出来——","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德声音有些颤抖，眼泪在她的眼眶中打转。")
	await novel_interface.show_dialog("……","父亲")
	await novel_interface.show_text_only("电话的另一头只有一阵沉默。")
	await novel_interface.show_text_only("她知道，以父亲的信息渠道和能力一定已经分析出了利弊，并做出了他认为的最优判断。")
	await novel_interface.show_text_only("父亲是一家对冲基金的创始人，战争期间在金融市场杀伐决断，最终获得了进入『董事会』的资格。")
	await novel_interface.show_text_only("但他也因此树敌无数，事实证明平时做空一只股票和战争期间做空一个国家的意义全然不同。")
	await novel_interface.show_text_only("斯库尔德从小就在仇恨与危险的环境中长大，但父亲不知出于何种坚持，从不为家人改变行事风格。")
	await novel_interface.show_text_only("可能是与很小的时候就过世的母亲有关吧……")
	await novel_interface.show_text_only("突然，斯库尔德发现手机屏幕上亮起一个小红框，那是通话期间位置被追踪时的提示。")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("——！！","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她立刻挂断了电话。")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("位置暴露了吗？得先离开这……","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Parking_Lot.png")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	await novel_interface.show_text_only("斯库尔德跑到了附近一座停车楼的楼梯间。")
	await novel_interface.show_text_only("此时她的手机上显示的是通讯录上一家洗衣店的号码，那是法贝拉交给她的『最终保险』措施。")
	novel_interface.show_character("skuld","panic")
	await novel_interface.show_dialog("……只能賭一把了！","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("少女蹲在楼梯台阶上，拨通了电话——")
	await novel_interface.show_text_only("三声铃声之后，一个温柔的女性声音接起了电话。")
	await novel_interface.show_text_only("您好，瑞希尔洗衣店。")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("……我是斯库尔德·艾克斯罗德，外交识别码是\nAX1832。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("好的，请稍等……")
	await novel_interface.show_text_only("您的衣服已经洗好了，要给您送过去吗？")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("好，我还有朋友在新丰洲纪念教堂。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("嗯，我记下了。")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("我的位置在……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我们知道您的位置，请耐心等待~")
	await novel_interface.show_text_only("电话那头挂断了。")
	await novel_interface.show_text_only("10分钟后，一队黑色的SUV驶入了停车楼。")
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("您好，艾克斯罗德小姐。","SID特工")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("你们是……SID的人吗？","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("是的，您的朋友已经被我们回收了。","SID探员")
	await novel_interface.show_dialog("请上车吧。","SID探员")
	
	
	print("=== 创伤反射篇第03话结束 ===")
	await novel_interface.end_story_episode(0.5)
