# traumareflex_ep04.gd - 创伤反射篇第04话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep04_script()

func play_script():
	pass

func traumareflex_ep04_script():
	novel_interface.change_background("res://assets/images/bg/APT/washingRoom.png")
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("欢迎肥来……啊不对！","小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("欢迎回来~！主、主、主人……","小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("感觉还是怪怪的……","小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("所以说……","小怜")
	await novel_interface.show_dialog("为什么我要去女仆咖啡厅打工啊！！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这么糟糕的伪装任务，完全是莉琉根据自己的兴趣安排的吧！")
	await novel_interface.show_text_only("虽然那家位于使馆区的咖啡厅确实很有名，我之前也在网上看过关于那家店的介绍——")
	await novel_interface.show_text_only("环境优雅、食物精美、餐具考究……最重要的是女仆小姐姐们都超级可爱！！")
	await novel_interface.show_text_only("不过那时我觉得被女生称作“主人”会很害羞，所以一次也没去过。")
	await novel_interface.show_text_only("太天真了……")
	novel_interface.show_character("ren_maid","shy_left")
	await novel_interface.show_dialog("真正会害羞的，是对着别人叫“主人”的那方啊！","小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（而且这套女仆装的细节好多，麻烦死了~~）","小怜")
	await novel_interface.show_dialog("（裙子本来就有点短）\n（加上裙撑之后走起路来简直……）","小怜")
	await novel_interface.show_dialog("（不过吊带袜还是第一次穿……）\n（原来吊带是固定在腰上的呀……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我低头看了看腿上的白色蕾丝吊带袜。")
	novel_interface.show_character("ren_maid","timid")
	await novel_interface.show_dialog("（从第一人称视角看来是这样的嘛……）\n（似乎还蛮可爱的~）","小怜")
	novel_interface.change_expression("uneasy")
	await novel_interface.show_dialog("（偷偷拍张照片，绝对不会给别人看的！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("咔")
	novel_interface.show_character("ren_maid","uneasy")
	await novel_interface.show_dialog("咳咳，继续练习……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("要是培训阶段就被筛下来，绝对会被莉琉踩死。")
	novel_interface.show_character("ren_maid","gratified")
	await novel_interface.show_dialog("欢迎回来~~！主人~~~","小怜")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("主人想在蛋包饭上写什么喵~~","小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("果然……这种台词说出来羞死了啊！！！","小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("再来再来……","小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("ren_maid","sob")
	await novel_interface.show_dialog("唉~~都12点多了，赶紧换衣服睡觉！","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("……这身女仆装还真挺适合你的。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("嗯嗯~~会让人想忍不住调教一番呢！","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("从洗手间出来，我发现莉琉和爱衣坐在公寓的沙发上，似乎在强忍着笑容。")
	novel_interface.show_character("ren_maid","awkward")
	await novel_interface.show_dialog("——莉琉？爱衣也在？？","小怜")
	await novel_interface.show_dialog("你、你们什么时候进来的！！！","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("刚刚才到。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","awkward")
	await novel_interface.show_dialog("那、那那那那那你们……","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_wink")
	await novel_interface.show_dialog("全听到啦~！","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","sob")
	await novel_interface.show_text_only("让我死吧……！！")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("呜呜呜……你们突然过来做什么？","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("来看你趁大人不在家的时候，半夜偷偷穿上全套女仆装对着镜子手舞足蹈啊~","莉琉") #少字问题
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("为什么被你形容得那么变态啊！！\n（虽然确实大概是这样没错）","小怜")
	novel_interface.change_expression("shy_right")
	await novel_interface.show_dialog("还不是你安排的身份……","小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("哼哼，女仆的工作可不是像那几句浮于表面的台词那么简单的。","莉琉")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("不过你还算用心的份上，这次先放过你了~\n直升机在楼顶等着呢，咱们走吧。","莉琉")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("诶？这么晚了有任务？\n等我先换下衣服……","小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("不用了，这次的任务目标也是女仆，你这身……还蛮应景的…噗——","莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("你在笑对吧！你刚才绝对在笑吧！！")
	novel_interface.show_character("ren_maid","perspire1")
	await novel_interface.show_dialog("可、可这身……","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("你上次见到她们的时候，穿的也是这身衣服呢。","爱衣")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("诶？","小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wink")
	await novel_interface.show_dialog("到那你就知道了。","爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Hospital_Passage.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("我、莉琉和爱衣乘直升机来到了一所大型的医疗机构，但这个时间大多数工作人员都下班了。")
	await novel_interface.show_text_only("建筑充斥着各种设备工作的白噪音，我们一路走下来，只能听到自己脚步的回声。")
	await novel_interface.show_text_only("半夜空无一人的医院走廊，并不算昏暗的灯光，似乎比漆黑的环境能引发恐怖的联想。")
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("这……是医院吗？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("刚才在直升机上，我看到两位驾驶员都是熟识的探员，就觉得情况并不简单。")
	await novel_interface.show_text_only("莉琉很少具体参与任务的执行环节，但这次她似乎想将知情人员控制在最少。")
	await novel_interface.show_text_only("而且我注意到，这里所有的监控摄像头都扭向了墙壁的一侧。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("这是播磨脑科学综合研究中心，实验医疗部。","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("这次的目标是敏感角色，要绝对保密——包括元老院。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","worry")
	await novel_interface.show_dialog("播磨脑研……不是元老院下属的研究机构吗？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("因为我的身体状况，还被要求背下了要尽量避免接触的机构名单。")
	novel_interface.show_character("ren_maid","upset")
	await novel_interface.show_dialog("布莱特博士还曾经是这的研究员吧……","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("那个大猩猩现在有自己的地盘，已经跟这关系不大了。","莉琉")
	await novel_interface.show_dialog("说到底也是应用型研究部门，SID也会时常给这些机构发出订单。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("订单的数额还不小哦~这栋实验医疗部的大楼都是为此修建的。","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣比了个“钱”的手势。")
	await novel_interface.show_text_only("哈哈哈，真是让人安心的交易关系呢……")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("这次的目标是法贝拉，你在天空酒店的那次任务中与她有过一面之缘。","莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("就是那个看你笨手笨脚的，把你拉到一边臭骂了一顿的女仆","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("是那个人啊！——我记得戴着一副红框眼镜，她的主人是个小姑娘叫什么……","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("斯库尔德·艾克斯罗德，第二学园都市董事会成员之一独生女。","莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("四小时前，她通过『洗衣房』发来了信息。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("她……想叛逃？","小怜")
	await novel_interface.show_dialog("（我记得只是跟伊露卡差不多年纪的小孩吧！）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("根据她的情报，收容队在协约非武装区的一座教堂里发现了陷入昏迷的法贝拉。","莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("在她的血中检测到了麦角酰二乙胺类复合物，并在教堂里发现了军用级化学气溶胶散布装置。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("致幻类化学武器嘛……让敌方士兵互相残杀，可以说非常有想象力的设计。","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","solemn")
	await novel_interface.show_dialog("是……恐怖袭击吗？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("不，更像是诱捕——","莉琉")
	await novel_interface.show_dialog("根据斯库尔德的供述，法贝拉是魔女。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","wry_smile")
	await novel_interface.show_dialog("哈？？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我忽然有点明白大半夜将我叫到这里的原因了。")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("我们将法贝拉体内的致幻剂中和掉之后，发现她依然处于深度昏迷状态……","爱衣")
	await novel_interface.show_dialog("即使注射过量的左旋多巴也无法唤醒。","爱衣")
	await novel_interface.show_dialog("而且她的体细胞新陈代谢水平呈现指数级暴走的趋势，体温即使泡在冰水中也无法控制。","爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("一般人在这样的温度下早就大面积脏器坏死了，但她的身体似乎对高温有超常的耐受能力。","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("斯库尔德说法贝拉是体内寄宿了火焰魔法的魔女。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","upset")
	await novel_interface.show_dialog("寄宿……？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我注意到了那个奇怪的词。")
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("根据目前对收集到数据的分析，魔法大概可以理解为一种信息操作的知识。","莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("与伊露卡那种能直接操作电场的类型不同，法贝拉的状况是『某种庞大的信息』将她作为了宿主。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("怎么说的好像活物一样……","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("确实如此。当信息的密度足够大，熵值足够低，就可能产生自我意识。","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","angry")
	await novel_interface.show_dialog("随着法贝拉自身的理性离线，那种『活的信息』开始慢慢侵蚀她的身体……","莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我想起曾经看到过昏迷不醒的主人被自己养的宠物所吃掉的报导，头皮一阵发麻。")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("很快我就发现了问题——之所以无法唤醒她，是因为她本来就是清醒的。","爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("扫描发现她的海马体和前额叶皮质非常活跃，就好像在回忆某件事情。","爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("但脑干区域却没有任何有效的反射信号，又似乎被什么东西封闭了。","爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣有点兴奋的加快了语速。")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("当使用玻尔兹曼探测器扫描的时候，居然发现了异变空间的特征……","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","panic")
	await novel_interface.show_dialog("魔女之茧……在她的大脑里？？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("Bingo~！","爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("后来我想到，正好有一台SID为审讯和训练委托播磨脑研开发的大脑潜入装置。","爱衣")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("虽然只是原型机，但已经通过了阿尔法测试。","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_maid","wail")
	await novel_interface.show_dialog("所以抓我来做小白鼠了吗……","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("你是最终手段。","莉琉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_dialog("已经先后派了四名探员潜入法贝拉的大脑，但他们似乎都被某种东西拒绝了。","莉琉")
	novel_interface.show_background("res://assets/images/bg/Fabiola/TheWall.png")
	await novel_interface.show_dialog("这些探员共同的描述是“一堵无限延伸的墙壁挡在了他们面前。”","莉琉")
	
	print("=== 创伤反射篇第04话结束 ===")
	await novel_interface.end_story_episode(0.5)
