# traumareflex_ep13.gd - 创伤反射篇第13话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第13话剧本
	traumareflex_ep13_script()

func play_script():
	pass

# 创伤反射篇第13话 - 正式剧本
func traumareflex_ep13_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	await novel_interface.show_text_only("多亏短剑极低的后坐力和超高射速，弹匣内28发\n子弹在不到两秒的时间里被我倾泻一空。")
	await novel_interface.show_text_only("随着“嘭”的一声，被我拋到空中的气凝胶喷罐在蜘蛛头顶炸开，大团的泡沫瞬间涌出。")
	await novel_interface.show_text_only("泡沫落在那东西的躯干和八条机械腿上，迅速与空气反应并变色膨胀，就像凭空长出的一团团肉瘤。")
	await novel_interface.show_text_only("短短几秒，机械蜘蛛的多数关节部位都被淡绿色的凝固团块牢牢锁死，动弹不得。")
	await novel_interface.show_text_only("机体内部还在持续发出不甘的异响，似乎是驱动系统在做最后的挣扎。")
	await novel_interface.show_text_only("法贝拉走到蜘蛛面前，拿出匕首对着它头顶依然闪烁着红光的探测器，用力刺了下去。")
	await novel_interface.show_text_only("匕首在加固的透明外罩上只刺入了三分之一，蜘蛛的头部抽搐般晃动了一下，全身颤抖得更厉害。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("去死——！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉转身对着匕首尾部一记侧踢，巨大的力道将刀身完全钉入蜘蛛头里。")
	await novel_interface.show_text_only("红点终于暗淡下来，机体彻底沉默。")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("成、成功了？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("惊魂未定的我还紧握着冲锋枪，赶紧趁这个空档换好弹匣。")
	await novel_interface.show_text_only("法贝拉和卡塞尔将机械蜘蛛推开，扶起被门板压住的培尔纳德。")
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("刚刚那究竟是什么东西？！","莉娜")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("虫巢……","培尔纳德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("培尔纳德背靠车坐在地上喘着粗气，看来他在刚才的搏斗中累得够呛。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("那个不是早就被废弃的武器概念吗……","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("怎么回事……","莉娜")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("当时流行一种设计理念，即认为如果短期内无法让程序模拟经验丰富的士兵作战的话——","罗素")
	await novel_interface.show_dialog("那么就先让机器模拟行为模式简单得多的昆虫，进行集群式作战。","罗素")
	await novel_interface.show_dialog("后来由于某些原因这个概念被废弃了，但那玩意儿确实和网上流传的设计图很像。","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("因为新丰洲的『埃癸斯』系统向全世界显示了复杂AI的前景，于是投资者和研发资金纷纷转向。","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","bored")
	await novel_interface.show_dialog("所以才有了『黄雀』这种东西吗……","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("（等等，集群……式作战？）","小怜")
	await novel_interface.show_text_only("我刚才好像听到了很不妙的字眼――")
	await novel_interface.show_dialog("靠，那边是怎么回事！","卡塞尔")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Spider_Cluster.png")
	await novel_interface.show_text_only("我顺着卡塞尔手指的方向，看向昏暗的街道尽头。")
	await novel_interface.show_text_only("街道远处攒动着几十个小红点，红点背后蜘蛛形状的黑影比刚才袭击我们的那只体型小很多。")
	await novel_interface.show_text_only("那些蜘蛛就像是被某种信号所召唤，纷纷从两侧的楼上爬下。")
	await novel_interface.show_dialog("果然――！","小怜")
	await novel_interface.show_text_only("据说某些昆虫死亡后，会散发能吸引同类的气味。")
	await novel_interface.show_text_only("那种气味会吸引大量同类迅速聚集，并对袭击者展开猛烈的报复性攻击。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	await novel_interface.show_text_only("只见红点越聚越多，靠近我们的第一波蜘蛛迅速朝这边扑来。")
	await novel_interface.show_text_only("我们六人围成半弧形，将斯库尔德挡在后面。")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("自由开火！！","培尔纳德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一只蜘蛛直接向我跳来，我立刻端枪射击。")
	await novel_interface.show_text_only("这些蜘蛛比刚才的那只小很多，而且护甲更薄，能被子弹直接击穿。")
	await novel_interface.show_text_only("但这些小东西速度极快，还会时不时从四周高楼的窗户中冲出来。")
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("注意头顶！！","莉娜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉娜抽出手枪打掉两只从我们旁边建筑顶部落下来的蜘蛛。")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("怎么越打越多……\n我还剩两个弹匣！！","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wail")
	await novel_interface.show_dialog("（我只剩最后一个了啊！）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("罗素，查查附近哪有没窗户的封闭式建筑――\n要有多个出入口的。","培尔纳德")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("没窗户的建筑……这里！\n附近有个两层的加固仓库，顶部可以上到天台。","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("就是它了！","培尔纳德")
	await novel_interface.show_dialog("莉娜你先走，在建筑附近找合适的狙击位。","培尔纳德")
	await novel_interface.hide_character()
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("是！","莉娜")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("法贝拉，你带小队朝那转移。","培尔纳德")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("好！","法贝拉")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("……我？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("培尔纳德从法贝拉身上扯走最后两枚手雷，并掀开黑色风衣的一侧。")
	await novel_interface.show_text_only("这个身材高大的男人左侧肋骨下方裂开了一个大口子，暗红色的血液从伤口处正汩汩涌出。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("培尔纳德？！！","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("刚才那个大家伙真是有点难办……","培尔纳德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("众人无言，在战场上这样的伤口往往意味着最糟的状況。")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("我拖住它们，你们才有时间――","培尔纳德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("培尔纳德换上新弹匣，拍了拍法贝拉的肩膀。")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("你带着小队立刻转移，这是命令！","培尔纳德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("培尔纳德转身向蜘蛛群方向丢出两枚手雷，然后开始快速射击。")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("你自己小心。","培尔纳德")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……","法贝拉")
	await novel_interface.show_dialog("走……","法贝拉")
	await novel_interface.show_text_only("法贝拉低头背对着我们，身体微微颤抖。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("走！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她转过身来，眼神异常坚定。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("我们转移！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Factory.png")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.show_text_only("这个仓库就在附近一栋大厦的背后，我们顺着一楼的工业电梯升到二层库房。")
	await novel_interface.show_text_only("此时远处稀疏的枪击声已经停止，大家都沉默不语。") #换行问题
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("头儿……","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","sad")
	await novel_interface.show_dialog("罗素，联系总部通知我们的位置呼叫支援，记得让他们带EMP炸弹。","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉眼中似乎有泪光在闪烁。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("啊……啊是！","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("然后法贝拉利落的拿出手枪上膛，将枪口对准了我的头。")
	await novel_interface.show_dialog("……诶？","小怜")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Muzzle.png")
	await novel_interface.show_dialog("你，究竟是谁？","法贝拉")
	await novel_interface.show_text_only("法贝拉黑洞洞的枪口让我猝不及防，能感觉到自己的心跳在剧烈加速，汗也从我的额头渗了出来。")
	await novel_interface.show_dialog("腿上一点肌肉都没有，连找掩体都不会，你的素质不可能通过攻击队筛选。","法贝拉")
	await novel_interface.show_dialog("我们身上都带着敌我识别装置，『黄雀』居然没做出任何攻击，是因为怕误伤你这个“友军”吧？","法贝拉")
	await novel_interface.show_dialog("还有你刚才用的那种泡沫武器我从没见过，估计是哪个间谍机构的特种装备吧？","法贝拉")
	await novel_interface.show_dialog("快说！你是什么人？","法贝拉")
	await novel_interface.show_text_only("我心虚的回避着她的视线，气凝胶确实是间谍机构SID的特种装备。")
	await novel_interface.show_dialog("另外，无论是判断对方狙击手会攻击哪里，还是躲避那个机械蜘蛛的下坠重击――","法贝拉")
	await novel_interface.show_dialog("连我都察觉不到的危险，你一个菜鸟怎么会有这么敏锐的直觉？","法贝拉")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("我一时无语。")
	await novel_interface.show_text_only("从刚才起就一直困扰我的那种强烈违和感――")
	await novel_interface.show_text_only("前几次面临危险的时候，我也不知自己为什么会有那种强烈的冲动。")
	await novel_interface.show_text_only("就是……\n你有没有过那种感觉――")
	await novel_interface.show_text_only("蓦然回想起某个画面，却忘记了是何时的记忆。")
	await novel_interface.show_text_only("直至你早就知道会发生的一幕，终于被验证了。")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Muzzle.png")
	await novel_interface.show_text_only("包括被法贝拉用枪顶着头。")
	await novel_interface.show_text_only("我早知事情会变成这样……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("不是吗？")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Factory.png")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("等等！","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德突然用娇小的身体挡在了我前面。")
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("小怜姐姐是父亲安排在攻击队里的，我们已经认识很久了。","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("（真、真的吗？）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("……","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","worry")
	await novel_interface.show_dialog("那个泡沫武器是『董事会』委托研究机构开发的试验型产品，只是还没实装给『帕兰蒂尔』。","斯库尔德")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wail")
	await novel_interface.show_dialog("（不，完全是编的吧！！）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","painful")
	await novel_interface.show_dialog("虽然我劝父亲别在攻击队里安排眼线，但他总是不放心……","斯库尔德")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("但求你别伤害小怜姐姐，她绝不会出卖我们的。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("金发小姑娘做出一副委屈得要哭出来的样子。")
	await novel_interface.show_text_only("面对纯真无邪眼神的斯库尔德僵持片刻后，法贝拉终于有些动摇的将枪放下。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("唔……『黄雀』攻击和防御的AI模块是独立的，有可能那台只解放了防御模块。","罗素")
	await novel_interface.show_dialog("否则马萨达堡对纽摩利达斯做这种几乎是公开宣战的行为有点太不合理了……","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉思索了一下，把枪收回枪套。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("可恶――","法贝拉")
	novel_interface.change_expression("sob")
	await novel_interface.show_text_only("这次护送路线、时间、人员车辆情况都泄露了！！还……")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉重重的踢了一脚货箱。")
	await novel_interface.show_text_only("斯库尔德将满脸问号的我拉到一边坐下，并对我露出一个神秘的微笑。")
	novel_interface.show_character("skuld","proud")
	await novel_interface.show_dialog("你吓坏了吧~\n先喝点水压压惊，对了要吃糖吗？","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她将自己粉色的水壶打开递给我，还取出一个金属盒，倒出两粒糖塞到我手心里。")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("（意思是……我可以直接对嘴喝吗？）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("小怜姐姐，你是不是也……","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她似乎有些忐忑，不知道要如何开口。")
	novel_interface.show_character("ren_mercenary","worry")
	await novel_interface.show_dialog("嗯？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","think")
	await novel_interface.show_dialog("比如说，我今天是第一次见到你。","斯库尔德")
	await novel_interface.show_dialog("但看见你的那一刻，我就意识到自己有关于你的记忆……就像忽然回忆起来一样。","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我回想起来，斯库尔德确实给我讲过……")
	await novel_interface.show_text_only("关于她那种奇特的“预言”能力。")
	novel_interface.show_character("ren_mercenary","worry")
	await novel_interface.show_dialog("（虽然是在法贝拉的记忆中，但按照时间逻辑，现在的她确实之前没有见过我呢。）","小怜")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("（不过就这么把秘密说出来真的没问题吗？）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("所以，小怜姐姐――","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("斯库尔德满怀期待的看着我，接着问道。")
	novel_interface.show_character("skuld","smile")
	await novel_interface.show_dialog("你也有类似的能力吧？","斯库尔德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我嘴里含着糖，愣愣的看着她。")
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("……啊？","小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_text_only("仔细想来，那些预感……")
	await novel_interface.show_text_only("确实有点像某种“预言”的能力呢。")
	await novel_interface.show_text_only("话说……这个薄荷糖的味道真不错啊。")
	await novel_interface.show_text_only("不是太甜、酸味也恰到好处。")
	await novel_interface.show_text_only("在嘴里化开的时候，感觉凉凉的――")
	await novel_interface.show_text_only("就像……")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Hospital_Passage_R.png")
	await novel_interface.show_dialog("你能生动的形容出那种糖的口感和味道，但就是说不上来在哪吃到的。","斯库尔德")
	await novel_interface.show_dialog("只有某天你真的吃到了，才会恍然大悟就是它！","斯库尔德")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Factory.png")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("――！！","小怜")
	await novel_interface.show_dialog("斯库尔德，你的那个糖，给我看一下……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小姑娘对我的回复有点不明所以，但还是将糖盒递给了我。")
	await novel_interface.show_text_only("我惊异的看着那个金属盒上的图案——上面印着知名的游戏角色『哔咔之星』。")
	await novel_interface.show_text_only("粉红的主角翱翔在蓝天中，是上个月我才拜托安妮买的最新版游戏的造型。")
	await novel_interface.show_text_only("由于是45周年的纪念版，这两周新丰洲随处可见\n那款游戏的广告。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Billboard.png")
	await novel_interface.show_dialog("那个红蓝相间图样……","小怜")
	await novel_interface.show_text_only("从运兵车出来之后，我不是一直有见到吗？")

	print("=== 创伤反射篇第13话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
