# traumareflex_ep11.gd - 创伤反射篇第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第11话剧本
	traumareflex_ep11_script()

func play_script():
	pass

# 创伤反射篇第11话 - 正式剧本
func traumareflex_ep11_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_VTOL.png")
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("无人武装直升机——『黄雀』。")
	await novel_interface.show_text_only("七年战争期间，第三学园都市马萨达堡研发的这款重火力机体堪称地面单位的噩梦。")
	await novel_interface.show_text_only("完全依靠自律算法进行战斗判定，能轻松适应电波干扰的战场环境。")
	await novel_interface.show_text_only("但AI识别技术并不完美，这架重火力战机也因经常造成大规模平民伤亡而臭名昭著。")
	await novel_interface.show_text_only("很多国家已签署协议，禁止使用机器判定的杀伤性设备，而马萨达堡始终拒绝签约。")
	await novel_interface.show_text_only("现在，那架黄黑相间的噩梦正从我们对面大厦的上空缓缓下降。")
	await novel_interface.show_text_only("机体两侧挂载的12枚长钉导弹，足以犁平整条街区。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("嘘，不要动――","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉保持单膝跪地的姿势将手中的狙击枪放在地上，双手张开微微抬起，做出毫无攻击性的姿势。")
	await novel_interface.show_text_only("我刚才被狙击枪的冲击震倒，浑身僵硬的坐在地上大气也不敢喘。")
	await novel_interface.show_text_only("隐约中，我看到一个模糊的影子正从底部慢慢接近那架黄蜂。")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("（那台侦查机……有自爆功能吧？）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("悬停在半空的『黄雀』扫描着周围环境，忽然从尾部放出数十枚闪耀着橙色光芒的弹头。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("――！！","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wail")
	await novel_interface.show_dialog("（完蛋了！！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("只见那些弹头划出数道弧线，均匀散布在『黄雀』周围的空间中，然后同时爆炸。")
	await novel_interface.show_text_only("直升机背后大厦附近几层的玻璃和那台侦查机在火光中化成了一片晶莹的碎屑。")
	await novel_interface.show_text_only("在远处闪烁着的红蓝广告牌映衬下，就像一场魔幻大型烟火表演。")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("（无法确认威胁具体位置时，居然放出被导弹锁定才会使用的干扰弹。）","法贝拉")
	await novel_interface.show_dialog("（这就是由智能程序控制的战争机器吗……）","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("接着那架直升机调整了悬停角度，将头部对准了我和法贝拉――")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_VTOL.png")
	await novel_interface.show_text_only("机身底部复眼镜头的小红点像死神一样，凝视着暴露在马路中央的我们。")
	await novel_interface.show_text_only("在令人窒息的气氛中，时间一秒一秒度过。")
	await novel_interface.show_text_only("感受死亡迫近的过程远比死亡本身更为恐怖。")
	await novel_interface.hide_background()
	await novel_interface.show_dialog("（已经……过去多久了？）","小怜")
	await novel_interface.show_dialog("（法贝拉的记忆，也就是确实发生过的事件吧？）","小怜")
	await novel_interface.show_text_only("但这种莫名的违和感究竟……")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	await novel_interface.show_text_only("『黄雀』的机身突然歪了一下。")
	await novel_interface.show_text_only("随着一阵电离空气和金属撞击声，几块碎片从机体上散落了下来。")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("（是……狙击？！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("武装直升机瞬间扭向一侧并开始下坠，但很快就稳住了飞行高度。")
	await novel_interface.show_text_only("接着它试图摇摇晃晃的攀升，控制系统应该正根据损伤情况调整姿态。")
	await novel_interface.show_text_only("已经安静了许久的耳机传出一阵杂音，夹杂着一个成熟的女性声音。")
	await novel_interface.show_dialog("久等了，小家伙们……","女声")
	await novel_interface.show_dialog("不过移动电磁加速器只能用一次，普通的子弹是打不穿那个的哦~","女声")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("莉娜！？阿尔法小队那边怎么样？","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你们先照顾自己吧，那东西还没掉下来呢！","男声")
	await novel_interface.show_text_only("接着传来一个沙哑低沉的男性声音提醒我们危机还未解除。")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("法贝拉……\n人呢？？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我反应过来时，刚才蹲在旁边的法贝拉已不见踪影\n，只剩我一个人傻傻的坐在大街中央。")  #换行问题
	await novel_interface.show_text_only("片刻后，一个拖着橙色尾焰的黑影伴随着尖锐的呼啸声从翻倒的装甲车后腾空而起。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("卧倒！！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("轰——！！！")
	await novel_interface.show_text_only("直升机就像被法贝拉的嘶吼扯碎一般，从侧方喷出一大团橘黄色火焰。")
	await novel_interface.show_text_only("火焰迅速吞噬了整架机体，『黄雀』在旋转中冒着一道黑烟重重的砸到地面上。")
	await novel_interface.show_text_only("一扇扭曲的螺旋桨叶片从烟雾中飞出，随着咚的一声巨响，牢牢插在我两腿之间的沥青路面里。")
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("？","小怜")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("………………","小怜")
	await novel_interface.show_dialog("啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊！！！！！！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我赶忙手脚并用的向后蹭了一段距离，被吓得心脏差点跳出来。")
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("哈哈哈哈，瞧把你吓的~还能站起来吗？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉从装甲车后走出来，随手将发射完的毒刺弹筒丢在一边。")
	await novel_interface.show_text_only("我满脸通红的从地上爬起来，整理了一下散乱的头发。")
	await novel_interface.show_dialog("干的不错！","男声")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("培尔纳德？你们那边怎么样了！？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哟，都不先谢谢我嘛~","女声")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("谢谢米尔金前辈！！","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("你这家伙刚刚一声不吭…见到异性就马上兴奋…","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("“包裹”没事，施瓦茨牺牲，阿佐雷重伤。","男声")
	await novel_interface.show_text_only("声音沙哑的男性只用寥寥几个字就说明了情况，干练中透着一丝冷酷。")
	await novel_interface.show_dialog("警察和帕兰蒂尔的增援估计被拖在外围，很可能还会有下一波袭击。","男声")
	await novel_interface.show_dialog("这条路两边都被封死了，咱们到东边那条街汇合。","男声")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("明白。","法贝拉")
	await novel_interface.show_dialog("整理装备，立刻转移！","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("是！","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("车里那个……","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","bored")
	await novel_interface.show_dialog("那个白痴先留在原地。","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("是！","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting2.png")
	await novel_interface.show_text_only("我们带着补给弹药，打破街道一侧酒店的窗户转移到隔壁街道。")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("这附近灯全亮着，怎么一个人影都没有？","法贝拉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("russell","",0.25)
	await novel_interface.show_dialog("90分钟前疾控中心在这一带发布三级生物危险品\n泄露警报，但现在已经被撤下了。","罗素")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("罗素一边拨动着手中的平板一边说道。")
	novel_interface.show_character("fabiola_battle","thinking")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("russell","",0.25)
	await novel_interface.show_dialog("去年才停战，市民也都是惊弓之鸟，谁也不想跟炭疽病毒什么的打交道吧。","罗素")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("法贝拉眉头紧锁，继续问道――")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("那个『黄雀』……是全球范围禁售的吧？","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("当然了，那玩意儿的控制系统是他们的核心机密。","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("那咱们去把控制单元拆下来岂不……","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("做梦吧你，坠毁的第一时间芯片就启动自爆了。","罗素")
	await novel_interface.show_dialog("据说攻击和防御的AI模组是独立的，几个月前有个马萨达军官带着其中一个模组样本叛逃。","罗素")
	await novel_interface.show_dialog("然后摩诺拉一路追杀到别国领土，连人带交通工具给轰成了焦炭，还大摇大摆的把焦炭运回国。","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","wail")
	await novel_interface.show_dialog("（哈哈哈哈，他们的情报机构也好可怕……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("他们来了！","卡塞尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我顺着声音望去，街道后方走来几个人。")
	novel_interface.show_character("bernardo")
	await novel_interface.show_dialog("这边还有4个战力吗……有个新人？","培尔纳德")
	await novel_interface.show_dialog("把这附近的地图给我。","培尔纳德")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("身材高大的阿尔法队队长戴着眼罩，汇合后二话不说立刻开始与法贝拉研究起附近环境。")
	novel_interface.show_character("leena")
	await novel_interface.show_dialog("好可爱的小姑娘！\n啊你好，我叫莉娜·米尔金。","莉娜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_mercenary","gratified",0.25)
	await novel_interface.show_dialog("您好……叫我小怜就可以了。","小怜")
	await novel_interface.show_dialog("（她就是刚才开枪帮我们解围的人吧？）","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("拿着狙击枪，戴着彩色编织头巾的大姐姐上下打量着我。")
	novel_interface.show_character("leena")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_mercenary","gratified",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯……你这个风格……","莉娜")
	await novel_interface.show_dialog("就是年轻人说的那种，朋克少女？","莉娜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_dialog("并不是啦！！","小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("然而单腿上穿着破洞丝袜的造型丝毫没有说服力。")
	await novel_interface.show_text_only("嗯……")
	await novel_interface.show_text_only("从高大的男性身后闪出一个熟悉的身影。")
	novel_interface.show_character("skuld","normal")
	await novel_interface.show_dialog("你好呀，小怜姐姐。","斯库尔德")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("我们又见面了~","")
	
	print("=== 创伤反射篇第11话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
