# traumareflex_ep10.gd - 创伤反射篇第10话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep10_script()

func play_script():
	pass

func traumareflex_ep10_script():
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_FightingP.png")
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("水泥掩体的阴影中，法贝拉骑在我的腰间。")
	await novel_interface.show_dialog("我知道怎么避免反光了――","法贝拉")
	await novel_interface.show_text_only("她一边说着，一边将我牢牢的按在了地上。")
	await novel_interface.show_dialog("欸？\n（等等……她要做什么！？）","小怜")
	await novel_interface.show_text_only("法贝拉左手撑在我脸旁的地上，将右膝顶在我两腿之间，脸上露出一抹十分不妙的坏笑。")
	await novel_interface.show_text_only("接着她右手向下伸，轻轻勾起我大腿上的丝袜……")
	await novel_interface.show_dialog("嘘――","法贝拉")
	await novel_interface.show_text_only("被压制视线的我完全看不见她的动作，只能通过触感脑内想象正在发生的画面。")
	await novel_interface.show_dialog("（不、不要啊……）\n（那、那种……）","小怜")
	await novel_interface.show_text_only("我的脸颊发烫，心扑通扑通的跳个不停，手指条件反射般的挠着地面。")
	await novel_interface.show_dialog("（为什么想到的都是非常糟糕的画面啊！！？）","小怜")
	await novel_interface.show_text_only("似乎是想教训一下刚将她扑倒后有些得意的我，法贝拉对我现在惊慌害羞的表情显得相当满意。")
	await novel_interface.show_text_only("她突然手腕用力，我感觉一紧，随后“嘶”的一声丝袜被扯开了一个洞。")
	await novel_interface.show_text_only("与此同时，我不争气的叫出了声……")
	await novel_interface.show_dialog("啊~","小怜")
	await novel_interface.show_text_only("通讯耳机里传来咽口水的声音，然后是卡塞尔一阵猛烈的咳嗽。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("法贝拉接着撕开了整圈丝袜，然后将我的鞋子脱掉，顺着腿把丝袜脱了下来。") #换行问题
	await novel_interface.show_text_only("在她给我穿鞋的时候，我已经羞得说不出话了。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	novel_interface.show_character("ren_mercenary","sob")
	await novel_interface.show_dialog("（呜呜呜呜……）\n（腿上凉飕飕的……）","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("fabiola_battle","mock",0.25)
	await novel_interface.show_dialog("哼哼，挺白嫩的嘛……\n一点肌肉都没有。","法贝拉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("哈哈哈哈那还真是抱歉。")
	await novel_interface.show_text_only("我的大脑还在颤抖，法贝拉却立刻恢复了指挥官的理智。")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("喂喂，你们几个都听傻了？","法贝拉")
	await novel_interface.show_dialog("还不快想想锁定位置之后，怎么干掉对面的狙击手。","法贝拉") #换行问题
	await novel_interface.show_dialog("没猜错的话，这个家伙的任务只是拖住我们，而真正的战场在那边……","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉看向我们后方被截断燃烧着的道路，远处隐约传来交火的声音。")
	await novel_interface.show_dialog("嗯……短距电磁加速装置的充电时间大约4.5秒。","罗素")
	await novel_interface.show_dialog("那个设备需要瞄准镜专门校准，所以就算枪械允许也不太可能连发。","罗素")
	await novel_interface.show_dialog("我们要在第一枪之后马上找到对方位置，并在他开出第二枪之前将其干掉。","罗素")
	await novel_interface.show_dialog("问题是狙击枪还在车厢里，而且也不知道如何安全的吸引他开出第一枪……","卡塞尔")
	await novel_interface.show_text_only("法贝拉用反光镜观察着前方，发现倾倒的装甲车尾部的一扇车门板。")
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("……那个是被爆炸索一起弹出来的吧？","法贝拉")
	await novel_interface.show_dialog("你们能查到咱们那辆贵得不靠谱的运兵车上，异质物装甲的耐受数据吗？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("老大，你是说做为盾牌……","罗素")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("……应该没问题。","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("哦？","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","sprite")
	await novel_interface.show_dialog("网上有个土豪用那种车做射击测试的视频――","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("在视频中，即使用配有电磁稳定加速设备的巴雷特M82A1直轰，车厢都岿然不动。")
	await novel_interface.show_text_only("虽然有点哗众取宠，但那个满嘴俄式英语的土豪做的武器评测视频确实颇受欢迎……")
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("那就你上吧~","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("啊？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉摸了摸我的战术夹克，像是找准位置然后猛然发力，一记冲拳锤在了我身上。")
	await novel_interface.show_text_only("看气势那一拳下去我可能会当场去世，但却只觉得上半身震了下。")
	await novel_interface.show_text_only("多亏了非牛顿流体填充物的保护，平时柔软的材质在受到冲击时会突然变得坚硬无比。")
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("这身外套不错嘛，一会记得隔着它顶住车门哦。","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("不――","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没等我拒绝，她就把面罩套在了我嘴上。")
	await novel_interface.show_text_only("接着法贝拉从腰间掏出一把玩具似的手枪，瞄准对面大楼顶部的位置。")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("6秒闪光弹，准备――","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("“嘭”")
	await novel_interface.show_text_only("手枪射出一个极亮的光点划破了夜空，飞到半空后缓缓下落。")
	await novel_interface.show_text_only("法贝拉并没立刻行动，而是等光点下落到合适的位置才拉着我飞奔到倾倒的运兵车后面。")
	await novel_interface.show_text_only("卡塞尔和罗素也看准时机，默契的转移到能与我们交流的掩体中。")
	await novel_interface.show_text_only("法贝拉在车厢后门输入密码，从弹出的武器架上拿走一只轻便的Scout。")
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("快速瞄准的话，这把比较顺手……","法贝拉")
	novel_interface.change_expression("thinking")
	await novel_interface.show_dialog("卡塞尔，你先把无人机准备好，用大楼拐角做掩体升到一定高度后再出来。","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉一边下着命令，一边将刚从我腿上脱下的丝袜缠在石头上丢给了卡塞尔。")
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("还是热的哦~","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("卡塞尔接到后看了看我，好像有些不好意思，我满脸通红的回避了他的视线。")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("罗素，你做观察手，盯着传输图像给我报位置。","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("明白。","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("接着法贝拉拿起地上的车门板，查看了一下上面异质物装甲蜂窝形的反光纹路，然后塞到了我手里。")
	await novel_interface.show_text_only("装甲门板比想象中轻，单手也能勉强举起来。")
	novel_interface.show_character("ren_mercenary","sob")
	await novel_interface.show_dialog("（不过为什么是我当诱饵啊！！）","小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（虽然好像我也不会做其他的……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她一把将我搂过来，凑在我耳边说道――")
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("听好了，一会你听我的指示顶着这块门板从浓烟那一侧走出去。","法贝拉")
	await novel_interface.show_dialog("对方在大楼的30层到50层之间，你用它要好好罩住自己，别不小心露个屁股什么的……","法贝拉")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("除非你以后都不想要屁股了~","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("说完她就把我推到烟雾中，示意我待命。")
	await novel_interface.show_text_only("此时，卡塞尔已经将丝袜套在了镜头上，并在暗处将无人机升到了10层楼的高度。")
	await novel_interface.show_text_only("折光涂层使无人机几乎与背景融为一体，如果不刻意观察的话，根本看不出它的存在。")
	await novel_interface.show_text_only("卡塞尔和罗素都朝我们做了OK的手势，法贝拉也将手中的狙击步枪上膛，对我点了点头。")
	novel_interface.show_character("ren_mercenary","wry_smile")
	await novel_interface.show_dialog("没办法了……","小怜")
	await novel_interface.show_dialog("（反正爱衣说就算在潜入中死掉也没事……）","小怜")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("（等等，她还说我只会作为旁观者呢！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("犹豫中，我的屁股忽然被枪口戳了一下，旁边的法贝拉做出一副随时准备开枪的样子。")
	await novel_interface.show_text_only("我不情愿的顶着车门板慢慢前移，一步一步走出了烟雾……")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("（拜托那个土豪可千万别坑我啊……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我逐渐前进，一直走到离开浓烟五六步的位置。")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("（……还没开枪？）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("现在我应该清晰的出现在狙击手的视野内了，不会被识破了吧……")
	await novel_interface.show_text_only("突然身后传来一阵急促的脚步声，法贝拉一套疾跑滑铲，最后以半蹲的姿势停到了我脚边。")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("――你？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("挡好！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然我小臂上的门板发出“铛”的一声巨响，猛烈的冲击使身体瞬间失去了平衡。") #文字错误
	await novel_interface.show_text_only("我一屁股坐在地上，门板也被摔到一边，我和法贝拉直接暴露在大街上。")
	novel_interface.show_character("ren_mercenary","wail")
	await novel_interface.show_dialog("（——惨了！！）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("42层，右面第三扇窗户！激光指向打开了！","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("隐藏在夜空中的无人机射出一道红色的激光，指向对面大楼的一扇窗户。")
	await novel_interface.show_text_only("砰！")
	await novel_interface.show_text_only("砰！砰！")
	await novel_interface.show_text_only("法贝拉快速的连开三枪。")
	await novel_interface.show_text_only("接着是死一般的寂静，我甚至能听到心脏将血液泵入大脑的声音。")
	await novel_interface.show_text_only("漫长的读秒中，我已经做好了被一道白光带走的准备。")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("确认击杀！重复，确认击杀！！","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","sob")
	await novel_interface.show_dialog("哈——啊~~~","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("厉害！！","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉却依然保持着射击姿势蹲在原地。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("嘘，安静，你们听到没有――","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("远处隐约传来直升机螺旋桨特有的声音。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("这个声音……VTOL？！","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("靠！是『黄雀』！！","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("什么？！那东西在闹市区飞？？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("黄雀——在七年战争期间马萨达堡研发的重火力无人武装直升机。")
	await novel_interface.show_text_only("特征是机体外挂载的12枚反坦克导弹，非常善于 执行“清扫”任务。")
	await novel_interface.show_text_only("当那架黄黑相间的死神从天而降，悬停在我们前方大厦正面的时候。")
	await novel_interface.show_text_only("我明白…这一切终于都完了……")
	
	print("=== 创伤反射篇第10话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
