# traumareflex_ep08.gd - 创伤反射篇第08话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	traumareflex_ep08_script()

func play_script():
	pass

func traumareflex_ep08_script():
	novel_interface.change_background("res://assets/images/bg/Shot/storyBGWar.png")
	await novel_interface.show_text_only("这个世界，并不善良。")
	await novel_interface.show_text_only("十年前的那场战争夺去了很多美好的东西。")
	await novel_interface.show_text_only("虽然福利院里有很多和我一样的小孩，但我常常觉得自己是最不幸的。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Mother.png")
	await novel_interface.show_text_only("或许是因为，每个人都会格外重视自己失去的东西吧……")
	await novel_interface.show_text_only("但在埃癸斯庇护下的我无法想象——")
	await novel_interface.show_text_only("那些失去了亲人后，依然要在战火中艰难生存下去的人，每天面对的是怎样的生活。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("呼——哈——")
	await novel_interface.show_text_only("呼——哈——")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	novel_interface.change_music("res://assets/audio/music/Hand-to-hand combat.mp3")
	await novel_interface.show_text_only("我好不容易靠面罩磕磕绊绊的走出了浓烟，躲到停在路边的一辆车后面。")
	await novel_interface.show_text_only("地面上密布着瓦砾和碎石块，周围传来无法分辨方位的呼喊和接二连三的爆炸声。")
	await novel_interface.show_text_only("透过火光和烟雾，能看到远处高楼的大屏幕上正播放着色彩绚丽的广告。")
	await novel_interface.show_text_only("一种诡异的不真实感油然而生。")
	novel_interface.show_character("ren_mercenary","solemn")
	await novel_interface.show_dialog("（不知道法贝拉的记忆中有多少这种经历……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这样的生活，离我实在太遥远了。")
	await novel_interface.show_text_only("虽然加入SID后我接受了不少训练，但大多是战术和情报操作方面的。")
	await novel_interface.show_text_only("别说实弹演习，即使在训练靶场我也只敢用后坐力最小的那几把枪，还总被莉琉和安妮笑话……")
	novel_interface.show_character("ren_mercenary","sob")
	await novel_interface.show_dialog("（呜呜，要是安妮在就好了~~）","小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("话说我手中这把是……KRISS？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("短剑冲锋枪，以超低的后坐力著称，亚音速的手枪弹也很体贴耳膜，被莉琉戏称为“呲水枪”。")
	await novel_interface.show_text_only("……谁像她总喜欢用那种大炮似的玩意啊！！")
	await novel_interface.hide_background()
	novel_interface.show_character("ren_mercenary","uneasy")
	await novel_interface.show_dialog("如、如果是这把武器的话……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我看着底部的加长弹匣，吞了吞口水。")
	novel_interface.show_character("ren_mercenary","shy")
	await novel_interface.show_dialog("（还是先关着保险吧，万一打到自己人就……）","小怜")
	novel_interface.show_background("res://assets/images/bg/Fabiola/Street_Fighting1.png")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我偷偷探出半个脑袋，观察外面的情况——")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("卡塞尔，驾驶室那个怎么样了？","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("司机死透了！！见鬼！见鬼……\n我靠，这傻帽还有气儿！！！","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("给他戴上防毒面罩丢后车厢里，然后拿上装备立刻找掩护！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("几位攻击队员没有片刻迟疑，法贝拉带着一个黑色手提包三两下就跳到了我附近的掩体后面。")
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("（……是我眼花了吗？动作好快！！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("罗素将刚才被炸开的顶部甲板立在石堆旁制造了一片盲区，然后在掩护下匍匐到了街对面。")
	await novel_interface.show_text_only("数秒后烟雾中丟出一个大背包，停顿片刻后卡塞尔一套跃进翻滚，迅速钻进了拐角的阴影中。")
	await novel_interface.show_text_only("这种状况对经常在热点地区执行任务的攻击队而言并不陌生吧……")
	await novel_interface.show_text_only("只不过这次换到了第二学园都市城区内。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("小心机械部队，放无人机观测战场环境！！\n罗素能联系到阿尔法队吗？","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("那边没回复，他们和“包裹”在爆破带的那头。","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我顺着罗素指的方向看去，街道前后的道路都被整齐炸开，我们被隔在道路中间的区域。")
	await novel_interface.show_text_only("大块的沥青地面翻起燃烧着，完全看不清对面的状况。")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("（……是预先埋的炸弹吗？）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("喂！新人！！你管那儿叫掩体吗？","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_mercenary","perspire1")
	await novel_interface.show_dialog("——啊？！\n（是说我吗？）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我还在发愣间脖子上突然传来一股巨力——法贝拉揪着我的外套把我拽到了街边ATM机的阴影中。")
	novel_interface.show_character("fabiola_battle","perspire")
	await novel_interface.show_dialog("你都不知道敌人在哪，躲在那么亮的地方是想让人以为你是路过的小姐吗？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没等我回应，她又转身对街道另一侧的罗素做了个手势，对方则回应了直指天空的大拇指。")
	await novel_interface.show_text_only("几秒后，他躲藏的汽车后面缓缓升起一个灰色的圆盘形飞行器。")
	await novel_interface.show_text_only("法贝拉从腰间掏出小型平板，观察着上面显示的战区俯瞰图。")
	await novel_interface.show_text_only("车队中打头的是两辆SUV，此时它们已经变成了冒着黑烟的火球。")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("那帮保镖都完蛋了……阿尔法队和“背包”的车在咱们后面。","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然平板显示的画面变成了一片雪花，紧接着传来“轰”的一声。")
	await novel_interface.show_text_only("伴随着微弱的电离空气的声音，灰色的飞行器在空中炸成了碎片。")
	await novel_interface.show_text_only("细碎的零件从半空中落下，砸在附近的车顶，发出金属撞击的声音。")
	novel_interface.show_character("ren_mercenary","serious")
	await novel_interface.show_dialog("——狙击手！？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("在对面楼上！是短距电磁加速的反器材设备，注意掩体厚度！！","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("电磁稳定加速的金属弹头，穿透力巨大，缺点是设备难以移动位置。")
	await novel_interface.show_text_only("战争期间某国首相在500米外隔着一米厚的水泥墙被狙杀，让这种组合狙击装置名声大振。")
	await novel_interface.show_text_only("这些知识并不在之前的培训内容里，不过某款游戏中这套武器的限定涂装价格太让人过目不忘了……")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("『眼睛』被击落！重复！『眼睛』被击落！！","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("对方至少在800米外，咱们还剩一台有折光涂层的无人机挂载了全知之眼，应该不会被看到……","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","panic")
	await novel_interface.show_dialog("慢着，那个挂载镜头直径有15厘米吧——","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉用反光镜观察着对面灯火通明的大厦。")
	novel_interface.show_character("fabiola_battle","thinking")
	await novel_interface.show_dialog("就算在晚上，没法覆盖涂层的镜头也会反光。","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("难办了……那栋楼里都是普通市民，不能精确定位的话没法还击。","卡塞尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("对狙击手而言，最重要的就是不要暴露位置，尤其是那种难以移动换弹又慢的设备。")
	await novel_interface.show_text_only("这是战术训练课程中教过的知识。")
	await novel_interface.show_text_only("但我记得在情报操作课程上似乎还有补充……")
	novel_interface.show_character("ren_mercenary","normal1")
	await novel_interface.show_dialog("（最不该暴露的……只是『位置』吗？）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("刚才那枪首先暴露的，首先是TA的『存在』吧？")
	await novel_interface.show_text_only("对方要么是个上来就暴露了自己存在，等着被目标找到位置干掉自己的菜鸟。")
	await novel_interface.show_text_only("要么就是已经知道第二枪要射向的高价值目标在什么位置……")
	await novel_interface.show_text_only("我的内心突然发出一道警兆——")
	await novel_interface.show_text_only("身体几乎是条件反射一般弹起，将紧靠掩体观察的法贝拉扑倒在地。")
	novel_interface.show_character("fabiola_battle","angry")
	await novel_interface.show_dialog("干什么！笨——","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("紧接着，她刚刚倚靠的掩体轰然碎裂。")
	await novel_interface.show_text_only("击碎掩体后，子弹剩余的动能驱动着它钻透了建筑墙面，并在墙体隆高一平米宽的鼓起。")
	await novel_interface.show_text_only("ATM机器的挡板被挤掉，大量的钞票像雪片般被\n喷向半空，在路灯的白光下翻滚着徐徐飘落。")
	await novel_interface.show_text_only("整个画面有种黑色电影的奇异美感……")
	await novel_interface.show_text_only("我还在看得发呆，法贝拉突然用大腿夹住我的腰向侧面滚进了一片水泥垛的阴影中。")
	novel_interface.show_character("ren_mercenary","awkward")
	await novel_interface.show_dialog("（欸？怎么突然变成我被压在下面了？？）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("没事吧老大！！","卡塞尔")
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("啊……没事！\n看来新人还挺机灵的~","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("法贝拉骑在我身上，一边回复一边拍了拍我的脸。")
	novel_interface.show_character("fabiola_battle","wink")
	await novel_interface.show_dialog("还有，我知道怎么避免反光了——","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她一边说着，一边把手伸向了我的大腿。")
	
	print("=== 创伤反射篇第08话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
