# traumareflex_ep01.gd - 创伤反射篇第01话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	# 播放创伤反射篇第01话剧本
	traumareflex_ep01_script()

func play_script():
	pass

# 创伤反射篇第01话 - 正式剧本
func traumareflex_ep01_script():
	novel_interface.show_background("res://assets/images/bg/Fabiola/Brain.png")
	await novel_interface.show_text_only("『病觉缺失』――")
	await novel_interface.show_text_only("指人可能在一段时间内，完全意识不到自己失去了某种官能的状态。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/Anton's_Blindness.png")
	await novel_interface.show_text_only("失明的人坚信自己的视觉毫无问题、并能生动的描述出他所臆想出来的周围环境。")
	await novel_interface.show_text_only("瘫痪的人认为自己依然可以正常的移动肢体，甚至认为他视野内的其他人也做了相同的动作……")
	await novel_interface.show_text_only("临床上称这种现象为『安东盲目症』。")
	await novel_interface.show_text_only("大脑为了给矛盾的现象编造合理的解释，会不停制造虚假的影像。")
	await novel_interface.show_text_only("或许这是人类的原始本能之一――")
	await novel_interface.show_text_only("一种刻印在遗传基因中，在面对未知事物时……古老的保护机制。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	novel_interface.change_music("res://assets/audio/music/Noise.mp3")
	await novel_interface.show_text_only("头痛。")
	await novel_interface.show_text_only("剧烈的头痛。")
	await novel_interface.show_text_only("就像有人把一袋水泥丢进了我的脑子，然后慢慢搅拌……")
	await novel_interface.show_text_only("脑壳内嗡嗡作响，伴随着阵阵尖锐的耳鸣。")
	await novel_interface.show_text_only("我这是……进来了吗？")
	novel_interface.change_background("res://assets/images/bg/Fabiola/APC_Blur.png")
	await novel_interface.show_text_only("我逐渐睁开眼，瞳孔开始慢慢适应周遭的光线。")
	await novel_interface.show_text_only("但耳朵还没适应过来，所有的声音似乎都隔着一层屏障从很远的地方传来。")
	await novel_interface.show_text_only("空气中有古龙水的味道，混在皮革和黄铜特有的锈味里……")
	await novel_interface.show_text_only("被厚重装甲包裹的狭小空间内，两排座椅相对排列，坐在上面的人正有说有笑的聊着天。")# 换行问题
	await novel_interface.show_text_only("虽然没有统一的制服，但每人身上都装备有发光的圆形敌我识别装置。")
	await novel_interface.show_text_only("这是第二学园都市情报机构『帕兰蒂尔』所属特种攻击队的装备特征。")
	await novel_interface.show_text_only("要是没看错的话……我这是在F-950 SWAT TRUCK的肚子里？？")# 换行问题
	await novel_interface.show_text_only("几年前有个土豪买来一辆这种贵得惊人的装甲运兵车，在内部做了奢华至极的夜店风格改装。")
	await novel_interface.show_text_only("然后他让人在车外面用各种武器轰击车体，自己和几个小姐姐坐在车里喝香槟。")
	await novel_interface.show_text_only("那段视频在网上火了好一阵，也使这辆使用异质物特种加固装甲的运兵车名声大振。")
	novel_interface.change_background("res://assets/images/bg/Fabiola/NewMoridas.png")
	await novel_interface.show_text_only("车内投影屏中正播放着车体顶部摄像头传回的实时画面。")
	await novel_interface.show_text_only("夜空下，繁华的大都市灯光璀璨，视野内还有十几座正在修建的摩天大楼。")
	await novel_interface.show_text_only("钢筋铁骨赤裸裸的伸入天空，就像人类不加掩饰的野心。")
	await novel_interface.show_text_only("密布的高层建筑群背后，遥远海面上那个巨大的黑色半球状『黑域』在夜幕中若隐若现。")
	await novel_interface.show_text_only("在『十七绅士董事会』管理下，这座学园都市继承了战前世界经济和金融中心的地位，并更甚从前。")
	await novel_interface.show_text_only("没错，这就是『第二学园都市』——纽摩利达斯。")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("几小时前。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("就是说，你要我潜入目标的大脑并读取她的记忆？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("简单来说就是这样。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("等等，这种事情真能办得到吗？","小怜")
	novel_interface.change_expression("speechless")
	await novel_interface.show_dialog("那种能直连大脑的设备……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("无论是登录到某个服务器还是别人的大脑――")
	await novel_interface.show_text_only("根据之前看过的各种动画和电影，这种设备通常都充满了非常不妙的设定啊！！")
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("嘛……安心安心。","爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("这是播磨脑研提供的试验型设备，一开始就是为了情报挖（拷）掘（问）而设计的。","爱衣")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("而且我亲自升级了保险装置，绝不会出现那种脑内受伤或死亡会牵连本体的状况啦。","爱衣")
	await novel_interface.show_dialog("连接六个小时就会自动唤醒，安全性十分可靠。","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("好、好吧……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着爱衣自信的表情，我稍微安心了些。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("听好了，在连接时你不存在实体，只是个纯粹的观察者，就像鬼魂一样。","莉琉")
	await novel_interface.show_dialog("你要尽量找到目标回忆中的关键信息，不能放过每一个细节。","莉琉")
	await novel_interface.show_dialog("目标现在处于深度昏迷中，我们对她的过往经历了解不多，不知道她被锁定在哪段回忆中。","莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_stare")
	await novel_interface.show_dialog("也就是说，即使目标要去洗澡，你也不能放过其中任何细节哦~！","爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("怎、怎么说的好像偷窥狂一样！","小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("如果只是看看的话……","小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("唔……","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_stare",0.25)
	await novel_interface.show_dialog("嗯嗯，我懂的！","爱衣")
	await novel_interface.show_dialog("可惜没法进行实体的互动，这台设备也暂时无法引发神经刺激，不然的话……","爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("说着爱衣满脸红晕的抱紧了自己。")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("我、我才不是那个意思！！！","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉卷起手中的纸卷，“啪”的一声猛抽在爱衣的头上。")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("现在，我似乎顺利进入了目标的记忆。")
	await novel_interface.show_text_only("原本还以为就像在FPS游戏中的观察视角那样。")
	await novel_interface.show_text_only("但实际上复杂的多――")
	await novel_interface.show_text_only("记忆中的细节所见之处大多都非常模糊，要很费力才能将目光聚焦。")
	novel_interface.change_music("res://assets/audio/music/Noise.mp3")
	novel_interface.change_background("res://assets/images/bg/Fabiola/APC_Blur2.png")
	await novel_interface.show_text_only("此刻装甲车内坐着几个身材魁梧的男性，我正努力分辨着他们的发言……")
	await novel_interface.show_dialog("联合议会已经宣布停战一年多了，可六个成员国之外的地方就他妈没消停过……","男声A")
	await novel_interface.show_dialog("现在六国的首脑正在开『国际和平论坛』，第一大道那边都被示威的人群挤满了。","男声A")
	await novel_interface.show_text_only("一个有些沙哑的男声从驾驶舱的副座传来，但现在的视角看不到他的样子。")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("那个和平论坛这已经第二届了吧？一点作用都没有。","男性B")# 换行问题
	await novel_interface.show_dialog("现在第三学园都市城外3公里的地方依然是每个礼拜都发生两三起炸弹袭击。","男性B")
	await novel_interface.show_dialog("我住在那的姑妈早都习以为常了，据说只要爆炸再离得稍微远点，那一带的小孩都懒得哭。","男性B")
	await novel_interface.show_text_only("跟他接话的人皮肤苍白，三四十岁的样子，深棕色的头发梳得一丝不苟。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("如果是联合议会宣布停战一年多的时间点，再加上第二届『国际和平论坛』……")
	await novel_interface.show_text_only("这段记忆应该是两年前的情景？")
	await novel_interface.show_text_only("下个月第四届『国际和平论坛』就轮到在新丰洲举办了。")
	await novel_interface.show_text_only("我记得莉琉上周还在抱怨，不知道到时候协约非武装区会乱成什么样子……")
	await novel_interface.show_dialog("那帮恐怖分子简直就是群疯子！","男声A")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("看马萨达新的都市防卫计划，就是想把城市直接改造成超级堡垒吧。","男性C")
	await novel_interface.show_text_only("坐在对面的男人大概20多岁，小麦色的皮肤，戴着印有骷髅样式的围巾。")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("咳！在马萨达打仗只是家常便饭而已，指不定哪天又有一枚核弹头落在他们头上。","男性B")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("嚯！你们听说了吗，董事会的那帮人――","男声A")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("那些老板们又怎么了？","男性B")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("他们居然同意志愿者组成考察团进入『黑域』了！","男声A")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("长岛外面那个看着就瘆人的黑色穹顶？","男性B")
	await novel_interface.show_dialog("无人机进去就失联，我还没见有什么东西进去之后还能出来的。","男性B")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("要不是那个凭空出现的玩意儿一口气吞了十二个航母战斗群，现在早就没董事会那帮人什么事儿了。","男声A")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("没准它连着罗素老妈的厨房？哈哈哈哈哈！","男性C")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("少放屁吧卡塞尔！我看那儿是你的外星老家！","罗素")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("哼，无论哪个年代，都不缺因为好奇心而寻死的笨蛋。","女声")
	await novel_interface.show_text_only("诶？好像有女孩子的声音？")
	await novel_interface.show_text_only("在一群粗放的男性声音中显得格外突兀。")
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_text_only("我循着声音望去，在卡塞尔宽大的肩膀后面，坐着一名粉色头发，戴着贝雷帽的少女。")
	await novel_interface.show_text_only("那副红框眼镜让我一眼就认出来，她就是这次的目标，之前在天空酒店有过一面之缘的——法贝拉。")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("副驾驶舱上的一阵咳嗽声打断了我的思绪。")
	await novel_interface.show_dialog("法贝拉大姐说得对！对了，前段时间新丰洲不是冒出个女科学家，叫莉什么来着？","男声A")
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("莉琉？哈哈我记得~","卡塞尔")
	await novel_interface.show_dialog("她在上期《科学》封面穿黑丝的那张照片让研究部门的书呆子都炸锅了。","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("你小子还看《科学》？！难不成打算用量子物理泡妞吗？","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("谁让麦克斯那家伙一口气买了20本。","卡塞尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉那时候就很出名了吗？如果可能的话，那个杂志封面请务必给我也看看！！")
	await novel_interface.show_dialog("听说是个身材火辣的美女，嘿嘿嘿~","男声A")
	await novel_interface.show_text_only("这位大哥，你的想法很危险啊……搞不好会被做成切片的！")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("队长正看着你呢！","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","normal")
	await novel_interface.show_dialog("这种看见美女照片就变成弱智的家伙早都没救了。","法贝拉")
	novel_interface.change_expression("mock")
	await novel_interface.show_dialog("小心又像约会网站那次一样，第二天早上被人扒个精光，直接丟在废车处理厂。","法贝拉")
	novel_interface.change_expression("wink")
	await novel_interface.show_dialog("不知道的还以为你和那辆六二年的切诺基上床了呢，那辆车年纪够当你奶奶了吧？","法贝拉")# 换行问题
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("哈哈哈哈哈哈~~老大你就别臊他了，那件事整个南区分部全知道了。","卡塞尔")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那个不到20岁的小姐姐居然是这帮攻击队员的老大吗？")
	await novel_interface.show_text_only("和之前见她的女仆形象反差好大，期间到底发生了什么啊。")
	await novel_interface.show_text_only("不对，如果这是两年前的话，应该是她之前到底经历了什么吧……")
	await novel_interface.show_text_only("总之目标已经找到了，虽然视线还有点模糊，而且头一直很疼。")
	await novel_interface.show_dialog("哎哎哎求求你们别再提了！","男声A")
	await novel_interface.show_dialog("咳咳…对了！今天有个刚通过筛选的菜鸟入队了吧？","男声A")# 换行问题
	await novel_interface.show_dialog("好歹在新人面前给我留点面子……","男声A")
	await novel_interface.show_text_only("队伍里有新人？")
	await novel_interface.show_text_only("这种作战小队，队员之间早就培养出默契，有个菜鸟突然加入确实是挺麻烦的……")
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("小子，刚刚我就注意到了，你一直在那儿瞎摸什么呢？","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("是在找自己的脑袋吗？它好好的待在你脖子上呢！","卡塞尔")
	await novel_interface.show_dialog("不过一会儿就不一定啦！哈哈哈哈！","卡塞尔")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","bored")
	await novel_interface.show_dialog("别吓人家了，待会儿走不动路了你们背吗？","法贝拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("嗯？他们在跟谁说话？")# 修复文本错误
	await novel_interface.show_text_only("视线依然有些模糊，我想揉揉眼睛，手却撞到了一片看不见的屏障。")
	await novel_interface.show_text_only("――等等，我能感觉到自己的手？")
	await novel_interface.show_text_only("对了，还有从一开始就觉得头疼……")
	await novel_interface.show_text_only("爱衣不是说这种潜入装置无法引发神经刺激吗？")
	novel_interface.change_background("res://assets/images/bg/Fabiola/APC.png")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	await novel_interface.show_text_only("突然，卡塞尔把手伸向我，一把将封闭式头盔取了下来，我的视野顿时清晰了起来。")
	await novel_interface.hide_character()
	novel_interface.show_character("russell")
	await novel_interface.show_dialog("居然――","罗素")
	await novel_interface.hide_character()
	novel_interface.show_character("fabiola_battle","mock")
	await novel_interface.show_dialog("呦嚯……","法贝拉")
	await novel_interface.hide_character()
	novel_interface.show_character("cassell")
	await novel_interface.show_dialog("是个妹子？！","卡塞尔")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("什么？？！长得正吗？","男声A")
	await novel_interface.show_text_only("……")
	novel_interface.show_character("ren_mercenary","panic")
	await novel_interface.show_dialog("诶――？","小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("这、这是怎么回事？？！！","小怜")
	
	print("=== 创伤反射篇第01话结束 ===")
	
	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
