# chapter2_ep05.gd - 第二章第5话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep05_script()

func play_script():
	pass

func chapter2_ep05_script():
	var player_name = GameConfig.player_name
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/hearingRoom.png")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("从今天早上开始，我们突然侦测到了新丰洲市内多处起『时空相位波动』的警报。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("就好像一夜之间什么东西觉醒了一样……", "莉琉")
	await novel_interface.show_dialog("监控卫星显示，你曾经凭空消失在异变区域内，不久后突然出现在另一边，身边还多了个人。", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉眼神看向安妮。")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("然后你们两个出现的地方，这种波动自行消失了。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","worry",0.25)
	await novel_interface.show_dialog("异变区域？是研究中心吗？", player_name)
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("没错。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("会不会是机器故障什么的……我可是一直都在大路上啊。", player_name)
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("莉琉的表情变得严肃了起来。")
	novel_interface.character_light(0.35,"serious")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你以为，随便什么人都能出入『时空相位波动』的区域吗？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("那个什么波动……很严重吗？", player_name)
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("还真是什么都不懂……", "莉琉")
	await novel_interface.show_dialog("时空相位是物理法则的基础，就像宇宙的坐标系。无论粒子如何运动，坐标轴必须保持稳定。", "莉琉")
	await novel_interface.show_dialog("如果坐标轴出现抖动，即使幅度再小，对空间内粒子的秩序也是毁灭性的。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("如果一幢大楼5%的粒子随机偏移1微米，就会彻底破坏材料结构而瞬间坍塌。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("而你现在还活蹦乱跳的，而且那片区域的建筑物也没出现结构性破坏。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（而且根据神迹研究的结果，拥有『GHOST』的人类是不可能进入那种空间的）", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("总之，你相当于走进了一个可以撕裂一切的十二级飓风眼，然后完好无缺的出来了还平息了风暴。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("……", player_name)
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("那异变是那些袭击我的东西造成的吗？\n好像是失去理智的……", player_name)
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("打住！我马上要去给元老院做简报——", "莉琉")
	await novel_interface.show_dialog("他们中有个神经病喜欢在会议过程中对视频实时分析测谎，所以现在我知道的越少越好。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("你对元老们的描述真是别致……", player_name)
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("而且女孩子要懂得什么时候才可以说谎哦~", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_dialog("我才不是女孩子！！", player_name)
	novel_interface.change_2nd_expression("shy")
	await novel_interface.show_dialog("总之我不说就是啦……", player_name)
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("近几来全世界只有4次这样时空波动的记录\n大多都与『异质物』的收容失效有关。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("特性不明的『神迹』被突然激发，很可能引发灾难性的后果。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire1")
	await novel_interface.show_dialog("……会有人受伤吗？", player_name)
	novel_interface.character_light(0.35,"serious")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("最严重的一次光死难者有几万人。", "莉琉")
	await novel_interface.show_dialog("不过几大学园都市都非常默契的将这些事件伪装成『常规事故』进行报道……", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("像是瓦斯泄露、飞机失事、恐怖袭击之类的……", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("那这次……", player_name)
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这次与以往不同，从没遇到过这么大规模的连续爆发……", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("超出了宣传剧本的最高预设等级，到时候连谎话都编不出来了。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire1")
	await novel_interface.show_dialog("这次会不会是因为我？\n如果我能帮上什么忙的话……", player_name)
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("别乱想了，虽然你身体的变化很可能与此有关，但光凭你还闹不出这么大动静。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("如果你想寻找线索，可以跟我的人去现场看看。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("（如果有那种可能，她现在是唯一的应对策略…\n…）", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("但是，绝不可以勉强自己，也不要跟任何人说你自己的事，明白了吗？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("不能跟别人说……也就是说……\n我要假装自己本来就是女生吗？", player_name)
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你也知道吧……\n新丰洲市一直都奉行科学至上的执政理念。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("如果你公开自己的经历，会被定为『实验对象』然后被带去研究机构哟~", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("到时应该会有一群发誓终身献身给科学的大叔排队等着研究你的身体吧……", "莉琉")
	await novel_interface.show_dialog("毕竟难得遇到这么可爱的女孩子——", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("……明、明白了！！", player_name)
	await novel_interface.show_dialog("我……我绝对不会乱说啦！！", player_name)

	print("=== 第二章第5话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
