# chapter2_ep06.gd - 第二章第6话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep06_script()

func play_script():
	pass

func chapter2_ep06_script():
	novel_interface.change_music("res://assets/audio/music/Sewer.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/spConferenceRoom.png")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("（自言自语）还是那个小家伙比较有趣……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉斜前方的荧幕闪过一串语音连线提示，故意伪装的电子音掩盖了说话人本身的性别特质。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("（虽然做过很多次简报，但这种单方加密干扰的形式，实在是不爽）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("那么有关『洛斯金杯』消失的事件，现在调查情况如何了？", "基尔斯")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("从今天凌晨零时十五分，安保系统发现『洛斯金\n杯』消失。", "莉琉")
	await novel_interface.show_dialog("早上六时四十分，『真实视域』卫星测控系统发出警告，检测到了强烈次元扭曲。", "莉琉")
	await novel_interface.show_dialog("之后从今早七点到现在——『埃癸斯』系统在新丰洲范围内共侦测到了六起时空相位波动警报。", "莉琉")
	await novel_interface.show_dialog("而如果以研究所为中心，半径一千五百公里以内范围内，同步出现了三十二起类似警报……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("这些都在文档里，说结论。", "基尔斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉朝着右后方看了一眼，笑了笑。")
	await novel_interface.show_text_only("仅凭语调就能听出，这是那位性格严谨不苟言笑的元老院首席执政。")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("——这不是失窃事件，而是『异质物』觉醒及其引发的连带效应。", "莉琉")
	await novel_interface.show_dialog("而且以现在的频率和规模看来，无法确定是不是模因类异质物。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉话音刚落，四周的黑暗荧幕中便传来吃惊和小声议论的声音。")
	await novel_interface.show_text_only("！！！！！")
	novel_interface.show_character("senate_giles")
	await novel_interface.show_dialog("什么？！", "基尔斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一道沉稳低哑的嗓音从莉琉的左手边传来。")
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("你是指精神影响型的『神迹』指数级爆发？\n这还真是有意思……", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("目前看来更可能是单纯的多起同时爆发。\n『神迹』……我不太习惯用不严谨的词汇。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("（虽然他是精神影响类『异质物』的权威……）", "莉琉")
	await novel_interface.show_dialog("（但总觉得这个大猩猩吃多了辐射脑子坏掉了）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("那按照你的判断……", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("现在可无法提出任何结论报告，有效信息太少了。", "莉琉")
	await novel_interface.show_dialog("根据目前的事态，我申请无限制的S级调查令，希望诸位可以理解。", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉并不理会四周传来的窃窃私语声，把注意力放回了手持终端上。")
	novel_interface.character_light(0.35,"normal1")
	await novel_interface.show_dialog("（那个小朋友去了新的异变区域……）", "莉琉")
	await novel_interface.show_dialog("（果然，又是消失之后一段时间重新出现，接着附近的相位波动也停止了）", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（现场传来的影像……她身上的是血迹吗？）", "莉琉")
	await novel_interface.show_dialog("（这个笨蛋……该不会是！！）", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("senate_giles","",0.25)
	await novel_interface.show_dialog("你看上去有些心不在焉啊。", "基尔斯")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("什么？……完全没有。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("你盯着看的东西，上面有什么比汇报内容更重要的信息吗？", "基尔斯")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……嘛，只是小猫咪的视频，你们想看吗？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("！！！", "基尔斯")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("莉琉的左侧传来了尖锐的电流音和蜂鸣。")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("别生气嘛，适当的调剂有利于提高工作效率。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("……", "基尔斯")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,false)
	await novel_interface.show_text_only("莉琉环视四周，似乎并没有人察觉到她刚才的动\n摇。")
	novel_interface.character_light()
	await novel_interface.show_dialog("总之，目前得到的基本情报如汇报所述。\n事件正在进一步调查中。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("没有问题的话，我要去现场了。", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("未等莉琉准备离开，左手边传来一道略显轻佻的声音。")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_#C")
	await novel_interface.show_dialog("……听说，你的手下带了两名高中生回SID进行审查？", "#C")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("……\n（又是这个讨厌的家伙）", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("senate_#C","",0.25)
	await novel_interface.show_dialog("是有什么特别之处吗？莉琉阁下……不，博士。", "#C")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……没什么，刚才已经查清，只是两只好奇心太过旺盛，翻进封锁区的小猫咪。", "莉琉")
	await novel_interface.show_dialog("之后我就会安排人送她们回家。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("是吗，那就好。", "#C")
	await novel_interface.show_dialog("在这种敏感的时期，万一被其他国家当做什么奇怪的存在就不好了……", "#C")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("这句话引起了众人喧哗。")
	await novel_interface.show_text_only("……这家伙什么意思？")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("说了不够严谨的话，有人会觉得不习惯吧。\n真是抱歉了，就当作是没有听过吧。", "#C")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("……\n（令人讨厌的家伙。）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("senate_bright")
	await novel_interface.show_dialog("好了，无论如何这次事件已经引起了其他学院都市的注意。", "布莱特")
	await novel_interface.show_dialog("接下来的机密调查和公共信息引导，也要拜托你\n了。", "布莱特")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("那是当然。", "莉琉")

	print("=== 第二章第6话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
