# chapter2_ep18.gd - 第二章第18话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep18_script()

func play_script():
	pass

func chapter2_ep18_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_centreSpace1.png")
	await novel_interface.show_text_only("被晒到喘不过气的夏日午后，我把一大摞文件摆到中庭的圆桌边，自己也瘫坐到树荫下的椅子上。")
	await novel_interface.show_text_only("看到一个漂亮的学姐很辛苦的抱着这摞东西，情不自禁的就冲上去包揽了……")
	await novel_interface.show_text_only("看着学姐一脸感激的消失在我的视野中，我才意识到自己是个笨蛋。")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("呼，总算可以休息了，热死了。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("唉……原来的身体拿这些根本是小菜一碟啊")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("而且接下来还有SID的训练……好想找个地方藏起来。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("小怜，那个……\n这里可是学校哦？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("是安妮啊~\n怎么了？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("虽然我能够理解你很热\n但直接撩起衣摆擦汗……好像不太好吧？", "安妮")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("就是……会走光啦。", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","wail",0.25)
	await novel_interface.show_dialog("糟糕！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_dialog("那个叫小怜的转学生也太粗鲁了……", "同学A")
	await novel_interface.show_dialog("是呀，我那天还看到她穿着裙子张开腿坐呢！", "同学B")
	await novel_interface.show_dialog("真的吗？这样子不好吧……", "同学A")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("……\n（因为我本来就不应该穿裙子啊！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("那个……")
	await novel_interface.show_text_only("一个温柔的声音传来。")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("你好，不介意的话，请用这张手帕吧。", "气质优雅的少女")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("出现在眼前的，是一名漂亮而优雅的女生。\n柔顺的紫色长发，紫丁香一般温柔的双眸。")
	await novel_interface.show_text_only("她向我递出了一张手帕，上面还带着优雅而清新的香味。")
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("哎？！\n谢、谢谢。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("你们就是一年级的转校生吧？\n我叫倪克斯·斯特罗齐，是你们的学姐。", "倪克斯")
	await novel_interface.show_dialog("看到你似乎很热的样子，而我刚好我随身带了手帕\n希望没有打扰到你们。", "倪克斯")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("倪克斯礼貌地点了点头，我不知所措地站起来，笨手笨脚的行了个礼。")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("不、不会的！\n完全没有，真是帮了大忙啦！", "小怜")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("（好温柔的学姐啊。）\n（她是外国人吧，睫毛好长…）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("看着倪克斯精致的面孔，感觉心跳有些力加快。")
	novel_interface.show_character("nyx_normal","normal1")
	await novel_interface.show_dialog("不用这么客气。\n那么……请问你的名字是……", "倪克斯")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","happy",0.25)
	await novel_interface.show_dialog("我叫小怜，她是安妮。\n我们都是最近才转学过来的。", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……安妮？", "倪克斯")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("倪克斯的表情变得有些古怪，凝视着安妮的脸。")
	await novel_interface.show_text_only("但她很快朝安妮友好地微笑了一下，仿佛刚才只是我的错觉。")
	novel_interface.show_character("nyx_normal","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","happy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("很高兴认识你们。", "倪克斯")
	await novel_interface.show_dialog("我还有事需要先走了，以后如果有什么需要，你们可以来找我。", "倪克斯")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("谢谢学姐！", "小怜")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("anne_uniform","upset",0.25)
	await novel_interface.show_dialog("……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮没有回应，有些犹豫。")
	novel_interface.show_character("ren_uniform","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","upset",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这位学姐……比其他的大小姐气质都要优雅啊。", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("安妮，你怎么了？\n从刚才起就一直不说话。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"unhappy")
	await novel_interface.show_dialog("刚才那个学姐说，她叫斯特罗齐？", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是啊，你认识她吗？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮勾住我的胳膊，露出了率性的笑容。")
	novel_interface.show_character("ren_uniform","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("哎？没有啦~\n我跟你都是刚转学来的，怎么会认识嘛。", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("说得也是呢。", "小怜")

	print("=== 第二章第18话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
