# chapter2_ep19.gd - 第二章第19话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep19_script()

func play_script():
	pass

func chapter2_ep19_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("ai","normal")
	await novel_interface.show_dialog("从训练的数据看，小怜的身体素质和普通的女高中生没什么区别。", "爱衣")
	await novel_interface.show_dialog("唯一亮眼的是眼手配合能力，估计与她游戏账号上那串白金奖杯有关……", "爱衣")
	await novel_interface.show_dialog("安妮单独训练的时候好一些，可以达到同年龄竞技选手的水准。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("但上次观测到她们俩再次一起消失在异变区域的时候就完全不同了。", "爱衣")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("哦？发现了什么有趣的？", "莉琉")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("虽然普通人不一定能感觉到……", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("但跟踪她们的无人机上『玻尔兹曼探针』的记录多次爆表，回收的时候已经坏掉了。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"serious")
	await novel_interface.show_dialog("不可能，如果探针无异常的话…那样的话在场的人\n……", "莉琉")
	await novel_interface.show_dialog("不，恐怕大半条街道都会气化了。", "莉琉")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("而且你把那么贵的玩意儿装在无人机上想做什么！", "莉琉")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("莉琉卷起报表，精准的敲到了爱衣的头上\n爱衣发出一声短促的呻吟。")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("嘛……所以说不是热量，信息熵的暴增也可以达到这种效果啦。", "爱衣")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("她们两个人，居然将概率不足万亿分之一的事件，以100%确定的形式表达了出来。", "爱衣")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("既然安妮是魔女，那小怜……算是『异质物』所造就的容器么？", "莉琉")
	await novel_interface.show_dialog("就像是小怜驱动了魔女和她们魔法一样……", "莉琉")
	novel_interface.character_light(0.35,"blush_think")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("就像是超级电池塞进了带震动电机的硅胶棒一样…\n…", "爱衣")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,false)
	await novel_interface.show_text_only("指挥室传出一声巨响，爱衣的头上长出一个包。")
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("真为纳税人感到悲哀，他们缴那么多税金，怎么会培养出你这种人呢？", "莉琉")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ai","blush_stare",0.25)
	await novel_interface.show_dialog("科学就是需要永远饥渴难耐的好奇心嘛~", "爱衣")
	novel_interface.character_2nd_light(0.35,"normal2")
	novel_interface.character_dark()
	await novel_interface.show_dialog("……亏你好意思说出来。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"stare")
	await novel_interface.show_dialog("你不是也经常给我的战研部指定奇奇怪怪的研发目标嘛……", "爱衣")
	novel_interface.change_expression("dizzy")
	await novel_interface.show_dialog("而且现在也一副在打主意的样子呢。\n说吧说吧，你想干什么？", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣发现了莉琉嘴角还没来得及收敛的微笑。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("既然已经接受了一段时间的训练，是时候该看看小朋友们的成果了。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("（异质物，洛斯金杯，魔女，时空相位波动，都被她串联起来……）", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（只有她在场的时候，安妮才能进出异变区域）\n（那安妮消失的这七年……）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("这个表情……想让无知少女直面危险吗？", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("现阶段还没有收集到足够的信息，对于不可言说的事只能保持沉默。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","normal",0.25)
	await novel_interface.show_dialog("哼~我还是比较喜欢维特根斯坦的另一句话。", "爱衣")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("真正神秘的，不是世界为何存在……", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("而是世界竟然存在。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("我当然会按照自己的原则做的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("我当然知道~", "爱衣")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	await novel_interface.show_text_only("我和安妮突然接到莉琉的命令，叫我们紧急返回公寓待命。")
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("是紧急任务吗？！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("这个嘛……\n（盯——）", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"shy_left")
	await novel_interface.show_dialog("莉、莉琉小姐？", "小怜")
	await novel_interface.show_dialog("（怎么觉得今天莉琉的眼神有点奇怪……）", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","speak2",0.25)
	await novel_interface.show_dialog("该说，一日不见，如隔三秋吗？\n你可是成长了不少啊——", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是啊……虽然生活上还是有一些地方不太习惯。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("哦？不习惯？", "莉琉")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("比如说，战服的设计……\n也太令人害羞了吧？！", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.show_2nd_character("anne_battle","smile",0.25)
	await novel_interface.show_dialog("明明很帅气！", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("上衣的尺寸已经不合适了？\n需要重新测量一下嘛。", "莉琉")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不、不是那个意思！", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_left(0,0.3,true)
	await novel_interface.show_text_only("莉琉向我伸出双手，我识破她的意图，连忙躲避。")
	novel_interface.character_light(0.35,"sob")
	await novel_interface.show_dialog("呃——没有没有！\n很合适非常合适！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("嘁。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"panic")
	await novel_interface.show_dialog("（你在可惜什么啊！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("果然，小怜还在长身体啊……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮露出羨慕又失落的表情。")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("安妮——！\n怎么连你也……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("我也想和小伶一起长大啊~！\n——可惜，我的时间是静止的。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("时间是静止的……和魔女有关吗？")
	await novel_interface.show_text_only("安妮开朗的表情里露出难以掩饰的哀伤，气氛一下子沉重了。")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("……安妮", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","happy")
	await novel_interface.show_dialog("所以，快让我感受一下——\n嘿咪！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮从背后一把抱住了没有提防的我。")
	novel_interface.show_character("anne_battle","smile")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("喂——！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("……女儿长大了，真是不中留。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉把头转向一边，偷偷擦拭眼泪。")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("真是的你们！什么跟什么啦！！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal1",0.25)
	await novel_interface.show_dialog("咳咳——说正事！\n现在确实有个紧急任务要你们执行。", "莉琉")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("你们知道江森变电所吗？", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是东部海边的那间超大型变电站？", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("（那边是六座学园都市在埃癸斯范围内划定出的共管区域，战后和谈就是在那里进行的。）")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("没错，刚才接到十几个中继站点的警告，东北部地区出现了强烈的电涌。", "莉琉")
	await novel_interface.show_dialog("卫星检测到了时空波动状况，锁定的位置就在江森变电所。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.character_move_right(0,0.3,true,"solemn")
	await novel_interface.show_dialog("时空波动？！难道……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("如果数据无误，那么很有可能和你们两个人之前出现的情况一样。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("按说你们还不到出外勤的资格……", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("但是那里地处『协约非武装区』，虽然在新丰洲范围内但SID也没有行动权限。", "莉琉")
	await novel_interface.show_dialog("算是为“世界和平”而做出的小小让步吧。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("所以，现在需要你们先行前往变电所侦查，SID的行动小组会在外围待命。", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("我会去联合议会，尽快申请正式许可。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","wry_smile",0.25)
	await novel_interface.show_dialog("我们要擅闯学园都市联盟的领地吗？\n会不会不太好啊。", "小怜")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哦？看来有人宁可让使馆区陷入大停电，也不想走一次捷径嘛。", "莉琉")
	await novel_interface.show_dialog("要是出了什么乱子，那群本来就互相看不顺眼的笨蛋说不定又会打起来啦。", "莉琉")
	await novel_interface.show_dialog("要是因为这件事开战的话……", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("好啦我知道……", "小怜")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("而且你们两个女高中生，万一被保安军抓到，说不定卖个萌就混过去了。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("能混过去才有鬼了啦！！", "小怜")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("总之，这是我的命令\n直升机就在楼顶，准备好就出发吧~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"sprite")
	await novel_interface.show_dialog("真是独裁……", "小怜")

	print("=== 第二章第19话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
