# chapter2_ep23.gd - 第二章第23话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep23_script()

func play_script():
	pass

func chapter2_ep23_script():
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_City_powerSubstation.png")
	await novel_interface.show_text_only("伊露卡使用电系魔法向我和安妮发起了攻击，不想伤害到她的我们只能勉强防御着。")
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("再这样下去，只会两败俱伤的……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("哈啊……哈……\n伊露卡，快冷静下来！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("目标锁定，继续攻击——", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("天空突然划过一条刺眼的亮线，伴随着一声巨响。当我睁开眼，却发现自己并没有受伤。")
	await novel_interface.show_text_only("管理员身后运输机的主旋翼缓慢的向一侧倾倒\n之后像折断的树枝一样掉了下去。")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("！？", "管理员")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("咳咳……都给我住手——！", "莉琉")
	novel_interface.change_music("res://assets/audio/music/Black Market.mp3")
	await novel_interface.show_text_only("远处的扩音喇叭传来莉琉的喝止声。")
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("莉琉小姐！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("天空中出现三架直升机，随之打出几道刺眼的探照灯光将地面照的宛若白昼。")
	await novel_interface.show_text_only("莉琉正坐在正中间的直升机上拿着喇叭喊话，她面前架着的巨大的枪械还在冒烟。")
	await novel_interface.show_dialog("爱衣的这玩意真给力啊，还真的一枪就能干掉螺旋桨的主轴。", "莉琉")
	await novel_interface.show_text_only("莉琉的语气有点兴奋，恨不得再开一枪……喂喂，那个东西已经算炮了吧！！")
	await novel_interface.show_text_only("坠毁的运输机驾驶仓从内侧打开，两个驾驶员屁滚尿流的逃了出去。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("哈……哈哈。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("直升机降落在变电所外的空地上，莉琉威风凛凛向我们走来，后面还跟着一大票全副武装的士兵。")
	await novel_interface.show_text_only("终于看清莉琉的脸，被称作管理员的男人低声啐了一口。")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("哼，SID的狗。", "管理员")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("这可不是SID的行动，我只是作为新丰洲都市防卫厅的顾问来执行防暴安保任务。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我才看清从直升机上下来的并不是SID探员，而臂章上都印着“MD”的标志。")
	novel_interface.show_character("liliu_uniform1","jest")
	await novel_interface.show_dialog("是不是呀……南哲队长？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("nantetsu","speak")
	await novel_interface.show_dialog("没错，现在都市防卫厅怀疑这里在进行一起针对新丰洲的恐怖活动。", "南哲")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("我现在命令你和你的手下立刻停止攻击，并配合我们回去接受调查。", "南哲")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("那个摔跤手一样的肌肉男我好像见过……是莉琉的熟人吗？", "小怜")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这两位可爱的小姑娘是你的手下？没有年龄限制的部门真不错……", "南哲")
	await novel_interface.show_dialog("嗯…这个小姑娘……", "南哲")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("哈，你们这样乱来真的好吗？", "管理员")
	await novel_interface.show_dialog("这里是协约非武装区，你们两个所属的机构都无权在这里行动。", "管理员")
	await novel_interface.show_dialog("而且也绝不可能在这个时间拿到联合议会的许可！", "管理员")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","sigh")
	await novel_interface.show_dialog("那种多国联合治理的官僚机构做事像蜗牛一样慢。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("哼……很抱歉让你失望，不过我要带着我的人离开\n了。", "管理员")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal2")
	await novel_interface.show_dialog("嗯~我话还没说完……不过江森重工的效率就高多了。", "莉琉")
	await novel_interface.show_dialog("毕竟他们的大公子还在新丰洲读书~现在可是他们有求于我啊……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("什么？！", "管理员")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("这座变电所现在有3%的负载已经并入了新丰洲的城市电网——", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("根据《萨蒙顿协定》，任何针对第五学园都市电网的袭击，都视为一级恐怖活动。", "莉琉")
	await novel_interface.show_dialog("都市防卫厅对此类活动，拥有所有联合议会所承认的最高行动权。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("毕竟我们『埃癸斯』的主机……\n是靠电力驱动的呢~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("你们怎么可能靠城市电网驱动埃癸斯！尽是耍些花招！！", "管理员")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nantetsu","speak",0.25)
	await novel_interface.show_dialog("少废话，都给我带走！", "南哲")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("…等等！马萨达堡与新丰洲早就签署过外交豁免协议吧？", "管理员")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("管理员从大衣口袋中拿出了自己的证件，得意洋洋的展示给莉琉和南哲。")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("我是第三学园都市——马萨达堡派驻联合议会的武官雅各·施密特。", "管理员")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform1","serious",0.25)
	await novel_interface.show_dialog("……", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("如果各位在这逮捕我，想必会引起一些不必要的外交纷争吧？", "雅各")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"angry")
	await novel_interface.show_dialog("…………\n——那么，限你一分钟之内从我面前消失。", "莉琉")
	novel_interface.change_2nd_expression("serious")
	await novel_interface.show_dialog("不过你的交通工具看来出了点小故障……\n只能麻烦你自己走回去了。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_battle","shout")
	await novel_interface.show_dialog("什么？！怎么能就这样！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform1","normal1",0.25)
	await novel_interface.show_dialog("规矩就是规矩，靠热血是解决不了问题的。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"serious")
	await novel_interface.show_dialog("可是……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("伊露卡，我们走。", "雅各")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform1","speak",0.25)
	await novel_interface.show_dialog("等一下，我只看到你的证件，你们的外交部不会给小孩也指派了职位吧？", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……你！！", "雅各")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("对不起咯，那个家伙是恐怖袭击的重要嫌疑犯。", "莉琉")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("想强行带走的话，我只能遗憾的通知你们的大使说你不幸在恐怖袭击中被人爆头了——", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉掏出手枪，顶在自称雅各的男人的脑门上。")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("哼……不过是一件工具罢了。\n那么想要你们就自己留着吧！", "雅各")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("能量，极低……\n哈啊，活动终止……", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("从刚才起就一直勉力支撑的伊露卡，突然像断电一样倒在了地上。")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("啧，反正这种程度的损坏估计也没用了。没用的垃圾，就交给你们处理吧！", "雅各")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("雅各竖起风衣的领子快步离开，头也不回的消失在了夜幕中。")
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("伊露卡，快醒醒！", "小怜")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("莉琉，求你快救救伊露卡！……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform1","normal1")
	await novel_interface.show_dialog("她在生命探测器上还有反应，应该只是累坏了。", "莉琉")
	novel_interface.change_expression("sigh")
	await novel_interface.show_dialog("倒是你，一个自己都需要被保护的小鬼，居然也敢喊着要救别人。", "莉琉")
	await novel_interface.show_dialog("——越来越像个热血笨蛋了。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("回家吧。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("nantetsu","serious",0.25)
	await novel_interface.show_dialog("那个小姑娘是敌方作战人员吧？", "南哲")
	await novel_interface.show_dialog("对于一级恐怖活动人员元老院不都是要求立刻监禁然后由……", "南哲")
	novel_interface.character_light(0.35,"speak")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("叫所有直升机不间断开启反扫描模块，我会让SID的四架UAV用自动反击模式护航。", "莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("我的人——我亲自护送。不怕死的家伙就来试试\n看！", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("哈哈哈……还真是你的风格。", "南哲")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/liliu_helicopterBackto.png")
	await novel_interface.show_text_only("莉琉叫医疗组给我们的伤口做了应急处理，然后带着我、安妮和伊露卡乘上了直升机。")
	await novel_interface.show_text_only("安妮累得靠在我肩膀上，不一会就进入了梦乡。")
	await novel_interface.show_text_only("伊露卡也躺在我的腿上呼呼的睡着，嘴角还流着口水，全然没有刚才那副冰冷的神情。")
	await novel_interface.show_text_only("只是个普通的小女孩嘛……我忽然觉得很安心。")
	await novel_interface.show_text_only("没事的，一切都会好的吧，就像那首歌唱的——\nEvery thing is gona be OK.")
	await novel_interface.show_text_only("虽然现在六个学园都市之间达成了和平，但六大市控制之外的大片地区依然战火纷飞。")
	await novel_interface.show_text_only("不知还有多少像伊露卡这样的小孩被作为武器或者工具呢……")
	await novel_interface.show_text_only("我知道莉琉说的对，我是个自不量力的笨蛋。")
	await novel_interface.show_text_only("但我从小都没遇到过多少能放下所有戒备，在自己身边安然入睡的人。")
	await novel_interface.show_text_only("……就让我做个笨蛋吧。")

	print("=== 第二章第23话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
