# chapter2_ep12.gd - 第二章第12话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep12_script()

func play_script():
	pass

func chapter2_ep12_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	await novel_interface.show_text_only("在完成了一系列SID学员训练的登记手续之后，我拿到了一大摞厚厚的“教材”。")
	await novel_interface.show_text_only("之后在工作人员的指引下，我从SID总部乘上了一部不起眼的小型电梯。")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	await novel_interface.show_text_only("电梯上升速度很快，能明显感觉到耳压升高\n到地面之后，才发现时间已经是傍晚了……")
	await novel_interface.show_text_only("电梯的出口在一栋小型写字楼的大厅，出来就是车水马龙的商业区。")
	await novel_interface.show_text_only("据说这部电梯在识别乘客全部为授权人员时才能向深层下降，否则只会在写字楼的1至3层之间往返") #换行问题
	await novel_interface.show_text_only("写字楼的二层是一家24小时营业的咖啡厅，全天都有人出入，很适合掩人耳目。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("唉……", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("还以为特工训练会教格斗和射击什么的，结果怎么好像报了全套的补习班一样……", "小怜")
	await novel_interface.show_dialog("这些书还真重啊！\n好在莉琉安排的住处离这不远。", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("学区东道6号，她说是个很低调的——", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("ren_battle","wail") 
	await novel_interface.show_dialog("——哪低调了啊！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我站在大厦顶层的豪宅中，豪华的客厅连接着巨大的露台，可以俯瞰商业区的夜景。")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("墙边的这排火苗，是货真价实的壁炉吗？\n太夸张了吧……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("正当我小心翼翼的观察打探着自己是不是走错房间的时候，收到了莉琉发来的一条讯息。")
	await novel_interface.show_text_only("莉琉：卧室随便挑一间\n元老院的经费不用客气~") #原文有个♥
	await novel_interface.show_text_only("这个家伙……快向新丰洲的纳税人道歉！！")
	await novel_interface.show_dialog("小怜，你回来啦！", "安妮")
	await novel_interface.show_text_only("安妮一边挽着头发，一边从浴室中走出来。")
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("安妮？！你也在啊~\n刚才莉琉说你去接受特别训练了……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	await novel_interface.show_dialog("训练项目提前完成了，我刚洗完澡在试校服\n看来我们要做室友啦~", "安妮")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是，是呢\n（似乎莉琉提到过……）", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,false,"shy_left")
	await novel_interface.show_dialog("（这是上天对我的考验吗？）\n（和女孩子住在同一屋檐下什么的……）", "小怜")
	novel_interface.change_expression("timid")
	await novel_interface.show_dialog("这是那个学校的校服吗？很可爱呢~", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("嗯嗯~他们为你准备的衣物在那边的箱子里，一会也试试看吧！", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("我、我也要穿吗……", "小怜")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嘿嘿，小怜果然还是不习惯女生的身份吗？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("听到这个话题，我忍不住挠着头发，瘫在沙发上。")
	novel_interface.show_character("anne_uniform","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_battle","shy",0.25)
	await novel_interface.show_dialog("这种事情，不可能习惯的吧……", "小怜")
	novel_interface.change_2nd_expression("sob")
	await novel_interface.show_dialog("呜呜……没人能理解这感觉吧", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("我能明白的哦。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮突然坐在了我的身旁，用手指安慰似的、轻轻碰触了一下我的脸颊。")
	novel_interface.show_character("ren_battle","timid")
	await novel_interface.show_dialog("……安妮？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","relieve")
	await novel_interface.show_dialog("因为我们是一样的嘛。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她的笑容似乎有些苦涩。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("什、什么——！\n原来你也是男生吗？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","smile",0.25)
	await novel_interface.show_dialog("哈哈哈哈哈哈！小怜你是笨蛋吗？", "安妮")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("安妮一直都是女孩子哦~", "安妮")
	novel_interface.character_light(0.35,"shy_left")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊呜……\n（丢爆人了！！）", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("在我的害羞指数要达到顶峰的时候，安妮收起笑容温柔地看着我。")
	novel_interface.show_character("ren_battle","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","normal2",0.25)
	await novel_interface.show_dialog("不过啊，你现在心里的恐慌，我完全可以理解。", "安妮")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_left(0,0.3,false)
	await novel_interface.show_dialog("我之前也被困在了另一个时空……\n那种感觉，应该和现在的你有些相似吧。", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("另一个……时空？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮顿了顿，似乎在思索措辞。")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("莉琉小姐没有告诉你吗？\n我在另一个时空里懵懵懂懂地度过了很久……", "安妮")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("在那里时间的概念很模糊，虽然并没有那么久的感觉，但回来才发现已经过了七年。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("嗯，听说了一点点……", "小怜")
	await novel_interface.show_dialog("（虽然是从莉琉那里听到只言片语……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("到底发生了什么呢？\n要主动问一下她吗？")
	await novel_interface.show_text_only("安妮并没有继续说，只是低下头，若有所思的把玩着手指。")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("小怜……你是不是也有这种感觉——", "安妮")
	await novel_interface.show_dialog("总怀疑这是一个梦，希望下一次睁开眼就能醒过\n来。", "安妮")
	await novel_interface.show_dialog("本不该是这样，本不该在这里……\n但是，不管怎么做，都回不到正常的轨道。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("（安妮就是抱着这样的心情，一个人撑过来的\n吗？）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我向安妮微微靠近了一些，拍了拍她的肩膀。\n呃，安慰女孩子……应该可以这样的吧？")
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("别害怕，你不是已经回来了嘛~", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","worry",0.25)
	await novel_interface.show_dialog("嗯……\n可我还是感觉十分陌生……", "安妮")
	await novel_interface.show_dialog("就连你们说的『学园都市』，我都完全没有头绪。", "安妮")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（……对啊，安妮消失的时候战争还没结束呢。）", "小怜")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("所以说，这些年发生了什么你还都不知道吧？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"unhappy")
	await novel_interface.show_dialog("我只是粗略的查了下……这几年发生太多事，就连很多新闻里的名词都不知道什么意思了。", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("七年前……\n正好是那场让全世界陷入混乱的战争中期啊。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("哎？战争？\n是指马萨达堡向欧洲发动的那场军事行动吗？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮努力的回想着。")
	novel_interface.show_character("ren_battle","worry")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","worry",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不是啦，那之后没多久，几乎所有国家都被卷入进去了。", "小怜")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("当时我还在寄宿学校上小学，每天都有战争和死亡人数的新闻，是一段相当糟糕的时期呢……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"upset")
	await novel_interface.show_dialog("小怜也经历了战争吗？", "安妮")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不算是啦，多亏了埃癸斯的保护，当时的新丰洲正在废墟旁全力重建。", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我看了看窗外繁华的都市夜景……记得小时候，城市里四处都是巨大的塔吊和忙碌的工程机械。")
	novel_interface.show_character("ren_battle","gratified")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","upset",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所以我知道的那些，大多都是从课本上学的啦。", "小怜")
	await novel_interface.show_dialog("由于战争的影响，神迹科技迅猛发展……\n『神迹』就是指异质物引发的现象哦。", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("战后掌握了关键技术的六个国家，分别在世界各地建立了六大学园都市。", "小怜")
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("（感觉自己突然点亮了历史老师的天赋……）", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"unhappy")
	await novel_interface.show_dialog("原来发生了这么多事……完全无法想像。", "安妮")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("毕竟安妮离开——啊，消失的时候，世界还算比较和平吧……", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("是啊，那时候我还能参加国际棒球赛呢！", "安妮")
	novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("安妮提到棒球，双眸闪闪发光。")
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("你知道吗小怜，每次轮到我击球的时候，观众们的目光就会集中在我一个人身上！", "安妮")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("那种紧张又必须拼尽全力的感觉，会让我全身的血液都沸腾起来！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("提起棒球，我忽然想到莱博娜棒球场外那座刻着几万名死难者名字的黑色石碑。")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("其实……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","normal2")
	await novel_interface.show_dialog("嗯？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("你避开了战争最惨烈的几年，没准也是件好事呢。", "小怜")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("这么一想，我会变成女孩子还遇到了你\n在某种意义上来说，可能也是件好事？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮愣住了，似乎有些难堪……\n是我看错了吗？")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("小怜……其实我一直想向你道谢。\n因为……是你将在那个世界彷徨的我救了出来。", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("诶？但是我什么都没做啊……", "小怜")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所以说，你一定是特别的嘛~", "安妮")
	await novel_interface.show_dialog("虽然我也不知道你是怎么做到的，但在那时，我能感觉到你温暖的手拉住了我。", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮轻轻握住了我的手，陷入了回忆。")
	novel_interface.show_character("anne_uniform","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("如果不是你，不知道我还要困在那边多久，最后会变成什么……", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("变成……什么？", "小怜")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊哈~没什么啦，已经过去了。\n好像突然之间有点困了呢~", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮似乎想避开这个话题\n伸了个懒腰，脸上依然保持着笑容")
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	await novel_interface.show_dialog("你们的少女夜谈打算什么时候结束啊？", "莉琉")
	await novel_interface.show_text_only("房间角落的音箱突然传来了莉琉的声音。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("莉、莉琉小姐？！\n你刚才在偷听吗？", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_dialog("怎么，监护人监督一下小朋友的作息\n有什么不对的吗？", "莉琉")
	novel_interface.character_light(0.35,"wry_smile")
	await novel_interface.show_dialog("真亏你说得出口……", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_dialog("还顶嘴？\n看来明天要好好的操练一下你……", "莉琉")
	novel_interface.character_light(0.35,"wail")
	await novel_interface.show_dialog("对不起！我马上就洗澡睡觉！\n晚安！！", "小怜")

	print("=== 第二章第12话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
