# chapter2_ep02.gd - 第二章第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep02_script()

func play_script():
	pass

func chapter2_ep02_script():
	var player_name = GameConfig.player_name
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/spSoundChannel.png")
	await novel_interface.show_dialog("各小组注意，相位波动正在衰减！", "探员A")
	await novel_interface.show_dialog("敌人随时可能出现！\n坚守位置准备迎击！！", "探员A")
	await novel_interface.show_dialog("……报、报告！", "探员B")
	await novel_interface.show_dialog("目视区域内发现两个人形单位，突然出现在异变核心区……", "探员B")
	await novel_interface.show_dialog("人类……？\n怎么可能！模因检测的结果是？？", "探员A")
	await novel_interface.show_dialog("色相是……\n绿色！！", "探员B")
	await novel_interface.show_dialog("似乎是两个小姑娘……\n不要开火！不要开火！", "探员B")
	await novel_interface.show_dialog("……", "探员A")
	await novel_interface.show_dialog("刚刚接到命令，优先将她们控制并带回总部。\n派一个高级探员去交涉——", "探员A")
	await novel_interface.show_dialog("其他人注意警戒，交涉期间目标如果有异动立刻处决！！", "探员A")
	await novel_interface.show_dialog("明白！", "探员B")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_RC_outside.png")
	await novel_interface.stop_music()
	await novel_interface.show_text_only("我们小心地向研究中心出口处前进。")
	await novel_interface.show_text_only("迎接我们的，除了熟悉的街道，还有一排封锁带和后面拿着武器严阵以待的人。")
	novel_interface.change_music("res://assets/audio/music/Story_01.mp3")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("怎、怎么突然冒出这么多人？！", player_name)
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("啊——安妮！\n快把我的衣服换回去！！", player_name)
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("这么羞耻的衣服……\n实在不想被人看到啊……", player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog("这种时候还在在意这个吗？", "安妮")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("你的衣服都好好的保存在我这，不用担心……", "安妮")
	await novel_interface.show_dialog("一定要换的话，你把现在的『战服』脱掉，再穿上原来那些松松垮垮的衣服就是了~", "安妮")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("不过前面有很多男人欸……\n真的要当着他们的面换衣服吗？", "安妮")
	novel_interface.character_light(0.35,"shy_right")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("呜呜呜~~\n明明我也是男……", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("说来……你刚才穿的都是男装啊！\n难道——", "安妮")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("欸？你以前也遇到过这样的状况？？", player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("（也是呢……安妮应该不是一般人吧？）", player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("（如果是安妮的话，或许能理解我的处境……）", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("嗯嗯，我理解的……", "安妮")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("你是偷拿了自己喜欢的男生的衣服自己穿对吧？", "安妮")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("理解个头啊！！！", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("嗯嗯~其实"+player_name+"是那种会迷恋异性味道的体质吧？不用难为情的啦……", "安妮") #文本变化important
	novel_interface.character_light(0.35,"sob")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不要做出一幅“虽然你是变态但我会包容你”的表情啊！！！", player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("唉……我为什么会变成这样还是完全没有头绪……", player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("……")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("站住！\n把手举起来！", "SID探员")
	await novel_interface.character_dark()
	await novel_interface.show_text_only("一个穿黑色西服的人走上前来对我们喊话")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("唉……？\n把我们当成坏人了吗？", player_name)
	novel_interface.change_2nd_expression("panic")
	await novel_interface.show_dialog("（等等，那么领头人胸口的标示）\n（正圆形、环套式的盾牌——该不会是……）", player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("两位，我是SID的探员。\n为了避免你们受伤，请保持姿势不要乱动。", "SID探员")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_text_only("果然是SID的家伙！\n这下惨了！！！")
	await novel_interface.show_text_only("我脑海中瞬间闪过那些SID出动大批特工抓捕间谍的新闻。")
	novel_interface.change_expression("sob")
	await novel_interface.show_text_only("还有“秘密监狱”啦，“暗杀行动”啦之类的都市传说……")
	await novel_interface.hide_character()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("核心封锁区报告，两名目标未发现攻击意图。\n暂定威胁等级D+。", "SID探员")
	await novel_interface.show_dialog("先做个简单的问话吧……\n——你们是什么人？在这里鬼鬼祟祟地做什么？", "SID探员")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("我是本市的学生……", player_name)
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("我们只、只是来做校外教学参观了一下研究所……", player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("穿黑色西装的特工表情露出了不屑的表情。")
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("是吗——参观？研究所？", "SID探员")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_text_only("糟糕……\n我忽然想起来——")
	await novel_interface.show_text_only("因为『洛斯金杯』消失的事情，研究所昨晚就被紧急戒严了。")
	novel_interface.change_expression("sob")
	await novel_interface.show_text_only("这种时候我们大摇大摆的从里面走出来，还声称自己只是参观了一下……简直就像自己招供的熊吉。")
	await novel_interface.show_text_only("果然，她似乎从耳机里接到了什么指令，严肃的看着我。")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("agent","",0.25)
	await novel_interface.show_dialog("我收到长官命令，请二位跟我们走一趟。", "SID探员")
	novel_interface.character_move_right(0,0.3,false)
	novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("短短几秒之间，我们两个就被完全包围住。")
	await novel_interface.show_text_only("视线所及，对着我们的全是黑压压的枪口。")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog(player_name+"，这些家伙看起来很不妙呢…\n不如我们看准时机逃掉吧。", "安妮")
	novel_interface.character_move_left(-0.3,0.3,false)
	novel_interface.character_2nd_move_left(0)
	novel_interface.show_3rd_character("agent","",0.3)
	await novel_interface.show_dialog("请放心，我们不会伤害你们的。\n只要你们好好配合调查，事情就能和平解决。", "SID探员")
	await novel_interface.show_dialog("两位应该知道，涉及『异质物』失踪的事情非同小可，可能引发各种超出常识的事件，请务必理解。", "SID探员")
	await novel_interface.hide_3rd_character()
	novel_interface.character_move_right(-0.25,0.3,true,"worry")
	novel_interface.character_2nd_move_right(0.25,0.3,false)
	await novel_interface.show_dialog("（超出常识的事件……吗？）", player_name)
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("好，明白了，我跟你们走。", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("哎？？怎么就跟着走了啊！\n喂！"+player_name+"！", "安妮")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("别、别拽了！笨蛋裙子要拽掉了！", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire")
	await novel_interface.show_dialog("你才是笨蛋啊！为什么要跟这么可疑的家伙走，如果被灌药卖掉了怎么办？！", "安妮")
	novel_interface.character_light(0.35,"shy_right")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我一个大男人有什么好……", player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("不对、谁会找来这么多人大张旗鼓的拐卖人口啊！", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"frustrate")
	await novel_interface.show_dialog(player_name+"一定没见过莱博娜群岛的黑帮吧……", "安妮")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("总之……说不定能搞清楚一些事呢\n还是乖乖跟她走吧……", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("好吧，你去哪我都会跟着你啦……", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那个，方便的话能不能先给我一件外套。", player_name) 
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("这件衣服实在有点……", player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("穿着女装被众人围观，实在是浑身不舒服。")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("agent")
	await novel_interface.show_dialog("好吧，我申请一下。", "SID探员")
	await novel_interface.show_dialog("……", "SID探员")
	await novel_interface.show_dialog("……抱歉，长官说“这身衣服很可爱”\n断然否决了申请。", "SID探员")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("到底是什么样的长官啊！！", player_name)

	print("=== 第二章第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
