# chapter2_ep13.gd - 第二章第13话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep13_script()

func play_script():
	pass

func chapter2_ep13_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("在进入新的学校之前，你的第一个任务就是进行基础知识培训。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","worry",0.25)
	await novel_interface.show_dialog("基础知识？\n我又不像安妮错过了这几年的事……", "小怜")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哼哼，你可是错过了整整十几年做女生的知识啊~", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("那种知识才不需要啦！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉完全没理会我的抗议，神采奕奕的走向桌边。我才发现她早已经准备了满满一桌子的各式道具。")
	novel_interface.show_character("liliu_research","speak")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","wry_smile",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("首先，你要能分辨口红的12种典型色号，并记住前20名的品牌。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("这么多种啊……\n颜色不是差不多吗？", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("太天真了！这只是总量的不到十分之一。", "莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("然后这里给你准备了全套的化妆道具——里面有粉底、眼影、唇彩、高光、修容……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("欸？要往脸上涂这么多东西吗？！\n又不是在画画……做女生到底有多复杂……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","speak",0.25)
	await novel_interface.show_dialog("不用担心，从今天开始会有专人教你化妆。", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("高中生不是不允许化妆……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("你啊，太不了解女高中生的世界了……\n这种大大咧咧的样子用不了两天就会引起怀疑的。", "莉琉")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("而且除了上学，作为SID的探员还需要执行各种任务，化妆是女性特工的必备技能之一。", "莉琉")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("尤其是你这样的小脸蛋——", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉伸出食指，挑起我的下巴。")
	await novel_interface.show_text_only("我后退一步躲开了她的手，总觉得自己的男性尊严无法接受。")
	novel_interface.show_character("ren_battle","shy_left")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("虽然之前确实是自告奋勇\n但我可没想到要学这些东西啊……", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("SID的学员考核可是非常严格的，每次都会筛选掉一大批人。", "莉琉")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("你既然说了那样的大话，就证明一下自己吧。", "莉琉")
	await novel_interface.show_dialog("而且如果通过最终考核就可以被纳入正式编制，还会有不菲的薪水哦~", "莉琉")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ren_battle","smile",0.25)
	await novel_interface.show_dialog("欸？还能有钱拿啊！？\n（那，那我的Gfat购物车……）", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("好，男性尊严先放到一边。")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"speak")
	await novel_interface.show_dialog("（呵呵呵，真是单纯的小鬼）", "莉琉")
	novel_interface.change_2nd_expression("angry")
	await novel_interface.show_dialog("但是相应的，你也要明白——作为你的长官，我的命令是绝对的，必须无条件服从！", "莉琉")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ren_battle","worry",0.25)
	await novel_interface.show_dialog("到底要怎样……", "小怜")
	novel_interface.character_2nd_light(0.35,"speak")
	novel_interface.character_dark()
	await novel_interface.show_dialog("先给你介绍一个人——自告奋勇教你化妆的老师。", "莉琉")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("虽然平时负责的是试验性药品和特种装备研发……", "莉琉")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("哦……小怜是吧？\n嘿嘿~这份档案真是有趣~", "戴眼镜的女生")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("你好~我是SID战研部的主任，既然咱们的档案都被修改过，你叫我爱衣就可以了。", "戴眼镜的女生")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("你好……\n（她的档案……也被修改过？）", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_wink",0.25)
	await novel_interface.show_dialog("莉琉啊，小怜这么好的研究素材，真的不能……\n借给我用用吗~！？", "爱衣")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（？？？研究素材？用用……？）", "小怜")
	await novel_interface.show_dialog("（为、为什么后背有点发凉……）", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("我怎么也算监护人，你不可以对她出手哦~", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","stare",0.25)
	await novel_interface.show_dialog("哼，好吧……", "爱衣")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_left(0,0.3,false,"normal")
	await novel_interface.show_dialog("虽然我也难得化妆，不过那些东西很简单，我看了10分钟就全记下来了。", "爱衣")
	await novel_interface.show_dialog("你应该也能很快学会的。", "爱衣")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("这么快？\n好像程序很复杂来的……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","smile",0.25)
	await novel_interface.show_dialog("爱衣记什么都很快，以后多跟她学学吧~", "莉琉")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是……\n（记忆力这种东西要怎么学嘛！）", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("啊呜~~\n跟爱衣记了一天化妆品的牌子和颜色头大死了。", "小怜")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("……莉琉！你怎么在这？！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","speak",0.25)
	await novel_interface.show_dialog("怎么？这公寓本来就是我在新丰洲的住所之一。\n不仅如此，这整栋大楼都是SID的资产~", "莉琉")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我说怎么这么夸张！\n等等，难道你要跟我和安妮住在一起……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("只是偶尔回来，并不会经常住在这~\n这里的冰箱都没有啤酒了，下次记得帮我买两箱。", "莉琉")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("不过今天是特意过来作为监护人……哼哼~", "莉琉") #♪少一个音乐符号
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不、不祥的感觉！！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("来试试，这是小怜的校服、这是连衣裙~", "莉琉")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("为什么……这个裙子这么短……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("裙子的长度果然还是这样好啊。", "莉琉")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这个裙子果然被改过长度了吧！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("不要在意那种细节~", "莉琉")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("这边还有短筒袜、中筒袜、长筒袜、连裤袜……\n哦哦，还有这条吊带袜！", "莉琉")
	novel_interface.character_light(0.35,"sob")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("袜子怎么也有这么多种类……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("还有不同类型的条纹、拼接、图案、波点……\n对了，要不要试试网袜？", "莉琉")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("才不要呢！！！", "小怜")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("不对！重点是！\n这种东西我才不要穿啦！！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("任务需要的时候也由不得你，不如趁早……\n要不要我来帮你？", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("你……你……！！", "小怜")

	print("=== 第二章第13话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
