# chapter2_ep09.gd - 第二章第9话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep09_script()

func play_script():
	pass

func chapter2_ep09_script():
	var player_name = GameConfig.player_name
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("所以说……为了保证安全，我会抹除你过去的一切档案和痕迹，重写你的身份记录。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("竟然能做到这种地步吗？\n果然是传说中的SID……", player_name)
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那当然，而且新丰洲市所有公民的身份信息，都是『异质物』的一部分。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wry_smile")
	await novel_interface.show_dialog("哈？开什么玩笑……", player_name)
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("学校的老师没教过你吗？新丰洲的城市管理系统全部建立在『埃癸斯』系统上。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("对哦，『埃癸斯』系统是模因类『异质物』……", player_name)
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("因为太贴近日常生活，大家早就习以为常了\n这个超越人类认知的存在。")
	novel_interface.show_character("liliu_uniform2","normal2")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","worry",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("『埃癸斯』是一个软件系统，运行后可以展开半径为35公里的防护力场。", "莉琉")
	await novel_interface.show_dialog("力场的外壳可以自动识别并防御任何形式的攻击，甚至能压制很多神迹武器的效果。", "莉琉")
	await novel_interface.show_dialog("这种识别攻击的原理未知，但非常智能，不会阻挡任何非攻击性物质和信息的流动。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("它绝对是新丰洲从战争中快速恢复并得以保持中立的根基。", "莉琉")
	await novel_interface.show_dialog("而且埃癸斯的主机对网络攻击也可以识别并防御。", "莉琉")
	await novel_interface.show_dialog("因为几乎完美的安全性，元老院决定把市政管理系统整体迁移到埃癸斯的主机上。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("确实只要把ID卡和手机绑定，埃癸斯就能关联所有的身份户籍和账号信息，连CAPH的学分都查得到") #换行问题important
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("这些学校确实有学过啦……\n不过考完试就忘的差不多了。", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("但接下来我要说的——是机密事项。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉严肃的盯着我，像是下定了决心。")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("『埃癸斯』系统还有一个从未公开的能力。", "莉琉")
	await novel_interface.show_dialog("任何人一旦进入防护力场的范围，就会立刻被系统识别。", "莉琉")
	await novel_interface.show_dialog("可以说这种识别，是基于灵魂的。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("基于……灵魂？", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("埃癸斯系统会给范围内的每个人一个电子编号，之后这个人无论是乔装、整容、失忆或者被洗脑……", "莉琉")
	await novel_interface.show_dialog("都会被识别为最初的电子编号。", "莉琉")
	await novel_interface.show_dialog("每个编号只有两个标记状态：在防护范围内，或者不在。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("如果有编号不在范围内，要么是离境了，要么就是去世了。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("听到这里，我觉得头皮一阵发麻。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("毎个人……都是一个编号？", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("对，除此以外没有任何其他信息，没有名字、没有照片、没有位置信息。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("为每个编号建档、对应到现实中的人，更新信息并追踪关键目标，这些都是SID的工作了。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("这是一个让其它学园都市都羨慕不已的安保系统。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("它……每时每刻都在监控着它保护的每一个人，每一个编号……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉流露出复杂的表情，虽然只是一瞬，我确清楚地看到了。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("怪不得你能对其他国家的情报人员进入新丰洲了如指掌。", player_name)
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("等等！那我的……", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("我让手下排查了今天全部的新增编号——", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("虽然我也是第一次遇到这种情况……至少在埃癸斯系统看来，你就是●●●●", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我一阵激动，几乎泛出泪花。\n终于……终于可以证明我是男生了！")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("所以，你不可以再做男生了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("啊？", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("既然你已经知道这些机密信息……", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉突然走近我，我下意识的后退，才发觉身体已经顶到了墙壁。")
	await novel_interface.show_text_only("但她并没有停下的意思，一只手臂撑住墙，把我逼到了墙角。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("所、所以呢……？", player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("脸贴的太近了！\n我的心扑通扑通要爆炸了！")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("所以从今以后，你就是我的人了~", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("诶——？？", player_name)
	await novel_interface.show_dialog("什、什么你的人啊！！！", player_name)
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("呵呵呵~我来看看……\n"+player_name+"，ID是2519G1911，15岁", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉终于放开我，娴熟的掏出一个手持设备，开始划划点点")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("初中开始回到普通公立学校上学……\n之前是独居的思春期少年阿~", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("身高165……不对，现在变成161了，体重也轻了不少，更新一下。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("随着莉琉的操作，手持设备发出清脆的确认音效。")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("哎？变矮了吗？", player_name)
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("（也对……之前的衣服都不合身了……）", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("还是高崎明良少女后援会的成员？\n啧啧，真是纯情……", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("你的网购记录也很有趣啊~《我的妹妹不可能是偶像》、《魔爱H》", "莉琉")
	await novel_interface.show_dialog("还买了抱枕……特殊版？", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊！！！\n不要看！！不要看啊！！！！", player_name)
	novel_interface.change_2nd_expression("sob")
	await novel_interface.show_dialog("（这是公开处刑吧？！\n不不不，被她看到比处刑还要糟糕啊！！）", player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("嘛……不欺负你了~", "莉琉")
	await novel_interface.show_dialog("虽然一直有5级权限，但是还是第一次做这么有趣的事情呢", "莉琉")
	await novel_interface.show_dialog("我看看……开始资料修改……\n修改性别『女』！", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("清脆的确认音效。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("啧啧，会留下时间戳吗？\n万一被那帮家伙发现可就不好了……", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("那么……修改记录列为『机密』\n这样就OK了。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("户籍行政档案全部电子化还真是便利。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("就……这、这么轻易的？？", player_name)
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯哼~我刚刚修改了你在所有行政系统记录中的档案。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("你现在已经是法律意义上的女孩子哟。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("坐电车的时候直接进女士专用车厢也没问题~", "莉琉") #缺少一个♥型
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sob")
	await novel_interface.show_dialog("居然！居然就这么轻易的…！！", player_name)
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("心里一阵萎靡，无法接受……")
	novel_interface.character_light(0.35,"normal2")
	await novel_interface.show_dialog("另外，你的名字与你男性身份的关联也太多了……", "莉琉")
	await novel_interface.show_dialog("给你重新起个什么名字比较可爱呢……？\n让我想想……", "莉琉")
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/Shot/girlchar_battleWearingCry.png")
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	await novel_interface.show_text_only("我忽然意识到，莉琉竟然有这么大的权力")
	await novel_interface.show_text_only("动动手指就能改变别人的人生……")
	await novel_interface.show_text_only("虽然是为了保护我，可是……好不甘心啊！！")
	await novel_interface.show_text_only("我明明是男生啊！！明明还……")
	await novel_interface.show_text_only("想到这里眼泪就不争气的流了出来……\n呜呜呜呜……")
	await novel_interface.show_text_only("可恶，因为身体变成女生的缘故吗？\n居然这么容易掉眼泪……")
	await novel_interface.show_text_only("明明已经说好了不会再哭的……\n但眼泪就是止不住……")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("哎？你竟然哭了？\n难道是因为彻底改了性别嘛~", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("哈哈哈，好啦好啦……\n唉，看你哭得梨花带雨的样子，还真是惹人怜爱~", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("惹人怜爱……怜爱……\n怜……", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("嗯……『怜』这个名字倒是不错~\n和你现在的样子很搭哦。", "莉琉")
	await novel_interface.show_dialog("就这么决定了！\n从今天开始，你就叫『怜』吧！", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("设定信息同步权限为……5级。\n这样应该连你游戏记录的姓名板都会被改掉吧？！", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("怜……\n欸——？？？什么！？？", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("（是在逗我吧？！一定是在逗我吧！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("已经修改好了！从今以后所有识别系统都会认定你叫这个名字了啦……小怜~", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","sob",0.25)
	await novel_interface.show_dialog("名字这种东西也能随随便便就改掉吗？\n呜……", "小怜")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("好了，别哭哭啼啼的了~", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("监护人……嗯，设成我好了。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("我、我不要！", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("咦？想反抗吗——", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("是不是我刚才的态度太过温柔，让你产生了我很好说话的错觉？", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉的语气忽然严肃起来。\n一股巨大的威压感袭来……")
	novel_interface.show_character("liliu_uniform2","serious")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("对不起！监护人大人！！\n我错了！！", "小怜")
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("虽说以现在的状况，确实应该把你监禁起来~", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("请不要笑着说出这么危险的台词啊！", "小怜")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("刚才只是修改了你的基本信息，关联的历史记录还需要大量的修饰工作。", "莉琉")
	await novel_interface.show_dialog("在完成之前如果你的身份暴露，随时都会有危险。你的档案我先锁定——", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("手持设备又传来一声清脆的确认音效。")
	novel_interface.show_character("liliu_uniform2","serious")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_battle","wail",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……！", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sob")
	await novel_interface.show_dialog("嗯？", "小怜")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是机密通信，我要处理一下。\n你先去大厅等我吧。", "莉琉")

	print("=== 第二章第9话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
