# chapter2_ep15.gd - 第二章第15话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep15_script()

func play_script():
	pass

func chapter2_ep15_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_passage.png")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("唉……裙子还是太短了啊……\n下面凉飕飕的……", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("这几天发生了太多难以置信的事情\n脑子都不够使了……", "小怜")
	await novel_interface.show_dialog("无论是城市毁灭的梦，还是清早起来就发现自己变成了女生，还是遭到莫名其妙的敌人袭击……", "小怜")
	await novel_interface.show_dialog("都那么的没有实感\n而且……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("小怜同学，进来吧。", "班主任")
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("啊，是！", "小怜")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_classRoom.png")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("初、初初、初次见面！\n大家好，我叫怜……", "小怜")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("很高兴和大家成为同学，今后就请大家多多指教了\n……", "小怜")
	await novel_interface.show_dialog("（然而是以不得不当女高中生的方式成为同学\n……）", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("（……饶了我吧……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那么，怜同学就坐后排的空位子吧。", "班主任")
	await novel_interface.show_dialog("（……这个时期转学，真稀奇呢。）", "同学A")
	await novel_interface.show_dialog("（看她一直盯着地上，应该很文静吧？）", "同学B")
	await novel_interface.show_dialog("（不过很可爱啊……头发的颜色是染过的吗？）", "同学A")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("大家都在看我……\n呜呜……前途多难啊……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("呼，下课了……学校生活以前可没这么累人啊。\n果然高偏差值的学校就是不一样……", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("（糟糕……想上厕所……）", "小怜")
	await novel_interface.show_dialog("（不…不行，绝对不能进学校的女洗手间…！）", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("唉，该怎么办啊……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("怎么啦~唉声叹气的。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("欸？安妮！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	await novel_interface.show_dialog("怎么样？新的学校还适应吗？这里都是些很可爱的女孩子呢~", "安妮")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("呜……先不管那些啦。\n你的基础知识训练结束了吗！", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("哼哼，我一通过考核就赶过来啦！让小怜一个人在这里说不定出什么事呀。", "安妮")
	await novel_interface.show_dialog("好在离开的时间不是很久，现在的新丰洲又是移民城市，我应该不难适应的。", "安妮")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("莉琉小姐还委托我要照顾小怜呢~\n特意把我们安排在一个班。", "安妮")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ren_uniform","shy",0.25)
	await novel_interface.show_dialog("我一个大男……\n总之照顾什么的，不用的啦~~", "小怜")
	novel_interface.character_2nd_light(0.35,"normal1")
	novel_interface.character_dark()
	await novel_interface.show_dialog("嘿嘿，而且呆在你身边，我也比较安心……", "安妮")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("我听说你自告奋勇要和我一起加入SID的事了。", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮露出感谢的神情，我一时语塞，也不知道自己能不能顺利通过测试……")
	novel_interface.show_character("anne_uniform","normal1")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("ren_uniform","shy",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("对了，刚才保健室的老师托我转告，要你去找她做一下体检。", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("体、体检！？", "小怜")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我们是转学生所以学校要单独体检啦~\n还是说，你是在懊恼错过了全班一起的……", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_dialog("哪有！！\n我明白啦，可在此之前……", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯？", "安妮")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"shy_left")
	await novel_interface.show_dialog("（……厕……所……）", "小怜")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("anne_uniform","worry",0.25)
	await novel_interface.show_dialog("听不见啦……说大声点~", "安妮")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"shy_right")
	await novel_interface.show_dialog("……那个，可不可以带我去上厕所……", "小怜")
	await novel_interface.show_dialog("我一个人会……很有罪恶感，不敢进去……", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("anne_uniform","normal2")
	await novel_interface.show_dialog("噗……\n还说不用人照顾~", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("好啦……快……", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/School/BG_School_passage.png")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("（额……体检的话……）", "小怜")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("（以前是男孩子的事，应该不会露馅吧！）", "小怜")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("（体检都要检查什么来着？）", "小怜")
	await novel_interface.show_dialog("（话说……是要脱衣服的吧？）", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（幸好没有嫌麻烦，把内衣穿来了……）", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/School/BG_School_heathRoom.png")
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("（保健室……是这里吗？）", "小怜")
	await novel_interface.show_dialog("打扰了，我是来体检的转学生……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("来得好，正等你呢。", "爱衣")
	novel_interface.change_music("res://assets/audio/music/Chaostic Daily.mp3")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("爱、爱爱爱、爱衣？", "小怜")
	novel_interface.change_expression("wail")
	await novel_interface.show_dialog("呜哇，别，为什么是你来做检查嘛！？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("欸？？？\n爱衣，住、住手啊———！！", "小怜")
	await novel_interface.show_dialog("等等……你手上拿的，那个奇怪的张牙舞爪的器械是什么？？", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("呜啊啊啊啊———！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_heathRoom.png")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("呜呜呜，怎么这样……", "小怜")
	await novel_interface.show_dialog("这种事情那种事情的，明明可以不用做的吧……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","blush_stare",0.25)
	await novel_interface.show_dialog("你太夸张啦。\n不过是常规的检查，常规哦~", "爱衣")
	novel_interface.change_2nd_expression("blush_think")
	await novel_interface.show_dialog("……双眼视力2.0，非常完美呀。\n和你以前的数据有变化吗？", "爱衣")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("诶？我原来是左眼1.0，右眼0.7\n医生还让我玩游戏的时候离远点……", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"blush_dizzy")
	await novel_interface.show_dialog("太有趣了……你的身体就像被重新构造了一遍，整个骨骼都发生了变化。", "爱衣")
	novel_interface.change_2nd_expression("blush_think")
	await novel_interface.show_dialog("但大脑的神经拓扑结构却同时展现了两种性别的特质，所以记忆和思维习惯得以保留吗……", "爱衣")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("爱衣的情绪似乎很激动，声音都有点发抖。")
	novel_interface.show_character("ai","blush_wink")
	await novel_interface.show_dialog("这样的话……理论上你应该能意识到，自己更容易感知别人的情绪了。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("没、没有吧……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("绝对没有！我是100%的男生！", "小怜")
	novel_interface.show_character("ai","think")
	await novel_interface.show_dialog("总之，从医学角度看来，你100%是女性无疑。\n健康状态完全没有问题，只不过……", "爱衣")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","worry",0.25)
	await novel_interface.show_dialog("只不过？", "小怜")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("过段时间会经历一次腹痛，除此以外都没问题~\n应该快了，记得做好准备啦。", "爱衣")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("肚子痛吗……", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,false,"wail")
	await novel_interface.show_dialog("……欸——？？？", "小怜")
	novel_interface.change_2nd_expression("sob")
	await novel_interface.show_dialog("呜呜……爱衣，你！！", "小怜")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("感觉委屈又无力，快要哭出来了……\n呜呜呜，男子汉，不许哭！！")
	novel_interface.show_character("ai","blush_think")
	await novel_interface.show_dialog("嗯嗯，真的是完美啊……很少有人长这么大身上一点疤痕都没有哦。", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","shy_left")
	await novel_interface.show_dialog("听着一点都不会开心啊！！", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("那个——我可以回去了吗……？", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Shot/aiyi_pickwearing.png")
	await novel_interface.show_text_only("爱衣脱掉了白大褂，一幅准备“这次要认真了哦”的表情，从衣柜里拿出两件衣服……")
	await novel_interface.show_dialog("说什么呢？\n好戏才刚开始呢……", "爱衣")
	await novel_interface.show_dialog("莉琉批准了，可以把各种各样的衣服都给小怜试穿一下呢……", "爱衣")
	await novel_interface.show_dialog("噫、噫——？", "小怜")
	await novel_interface.show_dialog("然后……呵呵呵呵，我还要研究一下小怜的每一项数据的啊。", "爱衣")
	await novel_interface.show_dialog("呀啊啊啊啊啊啊啊啊啊啊~~~！", "小怜")

	print("=== 第二章第15话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
