# chapter2_ep22.gd - 第二章第22话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep22_script()

func play_script():
	pass

func chapter2_ep22_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_City_powerSubstation.png")
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("对了，刚才你收起来的那几张纸在哪？", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","gratified",0.25)
	await novel_interface.show_dialog("啊……我正想跟你说呢。", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我拿出刚才战斗后捡到的文稿递给安妮，伊露卡在旁边似乎欲言又止。")
	novel_interface.show_character("anne_battle","happy")
	await novel_interface.show_dialog("Wardenclyffe\nManuscript……好厉害啊！你居然能找到这个！", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","worry",0.25)
	await novel_interface.show_dialog("这是之前那这群家伙们身上掉落下来的东西。总感觉哪里怪怪的……安妮可以读出来？", "小怜")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯——虽然很模糊，但确实能从它上面感受到魔力的流动。", "安妮")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("这应该就是『魔导书』……不，是魔导书的残页。", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("魔导书……是跟魔女有关的？", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("是记录魔法信息的文本，我第一次接触这种东西的时候，是不知道哪里冒出来的一本小册子。", "安妮")
	await novel_interface.show_dialog("名字好像叫做《神秘弹道学》，就那么凭空出现在我的储物柜里。", "安妮")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("一开始我还以为是教练发的，上面教的东西也很奇怪，比如改变弹道的魔法之类的。", "安妮")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("后来发现教练并不知道这本书，而且我觉得这只是迷信之类的，也从没有使用过。", "安妮")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("直到……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮似乎不想再回忆了，低头看着那几页书稿。")
	novel_interface.show_character("ren_battle","normal2")
	await novel_interface.show_dialog("我记得莉琉说过，『魔女』是感染了某种信息，而获得了一些类似『异质物』特性的人类。", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","normal",0.25)
	await novel_interface.show_dialog("感染嘛……倒是很贴切的形容，虽说是“信息”…\n…但有些“信息”一旦沾染就永远也忘不掉了。", "安妮")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("像是那种洗脑的广告歌和鬼畜视频吗？想忘也忘不掉，还会在走神的时候情不自禁的哼哼~", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("哈哈，小怜的形容很贴切呢。", "安妮")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("会不会是这几页纸，引起了时空波动？\n不过……真的就凭这几张纸吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"worry")
	await novel_interface.show_dialog("很有可能，这种信息对人的精神损耗很大，就算我都能明显的感觉到那种巨大的负担。", "安妮")
	novel_interface.change_2nd_expression("normal")
	await novel_interface.show_dialog("所以才要借助某种“物品”释放魔法，让它们代自己承受这种代价。", "安妮")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("安妮指了指自己的球棒，这种会消耗魔力的武器就是这么产生的吧……")
	novel_interface.character_2nd_light(0.35,"gratified")
	await novel_interface.show_dialog("如果接受了过量难以负荷的信息，就算丧失心智变得疯狂也有非常可能……", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("疯狂，女巫……\n需要，消灭。", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","gratified")
	await novel_interface.show_dialog("女巫……就是那种不幸的人吧？\n安妮懂得真多呢。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("哎？也没有啦……\n我也只是根据自己的经验做的推断而已。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("手稿……", "伊露卡")
	novel_interface.character_dark()
	await novel_interface.show_text_only("伊露卡露出若有所思又带着向往的表情。")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_battle","smile",0.25)
	await novel_interface.show_dialog("嗯？怎么啦，伊露卡？你也想看吗？", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯。", "伊露卡")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("伊露卡睁大了眼睛，像小动物一样用水润恳求的眼神看着我。")
	await novel_interface.show_text_only("完全无法拒绝，但这么危险的东西……")
	await novel_interface.show_text_only("正在我犹豫的时候，附近忽然传来了运输机降落的声音。")
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("有人来了！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("是SID的探员吗？太好了，我们发现了一名……\n咦？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("出乎我的意料，从运输机上下来的，并不是SID的探员。")
	await novel_interface.show_text_only("戴着眼镜的男人神色慈祥的看着伊露卡，但伊露卡却露出了恐惧的神色。")
	novel_interface.change_music("res://assets/audio/music/Conspiracy.mp3")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("伊露卡，这次动作很慢呢。", "管理员")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("管理员……对不起。", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("手稿拿到手了？\n跟你说过不能自己消化吧，快点拿过来。", "管理员")
	await novel_interface.show_dialog("如果这点小事都办不好，会变成那些没用的东西\n哦。", "管理员")
	await novel_interface.show_dialog("这里清理完毕后，马上跟我去奧莉加执行下一个任务。", "管理员")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("你那是什么语气！没看到她受伤了吗？", "小怜")
	novel_interface.change_expression("shout")
	await novel_interface.show_dialog("她只是个小姑娘，不是你的工具！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("陌生的男人这时才注意到站在一旁的我，他笑咪咪的打量着我，就像注视着某种猎物。")
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("伊露卡，把这个人也带走。", "管理员")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("哎？！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("我可不允许你做这种事，只要有我在，谁都别想带走小怜！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("带走……？", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("jacob")
	await novel_interface.show_dialog("对，这是命令。", "管理员")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("命令……", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡迷茫地望着我，她似乎很痛苦的在抗拒着什么。但终究无法反抗管理员的指令。")
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("任务：带走小怜。\n目标锁定——", "伊露卡")

	print("=== 第二章第22话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
