# chapter2_ep21.gd - 第二章第21话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep21_script()

func play_script():
	pass

func chapter2_ep21_script():
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/Shot/BG_City_powerSubstation.png")
	await novel_interface.show_text_only("一场激战过后，终于消灭了领头的家伙，其他人也随之化作一团红雾消散了。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("呼——\n诶？！", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("几页发黄的文稿落在了我面前，上面文字和图案错落交织，展现出一幅让人完全无法理解的状态。")
	novel_interface.character_light(0.35,"normal1")
	await novel_interface.show_dialog("W…A…D…", "小怜")
	novel_interface.change_expression("panic")
	await novel_interface.show_dialog("嗯？？\n是我眼花了吗……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我揉了揉眼睛又盯着那几页纸看了一遍，唯一可以确定的是，它们是用英语写成的。")
	await novel_interface.show_text_only("虽然能辨认局部的字母，可我一旦试图将它们连成单词和句子。")
	await novel_interface.show_text_only("就顿时觉得脑海中一片混乱在搅动，让我无法识\n别。")
	await novel_interface.show_text_only("就像患上了阅读困难症，我连那上面最简单的单词都认不出来了。")
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("先别在那里一直看啦，救人要紧~~", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("哦~知，知道啦！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("在我将它们收起来的一瞬间，似乎看纸张上闪过符咒纹样的光芒然后快速的消失了。")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("那是——", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog("什么？", "安妮")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("难道，是我的错觉？\n（那股难以言说的震颤，到底是……）", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("而手臂上还残留着酸麻的感觉，提醒着我，这一切并不是幻觉。")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("……", "伊露卡")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","gratified",0.25)
	await novel_interface.show_dialog("对了，你没事吧？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我打量起受伤的小女孩，她的表情依旧十分冰冷\n似乎并没有因为受到我和安妮帮助而感到开心。")
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("……", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("仔细一看，她的外表和装备，肯定不是普通的小孩子……")
	await novel_interface.show_text_only("眼罩这种地方也就罢了，罩袍之下，露出的是被机械铠甲包裹的双手。")
	await novel_interface.show_text_only("而且看她腹部的伤口……可能成年人都要哭喊丧失行动能力")
	await novel_interface.show_text_only("可她却始终一言不发的静静蹲着。")
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("小妹妹，你叫什么名字？\n在这种地方做什么？", "小怜")
	await novel_interface.show_dialog("刚才那群是什么人，你知道吗？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog("一口气问这么多，她回答不了吧……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("突然间，小女孩不顾还在渗血的伤口站了起来，个头还挺高的嘛……")
	await novel_interface.show_text_only("等等等等！！\n她的身体……悬浮在地面上？！")
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("……伊露卡。\n任务：消除，女巫。", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("小女孩用了一种奇怪的方式回答着问题。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_text_only("伊露卡……是她的名字吗？\n好奇怪的语气。")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("目标，判定——\n人类，女性，数量……", "伊露卡")
	await novel_interface.show_dialog("一名。", "伊露卡")
	await novel_interface.show_dialog("……\n再判定，启动。", "伊露卡")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","smile",0.25)
	await novel_interface.show_dialog("（『一名』女性？）\n（难道她能看出我的本质！！！）", "小怜")
	novel_interface.change_2nd_expression("uneasy")
	await novel_interface.show_dialog("没、没错！我可是男孩子啊！", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("魔女，数量，一名。\n防御模式，启动。", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"smile")
	await novel_interface.show_text_only("啊哈哈哈——\n最近总是出现自己被陌生人认出是男生的幻觉……")
	novel_interface.change_2nd_expression("wail")
	await novel_interface.show_text_only("小女孩手部的光怎么越来越亮啊？\n嗯？喂、慢着！")
	novel_interface.change_2nd_expression("sob")
	await novel_interface.show_dialog("啊啊啊啊啊——\n痛痛痛痛痛！", "小怜")
	novel_interface.change_2nd_expression("wail")
	await novel_interface.show_dialog("喂，怎么突然连我都劈啊？！", "小怜")
	novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("还好我反应快，雷击只是擦到手臂之后在刚才站的地面上留下一个小白点。")
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("战斗能力低下，逃跑迅速。\n——无威胁。", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我，似乎被鉴定为弱鸡了……")
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("有必要连帮忙的人都攻击吗？\n而且为什么针对我啊……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_battle","",0.25)
	await novel_interface.show_dialog("魔女，打不过。", "伊露卡")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("太直白了！！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("小伊露卡，你看我们这么友善。\n绝对不会是坏人啦~~", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","bored",0.25)
	await novel_interface.show_dialog("（小声）安妮，这种发言不仅没有说服力，而且很像诱拐犯啊……", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("嗯……", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("——那么，伊露卡，也是魔女吗？", "安妮")
	novel_interface.character_dark()
	await novel_interface.show_text_only("安妮没有理我，而是直截了当的提问。")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_battle","speechless",0.25)
	await novel_interface.show_text_only("喂喂，万一伊露卡连『魔女』是什么都不懂呢？")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("伊露卡，是，『行刑者』。", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("『行刑者』……现在的小孩子都喜欢这么中二的称号吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("……", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","frustrate")
	await novel_interface.show_dialog("……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("（糟糕，把心里的吐槽说出来了……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("又一道落雷，还好及时躲开了。")
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("哎，小朋友！\n有话好好说啊！", "小怜")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("嗯……给你一块巧克力，别生气了好不好？", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("我将兜里的巧克力拿出来，分了一半递给伊露卡。")
	novel_interface.character_light(0.35,"wry_smile")
	await novel_interface.show_text_only("呼，还好身上有带巧克力。\n毕竟应该不会有小孩子讨厌巧克力吧？")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("iluka_battle","",0.25)
	await novel_interface.show_dialog("……", "伊露卡")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊——\n你看，我已经吃掉啦！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("巧克力？", "伊露卡")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不是什么危险的东西啦……\n是能给人带来幸福感的零食哦！", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("（小声）随便给陌生的小女孩投喂食物，小怜才更像诱拐犯吧！", "安妮")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("嗯……不过在随身携带巧克力这点上来说，你已经越来越像女孩子了呢！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡犹豫了一下，小心翼翼地打开外包装，慢慢地将巧克力含进嘴里。")
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("……\n奇怪的，味道……", "伊露卡")
	await novel_interface.show_dialog("苦苦的。", "伊露卡")
	await novel_interface.show_dialog("甜甜的……", "伊露卡")
	await novel_interface.show_dialog("伊露卡，不讨厌。", "伊露卡")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","gratified",0.25)
	await novel_interface.show_dialog("嘿嘿，喜欢吗？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("糟糕，她的表情，超可爱的……！")
	novel_interface.show_character("ren_battle","smile")
	await novel_interface.show_dialog("唉嘿嘿嘿……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("啊！小怜露出了很危险的表情。", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_battle","",0.25)
	await novel_interface.show_dialog("表情，识别……变态。", "伊露卡")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("变变变态——？！\n是说我吗？！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_battle","",0.25)
	await novel_interface.show_dialog("但是，伊露卡，不讨厌。", "伊露卡")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嘿嘿，不讨厌就好~", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_battle","frustrate")
	await novel_interface.show_dialog("被说成变态也这么高兴吗？\n果然不能对你掉以轻心啊……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("求你别在旁边添加奇怪的注释啦！", "小怜")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("啊，对了！\n我这里还剩下一块巧克力，也给你吧！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_battle")
	await novel_interface.show_dialog("……给你。", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡从身上摸出了一块五号电池模样的透明容器递给我，里面有发着绿色荧光的粘稠液体。")
	novel_interface.show_character("ren_battle","gratified")
	await novel_interface.show_dialog("这是……电浆液吧？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_battle","",0.25)
	await novel_interface.show_dialog("交换，食物。", "伊露卡")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这种东西能够被称之为食物吗？", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("伊露卡认真地点了点头。")
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("饿的时候，管理员，给我食物。\n补充，能量。", "伊露卡")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("管理员，是你的监护人吗？", "小怜")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("如果能吃巧克力，应该是身体机能正常的小孩吧？", "小怜")
	await novel_interface.show_dialog("又不是家用电器……", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("果然这个小女孩，能感觉到魔法刻印的存在。", "安妮")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("但驱动的方式……很特别。", "安妮")
	await novel_interface.show_dialog("『行刑者』……吗？", "安妮")

	print("=== 第二章第21话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
