# chapter2_ex02.gd - 第二章番外02
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ex02_script()

func play_script():
	pass

func chapter2_ex02_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/hall.png")
	novel_interface.show_character("ren_battle","blush")
	await novel_interface.show_text_only("在大厅角落的镜子前面，看着镜中反射的自己\n稍稍被泪水浸湿的睫毛随着呼吸起伏……")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("已经完全……是女孩子的样子了吗？", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("（下面……空空的……）", "小怜")
	await novel_interface.show_dialog("（这样的话……）", "小怜")
	novel_interface.change_expression("shy_right")
	await novel_interface.show_dialog("（要怎么……上厕所啊……）", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（摸…）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("你在做什么呢？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("哇———哇———！！！", "小怜")
	await novel_interface.show_dialog("不是的…这个！！\n对不起！！我并没有想奇怪的事情……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("哈哈哈，你是在向谁道歉呢？\n难不成…是对自己的身体吗？", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","shy",0.25)
	await novel_interface.show_dialog("（怎、怎么办？？）", "小怜")
	novel_interface.change_2nd_expression("blush")
	await novel_interface.show_dialog("莉琉……那个……", "小怜")
	novel_interface.change_2nd_expression("shy_left")
	await novel_interface.show_dialog("女、女孩子要……", "小怜")
	novel_interface.character_light(0.35,"speak")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("要什么啊？拜托别人的时候要把事情说的清清楚楚才行！", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_dialog("……要怎么上厕所啊！？", "小怜")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哈——？！", "莉琉")
	await novel_interface.show_dialog("啊哈哈哈哈哈~~~~", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy_left")
	await novel_interface.show_dialog("（我居然真的问出来了！！又要被捉弄了……）", "小怜")
	await novel_interface.show_dialog("（但我好像……要忍不住了……）", "小怜")
	novel_interface.change_2nd_expression("timid")
	await novel_interface.show_dialog("不、不要笑了啦！！", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嘛……像平常那样坐下去就好了。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("女厕所就在走廊那边，快去吧！！", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,false,"normal1")
	await novel_interface.show_dialog("噗，这小鬼居然在女厕所前面纠结了几秒……\n最后还是闪着泪花着跑进去了嘛~", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("真是……太可爱了！！", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("……\n哗——（冲水的声音）")
	novel_interface.show_character("ren_battle","uneasy")
	await novel_interface.show_dialog("啊——总算放松了~~", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("等等…怎么……", "小怜")
	novel_interface.change_expression("timid")
	await novel_interface.show_dialog("颠…颠几下…？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………")
	await novel_interface.show_text_only("………………")
	novel_interface.change_background("res://assets/images/bg/SID/hall.png")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("回来了？感觉怎么样？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","shy_right")
	await novel_interface.show_dialog("这种事情不要问我感想啊！！！", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("（怪不得之前经常听说女厕所很容易没手纸……）", "小怜")
	await novel_interface.show_dialog("呜呜呜……\n真是太尴尬了……", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("可悲可悲可恶！！\n我一定！一定要尽快变回去！！", "小怜")

	print("=== 第二章番外02结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
