# chapter2_ex04.gd - 第二章番外04
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ex04_script()

func play_script():
	pass

func chapter2_ex04_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_street3.png")
	await novel_interface.show_text_only("得到了莉琉的许可，我和安妮决定带伊露卡逛街。")
	await novel_interface.show_text_only("伊露卡站在我的身后，谨慎地观察着周围的一切。")
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("伊露卡，巧克力要吗？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_normal","normal",0.25)
	await novel_interface.show_dialog("伊露卡，巧克力，喜欢。", "伊露卡")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("来，这一块给你。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡接过巧克力，小心翼翼地撕开包装，轻轻地咬了一口巧克力。")
	await novel_interface.show_text_only("不管看多少次，都觉得真是太可爱了！")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("某个人的脸上又出现了中年大叔才会有的表情哦！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("哎？！已经从青春期男生进化成中年大叔了吗？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_normal","smile",0.25)
	await novel_interface.show_dialog("变态——", "伊露卡")
	novel_interface.character_light(0.35,"stare")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("为什么会两个人一起攻击我啊！真是的！", "小怜")
	novel_interface.change_expression("sprite")
	await novel_interface.show_dialog("伊露卡，再这样的话就不给你吃巧克力了哦~", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("呜……", "伊露卡")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("糟糕，这种沮丧的表情也好可爱啊！")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("嘿嘿嘿，骗你的啦。\n喏，再给你一块。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("……你究竟在身上藏了多少巧克力啊？！\n摄入过量糖分会变胖哦！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("有什么关系嘛，只是几块巧克力而已。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮用异样的眼神紧紧地盯着我，让我感到了一股无形的压力。")
	novel_interface.show_character("ren_uniform","uneasy")
	await novel_interface.show_dialog("怎、怎么了？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","stare",0.25)
	await novel_interface.show_dialog("我有偷看过小怜最近的体检报告哦！\n除了体重在不断增长以外，身高一点变化都没有。", "安妮")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("为什么你要去看那种东西啊！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("嘿嘿嘿，当然是为了更加了解小怜呀。", "安妮")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("比如我现在就已经知道了，你的身高和我一样只有161厘米呢！", "安妮")
	novel_interface.character_light(0.35,"shy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("可恶，这有什么值得骄傲的啊！", "小怜")
	novel_interface.change_expression("shy_right")
	await novel_interface.show_dialog("再说了，我还是个男生的时候，身高可有165呢！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"panic")
	await novel_interface.show_dialog("哎？明明是男生，却只比现在高出那么一点吗？", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"awkward")
	await novel_interface.show_dialog("中计了……\n不该把这个数字说出来被你嘲笑的。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("从刚才起就一直在默默地吃着巧克力的伊露卡，在听到这段对话后，忽然疑惑地抬起了头。")
	novel_interface.show_character("iluka_normal","gourmet")
	await novel_interface.show_dialog("小怜姐姐？", "伊露卡")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","smile",0.25)
	await novel_interface.show_dialog("怎么啦？", "小怜")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("小怜……哥哥？", "伊露卡")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("……", "小怜")
	novel_interface.character_light(0.35,"sleepy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("姐姐？哥哥？\n数据混乱，无法判定。", "伊露卡")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"perspire1")
	await novel_interface.show_dialog("伊露卡！快点把刚才的对话忘掉！", "小怜")
	novel_interface.character_light(0.35,"normal")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("重新扫描，目标，人类女性……\n姐姐？哥哥？", "伊露卡")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sob")
	await novel_interface.show_dialog("啊啊啊快停下来啊！", "小怜")

	print("=== 第二章番外04结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
