# chapter2_ep04.gd - 第二章第4话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep04_script()

func play_script():
	pass

func chapter2_ep04_script():
	var player_name = GameConfig.player_name
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/hearingRoom.png")
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("嗯……但一切都真实得不像梦，我也有点糊涂。", player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("我找了好久，可完全查不到火灾或建筑损毁的新闻\n城市的景象也和平时没什么不同。", player_name)
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("只是……", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("嗯？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","normal")
	await novel_interface.show_dialog("只是……？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","shy_left")
	await novel_interface.show_dialog("一觉醒来……", player_name)
	novel_interface.change_music("res://assets/audio/music/Whisky.mp3")
	await novel_interface.show_dialog("我的身体，变成女生了……", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("……", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","normal",0.25)
	await novel_interface.show_dialog("……", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("嗯……", player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","speak2",0.25)
	await novel_interface.show_dialog("哦？你是说……变？", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我……别看我现在这样……", player_name)
	await novel_interface.show_dialog("我！我其实，本来是男生啊！！", player_name)
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true)
	await novel_interface.show_dialog("哦哦哦？ 男生？", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("啊……哈？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("你是说，你现在是在男扮女装？（凑近）", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_dialog("不、不是那个意思！\n喂！不要离我这么近啊！", player_name)
	novel_interface.change_2nd_expression("shy_left")
	await novel_interface.show_dialog("咦……不过某种意义来说……\n也算是？", player_name)
	novel_interface.change_2nd_expression("shy")
	await novel_interface.show_dialog("啊啊，真是的！", player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal2")
	await novel_interface.show_dialog("嗯……这胸部做得真不错。（摸）", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("这种弹性……到底用什么样的技术才能有这么自然的手感……（捏）", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","happy",0.25)
	await novel_interface.show_dialog("咦？这方面的话，安妮也想知道~~！！", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("呀！啊……不是，那个……\n你们不要随便摸我啊！！！", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("我看看……肩膀也很纤细，从腰到骨盆的曲线也很优美。", "莉琉")
	await novel_interface.show_dialog("全身究竟是用了怎样的材料，尤其是……", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("呀啊啊啊！很痒呀……！", player_name)
	novel_interface.change_expression("perspire1")
	await novel_interface.show_dialog("莉琉小姐！那里！不行啊！", player_name)
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("不行啊啊啊啊~~~！！！！！", player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("……")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("呜呜呜呜………", player_name)
	await novel_interface.show_dialog("总、总而言之！到昨天为止我都是男生！", player_name)
	await novel_interface.show_dialog("也没有做过任何手术之类的……", player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("不，我没怀疑这一点。", "莉琉")
	await novel_interface.show_dialog("以现在的技术，无论如何也不可能如此彻底的改变性别……", "莉琉")
	await novel_interface.show_dialog("如果不把骨骼全部换掉是无法做到这一步的。\n所以，你本来就是个女生。", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所以！我都说了！！\n我是一觉醒来就变成这样了啊！", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("那你有什么实际的证据吗？\n来证明你曾经的男性身份？", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯……证据……\n啊，学生证！", player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("我们进来的时候随身的东西都被没收了，包括我出门时穿的男装和里面的ID卡。")
	await novel_interface.show_text_only("莉琉在手持终端上点了两下，调出了我的学生证。")
	novel_interface.character_light(0.35,"bored")
	await novel_interface.show_dialog("有了！哼，就是这个！\n你们看！我是男的吧？", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("虽然五官的排列倒确实有一点点像，但仅凭这种东西……", "莉琉")
	await novel_interface.show_dialog("对了，调出城市监控系统最近1个月拍摄到"+player_name+"的所有录像……", "莉琉")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("莉琉熟练的在平板上点按了起来，脸上露出了一丝兴奋的表情。")
	novel_interface.character_light(0.35,"worry")
	await novel_interface.show_dialog("看到那些废墟的时候我还以为自己在做梦，以为醒了就好了……", player_name)
	await novel_interface.show_dialog("可醒来却发现自己变成了女孩子……", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("加入骨骼变化的修正，和刚才在走廊扫描到你的步态比对……", "莉琉")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("莉琉并不理会我的自言自语，继续饶有兴致的操作着手里的东西。")
	novel_interface.character_light(0.35,"bored")
	await novel_interface.show_dialog("难道那不是梦？可是现在一切都好好的，完全不像发生过那种事情……", player_name)
	novel_interface.change_expression("wry_smile")
	await novel_interface.show_dialog("啊……我真是，完全搞不清楚了……！", player_name)
	await novel_interface.show_dialog("到底我的记忆里哪些是真的哪些是梦啊……！", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("……步态识别模式吻合。", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是什么意思？", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("步态模式是大脑在行走时对身体每一块肌肉的控制习惯，就算是最优秀的特工也无法伪装。", "莉琉")
	novel_interface.change_2nd_expression("serious")
	await novel_interface.show_dialog("虽然现有的科学理论无法解释……\n但你确实是"+player_name+"。", "莉琉")
	novel_interface.character_move_left(-0.3,0.3,false)
	novel_interface.character_2nd_move_left(0)
	novel_interface.show_3rd_character("anne_battle","perspire",0.3)
	await novel_interface.show_dialog("真，真的吗？？", "安妮")
	await novel_interface.hide_2nd_character()
	await novel_interface.hide_3rd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("我还以为到这里就能搞清楚点什么……", player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("我说，你知道什么关于『洛斯金杯』的事吗？", "莉琉")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("洛斯金杯？早上看到新闻说在监控下突然消失的异质物……我也没亲眼见过啦。", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("嗯，假设你说的全是真话……", "莉琉")
	await novel_interface.show_dialog("我会答应去做那种无聊又没钱拿的讲座，原因只可能是它了。", "莉琉")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("那是在洛斯群岛上找到的『异质物』，杯子外面镶着四块纯度不可思议的宝石。", "莉琉")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("对了，后来我爬出废墟，看到飞在天上的发光的东西轮廓确实有点像个杯子……", player_name)
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("就那么浮在半空，发出的光还泛着淡淡的红色……", player_name)
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"serious")
	await novel_interface.show_dialog("淡红色？？", "莉琉")
	await novel_interface.show_dialog("（杯子里面的淡红色液体一直是不解之谜……）", "莉琉")
	await novel_interface.show_dialog("（但这个情报被列为机密，即使前不久被评定为了『Safe』也从没对外公开过）", "莉琉")
	await novel_interface.show_dialog("（没亲眼见到的人不可能说出这种细节……）", "莉琉")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("看来无论你说的是不是真是场梦，都有必要向你再多了解一下情况。", "莉琉")

	print("=== 第二章第4话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
