# chapter2_ep17.gd - 第二章第17话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep17_script()

func play_script():
	pass

func chapter2_ep17_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_diningRoom.png")
	await novel_interface.show_text_only("不愧是超——有名（钱）的学校！\n餐厅里的食物种类丰富到让人想流泪。")
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("您好！请给我一份咖哩饭套餐，三个炸鸡翅。", "小怜")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("今天的虾饼看上去也不错呢，麻烦给我两块吧。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("小姑娘，你一个人能吃完吗？", "食堂员工")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("当然没问题~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("喂喂，你们看那边那个女生，一个人居然能吃这么多东西。", "同学甲")
	await novel_interface.show_dialog("看不出来啊，难道是大胃王吗？", "同学乙")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("（……以男生的食量来说，这些不是正常范围的\n吗？）", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","normal1",0.25)
	await novel_interface.show_dialog("嘿嘿，大家一定都很羡慕你\n能吃这么多食物还长不胖~", "安妮")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("这是什么值得羡慕的事情吗？\n唔哇！虾饼的味道……果然超棒啊！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("那个，小怜……", "安妮")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("肿么啦？（嚼）\n这个咖哩饭也吼吼吃啊~（嚼）", "小怜")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("唔已经耐上这学校啦！（嚼）", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("小怜吃东西的样子，果然非常豪爽呢！", "安妮")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("哎？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那是新转学来的学生吗？", "同学甲")
	await novel_interface.show_dialog("行为举止完全不像女生啊……\n哇还分开腿坐！", "同学乙")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("……可恶。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("呜呜呜~", "小怜")
	await novel_interface.show_dialog("似乎……吃不下了……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","panic",0.25)
	await novel_interface.show_dialog("这才是女孩子的正常范围啦。", "安妮")
	novel_interface.character_light(0.35,"uneasy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我以前可是一顿能吃上两天的份量\n然后慢慢消化的……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("嗤……哈哈哈！\n你是骆驼吗？干嘛这么拼命啊。", "安妮")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"gratified")
	await novel_interface.show_dialog("因为……小时候经常不知道下次什么时候能有吃\n的。", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/Shot/cityCrash_ruin.png")
	await novel_interface.show_text_only("埃癸斯只能识别和屏蔽武器的射出的子弹，但手持武器的士兵却能轻易进入防护力场。")
	await novel_interface.show_text_only("所以半径35km的力场边界，成为了当时几百万幸存者的最后防线。")
	await novel_interface.show_text_only("战争制造了太多孤儿，忙于组织防御的元老院只能给每个保育学校发放有限的配额。")
	await novel_interface.show_text_only("我和很多小孩为了填饱肚子，经常要到边界的战区去寻找食物……")
	novel_interface.change_background("res://assets/images/bg/School/BG_School_diningRoom.png")
	novel_interface.show_character("anne_uniform","upset")
	await novel_interface.show_dialog("……小怜", "安妮")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("我知道啦，但也不能撑坏自己嘛。", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮应该也经历过那段历史吧……")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("呐~放学之后我带你去吃甜品吧！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("……嗯！", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/other/BG_City_coffeeShop.png")
	novel_interface.show_character("anne_uniform","normal1")
	await novel_interface.show_dialog("今天难得空闲能和小怜逛街呢~", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","shy",0.25)
	await novel_interface.show_dialog("之前我都没来过这种店……\n（周围都是女生啊，有点不自在……）", "小怜")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("看看菜单……我要这个！\n蓝莓雪芭超级碳酸特饮DX！！", "安妮")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("名字就好帅气~", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"gratified")
	await novel_interface.show_dialog("安妮还真是孩子气呢~", "小怜")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog(" 我要咖啡就行啦……", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("小怜现在可是女孩子呢。\n那些甜食很美味的啦~不试试看吗？", "安妮")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"gratified")
	await novel_interface.show_dialog("嗯……我看看\n抹茶拿破仑芝士松饼……（还，还不错嘛）", "小怜")
	novel_interface.change_2nd_expression("shy_left")
	await novel_interface.show_dialog("皇家香橙蜜饯奶油蛋糕……\n（看起来……也很美味啊）", "小怜")
	novel_interface.change_2nd_expression("shy_right")
	await novel_interface.show_dialog("热带盛宴冰果圣代……\n（吞口水）", "小怜")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_dialog("这位客人，请问您决定好点什么了吗？", "服务员")
	novel_interface.show_character("ren_uniform","awkward")
	await novel_interface.show_dialog("啊，那个！\n我还是……要咖啡就好了。", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("好的，请稍等。", "服务员")
	novel_interface.show_character("ren_uniform","panic")
	await novel_interface.show_dialog("嗯……", "小怜")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("请稍等！还、还是要一份……\n蓝莓慕斯草莓冰激凌巴菲吧……", "小怜")
	novel_interface.change_expression("shy")
	await novel_interface.show_dialog("我、我只是试试看啦！\n以前只见女同学吃过这种……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("嘿嘿~不用跟我解释的啦", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("久等了，这是您的甜品。", "服务员")
	novel_interface.show_character("ren_uniform","timid")
	await novel_interface.show_dialog("这个……我可以吃了吗？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("请用。", "服务员")
	novel_interface.show_character("ren_uniform","smile")
	await novel_interface.show_dialog("那我开动了！", "小怜")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("……", "小怜")
	novel_interface.change_expression("blush")
	await novel_interface.show_dialog("好、好美味……！！", "小怜")
	await novel_interface.show_dialog("新鲜草莓的香气和甜甜的奶油，再加上微酸的蓝莓慕斯……非常的好吃呢~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("才发现安妮饶有兴致的看着我陶醉的表情，有点不好意思")
	novel_interface.show_character("ren_uniform","shy")
	await novel_interface.show_dialog("其实……这些女孩子常去吃的东西是什么味道\n我一直都想知道呢。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("欸嘿嘿~~\n果然小怜……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","normal1")
	await novel_interface.show_dialog("嗯？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("很可爱呢~~", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("你…你在说什么啦突然就…！！", "小怜")

	print("=== 第二章第17话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
