# chapter2_ep11.gd - 第二章第11话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep11_script()

func play_script():
	pass

func chapter2_ep11_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/hall.png")
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("哟~这不是小怜嘛，刚刚成为名正言顺的美少女有什么感想吗？", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","shy",0.25)
	await novel_interface.show_dialog("……请不要再拿我开玩笑啦！", "小怜")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯哼~对了，刚才看到你在假期结束后准备去另一所公立学校上高中？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"worry")
	await novel_interface.show_dialog("是的，新学校离我住的地方比较近，还有就是……学分要求也没那么严……", "小怜")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("出于安全考虑，我会给你安排一个新的住所。\n至于学校嘛……", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（看来要去拜托那个老家伙了）", "莉琉")
	await novel_interface.show_dialog("（想想就觉得麻烦……还好信息已经被修正的非常完美了……）", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("御樱川女子中学，这所学校有最高的安保等级，而且离SID总部也不远。", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉边说边向上指了指。")
	await novel_interface.show_text_only("御樱川，在地下总部上方的繁华商区，据说是一座学费贵得吓死人的高级学校。")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("那、那不是大小姐高校吗！传说中“圣洁的百合与灿烂的樱花盛开的天国”……", "小怜")
	await novel_interface.show_text_only("这是某个经常宕机的破论坛外野，为讽刺御樱川高昂学费撰写的广告语。")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("你说什么？", "莉琉")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("没没没没！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("不过你这个蠢样，搞不好会成为学姐学妹们的……", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉轻轻一笑，并没有说出下文。")
	novel_interface.show_character("ren_battle","awkward")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_dark()
	novel_interface.show_2nd_character("liliu_uniform2","speak2",0.25)
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("会成为什么啊！？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("现在可不是好奇心发作的时间。\n总之明天，你就去乖乖报到。", "莉琉")
	await novel_interface.show_dialog("那里可没公立学校那么散漫。", "莉琉")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("就不能让我悠闲一点吗_(:3」∠)_")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("……啊对了，安妮怎么办？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("那丫头啊，可是很有趣的身世呢。", "莉琉")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("她……怎么了？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak2")
	await novel_interface.show_dialog("系统中关于安妮·巴斯的记录，只能追溯到七年以前，也就是她15岁的时候。", "莉琉")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("七年前是……她已经22岁了？！\n明明看起来跟我差不多大啊。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("是的，她现在的骨龄测定依然是15岁。", "莉琉")
	await novel_interface.show_dialog("但是这期间她究竟去了哪，为什么突然出现，目前为止没有人弄得清楚，包括她自己。", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……无论如何，我认为安妮不会是坏人。", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("这倒可以放心。\n毕竟就连SID里，还有她曾经的粉丝呢。", "莉琉")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("呃？！安妮是什么偶像吗？", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("……应该属于“多年前的明星”这类范畴吧。", "莉琉")
	await novel_interface.show_dialog("不过比起她以前的身份，我更中意现在她的特别之处。", "莉琉")
	await novel_interface.show_dialog("本来『魔女』的资料就少到让人头疼……真是意外的收获。", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("魔女……那又是什么？", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"speak2")
	await novel_interface.show_dialog("嗯……简单说，可以认为是因为感染了某种信息，而获得了一些类似『异质物』特性的人类。", "莉琉")
	await novel_interface.show_dialog("就像人们对目前的科学无法解释的『异质物』的奇异特性称呼为『神迹』。", "莉琉")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("在普通人看来，如果有人可以表达这种特性，简直可以称为『魔法』吧。", "莉琉")
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("ren_battle","normal1",0.25)
	await novel_interface.show_dialog("魔法……应该只是我们还不理解的科学吧……", "小怜")
	novel_interface.character_2nd_light()
	novel_interface.character_dark()
	await novel_interface.show_dialog("你想这样理解也没问题。", "莉琉")
	await novel_interface.hide_all_characters()
	novel_interface.change_background("res://assets/images/bg/Shot/burningPunish.png")
	await novel_interface.show_dialog("本来历史上有很多关于『魔女』的记载，但一直被当做迷信和传说。", "莉琉")
	await novel_interface.show_dialog("历史上欧洲人曾在三百多年的时间里，以『魔女』的名义处决了近十万名女性。", "莉琉")
	await novel_interface.show_dialog("『魔女狩猎』运动，历史课上有学……", "小怜")
	await novel_interface.show_dialog("虽然当时我只是当做无聊的考点，但仔细想来，的确是一场规模庞大到不正常的浩劫……", "莉琉")
	novel_interface.change_background("res://assets/images/bg/SID/hall.png")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("『异质物』被发现以来，各国都在重新审视那些传说的真实性。", "莉琉")
	await novel_interface.show_dialog("最近有传言说某些组织重新制造了魔女，并用于特务活动。", "莉琉")
	novel_interface.change_expression("speak2")
	await novel_interface.show_dialog("不过好在安妮能爽快的答应加入。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("加入什么？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("成为SID探员。", "莉琉")
	await novel_interface.show_dialog("从明天起，她就要开始替我办事了。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("那怎么行！SID探员的工作想想就知道太危险了！", "小怜")
	novel_interface.change_2nd_expression("wry_smile")
	await novel_interface.show_dialog("而且她和我一样才15岁，不能做什么探员吧……", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("哼哼，我们目前最小的探员只有13岁。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("13岁？！非法的吧！！\n那一定是非法的吧！！？", "小怜")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("以后有机会见到她你就不会这么想了。\n那孩子可远比你这个笨蛋要聪明得多。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sprite")
	await novel_interface.show_dialog("……哼", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("作为新丰洲市民，我当然知道现在各个学园都市虽然表面上停火，但都在暗中较量。")
	await novel_interface.show_text_only("而且埃癸斯的护盾对生化武器和渗透式的恐怖袭击是无效的。")
	await novel_interface.show_text_only("为了维护这座城市，可以想象莉琉与SID在暗中经历了多少殊死的激烈战斗。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("哦对了，安妮表面的身份，是和你一起入学的转学生。", "莉琉")
	await novel_interface.show_dialog("我给你们安排在同一个套间，制服和其他日常物\n品，一小时内都会送达。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("不要讨价还价。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("我明白……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我当然明白，这样没有什么不好。\n不，是比以前的生活会舒适太多了。")
	await novel_interface.show_text_only("只要让SID解决一切问题就好。\n只要继续浑浑噩噩地在贵族学校混学分就好。")
	await novel_interface.show_text_only("然后只要试着习惯这个新身体就好……吗？")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("……不。", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("嗯？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("就算什么也不明白，可我不想让安妮一个人面对这种危险。")
	await novel_interface.show_text_only("在相遇的那一刻，出现在我面前的安妮。\n虽然看似镇定，却透露出一丝惶恐。")
	await novel_interface.show_text_only("她其实……也很害怕吧？")
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("……莉琉姐，如果你不反对我这么称呼你…\n我也想帮忙！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","serious",0.25)
	await novel_interface.show_dialog("哈啊？！", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……我想…既然我有能力穿越那个飓风，应该也能在SID帮上点其他什么忙！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("那不是飓风，是时空相位波动……", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"shout")
	await novel_interface.show_dialog("总之，我不能让安妮独自面对危险。", "小怜")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("说不定，还能有机会找到变回男孩子的办法……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("…但是以你的体质，应该连SID的清洁人员都打不过。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","panic",0.25)
	await novel_interface.show_dialog("额……\n（你请了怎样的清洁工啊！扫地僧吗？！）", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……这样吧，让你尝试一下SID的学员训练，以后就算遇到什么危险，好歹能提升存活率。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("身份的话，就作为四级探员（候选）吧。", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("好的！我会努力的！", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（也好，看看能从这小家伙身上获取什么数据。）", "莉琉")

	print("=== 第二章第11话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
