# chapter2_ep24.gd - 第二章第24话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep24_script()

func play_script():
	pass

func chapter2_ep24_script():
	novel_interface.change_music("res://assets/audio/music/Shop.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/bedRoom.png")
	await novel_interface.show_text_only("回到公寓之后，一直处于睡梦中的伊露卡抓着我的衣服说什么也不放手。")
	await novel_interface.show_text_only("安妮和莉琉叫我转身不许偷看并组成人墙，把伊露卡的金属手甲和破损的外套脱下换成了普通的衣服") #换行问题
	await novel_interface.show_text_only("然后她们叫我以生命担保不会做什么奇怪的事情之后，才允许我把伊露卡抱回自己的房间。")
	await novel_interface.show_text_only("……现在伊露卡躺在我的床上，抓着我的衣服继续呼呼大睡，我只得陪坐在床边。")
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("小孩子这么黏人的嘛……\n好累啊~~", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("经过一晚的行动，我也四肢酸软，无力地瘫倒在一旁，无意中碰到了口袋里放着的那摞纸页。")
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("这是安妮所说的……『魔导书残页』？", "小怜")
	novel_interface.change_expression("stare")
	await novel_interface.show_dialog("刚才伊露卡好像也很想要呢，还用小动物似的眼神看着我……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我躺在床上又仔细看了看书页，还是一片混沌，根本无法识别上面的内容。")
	await novel_interface.show_text_only("在我想翻看其他页的时候，几张纸页从手中滑落在了伊露卡身上。")
	await novel_interface.show_text_only("接触到伊露卡的纸页突然激发出蓝色的光芒。")
	await novel_interface.show_text_only("大量记载着某种信息的符文涌出的同时，甚至连屋内的空气也震动起来。")
	await novel_interface.show_text_only("随后我手上的书页也好像被某种力量拉扯着全部飞到了伊露卡身上。")
	await novel_interface.show_text_only("在一阵夺目的强光之后，所有的一切消失不见了。")
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("这、这是——！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","normal")
	await novel_interface.show_dialog("探索开始，发现目标——\n巧克力……姐姐！", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","happy")
	await novel_interface.show_dialog("伊露卡？！你醒了？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡一把抱住我，与此同时大门在我的身后被用力地端开。")
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("喂，刚才的震动是怎么回事？\n……哇啦！你终于对伊露卡下手了吗？", "安妮")
	novel_interface.character_dark()
	await novel_interface.show_text_only("安妮用一种古怪的眼神看着我。")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("不是你想的那样啊，请听我解释！", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_left(-0.25)
	novel_interface.show_character("iluka_normal","normal",0.25)
	await novel_interface.show_dialog("能量，充满。\n搜索……未找到。", "伊露卡")
	novel_interface.character_2nd_light(0.35,"worry")
	novel_interface.character_dark()
	await novel_interface.show_dialog("怎么了，你是要找谁吗？", "小怜")
	novel_interface.character_2nd_dark()
	novel_interface.character_light(0.35,"sleepy")
	await novel_interface.show_dialog("……裁判所，管理员。", "伊露卡")
	novel_interface.character_2nd_light(0.35,"perspire1")
	novel_interface.character_dark()
	await novel_interface.show_dialog("裁判所……是什么啊？\n总之，我们先找莉琉来想想对策吧。", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("liliu_research","shock")
	await novel_interface.show_dialog("裁判所……你可真会给我找麻烦，居然把『教团』的人带回来了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("哎？！那是什么？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","normal")
	await novel_interface.show_dialog("为了调查魔女的记录，我也在文献中查到了一些奇怪的地下组织，最古老的就属『教团』。", "莉琉")
	novel_interface.change_expression("smile")
	await novel_interface.show_dialog("但教团似乎分裂成了好几个派系，『裁判所』就是教团的一支。", "莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("那个派系是几百年前分裂出来的，成天叫嚣着要消灭一切魔女，是当年『魔女狩猎』活动的主力。", "莉琉")
	novel_interface.change_expression("angry")
	await novel_interface.show_dialog("我最讨厌这种不科学的团体扯上关系了。", "莉琉")
	novel_interface.change_expression("happy")
	await novel_interface.show_dialog("之前只是想给伊露卡安排到新丰洲的保育学校……不过既然如此，看来不能轻易地放走了~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("莉琉其实是另有目的吧，不要私下里做什么研究试验啊……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("在你心中，我就那么坏吗？", "莉琉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉弹了一下我的脑袋。\n伊露卡鼓着嘴，有些不高兴地盯着莉琉。")
	novel_interface.show_character("iluka_normal","unhappy")
	await novel_interface.show_dialog("目标判定，危险指数，极高。", "伊露卡")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","normal",0.25)
	await novel_interface.show_dialog("……这小鬼。", "莉琉")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("对了，伊露卡，那个叫雅各的男人，究竟要让你执行什么任务？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡皱着眉头，慢慢地回忆起来——")
	novel_interface.show_character("iluka_normal","worry")
	await novel_interface.show_dialog("一，清理女巫，完成\n二，获取手稿，失败。", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("手稿？不是在小怜那里吗？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_normal","worry")
	await novel_interface.show_dialog("搜索……状态异常\n手稿……已消化", "伊露卡")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("消化是说……已经与你合为一体了？\n还是说那些手稿本来就是伊露卡魔导书的一部分？", "小怜")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("那管理员不许你消化……\n是怕你能力变强无法控制吧？", "小怜")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("居然能把伊露卡的话翻译出这么详细的内容，小怜你果然超厉害的！", "安妮")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("等等，伊露卡的魔导书\n也就是说……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("果然这小丫头也是『魔女』吗？", "莉琉")
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉立刻上前尝试捏伊露卡的脸，但被伊露卡小心地躲开。")
	novel_interface.character_light(0.35,"smile")
	await novel_interface.show_dialog("早听说有组织试图制造并控制魔女，真是什么年代都有野心家想拥有超级士兵啊。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("为什么你们都对魔女很熟悉的样子……就我一个还搞不清楚，究竟怎么样才会变成魔女啊？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("嗯，一开始我也不太清楚呢。只记得那时候，稀里糊涂的看了那本书。", "安妮")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("看的时候感觉大脑发麻，越往后越难懂，之后就能感觉到身体被某种力量侵染了。", "安妮")
	novel_interface.change_expression("gratified")
	await novel_interface.show_dialog("后来有一天，我默念了其中的一句咒语，然后就被卷入了那个异次元空间……", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","smile",0.25)
	await novel_interface.show_dialog("空间嘛……你们俩到达变电所的时候，卫星侦测到那里的时空相位波动已经消失了。", "莉琉")
	novel_interface.character_light(0.35,"perspire")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我就说没有之前在异变区域的那种感觉呢！", "安妮")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("你所说的异变区域，古代记载魔女的文献上称为\n『魔女之茧』。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,false)
	await novel_interface.show_dialog("是人类转变为魔女时形成的，外人无法打破也不可能进入的结界，性质与异质物造成的空间很像吧？", "莉琉")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("而在变电所的波动消失的几乎同时，卫星侦测到到了光学信号——", "莉琉")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("就是与你们开战的家伙，出现了。", "莉琉")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("仔细想想，『魔女之茧』这个名字…那些家伙在茧消失的同时出现，就好像被孵化出来的一样。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("iluka_normal","unhappy")
	await novel_interface.show_dialog("女巫，消灭！", "伊露卡")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","solemn")
	await novel_interface.show_dialog("所以女巫果然是无法承受魔导书上的信息，而丧失心智的人吧！？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","worry",0.25)
	await novel_interface.show_dialog("她们应该就是普通的少女，因为无法承载手稿上的魔法，阅读过程中遭到了力量的反噬。", "安妮")
	await novel_interface.show_dialog("引起空间巨变同时，连自己也变成了……\n被称为“女巫”的怪物。", "安妮")
	await novel_interface.hide_all_characters()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("很多古书上也有这样的记载，那些关于魔法的信息或许知道的越多，越会让人不可逆的陷入疯狂。", "莉琉")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("掌握魔法又失去心智的女巫会造成巨大的破坏，如果真的是这样的话……", "莉琉")
	await novel_interface.show_dialog("这或许这是欧洲的『魔女狩猎』运动持续了那么久的原因之一。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","perspire1",0.25)
	await novel_interface.show_dialog("什么啊，这根本就像病毒感染一样啊。", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"angry")
	await novel_interface.show_dialog("从目前的信息推断，伊露卡的管理员把歼灭女巫作为第一目标，进而想要回收魔导书的残页。", "莉琉")
	await novel_interface.show_dialog("但并不允许伊露卡使用魔导书……或许是想以此制造更多的魔女。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("可是我也看了伊露卡的魔导书，却一个单词都读不出来。这和我本来是男生有关吗？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("iluka_normal","worry",0.25)
	await novel_interface.show_dialog("……男生？", "伊露卡")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("伊露卡有些紧张，向后退了两步，露出疑惑的表情")
	novel_interface.show_character("ren_battle","wail")
	await novel_interface.show_dialog("呃，伊露卡，这件事情先放到一边\n不要在意……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","uneasy")
	await novel_interface.show_dialog("我就可以读呀，小怜不会是笨蛋吧？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("比起这个，我更想知道你到底用了什么办法，能轻易进入『魔女之茧』。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("我也不想啊！每次进去都有人想打我……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","speak")
	await novel_interface.show_dialog("——这种行为已经跨越了多层维度，目前无法从科学的角度解释清楚。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("如果能解释的话，那我首先想知道的，是为什么我会变成女生啊！")
	novel_interface.show_character("anne_battle","smile")
	await novel_interface.show_dialog("嘿嘿，不要烦恼啦，现在搞不明白的事，总有一天会知道原因的嘛！", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","wry_smile")
	await novel_interface.show_dialog("你还真是乐观啊……", "小怜")

	print("=== 第二章第24话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
