# chapter2_ep14.gd - 第二章第14话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep14_script()

func play_script():
	pass

func chapter2_ep14_script():
	novel_interface.change_music("res://assets/audio/music/step by step.mp3")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("但是我想变回男生啊……\n究竟怎么做才行……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("嘛……索性就这么当女孩子就好了啊~", "莉琉")
	novel_interface.character_light(0.35,"awkward")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("诶——？？\n才！不！要！", "小怜")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal")
	await novel_interface.show_dialog("就像你说的，或许这座城市扭转了毁灭的命运，上千万的生命也因此复活……", "莉琉")
	await novel_interface.show_dialog("这种程度的奇迹背后，总有某种代价吧？", "莉琉")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("如果代价……只是你变成这个样子呢？", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("怎么会……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","smile")
	await novel_interface.show_dialog("另外……\n你已经15岁了吧？", "莉琉")
	novel_interface.change_expression("speak")
	await novel_interface.show_dialog("这个年纪的女孩子\n至少……也应该穿内衣吧？", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","shy_left",0.25)
	await novel_interface.show_dialog("哈？", "小怜")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你还在成长期，今后说不定越长越大……", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_dialog("欸——？？", "小怜")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不穿的话，会出问题喔。\n比如跑动的时候……", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"shy")
	await novel_interface.show_dialog("内、内衣该不会是……？！", "小怜")
	novel_interface.character_light(0.35,"speak")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("对啊，我觉得你应该适合那种可爱的少女风格吧？\n毕竟脸蛋是可爱类型的~", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_dialog("绝对不要！！\n我、我可是男生啊！！", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("而且话说你的坐姿啊……\n真是意外的大胆呢~", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"blush")
	await novel_interface.show_dialog("我我我我……\n我要去卫生间了！！", "小怜")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"smile")
	await novel_interface.show_dialog("哎呀——\n那孩子……真是好捉弄呢~", "莉琉")
	await novel_interface.show_dialog("看来以后不会无聊了~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.change_background("res://assets/images/bg/APT/washingRoom.png")
	await novel_interface.show_text_only("我看着镜中的自己，回想着刚才的对话，身体靠墙缓缓的蹲了下去。")
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_dialog("果然，难以相信啊……", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("那种东西……绝对不想穿啊！！", "小怜")
	await novel_interface.show_dialog("作为男人的我……\n感觉有某样重要的东西……要离我远去了！", "小怜")
	novel_interface.change_expression("shy_left")
	await novel_interface.show_dialog("而且，在买那种东西的地方被人看到的话……\n不行不行！绝对不可以！", "小怜")
	await novel_interface.show_dialog("（如果那样做的话……）\n（那就真的是……变态了！！！）", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("我才不想做变态啊！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_research","happy")
	await novel_interface.show_dialog("哦？你还蹲在这哭啊\n已经按你的胸围准备好了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("诶？", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","smile",0.25)
	await novel_interface.show_dialog("放在你的房间，就当送你的礼物了~", "莉琉")
	novel_interface.character_light(0.35,"sob")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("不用！\n我用创可贴就好了！！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("这孩子……到底是是纯洁还是H啊~", "莉琉")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog("虽然用胶布状的创可贴可能……更加有趣。", "莉琉")
	novel_interface.change_2nd_expression("happy")
	await novel_interface.show_dialog("难道你比较喜欢撕下来创可贴那一瞬的痛感吗？", "莉琉")
	await novel_interface.show_dialog("可惜这里只有喷雾型的创可贴哦~", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0)
	await novel_interface.show_dialog("你是故意的吧！！\n呜……可恶！！", "小怜")
	await novel_interface.hide_character()
	novel_interface.change_music("res://assets/audio/music/Chaostic Daily.mp3")
	novel_interface.show_character("ren_nude","indignation")
	await novel_interface.show_dialog("切，穿就穿~！\n堂堂男子汉有什么可害羞的！！", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("…………")
	novel_interface.character_light(0.35,"shock")
	await novel_interface.show_dialog("……嗯？咦？\n这个……好难啊……", "小怜")
	novel_interface.change_expression("timid")
	await novel_interface.show_dialog("……嗯嗯", "小怜")
	novel_interface.character_dark()
	await novel_interface.show_text_only("『啪嗒』")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("liliu_research","happy",0.25)
	await novel_interface.show_dialog("帮你扣好了~", "莉琉")
	novel_interface.character_light(0.35,"shock")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("莉琉？！\n你、你怎么进来的？！！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"smile")
	await novel_interface.show_dialog("好心帮帮你嘛~\n话说制服的长筒袜，你一个人能行吗？", "莉琉")
	novel_interface.character_light(0.35,"uneasy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊！？不就是几双袜子吗，有什么不行的！\n我还是自己来吧！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"speak")
	await novel_interface.show_dialog("那裙子呢？", "莉琉")
	novel_interface.character_light(0.35,"shock")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("裙子还是会的……我自己穿就好……\n莉琉你快出去！！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"happy")
	await novel_interface.show_dialog("咦~你居然会穿裙子啊，还真了不起呢。", "莉琉")
	novel_interface.character_light(0.35,"shame")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("裙子又不用把手伸到后面扣扣子，有什么难的！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("噗，好吧~\n一会我就来看看你穿成什么样子。", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"indignation")
	await novel_interface.show_dialog("可恶……太小看我了，莉琉那家伙！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_text_only("一段时间后……")
	novel_interface.change_background("res://assets/images/bg/APT/livingRoom.png")
	novel_interface.show_character("ren_uniform","happy")
	await novel_interface.show_dialog("莉琉！我穿好了！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_research","shock",0.25)
	await novel_interface.show_dialog("你确定？", "莉琉")
	novel_interface.character_light(0.35,"sprite")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("有什么好确定的！这不好好的穿着呢么！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("你的拉链……放在哪啊？", "莉琉")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("前面啊！方便上厕所嘛！", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("嗯……你现在用什么上厕所？", "莉琉")
	novel_interface.character_light(0.35,"wail")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("呃……", "小怜")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("这……这有什么关系嘛！反正……", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("噗……拉链是在旁边的\n你去照照镜子吧~", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"shy")
	await novel_interface.show_dialog("旁边就旁边……\n……", "小怜")
	novel_interface.change_expression("sob")
	await novel_interface.show_dialog("为什么女生的衣服这么难穿啊！！", "小怜")

	print("=== 第二章第14话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
