# chapter2_ep16.gd - 第二章第16话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep16_script()

func play_script():
	pass

func chapter2_ep16_script():
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	await novel_interface.show_text_only("爱衣正捧着报告书核对荧幕上跳动的数据，房间内不时传出她窃笑的声音。")
	await novel_interface.show_text_only("莉琉从爱衣身后抽走了文件，打量着上面的内容。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("体检的结果如何？把你高兴成这样。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","wink",0.25)
	await novel_interface.show_dialog("啊——真是太美妙了！！", "爱衣")
	novel_interface.change_2nd_expression("blush_think")
	await novel_interface.show_dialog("身体是女生，灵魂却是男生……『播磨脑研』的家伙要是知道了，拼命也会提交实验申请把她抢走吧", "爱衣")
	novel_interface.character_light(0.35,"normal1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("所以要严格保密，明白了吗。\n找到什么线索了？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal")
	await novel_interface.show_dialog("她们端粒检测的年龄确实都是15岁，但安妮软组织中铯-137的含量只有当前人均值的四分之一。", "爱衣")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("亏你能想到这种方法……\n所以『七年战争』她最多只经历了一半？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"stare")
	await novel_interface.show_dialog("除非战争后几年她一直呆在密封舱里。", "爱衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("我知道了。\n另一个呢？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"think")
	await novel_interface.show_dialog("至于小怜……她肌肉组织里检测出的含量不到均值的两百分之一，比新生儿从母继承的还要低。", "爱衣")
	novel_interface.character_light(0.35,"serious")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("……所以，是新生成的身体吗？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal")
	await novel_interface.show_dialog("这才是最有趣的地方——她的体内有包括天花在内的很多已经灭绝的病毒抗体。", "爱衣")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("——？！", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("放心~脊髓没有病毒残留。", "爱衣")
	novel_interface.change_expression("normal")
	await novel_interface.show_dialog("我粗略的排查了一下，小怜的免疫系统足迹应该在最近几百年内，没有中世纪以前的病毒抗体。", "爱衣")
	await novel_interface.show_dialog("不过我想申请用她的白细胞，培养008、217和\n742号病毒试试看……", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("……我派你去做校医，可不是为了满足你这种奇怪的嗜好。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ai","think",0.25)
	await novel_interface.show_dialog("好啦好啦我明白~\n要观察她们对吧？", "爱衣")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("她们和『洛斯金杯』的消失可能有关联……\n我怀疑有些细节，她们依旧没有说出来。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"normal")
	await novel_interface.show_dialog("关起来审问一下不就好了嘛。", "爱衣")
	novel_interface.change_2nd_expression("stare")
	await novel_interface.show_dialog("需要帮忙吗？今天体检用的装置稍微改造一下就是很好的审问道具哦~", "爱衣")
	await novel_interface.hide_2nd_character()
	await novel_interface.show_text_only("爱衣露出探究的兴奋神色，莉琉卷起报告，敲了她一下。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("你做好监视就行，有任何情况都马上向我汇报。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（那家伙已经注意到了，恐怕SID内部早就……）", "莉琉")
	await novel_interface.show_dialog("（放在学校里的话，至少可以降低好奇心）\n（还能顺便牵制一下他的小动作……）", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","blush_think")
	await novel_interface.show_dialog("不用你说，小怜的身体变化，我会全~部记录下来的！", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("……你也稍微给我收敛一点。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("嘿嘿嘿，放心吧。\n毕竟一下子榨干净就不好玩了嘛。", "爱衣")

	print("=== 第二章第16话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
