# chapter2_ep03.gd - 第二章第3话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep03_script()

func play_script():
	pass

func chapter2_ep03_script():
	var player_name = GameConfig.player_name
	novel_interface.change_music("res://assets/audio/music/Hard Stage.mp3")
	await novel_interface.show_text_only("我和安妮在特工们的“护送”下，登上了一辆黑色轿车。")
	novel_interface.change_background("res://assets/images/bg/Shot/incarView2.png")
	await novel_interface.show_text_only("封闭的车厢令人窒息。")
	await novel_interface.show_text_only("内心惴惴不安的我，蜷起身抱着自己的双膝，不知应该做些什么。")
	await novel_interface.show_text_only("安妮轻轻地靠在我的身旁，稍稍让我有些放松。")
	await novel_interface.show_dialog("SID……那个『秘密情报局』到底是什么呀？\n你一听到就这么紧张。", "安妮")
	await novel_interface.show_dialog("你真的不知道吗？\nSID是元老院直属的情报机构。", player_name)
	await novel_interface.show_dialog("虽然有人说第五学园都市能一直保持中立，SID的功劳比『埃癸斯』的防护系统还要大……", player_name)
	await novel_interface.show_dialog("但更多是“某人被SID带走从此人间蒸发”的都市传说，总之是很恐怖的间谍机关。", player_name)
	await novel_interface.show_dialog("哦……那学园都市是什么？", "安妮")
	await novel_interface.show_dialog("（喂喂……这家伙完全没有常识吗？）", player_name)
	await novel_interface.show_text_only("安妮看着我不可思议的表情，只是露出了轻松的笑容。")
	await novel_interface.show_dialog("总之我们不会有什么问题的啦！", "安妮")
	await novel_interface.show_dialog("因为，你是特殊的嘛。", "安妮")
	await novel_interface.show_dialog("……", player_name)
	await novel_interface.show_text_only("真奇怪，安妮轻松说出的不着边际的话语让我焦虑的情绪一下子镇定了不少。")
	await novel_interface.show_text_only("似乎我们被SID带走这件事也没那么可怕了……")
	await novel_interface.show_text_only("（不不不，还是很可怕的！）")
	novel_interface.change_background("res://assets/images/bg/Shot/incarView1.png")
	await novel_interface.show_text_only("我们的车来到了城市的繁华商业区，从一处不起眼的地下停车场直接驶入了泊车电梯。")
	await novel_interface.show_text_only("探员汇报了一下，电梯开始动了起来。")
	await novel_interface.show_text_only("能感觉到这台电梯速度很快，进行了数次长距离的下降，期间居然还有几次横向移动。")
	await novel_interface.show_dialog("（这片商业区的地下居然有如此巨大的迷宫般的构造嘛……）", player_name)
	await novel_interface.show_text_only("关于SID的总部有各种各样的传说，有爆料说地点在新丰洲东南郊，整栋设施都用光学伪装包裹。")
	await novel_interface.show_text_only("对于一个在系统上“不存在”的建筑，营销媒体只要能吸引点击怎么瞎编都可以。")
	await novel_interface.show_text_only("而现在我踏入的地方，正是“不存在”的机关的核心区域。")
	await novel_interface.show_dialog("（希望我不会在这里变成“不存在”……）", player_name)
	await novel_interface.hide_background_with_fade()
	await novel_interface.show_text_only("下车之后，正对着我们的只有一条金属甲板包裹的科技感十足的走廊，装置风格有一丝禁欲色彩。")
	await novel_interface.show_text_only("我们刚走几步，电梯门就自动关闭，听到电梯迅速远去的声音，幽暗的走廊变得严肃而压抑。")
	await novel_interface.show_text_only("我的心也开始下沉……")
	novel_interface.change_background("res://assets/images/bg/SID/hearingRoom.png")
	await novel_interface.show_text_only("我们顺着走廊径直来到了一个明亮而封闭的房间。")
	await novel_interface.show_text_only("看上去像是某种审讯室，但并没有桌椅，一侧的墙面是一块巨大的玻璃。")
	await novel_interface.show_text_only("还没等我转身观察——")
	novel_interface.show_character("ren_battle","awkward")
	await novel_interface.show_dialog("呜啊——！", player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("突然有人从背后用力揽住了我的腰。")
	novel_interface.character_light(0.35,"sob")
	await novel_interface.show_dialog("啊啊诶痛痛痛痛痛——！！！！！", player_name)
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我的身体马上要失去平衡的时候，后脑勺靠在了一个柔软又坚实的似曾相识的物体上。")
	await novel_interface.show_dialog("嗯……你这种水平的核心力量，就算是间谍也达不到可以出外勤的程度。", "女性的声音")
	await novel_interface.show_dialog("刚才我还以为身体扫描的数据出错了，才来亲自确认一下。", "女性的声音")
	await novel_interface.show_dialog("手感倒是不错……", "女性的声音")
	await novel_interface.show_text_only("一个有点熟悉的女性声音从我背后传来。")
	await novel_interface.show_text_only("对方松手，我惊魂未定的回头\n正前方面对的是——")
	novel_interface.show_character("ren_battle","blush")
	await novel_interface.show_dialog("（诶？？好、好大！！！！）", player_name)
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_expression("awkward")
	await novel_interface.show_dialog("莉、莉琉小姐！？", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("anne_battle","worry")
	await novel_interface.show_dialog("嗯？……你认识她嘛？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("哦？这么快就透露你能识别对方情报机构的人员。看来你没打算隐藏身份嘛……", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","sob",0.25)
	await novel_interface.show_dialog("（啊！不好，顺口就叫出来了……）", player_name)
	novel_interface.character_2nd_dark()
	await novel_interface.show_text_only("虽然难以置信，但眼前一身军装的人，正是梦里在研究中心遇到的那个姐姐。")
	await novel_interface.show_text_only("高挑的身材、火红的头发、抖S的表情……")
	novel_interface.character_light(0.35,"speak2")
	await novel_interface.show_dialog("那么接下来，你要诚实的回答我的问题。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("别想用什么意外和巧合之类的借口蒙混过关。", "莉琉")
	await novel_interface.show_dialog("审讯技巧也算是我的特长之一。\n我可不会对你可爱的小脸蛋手下留情的~", "莉琉")
	await novel_interface.hide_character()
	novel_interface.character_2nd_move_right(0,0.3,true,"panic")
	await novel_interface.show_text_only("这种不容质疑又喜欢戏弄人的恶劣态度，还有那自信而略带嘲讽的眼神……")
	await novel_interface.show_text_only("她全名叫什么来着？\n对了，是——")
	await novel_interface.hide_2nd_character()
	novel_interface.show_character("liliu_uniform2","speak2")
	await novel_interface.show_dialog("没错，我就是SID的主管，莉琉·冯·布劳恩。", "莉琉")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","awkward",0.25)
	await novel_interface.show_text_only("就是她！！！")
	novel_interface.change_2nd_expression("perspire1")
	await novel_interface.show_text_only("等等，SID主管？\n她不是首席科学家吗？！")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_text_only("不过仔细看她衣服的样式和肩章，确实像是很大的官……")
	novel_interface.change_2nd_expression("shy")
	await novel_interface.show_text_only("丝袜和高跟鞋倒是和昨天一模一样。")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("喂？小丫头，你眼睛在看哪呢？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"sob")
	await novel_interface.show_dialog("哇！没有！\n对不起！莉琉大人！", player_name)
	novel_interface.character_light(0.35,"speak2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("还敢开小差，真是好胆量啊~", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("听说你向这个蓝色双马尾灌输了不少有关SID的恐怖传言？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"awkward")
	await novel_interface.show_text_only("莉琉饶有兴致的把玩着手中的教鞭，我紧张的咽了咽口水。")
	novel_interface.character_light(0.35,"normal2")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你猜……\n那些传闻有多少是真的？", "莉琉")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"wail")
	await novel_interface.show_dialog("噫！对、对不起！", player_name)
	await novel_interface.hide_all_characters()
	novel_interface.show_character("anne_battle","perspire")
	await novel_interface.show_dialog("蓝、蓝色双马尾……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("既然知道害怕，就从你的身份开始，如实交待清楚吧。", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉打开手持终端，审讯室的墙面上立刻出现了投影")
	await novel_interface.show_text_only("上面是从监控视频中调取的，不同角度的我的照\n片，而面部分析结果显示——")
	await novel_interface.show_text_only("『未识别特征匹配人员。』")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("没有入境记录，『埃癸斯』系统无法识别。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("要不是你身体素质太差，可以立刻作为潜入新丰洲的间谍或者恐怖分子处理了。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","shy")
	await novel_interface.show_text_only("我下意识的揉了揉软软的肚子，有点不好意思。")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_battle","frustrate",0.25)
	await novel_interface.show_dialog(player_name+"，这个姐姐好像比刚才遇到的敌人还可怕……", "安妮")
	novel_interface.character_light(0.35,"wry_smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("（是啊，跟她说谎马上会被看穿的样子……）", player_name)
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,false,"sob")
	await novel_interface.show_dialog("（还是老实交代吧！啊啊啊！不管了！）", player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("我叫"+player_name+"，该从哪里说起才好呢…", player_name)
	await novel_interface.show_dialog("事情的经过有点复杂，我自己也很混乱。", player_name)
	await novel_interface.show_dialog("你听了也不一定会相信……", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("怎么啰里啰唆的，我自己会判断！", "莉琉")
	novel_interface.change_music("res://assets/audio/music/Witch's Confession.mp3")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","normal1")
	await novel_interface.show_dialog("……我……做了个梦。", player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("因为要完成户外教学的报告，我去研究中心听讲座\n……是在昨天闭馆之前才赶到的。", player_name)
	await novel_interface.show_dialog("我在那遇到了你，你说那里被人入侵了……", player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉像是听到了什么笑话一般。")
	novel_interface.character_move_left(-0.25,0.3,false)
	novel_interface.show_2nd_character("liliu_uniform2","speak2",0.25)
	await novel_interface.show_dialog("你是说，在梦里见过我？", "莉琉")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("是的，的确是你。\n你还不由分说的把我拖到墙角……", player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("啊对了，你好像是元老院评定的SS级科学家……莉琉·冯·布劳恩博士，没错吧？", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("……确实我就是。", "莉琉")
	novel_interface.change_2nd_expression("normal1")
	await novel_interface.show_dialog("不过，这种信息本来就是公开的，对新丰洲科学院有一定了解的人都知道。", "莉琉")
	await novel_interface.show_dialog("……也罢\n然后呢？", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("然后你放倒了一个劫匪并抢了一把手枪，叫我待在原地等救援，就自己去劫持现场了……", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("劫持现场？\n是什么位置？", "莉琉")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("嗯，你说是『会议厅』。", player_name)
	await novel_interface.show_dialog("当时要举行一个讲座，你本应是主讲人。", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("……讲座……主讲人", "莉琉")
	novel_interface.change_2nd_expression("serious")
	await novel_interface.show_dialog("（……难道是沃尔夫冈那个老家伙给我安排的关于洛斯金杯的义务讲座？）", "莉琉")
	await novel_interface.show_dialog("（不过应该被临时取消了，她怎么会知道？）", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那个……莉琉小姐？", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal2")
	await novel_interface.show_dialog("嗯，没事，继续说。", "莉琉")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("然后来了几个带着枪的蒙面人，我逃走时摔到了楼下，挣扎着爬到一块石板的阴影里躲了起来……", player_name)
	await novel_interface.show_dialog("对不起，这一段我记不太清楚了……", player_name)
	await novel_interface.show_dialog("然后我似乎晕过去了，醒过来的时候，就发现……", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("发现什么？", "莉琉")
	await novel_interface.hide_2nd_character()
	novel_interface.character_move_right(0,0.3,true,"normal1")
	await novel_interface.show_dialog("四处都是浓烟和大火", player_name)
	await novel_interface.show_dialog("研究中心和周围的建筑变成了一片废墟……", player_name)
	await novel_interface.show_dialog("空气里有一股刺鼻的味道。", player_name)
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("还有厚重的咸味，让人舌根发涩……", player_name)
	await novel_interface.show_dialog("所有人都变成了石像", player_name)
	await novel_interface.show_dialog("不，不是石头，是盐。", player_name)
	novel_interface.change_expression("solemn")
	await novel_interface.show_dialog("我看到一个发光的东西飘在半空", player_name)
	await novel_interface.show_dialog("明明是那样地狱般的景象\n却能感到一种异样的宁静……", player_name)
	await novel_interface.show_dialog("似乎有什么在回应我……", player_name)
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("然后我的记忆就模糊了，应该是有一道光——", player_name)
	await novel_interface.show_dialog("嗯……然后梦就到此为止了。", player_name)
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("等我回过神来，发现躺在自己房间的床上，时间已经是早上了。", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("只是……梦吗……？", "莉琉")
	await novel_interface.show_dialog("这么强烈的嗅觉记忆，好像你真的在现场一样……", "莉琉")
	await novel_interface.show_dialog("（如果“刺鼻的味道”是指硫磺的话……）\n（像是《创世纪》中所多玛和蛾摩拉毁灭的方式）", "莉琉")

	print("=== 第二章第3话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
