# chapter2_ep08.gd - 第二章第8话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chapter2_ep08_script()

func play_script():
	pass

func chapter2_ep08_script():
	var player_name = GameConfig.player_name
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/opsRoom.png")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("安妮已经安置到隔壁房间了，有些事情我必须单独和你讲。", "莉琉")
	await novel_interface.show_dialog("我刚得到确认的消息。", "莉琉")
	await novel_interface.show_dialog("从今天早上开始，多个主要城市都出现了大规模的时空异变……", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("已知受影响的地区包括：华云宫城、纽摩利达斯、马萨达堡、萨蒙顿、新丰洲和莱博娜群岛。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","serious")
	await novel_interface.show_dialog("那岂不是……\n六大学园都市全都……？！", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("没错，现在全世界都盯着这件事，影响程度远超预期。", "莉琉")
	await novel_interface.show_dialog("我觉得，或许有一种可能……", "莉琉")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_dialog("你描述的你在梦中经历的一切：袭击研究中心的恐怖分子、化为废墟的城市……", "莉琉")
	await novel_interface.show_dialog("……这些可能都确实发生过。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("怎…怎么可能？！", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","speak")
	await novel_interface.show_dialog("虽然没有确切的证据，不过今早，一场超大规模的次元扭曲很可能已经发生。", "莉琉")
	await novel_interface.show_dialog("SID『真实视域』卫星同时也侦测到了超乎寻常的杂讯爆发。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("这么说你也许更容易理解：新丰洲市确实曾经一度毁灭，但某种力量扭转了这个现实……", "莉琉")
	await novel_interface.show_dialog("并且这种力量似乎也和你身体的变化，以及遭遇怪异敌人的袭击有关。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("当然，这还是我的假说。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","panic")
	await novel_interface.show_dialog("这想法……会不会太大胆了些……", player_name)
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("因为今天的事件，现在其他五个学园都市都在给元老院施加压力，希望进行入境调查。", "莉琉")
	await novel_interface.show_dialog("而你与这次件事的关联一旦暴露，恐怕就不止被研究机构带走那么简单了……", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("所有情报组织的特工都会把你标记为关键目标。", "莉琉")
	await novel_interface.show_dialog("不算潜伏的特工，单今天用假身份进入新丰洲的各国情报人员就超过一百人。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("你知道的这么清楚？\n为什么不阻止他们？", player_name)
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("哼，与其逼他们换新面孔，现在我在暗中可以更好的掌握局面。", "莉琉")
	novel_interface.change_2nd_expression("speak")
	await novel_interface.show_dialog(player_name+"，这一点你必须清楚，只要你还是女孩的身体，就不可能回到原来的生活。", "莉琉")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("不过最早发现你的是我们SID，未尝不是一种幸\n运。", "莉琉")
	novel_interface.character_light(0.35,"upset")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("一夜之间变成女孩子这种事……\n我该对同学和朋友们怎么说才好……", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light()
	await novel_interface.show_dialog("嗯…你不担心你的父母？", "莉琉")
	novel_interface.character_light(0.35,"gratified")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("在我小时候妈妈就去世了\n爸爸……也已经失踪好多年……", player_name)
	await novel_interface.show_dialog("我在12岁之前一直住在寄宿学校。", player_name)
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"normal1")
	await novel_interface.show_dialog("（……大猩猩主持的战后保育计划，还是帮到了一些小朋友啊）", "莉琉")
	novel_interface.change_2nd_expression("normal2")
	await novel_interface.show_dialog("嗯，也算吃过些苦了。\n不过，身份转换的问题你倒是用不着担心。", "莉琉")
	novel_interface.character_light(0.35,"worry")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("身份……转换？", player_name)
	novel_interface.character_dark()
	await novel_interface.show_text_only("莉琉脸上露出了一抹不妙的笑容……")

	print("=== 第二章第8话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
