# chaoscalculus_ep01.gd - 混沌演算篇第1话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chaoscalculus_ep01_script()

func play_script():
	pass

func chaoscalculus_ep01_script():
	novel_interface.change_background("res://assets/images/bg/Baizhu/Subjective_Validation1.png")
	await novel_interface.show_text_only("你是否曾有过这样的体验——")
	await novel_interface.show_text_only("睡梦中，突然意识到自己正在做梦。")
	await novel_interface.show_text_only("因为某个线索或契机，你猛然发觉周围的一切都是不真实的。")
	await novel_interface.show_text_only("心理学家称这种状态为清醒梦（lucid dream）。")
	await novel_interface.show_text_only("有人在发觉后会想尽快脱离梦境，有人却认为那是难得的神性体验。")
	await novel_interface.show_text_only("更有传言认为，爱因斯坦和费曼都曾在清醒梦中得到过“让他们更加接近真理的”灵感和启示。")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("但当醒来之后，回想刚才的一切，不知哪部分会让你更加在意——")
	await novel_interface.show_text_only("是梦境中光怪陆离的情节……")
	novel_interface.show_background("res://assets/images/bg/Baizhu/Subjective_Validation2.png")
	await novel_interface.show_text_only("还是在顿悟前一直坦然接受那些情节的…你自己？")
	await novel_interface.hide_background()
	novel_interface.change_music("res://assets/audio/music/Sonar.mp3")
	await novel_interface.show_text_only("……")
	await novel_interface.show_dialog("命运会强迫每个人都对它保持谦卑……","？？")
	await novel_interface.show_dialog("就像薪柴般的凡人，有时却不得不承受天命吗……","？？")
	novel_interface.show_background("res://assets/images/bg/chaoscalculus/BG_Baizhu_Deepsea.png")
	await novel_interface.show_text_only("（谁！？）")
	await novel_interface.show_text_only("嗤——")
	await novel_interface.show_text_only("随着某种设备启动的声音，大量气体被排出。")
	await novel_interface.show_text_only("（这里……是哪……）")
	await novel_interface.show_text_only("（我……死了吗？）")
	await novel_interface.show_text_only("（好难受……）")
	await novel_interface.show_text_only("肺里似乎充满了液体，如灼烧般疼痛，却无法咳出来。")
	await novel_interface.show_text_only("我的身体似乎正在漆黑的液体中缓慢上浮，被封闭许久的神经慢慢开始恢复了知觉——")
	await novel_interface.show_text_only("先是颈部的酸胀感，顺着脊椎一直蔓延到背部、腰部，接着好像每个关节都开始剧烈膨胀。")
	await novel_interface.show_text_only("这种剧痛使我想要挣扎着逃离这里，可身体却完全无法动弹。")
	await novel_interface.show_text_only("（上面……有光？）")
	await novel_interface.show_text_only("忽然，随着喉头蠕动，植物神经让我无意识的做出了吞咽动作。")
	await novel_interface.show_text_only("看着自己依然僵硬的手臂，我感觉到下面水体中某种巨大的生物正在慢慢逼近……")
	await novel_interface.show_text_only("（喂喂……给我动起来啊！）")
	await novel_interface.show_text_only("手指忽然不受控制的抽动了一下——")
	await novel_interface.show_text_only("——喂！！！！")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("喂——！")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_background("res://assets/images/bg/chaoscalculus/BG_Baizhu_Outdoorcafe.png")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("欸……啊，啊啊！？","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("哈，小怜怎么又睡着了？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("突然被熟悉的声音叫醒，我下意识的擦了擦嘴角。")
	await novel_interface.show_text_only("这是上次在物理课睡着被老师点名叫起来之后养成的条件反射。")
	novel_interface.show_character("ren_uniform","shy_left")
	await novel_interface.show_dialog("（在那种学校当着全班同学的面流口水简直太羞耻了！）","小怜")
	await novel_interface.show_dialog("（还、还好这次没有……）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("iluka_uniform","hungry")
	await novel_interface.show_dialog("哇，好吃的——！！", "伊露卡")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊露卡满眼星星的扑到巧克力圣代芭菲旁边，却并没有动手，只是像小狗般眼巴巴的看着安妮。")
	await novel_interface.show_text_only("安妮有些无奈的望向伸着懒腰打哈欠的我，转过头对伊露卡露出一个微笑。")
	novel_interface.show_character("iluka_uniform","hungry")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","happy",0.25)
	await novel_interface.show_dialog("可以开动了哦~", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("得到准许之后，伊露卡立刻抱起与体型不相称的巨大芭菲杯，心满意足的回到了自己座位上。")
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("你什么时候把她调教的这么好……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("这小家伙最近和我抢手柄的时候，都会手脚并用像章鱼一样糊在我脸上……")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("（等等，她是不是最近跟索娅学坏了！）","小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_uniform","smile")
	await novel_interface.show_dialog("看人家多乖，小怜怎么最近总是迷迷糊糊的。", "安妮")
	novel_interface.change_expression("worry")
	await novel_interface.show_dialog("虽然你上周拍广告是比较忙……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("啊，哈哈！\n这、这个季节比较容易犯困嘛……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我快速打断了安妮的话题——")
	await novel_interface.show_text_only("莉琉最近不知又做了什么交易，以“经纪人”的名义擅自替我接下了一家广告公司的单子。")
	await novel_interface.show_text_only("工作内容是给马萨达某种新型电池做形象代言……")
	novel_interface.show_character("ren_uniform","wail")
	await novel_interface.show_dialog("（之前给电池做代言的不都是粉红色的小兔子什么的吗？！）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("虽然贝阿特丽切认为由我替代小兔子非常合适，爱衣也认为我给电池代言很形象……")
	await novel_interface.show_text_only("——哪里形象了啊！？")
	novel_interface.show_character("anne_uniform","happy")
	await novel_interface.show_dialog("总之知道你最近辛苦啦，来这家店也是想搞劳你一下嘛。", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","gratified")
	await novel_interface.show_dialog("嗯嗯，这里环境确实挺舒服的……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我抱着抱枕缩在宽大的座椅上，下午柔和的阳光慵懒的从楼上树叶缝隙中洒进来。")
	await novel_interface.show_text_only("这家咖啡厅在酒店的下沉式露天广场，虽然在地下一层，却恰到好处的隔绝了外面的喧闹。")
	await novel_interface.show_text_only("据说老板是从萨蒙顿来的知名糕点师，很擅长在传统欧式甜点的基础上创新并做出惊艳的味道。")
	await novel_interface.show_text_only("在御樱川的学生中也有不低的知名度，不过可能主要是因为盛传这里的老板是个大帅哥吧。")
	novel_interface.show_character("ren_uniform","speechless")
	await novel_interface.show_dialog("（呵，那群小姑娘……）","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","smile",0.25)
	await novel_interface.show_dialog("来，小怜尝尝这个红丝绒蛋糕。", "安妮")
	novel_interface.character_light(0.35,"happy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("你不吃嘛？怎么只点了一杯牛奶啊~", "小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"relieve")
	await novel_interface.show_dialog("我没关系的，因为最近训练要控制热量——", "安妮")
	novel_interface.change_2nd_expression("panic")
	await novel_interface.show_dialog("而且……", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮不易察觉的微微低头扫了一眼胸前，然后快速切换了话题。")
	novel_interface.show_character("ren_uniform","happy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("anne_uniform","shy",0.25)
	await novel_interface.show_dialog("你喜欢什么可以再点啦，总之今天我请你。", "安妮")
	novel_interface.change_2nd_expression("worry")
	await novel_interface.show_dialog("看那套VR设备寄来好几天都没开箱就知道你有多忙了，我还想找哪天去探班……", "安妮")
	novel_interface.character_light(0.35,"perspire1")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("——不、不用！", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("说实话，一开始我还以为只是拍几张照片就能搞定的事。")
	await novel_interface.show_text_only("没想到光拍照就要换十几套衣服，而且每次都要像抽风一样对着摄影师快速切换各种动作和表情。")
	await novel_interface.show_text_only("专业模特半小时就能完成的出片量，我要从放学拍到半夜……全组的人都要默默陪着我加班。")
	novel_interface.show_character("ren_uniform","happy")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.character_light()
	novel_interface.show_2nd_character("anne_uniform","worry",0.25)
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("说来那套设备，最近似乎还挺流行的呢？","小怜")
	novel_interface.character_dark()
	novel_interface.character_2nd_light(0.35,"relieve")
	await novel_interface.show_dialog("嗯，我也听班上同学说过——", "安妮")
	await novel_interface.show_dialog("以前的虚拟现实设备需要肢体运动进行操作，95%\n以上的玩家是都是男性。", "安妮")
	await novel_interface.show_dialog("但新型号可以通过传感器读取运动神经信号，熟练之后躺在床上不动都能完成全部操作。", "安妮")
	novel_interface.change_2nd_expression("smile")
	await novel_interface.show_dialog("有好几个同学都买了呢。", "安妮")
	novel_interface.character_light(0.35,"smile")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("那还真不错啊……这样也没有那么严格的场地要求了吧？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我可没做过带着VR头盔膝盖磕到桌角然后蜷缩在地上痛到说不出话这种事，绝对没有！")
	await novel_interface.show_text_only("想到不堪回首的往事，我揉了揉还在隐隐作痛的膝盖，一位服务员向我们走了过来。")
	await novel_interface.show_dialog("您好，这位小姐——", "服务员")
	await novel_interface.show_dialog("因为刚才的圣代制作比较久，我们老板额外送您一份皇后刨冰，不过需要确认一下您的结账单号。", "服务员")
	novel_interface.show_character("anne_uniform","panic")
	await novel_interface.show_dialog("诶？稍等哈……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮掏出手机核对，我看着服务员托盘上那份皇后刨冰，超大号的高脚杯里高高堆起像雪山一样。")
	await novel_interface.show_text_only("“雪山”脚下还插着一只萌萌的小企鹅立牌。")
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("（那么大的刨冰谁吃得完啊……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("扭头看看伊露卡，不一会功夫她已经默默吃掉了大半杯芭菲。")
	novel_interface.show_character("ren_uniform","uneasy")
	await novel_interface.show_dialog("（我大概多虑了吧……）","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我突然感到手机震动，低头看到一条简讯，发信人是『未知号码』——")
	novel_interface.show_character("ren_uniform","stare")
	await novel_interface.show_dialog("“220284”","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("（没头没尾的，难道是什么东西的验证码？）","小怜")
	novel_interface.show_character("anne_uniform","worry")
	await novel_interface.show_dialog("奇怪，怎么一直连不上网……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("“——咚！！”")
	novel_interface.show_background("res://assets/images/bg/chaoscalculus/BG_Baizhu_Outdoorcafe_Powercut.png")
	await novel_interface.show_text_only("忽然，大厦内部传出一声闷响，随即店里的人群开始窸窸窣窣的骚动起来。")
	novel_interface.show_character("anne_uniform","unhappy")
	await novel_interface.show_dialog("这是……","安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","solemn")
	await novel_interface.show_dialog("这栋楼停电了？！", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","stare",0.25)
	await novel_interface.show_dialog("不对……你的手机还有信号吗？", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮站起身，发现远处有人走来走去的举着手机找信号。")
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("我的手机似乎也断网了……","小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","stare",0.25)
	await novel_interface.show_dialog("这种商业区至少被七八个信号站覆盖着，如果附近所有的信号站都离线了的话，就是说……","安妮")
	await novel_interface.hide_all_characters()
	novel_interface.change_music("res://assets/audio/music/Barrier Maze.mp3")
	await novel_interface.show_text_only("我和安妮对视，同时意识到了事态的严重。")
	await novel_interface.show_text_only("埃癸斯护盾展开后，从没发生过这种事——")
	novel_interface.show_character("ren_uniform","serious")
	await novel_interface.show_dialog("新丰洲市中心……整体停电了！？？","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我还在不知所措，远处突然传来一阵长啸，是轮胎与地面摩擦的尖锐声音。")
	await novel_interface.show_text_only("安妮下意识的走过来护住伊露卡，同时拉住了我的手。")
	await novel_interface.show_text_only("那个声音由远及近，整整持续了两三秒，并且完全没有停止的趋势。")
	novel_interface.show_character("ren_uniform","solemn")
	await novel_interface.show_dialog("等等……","小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("如果这么久都没能刹住的话，那么车身的重量……")
	await novel_interface.show_text_only("突然，一辆大卡车横着冲破了下沉式露天广场的护栏，呼啸着向我们的位置撞了过来！")
	await novel_interface.show_text_only("只一瞬间，我甚至还没来得及看清车身侧面紫色喷漆的图案——")
	await novel_interface.show_text_only("整个车柜就变为一个巨大的黑影，眨眼间拍到我身上……")
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("——！！！！")
	await novel_interface.show_text_only("……")
	await novel_interface.show_dialog("哈……","小怜")
	novel_interface.show_background("res://assets/images/bg/chaoscalculus/BG_Baizhu_RENbed.png")
	await novel_interface.show_dialog("是做梦啊……","小怜")
	await novel_interface.show_text_only("虽然能感到心脏猛烈的跳动，但足足用了好几秒才确认到自己的呼吸。")
	await novel_interface.show_text_only("我坐起身，看着窗外的夜景，心情久久难以平复。")
	await novel_interface.show_dialog("呜……\n刚两点，才睡了不到三小时啊……","小怜")
	await novel_interface.show_dialog("是因为这几天总被闪光灯闪的缘故吗？","小怜")
	await novel_interface.show_text_only("我揉了揉太阳穴，习惯性的去摸手机。")
	novel_interface.change_music("res://assets/audio/music/Deep Water.mp3")
	await novel_interface.show_text_only("然而屏幕上的画面却让我瞬间屏住呼吸彻底清醒—")
	await novel_interface.show_text_only("手机上只有一条简单的讯息。")
	await novel_interface.show_text_only("“220284”")
	await novel_interface.show_text_only("发信人—『未知号码』。")

	print("=== 混沌演算篇第1话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
