# chaoscalculus_ep02.gd - 混沌演算篇第2话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	chaoscalculus_ep02_script()

func play_script():
	pass

func chaoscalculus_ep02_script():
	novel_interface.change_music("res://assets/audio/music/Normal Stage.mp3")
	novel_interface.change_background("res://assets/images/bg/SID/hearingRoom.png")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("哈~~~困……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我揉了揉眼睛，有些不满的抱怨道。")
	novel_interface.show_character("ren_battle","sob")
	await novel_interface.show_dialog("我只是留言说刚做了奇怪的梦而已……也不至于连夜把我和安妮都接过来吧？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","worry")
	await novel_interface.show_dialog("而且咱们为什么在审讯室呀？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我打量着四周，回想起自己和安妮几个月前第一次被带到这里的情景。")
	novel_interface.show_character("liliu_uniform2","normal1")
	await novel_interface.show_dialog("哦？是不是很怀念啊~", "莉琉")
	await novel_interface.show_dialog("几个月前你们俩什么都不懂也就算了，今天再考考你们，看看这个房间有什么特点。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","bored")
	await novel_interface.show_dialog("嗯……加固的水泥墙面和地板，吸音性很强，而且墙体外面应该有全包裹的金属屏蔽层吧？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","normal1")
	await novel_interface.show_dialog("观察室的玻璃和灯具都是多层复合加固的，房间的气密性应该足以应对腐蚀性神经毒气……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("嗯……还有呢？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("果然越明显的东西越容易被忽略呐~", "爱衣")
	await novel_interface.show_text_only("爱衣似乎正忙着处理平板上的数据，头也不抬的插话道。")
	novel_interface.show_character("anne_normal","panic")
	await novel_interface.show_dialog("明显的东西……？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉轻轻叹了口气，继续问道。")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("这个房间，是什么颜色的？", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("墙面是灰绿色……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","stare")
	await novel_interface.show_dialog("被灯光照射的地方微微反射着淡蓝色的光芒……", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("难道说——")
	await novel_interface.show_text_only("我和安妮同时明白了过来，这个房间内壁的涂料中混入了那种能屏蔽模因类异质物效果的特殊金属。")
	novel_interface.show_character("anne_normal","panic")
	await novel_interface.show_dialog("……是什么模因类异质物失控了？", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("莉琉微微的点点头。")
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("一个多小时前，新丰洲城区内检测到了大范围的低频噪音信号。", "莉琉")
	await novel_interface.show_dialog("由于发射源一直在不停跳转，无法追踪地理位置。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("那到底……是什么东西？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.show_dialog("那种低频噪音的波形特征识别不久前才被添加到\nSID的预警系统里。", "莉琉")
	novel_interface.show_background("res://assets/images/bg/Baizhu/Snowstorm.png")
	await novel_interface.show_dialog("与人类快速眼动睡眠时脑电波的特性一致，但强度却能够高出几十万倍的——", "莉琉")
	await novel_interface.show_dialog("使你们在南极陷入梦境的那种信号……", "莉琉")
	novel_interface.change_background("res://assets/images/bg/SID/hearingRoom.png")
	novel_interface.show_character("ai","blush_think")
	await novel_interface.show_dialog("想想看，如果那东西在人口密集的新丰洲城区大范围爆发——", "爱衣")
	novel_interface.change_expression("blush_stare")
	await novel_interface.show_dialog("几百万人在睡梦中变成行尸走肉……", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("爱衣有些兴奋，像在讲鬼故事一样的语气让我和安妮不禁头皮发麻。")
	novel_interface.show_character("ai","blush_stare")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("liliu_uniform2","normal2",0.25)
	await novel_interface.show_dialog("还好这次的信号强度不大，而且只持续了90秒。", "莉琉")
	novel_interface.character_light(0.35,"blush_dizzy")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("简直就像是为了之后的大场面而进行的预演嘛——哎呀！", "爱衣")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("莉琉一记手刀，精准的敲在爱衣脑壳中间。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("咳咳，总之明白为什么这么晚也要把你们叫过来了吧。", "莉琉")
	await novel_interface.show_dialog("刚才爱衣确认过，『未知号码』的那条讯息不是通过合法的信号站发送的。", "莉琉")
	await novel_interface.show_dialog("那么目前唯一的线索就是小怜的梦了。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("在那个梦里预示了一个很严重的事件：新丰洲市区大规模停电。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","stare")
	await novel_interface.show_dialog("（难道不是车祸吗！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","worry")
	await novel_interface.show_dialog("停电……很严重吗？\n好像时不时就能遇到呢~", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("有吗？", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("那是安妮之前在其他城市的记忆，新丰洲是不会停电的——", "莉琉")
	await novel_interface.show_dialog("由于『埃癸斯』主机的耗电量极大且难以预测，电力系统一直都有是元老院以最高优先级来保障的。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("战争期间新丰洲的电网一直在进行强化和改造，各种容灾方案一开始还被列为机密……", "莉琉")
	await novel_interface.show_dialog("后来大多数方案索性都公开了，有些作为超级工程案例，在大学里都能单独开一学年的课。", "莉琉")
	await novel_interface.show_dialog("就算在埃癸斯护盾内引爆一颗电磁脉冲弹，供电系统也不会受到任何影响。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("也因为这样，全世界凡是有一定规模的机构，都愿意选择新丰洲作为自己的最终数据备份中心。", "莉琉")
	await novel_interface.hide_character()
	novel_interface.show_character("anne_normal","panic")
	await novel_interface.show_dialog("……这、这么厉害！", "安妮")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮惊讶的看着我，我心虚的假装点点头。")
	novel_interface.show_character("ren_battle","uneasy")
	await novel_interface.show_dialog("（我也是才知道！）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("而且元老院在其中究竟使用了多少异质物技术，连SID都不知道。", "莉琉")
	await novel_interface.show_dialog("即使动用异质物武器……也要动用XK级异质物才可能造成新丰洲停电。", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("而目前已知的XK级异质物全都无法做到这一点\n——", "莉琉")
	await novel_interface.show_dialog("你们明白有多严重了吗？", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我紧张的吞了吞口水。")
	await novel_interface.show_text_only("以前莉琉说过，《萨蒙顿协定》规定任何针对新丰洲电网的攻击，都被视为一级恐怖活动。")
	await novel_interface.show_text_only("其实真有人能实现这种攻击才是最恐怖的吧……")
	novel_interface.show_character("ai","wink")
	await novel_interface.show_dialog("啊，刚刚去咖啡厅老板和服务员家访的调查员全都有回复了！", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","upset")
	await novel_interface.show_dialog("（家……家访？）", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("ai","stare")
	await novel_interface.show_dialog("虽然小怜此前从没在网上查过那家店的信息，但咖啡厅的地理位置和装修都符合她梦境的描述。", "爱衣")
	await novel_interface.show_dialog("服务员的服装、红丝绒蛋糕和巧克力圣代芭菲的样子也都和小怜的描述一致。", "爱衣")
	novel_interface.change_expression("think")
	await novel_interface.show_dialog("但他们店里并没有“皇后刨冰”这种东西，也从来不会在甜品里放小动物的立牌…", "爱衣")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("诶，没有吗？\n我记得那个刨冰超有存在感的……", "小怜")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("anne_uniform","relieve",0.25)
	await novel_interface.show_dialog("而且我最近也不需要那么严格的控制饮食，本来都想好明天要去店里吃什么了。", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("安妮的脸颊有点泛红的说道。")
	novel_interface.show_character("anne_normal","relieve")
	await novel_interface.show_dialog("另外……", "安妮")
	novel_interface.change_expression("frustrate")
	await novel_interface.show_dialog("牛奶其实没什么作用，我很久之前就发现了……", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","perspire1")
	await novel_interface.show_dialog("什、什么作用？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("安妮低着头没有说话。")
	novel_interface.show_character("liliu_uniform2","normal2")
	await novel_interface.show_dialog("那么冷静分析一下——", "莉琉")
	await novel_interface.show_dialog("小怜的梦里，停电发生前绝大多数细节都与现实高度一致，却又存在几处明显的矛盾。", "莉琉")
	novel_interface.show_character("anne_normal","stare")
	await novel_interface.show_dialog("牛奶和皇后刨冰吗……", "安妮")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_battle","upset",0.25)
	await novel_interface.show_dialog("皇后，企鹅……南极？", "小怜")
	novel_interface.character_light(0.35,"panic")
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("白皇后基地？！", "安妮")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("几个月前，我们在南极的一处科研基地内找到了解决甲烷泄露危机关键道具。")
	await novel_interface.show_text_only("并在基地的最下层找到了沉睡了19年的白烛。")
	await novel_interface.show_text_only("加上刚才莉琉说，那种低频噪音与曾在南极接收到的信号有一样的特征……")
	novel_interface.show_character("anne_normal","panic")
	await novel_interface.show_dialog("如果是提示的话，也太绕圈子了吧？", "安妮")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_battle","worry")
	await novel_interface.show_dialog("牛奶……我记得是和白烛很要好的那个朋友。", "小怜")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("当时我从中控室找到的手表里听到过她的录音，但是连她长什么样子都不知道……", "小怜")
	await novel_interface.hide_character()
	novel_interface.show_character("liliu_uniform2","serious")
	await novel_interface.show_dialog("是那个代号『牛奶』的情报人员吗？", "莉琉")
	await novel_interface.show_dialog("小怜带出来的那块军用手表，确实是战前华云宫的军总三部配置给技术特勤人员的东西。", "莉琉")
	novel_interface.change_expression("normal1")
	await novel_interface.show_dialog("而且还被私下改造过……以当时的水准看，技术相当不错。", "莉琉")
	novel_interface.change_expression("normal2")
	await novel_interface.show_dialog("（不过一直以来运作白皇后基地的那个秘密机构如此注重保密性，每年都会清空中控室的资料……）", "莉琉")
	await novel_interface.show_dialog("（怎么可能单单留下一块用于破解安保系统的手表一直插在中控台上呢？）", "莉琉")
	novel_interface.change_expression("serious")
	await novel_interface.show_dialog("（难道……那是小怜无意中从梦境中带出来的？）", "莉琉")
	await novel_interface.hide_character()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("忽然，爱衣平板的扬声器传出的声音打断了莉琉的思考。")
	novel_interface.change_music("res://assets/audio/music/Everything's gonna be Okay.mp3")
	novel_interface.show_character("ai","dizzy")
	await novel_interface.show_dialog("啊，找到那段录音了~！", "爱衣")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("房间内的人都不禁安静下来，听着这温暖甜美的旋律，我慢慢闭上了眼睛——")
	await novel_interface.show_text_only("小时候，妈妈也很喜欢这首歌呢……")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("……")
	await novel_interface.show_dialog("“小~白~烛~”", "Record牛奶")
	await novel_interface.show_dialog("还有四个月就圣诞节了，有没有想好准备送给我的礼物呢？", "Record牛奶")
	await novel_interface.show_dialog("嘿嘿，这么早就开始考虑礼物的事情，好像有点坏心眼啊……", "Record牛奶")
	await novel_interface.show_dialog("不过，我真的超期待！", "Record牛奶")
	await novel_interface.show_dialog("……真是奇怪，明明只相处了一年，却感觉和你认识了几个世纪一样。", "Record牛奶")
	await novel_interface.show_dialog("你肯定又会害羞的说，太夸张了吧。", "Record牛奶")
	await novel_interface.show_dialog("毕竟在我面前，小白烛是完全没有秘密的嘛！", "Record牛奶")
	await novel_interface.show_dialog("嗯……还记得我们第一次相遇的时候，你告诉我那个教授保险箱的密码，是一组亲和数。", "Record牛奶")
	await novel_interface.show_dialog("220，284，我到现在都还记得。", "Record牛奶")
	await novel_interface.show_dialog("那是我第一次了解到这种密码构成方式呢~", "Record牛奶")

	print("=== 混沌演算篇第2话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
