# deathconfession_ep01.gd - 死亡告白篇第1话
extends Node2D

@onready var novel_interface = $NovelInterface

func _ready():
	await get_tree().process_frame
	deathconfession_ep01_script()

func play_script():
	pass

func deathconfession_ep01_script():
	novel_interface.change_background("res://assets/images/bg/DeathConfession/BG_ECT.png")
	await novel_interface.show_text_only("几十年前，医生在研究针对抑郁症的疗法时，偶然发现以特定的频率电击可以消除患者的记忆。")
	await novel_interface.show_text_only("高强度正弦电流的刺激，会打断大脑扣带皮层的蛋白质合成，从而改变神经传递系统。")
	await novel_interface.show_text_only("被消除记忆的人会失去所有的『经历记忆』：包括父母、爱人、自己的过往和身份等等。")
	await novel_interface.show_text_only("但他们仍会保留已习得的技能：比如说话、走路、甚至会记得如何驾驶汽车和使用武器。")
	await novel_interface.show_text_only("如果某天你从一张陌生的床上醒来，忘记了一切。")
	await novel_interface.show_text_only("一群陌生人围在你身边，声称自己是你最重要的亲人或朋友，而其他人都在欺骗你——")
	await novel_interface.hide_background()
	await novel_interface.show_text_only("你会选择相信谁？")
	await novel_interface.show_text_only("……")
	novel_interface.show_background("res://assets/images/bg/DeathConfession/BG_NewMoridas_apartment.png")
	novel_interface.change_music("res://assets/audio/music/Sunset.mp3")
	await novel_interface.show_text_only("第二学园都市——纽摩利达斯。")
	await novel_interface.show_text_only("某高层公寓内，一个女孩正坐在地毯上，透过高脚杯中的红酒眺望窗外的夜景。")
	await novel_interface.show_text_only("灯火辉煌的大都会被液体滤镜染成一片血红，随着酒杯的微微摇晃，不断被拉伸、扭曲、变形……")
	await novel_interface.show_text_only("女孩出神的看了一会，随后把酒杯放在地板上，哼着歌拿起一根像马克笔似的东西开始写字。")
	await novel_interface.show_text_only("忽然她的手机响了起来，女孩立刻戴上耳机，清了清嗓子，随后按下接听键——")
	await novel_interface.show_dialog("对不起，您拨打的用户不在服务区，请稍后再拨。", "女孩")
	await novel_interface.show_dialog("Sorry， The number you dialed is out of…", "女孩")
	await novel_interface.show_dialog("伊娜拉，别闹了！", "男性的声音")
	await novel_interface.show_text_only("电话中一个低沉的男性声音打断了女孩的恶作剧。")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("嘁，没劲……", "伊娜拉")
	await novel_interface.show_dialog("什么事啊，我这周很忙哦~", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("纽摩利达斯时装周？", "男性的声音")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("哟？还挺懂的嘛，是不是你老婆她……", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("不谈论家人，这是规矩。", "男性的声音")
	await novel_interface.show_text_only("男人斩钉截铁的打断对话。")
	await novel_interface.show_text_only("伊娜拉翻了翻白眼，接着朝空气做了个鬼脸。")
	await novel_interface.show_dialog("你听好，我刚得到情报，由于你上次的过火行为，开普敦警方已经向联合议会提出援助调查的申请。", "男性的声音")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("开普敦？联合议会连那种地方都管啊~", "伊娜拉")
	await novel_interface.show_dialog("而且……你怎么知道“那个”是人家做的呀？", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊娜拉故意用小女孩的声音和口吻，一幅天真的语气问道")
	await novel_interface.show_dialog("除了你还有谁会接那种送命又没多少报酬的工作，而且有必要做的那么夸张吗？", "男性的声音")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("很、很夸张吗？", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊娜拉用很意外的语气反问道。")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("把暴君的脑袋挂在教堂的尖顶上难道不是传统吗？", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("传统个屁！！", "男性的声音")
	await novel_interface.show_dialog("现在大众都喜欢看这种有政治隐喻的东西，你知道这事儿上了多少媒体的头条吗！？", "男性的声音")
	await novel_interface.show_text_only("电话另一头的男性有些控制不住自己情绪的嚷起\n来，但很快再次压低声音，并迅速调整呼吸。")
	await novel_interface.show_dialog("总而言之，现在联合议会怀疑这件事涉及到异质物滥用，已经派遣了特别调查员。", "男性的声音")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("异质物？噗哈哈哈哈~~！", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊娜拉大笑着锤着地板。")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("果然那群家伙只是关心异质物而已，那他们要失望了，因为我完全没有用什么异质物啊~", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("那你是怎么……\n算了，我还是不知道的好。", "男性的声音")
	await novel_interface.show_dialog("我提醒你，据说这次的调查员是个死脑筋，就算与异质物无关的事件也都会查到底。", "男性的声音")
	await novel_interface.show_dialog("那人的资料我发给你了，你这一阵最好低调点。", "男性的声音")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("嗯嗯，低调低调，特别低调行了吧？", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊娜拉心不在焉的附和着，同时加快了手里写字的速度。")
	await novel_interface.show_dialog("下个月我们和萨蒙顿做稀土贸易谈判，到时候还有工作给你。", "男性的声音")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("嘿嘿，是你们自己不方便还是做不来啊？", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("电话另一头沉默不语。")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("反正只要按时付账就行，我可不会给『帕兰蒂尔』打折哦！", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊娜拉拿起酒杯做了个干杯的姿势，喝了一口。")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("噗呸，什么啊，还以为这酒有多好喝呢……", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("你什么时候开始喝酒了？", "男性的声音")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("刚刚开始——\n我找到一瓶09年的玛歌~", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("什么！？", "男性的声音")
	await novel_interface.show_text_only("电话另一头的声音又激动起来。")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("我就是上网搜了一下，发现酒柜里就这瓶最贵，你说这么酸的东西凭什么卖好几万啊？", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("……酒柜？\n等等！你不会正在“工作”吧？", "男性的声音")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("哼哼，你猜~", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊娜拉说话的尾音故意扬起，右手“马克笔”的笔锋顺势上挑画了个勾，发出『嗞』的一声。")
	await novel_interface.show_dialog("什么声音……你到底干嘛呢？", "男性的声音")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("纹身~", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("什么？！", "男性的声音")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("没有啦，总之多谢提醒咯。", "伊娜拉")
	await novel_interface.show_dialog("还有你平时少喝点酒，一点都不好喝，而且你那个血压难道不怕便秘的时候脑血管忽然爆……", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("没等少女念叨完，对方就挂断了电话。")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("老东西，就知道说我。", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("伊娜拉站起身，关掉了“马克笔”上的开关，接着从挎包里拿出一节新电池换好。")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("来，小猪猪，翻面咯~", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("她看着地毯上自己的“画布”：一个被扒得只剩内裤，塞着口球，身材有些发福的中年男性白人。")
	await novel_interface.show_text_only("男人此时已经失去意识，胸口、腹部、手臂和大腿都被纹上了字，胸口和腹部的字还是反写的。")
	await novel_interface.show_text_only("伊娜拉踩着男人的跨用力一蹬，将那个肥胖的身躯侧翻了90度，卡在沙发边缘。")
	await novel_interface.show_text_only("但少女并没有立刻继续“创作”，而是目不转睛的盯着自己手机的屏幕——")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("调查员叫……九月？\n好奇怪的名字。", "伊娜拉")
	await novel_interface.show_dialog("啊，是女孩子啊？\n嘿嘿……", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.hide_background()
	await novel_interface.stop_music()
	await novel_interface.show_text_only("……")
	await novel_interface.show_text_only("几天后，新丰洲市。")
	novel_interface.change_music("res://assets/audio/music/Like A Girl.mp3")
	novel_interface.show_background("res://assets/images/bg/other/BG_City_street3.png")
	await novel_interface.show_dialog("几日前，发生在第二学园都市纽摩利达斯的举世瞩目的枪击案有了最新进展", "新闻")
	await novel_interface.show_dialog("军工生产商格鲁门工业的主席塔尔斯·科赫被认为是第一目标，被击中三枪当场死亡。", "新闻")
	await novel_interface.show_dialog("嫌犯为一名会计师，据其声称自己曾是科赫的同性恋人。", "新闻")
	await novel_interface.show_dialog("嫌犯称对方在分手后袭击自己导致大脑受损，丧失了以前的记忆，他这么做是为了复仇。", "新闻")
	await novel_interface.show_dialog("科赫的妻子表示嫌犯的指控纯属无稽之谈，随后警方透露嫌犯身上有大量纹身。", "新闻")
	await novel_interface.show_dialog("纹身内容指出格鲁门工业与西亚和非洲存在大量地下交易，帕兰蒂尔已宣布接管此次调查……", "新闻")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("这个新闻……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("大脑受损，纹身……不会是那个电影的影迷吧")
	novel_interface.show_character("ren_uniform","wry_smile")
	await novel_interface.show_dialog("（不对不对，同性恋人和妻子又是什么鬼！）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我收起了手机，百无聊赖的倚着路边的栏杆，看着来来往往的行人和车辆。")
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("唔……下周就要考试了啊……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("每次大考之前，我都会有一段放空大脑的时间——")
	await novel_interface.show_text_only("比如想象着自己不过是由几十万亿个细胞组成的有机体，所谓的“自我”只是一种错觉。")
	await novel_interface.show_text_only("构成我身体的所有原子在几十年前曾散布在地球各个角落，一百年后也会尘归尘土归土。")
	await novel_interface.show_text_only("所以说考试什么的，在如此广袤浩瀚的宇宙中，在地球几十亿年的历史里，还有什么意义吗？")
	novel_interface.show_character("ren_uniform","sob")
	await novel_interface.show_dialog("有意义啊！！！", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("考砸了的话会被莉琉弄死啊！！！")
	await novel_interface.show_text_only("我两手抓着脑袋用力晃了晃，试图通过想象将考试化为虚无的努力很快宣告失败。")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("嘿！小可爱~", "伊娜拉")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("一个姐姐从我身后气喘吁吁的跑过来，大声叫住了我。")
	novel_interface.show_character("inara","normal")
	novel_interface.character_move_left(-0.25)
	novel_interface.show_2nd_character("ren_uniform","upset",0.25)
	await novel_interface.show_dialog("诶？", "小怜")
	novel_interface.character_light()
	novel_interface.character_2nd_dark()
	await novel_interface.show_dialog("啊啊抱歉，是不是吓到你了~", "伊娜拉")
	await novel_interface.show_dialog("我是时尚杂志的编辑，刚刚在马路对面看到你就赶忙跑过来，想给你拍张照片。", "伊娜拉")
	await novel_interface.show_dialog("因为你有一种……嗯……未经尘世的天真感嘛！\n现在的读者最喜欢你这种类型了！", "伊娜拉")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("她一边说一边笑着对我抛了个媚眼。")
	novel_interface.show_character("inara","normal")
	novel_interface.character_move_left(-0.25,0)
	novel_interface.show_2nd_character("ren_uniform","shy",0.25)
	await novel_interface.show_dialog("啊……\n是、是吗？", "小怜")
	await novel_interface.hide_all_characters()
	await novel_interface.show_text_only("我有些不好意思的捋了捋头发，这个打扮帅气的姐姐拍了拍我，叫我别害羞。")
	await novel_interface.show_text_only("随后她掏出手机，不由分说的把我拉到一旁，自己端着手机退到路边商店的招牌后面。")
	novel_interface.show_character("inara","normal")
	await novel_interface.show_dialog("来来来，看着我这边哦~", "伊娜拉")
	await novel_interface.hide_character()
	novel_interface.show_character("ren_uniform","perspire1")
	await novel_interface.show_dialog("（这、这难道就是杂志上的“街拍”吗？）\n（可我今天穿的只是校服啊……）", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("我还在犹豫要不要比个“V”的手势，身后忽然跑过去几个穿着西装的男人差点把我撞倒。")
	await novel_interface.show_text_only("那几个人一路风风火火的跑出去几十米远，其中一个盯着手机的人发现不对，又折返回来。")
	novel_interface.show_character("ren_uniform","worry")
	await novel_interface.show_dialog("什么人啊！真过分……", "小怜")
	novel_interface.change_expression("upset")
	await novel_interface.show_dialog("欸？那个姐姐呢？", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_text_only("刚才的女生所在的招牌后面已经没了人影，我上前几步左右观望，她就好像忽然蒸发了一样。")
	novel_interface.show_character("ren_uniform","upset")
	await novel_interface.show_dialog("奇怪……", "小怜")
	await novel_interface.hide_character()
	await novel_interface.show_dialog("喂，小姑娘——", "穿西装的男性")
	await novel_interface.show_text_only("此时，那几个撞到我的男人已经整齐的围在了我身后。")
	await novel_interface.show_text_only("领头的家伙右手拿着手机，左手从我校服的袖子上摘下来一个药片大小的金属颗粒。")
	await novel_interface.show_text_only("他的手机立刻发出急促的“嘟嘟嘟”的声音……")
	await novel_interface.show_dialog("你刚才，有没有遇到什么人？", "穿西装的男性")

	print("=== 死亡告白篇第1话结束 ===")

	# 调用剧情结束函数
	await novel_interface.end_story_episode(0.5)
